import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.95.0";

const ENGINE="watchdog-analyst-scenario-v1";
const TOOL_VERSION="watchdog-analyst-scenario-tool-v1";
const PLAN_RANK:Record<string,number>={standard:0,agent:1,pro:2,pro_plus:3,teams:4,developer:5};
const DAILY_LIMIT:Record<string,number>={pro:75,pro_plus:300,teams:1500,developer:10000};
type O=Record<string,any>;
const clean=(v:unknown,n=1800)=>String(v??"").replace(/[<>]/g,"").trim().slice(0,n);
const env=(j:string,l:string)=>{const raw=Deno.env.get(j)||"";if(raw){try{const x=JSON.parse(raw);if(x?.default)return String(x.default)}catch{}}return Deno.env.get(l)||""};
function origin(req:Request){const o=req.headers.get("origin")||"";if(["https://njpropertytaxrelief.com","https://www.njpropertytaxrelief.com","http://localhost:3000","http://127.0.0.1:3000"].includes(o))return o;if(/^https:\/\/njtaxrelief(?:-git)?-[a-z0-9-]+-johnscafides-projects\.vercel\.app$/i.test(o))return o;return"https://njpropertytaxrelief.com"}
const cors=(r:Request)=>({"Access-Control-Allow-Origin":origin(r),"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"});
const out=(r:Request,s:number,p:unknown)=>new Response(JSON.stringify(p),{status:s,headers:{...cors(r),"Content-Type":"application/json","Cache-Control":"private, no-store"}});
function usd(v:unknown){const n=Number(v);return Number.isFinite(n)?n.toLocaleString("en-US",{style:"currency",currency:"USD",minimumFractionDigits:2,maximumFractionDigits:2}):"not available"}
function pct(v:unknown){const n=Number(v);return Number.isFinite(n)?`${n>=0?"+":""}${n.toFixed(2).replace(/\.00$/,'')}%`:"not provided"}
function deterministicScenario(data:O){
  if(data?.status==="needs_assumptions"){
    const missing=Array.isArray(data.missing_assumptions)?data.missing_assumptions.map((x:unknown)=>clean(x,120)):[];
    return{conclusion:"Watchdog can run this property-tax scenario, but required financial assumptions are still missing.",evidence:[],missing_evidence:missing.map((x:string)=>`Missing explicit assumption: ${x}.`),caveats:["Watchdog did not invent or default any missing financial assumption.","State the missing percentage explicitly, or say it is unchanged/flat/no change to use 0%."],suggested_actions:[],sources:[],scenario_status:"needs_assumptions",parser_version:data?.parser_version||null};
  }
  const scenario=data?.scenario||{},parsed=data?.parsed||{},series=Array.isArray(scenario?.series)?scenario.series:[],last=series[series.length-1]||null,a=parsed?.assumptions||{},evidence:string[]=[];
  evidence.push(`Current annual property tax: ${usd(scenario?.current?.annual_tax)}.`);
  evidence.push(`Explicit assumptions: municipal levy ${pct(a.levy_growth_pct)}, property assessment ${pct(a.property_assessment_growth_pct)}, municipal tax base ${pct(a.municipal_tax_base_growth_pct)}.`);
  for(const row of series.slice(0,5))evidence.push(`Year ${Number(row.year||0)} scenario: ${usd(row.projected_tax)} (${pct(row.change_pct)} from current).`);
  const conflicts=Array.isArray(scenario?.input_conflicts)?scenario.input_conflicts:[];
  for(const c of conflicts.slice(0,3))evidence.push(`${clean(c.marker_id||"Scenario input",120)} had competing governed observations; Watchdog used canonical ${usd(c.canonical_value)} from ${clean(c.canonical_source||"the highest-authority governed source",180)} at authority ${Number(c.authority_rank||0)}/100.`);
  const caveats=Array.isArray(scenario?.caveats)?scenario.caveats.map((x:unknown)=>clean(x,500)):[];
  return{conclusion:last?`Under the assumptions you stated, the year ${Number(last.year||series.length)} property-tax scenario is ${usd(last.projected_tax)}. This is a deterministic scenario, not a forecast.`:"Watchdog computed the requested deterministic property-tax scenario.",evidence,missing_evidence:[],caveats,suggested_actions:[],sources:[],scenario_status:"complete",parser_version:data?.parser_version||null,scenario_lineage:{engine_version:scenario?.engine_version||null,formula_version:scenario?.formula_version||null,semantic_contract_version:scenario?.lineage?.semantic_contract_version||null,semantic_snapshot_hash:scenario?.lineage?.semantic_snapshot_hash||null,assumption_hash:scenario?.lineage?.assumption_hash||null,input_conflicts:conflicts}};
}

Deno.serve(async(req:Request)=>{
  if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});if(req.method!=="POST")return out(req,405,{error:"POST required"});
  const auth=req.headers.get("authorization")||"";if(!auth.startsWith("Bearer "))return out(req,401,{error:"Sign in required"});
  const url=Deno.env.get("SUPABASE_URL")||"",pub=env("SUPABASE_PUBLISHABLE_KEYS","SUPABASE_ANON_KEY"),secret=env("SUPABASE_SECRET_KEYS","SUPABASE_SERVICE_ROLE_KEY");if(!url||!pub||!secret)return out(req,503,{error:"Analyst scenario configuration incomplete"});
  const uc=createClient(url,pub,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}}),admin=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}}),{data:who}=await uc.auth.getUser(),user=who?.user;if(!user)return out(req,401,{error:"Session invalid"});
  let body:O={};try{body=await req.json()}catch{return out(req,400,{error:"Invalid JSON"})}const prompt=clean(body.prompt),pin=clean(body.pams_pin,120),context=body?.context&&typeof body.context==="object"&&!Array.isArray(body.context)?body.context:{};if(!prompt)return out(req,400,{error:"prompt required"});if(!pin)return out(req,400,{error:"Select exactly one governed property before running a property-tax scenario."});
  const [{data:ent},{data:profile},{data:promptRows}]=await Promise.all([admin.from("account_entitlements").select("plan_tier,profession").eq("user_id",user.id).maybeSingle(),admin.from("profiles").select("account_role").eq("id",user.id).maybeSingle(),admin.from("intelligence_prompt_versions").select("prompt_key,version").eq("prompt_key","watchdog_analyst").in("status",["preview","live"]).order("version",{ascending:false}).limit(1)]);
  const plan=String(profile?.account_role||"")==="developer"?"developer":String(ent?.plan_tier||"standard");if((PLAN_RANK[plan]??0)<PLAN_RANK.pro)return out(req,403,{error:"Pro plan required",minimum_plan:"pro"});const profession=clean(ent?.profession||context?.profession||"general",80)||"general";
  const since=new Date(Date.now()-86400000).toISOString(),{count}=await admin.from("intelligence_usage_events").select("id",{count:"exact",head:true}).eq("user_id",user.id).eq("event_type","analyst_request").gte("created_at",since);if(Number(count||0)>=(DAILY_LIMIT[plan]||DAILY_LIMIT.pro))return out(req,429,{error:"Watchdog Analyst preview usage limit reached for this rolling 24-hour window."});
  const promptRow=Array.isArray(promptRows)?promptRows[0]:null;let sessionId=clean(body.session_id,80),session:O|null=null;
  if(sessionId){const q=await admin.from("intelligence_analyst_sessions").select("id,user_id,context,profession").eq("id",sessionId).eq("user_id",user.id).maybeSingle();if(q.error)return out(req,503,{error:"Could not read Analyst scenario session"});session=q.data;if(!session)return out(req,404,{error:"Analyst scenario session not found"})}
  else{const q=await admin.from("intelligence_analyst_sessions").insert({user_id:user.id,profession,context:{...context,pams_pins:[pin],surface:context?.surface||"data_workbench",scenario_bridge:true},title:prompt.slice(0,90)}).select("id,context,profession").single();if(q.error||!q.data)return out(req,503,{error:"Could not start Analyst scenario session"});session=q.data;sessionId=String(q.data.id)}
  const userMessage=await admin.from("intelligence_analyst_messages").insert({session_id:sessionId,user_id:user.id,role:"user",content:{text:prompt},prompt_key:promptRow?.prompt_key||"watchdog_analyst",prompt_version:promptRow?.version||null,tool_contract_version:TOOL_VERSION,status:"complete"}).select("id").single();if(userMessage.error)return out(req,503,{error:"Could not record Analyst scenario request"});
  const started=Date.now();const call=await fetch(`${url}/functions/v1/intelligence-scenario-from-prompt`,{method:"POST",headers:{Authorization:auth,apikey:pub,"Content-Type":"application/json"},body:JSON.stringify({pams_pin:pin,prompt})}),data=await call.json().catch(()=>({}));
  const accepted=call.ok||call.status===409&&data?.status==="needs_assumptions";const response=accepted?deterministicScenario(data):{conclusion:"Watchdog could not complete that property-tax scenario.",evidence:[],missing_evidence:[clean(data?.error||`Scenario adapter returned ${call.status}`,400)],caveats:["No scenario figure was generated from a failed deterministic tool call."],suggested_actions:[],sources:[],scenario_status:"failed"};const status=accepted?"complete":"failed",latency=Date.now()-started;
  const toolCall=await admin.from("intelligence_tool_calls").insert({session_id:sessionId,message_id:userMessage.data?.id||null,user_id:user.id,tool_name:"run_property_tax_scenario",tool_version:TOOL_VERSION,arguments:{pams_pin:pin,parser_version:data?.parser_version||null,years:data?.parsed?.years||null,missing_assumptions:data?.missing_assumptions||[],surface:context?.surface||"data_workbench"},result_summary:{status:data?.status||"failed",scenario_engine:data?.scenario?.engine_version||null,formula_version:data?.scenario?.formula_version||null,semantic_contract:data?.scenario?.lineage?.semantic_contract_version||null,semantic_snapshot_hash:data?.scenario?.lineage?.semantic_snapshot_hash||null,assumption_hash:data?.scenario?.lineage?.assumption_hash||null,input_conflict_count:Array.isArray(data?.scenario?.input_conflicts)?data.scenario.input_conflicts.length:0},status,duration_ms:latency}).select("id").single();
  await admin.from("intelligence_analyst_messages").insert({session_id:sessionId,user_id:user.id,role:"assistant",content:response,prompt_key:promptRow?.prompt_key||"watchdog_analyst",prompt_version:promptRow?.version||null,tool_contract_version:TOOL_VERSION,status});
  await admin.from("intelligence_usage_events").insert({user_id:user.id,plan_tier:plan,event_type:"analyst_request",request_units:1,latency_ms:latency,metadata:{status,tool:"run_property_tax_scenario",tool_version:TOOL_VERSION,engine_version:ENGINE,scenario_status:data?.status||"failed",parser_version:data?.parser_version||null,formula_version:data?.scenario?.formula_version||null}});
  await admin.from("intelligence_analyst_sessions").update({context:{...(session?.context||{}),...context,pams_pins:[pin],surface:context?.surface||"data_workbench",scenario_bridge:true,last_scenario:{status:data?.status||"failed",parser_version:data?.parser_version||null,formula_version:data?.scenario?.formula_version||null,semantic_snapshot_hash:data?.scenario?.lineage?.semantic_snapshot_hash||null,assumption_hash:data?.scenario?.lineage?.assumption_hash||null}},updated_at:new Date().toISOString()}).eq("id",sessionId).eq("user_id",user.id);
  return out(req,200,{ok:accepted,session_id:sessionId,status,provider_status:"not_called",provider:null,model:null,prompt:{key:promptRow?.prompt_key||"watchdog_analyst",version:promptRow?.version||null},tool:{name:"run_property_tax_scenario",version:TOOL_VERSION,id:toolCall.data?.id||null},response});
});
