import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.95.0";
type Obj=Record<string,any>;
const ORIGINS=new Set(["https://njpropertytaxrelief.com","https://www.njpropertytaxrelief.com","http://localhost:3000","http://127.0.0.1:3000"]);
const NJ="https://services2.arcgis.com/XVOqAjTOJ5P6ngMu/arcgis/rest/services/Parcels_Composite_NJ_WM/FeatureServer/0/query";
function namedEnv(jsonName:string,legacyName:string){const raw=Deno.env.get(jsonName)||"";if(raw){try{const x=JSON.parse(raw);if(x?.default)return String(x.default)}catch{}}return Deno.env.get(legacyName)||"";}
function clean(v:unknown,max=500){return String(v??"").replace(/[\u0000-\u001f<>]/g,"").trim().slice(0,max);}
function cors(req:Request){const o=req.headers.get("origin")||"";const allow=ORIGINS.has(o)||/^https:\/\/[a-z0-9-]+\.vercel\.app$/i.test(o)?o:"https://njpropertytaxrelief.com";return{"Access-Control-Allow-Origin":allow,"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"};}
function out(req:Request,status:number,p:unknown){return new Response(JSON.stringify(p),{status,headers:{...cors(req),"Content-Type":"application/json","Cache-Control":"private, no-store"}});}
function pRank(p:string){return({standard:0,agent:1,pro:2,pro_plus:3,teams:4,developer:5} as Record<string,number>)[p]??0;}
function escSql(v:string){return v.replace(/'/g,"''");}
async function parcelByPin(pin:string){const p=new URLSearchParams({f:"json",where:`PAMS_PIN='${escSql(pin)}'`,outFields:"PAMS_PIN,PROP_LOC,MUN_NAME,COUNTY,ZIP5",returnGeometry:"false",resultRecordCount:"2"});const r=await fetch(`${NJ}?${p.toString()}`,{headers:{Accept:"application/json"}});if(!r.ok)throw new Error("parcel_lookup_failed");const j=await r.json(),a=j?.features?.[0]?.attributes;return a&&clean(a.PAMS_PIN,120)?a:null;}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});if(req.method!=="POST")return out(req,405,{error:"POST required"});const origin=req.headers.get("origin")||"";if(origin&&!ORIGINS.has(origin)&&!/^https:\/\/[a-z0-9-]+\.vercel\.app$/i.test(origin))return out(req,403,{error:"Origin not allowed"});const auth=req.headers.get("authorization")||"";if(!auth.startsWith("Bearer "))return out(req,401,{error:"Sign in required"});const url=Deno.env.get("SUPABASE_URL")||"",pub=namedEnv("SUPABASE_PUBLISHABLE_KEYS","SUPABASE_ANON_KEY"),secret=namedEnv("SUPABASE_SECRET_KEYS","SUPABASE_SERVICE_ROLE_KEY");if(!url||!pub||!secret)return out(req,503,{error:"Resolver configuration incomplete"});const userDb=createClient(url,pub,{global:{headers:{Authorization:auth}},auth:{persistSession:false}}),admin=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});const {data:authData}=await userDb.auth.getUser(),user=authData?.user;if(!user)return out(req,401,{error:"Session invalid"});const {data:planData,error:planError}=await admin.rpc("watchdog_effective_plan",{p_user_id:user.id});if(planError)return out(req,503,{error:"Could not resolve Watchdog plan"});const plan=clean(planData,40)||"standard";if(pRank(plan)<4)return out(req,403,{error:"Verified CRM property resolution requires Teams"});let body:Obj={};try{body=await req.json()}catch{return out(req,400,{error:"Invalid JSON"})}const action=clean(body.action,80);
  if(action==="status"){
    const {data:states}=await admin.from("integration_crm_resolution_state").select("detail_status,candidate_count").eq("user_id",user.id),{data:links}=await admin.from("integration_crm_property_links").select("status,link_method").eq("user_id",user.id);const counts:Record<string,number>={};for(const s of states||[])counts[s.detail_status]=(counts[s.detail_status]||0)+1;const lc:Record<string,number>={candidate:0,verified:0,rejected:0};for(const l of links||[])if(lc[l.status]!=null)lc[l.status]++;return out(req,200,{ok:true,plan,resolution:{total:(states||[]).length,counts},links:lc,policy:{auto_verified_methods:["provider_property_ref"],address_matches:"candidate_only",candidate_rules:["exact_normalized_street_and_zip","njogis_zip_enriched_exact_street_spatial_parcel"],name_matching:false,ownership_inference:false}});
  }
  if(action==="candidates.list"){
    const limit=Math.min(Math.max(Number(body.limit||50),1),100);const {data:links,error}=await admin.from("integration_crm_property_links").select("id,crm_context_id,pams_pin,crm_property_address,candidate_property_address,candidate_municipality,confidence,candidate_count,evidence,created_at").eq("user_id",user.id).eq("status","candidate").order("created_at",{ascending:true}).limit(limit);if(error)return out(req,503,{error:"Could not load candidates"});const ids=[...new Set((links||[]).map((x:Obj)=>x.crm_context_id))];let contexts:Obj[]=[];if(ids.length){const q=await admin.from("integration_crm_context").select("id,contact_name,lead_stage,relationship,property_address,context").eq("user_id",user.id).in("id",ids);contexts=q.data||[];}const cm=new Map(contexts.map((x:Obj)=>[x.id,x]));return out(req,200,{ok:true,candidates:(links||[]).map((l:Obj)=>{const c=cm.get(l.crm_context_id)||{};return{id:l.id,crm_context_id:l.crm_context_id,contact_name:c.contact_name||"CRM contact",lead_stage:c.lead_stage||null,relationship:c.relationship||null,crm_address:c.property_address||l.crm_property_address||null,pams_pin:l.pams_pin,property_address:l.candidate_property_address||null,municipality:l.candidate_municipality||null,confidence:Number(l.confidence||0),candidate_count:Number(l.candidate_count||1),evidence:{address_source:l.evidence?.address_source||null,match_policy:l.evidence?.match_policy||null,zip_source:l.evidence?.zip_source||null,geocode_score:l.evidence?.geocode_score??null,parcel_source:l.evidence?.parcel_source||null,match_tier:l.evidence?.match_tier||null,name_match_used:false,ownership_inferred:false}};}),policy:{verification_required:true}});
  }
  if(action==="candidate.verify"||action==="candidate.reject"){
    const id=clean(body.link_id,80),note=clean(body.note,300);if(!id)return out(req,400,{error:"link_id is required"});const {data:link}=await admin.from("integration_crm_property_links").select("*").eq("id",id).eq("user_id",user.id).maybeSingle();if(!link||link.status!=="candidate")return out(req,404,{error:"Candidate not found"});const now=new Date().toISOString(),verify=action.endsWith("verify"),evidence={...(link.evidence||{}),user_reviewed:true,user_decision:verify?"verified":"rejected",user_reviewed_at:now,reviewer_user_id:user.id,match_tier:verify?"human_verified_gold":"human_rejected_gold",reviewed_match_policy:link.evidence?.match_policy||link.link_method};const patch:Obj={status:verify?"verified":"rejected",link_method:verify?"verified_address":link.link_method,confidence:verify?1:link.confidence,reviewed_by_user_id:user.id,reviewed_at:now,review_note:note||null,evidence,updated_at:now};if(verify)patch.verified_at=now;await admin.from("integration_crm_property_links").update(patch).eq("id",id).eq("user_id",user.id);const {count:remaining}=await admin.from("integration_crm_property_links").select("id",{count:"exact",head:true}).eq("user_id",user.id).eq("crm_context_id",link.crm_context_id).eq("status","candidate");if(Number(remaining||0)===0)await admin.from("integration_crm_resolution_state").update({detail_status:"enriched",candidate_count:0,updated_at:now}).eq("crm_context_id",link.crm_context_id).eq("user_id",user.id);await admin.from("integration_audit_log").insert({user_id:user.id,connection_id:link.connection_id,action:verify?"crm.property_link.verified":"crm.property_link.rejected",actor:"user",details:{link_id:id,crm_context_id:link.crm_context_id,pams_pin:link.pams_pin,method:verify?"verified_address":link.link_method,match_policy:link.evidence?.match_policy||null,match_tier:verify?"human_verified_gold":"human_rejected_gold",name_match_used:false,ownership_inferred:false}});return out(req,200,{ok:true,status:verify?"verified":"rejected",link_id:id});
  }
  if(action==="manual.verify"){
    const crmId=clean(body.crm_context_id,80),pin=clean(body.pams_pin,120),note=clean(body.note,300);if(!crmId||!/^\d{4}_.+/.test(pin))return out(req,400,{error:"Valid crm_context_id and PAMS pin are required"});const {data:ctx}=await admin.from("integration_crm_context").select("id,user_id,connection_id,property_address").eq("id",crmId).eq("user_id",user.id).maybeSingle();if(!ctx)return out(req,404,{error:"CRM context not found"});const parcel=await parcelByPin(pin);if(!parcel)return out(req,404,{error:"Governed parcel not found"});const now=new Date().toISOString(),evidence={source:"user_verified_pams",parcel_source:"NJOGIS Parcels / MOD-IV Composite",user_reviewed:true,user_reviewed_at:now,reviewer_user_id:user.id,match_tier:"human_verified_manual",name_match_used:false,ownership_inferred:false};const rowToUpsert={user_id:user.id,connection_id:ctx.connection_id,crm_context_id:ctx.id,pams_pin:pin,crm_property_address:ctx.property_address||null,candidate_property_address:clean(parcel.PROP_LOC,220)||null,candidate_municipality:clean(parcel.MUN_NAME,120)||null,link_method:"manual",confidence:1,status:"verified",candidate_count:1,evidence,verified_at:now,reviewed_by_user_id:user.id,reviewed_at:now,review_note:note||null,updated_at:now};await admin.from("integration_crm_property_links").upsert(rowToUpsert,{onConflict:"user_id,crm_context_id,pams_pin"});await admin.from("integration_crm_resolution_state").update({detail_status:"enriched",candidate_count:0,updated_at:now}).eq("crm_context_id",ctx.id).eq("user_id",user.id);await admin.from("integration_audit_log").insert({user_id:user.id,connection_id:ctx.connection_id,action:"crm.property_link.manual_verified",actor:"user",details:{crm_context_id:ctx.id,pams_pin:pin,match_tier:"human_verified_manual",name_match_used:false,ownership_inferred:false}});return out(req,200,{ok:true,status:"verified",pams_pin:pin,property_address:clean(parcel.PROP_LOC,220)||null});
  }
  if(action==="resolution.run_now"){
    const connectionId=clean(body.connection_id,80);let cq=admin.from("integration_provider_connections").select("connection_id").eq("user_id",user.id).eq("provider","boldtrail").neq("sync_status","revoked");if(connectionId)cq=cq.eq("connection_id",connectionId);const {data:conn}=await cq.limit(1).maybeSingle();if(!conn)return out(req,404,{error:"Active BoldTrail connection not found"});const {data:workerToken}=await admin.rpc("integration_get_named_secret",{p_name:"integration_crm_resolution_worker_token"});if(!workerToken)return out(req,503,{error:"Resolution worker unavailable"});const r=await fetch(`${url}/functions/v1/integration-crm-resolution-worker`,{method:"POST",headers:{"Content-Type":"application/json","x-watchdog-resolution-worker-token":String(workerToken)},body:JSON.stringify({connection_id:conn.connection_id,limit:Math.min(Math.max(Number(body.limit||20),1),50)})});const d=await r.json().catch(()=>({}));if(!r.ok)return out(req,503,{error:"Resolution worker failed"});return out(req,200,{ok:true,...d});
  }
  return out(req,400,{error:"Unknown action"});
});
