import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.95.0";

type Row=Record<string,any>;
const RANK:Record<string,number>={standard:0,agent:1,pro:2,pro_plus:3,teams:4,developer:5};
const ORIGINS=new Set(["https://watchdogindex.com","https://www.watchdogindex.com","http://localhost:3000","http://127.0.0.1:3000"]);
const clean=(v:unknown,n=1000)=>String(v??"").replace(/[<>]/g,"").trim().slice(0,n);
const safe=(v:unknown)=>(v&&typeof v==="object"&&!Array.isArray(v)?v as Row:{});
const cors=(r:Request)=>({"Access-Control-Allow-Origin":ORIGINS.has(r.headers.get("origin")||"")?(r.headers.get("origin")||""):"https://www.watchdogindex.com","Access-Control-Allow-Headers":"authorization,apikey,content-type,x-client-info","Access-Control-Allow-Methods":"POST,OPTIONS","Vary":"Origin"});
const respond=(r:Request,s:number,b:unknown)=>new Response(JSON.stringify(b),{status:s,headers:{...cors(r),"Content-Type":"application/json","Cache-Control":"private, no-store"}});
const district=(tx:Row)=>{const p=clean(tx.pams_pin,80);return /^\d{4}/.test(p)?p.slice(0,4):""};
const compact=(v:unknown)=>clean(v,40).toUpperCase().replace(/\s+/g,"").replace(/^0+(?=\d)/,"").replace(/\.0+$/,"");
const money=(v:number)=>v.toLocaleString("en-US",{style:"currency",currency:"USD"});
const numberOrNull=(v:unknown)=>{const m=String(v??"").replace(/[$,]/g,"").match(/-?\d+(?:\.\d+)?/);return m?Number(m[0]):null};
async function digest(v:unknown){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(JSON.stringify(v)));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function decode(s:string){return s.replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&#39;/g,"'").replace(/&quot;/gi,'"').replace(/&#x2F;/gi,"/")}
function text(html:string){return decode(html.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ")).replace(/\s+/g," ").trim()}
function rows(html:string){const out:string[][]=[];for(const m of html.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi)){const cells=[...m[1].matchAll(/<t[dh]\b[^>]*>([\s\S]*?)<\/t[dh]>/gi)].map(x=>text(x[1])).filter(Boolean);if(cells.length)out.push(cells)}return out}
function labelValue(html:string,label:RegExp){const rs=rows(html);for(const r of rs){if(r.length>1&&label.test(r[0]))return clean(r.slice(1).join(" "),400)}const plain=text(html);const source=label.source.replace(/^\^|\$$/g,"").replace(/\\s\*/g,"\\s*");const m=plain.match(new RegExp(source+"\\s*:?\\s*([^|]{0,160})","i"));return m?clean(m[1],400):""}
function hidden(html:string,name:string){const escaped=name.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");const a=html.match(new RegExp(`<input[^>]+name=["']${escaped}["'][^>]+value=["']([^"']*)["']`,`i`));const b=html.match(new RegExp(`<input[^>]+value=["']([^"']*)["'][^>]+name=["']${escaped}["']`,`i`));return decode((a?.[1]||b?.[1]||"").trim())}
function buttonValue(html:string,name:string){return hidden(html,name)||"Search"}
function anchors(html:string){const out:{href:string,label:string}[]=[];for(const m of html.matchAll(/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi))out.push({href:decode(m[1]),label:text(m[2])});return out}
function normalizeBase(providerUrl:string){try{const u=new URL(providerUrl);const m=u.pathname.match(/^\/(.+?-nj)\//i);if(!m)return "";return `${u.protocol}//${u.host}/${m[1]}/cn/taxinquiry_edm/`}catch{return ""}}
async function get(url:string,timeout=12000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{headers:{"User-Agent":"Mozilla/5.0 Watchdog-CITE-Evidence/1.0 (+https://www.watchdogindex.com/)","Accept":"text/html,*/*"},redirect:"follow",signal:c.signal});return {ok:r.ok,status:r.status,url:r.url,html:await r.text()}}catch(e){return {ok:false,status:0,url,html:"",error:clean(e,200)}}finally{clearTimeout(t)}}
function exactDetailLinks(searchHtml:string,baseUrl:string,tx:Row){const b=compact(tx.block),l=compact(tx.lot),q=clean(tx.qualifier,40).toUpperCase();const links=[] as string[];for(const a of anchors(searchHtml)){if(!/itemDetail\.cfm/i.test(a.href))continue;let u:URL;try{u=new URL(a.href,baseUrl)}catch{continue}const ub=compact(u.searchParams.get("block")),ul=compact(u.searchParams.get("lot")),uq=clean(u.searchParams.get("qualifier"),40).toUpperCase();if(ub===b&&ul===l&&(!q||!uq||uq===q))links.push(u.toString())}return [...new Set(links)]}
function taxData(html:string){const rs=rows(html);const installments:Row[]=[];let currentYear=new Date().getFullYear();for(const r of rs){if(r.length===1&&/^20\d{2}$/.test(r[0])){currentYear=Number(r[0]);continue}if(r.length>=5&&/^\d{2}\/\d{2}\/20\d{2}$/.test(r[0])){const year=Number(r[0].slice(-4))||currentYear;installments.push({year,due_date:r[0],billed:numberOrNull(r[1]),balance:numberOrNull(r[2]),interest:numberOrNull(r[3]),total_due:numberOrNull(r[4]),status:clean(r[5]||"",60)})}}
 const open=installments.filter(x=>/open|due|delinquent|unpaid/i.test(String(x.status))||(x.total_due??0)>0);const liveDue=open.reduce((s,x)=>s+(Number(x.total_due)||0),0);const taxSale=labelValue(html,/^Tax Sale$/i),lienStatus=labelValue(html,/^Lien Status$/i);return {tax_account:labelValue(html,/^Tax Account No\.?$/i),location:labelValue(html,/^Location$/i),owner_info:labelValue(html,/^Owner Info$/i),muni_code:labelValue(html,/^Muni\.? Code$/i),lien_status:lienStatus,tax_sale:taxSale,installments,open_installments:open,live_due:liveDue}}
function utilityLinks(html:string,detailUrl:string){return anchors(html).filter(a=>/sewer|water|utility/i.test(a.label)&&/itemDetail\.cfm/i.test(a.href)).map(a=>({label:a.label,url:new URL(a.href,detailUrl).toString()})).slice(0,6)}
function utilityData(html:string){const rs=rows(html);const financial=rs.filter(r=>r.some(c=>/balance|interest|total due|amount due|status|due date/i.test(c))).slice(0,80);let due=0,found=false;for(const r of financial){for(let i=0;i<r.length;i++){if(/total due|balance/i.test(r[0])&&i>0){const n=numberOrNull(r[i]);if(n!=null){due+=n;found=true}}}}return {account:labelValue(html,/^Account No\.?$/i)||labelValue(html,/^Account Number$/i),financial_rows:financial,amount_due:found?due:null}}

Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});if(req.method!=="POST")return respond(req,405,{error:"POST required"});const auth=req.headers.get("authorization")||"";if(!auth.startsWith("Bearer "))return respond(req,401,{error:"Sign in required"});
 const url=Deno.env.get("SUPABASE_URL")||"",anon=Deno.env.get("SUPABASE_ANON_KEY")||"",service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";if(!url||!anon||!service)return respond(req,503,{error:"CIT-E provider unavailable"});const uc=createClient(url,anon,{global:{headers:{Authorization:auth}},auth:{persistSession:false}}),admin=createClient(url,service,{auth:{persistSession:false}});const {data:who}=await uc.auth.getUser();const user=who?.user;if(!user)return respond(req,401,{error:"Session invalid"});const [{data:ent},{data:prof}]=await Promise.all([admin.from("account_entitlements").select("plan_tier").eq("user_id",user.id).maybeSingle(),admin.from("profiles").select("account_role").eq("id",user.id).maybeSingle()]);const plan=prof?.account_role==="developer"?"developer":String(ent?.plan_tier||"standard");if((RANK[plan]??0)<RANK.pro_plus)return respond(req,403,{error:"Pro+ required"});
 let body:Row={};try{body=await req.json()}catch{return respond(req,400,{error:"Invalid JSON"})}const ids=[...new Set((Array.isArray(body.transaction_ids)?body.transaction_ids:[]).map((x:unknown)=>clean(x,80)).filter(Boolean))].slice(0,50);if(!ids.length)return respond(req,400,{error:"transaction_ids required"});const {data:txs}=await admin.from("transaction_workspaces").select("id,user_id,address,municipality,county,block,lot,qualifier,pams_pin").eq("user_id",user.id).in("id",ids);const dists=[...new Set((txs||[]).map((x:Row)=>district(x)).filter(Boolean))];const {data:routes}=dists.length?await admin.from("transaction_provider_registry").select("jurisdiction_key,provider_url,evidence_families,adapter_status").eq("jurisdiction_type","municipality").eq("provider_key","cite_tax_inquiry").in("jurisdiction_key",dists):{data:[]};const routeMap=new Map<string,Row[]>();for(const r of routes||[])routeMap.set(String(r.jurisdiction_key),[...(routeMap.get(String(r.jurisdiction_key))||[]),r]);const keys=["property_tax_status","tax_sale_delinquency","municipal_lien_clearance","ownership_vesting","water_sewer"];const {data:items}=await admin.from("transaction_items").select("id,transaction_id,item_key,payload").eq("user_id",user.id).in("transaction_id",ids).in("item_key",keys);const itemMap=new Map<string,Row>();for(const i of items||[])itemMap.set(`${i.transaction_id}:${i.item_key}`,i);const checkedAt=new Date().toISOString(),results:Row[]=[];
 for(const tx of txs||[]){const route=(routeMap.get(district(tx))||[]).find(r=>r.provider_url);if(!route){results.push({transaction_id:tx.id,status:"not_cite"});continue}const base=normalizeBase(route.provider_url);if(!base){results.push({transaction_id:tx.id,status:"route_unusable"});continue}const index=await get(base+"index.cfm");if(!index.ok){results.push({transaction_id:tx.id,status:"index_unavailable",http_status:index.status});continue}const tpid=hidden(index.html,"tpid")||(()=>{try{return new URL(route.provider_url).searchParams.get("tpid")||new URL(route.provider_url).searchParams.get("TPID")||""}catch{return ""}})();if(!tpid||!clean(tx.block)||!clean(tx.lot)){results.push({transaction_id:tx.id,status:"search_identity_missing"});continue}const params=new URLSearchParams({Block:clean(tx.block,40),SubBlock:"",Lot:clean(tx.lot,40),SubLot:"",Qualifier:clean(tx.qualifier,40),searchBlock:buttonValue(index.html,"searchBlock"),tpid});const search=await get(base+"finditems.cfm?"+params.toString());if(!search.ok){results.push({transaction_id:tx.id,status:"search_unavailable",http_status:search.status});continue}const links=exactDetailLinks(search.html,search.url,tx);if(links.length!==1){results.push({transaction_id:tx.id,status:links.length?"ambiguous":"no_exact_match",candidate_count:links.length});continue}const detail=await get(links[0]);if(!detail.ok){results.push({transaction_id:tx.id,status:"detail_unavailable"});continue}const data=taxData(detail.html),label=`${clean(tx.municipality,120)||"Municipality"} · CIT-E`;const patch=async(key:string,v:Row)=>{const it=itemMap.get(`${tx.id}:${key}`);if(!it)return;await admin.from("transaction_items").update({...v,payload:{...safe(it.payload),...safe(v.payload)},updated_at:checkedAt}).eq("id",it.id).eq("user_id",user.id)};const taxSale=/^(yes|y|active|open)$/i.test(data.tax_sale),lienObserved=Boolean(data.lien_status&&!/^(none|no|n\/a|not applicable)$/i.test(data.lien_status)),balanceObserved=data.live_due>0;
 await patch("property_tax_status",{evidence_state:balanceObserved?"verify":"clear_observed",severity:balanceObserved?"review":"info",source_type:"live_municipal_account",source_label:label,source_url:detail.url,source_checked_at:checkedAt,description:`Live CIT-E municipal tax account matched this parcel. Open installment amount observed: ${money(data.live_due)}. Tax Sale: ${data.tax_sale||"not stated"}. Lien Status: ${data.lien_status||"not stated"}. This is live account evidence, not a municipal lien certificate.`,payload:{provider_family:"cite",tax_account:data.tax_account,live_due:data.live_due,installments:data.installments,open_installments:data.open_installments,tax_sale:data.tax_sale,lien_status:data.lien_status,detail_url:detail.url}});
 if(data.owner_info)await patch("ownership_vesting",{evidence_state:"verify",severity:"review",source_type:"live_municipal_account",source_label:label,source_url:detail.url,source_checked_at:checkedAt,description:`The matched CIT-E municipal account exposes owner/account information. Compare the live municipal account against the contract and title; Watchdog is not making a legal vesting determination.`,payload:{owner_account_text:data.owner_info,owner_source:"cite_live_account",provider_family:"cite"}});
 await patch("tax_sale_delinquency",{evidence_state:taxSale?"issue_observed":"clear_observed",severity:taxSale?"blocker":"info",source_type:"live_municipal_account",source_label:label,source_url:detail.url,source_checked_at:checkedAt,description:taxSale?"CIT-E reports Tax Sale: YES on the matched municipal account. Review the municipal evidence immediately before closing.":`CIT-E reports Tax Sale: ${data.tax_sale||"not stated"} on the matched account. “No” is evidence from this checked portal, not a title or municipal lien certificate.`,payload:{provider_family:"cite",tax_sale:data.tax_sale,search_completed:true,detail_url:detail.url}});
 await patch("municipal_lien_clearance",{evidence_state:lienObserved?"issue_observed":"verify",severity:lienObserved?"blocker":"review",source_type:"live_municipal_account",source_label:label,source_url:detail.url,source_checked_at:checkedAt,description:lienObserved?`CIT-E displays a lien status on the matched municipal account: ${data.lien_status}. Obtain formal municipal/title clearance.`:`No affirmative lien status was observed on the checked CIT-E account. Formal municipal/title clearance is still required where applicable.`,payload:{provider_family:"cite",lien_status:data.lien_status,municipal_lien_certificate:false}});
 const ulinks=utilityLinks(detail.html,detail.url);let utilityEvidence:Row[]=[];for(const u of ulinks.slice(0,3)){const ur=await get(u.url);if(!ur.ok)continue;utilityEvidence.push({label:u.label,url:ur.url,...utilityData(ur.html)})}if(utilityEvidence.length){const amounts=utilityEvidence.map(x=>x.amount_due).filter(x=>typeof x==="number") as number[];const due=amounts.reduce((a,b)=>a+b,0);await patch("water_sewer",{evidence_state:due>0?"verify":"clear_observed",severity:due>0?"review":"info",source_type:"live_municipal_account",source_label:label,source_url:utilityEvidence[0].url,source_checked_at:checkedAt,description:`CIT-E utility evidence was retrieved for this matched parcel. Parsed current/open amount: ${money(due)}. Confirm final reading and closing payoff with the utility authority.`,payload:{provider_family:"cite",accounts:utilityEvidence,amount_due:due,final_reading_clearance:false}})}
 const evidence={tax:data,utilities:utilityEvidence,detail_url:detail.url};await admin.from("transaction_evidence_observations").upsert({transaction_id:tx.id,user_id:user.id,pams_pin:tx.pams_pin,evidence_key:"municipal_tax_cite",provider_key:`cite-${district(tx)}`,evidence_status:(taxSale||lienObserved||balanceObserved)?"observed":"no_issue_observed",value:evidence,source_label:label,source_url:detail.url,source_checked_at:checkedAt,facts_hash:await digest(evidence),metadata:{live_account:true,exact_parcel_match:true,municipal_lien_certificate:false,final_reading_clearance:false}},{onConflict:"transaction_id,evidence_key,provider_key,facts_hash",ignoreDuplicates:true});results.push({transaction_id:tx.id,status:"matched",provider:"cite",live_due:data.live_due,tax_sale:data.tax_sale,lien_status:data.lien_status,utility_accounts:utilityEvidence.length})}
 return respond(req,200,{ok:true,checked_at:checkedAt,provider_family:"cite",results});
});
