(function(){
'use strict';
var W=window.WatchdogAgentWorkflows;if(!W)return;var db=W.client(),user=null,events=[],selected=null,leads=[],picked=null;
var $=function(s){return document.querySelector(s)};
function renderList(){var host=$('#oh-list');if(!events.length){host.innerHTML='<div class="ag-empty">No open houses yet.</div>';return}host.innerHTML=events.map(function(x){return'<button type="button" data-event="'+W.esc(x.id)+'" class="'+(selected&&selected.id===x.id?'active':'')+'"><strong>'+W.esc(x.title||x.address)+'</strong><small>'+W.esc([x.address,W.dateTime(x.event_at),x.status].filter(Boolean).join(' · '))+'</small></button>'}).join('')}
function eventUrl(){return selected?location.origin+'/open-house?code='+encodeURIComponent(selected.event_code):''}
function renderQr(){var host=$('#oh-qr');if(!host||!selected)return;host.innerHTML='';if(window.QRCode)new QRCode(host,{text:eventUrl(),width:220,height:220,correctLevel:QRCode.CorrectLevel.M})}
function renderLeads(){var body=$('#oh-leads');$('#oh-lead-count').textContent=leads.length+' '+(leads.length===1?'lead':'leads');if(!leads.length){body.innerHTML='<tr><td colspan="5"><div class="ag-empty">No consented visitors yet.</div></td></tr>';return}body.innerHTML=leads.map(function(l){return'<tr><td><b>'+W.esc(l.full_name)+'</b></td><td><b>'+W.esc(l.email||l.phone||'—')+'</b><small>'+W.esc([l.email&&l.phone?l.phone:''].filter(Boolean).join(''))+'</small></td><td>'+W.esc(l.address||selected.address)+'</td><td>'+W.esc(W.dateTime(l.created_at))+'</td><td>'+(l._duplicate?'<span class="ag-pill amber">Possible duplicate</span>':'<span class="ag-pill green">New in lead ledger</span>')+'</td></tr>'}).join('')}
function renderDetail(){var has=!!selected;$('#oh-detail').hidden=!has;$('#oh-leads-card').hidden=!has;if(!has){renderList();return}$('#oh-title').textContent=selected.title||selected.address;$('#oh-status').value=selected.status||'scheduled';$('#oh-edit-event-at').value=selected.event_at?new Date(selected.event_at).toISOString().slice(0,16):'';$('#oh-edit-notes').value=selected.notes||'';$('#oh-url').value=eventUrl();renderQr();renderLeads();renderList()}
async function load(){try{user=await W.auth();var r=await db.from('agent_open_houses').select('*').eq('user_id',user.id).order('event_at',{ascending:false,nullsFirst:false}).order('created_at',{ascending:false});if(r.error)throw r.error;events=r.data||[];var wanted=new URLSearchParams(location.search).get('id');selected=events.find(function(x){return x.id===wanted})||events[0]||null;renderList();if(selected)await loadLeads();renderDetail()}catch(e){W.showNote($('#oh-create-note'),e.message,'error')}}
async function loadLeads(){if(!selected){leads=[];return}var r=await db.from('agent_portal_leads').select('id,full_name,email,phone,address,created_at,open_house_id').eq('agent_user_id',user.id).order('created_at',{ascending:false}).limit(5000);if(r.error){leads=[];return}var all=r.data||[];leads=all.filter(function(x){return x.open_house_id===selected.id}).map(function(x){var email=W.clean(x.email).toLowerCase(),phone=W.clean(x.phone).replace(/\D/g,'');x._duplicate=all.some(function(y){if(y.id===x.id)return false;var ye=W.clean(y.email).toLowerCase(),yp=W.clean(y.phone).replace(/\D/g,'');return(email&&ye===email)||(phone.length>=7&&yp===phone)});return x})}
async function choose(id){selected=events.find(function(x){return x.id===id})||null;await loadLeads();renderDetail()}
async function search(){var q=W.clean($('#oh-search').value),host=$('#oh-results');if(q.length<3){host.hidden=true;return}try{var rows=await W.propertySearch(q,6);host._rows=rows;host.hidden=false;host.innerHTML=rows.length?rows.map(function(p,i){return'<button class="ag-result" type="button" data-pick="'+i+'"><span><b>'+W.esc(p.address)+'</b><small>'+W.esc(W.place(p))+'</small></span><span class="ag-pill">Use property</span></button>'}).join(''):'<div class="ag-empty">No matching property record found. You can still enter the address manually.</div>'}catch(_){host.hidden=false;host.innerHTML='<div class="ag-empty">Property search is unavailable right now.</div>'}}
function pick(i){var p=($('#oh-results')._rows||[])[Number(i)];if(!p)return;picked=p;$('#oh-address').value=p.address||'';$('#oh-city').value=p.city||p.town||'';$('#oh-zip').value=p.zip||'';$('#oh-results').hidden=true}
async function create(e){e.preventDefault();var row={user_id:user.id,title:W.clean($('#oh-title-input').value)||null,address:W.clean($('#oh-address').value),city:W.clean($('#oh-city').value)||null,municipality:picked&&(picked.town||picked.city)||W.clean($('#oh-city').value)||null,county:picked&&picked.county||null,postal_code:W.clean($('#oh-zip').value)||null,pams_pin:picked&&picked.pams_pin||null,event_at:$('#oh-event-at').value?new Date($('#oh-event-at').value).toISOString():null,status:'scheduled',notes:W.clean($('#oh-notes').value)||null};if(!row.address)return;W.showNote($('#oh-create-note'),'Saving…');var r=await db.from('agent_open_houses').insert(row).select('*').single();if(r.error){W.showNote($('#oh-create-note'),r.error.message,'error');return}events.unshift(r.data);selected=r.data;leads=[];e.currentTarget.reset();picked=null;renderDetail();W.showNote($('#oh-create-note'),'Open-house link created.','ok')}
async function save(){if(!selected)return;var patch={status:$('#oh-status').value,event_at:$('#oh-edit-event-at').value?new Date($('#oh-edit-event-at').value).toISOString():null,notes:W.clean($('#oh-edit-notes').value)||null,updated_at:new Date().toISOString()};var r=await db.from('agent_open_houses').update(patch).eq('id',selected.id).eq('user_id',user.id).select('*').single();if(r.error){W.showNote($('#oh-save-note'),r.error.message,'error');return}selected=r.data;var i=events.findIndex(function(x){return x.id===selected.id});if(i>=0)events[i]=selected;renderDetail();W.showNote($('#oh-save-note'),'Saved.','ok')}
function csvCell(v){var s=String(v==null?'':v);return'"'+s.replace(/"/g,'""')+'"'}
function exportCsv(){if(!leads.length)return;var lines=[['First Name','Last Name','Email','Phone','Street Address','City','State','ZIP','Tags','Source']];leads.forEach(function(l){var parts=W.clean(l.full_name).split(/\s+/),first=parts.shift()||'',last=parts.join(' ');lines.push([first,last,l.email||'',l.phone||'',l.address||selected.address,selected.city||'','NJ',selected.postal_code||'','Watchdog Open House','Watchdog'])});var csv=lines.map(function(row){return row.map(csvCell).join(',')}).join('\r\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='watchdog-open-house-'+(selected.event_code||'leads')+'.csv';document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(a.href)},1000)}
document.addEventListener('click',function(e){var ev=e.target.closest('[data-event]');if(ev)choose(ev.dataset.event);var p=e.target.closest('[data-pick]');if(p)pick(p.dataset.pick)});
$('#oh-search-btn').addEventListener('click',search);$('#oh-search').addEventListener('keydown',function(e){if(e.key==='Enter'){e.preventDefault();search()}});$('#oh-form').addEventListener('submit',create);$('#oh-save').addEventListener('click',save);$('#oh-copy').addEventListener('click',function(){W.copy(eventUrl()).then(function(){W.showNote($('#oh-save-note'),'Link copied.','ok')}).catch(function(){})});$('#oh-export').addEventListener('click',exportCsv);$('#oh-new').addEventListener('click',function(){$('#oh-title-input').focus();scrollTo({top:0,behavior:'smooth'})});
load();
})();