import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.95.0";

type Row=Record<string,any>;
const WIPP_BASE="https://api.edmundsgovtech.cloud/wipp-core/v1";
const WIPP_PORTAL="https://wipp.edmundsgovtech.cloud";
const ORIGINS=new Set(["https://watchdogindex.com","https://www.watchdogindex.com","https://njpropertytaxrelief.com","https://www.njpropertytaxrelief.com","http://localhost:3000","http://127.0.0.1:3000"]);
const RANK:Record<string,number>={standard:0,agent:1,pro:2,pro_plus:3,teams:4,developer:5};
const clean=(v:unknown,n=500)=>String(v??"").replace(/[<>]/g,"").trim().slice(0,n);
const safe=(v:unknown)=>(v&&typeof v==="object"&&!Array.isArray(v)?v as Row:{});
const cors=(r:Request)=>({"Access-Control-Allow-Origin":ORIGINS.has(r.headers.get("origin")||"")?(r.headers.get("origin")||""):"https://www.watchdogindex.com","Access-Control-Allow-Headers":"authorization,apikey,content-type,x-client-info","Access-Control-Allow-Methods":"POST,OPTIONS","Vary":"Origin"});
const respond=(r:Request,s:number,b:unknown)=>new Response(JSON.stringify(b),{status:s,headers:{...cors(r),"Content-Type":"application/json","Cache-Control":"private, no-store"}});
const num=(v:unknown)=>{if(v===null||v===undefined||v==="")return null;const n=Number(String(v).replace(/[$,]/g,""));return Number.isFinite(n)?n:null};
const SUFFIX:Record<string,string>={STREET:"ST",ST:"ST",ROAD:"RD",RD:"RD",AVENUE:"AVE",AVE:"AVE",COURT:"CT",CT:"CT",DRIVE:"DR",DR:"DR",LANE:"LN",LN:"LN",PLACE:"PL",PL:"PL",BOULEVARD:"BLVD",BLVD:"BLVD",TERRACE:"TER",TER:"TER",CIRCLE:"CIR",CIR:"CIR",PARKWAY:"PKWY",PKWY:"PKWY",HIGHWAY:"HWY",HWY:"HWY",WAY:"WAY"};
function normStreet(v:unknown){const raw=clean(v,240).split(",")[0].toUpperCase().replace(/[^A-Z0-9 ]+/g," ").replace(/\s+/g," ").trim();const p=raw.split(" ").filter(Boolean);if(p.length&&SUFFIX[p[p.length-1]])p[p.length-1]=SUFFIX[p[p.length-1]];return p.join(" ")}
function searchTerm(v:unknown){const raw=clean(v,240).split(",")[0].replace(/[^A-Za-z0-9 ]+/g," ").replace(/\s+/g," ").trim();const p=raw.split(" ").filter(Boolean);if(p.length>2&&SUFFIX[String(p[p.length-1]).toUpperCase()])p.pop();return p.join(" ").slice(0,100)}
function compact(v:unknown){let s=clean(v,40).toUpperCase().replace(/\s+/g,"").replace(/^0+(?=\d)/,"");if(/^\d+(?:\.\d+)?$/.test(s)&&s.includes("."))s=s.replace(/0+$/,"").replace(/\.$/,"");return s}
function district(row:Row){const explicit=clean(row.municipality_code,4);if(/^\d{4}$/.test(explicit))return explicit;const pin=clean(row.pams_pin,80).replace(/\D/g,"");return pin.length>=4?pin.slice(0,4):""}
function pick(rows:Row[],p:Row){const wanted=normStreet(p.address);const exact=rows.filter(r=>normStreet(r.propertyLoc)===wanted);if(exact.length===1)return exact[0];const b=compact(p.block),l=compact(p.lot);if(b&&l){const candidates=(exact.length?exact:rows).filter(r=>{const x=clean(r.blqId,120).toUpperCase().replace(/\s+/g,"");return x.includes(b)&&x.includes(l)});if(candidates.length===1)return candidates[0]}return null}
async function wipp(id:string,path:string,timeout=9000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(`${WIPP_BASE}${path}`,{signal:c.signal,headers:{"X-Wipp-Id":id,"User-Agent":"Watchdog-Property-Tax-Evidence/1.0","Accept":"application/json"}});const data=await r.json().catch(()=>null);return{ok:r.ok,status:r.status,data}}catch(e){return{ok:false,status:0,data:null,error:clean(e,160)}}finally{clearTimeout(t)}}
function annual(detail:Row){const out:Record<string,number>={};const years=safe(detail.taxYears);for(const [year,groupsRaw] of Object.entries(years)){let total=0,found=false;const rows=Array.isArray(safe(groupsRaw).NJTAX)?safe(groupsRaw).NJTAX:[];for(const raw of rows){const t=safe(raw);for(let q=1;q<=4;q++){const adj=num(t[`qtr${q}AdjBilled`]),orig=num(t[`qtr${q}OrigBilled`]);const billed=adj??orig;if(billed!=null){total+=billed;found=true}}}if(found)out[String(year)]=Math.round(total*100)/100}return out}
function balance(detail:Row){let open=0,past=0,interest=0;const now=Date.now(),years=safe(detail.taxYears);for(const groupsRaw of Object.values(years)){for(const raw of (Array.isArray(safe(groupsRaw).NJTAX)?safe(groupsRaw).NJTAX:[])){const t=safe(raw);for(let q=1;q<=4;q++){const prn=num(t[`qtr${q}PrnBal`])||0,int=num(t[`qtr${q}IntDue`])||0,due=Date.parse(clean(t[`qtr${q}DueDate`],50));open+=prn+int;interest+=int;if(prn+int>0&&Number.isFinite(due)&&due<now)past+=prn+int}}}return{open_balance:Math.round(open*100)/100,past_due_balance:Math.round(past*100)/100,interest_due:Math.round(interest*100)/100}}
async function providerIsLive(admin:any,id:string){const r=await admin.from("transaction_provider_registry").select("provider_key,provider_label,adapter_status").eq("jurisdiction_type","municipality").eq("jurisdiction_key",id).eq("provider_key","edmunds_wipp").eq("adapter_status","live").limit(1);return r.data?.[0]||null}
async function resolveWipp(admin:any,p:Row){const id=district(p);if(!/^\d{4}$/.test(id))return{status:"municipality_code_required"};const provider=await providerIsLive(admin,id);if(!provider)return{status:"provider_not_supported",municipality_code:id};const meta=await wipp(id,`/metadata/${id}`);if(!meta.ok)return{status:"provider_unavailable",municipality_code:id,http_status:meta.status};const term=searchTerm(p.address);if(!term)return{status:"address_required",municipality_code:id};const sr=await wipp(id,`/wippPropInfo/search?propertyLoc=${encodeURIComponent(term)}&size=25`);if(!sr.ok||!Array.isArray(sr.data?.content))return{status:"search_unavailable",municipality_code:id,http_status:sr.status};const match=pick(sr.data.content,p);if(!match)return{status:"property_not_uniquely_matched",municipality_code:id,candidate_count:sr.data.content.length};const account=clean(match.accountId,100);if(!account)return{status:"account_missing",municipality_code:id};const detail=await wipp(id,`/wippTaxes/${encodeURIComponent(account)}`);if(!detail.ok||!detail.data)return{status:"detail_unavailable",municipality_code:id,http_status:detail.status};const totals=annual(detail.data),bal=balance(detail.data),prop=safe(detail.data.propertyInfo),source_url=`${WIPP_PORTAL}/view/wippTaxes/${encodeURIComponent(account)}?wippId=${encodeURIComponent(id)}`;return{status:"available",provider_family:"edmunds_wipp",provider_label:`${clean(meta.data?.cityName,160)||clean(p.municipality,160)||"Municipality"} · Edmunds GovTech WIPP`,municipality_code:id,account_id:account,address_match:clean(match.propertyLoc,240)||null,block_lot:clean(match.blqId,120)||null,owner_name:clean(prop.ownerName,240)||null,annual_billed:totals,property_tax_2024:totals["2024"]??null,property_tax_2025:totals["2025"]??null,...bal,last_payment:clean(prop.lastDatePaid,80)||null,tax_sale_flag:prop.taxSaleFlag??null,source_url,checked_at:new Date().toISOString(),result_semantics:"Annual billed totals and live account balances are derived from the matched municipal WIPP tax account. They are public tax-account evidence, not a municipal lien certificate, title clearance, or final filing determination."}}

Deno.serve(async(req:Request)=>{
  if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});if(req.method!=="POST")return respond(req,405,{error:"POST required"});const auth=req.headers.get("authorization")||"";if(!auth.startsWith("Bearer "))return respond(req,401,{error:"Sign in required"});
  const url=Deno.env.get("SUPABASE_URL")||"",anon=Deno.env.get("SUPABASE_ANON_KEY")||Deno.env.get("SUPABASE_PUBLISHABLE_KEY")||"",service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||Deno.env.get("SUPABASE_SECRET_KEY")||"";if(!url||!anon||!service)return respond(req,503,{error:"Configuration incomplete"});const uc=createClient(url,anon,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}}),admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});const {data:who}=await uc.auth.getUser();const user=who?.user;if(!user)return respond(req,401,{error:"Session invalid"});let body:Row={};try{body=await req.json()}catch{return respond(req,400,{error:"Invalid JSON"})}
  if(body.property&&typeof body.property==="object")return respond(req,200,await resolveWipp(admin,safe(body.property)));
  const ids=[...new Set((Array.isArray(body.transaction_ids)?body.transaction_ids:[]).map((x:unknown)=>clean(x,80)).filter(Boolean))].slice(0,50);if(!ids.length)return respond(req,400,{error:"property or transaction_ids required"});const [{data:ent},{data:profile}]=await Promise.all([admin.from("account_entitlements").select("plan_tier").eq("user_id",user.id).maybeSingle(),admin.from("profiles").select("account_role").eq("id",user.id).maybeSingle()]);const plan=profile?.account_role==="developer"?"developer":String(ent?.plan_tier||"standard");if((RANK[plan]??0)<RANK.pro_plus)return respond(req,403,{error:"Pro+ required for transaction updates"});const {data:txs}=await admin.from("transaction_workspaces").select("id,address,city,state,postal_code,municipality,county,block,lot,qualifier,pams_pin").eq("user_id",user.id).in("id",ids);const results=[];for(const tx of txs||[]){const e:any=await resolveWipp(admin,tx);results.push({transaction_id:tx.id,...e});if(e.status!=="available")continue;const {data:item}=await admin.from("transaction_items").select("id,payload").eq("user_id",user.id).eq("transaction_id",tx.id).eq("item_key","property_tax_status").maybeSingle();if(item){const payload={...safe(item.payload),municipal_live_account_checked:true,provider_family:e.provider_family,municipality_code:e.municipality_code,municipal_account_id:e.account_id,annual_billed:e.annual_billed,pas1_tax_info:{tax_2024:e.property_tax_2024,tax_2025:e.property_tax_2025,source_url:e.source_url,checked_at:e.checked_at},live_open_balance:e.open_balance,past_due_balance:e.past_due_balance,interest_due:e.interest_due,last_payment:e.last_payment,tax_sale_flag:e.tax_sale_flag,result_semantics:e.result_semantics};await admin.from("transaction_items").update({source_type:"live_municipal_account",source_label:e.provider_label,source_url:e.source_url,source_checked_at:e.checked_at,evidence_state:e.past_due_balance>0||e.tax_sale_flag===true?"verify":"clear_observed",severity:e.past_due_balance>0||e.tax_sale_flag===true?"review":"info",description:e.result_semantics,payload,updated_at:e.checked_at}).eq("id",item.id).eq("user_id",user.id)}}return respond(req,200,{ok:true,results});
});
