import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.95.0";

type Obj = Record<string, any>;
const ALLOWED_PLANS = new Set(["teams", "developer"]);
const ORIGINS = new Set(["https://njpropertytaxrelief.com","https://www.njpropertytaxrelief.com","http://localhost:3000","http://127.0.0.1:3000"]);
const BOLDTRAIL_CONTACTS = "https://api.kvcore.com/v2/public/contacts";
const DIRECT_SCOPES = ["crm.contacts.read"];
function namedEnv(jsonName:string,legacyName:string){const raw=Deno.env.get(jsonName)||"";if(raw){try{const x=JSON.parse(raw);if(x?.default)return String(x.default)}catch{}}return Deno.env.get(legacyName)||"";}
function clean(v:unknown,max=200){return String(v??"").replace(/[\u0000-\u001f<>]/g,"").trim().slice(0,max);}
function planName(v:unknown){return clean(v,30).toLowerCase().replace("pro+","pro_plus")||"standard";}
function cors(req:Request){const origin=req.headers.get("origin")||"";const allow=ORIGINS.has(origin)||/^https:\/\/[a-z0-9-]+\.vercel\.app$/i.test(origin)?origin:"https://njpropertytaxrelief.com";return{"Access-Control-Allow-Origin":allow,"Access-Control-Allow-Headers":"authorization, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"};}
function reply(req:Request,status:number,payload:unknown){return new Response(JSON.stringify(payload),{status,headers:{...cors(req),"Content-Type":"application/json","Cache-Control":"private, no-store"}});}
async function validateBoldTrailToken(token:string){const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),10000);try{const u=new URL(BOLDTRAIL_CONTACTS);u.searchParams.set("limit","1");const res=await fetch(u,{headers:{Authorization:`Bearer ${token}`,Accept:"application/json","Content-Type":"application/json"},signal:ctrl.signal});if(!res.ok)return{ok:false,status:res.status,total:null};const data=await res.json().catch(()=>({}));return{ok:true,status:res.status,total:Number.isFinite(Number(data?.total))?Number(data.total):null};}catch{return{ok:false,status:0,total:null};}finally{clearTimeout(timer);}}
function publicProviderState(p:Obj,c:Obj){return{connection_id:p.connection_id,provider:p.provider,auth_type:p.auth_type,sync_enabled:!!p.sync_enabled,sync_status:p.sync_status,sync_interval_minutes:p.sync_interval_minutes,cursor_updated_at:p.cursor_updated_at||null,last_sync_started_at:p.last_sync_started_at||null,last_sync_completed_at:p.last_sync_completed_at||null,last_success_at:p.last_success_at||null,last_error:p.last_error||c?.last_error||null,consecutive_failures:Number(p.consecutive_failures||0),last_records_seen:Number(p.last_records_seen||0),last_records_upserted:Number(p.last_records_upserted||0),records_synced_total:Number(p.records_synced_total||0),provider_account_ref:p.provider_account_ref||null,provider_metadata:p.provider_metadata||{},name:c?.name||"Direct CRM",status:c?.status||"revoked",external_account_label:c?.external_account_label||null,intelligence_access:!!c?.intelligence_access,intelligence_access_updated_at:c?.intelligence_access_updated_at||null,scopes:c?.scopes||[],created_at:p.created_at,updated_at:p.updated_at};}
Deno.serve(async(req)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});if(req.method!=="POST")return reply(req,405,{error:"Method not allowed"});const origin=req.headers.get("origin")||"";if(origin&&!ORIGINS.has(origin)&&!/^https:\/\/[a-z0-9-]+\.vercel\.app$/i.test(origin))return reply(req,403,{error:"Origin not allowed"});const auth=req.headers.get("authorization")||"";if(!auth.startsWith("Bearer "))return reply(req,401,{error:"Sign in required"});
 const url=Deno.env.get("SUPABASE_URL")||"",pub=namedEnv("SUPABASE_PUBLISHABLE_KEYS","SUPABASE_ANON_KEY"),secret=namedEnv("SUPABASE_SECRET_KEYS","SUPABASE_SERVICE_ROLE_KEY");if(!url||!pub||!secret)return reply(req,503,{error:"Direct CRM service unavailable"});const userDb=createClient(url,pub,{global:{headers:{Authorization:auth}},auth:{persistSession:false}}),admin=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});const {data:authData,error:authError}=await userDb.auth.getUser();if(authError||!authData.user)return reply(req,401,{error:"Session could not be verified"});const user=authData.user;const {data:ent,error:entError}=await userDb.rpc("get_my_entitlement");if(entError)return reply(req,403,{error:"Plan could not be verified"});const entRow=Array.isArray(ent)?ent[0]:ent,plan=planName(entRow?.plan_tier);if(!ALLOWED_PLANS.has(plan))return reply(req,403,{error:"Native CRM connections require Teams",required_plan:"teams",plan});let body:Obj={};try{body=await req.json()}catch{return reply(req,400,{error:"Invalid JSON"})}const action=clean(body.action,60);
 const audit=async(connectionId:string|null,kind:string,details:Obj={})=>{await admin.from("integration_audit_log").insert({user_id:user.id,connection_id:connectionId,action:kind,actor:"user",details});};const getConnection=async(id:string)=>{const {data}=await admin.from("integration_connections").select("*").eq("id",id).eq("user_id",user.id).maybeSingle();return data||null;};const getProvider=async(provider="boldtrail")=>{const {data}=await admin.from("integration_provider_connections").select("*").eq("user_id",user.id).eq("provider",provider).maybeSingle();return data||null;};
 if(action==="status"||action==="providers.list"){const {data:states,error}=await admin.from("integration_provider_connections").select("*").eq("user_id",user.id).order("created_at",{ascending:false});if(error)return reply(req,503,{error:"Direct CRM connections could not be loaded"});const ids=(states||[]).map((x:Obj)=>x.connection_id),{data:connRows}=ids.length?await admin.from("integration_connections").select("*").eq("user_id",user.id).in("id",ids):{data:[] as Obj[]},cm=new Map((connRows||[]).map((c:Obj)=>[c.id,c]));return reply(req,200,{phase:4,plan,providers:(states||[]).map((p:Obj)=>publicProviderState(p,cm.get(p.connection_id)||{})),supported_providers:[{id:"boldtrail",name:"BoldTrail / kvCORE",auth_type:"api_token",status:"beta"}]});}
 if(action==="boldtrail.connect"){const token=String(body.api_token||"").trim();if(token.length<20||token.length>5000)return reply(req,400,{error:"A valid BoldTrail API token is required"});const validation=await validateBoldTrailToken(token);if(!validation.ok){await audit(null,"boldtrail.connection.validation_failed",{http_status:validation.status||null});return reply(req,400,{error:"BoldTrail credentials could not be verified",provider_status:validation.status||null});}const existing=await getProvider("boldtrail"),connectionId=existing?.connection_id||crypto.randomUUID(),stored=await admin.rpc("integration_store_secret",{p_secret:token,p_name:`integration:boldtrail:${connectionId}:${Date.now()}`,p_description:"Watchdog native BoldTrail API token"});if(stored.error||!stored.data)return reply(req,503,{error:"BoldTrail credential could not be secured"});const newSecretId=String(stored.data),oldSecretId=existing?.credential_secret_id?String(existing.credential_secret_id):null,intelligence=!!body.intelligence_access,scopes=[...DIRECT_SCOPES,...(intelligence?["intelligence.context.read"]:[])],now=new Date().toISOString(),label=clean(body.external_account_label||"BoldTrail CRM",120)||"BoldTrail CRM";
  if(existing){const cu=await admin.from("integration_connections").update({provider:"boldtrail",name:"BoldTrail Direct",status:"active",direction:"bidirectional",outbound_url:null,outbound_secret_id:null,inbound_token_hash:null,event_types:[],scopes,intelligence_access:intelligence,intelligence_access_updated_at:now,intelligence_access_updated_by:"user",external_account_label:label,last_error:null,metadata:{phase:4,direct_crm:true,provider:"boldtrail"},updated_at:now}).eq("id",connectionId).eq("user_id",user.id);if(cu.error){await admin.rpc("integration_delete_secret",{p_secret_id:newSecretId});return reply(req,503,{error:"BoldTrail connection could not be updated"});}const pu=await admin.from("integration_provider_connections").update({credential_secret_id:newSecretId,auth_type:"api_token",sync_enabled:true,sync_status:"idle",last_error:null,consecutive_failures:0,provider_account_ref:null,provider_metadata:{api_base:"https://api.kvcore.com",api_version:"v2",validated_total_contacts:validation.total,direct_beta:true},updated_at:now}).eq("connection_id",connectionId).eq("user_id",user.id);if(pu.error){await admin.rpc("integration_delete_secret",{p_secret_id:newSecretId});return reply(req,503,{error:"BoldTrail provider state could not be updated"});}}
  else{const ci=await admin.from("integration_connections").insert({id:connectionId,user_id:user.id,provider:"boldtrail",name:"BoldTrail Direct",status:"active",direction:"bidirectional",outbound_url:null,outbound_secret_id:null,inbound_token_hash:null,event_types:[],scopes,intelligence_access:intelligence,intelligence_access_updated_at:now,intelligence_access_updated_by:"user",external_account_label:label,metadata:{phase:4,direct_crm:true,provider:"boldtrail"}});if(ci.error){await admin.rpc("integration_delete_secret",{p_secret_id:newSecretId});return reply(req,503,{error:"BoldTrail connection could not be created"});}const si=await admin.from("integration_provider_connections").insert({connection_id:connectionId,user_id:user.id,provider:"boldtrail",auth_type:"api_token",credential_secret_id:newSecretId,sync_enabled:true,sync_status:"idle",sync_interval_minutes:15,provider_metadata:{api_base:"https://api.kvcore.com",api_version:"v2",validated_total_contacts:validation.total,direct_beta:true}});if(si.error){await admin.from("integration_connections").delete().eq("id",connectionId).eq("user_id",user.id);await admin.rpc("integration_delete_secret",{p_secret_id:newSecretId});return reply(req,503,{error:"BoldTrail provider state could not be created"});}}
  if(oldSecretId&&oldSecretId!==newSecretId)await admin.rpc("integration_delete_secret",{p_secret_id:oldSecretId});await audit(connectionId,existing?"boldtrail.connection.reconnected":"boldtrail.connection.created",{intelligence_access:intelligence,validated_total_contacts:validation.total});const kick=await admin.rpc("integration_kick_provider_sync",{p_connection_id:connectionId,p_trigger:"connect"}),p=await getProvider("boldtrail"),c=await getConnection(connectionId);return reply(req,existing?200:201,{connection:publicProviderState(p||{},c||{}),first_sync_queued:!kick.error,request_id:kick.data||null});}
 if(action==="provider.sync_now"){const connectionId=clean(body.connection_id,80),p=await getProvider("boldtrail");if(!p||p.connection_id!==connectionId||p.sync_status==="revoked")return reply(req,404,{error:"Direct CRM connection not found"});const c=await getConnection(connectionId);if(!c||c.status!=="active")return reply(req,409,{error:"Direct CRM connection is not active"});const kick=await admin.rpc("integration_kick_provider_sync",{p_connection_id:connectionId,p_trigger:"manual"});if(kick.error)return reply(req,503,{error:"CRM sync could not be queued"});await audit(connectionId,"provider.sync.manual_queued",{provider:p.provider,request_id:kick.data||null});return reply(req,202,{ok:true,request_id:kick.data||null});}
 if(action==="provider.set_intelligence"){const connectionId=clean(body.connection_id,80),p=await getProvider("boldtrail");if(!p||p.connection_id!==connectionId||p.sync_status==="revoked")return reply(req,404,{error:"Direct CRM connection not found"});const c=await getConnection(connectionId);if(!c)return reply(req,404,{error:"Direct CRM connection not found"});const enabled=!!body.enabled,scopes=new Set<string>((c.scopes||[]).filter((x:string)=>x!=="intelligence.context.read"));if(enabled)scopes.add("intelligence.context.read");const now=new Date().toISOString(),{data:updated,error}=await admin.from("integration_connections").update({scopes:[...scopes],intelligence_access:enabled,intelligence_access_updated_at:now,intelligence_access_updated_by:"user",updated_at:now}).eq("id",connectionId).eq("user_id",user.id).select("*").single();if(error)return reply(req,503,{error:"Intelligence permission could not be updated"});await audit(connectionId,"intelligence.context.permission_changed",{enabled,provider:p.provider});return reply(req,200,{connection:publicProviderState(p,updated)});}
 if(action==="provider.history"){const connectionId=clean(body.connection_id,80),p=await getProvider("boldtrail");if(!p||p.connection_id!==connectionId)return reply(req,404,{error:"Direct CRM connection not found"});const limit=Math.min(Math.max(Number(body.limit||20),1),50),{data,error}=await admin.from("integration_provider_sync_runs").select("id,provider,trigger_source,status,cursor_from,cursor_to,records_seen,records_upserted,error_code,error_message,details,started_at,completed_at").eq("user_id",user.id).eq("connection_id",connectionId).order("started_at",{ascending:false}).limit(limit);if(error)return reply(req,503,{error:"CRM sync history could not be loaded"});return reply(req,200,{runs:data||[]});}
 if(action==="provider.disconnect"){const connectionId=clean(body.connection_id,80),p=await getProvider("boldtrail");if(!p||p.connection_id!==connectionId)return reply(req,404,{error:"Direct CRM connection not found"});const now=new Date().toISOString(),purgeContext=body.purge_context!==false;let removed=0;if(purgeContext){const {count}=await admin.from("integration_crm_context").delete({count:"exact"}).eq("user_id",user.id).eq("connection_id",connectionId);removed=Number(count||0);}await admin.from("integration_provider_connections").update({credential_secret_id:null,sync_enabled:false,sync_status:"revoked",last_error:null,updated_at:now}).eq("connection_id",connectionId).eq("user_id",user.id);await admin.from("integration_connections").update({status:"revoked",intelligence_access:false,updated_at:now}).eq("id",connectionId).eq("user_id",user.id);if(p.credential_secret_id)await admin.rpc("integration_delete_secret",{p_secret_id:p.credential_secret_id});await audit(connectionId,"provider.connection.revoked",{provider:p.provider,crm_context_rows_removed:removed,purge_context:purgeContext});return reply(req,200,{ok:true,crm_context_rows_removed:removed});}
 return reply(req,400,{error:"Unknown action"});
});
