import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.95.0";

type Obj = Record<string, any>;
const PROD_ORIGINS = new Set(["https://njpropertytaxrelief.com","https://www.njpropertytaxrelief.com","http://localhost:3000","http://127.0.0.1:3000"]);
const PLANS = new Set(["pro_plus","teams","developer"]);
const DIRECTIONS = new Set(["inbound","outbound","bidirectional"]);
const EVENTS = new Set(["property.signal.changed","watchlist.alert","report.ready","intelligence.finding.created","integration.test"]);
const SCOPES = new Set(["crm.context.ingest","crm.contacts.read","crm.contacts.write","crm.activities.read","crm.notes.read","crm.notes.write","crm.tasks.write","property.links.read","intelligence.context.read"]);
const MAPPING_KEYS = new Set(["external_contact_id","contact_name","contact_email","contact_phone","lead_stage","relationship","last_activity_at","tags","property_ref","property_address","property_municipality","property_county","source_updated_at"]);

function cors(req: Request){const o=req.headers.get("origin")||"";const allow=PROD_ORIGINS.has(o)||/^https:\/\/[a-z0-9-]+\.vercel\.app$/i.test(o)?o:"https://njpropertytaxrelief.com";return{"Access-Control-Allow-Origin":allow,"Access-Control-Allow-Headers":"authorization, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"};}
function out(req:Request,status:number,payload:unknown){return new Response(JSON.stringify(payload),{status,headers:{...cors(req),"Content-Type":"application/json","Cache-Control":"private, no-store"}});}
function clean(v:unknown,max=200){return String(v??"").replace(/[\u0000-\u001f<>]/g,"").trim().slice(0,max);}
function namedEnv(jsonName:string,legacyName:string){const raw=Deno.env.get(jsonName)||"";if(raw){try{const x=JSON.parse(raw);if(x?.default)return String(x.default)}catch{}}return Deno.env.get(legacyName)||"";}
function randomToken(bytes=32){const b=new Uint8Array(bytes);crypto.getRandomValues(b);let s="";for(const n of b)s+=String.fromCharCode(n);return btoa(s).replaceAll("+","-").replaceAll("/","_").replace(/=+$/g,"");}
async function sha256(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(d)).map(x=>x.toString(16).padStart(2,"0")).join("");}
function normalizeDirection(v:unknown){const x=clean(v,30);return DIRECTIONS.has(x)?x:"bidirectional";}
function normalizeEvents(v:unknown){const xs=Array.isArray(v)?v.map(x=>clean(x,80)).filter(x=>EVENTS.has(x)):[];if(!xs.includes("integration.test"))xs.push("integration.test");return [...new Set(xs.length?xs:["property.signal.changed","integration.test"])];}
function normalizeScopes(v:unknown,direction:string){const xs=Array.isArray(v)?v.map(x=>clean(x,80)).filter(x=>SCOPES.has(x)):[];if((direction==="inbound"||direction==="bidirectional")&&!xs.includes("crm.context.ingest"))xs.push("crm.context.ingest");return [...new Set(xs)];}
function normalizePlan(v:unknown){const x=clean(v,30).toLowerCase().replace("pro+","pro_plus");return x||"standard";}
function normalizeMapping(v:unknown){const src=v&&typeof v==="object"&&!Array.isArray(v)?v as Obj:{};const next:Obj={};for(const [k,val] of Object.entries(src)){if(!MAPPING_KEYS.has(k))continue;const path=clean(val,120);if(path&&/^[A-Za-z0-9_-]+(?:\.[A-Za-z0-9_-]+){0,5}$/.test(path))next[k]=path;}return next;}
function publicHttps(v:unknown){try{const u=new URL(String(v||""));if(u.protocol!=="https:")return null;const h=u.hostname.toLowerCase();if(!h||h==="localhost"||h.endsWith(".local")||h.endsWith(".internal"))return null;if(/^127\.|^10\.|^192\.168\.|^169\.254\.|^0\./.test(h))return null;const m=h.match(/^172\.(\d+)\./);if(m&&Number(m[1])>=16&&Number(m[1])<=31)return null;if(h==="::1"||h.startsWith("fc")||h.startsWith("fd")||h.startsWith("fe80:"))return null;u.username="";u.password="";u.hash="";return u.toString();}catch{return null;}}

Deno.serve(async(req)=>{
  if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});
  if(req.method!=="POST")return out(req,405,{error:"Method not allowed"});
  const origin=req.headers.get("origin")||"";if(origin&&!PROD_ORIGINS.has(origin)&&!/^https:\/\/[a-z0-9-]+\.vercel\.app$/i.test(origin))return out(req,403,{error:"Origin not allowed"});
  const auth=req.headers.get("authorization")||"";if(!auth.startsWith("Bearer "))return out(req,401,{error:"Sign in required"});
  const url=Deno.env.get("SUPABASE_URL")||"",pub=namedEnv("SUPABASE_PUBLISHABLE_KEYS","SUPABASE_ANON_KEY"),secret=namedEnv("SUPABASE_SECRET_KEYS","SUPABASE_SERVICE_ROLE_KEY");if(!url||!pub||!secret)return out(req,503,{error:"Integration service unavailable"});
  const userDb=createClient(url,pub,{global:{headers:{Authorization:auth}},auth:{persistSession:false}}),admin=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});
  await admin.from("integration_runtime_config").upsert({id:true,project_url:url,updated_at:new Date().toISOString()},{onConflict:"id"});
  const {data:authData,error:authError}=await userDb.auth.getUser();if(authError||!authData.user)return out(req,401,{error:"Session could not be verified"});const user=authData.user;
  const {data:ent,error:entError}=await userDb.rpc("get_my_entitlement");if(entError)return out(req,403,{error:"Plan could not be verified"});const row=Array.isArray(ent)?ent[0]:ent,plan=normalizePlan(row?.plan_tier);if(!PLANS.has(plan))return out(req,403,{error:"Watchdog Integrations requires Pro+ or Teams",required_plan:"pro_plus",plan});
  let body:Obj={};try{body=await req.json()}catch{return out(req,400,{error:"Invalid JSON"})}const action=clean(body.action,60);
  const audit=async(connectionId:string|null,kind:string,details:Obj={})=>{await admin.from("integration_audit_log").insert({user_id:user.id,connection_id:connectionId,action:kind,actor:"user",details});};
  const owned=async(id:string)=>{const {data}=await admin.from("integration_connections").select("*").eq("id",id).eq("user_id",user.id).maybeSingle();return data||null;};
  const view=(c:Obj)=>({id:c.id,provider:c.provider,name:c.name,status:c.status,direction:c.direction,outbound_url:c.outbound_url,event_types:c.event_types||[],scopes:c.scopes||[],intelligence_access:!!c.intelligence_access,intelligence_access_updated_at:c.intelligence_access_updated_at||null,intelligence_access_updated_by:c.intelligence_access_updated_by||null,external_account_label:c.external_account_label||null,last_inbound_at:c.last_inbound_at||null,last_outbound_at:c.last_outbound_at||null,last_error:c.last_error||null,created_at:c.created_at,updated_at:c.updated_at,inbound_configured:!!c.inbound_token_hash,outbound_signing_configured:!!c.outbound_secret_id,inbound_url:`${url}/functions/v1/integration-webhook?connection=${encodeURIComponent(c.id)}`});

  if(action==="status")return out(req,200,{ok:true,plan,phase:3,capabilities:{generic_webhooks:true,zapier_keys:true,inbound_crm_context:true,field_mapping:true,outbound_signing:true,retry_history:true,intelligence_context_toggle:true},supported_events:[...EVENTS],supported_scopes:[...SCOPES],mapping_fields:[...MAPPING_KEYS]});
  if(action==="connections.list"){const {data,error}=await admin.from("integration_connections").select("*").eq("user_id",user.id).neq("status","revoked").order("created_at",{ascending:false});if(error)return out(req,503,{error:"Connections could not be loaded"});const ids=(data||[]).map((x:Obj)=>x.id);const maps=ids.length?await admin.from("integration_field_mappings").select("connection_id,updated_at").eq("user_id",user.id).in("connection_id",ids):{data:[] as Obj[]};const mm=new Map((maps.data||[]).map((x:Obj)=>[x.connection_id,x.updated_at]));return out(req,200,{connections:(data||[]).map((c:Obj)=>({...view(c),mapping_configured:mm.has(c.id),mapping_updated_at:mm.get(c.id)||null})),plan});}
  if(action==="connection.create"){
    const id=crypto.randomUUID(),direction=normalizeDirection(body.direction),name=clean(body.name||"Webhook connection",100),outboundUrl=(direction==="outbound"||direction==="bidirectional")?publicHttps(body.outbound_url):null;if((direction==="outbound"||direction==="bidirectional")&&!outboundUrl)return out(req,400,{error:"A public HTTPS outbound URL is required"});
    const eventTypes=normalizeEvents(body.event_types),scopes=normalizeScopes(body.scopes,direction),inboundToken=(direction==="inbound"||direction==="bidirectional")?randomToken():null,inboundHash=inboundToken?await sha256(inboundToken):null,outboundSecret=(direction==="outbound"||direction==="bidirectional")?randomToken():null;
    let secretId:string|null=null;if(outboundSecret){const stored=await admin.rpc("integration_store_secret",{p_secret:outboundSecret,p_name:`integration:${id}`,p_description:`Watchdog outbound HMAC secret for ${name}`});if(stored.error||!stored.data)return out(req,503,{error:"Signing secret could not be stored"});secretId=String(stored.data);}
    const inserted=await admin.from("integration_connections").insert({id,user_id:user.id,provider:"webhook",name,status:"active",direction,outbound_url:outboundUrl,outbound_secret_id:secretId,inbound_token_hash:inboundHash,event_types:eventTypes,scopes,intelligence_access:false,external_account_label:clean(body.external_account_label,120)||null,metadata:{phase:3,created_via:"integration_center"}}).select("*").single();
    if(inserted.error){if(secretId)await admin.rpc("integration_delete_secret",{p_secret_id:secretId});return out(req,503,{error:"Connection could not be created"});}
    await audit(id,"connection.created",{direction,event_types:eventTypes,scopes});return out(req,201,{connection:view(inserted.data),credentials:{inbound_token:inboundToken,outbound_signing_secret:outboundSecret,shown_once:true}});
  }
  if(action==="connection.update"){
    const id=clean(body.connection_id,80),c=await owned(id);if(!c)return out(req,404,{error:"Connection not found"});if(c.status==="revoked")return out(req,409,{error:"Revoked connections cannot be edited"});
    const now=new Date().toISOString(),patch:Obj={updated_at:now};if(body.name!==undefined)patch.name=clean(body.name,100)||c.name;if(body.status!==undefined){const s=clean(body.status,20);if(!["active","paused"].includes(s))return out(req,400,{error:"Invalid status"});patch.status=s;}if(body.outbound_url!==undefined&&(c.direction==="outbound"||c.direction==="bidirectional")){const u=publicHttps(body.outbound_url);if(!u)return out(req,400,{error:"A public HTTPS outbound URL is required"});patch.outbound_url=u;}if(body.event_types!==undefined)patch.event_types=normalizeEvents(body.event_types);if(body.scopes!==undefined)patch.scopes=normalizeScopes(body.scopes,c.direction);if(body.external_account_label!==undefined)patch.external_account_label=clean(body.external_account_label,120)||null;if(body.intelligence_access!==undefined){const nextScopes=(patch.scopes||c.scopes||[]) as string[];patch.intelligence_access=!!body.intelligence_access&&nextScopes.includes("intelligence.context.read");patch.intelligence_access_updated_at=now;patch.intelligence_access_updated_by="user";}
    const updated=await admin.from("integration_connections").update(patch).eq("id",id).eq("user_id",user.id).select("*").single();if(updated.error)return out(req,503,{error:"Connection could not be updated"});await audit(id,"connection.updated",{fields:Object.keys(patch).filter(x=>x!=="updated_at")});if(body.intelligence_access!==undefined&&!!c.intelligence_access!==!!updated.data.intelligence_access)await audit(id,"intelligence.context.permission_changed",{enabled:!!updated.data.intelligence_access});return out(req,200,{connection:view(updated.data)});
  }
  if(action==="mapping.get"){
    const id=clean(body.connection_id,80),c=await owned(id);if(!c)return out(req,404,{error:"Connection not found"});const {data,error}=await admin.from("integration_field_mappings").select("mapping,updated_at").eq("user_id",user.id).eq("connection_id",id).maybeSingle();if(error)return out(req,503,{error:"Field mapping could not be loaded"});return out(req,200,{connection_id:id,mapping:data?.mapping||{},updated_at:data?.updated_at||null});
  }
  if(action==="mapping.update"){
    const id=clean(body.connection_id,80),c=await owned(id);if(!c||c.status==="revoked")return out(req,404,{error:"Connection not found"});if(!["inbound","bidirectional"].includes(c.direction))return out(req,409,{error:"Field mapping applies only to inbound CRM connections"});const mapping=normalizeMapping(body.mapping);const now=new Date().toISOString();const saved=await admin.from("integration_field_mappings").upsert({user_id:user.id,connection_id:id,mapping,updated_at:now},{onConflict:"user_id,connection_id"}).select("mapping,updated_at").single();if(saved.error)return out(req,503,{error:"Field mapping could not be saved"});await audit(id,"field_mapping.updated",{mapped_fields:Object.keys(mapping)});return out(req,200,{connection_id:id,mapping:saved.data.mapping,updated_at:saved.data.updated_at});
  }
  if(action==="context.summary"){
    const [total,withProperty,latest]=await Promise.all([admin.from("integration_crm_context").select("*",{count:"exact",head:true}).eq("user_id",user.id),admin.from("integration_crm_context").select("*",{count:"exact",head:true}).eq("user_id",user.id).not("property_ref","is",null),admin.from("integration_crm_context").select("connection_id,updated_at,last_activity_at,source_updated_at").eq("user_id",user.id).order("updated_at",{ascending:false}).limit(1)]);return out(req,200,{crm_records:Number(total.count||0),property_linked:Number(withProperty.count||0),latest:latest.data?.[0]||null});
  }
  if(action==="connection.rotate"){
    const id=clean(body.connection_id,80),c=await owned(id);if(!c||c.status==="revoked")return out(req,404,{error:"Connection not found"});const inboundToken=(c.direction==="inbound"||c.direction==="bidirectional")?randomToken():null,outboundSecret=(c.direction==="outbound"||c.direction==="bidirectional")?randomToken():null;let newSecretId:string|null=null;if(outboundSecret){const stored=await admin.rpc("integration_store_secret",{p_secret:outboundSecret,p_name:`integration:${id}:${Date.now()}`,p_description:`Rotated Watchdog outbound HMAC secret for ${c.name}`});if(stored.error||!stored.data)return out(req,503,{error:"New signing secret could not be stored"});newSecretId=String(stored.data);}
    const patch={inbound_token_hash:inboundToken?await sha256(inboundToken):null,outbound_secret_id:newSecretId,updated_at:new Date().toISOString(),last_error:null};const updated=await admin.from("integration_connections").update(patch).eq("id",id).eq("user_id",user.id).select("*").single();if(updated.error){if(newSecretId)await admin.rpc("integration_delete_secret",{p_secret_id:newSecretId});return out(req,503,{error:"Credentials could not be rotated"});}if(c.outbound_secret_id)await admin.rpc("integration_delete_secret",{p_secret_id:c.outbound_secret_id});await audit(id,"credentials.rotated",{});return out(req,200,{connection:view(updated.data),credentials:{inbound_token:inboundToken,outbound_signing_secret:outboundSecret,shown_once:true}});
  }
  if(action==="connection.revoke"){
    const id=clean(body.connection_id,80),c=await owned(id);if(!c)return out(req,404,{error:"Connection not found"});await admin.from("integration_connections").update({status:"revoked",inbound_token_hash:null,outbound_secret_id:null,updated_at:new Date().toISOString()}).eq("id",id).eq("user_id",user.id);await admin.from("integration_deliveries").update({status:"canceled",updated_at:new Date().toISOString()}).eq("connection_id",id).eq("user_id",user.id).in("status",["pending","processing"]);if(c.outbound_secret_id)await admin.rpc("integration_delete_secret",{p_secret_id:c.outbound_secret_id});await audit(id,"connection.revoked",{});return out(req,200,{ok:true});
  }
  if(action==="delivery.test"){
    const id=clean(body.connection_id,80),c=await owned(id);if(!c||c.status!=="active"||!["outbound","bidirectional"].includes(c.direction)||!c.outbound_url)return out(req,409,{error:"Active outbound connection required"});const eventKey=`test:${crypto.randomUUID()}`,event=await admin.from("integration_events").insert({user_id:user.id,direction:"outbound",event_type:"integration.test",event_key:eventKey,source:"watchdog.integration_center",status:"queued",payload:{message:"Watchdog integration test",connection_name:c.name,sent_at:new Date().toISOString()}}).select("id").single();if(event.error)return out(req,503,{error:"Test event could not be queued"});const delivery=await admin.from("integration_deliveries").insert({event_id:event.data.id,connection_id:id,user_id:user.id,status:"pending",next_attempt_at:new Date().toISOString()}).select("id").single();if(delivery.error)return out(req,503,{error:"Test delivery could not be queued"});let headers:Record<string,string>={"Content-Type":"application/json"};const automation=Deno.env.get("WATCHDOG_AUTOMATION_SECRET")||Deno.env.get("AGENT_DIGEST_CRON_SECRET")||"";if(automation)headers["x-watchdog-automation-secret"]=automation;else{const internal=await admin.rpc("integration_get_named_secret",{p_name:"integration_delivery_worker_token"});if(internal.data)headers["x-watchdog-worker-token"]=String(internal.data);}fetch(`${url}/functions/v1/integration-delivery-worker`,{method:"POST",headers,body:JSON.stringify({delivery_id:delivery.data.id})}).catch(()=>{});await audit(id,"delivery.test_queued",{delivery_id:delivery.data.id});return out(req,202,{ok:true,delivery_id:delivery.data.id});
  }
  if(action==="events.list"){
    const limit=Math.min(Math.max(Number(body.limit||30),1),50),deliveries=await admin.from("integration_deliveries").select("*").eq("user_id",user.id).order("created_at",{ascending:false}).limit(limit);if(deliveries.error)return out(req,503,{error:"Delivery history could not be loaded"});const ds=deliveries.data||[],eventIds=[...new Set(ds.map((d:Obj)=>d.event_id))],connectionIds=[...new Set(ds.map((d:Obj)=>d.connection_id))];const [ev,cn,at]=await Promise.all([eventIds.length?admin.from("integration_events").select("id,event_type,event_key,source,status,payload,occurred_at,created_at").in("id",eventIds):Promise.resolve({data:[]}),connectionIds.length?admin.from("integration_connections").select("id,name,provider").in("id",connectionIds):Promise.resolve({data:[]}),ds.length?admin.from("integration_delivery_attempts").select("delivery_id,attempt_no,status,response_status,response_excerpt,error_code,duration_ms,created_at").in("delivery_id",ds.map((d:Obj)=>d.id)).order("created_at",{ascending:false}):Promise.resolve({data:[]})]);const em=new Map((ev.data||[]).map((x:Obj)=>[x.id,x])),cm=new Map((cn.data||[]).map((x:Obj)=>[x.id,x]));return out(req,200,{deliveries:ds.map((d:Obj)=>({...d,event:em.get(d.event_id)||null,connection:cm.get(d.connection_id)||null,attempts:(at.data||[]).filter((a:Obj)=>a.delivery_id===d.id)}))});
  }
  return out(req,400,{error:"Unknown action"});
});