import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.95.0";

type Row = Record<string, any>;
const RANK: Record<string, number> = { standard:0, agent:1, pro:2, pro_plus:3, teams:4, developer:5 };
const GEOCODER = "https://geo.nj.gov/arcgis/rest/services/Tasks/NJ_Geocode/GeocodeServer/findAddressCandidates";
const ELECTRIC = "https://mapsdep.nj.gov/arcgis/rest/services/Features/Utilities/MapServer/10/query";
const SOLAR_BTM = "https://mapsdep.nj.gov/arcgis/rest/services/Features/Utilities/MapServer/22/query";
const SOLAR_LAYER = "https://mapsdep.nj.gov/arcgis/rest/services/Features/Utilities/MapServer/22";
const ELECTRIC_LAYER = "https://mapsdep.nj.gov/arcgis/rest/services/Features/Utilities/MapServer/10";
const DCA = "https://data.nj.gov/resource/w9se-dmra.json";
const DCA_PAGE = "https://data.nj.gov/resource/w9se-dmra";
const ORIGINS = new Set(["https://watchdogindex.com","https://www.watchdogindex.com","http://localhost:3000","http://127.0.0.1:3000"]);
const clean=(v:unknown,n=1000)=>String(v??"").replace(/[<>]/g,"").trim().slice(0,n);
const safe=(v:unknown)=>(v&&typeof v==="object"&&!Array.isArray(v)?v as Row:{});
const cors=(r:Request)=>({"Access-Control-Allow-Origin":ORIGINS.has(r.headers.get("origin")||"")?(r.headers.get("origin")||""):"https://www.watchdogindex.com","Access-Control-Allow-Headers":"authorization,apikey,content-type,x-client-info","Access-Control-Allow-Methods":"POST,OPTIONS","Vary":"Origin"});
const respond=(r:Request,s:number,b:unknown)=>new Response(JSON.stringify(b),{status:s,headers:{...cors(r),"Content-Type":"application/json","Cache-Control":"private, no-store"}});
const district=(tx:Row)=>{const p=clean(tx.pams_pin,100);return /^\d{4}/.test(p)?p.slice(0,4):""};
const escSql=(v:string)=>v.replace(/'/g,"''");
const solarWords=/\b(solar|photovoltaic|photo voltaic|pv system|pv array|solar panel|solar electric|roof mounted pv|ground mounted pv)\b/i;
const providerPortal=(name:string)=>{
  const n=name.toLowerCase();
  if(n.includes("atlantic city electric"))return "https://www.atlanticcityelectric.com/";
  if(n.includes("jersey central")||n.includes("jcpl")||n.includes("jcp&l"))return "https://www.firstenergycorp.com/jersey_central_power_light.html";
  if(n.includes("public service electric")||n.includes("pse&g")||n.includes("pseg"))return "https://nj.pseg.com/";
  if(n.includes("rockland"))return "https://www.oru.com/en/about-us/company-information/orange-rockland-service-territory/new-jersey";
  if(n.includes("sussex rural"))return "https://www.sussexrec.com/";
  return null;
};
function normStreet(v:unknown){return clean(v,220).toUpperCase().split(",")[0].replace(/\b(STREET)\b/g,"ST").replace(/\b(ROAD)\b/g,"RD").replace(/\b(AVENUE)\b/g,"AVE").replace(/\b(COURT)\b/g,"CT").replace(/\b(DRIVE)\b/g,"DR").replace(/\b(LANE)\b/g,"LN").replace(/\b(PLACE)\b/g,"PL").replace(/\b(BOULEVARD)\b/g,"BLVD").replace(/[^A-Z0-9 ]+/g," ").replace(/\s+/g," ").trim()}
async function hash(v:unknown){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(JSON.stringify(v)));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function json(url:string,timeout=12000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{headers:{"User-Agent":"Watchdog-Transaction-Energy/1.0 (+https://www.watchdogindex.com/)",Accept:"application/json"},signal:c.signal});const data=await r.json().catch(()=>({}));return {ok:r.ok,status:r.status,data}}catch(e){return {ok:false,status:0,data:{error:clean(e,240)}}}finally{clearTimeout(t)}}
async function geocode(tx:Row){const single=[tx.address,tx.city,tx.state||"NJ",tx.postal_code].filter(Boolean).join(", ");if(!single)return null;const q=new URLSearchParams({SingleLine:single,f:"json",outFields:"Match_addr,Addr_type,Score",maxLocations:"1",outSR:"4326"});const r=await json(`${GEOCODER}?${q}`);const c=r.data?.candidates?.[0];if(!r.ok||!c?.location||Number(c.score||0)<70)return null;return {x:Number(c.location.x),y:Number(c.location.y),score:Number(c.score||0),match:clean(c.address,240)}}
async function electricAt(point:Row){const q=new URLSearchParams({geometry:`${point.x},${point.y}`,geometryType:"esriGeometryPoint",inSR:"4326",spatialRel:"esriSpatialRelIntersects",outFields:"NAME",returnGeometry:"false",f:"json"});const r=await json(`${ELECTRIC}?${q}`);const names=[...new Set((r.data?.features||[]).map((x:Row)=>clean(x?.attributes?.NAME,160)).filter(Boolean))];return {ok:r.ok,names}}
async function solarNear(point:Row,tx:Row){const q=new URLSearchParams({geometry:`${point.x},${point.y}`,geometryType:"esriGeometryPoint",inSR:"4326",distance:"150",units:"esriSRUnit_Meter",spatialRel:"esriSpatialRelIntersects",outFields:"PROJECTNUM,ACCT_NUM,COMPNAME,INSTALLADD,INSTALLCIT,INSTALLZIP,YEAR,SYSTEMSIZE,CUST_TYPE,THIRDPARTY,EDC,LATITUDE,LONGITUDE",returnGeometry:"false",f:"json"});const r=await json(`${SOLAR_BTM}?${q}`);const wanted=normStreet(tx.address);const exact=(r.data?.features||[]).map((x:Row)=>x.attributes||{}).filter((a:Row)=>normStreet(a.INSTALLADD)===wanted);return {ok:r.ok,records:exact.slice(0,8),nearby_count:(r.data?.features||[]).length}}
function permitDescription(row:Row){for(const k of ["descriptionofwork","workdescription","workdesc","description","worktype","permit_type"]){const v=clean(row?.[k],500);if(v)return v}return ""}
async function solarPermits(tx:Row){const d=district(tx),block=clean(tx.block,50),lot=clean(tx.lot,50);if(!d||!block||!lot)return {ok:false,records:[]};const where=`treasurycode='${escSql(d)}' AND block='${escSql(block)}' AND lot='${escSql(lot)}'`;const q=new URLSearchParams({$where:where,$limit:"5000",$order:"permitdate DESC"});const r=await json(`${DCA}?${q}`);const records=(Array.isArray(r.data)?r.data:[]).filter((x:Row)=>solarWords.test(permitDescription(x))).slice(0,20).map((x:Row)=>({permit_number:clean(x.permitno,120),permit_date:clean(x.permitdate,80)||null,certificate_date:clean(x.certdate,80)||null,status:clean(x.status,20)||null,description:permitDescription(x)}));return {ok:r.ok,records}}
async function mapLimit<T,R>(rows:T[],n:number,fn:(row:T)=>Promise<R>){const out=new Array<R>(rows.length);let i=0;async function worker(){while(true){const x=i++;if(x>=rows.length)return;out[x]=await fn(rows[x])}}await Promise.all(Array.from({length:Math.min(n,rows.length||1)},worker));return out}

Deno.serve(async(req:Request)=>{
  if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});if(req.method!=="POST")return respond(req,405,{error:"POST required"});
  const auth=req.headers.get("authorization")||"";if(!auth.startsWith("Bearer "))return respond(req,401,{error:"Sign in required"});
  const url=Deno.env.get("SUPABASE_URL")||"",anon=Deno.env.get("SUPABASE_ANON_KEY")||"",service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";if(!url||!anon||!service)return respond(req,503,{error:"Energy evidence configuration incomplete"});
  const uc=createClient(url,anon,{global:{headers:{Authorization:auth}},auth:{persistSession:false}}),admin=createClient(url,service,{auth:{persistSession:false}});const {data:who}=await uc.auth.getUser();const user=who?.user;if(!user)return respond(req,401,{error:"Session invalid"});
  const [{data:ent},{data:prof}]=await Promise.all([admin.from("account_entitlements").select("plan_tier").eq("user_id",user.id).maybeSingle(),admin.from("profiles").select("account_role").eq("id",user.id).maybeSingle()]);const plan=prof?.account_role==="developer"?"developer":String(ent?.plan_tier||"standard");if((RANK[plan]??0)<RANK.pro_plus)return respond(req,403,{error:"Pro+ required"});
  let body:Row={};try{body=await req.json()}catch{return respond(req,400,{error:"Invalid JSON"})}const ids=[...new Set((Array.isArray(body.transaction_ids)?body.transaction_ids:[]).map((x:unknown)=>clean(x,80)).filter(Boolean))].slice(0,50);if(!ids.length)return respond(req,400,{error:"transaction_ids required"});
  const {data:txs,error:txErr}=await admin.from("transaction_workspaces").select("id,user_id,address,city,state,postal_code,municipality,county,block,lot,qualifier,pams_pin").eq("user_id",user.id).in("id",ids);if(txErr)return respond(req,503,{error:"Transactions unavailable"});
  const checkedAt=new Date().toISOString();
  for(const tx of txs||[])await admin.from("transaction_items").upsert({transaction_id:tx.id,user_id:user.id,category:"tax_municipal",item_key:"electric_utility",title:"Electric utility / account transfer",description:"Identify the electric distribution utility and confirm account transfer/final-bill requirements directly with the utility.",severity:"review",state:"open",evidence_state:"unknown",assigned_role:"agent",sort_order:95,payload:{}},{onConflict:"transaction_id,item_key",ignoreDuplicates:true});
  const {data:items}=await admin.from("transaction_items").select("id,transaction_id,item_key,payload").eq("user_id",user.id).in("transaction_id",ids).in("item_key",["solar","electric_utility"]);const itemMap=new Map<string,Row>();for(const i of items||[])itemMap.set(`${i.transaction_id}:${i.item_key}`,i);
  const results=await mapLimit(txs||[],4,async(tx:Row)=>{
    const [point,permits]=await Promise.all([geocode(tx),solarPermits(tx)]);let electric={ok:false,names:[] as string[]},solar={ok:false,records:[] as Row[],nearby_count:0};if(point){[electric,solar]=await Promise.all([electricAt(point),solarNear(point,tx)])}
    const patch=async(key:string,v:Row)=>{const it=itemMap.get(`${tx.id}:${key}`);if(!it)return;await admin.from("transaction_items").update({...v,payload:{...safe(it.payload),...safe(v.payload)},updated_at:checkedAt}).eq("id",it.id).eq("user_id",user.id)};
    const utilityNames=electric.names||[],utility=utilityNames.length===1?utilityNames[0]:"",portal=utility?providerPortal(utility):null;
    if(utility){await patch("electric_utility",{evidence_state:"verify",severity:"review",source_type:"official_service_territory",source_label:"NJDEP Electric Utilities Territory Map",source_url:ELECTRIC_LAYER,source_checked_at:checkedAt,description:`NJDEP service-territory data identifies ${utility} as the electric distribution utility at this location. Current customer balance, final bill and transfer status are private account data and still require customer-authorized verification.`,payload:{provider_name:utility,provider_portal:portal,service_territory_checked:true,geocode_match:point?.match||null,account_balance_state:"customer_authorization_required",final_bill_clearance:false}})}else{await patch("electric_utility",{evidence_state:"verify",severity:"review",source_type:"official_service_territory",source_label:"NJDEP Electric Utilities Territory Map",source_url:ELECTRIC_LAYER,source_checked_at:checkedAt,description:"Watchdog checked the statewide electric service-territory source but could not resolve a single utility for this address. Verify the electric provider before closing.",payload:{provider_name:null,service_territory_checked:Boolean(point),account_balance_state:"provider_identity_unresolved",final_bill_clearance:false}})}
    const solarRecords=solar.records||[],permitRecords=permits.records||[],solarObserved=solarRecords.length>0||permitRecords.length>0,thirdParty=solarRecords.some((r:Row)=>/^y(es)?$/i.test(clean(r.THIRDPARTY,20))),edcs=[...new Set(solarRecords.map((r:Row)=>clean(r.EDC,120)).filter(Boolean))];
    const publicRecords=solarRecords.map((r:Row)=>({project_number:clean(r.PROJECTNUM,80)||null,program_account_number:clean(r.ACCT_NUM,80)||null,company_on_program_record:clean(r.COMPNAME,180)||null,installation_address:clean(r.INSTALLADD,200)||null,completion_year:r.YEAR||null,system_size_kw:Number.isFinite(Number(r.SYSTEMSIZE))?Number(r.SYSTEMSIZE):null,customer_type:clean(r.CUST_TYPE,80)||null,third_party_ownership:clean(r.THIRDPARTY,20)||null,electric_distribution_company:clean(r.EDC,120)||null}));
    const solarDescription=solarObserved?(thirdParty?"Public solar evidence was matched to this property, and the NJDEP program record indicates third-party ownership. Confirm lease/PPA/financing transfer and payoff requirements with the seller and provider before closing.":"Public solar evidence was matched to this property. Confirm whether the system is owned, financed, leased or under a PPA and obtain transfer/payoff documents before closing."):"No property-specific solar record was matched in the checked public solar/permit sources. These public sources are not complete enough to prove that no solar system exists, so seller/provider verification is still required.";
    await patch("solar",{evidence_state:solarObserved?"verify":"verify",severity:solarObserved?"attention":"review",source_type:"public_solar_evidence",source_label:"NJ DCA permits + NJDEP Solar PV BTM",source_url:solarRecords.length?SOLAR_LAYER:DCA_PAGE,source_checked_at:checkedAt,description:solarDescription,payload:{solar_observed:solarObserved,third_party_ownership_observed:thirdParty,solar_program_records:publicRecords,solar_permit_records:permitRecords,electric_distribution_companies:edcs,public_sources_checked:[DCA_PAGE,SOLAR_LAYER],coverage_note:"NJDEP Solar PV BTM layer is a public historical program layer; DCA permit data and seller/provider documents remain necessary for current transfer/payoff verification.",payoff_balance_state:"customer_or_provider_authorization_required"}});
    const evidence={electric:{utility_names:utilityNames,provider_portal:portal},solar:{solar_observed:solarObserved,third_party:thirdParty,program_records:publicRecords,permit_records:permitRecords}};await admin.from("transaction_evidence_observations").upsert({transaction_id:tx.id,user_id:user.id,pams_pin:tx.pams_pin,evidence_key:"energy_and_solar",provider_key:"njdep-dca-free",evidence_status:solarObserved?"verify":"verify",value:evidence,source_label:"NJDEP + NJ DCA public energy sources",source_url:ELECTRIC_LAYER,source_checked_at:checkedAt,facts_hash:await hash(evidence),metadata:{electric_balance_private:true,solar_payoff_private:true,title_clearance:false}},{onConflict:"transaction_id,evidence_key,provider_key,facts_hash",ignoreDuplicates:true});
    return {transaction_id:tx.id,electric_provider:utility||null,solar_observed:solarObserved,solar_program_records:solarRecords.length,solar_permit_records:permitRecords.length};
  });
  return respond(req,200,{ok:true,checked_at:checkedAt,results});
});
