import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.95.0";

type Obj=Record<string,any>;
const VERSION="watchdog-crm-analyst-v2";
const TOOL_VERSION="watchdog-crm-tools-v1";
const PLANS=new Set(["pro_plus","teams","developer"]);
const ORIGINS=new Set(["https://njpropertytaxrelief.com","https://www.njpropertytaxrelief.com","http://localhost:3000","http://127.0.0.1:3000"]);
function clean(v:unknown,max=1000){return String(v??"").replace(/[<>]/g,"").trim().slice(0,max);}
function planName(v:unknown){return clean(v,30).toLowerCase().replace("pro+","pro_plus")||"standard";}
function namedEnv(jsonName:string,legacyName:string){const raw=Deno.env.get(jsonName)||"";if(raw){try{const x=JSON.parse(raw);if(x?.default)return String(x.default)}catch{}}return Deno.env.get(legacyName)||"";}
function cors(req:Request){const o=req.headers.get("origin")||"";const allow=ORIGINS.has(o)||/^https:\/\/[a-z0-9-]+\.vercel\.app$/i.test(o)?o:"https://njpropertytaxrelief.com";return{"Access-Control-Allow-Origin":allow,"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"};}
function out(req:Request,status:number,payload:unknown){return new Response(JSON.stringify(payload),{status,headers:{...cors(req),"Content-Type":"application/json","Cache-Control":"private, no-store"}});}
function safeObj(v:unknown,max=20000):Obj{if(!v||typeof v!=="object"||Array.isArray(v))return{};try{return JSON.stringify(v).length<=max?v as Obj:{}}catch{return{}}}
function refusal(prompt:string){const target=/\b(find|rank|target|filter|exclude|include|prioritize|prospect)\b/i.test(prompt),protectedTerm=/\b(race|racial|ethnic|ethnicity|religion|religious|disability|disabled|familial status|families with children|national origin|sex|gender|sexual orientation|pregnan|marital status)\b/i.test(prompt);if(target&&protectedTerm)return"Watchdog cannot rank, target, include, or exclude housing opportunities using protected or sensitive personal characteristics.";if(/\b(likely to sell|will sell|motivated seller|distressed owner|desperate owner|foreclosure likelihood|divorce|death|health condition)\b/i.test(prompt))return"Watchdog does not infer seller intent, personal distress, private life events, or a person's likelihood to transact.";return null;}
function searchText(prompt:string){const q=prompt.match(/["“]([^"”]{2,100})["”]/);if(q&&/\b(crm|boldtrail|kvcore|lead|contact|client)\b/i.test(prompt))return clean(q[1],100);return"";}
function recordLine(r:Obj){const name=clean(r.contact_name,120)||"CRM contact",stage=clean(r.lead_stage,80)||"stage not supplied",rel=clean(r.relationship||r.deal_type,80)||"relationship not supplied",source=clean(r.source||r.system_source,100)||"source not supplied",agent=clean(r.assigned_agent_external_id||r.assigned_agent_id,80);return`${name}: ${stage}; ${rel}; source ${source}${agent?`; assigned agent reference ${agent}`:""}.`;}
function buildResponse(data:Obj,mode:string){const records=Array.isArray(data.records)?data.records:[],summary=data.summary||{},evidence=records.slice(0,12).map(recordLine),missing:string[]=[],caveats=["CRM context is customer-controlled relationship/workflow data. It does not replace Watchdog's governed property facts.","Lead stage and relationship labels are reported CRM workflow state, not Watchdog predictions of seller intent or transaction likelihood.","This CRM-aware response is deterministic in Phase 5. CRM record content was not sent to the external prose model."];
  let conclusion="";
  if(mode==="property"){
    const linked=Number(summary.verified_property_links||0);
    if(records.length)conclusion=`Watchdog found ${records.length} authorized CRM relationship record${records.length===1?"":"s"} with a verified link to the selected governed property scope.`;
    else{conclusion=`Watchdog can access ${Number(summary.authorized_records||0).toLocaleString()} authorized CRM record${Number(summary.authorized_records||0)===1?"":"s"}, but none has a verified CRM-to-property link for the selected property scope.`;missing.push("No explicit or user-verified CRM property relationship is available for the selected property. Watchdog did not infer one from a person's name.");if(!linked)missing.push("The authorized CRM dataset currently contains no verified Watchdog property links.");}
  }else if(mode==="search")conclusion=records.length?`Watchdog found ${records.length} authorized CRM record${records.length===1?"":"s"} matching that CRM search.`:"No authorized CRM record matched that search.";
  else conclusion=`Watchdog has ${Number(summary.authorized_records||0).toLocaleString()} CRM relationship record${Number(summary.authorized_records||0)===1?"":"s"} authorized for Intelligence. ${records.length?`The ${records.length} most recently updated records in this response are shown below.`:"No records were returned in this response."}`;
  return{conclusion,evidence,missing_evidence:missing,caveats,suggested_actions:[],sources:[],crm_context:{authorized_records:Number(summary.authorized_records||0),verified_property_links:Number(summary.verified_property_links||0),returned_records:records.length,mode,truth_policy:data.truth_policy||null,privacy:data.privacy||null}};
}

Deno.serve(async(req)=>{
  if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});if(req.method!=="POST")return out(req,405,{error:"POST required"});
  const origin=req.headers.get("origin")||"";if(origin&&!ORIGINS.has(origin)&&!/^https:\/\/[a-z0-9-]+\.vercel\.app$/i.test(origin))return out(req,403,{error:"Origin not allowed"});
  const auth=req.headers.get("authorization")||"";if(!auth.startsWith("Bearer "))return out(req,401,{error:"Sign in required"});
  const url=Deno.env.get("SUPABASE_URL")||"",pub=namedEnv("SUPABASE_PUBLISHABLE_KEYS","SUPABASE_ANON_KEY"),secret=namedEnv("SUPABASE_SECRET_KEYS","SUPABASE_SERVICE_ROLE_KEY");if(!url||!pub||!secret)return out(req,503,{error:"CRM Analyst configuration incomplete"});
  const userDb=createClient(url,pub,{global:{headers:{Authorization:auth}},auth:{persistSession:false}}),admin=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});const {data:authData}=await userDb.auth.getUser(),user=authData?.user;if(!user)return out(req,401,{error:"Session invalid"});
  const {data:ent,error:entError}=await userDb.rpc("get_my_entitlement");if(entError)return out(req,403,{error:"Plan could not be verified"});const entRow=Array.isArray(ent)?ent[0]:ent,planTier=planName(entRow?.plan_tier);if(!PLANS.has(planTier))return out(req,403,{error:"CRM-aware Watchdog Intelligence requires Pro+ with an authorized integration or Teams",required_plan:"pro_plus",plan:planTier});
  let body:Obj={};try{body=await req.json()}catch{return out(req,400,{error:"Invalid JSON"})}const prompt=clean(body.prompt,1800);if(!prompt)return out(req,400,{error:"prompt is required"});const context=safeObj(body.context),pins=[...new Set((Array.isArray(context.pams_pins)?context.pams_pins:[]).map((x:unknown)=>clean(x,120)).filter((x:string)=>/^\d{4}_.+/.test(x)))].slice(0,50),blocked=refusal(prompt);
  let sessionId=clean(body.session_id,80),session:Obj|null=null;if(sessionId){const q=await admin.from("intelligence_analyst_sessions").select("id,user_id,context,profession").eq("id",sessionId).eq("user_id",user.id).maybeSingle();session=q.data;if(!session)return out(req,404,{error:"Analyst session not found"});}else{const q=await admin.from("intelligence_analyst_sessions").insert({user_id:user.id,profession:clean(context.profession,80)||"general",context,title:prompt.slice(0,90)}).select("id,context,profession").single();if(q.error||!q.data)return out(req,503,{error:"Could not start Analyst session"});session=q.data;sessionId=String(q.data.id);}
  const userMessage=await admin.from("intelligence_analyst_messages").insert({session_id:sessionId,user_id:user.id,role:"user",content:{text:prompt},tool_contract_version:TOOL_VERSION,status:blocked?"refused":"complete"}).select("id").single();
  if(blocked){const response={conclusion:blocked,evidence:[],missing_evidence:[],caveats:["Watchdog did not access CRM context for this refused request."],suggested_actions:[],sources:[]};const m=await admin.from("intelligence_analyst_messages").insert({session_id:sessionId,user_id:user.id,role:"assistant",content:response,tool_contract_version:TOOL_VERSION,status:"refused"}).select("id").single();await admin.from("intelligence_usage_events").insert({user_id:user.id,plan_tier:planTier,event_type:"analyst_request",request_units:1,metadata:{status:"refused",reason:"crm_guardrail",analyst_version:VERSION}});return out(req,200,{ok:true,session_id:sessionId,message_id:m.data?.id||null,status:"refused",provider_status:"not_called",tool:{name:"get_crm_context",version:TOOL_VERSION},response});}
  const started=Date.now(),search=searchText(prompt),mode=pins.length?"property":search?"search":"overview";
  const call=await fetch(`${url}/functions/v1/intelligence-crm-context`,{method:"POST",headers:{Authorization:auth,apikey:pub,"Content-Type":"application/json"},body:JSON.stringify({mode,pams_pins:pins,query:search,limit:12,session_id:sessionId})});const data=await call.json().catch(()=>({}));if(!call.ok){const response={conclusion:"Watchdog could not access authorized CRM context for that request.",evidence:[],missing_evidence:[clean(data.error||`CRM context failed (${call.status})`,400)],caveats:["No CRM conclusion was generated from a failed or unauthorized context read."],suggested_actions:[],sources:[]};const m=await admin.from("intelligence_analyst_messages").insert({session_id:sessionId,user_id:user.id,role:"assistant",content:response,tool_contract_version:TOOL_VERSION,status:"failed"}).select("id").single();await admin.from("intelligence_tool_calls").insert({session_id:sessionId,message_id:userMessage.data?.id||null,user_id:user.id,tool_name:"get_crm_context",tool_version:TOOL_VERSION,arguments:{mode,pams_pin_count:pins.length,search_used:!!search},result_summary:{error:clean(data.error,300)},status:"failed",duration_ms:Date.now()-started});await admin.from("intelligence_usage_events").insert({user_id:user.id,plan_tier:planTier,event_type:"analyst_request",request_units:1,latency_ms:Date.now()-started,metadata:{status:"failed",tool:"get_crm_context",analyst_version:VERSION,provider_status:"not_called_crm_privacy_boundary"}});return out(req,200,{ok:false,session_id:sessionId,message_id:m.data?.id||null,status:"failed",provider_status:"not_called",tool:{name:"get_crm_context",version:TOOL_VERSION},response});}
  const response=buildResponse(data,mode),tool=await admin.from("intelligence_tool_calls").insert({session_id:sessionId,message_id:userMessage.data?.id||null,user_id:user.id,tool_name:"get_crm_context",tool_version:TOOL_VERSION,arguments:{mode,pams_pin_count:pins.length,search_used:!!search},result_summary:{authorized_records:Number(data.summary?.authorized_records||0),verified_property_links:Number(data.summary?.verified_property_links||0),returned_records:Number(data.summary?.returned_records||0),external_prose_provider:false},status:"complete",duration_ms:Date.now()-started}).select("id").single();const assistant=await admin.from("intelligence_analyst_messages").insert({session_id:sessionId,user_id:user.id,role:"assistant",content:response,provider:null,model:null,tool_contract_version:TOOL_VERSION,status:"complete"}).select("id").single();await admin.from("intelligence_usage_events").insert({user_id:user.id,plan_tier:planTier,event_type:"analyst_request",request_units:1,latency_ms:Date.now()-started,metadata:{status:"complete",tool:"get_crm_context",tool_version:TOOL_VERSION,analyst_version:VERSION,provider_status:"not_called_crm_privacy_boundary",authorized_records:Number(data.summary?.authorized_records||0),returned_records:Number(data.summary?.returned_records||0)}});return out(req,200,{ok:true,session_id:sessionId,message_id:assistant.data?.id||null,status:"complete",provider_status:"not_called_crm_privacy_boundary",provider:null,model:null,tool:{name:"get_crm_context",version:TOOL_VERSION,id:tool.data?.id||null},response});
});
