alter table public.backoffice_leads
  add column if not exists crm_owner text not null default 'unassigned',
  add column if not exists last_exported_at timestamptz,
  add column if not exists last_export_profile text,
  add column if not exists address_validation_provider text,
  add column if not exists address_validated_at timestamptz;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'backoffice_leads_crm_owner_check') then
    alter table public.backoffice_leads add constraint backoffice_leads_crm_owner_check check (crm_owner in ('unassigned','john','wife'));
  end if;
end $$;

create index if not exists backoffice_leads_crm_owner_export_idx on public.backoffice_leads (crm_owner, last_exported_at, created_at desc);

create table if not exists public.backoffice_export_profiles (
  profile_key text primary key,
  label text not null,
  enabled boolean not null default true,
  sort_order integer not null default 100,
  settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
insert into public.backoffice_export_profiles (profile_key,label,sort_order)
values ('john','John',10),('wife','Wife',20)
on conflict (profile_key) do update set label=excluded.label,sort_order=excluded.sort_order,enabled=true,updated_at=now();

create table if not exists public.backoffice_sessions (
  id uuid primary key default gen_random_uuid(),
  token_hash text not null unique,
  actor_label text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  revoked_at timestamptz,
  request_fingerprint text
);
create index if not exists backoffice_sessions_active_idx on public.backoffice_sessions (token_hash, expires_at) where revoked_at is null;

create table if not exists public.backoffice_auth_events (
  id bigint generated by default as identity primary key,
  actor_label text,
  event_type text not null,
  success boolean not null default false,
  request_fingerprint text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists backoffice_auth_events_fingerprint_idx on public.backoffice_auth_events (request_fingerprint, created_at desc);

create table if not exists public.backoffice_exports (
  id uuid primary key default gen_random_uuid(),
  profile_key text not null references public.backoffice_export_profiles(profile_key),
  filename text not null,
  row_count integer not null default 0 check (row_count >= 0),
  session_id uuid references public.backoffice_sessions(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists backoffice_exports_profile_created_idx on public.backoffice_exports (profile_key, created_at desc);
create index if not exists backoffice_exports_session_idx on public.backoffice_exports (session_id);

create table if not exists public.backoffice_export_items (
  export_id uuid not null references public.backoffice_exports(id) on delete cascade,
  lead_id uuid not null references public.backoffice_leads(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (export_id, lead_id)
);
create index if not exists backoffice_export_items_lead_idx on public.backoffice_export_items (lead_id, created_at desc);

alter table public.backoffice_export_profiles enable row level security;
alter table public.backoffice_sessions enable row level security;
alter table public.backoffice_auth_events enable row level security;
alter table public.backoffice_exports enable row level security;
alter table public.backoffice_export_items enable row level security;
revoke all on table public.backoffice_export_profiles,public.backoffice_sessions,public.backoffice_auth_events,public.backoffice_exports,public.backoffice_export_items from anon, authenticated;
grant all on table public.backoffice_export_profiles,public.backoffice_sessions,public.backoffice_auth_events,public.backoffice_exports,public.backoffice_export_items to service_role;

create or replace function public.backoffice_get_secret(p_name text)
returns text language plpgsql security definer set search_path=public,vault,pg_temp as $$
declare v_secret text;
begin
  if p_name not in ('backoffice_shared_access_key','google_address_validation_api_key','backoffice_ingest_secret') then raise exception 'Secret name is not allowed'; end if;
  select secret into v_secret from vault.decrypted_secrets where name=p_name order by created_at desc limit 1;
  return v_secret;
end; $$;

create or replace function public.backoffice_secret_configured(p_name text)
returns boolean language sql security definer set search_path=public,vault,pg_temp as $$
  select coalesce(length(public.backoffice_get_secret(p_name))>0,false)
$$;

create or replace function public.backoffice_verify_shared_key(p_candidate text)
returns boolean language plpgsql security definer set search_path=public,vault,extensions,pg_temp as $$
declare v_expected text;
begin
  v_expected:=public.backoffice_get_secret('backoffice_shared_access_key');
  if v_expected is null or p_candidate is null then return false; end if;
  return digest(convert_to(v_expected,'UTF8'),'sha256')=digest(convert_to(p_candidate,'UTF8'),'sha256');
end; $$;

create or replace function public.backoffice_set_secret(p_name text,p_value text,p_description text default null)
returns void language plpgsql security definer set search_path=public,vault,pg_temp as $$
declare v_id uuid;
begin
  if p_name not in ('backoffice_shared_access_key','google_address_validation_api_key','backoffice_ingest_secret') then raise exception 'Secret name is not allowed'; end if;
  if p_value is null or length(trim(p_value))<8 then raise exception 'Secret is too short'; end if;
  select id into v_id from vault.decrypted_secrets where name=p_name order by created_at desc limit 1;
  if v_id is null then perform vault.create_secret(p_value,p_name,coalesce(p_description,'Watchdog Backoffice secret'),null);
  else perform vault.update_secret(v_id,p_value,p_name,coalesce(p_description,'Watchdog Backoffice secret'),null); end if;
end; $$;

revoke all on function public.backoffice_get_secret(text),public.backoffice_secret_configured(text),public.backoffice_verify_shared_key(text),public.backoffice_set_secret(text,text,text) from public,anon,authenticated;
grant execute on function public.backoffice_get_secret(text),public.backoffice_secret_configured(text),public.backoffice_verify_shared_key(text),public.backoffice_set_secret(text,text,text) to service_role;
