import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.95.0";

type Row=Record<string,any>;
const RANK:Record<string,number>={standard:0,agent:1,pro:2,pro_plus:3,teams:4,developer:5};
const PATHS:Record<string,string>={"0901":"Bayonne","0902":"EastNewark","0903":"Guttenberg","0904":"Harrison","0905":"Hoboken","0906":"JerseyCity","0907":"Kearny","0908":"NorthBergen","0909":"Secaucus","0910":"UnionCity","0911":"Weehawken","0912":"WestNewYork"};
const ORIGINS=new Set(["https://watchdogindex.com","https://www.watchdogindex.com","http://localhost:3000","http://127.0.0.1:3000"]);
const clean=(v:unknown,n=1000)=>String(v??"").replace(/[<>]/g,"").trim().slice(0,n);
const safe=(v:unknown)=>(v&&typeof v==="object"&&!Array.isArray(v)?v as Row:{});
const cors=(r:Request)=>({"Access-Control-Allow-Origin":ORIGINS.has(r.headers.get("origin")||"")?(r.headers.get("origin")||""):"https://www.watchdogindex.com","Access-Control-Allow-Headers":"authorization,apikey,content-type,x-client-info","Access-Control-Allow-Methods":"POST,OPTIONS","Vary":"Origin"});
const json=(r:Request,s:number,b:unknown)=>new Response(JSON.stringify(b),{status:s,headers:{...cors(r),"Content-Type":"application/json","Cache-Control":"private, no-store"}});
const money=(v:unknown)=>Number(v||0).toLocaleString("en-US",{style:"currency",currency:"USD"});
const district=(tx:Row)=>{const p=clean(tx.pams_pin,80);return /^\d{4}/.test(p)?p.slice(0,4):""};
const norm=(v:unknown)=>clean(v,240).toUpperCase().replace(/[^A-Z0-9]+/g," ").replace(/\b(STREET|ST)\b/g,"ST").replace(/\b(ROAD|RD)\b/g,"RD").replace(/\b(AVENUE|AVE)\b/g,"AVE").replace(/\b(COURT|CT)\b/g,"CT").replace(/\b(DRIVE|DR)\b/g,"DR").replace(/\s+/g," ").trim();
const num=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?n:0};
async function digest(v:unknown){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(JSON.stringify(v)));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function get(url:string){const c=new AbortController(),t=setTimeout(()=>c.abort(),10000);try{const r=await fetch(url,{headers:{"User-Agent":"Mozilla/5.0 Watchdog-HLS-Evidence/1.0 (+https://www.watchdogindex.com/)","Accept":"application/json,*/*;q=0.5"},signal:c.signal});let data:any=null;try{data=await r.json()}catch{}return {ok:r.ok,status:r.status,data,url:r.url}}catch(e){return {ok:false,status:0,data:null,url,error:clean(e,200)}}finally{clearTimeout(t)}}
async function details(base:string,account:string){const d=new Date();const ds=d.toLocaleDateString("en-US",{weekday:"short",month:"short",day:"2-digit",year:"numeric"}).replace(",","");return await get(`${base}/GetAccountDetails?accountNumber=${encodeURIComponent(account)}&interestThruDate=${encodeURIComponent(ds)}`)}
async function findAccount(tx:Row){const code=district(tx),path=PATHS[code];if(!path)return null;const base=`https://apps.hlssystems.com/${path}/PropertyTaxInquiry`;const blq=[clean(tx.block,40),clean(tx.lot,40),clean(tx.qualifier,40)].filter((x,i)=>i<2||x).join("-");if(clean(tx.block)&&clean(tx.lot)){const direct=await details(base,blq);if(direct.ok&&direct.data?.validAccountNumber)return {base,response:direct.data,match:"blq"}}
 const q=clean(tx.address,200).split(",")[0];if(!q)return null;const search=await get(`${base}/GetAccounts?page=1&searchType=PropertyLocation&searchField=${encodeURIComponent(q)}`);const rows=Array.isArray(search.data?.accounts)?search.data.accounts:[];const exact=rows.filter((x:Row)=>norm(x.PropertyLocation)===norm(q)|| (clean(tx.block)&&clean(tx.lot)&&clean(x.Block)===clean(tx.block)&&clean(x.Lot)===clean(tx.lot)));if(exact.length!==1)return null;const acct=clean(exact[0].AccountNumber,80);if(!acct)return null;const det=await details(base,acct);return det.ok&&det.data?.validAccountNumber?{base,response:det.data,match:"address"}:null}

Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});if(req.method!=="POST")return json(req,405,{error:"POST required"});
 const auth=req.headers.get("authorization")||"";if(!auth.startsWith("Bearer "))return json(req,401,{error:"Sign in required"});const url=Deno.env.get("SUPABASE_URL")||"",anon=Deno.env.get("SUPABASE_ANON_KEY")||"",service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";if(!url||!anon||!service)return json(req,503,{error:"HLS provider unavailable"});
 const uc=createClient(url,anon,{global:{headers:{Authorization:auth}},auth:{persistSession:false}}),admin=createClient(url,service,{auth:{persistSession:false}});const {data:who}=await uc.auth.getUser();const user=who?.user;if(!user)return json(req,401,{error:"Session invalid"});const [{data:ent},{data:prof}]=await Promise.all([admin.from("account_entitlements").select("plan_tier").eq("user_id",user.id).maybeSingle(),admin.from("profiles").select("account_role").eq("id",user.id).maybeSingle()]);const plan=prof?.account_role==="developer"?"developer":String(ent?.plan_tier||"standard");if((RANK[plan]??0)<RANK.pro_plus)return json(req,403,{error:"Pro+ required"});
 let body:Row={};try{body=await req.json()}catch{return json(req,400,{error:"Invalid JSON"})}const ids=[...new Set((Array.isArray(body.transaction_ids)?body.transaction_ids:[]).map((x:unknown)=>clean(x,80)).filter(Boolean))].slice(0,50);if(!ids.length)return json(req,400,{error:"transaction_ids required"});
 const {data:txs}=await admin.from("transaction_workspaces").select("id,user_id,address,municipality,county,block,lot,qualifier,pams_pin").eq("user_id",user.id).in("id",ids);const keys=["property_tax_status","tax_sale_delinquency","municipal_lien_clearance","ownership_vesting","deed_recording_reference"];const {data:items}=await admin.from("transaction_items").select("id,transaction_id,item_key,payload").eq("user_id",user.id).in("transaction_id",ids).in("item_key",keys);const map=new Map<string,Row>();for(const i of items||[])map.set(`${i.transaction_id}:${i.item_key}`,i);const checkedAt=new Date().toISOString(),results:Row[]=[];
 for(const tx of txs||[]){const found=await findAccount(tx);if(!found){results.push({transaction_id:tx.id,provider:"hls",status:"not_matched_or_not_hls"});continue}const a=safe(found.response?.accountInquiryVM);const source=`${found.base}?account=${encodeURIComponent(clean(a.AccountNumber,80))}`;const label=`${clean(tx.municipality,120)||"Municipality"} · HLS Systems`;const patch=async(key:string,v:Row)=>{const it=map.get(`${tx.id}:${key}`);if(!it)return;await admin.from("transaction_items").update({...v,payload:{...safe(it.payload),...safe(v.payload)},updated_at:checkedAt}).eq("id",it.id).eq("user_id",user.id)};
 const total=num(a.TotalDue),principal=num(a.Principal),interest=num(a.Interest),delinq=Boolean(a.DelinquentStatus),pending=Boolean(a.PendingTaxsale),townLien=Boolean(a.OpenTownLien),liens=Array.isArray(a.AccountLiens)?a.AccountLiens:[];
 await patch("property_tax_status",{evidence_state:(total>0||delinq)?"verify":"clear_observed",severity:(total>0||delinq)?"review":"info",source_type:"live_municipal_account",source_label:label,source_url:source,source_checked_at:checkedAt,description:`Live HLS municipal tax account matched this parcel. Total due ${money(total)}; principal ${money(principal)}; interest ${money(interest)}; delinquent flag ${delinq?"YES":"not observed"}. This is account evidence, not a municipal lien certificate.`,payload:{provider_family:"hls",account_number:a.AccountNumber,principal,interest,total_due:total,delinquent_status:delinq,yearly_summaries:a.YearlySummaries||[],quarterly_summaries:a.QuarterlySummaries||[]}});
 if(clean(a.OwnerName,240))await patch("ownership_vesting",{evidence_state:"verify",severity:"review",source_type:"live_municipal_account",source_label:label,source_url:source,source_checked_at:checkedAt,description:`Live municipal account name: “${clean(a.OwnerName,240)}”. Compare against contract and title; this is not a legal vesting determination.`,payload:{owner_name:clean(a.OwnerName,240),owner_source:"hls_live_account",provider_family:"hls"}});
 if(clean(a.DeedBook,60)||clean(a.DeedPage,60))await patch("deed_recording_reference",{source_type:"live_municipal_account",source_label:label,source_url:source,source_checked_at:checkedAt,payload:{hls_deed_book:clean(a.DeedBook,60),hls_deed_page:clean(a.DeedPage,60),hls_deed_date:a.DeedDate||null,provider_family:"hls"}});
 const taxIssue=pending||liens.length>0;await patch("tax_sale_delinquency",{evidence_state:taxIssue?"issue_observed":"clear_observed",severity:taxIssue?"blocker":"info",source_type:"live_municipal_account",source_label:label,source_url:source,source_checked_at:checkedAt,description:taxIssue?`HLS reports ${pending?"a pending tax-sale flag":"tax-lien records"} for this municipal account. Review the attached municipal evidence immediately.`:`No pending tax-sale flag or tax-lien record was observed in the checked HLS municipal account. This does not replace a municipal lien certificate.`,payload:{provider_family:"hls",pending_taxsale:pending,open_town_lien:townLien,lien_count:num(a.LienCount),records:liens}});
 await patch("municipal_lien_clearance",{evidence_state:townLien?"issue_observed":"verify",severity:townLien?"blocker":"review",source_type:"live_municipal_account",source_label:label,source_url:source,source_checked_at:checkedAt,description:townLien?"HLS reports an open town-lien flag on this municipal account. Obtain municipal/title clearance before closing.":"No open town-lien flag was observed in HLS. Watchdog still requires the formal municipal/title clearance where applicable.",payload:{provider_family:"hls",open_town_lien:townLien,municipal_lien_certificate:false}});
 const evidence={account_number:a.AccountNumber,property_location:a.PropertyLocation,owner_name:clean(a.OwnerName,240),principal,interest,total_due:total,delinquent_status:delinq,pending_taxsale:pending,open_town_lien:townLien,lien_count:num(a.LienCount),liens};await admin.from("transaction_evidence_observations").upsert({transaction_id:tx.id,user_id:user.id,pams_pin:tx.pams_pin,evidence_key:"municipal_tax_hls",provider_key:`hls-${district(tx)}`,evidence_status:(total>0||delinq||pending||townLien||liens.length)?"observed":"no_issue_observed",value:evidence,source_label:label,source_url:source,source_checked_at:checkedAt,facts_hash:await digest(evidence),metadata:{live_account:true,municipal_lien_certificate:false}},{onConflict:"transaction_id,evidence_key,provider_key,facts_hash",ignoreDuplicates:true});results.push({transaction_id:tx.id,provider:"hls",status:"matched",total_due:total,pending_taxsale:pending,lien_count:liens.length})}
 return json(req,200,{ok:true,checked_at:checkedAt,provider_family:"hls",results});
});
