// Phase 5 governed derived-marker engine.
// Formula definitions are explicit, versioned, dependency-aware, and never invent values.
export const DERIVED_ENGINE_VERSION='watchdog-derived-v1';
type Result={v:any;formula:string;dependencies:string[];confidence:'high'|'medium';explanation:string}|null;
function n(v:any){const x=Number(v);return Number.isFinite(x)?x:null}
function truth(v:any){return v===true||v===1||v==='1'||String(v).toLowerCase()==='true'||String(v).toLowerCase()==='yes'}
function countPositive(vals:any[]){return vals.reduce((s,v)=>s+((n(v)!=null&&Number(v)>0)||truth(v)?1:0),0)}
function floodRisk(v:any){const z=String(v||'').toUpperCase();if(!z)return 0;if(/^(A|AE|AH|AO|AR|A99|V|VE)/.test(z))return 3;if(/^(X.*0\.2|B)/.test(z))return 2;if(/^(X|C)/.test(z))return 0;return 1}
export function isGovernedDerived(id:string){return id.startsWith('watchdog.')}
export function derive(id:string,get:(id:string)=>any,row:any):Result{
 const ass=n(row?.assessed_value),tax=n(row?.last_year_tax),land=n(row?.land_value),imp=n(row?.improvement_value),acres=n(row?.acres),sale=n(row?.last_sale_price); const year=new Date().getUTCFullYear(),built=n(row?.year_built),sold=n(row?.last_sale_year);
 if(id==='watchdog.building_age_years'&&built&&built>1600)return{v:year-built,formula:'current_year - YR_CONSTR',dependencies:['property.year_built'],confidence:'high',explanation:'Elapsed years since recorded construction year.'};
 if(id==='watchdog.years_since_last_sale'&&sold&&sold>1800)return{v:year-sold,formula:'current_year - DEED_DATE.year',dependencies:['property.deed_date'],confidence:'high',explanation:'Elapsed years since the recorded deed/sale year.'};
 if((id==='watchdog.tax_to_assessment_rate'||id==='watchdog.effective_tax_rate')&&ass&&tax!=null)return{v:Number((tax/ass*100).toFixed(3)),formula:'LAST_YR_TX / NET_VALUE * 100',dependencies:['property.annual_tax','property.assessed_value'],confidence:'high',explanation:'Annual property tax as a percent of recorded total assessment.'};
 if(id==='watchdog.land_share_pct'&&ass&&land!=null)return{v:Number((land/ass*100).toFixed(1)),formula:'LAND_VAL / NET_VALUE * 100',dependencies:['property.land_assessment','property.assessed_value'],confidence:'high',explanation:'Land share of the total assessment.'};
 if(id==='watchdog.improvement_share_pct'&&ass&&imp!=null)return{v:Number((imp/ass*100).toFixed(1)),formula:'IMPRVT_VAL / NET_VALUE * 100',dependencies:['property.improvement_assessment','property.assessed_value'],confidence:'high',explanation:'Improvement share of the total assessment.'};
 if(id==='watchdog.assessment_per_acre'&&ass!=null&&acres&&acres>0)return{v:Math.round(ass/acres),formula:'NET_VALUE / CALC_ACRE',dependencies:['property.assessed_value','property.lot_area'],confidence:'high',explanation:'Assessed value normalized by parcel acreage.'};
 if(id==='watchdog.sale_to_assessment_ratio'&&sale&&ass)return{v:Number((sale/ass).toFixed(3)),formula:'SALE_PRICE / NET_VALUE',dependencies:['property.sale_price','property.assessed_value'],confidence:'high',explanation:'Recorded sale price divided by total assessment.'};
 if(id==='watchdog.assessment_to_sale_ratio'&&sale&&ass)return{v:Number((ass/sale).toFixed(3)),formula:'NET_VALUE / SALE_PRICE',dependencies:['property.assessed_value','property.sale_price'],confidence:'high',explanation:'Total assessment divided by recorded sale price.'};
 if(id==='watchdog.land_to_improvement_ratio'&&land!=null&&imp&&imp>0)return{v:Number((land/imp).toFixed(3)),formula:'LAND_VAL / IMPRVT_VAL',dependencies:['property.land_assessment','property.improvement_assessment'],confidence:'high',explanation:'Land assessment divided by improvement assessment.'};
 if(id==='watchdog.permit_activity_score'){const pc=n(get('preflight.permit_count')),oc=n(get('preflight.open_permit_count'));if(pc==null&&oc==null)return null;return{v:Math.min(100,Math.round(Math.min(pc||0,20)*3+Math.min(oc||0,10)*8)),formula:'min(100, min(permit_count,20)*3 + min(open_permit_count,10)*8)',dependencies:['preflight.permit_count','preflight.open_permit_count'],confidence:'medium',explanation:'Permit activity screening score; not a compliance finding.'}}
 if(id==='watchdog.environmental_encumbrance_severity'){const deps=['preflight.deed_notice_hit','preflight.cea_hit','preflight.contaminated_site_500m','preflight.ust_250m'],v=deps.map(get);if(v.every(x=>x==null))return null;return{v:Math.min(100,(truth(v[0])?35:0)+(truth(v[1])?30:0)+Math.min(n(v[2])||0,3)*12+Math.min(n(v[3])||0,3)*8),formula:'deed_notice*35 + CEA*30 + min(contaminated_sites,3)*12 + min(UST,3)*8',dependencies:deps,confidence:'medium',explanation:'Environmental due-diligence screening severity; not a contamination determination.'}}
 if(id==='watchdog.title_constraint_stack'){const deps=['preflight.tidelands_reference_hit','preflight.deed_notice_hit','preflight.wetlands_2012_hit','preflight.epa_priority_wetland_hit','preflight.highlands_hit','preflight.pinelands_hit'],v=deps.map(get);if(v.every(x=>x==null))return null;return{v:countPositive(v),formula:'count(tidelands, deed_notice, wetlands, priority_wetlands, highlands, pinelands)',dependencies:deps,confidence:'medium',explanation:'Mapped constraint signal count; not a title opinion.'}}
 if(id==='watchdog.flood_environment_risk_score'){const deps=['preflight.fema_flood_zone','preflight.tidal_cafe_hit','preflight.wetlands_2012_hit','preflight.epa_priority_wetland_hit'],v=deps.map(get);if(v.every(x=>x==null))return null;return{v:Math.min(100,floodRisk(v[0])*22+(truth(v[1])?18:0)+(truth(v[2])?10:0)+(truth(v[3])?6:0)),formula:'FEMA_zone_weight + tidal_CAFE*18 + wetlands*10 + priority_wetlands*6',dependencies:deps,confidence:'medium',explanation:'Combined flood/environment screening score.'}}
 if(id==='watchdog.due_diligence_signal_count'){const deps=['preflight.fema_flood_zone','preflight.tidal_cafe_hit','preflight.wetlands_2012_hit','preflight.epa_priority_wetland_hit','preflight.tidelands_reference_hit','preflight.deed_notice_hit','preflight.cea_hit','preflight.highlands_hit','preflight.pinelands_hit'],v=deps.map(get);if(v.every(x=>x==null))return null;return{v:countPositive(v.map((x,i)=>i===0?floodRisk(x)>0:x)),formula:'count(active governed preflight signals)',dependencies:deps,confidence:'medium',explanation:'Count of active mapped due-diligence signals.'}}
 return null;
}