// Phase 5 governed derived-marker engine.
// Formula definitions are explicit, versioned, dependency-aware, and never invent values.
export const DERIVED_ENGINE_VERSION='watchdog-derived-v2';
type Result={v:any;formula:string;dependencies:string[];confidence:'high'|'medium';explanation:string}|null;
function n(v:any){const x=Number(v);return Number.isFinite(x)?x:null}
function truth(v:any){return v===true||v===1||v==='1'||String(v).toLowerCase()==='true'||String(v).toLowerCase()==='yes'}
function present(v:any){return v!==null&&v!==undefined&&v!==''}
function pct(vals:any[]){return Math.round(vals.filter(present).length/vals.length*100)}
function countPositive(vals:any[]){return vals.reduce((s,v)=>s+((n(v)!=null&&Number(v)>0)||truth(v)?1:0),0)}
function floodRisk(v:any){const z=String(v||'').toUpperCase();if(!z)return 0;if(/^(A|AE|AH|AO|AR|A99|V|VE)/.test(z))return 3;if(/^(X.*0\.2|B)/.test(z))return 2;if(/^(X|C)/.test(z))return 0;return 1}
function appraisalCompleteness(r:any){return pct([r?.land_value,r?.improvement_value,r?.assessed_value,r?.last_sale_price,r?.deed_date||r?.last_sale_year,r?.year_built,r?.acres,r?.prop_class])}
export function isGovernedDerived(id:string){return id.startsWith('watchdog.')}
export function derive(id:string,get:(id:string)=>any,row:any):Result{
 const ass=n(row?.assessed_value),tax=n(row?.last_year_tax),land=n(row?.land_value),imp=n(row?.improvement_value),acres=n(row?.acres),sale=n(row?.last_sale_price); const year=new Date().getUTCFullYear(),built=n(row?.year_built),sold=n(row?.last_sale_year);
 if(id==='watchdog.building_age_years'&&built&&built>1600)return{v:year-built,formula:'current_year - YR_CONSTR',dependencies:['property.year_built'],confidence:'high',explanation:'Elapsed years since recorded construction year.'};
 if(id==='watchdog.years_since_last_sale'&&sold&&sold>1800)return{v:year-sold,formula:'current_year - DEED_DATE.year',dependencies:['property.deed_date'],confidence:'high',explanation:'Elapsed years since the recorded deed/sale year.'};
 if((id==='watchdog.tax_to_assessment_rate'||id==='watchdog.effective_tax_rate')&&ass&&tax!=null)return{v:Number((tax/ass*100).toFixed(3)),formula:'LAST_YR_TX / NET_VALUE * 100',dependencies:['property.annual_tax','property.assessed_value'],confidence:'high',explanation:'Annual property tax as a percent of recorded total assessment.'};
 if(id==='watchdog.land_share_pct'&&ass&&land!=null)return{v:Number((land/ass*100).toFixed(1)),formula:'LAND_VAL / NET_VALUE * 100',dependencies:['property.land_assessment','property.assessed_value'],confidence:'high',explanation:'Land share of the total assessment.'};
 if(id==='watchdog.improvement_share_pct'&&ass&&imp!=null)return{v:Number((imp/ass*100).toFixed(1)),formula:'IMPRVT_VAL / NET_VALUE * 100',dependencies:['property.improvement_assessment','property.assessed_value'],confidence:'high',explanation:'Improvement share of the total assessment.'};
 if(id==='watchdog.assessment_per_acre'&&ass!=null&&acres&&acres>0)return{v:Math.round(ass/acres),formula:'NET_VALUE / CALC_ACRE',dependencies:['property.assessed_value','property.lot_area'],confidence:'high',explanation:'Assessed value normalized by parcel acreage.'};
 if(id==='watchdog.sale_to_assessment_ratio'&&sale&&ass)return{v:Number((sale/ass).toFixed(3)),formula:'SALE_PRICE / NET_VALUE',dependencies:['property.sale_price','property.assessed_value'],confidence:'high',explanation:'Recorded sale price divided by total assessment.'};
 if(id==='watchdog.assessment_to_sale_ratio'&&sale&&ass)return{v:Number((ass/sale).toFixed(3)),formula:'NET_VALUE / SALE_PRICE',dependencies:['property.assessed_value','property.sale_price'],confidence:'high',explanation:'Total assessment divided by recorded sale price.'};
 if(id==='watchdog.land_to_improvement_ratio'&&land!=null&&imp&&imp>0)return{v:Number((land/imp).toFixed(3)),formula:'LAND_VAL / IMPRVT_VAL',dependencies:['property.land_assessment','property.improvement_assessment'],confidence:'high',explanation:'Land assessment divided by improvement assessment.'};
 if(id==='watchdog.consumer.home_cost_clarity'){const saleContext=present(row?.last_sale_price)&&present(row?.deed_date||row?.last_sale_year)?1:null,rate=ass&&tax!=null?tax/ass:null;return{v:pct([row?.last_year_tax,rate,row?.assessed_value,saleContext]),formula:'present(annual_tax, tax_rate, assessment, sale_context) / 4 * 100',dependencies:['property.annual_tax','property.assessed_value','property.sale_price','property.sale_date'],confidence:'high',explanation:'Completeness of core public cost facts used for homeowner planning; it is not a cost or value opinion.'}}
 if(id==='watchdog.consumer.public_record_completeness')return{v:pct([row?.address,row?.town,row?.block,row?.lot,row?.prop_class,row?.assessed_value,row?.last_year_tax,row?.year_built,row?.acres,row?.deed_date||row?.last_sale_year]),formula:'present(address, municipality, block, lot, property_class, assessment, annual_tax, year_built, lot_area, sale_date) / 10 * 100',dependencies:['property.address','property.municipality','property.block','property.lot','property.property_class','property.assessed_value','property.annual_tax','property.year_built','property.lot_area','property.sale_date'],confidence:'high',explanation:'Completeness of a defined homeowner-facing public parcel record set; missing facts remain missing.'};
 if(id==='watchdog.title.recording_reference_completeness')return{v:pct([row?.deed_book,row?.deed_page,row?.deed_date||row?.last_sale_year,row?.pams_pin]),formula:'present(deed_book, deed_page, sale_date, parcel_id) / 4 * 100',dependencies:['property.deed_book','property.deed_page','property.sale_date','property.pams_pin'],confidence:'high',explanation:'Completeness of key public recording references; not a title opinion.'};
 if(id==='watchdog.agent.client_brief_completeness')return{v:pct([row?.address,row?.town,row?.prop_class,row?.assessed_value,row?.last_year_tax,row?.last_sale_price,row?.deed_date||row?.last_sale_year,row?.year_built,row?.acres]),formula:'present(address, municipality, property_class, assessment, annual_tax, sale_price, sale_date, year_built, lot_area) / 9 * 100',dependencies:['property.address','property.municipality','property.property_class','property.assessed_value','property.annual_tax','property.sale_price','property.sale_date','property.year_built','property.lot_area'],confidence:'high',explanation:'Completeness of the defined public-record essentials used in a client brief; not a CMA or valuation.'};
 if(id==='watchdog.lender.lending_diligence_coverage')return{v:pct([row?.pams_pin,row?.prop_class,row?.assessed_value,row?.last_year_tax,row?.last_sale_price,row?.deed_date||row?.last_sale_year,row?.year_built,row?.acres]),formula:'present(parcel_id, property_class, assessment, annual_tax, sale_price, sale_date, year_built, lot_area) / 8 * 100',dependencies:['property.pams_pin','property.property_class','property.assessed_value','property.annual_tax','property.sale_price','property.sale_date','property.year_built','property.lot_area'],confidence:'high',explanation:'Coverage of defined public collateral facts for diligence discussion; not an underwriting conclusion.'};
 if(id==='watchdog.appraisal_record_completeness')return{v:appraisalCompleteness(row),formula:'present(land_assessment, improvement_assessment, assessment, sale_price, sale_date, year_built, lot_area, property_class) / 8 * 100',dependencies:['property.land_assessment','property.improvement_assessment','property.assessed_value','property.sale_price','property.sale_date','property.year_built','property.lot_area','property.property_class'],confidence:'high',explanation:'Completeness of defined public appraisal inputs; not an appraisal or value conclusion.'};
 if(id==='watchdog.appraiser.public_input_gap')return{v:100-appraisalCompleteness(row),formula:'100 - watchdog.appraisal_record_completeness',dependencies:['watchdog.appraisal_record_completeness'],confidence:'high',explanation:'Share of the defined public appraisal-input set that is missing.'};
 if(id==='watchdog.lender.collateral_record_gap')return{v:100-appraisalCompleteness(row),formula:'100 - watchdog.appraisal_record_completeness',dependencies:['watchdog.appraisal_record_completeness'],confidence:'high',explanation:'Share of the defined public appraisal-input set missing before collateral workflow handoff.'};
 if(id==='watchdog.permit_activity_score'){const pc=n(get('preflight.permit_count')),oc=n(get('preflight.open_permit_count'));if(pc==null&&oc==null)return null;return{v:Math.min(100,Math.round(Math.min(pc||0,20)*3+Math.min(oc||0,10)*8)),formula:'min(100, min(permit_count,20)*3 + min(open_permit_count,10)*8)',dependencies:['preflight.permit_count','preflight.open_permit_count'],confidence:'medium',explanation:'Permit activity screening score; not a compliance finding.'}}
 if(id==='watchdog.environmental_encumbrance_severity'){const deps=['preflight.deed_notice_hit','preflight.cea_hit','preflight.contaminated_site_500m','preflight.ust_250m'],v=deps.map(get);if(v.every(x=>x==null))return null;return{v:Math.min(100,(truth(v[0])?35:0)+(truth(v[1])?30:0)+Math.min(n(v[2])||0,3)*12+Math.min(n(v[3])||0,3)*8),formula:'deed_notice*35 + CEA*30 + min(contaminated_sites,3)*12 + min(UST,3)*8',dependencies:deps,confidence:'medium',explanation:'Environmental due-diligence screening severity; not a contamination determination.'}}
 if(id==='watchdog.title_constraint_stack'){const deps=['preflight.tidelands_reference_hit','preflight.deed_notice_hit','preflight.wetlands_2012_hit','preflight.epa_priority_wetland_hit','preflight.highlands_hit','preflight.pinelands_hit'],v=deps.map(get);if(v.every(x=>x==null))return null;return{v:countPositive(v),formula:'count(tidelands, deed_notice, wetlands, priority_wetlands, highlands, pinelands)',dependencies:deps,confidence:'medium',explanation:'Mapped constraint signal count; not a title opinion.'}}
 if(id==='watchdog.flood_environment_risk_score'){const deps=['preflight.fema_flood_zone','preflight.tidal_cafe_hit','preflight.wetlands_2012_hit','preflight.epa_priority_wetland_hit'],v=deps.map(get);if(v.every(x=>x==null))return null;return{v:Math.min(100,floodRisk(v[0])*22+(truth(v[1])?18:0)+(truth(v[2])?10:0)+(truth(v[3])?6:0)),formula:'FEMA_zone_weight + tidal_CAFE*18 + wetlands*10 + priority_wetlands*6',dependencies:deps,confidence:'medium',explanation:'Combined flood/environment screening score.'}}
 if(id==='watchdog.due_diligence_signal_count'){const deps=['preflight.fema_flood_zone','preflight.tidal_cafe_hit','preflight.wetlands_2012_hit','preflight.epa_priority_wetland_hit','preflight.tidelands_reference_hit','preflight.deed_notice_hit','preflight.cea_hit','preflight.highlands_hit','preflight.pinelands_hit'],v=deps.map(get);if(v.every(x=>x==null))return null;return{v:countPositive(v.map((x,i)=>i===0?floodRisk(x)>0:x)),formula:'count(active governed preflight signals)',dependencies:deps,confidence:'medium',explanation:'Count of active mapped due-diligence signals.'}}
 return null;
}