// Phase 4 governed spatial preflight resolver.
// NJDEP layers use explicit service/layer mappings; FEMA NFHL is kept as a separate authoritative service.
// CSRR parcel facts use the official SRP Preferred ID COMU_CODE + PARCELS fields, never point proximity.
type Spec={base:string,layer:string,distance?:number,mode?:'hit'|'count'|'value'|'fema'};
type QueryResult={ok:boolean,features:any[],error?:string};
export type SpatialObservation={status:'available'|'source_checked_no_value'|'dependency_missing'|'provider_error'|'provider_missing',value:any,reason?:string};
const SERVICES:Record<string,string>={
 'njdep-geology-live':'https://mapsdep.nj.gov/arcgis/rest/services/Features/Geology/MapServer',
 'njdep-hydro-live':'https://mapsdep.nj.gov/arcgis/rest/services/Features/Hydrography/MapServer',
 'njdep-land-live':'https://mapsdep.nj.gov/arcgis/rest/services/Features/Land/MapServer',
 'njdep-csrr-gis':'https://mapsdep.nj.gov/arcgis/rest/services/Features/Environmental_NJEMS/MapServer'
};
const FEMA_NFHL='https://hazards.fema.gov/arcgis/rest/services/public/NFHL/MapServer';
const GOVERNMENT='https://mapsdep.nj.gov/arcgis/rest/services/Features/Government/MapServer';
const HUD_OPPORTUNITY_ZONES='https://services.arcgis.com/VTyQ9soqVukalItT/arcgis/rest/services/Opportunity_Zones/FeatureServer';
const NJDOT_TRANSIT_VILLAGES='https://services.arcgis.com/HggmsDF7UJsNN1FK/ArcGIS/rest/services/TransitVillageBuffersV6/FeatureServer';
const CSRR_SRP='https://mapsdep.nj.gov/arcgis/rest/services/Features/Environmental_NJEMS/MapServer/24';
const CSRR_FIELDS=new Set(['kcsl_case_status','kcsl_program_interest','kcsl_site_id','deed_notice_reference','cea_reference','ust_facility_reference','brownfield_inventory_status','environmental_layer_vintage']);
const PRE:Record<string,Spec>={
 'preflight.contaminated_site_500m':{base:'https://mapsdep.nj.gov/arcgis/rest/services/Features/Environmental_NJEMS/MapServer',layer:'0',distance:500,mode:'count'},
 'preflight.deed_notice_hit':{base:'https://mapsdep.nj.gov/arcgis/rest/services/Features/Environmental/MapServer',layer:'40',mode:'hit'},
 'preflight.cea_hit':{base:'https://mapsdep.nj.gov/arcgis/rest/services/Applications/RSP_Query_Layers/MapServer',layer:'5',mode:'hit'},
 'preflight.ust_250m':{base:'https://mapsdep.nj.gov/arcgis/rest/services/Features/Environmental_NJEMS/MapServer',layer:'9',distance:250,mode:'count'},
 'preflight.tidelands_reference_hit':{base:'https://mapsdep.nj.gov/arcgis/rest/services/Features/Hydrography/MapServer',layer:'30',mode:'hit'},
 'preflight.highlands_hit':{base:'https://mapsdep.nj.gov/arcgis/rest/services/Applications/RSP_Query_Layers/MapServer',layer:'6',mode:'hit'},
 'preflight.pinelands_hit':{base:'https://mapsdep.nj.gov/arcgis/rest/services/Applications/RSP_Query_Layers/MapServer',layer:'7',mode:'hit'},
 'preflight.fema_flood_zone':{base:FEMA_NFHL,layer:'28',mode:'fema'},
 'preflight.tidal_cafe_hit':{base:'https://mapsdep.nj.gov/arcgis/rest/services/Features/Hydrography/MapServer',layer:'48',mode:'hit'},
 'preflight.wetlands_2012_hit':{base:'https://mapsdep.nj.gov/arcgis/rest/services/Features/Land_lu/MapServer',layer:'2',mode:'hit'},
 'preflight.epa_priority_wetland_hit':{base:'https://mapsdep.nj.gov/arcgis/rest/services/Features/Land/MapServer',layer:'79',mode:'hit'},
 'njplus.nj-dca-community-assets.urban_enterprise_zone_status':{base:GOVERNMENT,layer:'24',mode:'hit'},
 'njplus.nj-dca-community-assets.redevelopment_area_status':{base:GOVERNMENT,layer:'31',mode:'hit'},
 'njplus.nj-dca-community-assets.opportunity_zone_status':{base:HUD_OPPORTUNITY_ZONES,layer:'13',mode:'hit'},
 'njplus.nj-dca-community-assets.transit_village_status':{base:NJDOT_TRANSIT_VILLAGES,layer:'0',mode:'hit'}
};
const cache=new Map<string,{at:number,v:any[]}>(),TTL=6*60*60*1000;
const csrrCache=new Map<string,{at:number,v:any[]}>(),CSRR_TTL=30*60*1000;
let csrrVintage:{at:number,v:string|null}|null=null;
function norm(s:string){return String(s||'').toLowerCase().replace(/[^a-z0-9]/g,'')}
function distanceFor(field:string){const m=String(field).match(/within_(\d+)(m|km)|_(\d+)m$/);if(!m)return 0;return m[3]?Number(m[3]):Number(m[1])*(m[2]==='km'?1000:1)}
function pick(attrs:any,field:string){if(!attrs)return null;const want=norm(field);for(const k of Object.keys(attrs))if(norm(k)===want)return attrs[k];for(const k of Object.keys(attrs)){const nk=norm(k);if(want&&nk.includes(want.replace(/hit$|reference$|status$|tier$|traveltime$/g,'')))return attrs[k]}return null}
function parcelPart(v:any){return String(v??'').trim().toUpperCase().replace(/\s+/g,'')}
function district(row:any){const pin=String(row?.pams_pin||'').replace(/\D/g,'');return pin.length>=4?pin.slice(0,4):String(row?.cd_code||'').replace(/\D/g,'').slice(0,4)}
function parcelToken(row:any){const block=parcelPart(row?.block),lot=parcelPart(row?.lot);return block&&lot?block+'-'+lot:''}
function parcelTokens(v:any){return String(v??'').split(';').map(parcelPart).filter(Boolean)}
function sql(v:string){return v.replace(/'/g,"''")}
function distinct(values:any[]){const seen=new Set<string>(),out:any[]=[];for(const value of values){if(value===null||value===undefined||value==='')continue;const key=String(value).trim();if(!key||seen.has(key))continue;seen.add(key);out.push(typeof value==='string'?key:value)}return out}
function scalarOrList(values:any[]){const v=distinct(values);return !v.length?null:v.length===1?v[0]:v}
async function query(spec:Spec,lat:number,lon:number):Promise<QueryResult>{const ck=[spec.base,spec.layer,lat.toFixed(5),lon.toFixed(5),spec.distance||0].join('|'),old=cache.get(ck);if(old&&Date.now()-old.at<TTL)return{ok:true,features:old.v};const q=new URLSearchParams({f:'json',where:'1=1',geometry:lon+','+lat,geometryType:'esriGeometryPoint',inSR:'4326',spatialRel:'esriSpatialRelIntersects',outFields:'*',returnGeometry:'false',resultRecordCount:'10'});if(spec.distance){q.set('distance',String(spec.distance));q.set('units','esriSRUnit_Meter')}const c=new AbortController(),t=setTimeout(()=>c.abort(),4500);try{const r=await fetch(spec.base+'/'+spec.layer+'/query?'+q.toString(),{signal:c.signal,headers:{accept:'application/json'}});if(!r.ok)return{ok:false,features:[],error:'provider_http_'+r.status};const j=await r.json();if(j?.error)return{ok:false,features:[],error:'provider_arcgis_error'};const v=Array.isArray(j.features)?j.features:[];cache.set(ck,{at:Date.now(),v});return{ok:true,features:v}}catch(e){return{ok:false,features:[],error:e instanceof DOMException&&e.name==='AbortError'?'provider_timeout':'provider_unavailable'}}finally{clearTimeout(t)}}
async function queryCsrrParcel(row:any):Promise<QueryResult>{const d=district(row),token=parcelToken(row);if(!/^\d{4}$/.test(d)||!token)return{ok:false,features:[],error:'parcel_key_unavailable'};const ck=d+'|'+token,old=csrrCache.get(ck);if(old&&Date.now()-old.at<CSRR_TTL)return{ok:true,features:old.v};const q=new URLSearchParams({f:'json',where:`COMU_CODE='${sql(d)}' AND PARCELS LIKE '%${sql(token)}%'`,outFields:'PREFERRED_ID,SITE_ID,CASE_STATUS,KCSL,COMU_CODE,PARCELS,DATALOAD_DATE,DEED_NOTICE,DN_DATE,CEA,CEA_DATE,REGULATED_UST,BROWNFIELDS_DEVELOPMENT_AREA',returnGeometry:'false',resultRecordCount:'2000'});const c=new AbortController(),t=setTimeout(()=>c.abort(),5000);try{const r=await fetch(CSRR_SRP+'/query?'+q.toString(),{signal:c.signal,headers:{accept:'application/json'}});if(!r.ok)return{ok:false,features:[],error:'provider_http_'+r.status};const j=await r.json();if(j?.error)return{ok:false,features:[],error:'provider_arcgis_error'};const v=(Array.isArray(j.features)?j.features:[]).filter((f:any)=>parcelTokens(f?.attributes?.PARCELS).includes(token));csrrCache.set(ck,{at:Date.now(),v});return{ok:true,features:v}}catch(e){return{ok:false,features:[],error:e instanceof DOMException&&e.name==='AbortError'?'provider_timeout':'provider_unavailable'}}finally{clearTimeout(t)}}
async function csrrLayerVintage():Promise<{ok:boolean,v:string|null,error?:string}>{if(csrrVintage&&Date.now()-csrrVintage.at<TTL)return{ok:true,v:csrrVintage.v};const stats=JSON.stringify([{statisticType:'max',onStatisticField:'DATALOAD_DATE',outStatisticFieldName:'max_dataload'}]),q=new URLSearchParams({f:'json',where:'1=1',outStatistics:stats,returnGeometry:'false'});const c=new AbortController(),t=setTimeout(()=>c.abort(),5000);try{const r=await fetch(CSRR_SRP+'/query?'+q.toString(),{signal:c.signal,headers:{accept:'application/json'}});if(!r.ok)return{ok:false,v:null,error:'provider_http_'+r.status};const j=await r.json();if(j?.error)return{ok:false,v:null,error:'provider_arcgis_error'};const raw=Number(j?.features?.[0]?.attributes?.max_dataload),v=Number.isFinite(raw)&&raw>0?new Date(raw).toISOString():null;csrrVintage={at:Date.now(),v};return{ok:true,v}}catch(e){return{ok:false,v:null,error:e instanceof DOMException&&e.name==='AbortError'?'provider_timeout':'provider_unavailable'}}finally{clearTimeout(t)}}
async function csrrObservation(marker:any,row:any):Promise<SpatialObservation>{const field=String(marker?.field||'');if(field==='environmental_layer_vintage'){const vintage=await csrrLayerVintage();if(!vintage.ok)return{status:'provider_error',value:null,reason:vintage.error||'provider_error'};return vintage.v?{status:'available',value:vintage.v}:{status:'source_checked_no_value',value:null,reason:'dataload_vintage_unpublished'}}if(parcelPart(row?.qualifier))return{status:'dependency_missing',value:null,reason:'source_parcel_field_not_unit_qualified'};const d=district(row),token=parcelToken(row);if(!/^\d{4}$/.test(d)||!token)return{status:'dependency_missing',value:null,reason:'parcel_key_unavailable'};const result=await queryCsrrParcel(row);if(!result.ok)return{status:result.error==='parcel_key_unavailable'?'dependency_missing':'provider_error',value:null,reason:result.error||'provider_error'};if(!result.features.length)return{status:'source_checked_no_value',value:null,reason:'no_exact_srp_parcel_record'};const kcsl=result.features.filter((f:any)=>String(f?.attributes?.KCSL??'').trim()!=='');let v:any=null,reason='exact_srp_field_unpublished';if(field==='kcsl_case_status'||field==='kcsl_program_interest'||field==='kcsl_site_id'){if(!kcsl.length)return{status:'source_checked_no_value',value:null,reason:'no_exact_kcsl_parcel_record'};reason='exact_kcsl_field_unpublished';if(field==='kcsl_case_status')v=scalarOrList(kcsl.map((f:any)=>f?.attributes?.CASE_STATUS));else if(field==='kcsl_program_interest')v=scalarOrList(kcsl.map((f:any)=>f?.attributes?.PREFERRED_ID));else v=scalarOrList(kcsl.map((f:any)=>f?.attributes?.SITE_ID))}else if(field==='deed_notice_reference')v=scalarOrList(result.features.map((f:any)=>f?.attributes?.DEED_NOTICE));else if(field==='cea_reference')v=scalarOrList(result.features.map((f:any)=>f?.attributes?.CEA));else if(field==='ust_facility_reference')v=scalarOrList(result.features.map((f:any)=>f?.attributes?.REGULATED_UST));else if(field==='brownfield_inventory_status')v=scalarOrList(result.features.map((f:any)=>f?.attributes?.BROWNFIELDS_DEVELOPMENT_AREA));return v===null?{status:'source_checked_no_value',value:null,reason}:{status:'available',value:v}}
function femaValue(fs:any[]){if(!fs.length)return null;const a=fs[0]?.attributes||{};const zone=String(a.FLD_ZONE||'').trim(),sub=String(a.ZONE_SUBTY||'').trim();if(zone&&sub&&sub.toLowerCase()!=='null')return zone+' · '+sub;if(zone)return zone;if(sub&&sub.toLowerCase()!=='null')return sub;return 'Mapped NFHL flood hazard'}
export async function njdepObservation(marker:any,row:any):Promise<SpatialObservation>{const field=String(marker?.field||'');if(String(marker?.source_id||'')==='njdep-csrr-gis'&&CSRR_FIELDS.has(field))return csrrObservation(marker,row);const lat=Number(row?.lat),lon=Number(row?.lon);if(!Number.isFinite(lat)||!Number.isFinite(lon))return{status:'dependency_missing',value:null,reason:'parcel_coordinates_unavailable'};const id=String(marker?.id||''),pre=PRE[id];let spec=pre;if(!spec){const base=SERVICES[String(marker?.source_id||'')],layer=String(marker?.source_layer??'');if(!base||!layer)return{status:'provider_missing',value:null,reason:'spatial_provider_mapping_missing'};spec={base,layer,distance:distanceFor(field)}}const result=await query(spec,lat,lon);if(!result.ok)return{status:'provider_error',value:null,reason:result.error||'spatial_provider_error'};const fs=result.features;if(spec.mode==='fema'){const v=femaValue(fs);return v==null?{status:'source_checked_no_value',value:null}:{status:'available',value:v}}if(spec.mode==='count'||field.endsWith('_count')||/_(\d+)m$/.test(field))return{status:'available',value:fs.length};if(spec.mode==='hit'||/_hit$|within_/.test(field))return{status:'available',value:fs.length>0};if(!fs.length)return{status:'source_checked_no_value',value:null};const v=pick(fs[0].attributes||{},field);return v===null||v===undefined||v===''?{status:'source_checked_no_value',value:null}:{status:'available',value:v}}
export async function njdepValue(marker:any,row:any){const result=await njdepObservation(marker,row);return result.status==='available'?result.value:null}
export function isNjdepMarker(marker:any){const src=String(marker?.source_id||''),field=String(marker?.field||'');return !!PRE[String(marker?.id||'')] || (src==='njdep-csrr-gis'&&CSRR_FIELDS.has(field)) || (!!SERVICES[src]&&marker?.source_layer!=null)}
export const NJDEP_PROVIDER_VERSION='spatial-preflight-v10-csrr-exact-controls';
