import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.95.0";

type Row=Record<string,any>;
const WIPP_BASE="https://api.edmundsgovtech.cloud/wipp-core/v1";
const WIPP_PORTAL="https://wipp.edmundsgovtech.cloud";
const ORIGINS=new Set(["https://watchdogindex.com","https://www.watchdogindex.com","https://njpropertytaxrelief.com","https://www.njpropertytaxrelief.com","http://localhost:3000","http://127.0.0.1:3000"]);
const UA="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/154 Safari/537.36 Watchdog-Municipal-Tax/1.0";
const clean=(v:unknown,n=1000)=>String(v??"").replace(/[<>]/g,"").trim().slice(0,n);
const safe=(v:unknown)=>(v&&typeof v==="object"&&!Array.isArray(v)?v as Row:{});
const cors=(r:Request)=>({"Access-Control-Allow-Origin":ORIGINS.has(r.headers.get("origin")||"")?(r.headers.get("origin")||""):"https://www.watchdogindex.com","Access-Control-Allow-Headers":"authorization,apikey,content-type,x-client-info","Access-Control-Allow-Methods":"POST,OPTIONS","Vary":"Origin"});
const respond=(r:Request,s:number,b:unknown)=>new Response(JSON.stringify(b),{status:s,headers:{...cors(r),"Content-Type":"application/json","Cache-Control":"private, no-store"}});
const num=(v:unknown)=>{if(v===null||v===undefined||v==="")return null;const n=Number(String(v).replace(/[$,%\s,]/g,""));return Number.isFinite(n)?n:null};
const SUFFIX:Record<string,string>={STREET:"ST",ST:"ST",ROAD:"RD",RD:"RD",AVENUE:"AVE",AVE:"AVE",COURT:"CT",CT:"CT",DRIVE:"DR",DR:"DR",LANE:"LN",LN:"LN",PLACE:"PL",PL:"PL",BOULEVARD:"BLVD",BLVD:"BLVD",TERRACE:"TER",TER:"TER",CIRCLE:"CIR",CIR:"CIR",PARKWAY:"PKWY",PKWY:"PKWY",HIGHWAY:"HWY",HWY:"HWY",TRAIL:"TRL",TRL:"TRL",WAY:"WAY"};
function streetOnly(v:unknown){return clean(v,240).split(",")[0].trim()}
function normStreet(v:unknown){const raw=streetOnly(v).toUpperCase().replace(/[^A-Z0-9 ]+/g," ").replace(/\s+/g," ").trim();const p=raw.split(" ").filter(Boolean);const dirs:Record<string,string>={NORTH:"N",SOUTH:"S",EAST:"E",WEST:"W",NORTHEAST:"NE",NORTHWEST:"NW",SOUTHEAST:"SE",SOUTHWEST:"SW"};for(let i=0;i<p.length;i++){if(dirs[p[i]])p[i]=dirs[p[i]]}for(let i=0;i<p.length;i++){if(SUFFIX[p[i]])p[i]=SUFFIX[p[i]]}if(p.length>3&&["N","S","E","W","NE","NW","SE","SW"].includes(p[1])){const d=p.splice(1,1)[0];p.push(d)}return p.join(" ")}
function searchTerm(v:unknown){const raw=streetOnly(v).replace(/[^A-Za-z0-9 ]+/g," ").replace(/\s+/g," ").trim();const p=raw.split(" ").filter(Boolean);if(p.length>2&&SUFFIX[String(p.at(-1)).toUpperCase()])p.pop();return p.join(" ").slice(0,100)}
function compact(v:unknown){let s=clean(v,50).toUpperCase().replace(/\s+/g,"").replace(/^0+(?=\d)/,"");if(/^\d+(?:\.\d+)?$/.test(s)&&s.includes("."))s=s.replace(/0+$/,"").replace(/\.$/,"");return s}
function pickMatch(rows:Row[],address:string,block:string,lot:string){const wanted=normStreet(address);if(!wanted)return null;const exact=rows.filter(r=>normStreet(r.propertyLoc)===wanted);if(exact.length===1)return exact[0];if(exact.length>1&&block&&lot){const b=compact(block),l=compact(lot);const byParcel=exact.filter(r=>{const x=clean(r.blqId,140).toUpperCase().replace(/\s+/g,"");return x.includes(b)&&x.includes(l)});if(byParcel.length===1)return byParcel[0]}return null}
function headers(id:string){return {"X-Wipp-Id":id,"User-Agent":UA,"Accept":"application/json"}}
async function get(id:string,path:string,timeoutMs=9000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeoutMs);try{const r=await fetch(`${WIPP_BASE}${path}`,{headers:headers(id),signal:c.signal});const data=await r.json().catch(()=>null);return{ok:r.ok,status:r.status,data}}catch(e){return{ok:false,status:0,data:null,error:e instanceof DOMException&&e.name==="AbortError"?"timeout":"unavailable"}}finally{clearTimeout(t)}}
function normKey(k:string){return k.toLowerCase().replace(/[^a-z0-9]/g,"")}
function findValue(root:any,aliases:string[],maxDepth=7):unknown{const want=new Set(aliases.map(normKey));const seen=new Set<any>();function walk(v:any,d:number):unknown{if(d>maxDepth||v===null||v===undefined||typeof v!=="object"||seen.has(v))return undefined;seen.add(v);if(Array.isArray(v)){for(const x of v){const f=walk(x,d+1);if(f!==undefined&&f!==null&&f!=="")return f}return undefined}for(const [k,val] of Object.entries(v)){if(want.has(normKey(k))&&val!==null&&val!==undefined&&val!=="")return val}for(const val of Object.values(v)){const f=walk(val,d+1);if(f!==undefined&&f!==null&&f!=="")return f}return undefined}return walk(root,0)}
function annualTax(detail:Row){const years=safe(detail.taxYears),out:Row={};for(const [year,groupsRaw] of Object.entries(years)){const groups=safe(groupsRaw),taxRows=Array.isArray(groups.NJTAX)?groups.NJTAX:[],quarters:Row[]=[];for(const raw of taxRows){const row=safe(raw);for(let q=1;q<=4;q++){const original=num(row[`qtr${q}OrigBilled`]),adjusted=num(row[`qtr${q}AdjBilled`]),principal=num(row[`qtr${q}PrnBal`]),interest=num(row[`qtr${q}IntDue`]),due=clean(row[`qtr${q}DueDate`],60)||null;if(original==null&&adjusted==null&&principal==null&&interest==null&&!due)continue;quarters.push({quarter:q,due_date:due,billed:adjusted??original??0,principal_balance:principal??0,interest_due:interest??0})}}const propertyTax=quarters.reduce((s,q)=>s+Number(q.billed||0),0);const yearRoot={year,groups:groupsRaw};const taxRate=num(findValue(yearRoot,["taxRate","tax_rate","rate"]));const assessed=num(findValue(yearRoot,["totalAssessedValue","totalAssessment","assessedValue","assessment","netAssessedValue"]));out[String(year)]={property_tax_billed:Number(propertyTax.toFixed(2)),tax_rate:taxRate,total_assessed_value:assessed,quarters}}return out}
function splitBlq(raw:unknown){const s=clean(raw,100);const parts=s.split(/[.\/-]/).map(x=>x.trim()).filter(Boolean);return{raw:s||null,block:parts[0]||null,lot:parts[1]||null,qualifier:parts[2]||null}}
function portal(id:string,account:string){return `${WIPP_PORTAL}/view/wippTaxes/${encodeURIComponent(account)}?wippId=${encodeURIComponent(id)}`}
function effective_rate_from_same_year(v:number|null){return v}
function currentTaxSummary(annual:Row,assessed:number|null){
  const years=Object.keys(annual).filter(y=>/^\\d{4}$/.test(y)).map(Number).sort((a,b)=>b-a);
  const complete=years.find(y=>{
    const x=safe(annual[String(y)]),qs=Array.isArray(x.quarters)?x.quarters:[];
    return num(x.property_tax_billed)!==null&&Number(x.property_tax_billed)>0&&new Set(qs.map((q:Row)=>Number(q.quarter)).filter(q=>q>=1&&q<=4)).size===4;
  });
  if(!complete)return{tax_year:null,annual_tax:null,assessment_year:null,assessed_value:assessed,effective_rate:null,status:"no_complete_tax_year",revaluation_mismatch:false};
  const x=safe(annual[String(complete)]),tax=num(x.property_tax_billed),yearAssessed=num(x.total_assessed_value),snapshotAssessed=assessed;
  const effective=tax!==null&&yearAssessed!==null&&yearAssessed>0?Number((tax/yearAssessed*100).toFixed(4)):null;
  return{tax_year:complete,annual_tax:tax,assessment_year:yearAssessed!==null?complete:null,assessed_value:yearAssessed,current_assessment_snapshot:snapshotAssessed,effective_rate:effective_rate_from_same_year(effective),tax_rate:num(x.tax_rate),status:"official_municipal_complete_year",revaluation_mismatch:yearAssessed===null};
}

Deno.serve(async(req:Request)=>{
  if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});if(req.method!=="POST")return respond(req,405,{error:"POST required"});
  const auth=req.headers.get("authorization")||"";if(!auth.startsWith("Bearer "))return respond(req,401,{error:"Sign in required"});
  const url=Deno.env.get("SUPABASE_URL")||"",anon=Deno.env.get("SUPABASE_ANON_KEY")||"";if(!url||!anon)return respond(req,503,{error:"Configuration unavailable"});const client=createClient(url,anon,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}});const {data:who}=await client.auth.getUser();if(!who?.user)return respond(req,401,{error:"Session invalid"});
  let body:Row={};try{body=await req.json()}catch{return respond(req,400,{error:"Invalid JSON"})}
  const code=clean(body.municipality_code,4).replace(/\D/g,"");const address=clean(body.address,240),block=clean(body.block,50),lot=clean(body.lot,50);if(!/^\d{4}$/.test(code)||!address)return respond(req,400,{error:"municipality_code and address required"});
  const meta=await get(code,`/metadata/${code}`);if(!meta.ok||!meta.data)return respond(req,200,{ok:true,status:"provider_not_available",municipality_code:code,provider:"edmunds_wipp"});
  const term=searchTerm(address);const sr=await get(code,`/wippPropInfo/search?propertyLoc=${encodeURIComponent(term)}&size=25`);if(!sr.ok||!Array.isArray(sr.data?.content))return respond(req,200,{ok:true,status:"provider_search_unavailable",municipality_code:code,provider:"edmunds_wipp"});
  const match=pickMatch(sr.data.content,address,block,lot);if(!match)return respond(req,200,{ok:true,status:"no_exact_match",municipality_code:code,provider:"edmunds_wipp",candidate_count:sr.data.content.length});
  const account=clean(match.accountId,100);if(!account)return respond(req,200,{ok:true,status:"matched_no_account",municipality_code:code,provider:"edmunds_wipp"});const detail=await get(code,`/wippTaxes/${encodeURIComponent(account)}`);if(!detail.ok||!detail.data)return respond(req,200,{ok:true,status:"detail_unavailable",municipality_code:code,provider:"edmunds_wipp"});
  const d=safe(detail.data),property=safe(d.propertyInfo),annual=annualTax(d),parcel=splitBlq(match.blqId||property.blqId);const checkedAt=new Date().toISOString();const land=num(findValue(property,["landValue","landAssessment"])),improvement=num(findValue(property,["improvementValue","improvementAssessment"])),exempt=num(findValue(property,["exemptValue","exemptionValue"])),assessed=num(findValue(property,["totalAssessedValue","totalAssessment","assessedValue"])),current=currentTaxSummary(annual,assessed);
  return respond(req,200,{ok:true,status:"exact_match",provider:"edmunds_wipp",provider_label:`${clean(meta.data.cityName,160)||"Municipality"} · Edmunds GovTech WIPP`,municipality_code:code,checked_at:checkedAt,match:{property_location:clean(match.propertyLoc,240)||null,account_id:account,owner_name:clean(property.ownerName||match.ownerName,240)||null,parcel},property:{property_class:clean(property.propertyClass||property.propClass,120)||null,land_value:land,improvement_value:improvement,exempt_value:exempt,total_assessed_value:assessed},current,annual,source:{url:portal(code,account),semantics:"Exact official municipal WIPP address match. Values are public tax-account evidence and should be reviewed before filing; Watchdog does not infer missing values or overwrite user-entered application answers."}});
});
