import { createClient } from '@supabase/supabase-js';
const cors={'Access-Control-Allow-Origin':'https://njpropertytaxrelief.com','Access-Control-Allow-Headers':'authorization, apikey, content-type'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json'}});
const paddleBase=()=>Deno.env.get('PADDLE_ENVIRONMENT')==='sandbox'?'https://sandbox-api.paddle.com':'https://api.paddle.com';
const PRICES={agent:{monthly:'pri_01kzp7mcvs46mmcdwyxd0sjvne',yearly:'pri_01kzp7kwcfzs9znjwwj24zgdb6'},pro:{monthly:'pri_01kzp7jhcsk07k47dtvrmaxvjh',yearly:'pri_01kzp7hwtx1qp946ftnmj4xpqc'},pro_plus:{monthly:'pri_01kzp7h2mw9waf3exfsee8jxsb',yearly:'pri_01kzp7fmg7ksff6sjg054mqbe4'},teams:{monthly:'pri_01kzp7e6vsmsbjyw36mxgvww1b'}} as const;
const PLANS={agent:'pro',pro:'pro_plus',pro_plus:'pro_plus',teams:'pro_plus'} as const;
const CAP={agent:25,pro:250,pro_plus:2500,teams:10000} as const;
async function paddle(path:string,init:RequestInit={}){const key=Deno.env.get('PADDLE_API_KEY');if(!key)throw new Error('Paddle is not configured yet');const r=await fetch(paddleBase()+path,{...init,headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json',...(init.headers||{})}});const p=await r.json().catch(()=>({}));if(!r.ok){console.error('PADDLE_API_ERROR',JSON.stringify({path,status:r.status,environment:Deno.env.get('PADDLE_ENVIRONMENT')||'production',payload:p}));const detail=p?.error?.detail||p?.error?.type||'Paddle request failed';const e=new Error(detail);(e as any).paddle_status=r.status;(e as any).paddle_payload=p;throw e}return p?.data;}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'Method not allowed'},405);
 const auth=req.headers.get('Authorization');if(!auth)return json({error:'Sign in required',code:'SIGN_IN_REQUIRED'},401);const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const uc=createClient(url,anon,{global:{headers:{Authorization:auth}}}),admin=createClient(url,service);const {data:{user},error}=await uc.auth.getUser();if(error||!user)return json({error:'Sign in required',code:'SIGN_IN_REQUIRED'},401);const {data:isTest}=await admin.rpc('is_watchdog_test_account',{p_user_id:user.id});if(isTest)return json({error:'Sandbox accounts cannot create or modify real billing.',code:'WATCHDOG_TEST_NO_REAL_SPEND'},403);
 const body=await req.json().catch(()=>({}));const tier=String(body?.tier||body?.plan||'').toLowerCase() as keyof typeof PRICES;const cadence=(String(body?.cadence||'yearly').toLowerCase()==='monthly'?'monthly':'yearly') as 'monthly'|'yearly';if(!PRICES[tier])return json({error:'Choose Agent, Pro, Pro+, or Teams',code:'INVALID_PLAN'},400);if(tier==='teams'&&cadence!=='monthly')return json({error:'Teams is monthly only',code:'INVALID_CADENCE'},400);const price=(PRICES[tier] as Record<string,string>)[cadence];if(!price)return json({error:'Billing price is not configured yet',code:'PRICE_NOT_CONFIGURED'},503);const clientToken=Deno.env.get('PADDLE_CLIENT_TOKEN');if(!clientToken)return json({error:'Paddle Checkout is not configured yet',code:'CLIENT_TOKEN_MISSING'},503);
 const {data:ent}=await admin.from('account_entitlements').select('plan_tier,billing_tier,provider,provider_customer_id,provider_subscription_id,provider_price_id,subscription_status').eq('user_id',user.id).maybeSingle();const customerId=ent?.provider==='paddle'?ent.provider_customer_id:null;
 if(customerId&&ent?.provider_subscription_id&&['active','trialing','past_due','paused'].includes(ent.subscription_status||'')){
   if(ent.provider_price_id===price){try{const portal=await paddle(`/customers/${encodeURIComponent(customerId)}/portal-sessions`,{method:'POST',body:JSON.stringify({subscription_ids:[ent.provider_subscription_id]})});return json({url:portal?.urls?.general?.overview,destination:'portal',provider:'paddle'});}catch(e){console.error('CHECKOUT_PORTAL_ERROR',e);return json({error:e instanceof Error?e.message:'Could not open billing portal',code:'PADDLE_PORTAL_ERROR'},502);}}
   if(['active','trialing'].includes(ent.subscription_status||'')){try{const sub=await paddle(`/subscriptions/${encodeURIComponent(ent.provider_subscription_id)}`,{method:'PATCH',body:JSON.stringify({items:[{price_id:price,quantity:1}],proration_billing_mode:'prorated_immediately'})});await admin.from('access_audit_log').insert({user_id:user.id,event_type:'billing.subscription_plan_change_requested',resource_type:'subscription',resource_id:ent.provider_subscription_id,required_plan:PLANS[tier],allowed:true,metadata:{provider:'paddle',from_tier:ent.billing_tier,to_tier:tier,cadence,price_id:price}});return json({provider:'paddle',destination:'plan_change',plan_change_requested:true,subscription_id:sub?.id||ent.provider_subscription_id,requested_tier:tier,requested_cadence:cadence});}catch(e){console.error('CHECKOUT_PLAN_CHANGE_ERROR',e);return json({error:e instanceof Error?e.message:'Could not change subscription plan',code:'PADDLE_PLAN_CHANGE_ERROR'},502);}}
   try{const portal=await paddle(`/customers/${encodeURIComponent(customerId)}/portal-sessions`,{method:'POST',body:JSON.stringify({subscription_ids:[ent.provider_subscription_id]})});return json({url:portal?.urls?.general?.overview,destination:'portal',provider:'paddle'});}catch(e){console.error('CHECKOUT_FALLBACK_PORTAL_ERROR',e);return json({error:e instanceof Error?e.message:'Could not open billing portal',code:'PADDLE_PORTAL_ERROR'},502);}
 }
 try{const transaction=await paddle('/transactions',{method:'POST',body:JSON.stringify({items:[{price_id:price,quantity:1}],collection_mode:'automatic',...(customerId?{customer_id:customerId}:{}),custom_data:{watchdog_user_id:user.id,billing_tier:tier,plan_tier:PLANS[tier],billing_interval:cadence,property_capacity:CAP[tier],product:'watchdog'},checkout:{url:'https://njpropertytaxrelief.com/property/account?checkout=success'}})});await admin.from('access_audit_log').insert({user_id:user.id,event_type:'billing.checkout_created',resource_type:'transaction',resource_id:transaction?.id,required_plan:PLANS[tier],allowed:true,metadata:{provider:'paddle',billing_tier:tier,cadence,price_id:price}});return json({provider:'paddle',transaction_id:transaction?.id,client_token:clientToken,environment:Deno.env.get('PADDLE_ENVIRONMENT')==='sandbox'?'sandbox':'production',tier,cadence});}catch(e){console.error('CHECKOUT_TRANSACTION_ERROR',e);return json({error:e instanceof Error?e.message:'Could not create checkout',code:'PADDLE_TRANSACTION_ERROR'},502);}
});