import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.95.0";

const ENGINE="watchdog-model-shadow-evaluate-v1";
const ORIGINS=new Set(["https://njpropertytaxrelief.com","https://www.njpropertytaxrelief.com","http://localhost:3000","http://127.0.0.1:3000"]);
const clean=(v:unknown,n=180)=>String(v??"").replace(/[<>]/g,"").trim().slice(0,n);
const numeric=(v:unknown)=>{if(v===null||v===undefined||v==="")return null;const n=Number(v);return Number.isFinite(n)?n:null};
const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
const round=(v:number,d=2)=>Number(v.toFixed(d));
const cors=(r:Request)=>({"Access-Control-Allow-Origin":ORIGINS.has(r.headers.get("origin")||"")?(r.headers.get("origin")||""):"https://njpropertytaxrelief.com","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"});
const out=(r:Request,s:number,p:unknown)=>new Response(JSON.stringify(p),{status:s,headers:{...cors(r),"Content-Type":"application/json","Cache-Control":"private, no-store"}});
const env=(j:string,l:string)=>{const raw=Deno.env.get(j)||"";if(raw){try{const x=JSON.parse(raw);if(x?.default)return String(x.default)}catch{}}return Deno.env.get(l)||""};
function quantile(values:number[],q:number){if(!values.length)return null;const a=values.slice().sort((x,y)=>x-y),p=Math.max(0,Math.min(1,q))*(a.length-1),lo=Math.floor(p),hi=Math.ceil(p);return lo===hi?a[lo]:a[lo]+(a[hi]-a[lo])*(p-lo)}
function transform(def:any,raw:unknown){const cfg=def?.config||{},type=String(def?.transform_type||"");
 if(type==="identity_0_100"){const n=numeric(raw);return n===null?null:clamp(n)}
 if(type==="inverse_0_100"){const n=numeric(raw);return n===null?null:clamp(100-clamp(n))}
 if(type==="count_cap"){const n=numeric(raw),cap=Math.max(Number(cfg.cap||1),1);return n===null?null:clamp(Math.max(0,n)/cap*100)}
 if(type==="categorical_map"){const key=clean(raw,80).toLowerCase(),n=numeric(cfg[key]);return n===null?null:clamp(n)}
 if(type==="recency_decay"){const d=new Date(String(raw||""));if(!Number.isFinite(d.getTime())||d.getTime()>Date.now()+300000)return null;const days=Math.max(0,(Date.now()-d.getTime())/86400000),points=Array.isArray(cfg.breakpoints)?cfg.breakpoints.slice().sort((a:any,b:any)=>Number(a.days)-Number(b.days)):[],hit=points.find((p:any)=>days<=Number(p.days));return clamp(Number(hit?hit.score:(cfg.older_score??0)))}
 if(type==="distance_from_target"){const n=numeric(raw);if(n===null)return null;const target=Number(cfg.target??0),delta=Math.max(Number(cfg.full_attention_delta||1),0.000001);return clamp(Math.abs(n-target)/delta*100)}
 return null;
}
function featureStats(rows:any[],keys:string[]){return keys.map(key=>{const vals=rows.map(r=>r.features[key]).filter((v:any)=>typeof v==="number"&&Number.isFinite(v)),distinct=new Set(vals.map((v:number)=>round(v,4)));return{feature_key:key,available:vals.length,available_rate:rows.length?round(vals.length/rows.length,4):0,distinct_scores:distinct.size,min:vals.length?round(Math.min(...vals)):null,max:vals.length?round(Math.max(...vals)):null};})}
function distribution(values:number[]){if(!values.length)return{observations:0,distinct_scores:0,min:null,max:null,mean:null,p10:null,p25:null,p50:null,p75:null,p90:null};const distinct=new Set(values.map(v=>round(v,4)));return{observations:values.length,distinct_scores:distinct.size,min:round(Math.min(...values)),max:round(Math.max(...values)),mean:round(values.reduce((a,b)=>a+b,0)/values.length),p10:round(quantile(values,.10)!),p25:round(quantile(values,.25)!),p50:round(quantile(values,.50)!),p75:round(quantile(values,.75)!),p90:round(quantile(values,.90)!)} }

Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});if(req.method!=="POST")return out(req,405,{error:"POST required"});
 const auth=req.headers.get("authorization")||"";if(!auth.startsWith("Bearer "))return out(req,401,{error:"Sign in required"});
 const url=Deno.env.get("SUPABASE_URL")||"",pub=env("SUPABASE_PUBLISHABLE_KEYS","SUPABASE_ANON_KEY"),secret=env("SUPABASE_SECRET_KEYS","SUPABASE_SERVICE_ROLE_KEY");if(!url||!pub||!secret)return out(req,503,{error:"Shadow evaluator configuration incomplete"});
 const uc=createClient(url,pub,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}}),admin=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}}),{data:who}=await uc.auth.getUser(),user=who?.user;if(!user)return out(req,401,{error:"Session invalid"});
 const {data:profile}=await admin.from("profiles").select("account_role").eq("id",user.id).maybeSingle();if(String(profile?.account_role||"")!=="developer")return out(req,403,{error:"Developer access required"});
 let body:any={};try{body=await req.json()}catch{return out(req,400,{error:"Invalid JSON"})}
 const modelKey=clean(body?.model_key||"closing_review",80),modelVersion=Math.trunc(Number(body?.model_version||3)),sampleSize=Math.min(200,Math.max(25,Math.trunc(Number(body?.sample_size||100)))),threshold=clamp(Number(body?.priority_threshold??60));
 if(!["closing_review","property_change_priority"].includes(modelKey))return out(req,400,{error:"Unsupported shadow model"});
 const [{data:model,error:me},{data:current,error:ce}]=await Promise.all([
  admin.from("intelligence_model_versions").select("model_key,version,status,calibration_state,signal_config,minimum_plan").eq("model_key",modelKey).eq("version",modelVersion).maybeSingle(),
  admin.from("intelligence_models").select("model_key,version,status,calibration_state").eq("model_key",modelKey).maybeSingle()
 ]);if(me||ce||!model||!current)return out(req,404,{error:"Shadow model or current baseline unavailable"});
 if(String(model.status)!=="draft")return out(req,409,{error:"Shadow evaluator accepts draft model versions only"});
 if(Number(current.version)===modelVersion)return out(req,409,{error:"Shadow evaluator refuses the current customer-facing model version"});
 const signals=Array.isArray(model.signal_config?.signals)?model.signal_config.signals:[],featureKeys=[...new Set(signals.map((s:any)=>clean(s?.id,140)).filter(Boolean))];if(!featureKeys.length)return out(req,409,{error:"Draft model has no feature contract"});
 const {data:defRows,error:de}=await admin.from("intelligence_feature_versions").select("feature_key,version,source_key,transform_type,config,status").in("feature_key",featureKeys).in("status",["draft","preview","live"]).order("version",{ascending:false});if(de)return out(req,503,{error:"Feature registry unavailable"});
 const defs=new Map<string,any>();for(const d of defRows||[])if(!defs.has(String(d.feature_key)))defs.set(String(d.feature_key),d);if(featureKeys.some(k=>!defs.has(k)))return out(req,409,{error:"Draft feature registry incomplete"});
 const sourceKeys=[...new Set(featureKeys.map(k=>clean(defs.get(k)?.source_key,140)).filter(Boolean))];
 const {data:formulaRows,error:fe}=await admin.from("derived_formula_registry").select("marker_id,status").in("marker_id",sourceKeys).eq("status","live");if(fe)return out(req,503,{error:"Formula registry unavailable"});const derivedSet=new Set((formulaRows||[]).map((x:any)=>String(x.marker_id))),derivedKeys=sourceKeys.filter(k=>derivedSet.has(k)),rawKeys=sourceKeys.filter(k=>!derivedSet.has(k));

 const {data:batches,error:be}=await admin.from("intelligence_evidence_batches").select("candidates").eq("user_id",user.id).eq("model_key",modelKey).eq("model_version",Number(current.version)).order("created_at",{ascending:false}).limit(100);if(be)return out(req,503,{error:"Baseline evidence pool unavailable"});
 const pins:string[]=[],seen=new Set<string>();for(const b of batches||[]){for(const c of Array.isArray(b.candidates)?b.candidates:[]){const pin=clean(c?.pams_pin,100);if(pin&&!seen.has(pin)){seen.add(pin);pins.push(pin);if(pins.length>=sampleSize)break}}if(pins.length>=sampleSize)break}
 if(pins.length<25)return out(req,409,{error:"Not enough owner-scoped baseline properties for a structural shadow sample",sample_count:pins.length});

 const derivedPromise=derivedKeys.length?fetch(`${url}/functions/v1/workbench-derived`,{method:"POST",headers:{Authorization:auth,apikey:pub,"Content-Type":"application/json"},body:JSON.stringify({pams_pins:pins,marker_ids:derivedKeys})}):Promise.resolve(null);
 const rawPromise=rawKeys.length?fetch(`${url}/functions/v1/workbench-hydrate`,{method:"POST",headers:{Authorization:auth,apikey:pub,"Content-Type":"application/json"},body:JSON.stringify({pams_pins:pins,marker_ids:rawKeys})}):Promise.resolve(null);
 const [dr,hr]=await Promise.all([derivedPromise,rawPromise]),derived=dr?await dr.json().catch(()=>({})):{};if(dr&&!dr.ok)return out(req,dr.status,{error:"Draft derived evidence dry-run failed",detail:clean(derived?.error,240)||null});const hydrated=hr?await hr.json().catch(()=>({})):{};if(hr&&!hr.ok)return out(req,hr.status,{error:"Draft raw evidence dry-run failed",detail:clean(hydrated?.error,240)||null});

 const rows:any[]=[];for(const pin of pins){const raw:Record<string,unknown>={};for(const sk of sourceKeys){const source=derivedSet.has(sk)?derived:hydrated,value=source?.markers?.[pin]?.[sk];if(value!==undefined&&value!==null&&value!=="")raw[sk]=value}const features:Record<string,number|null>={};for(const key of featureKeys){const def=defs.get(key),sourceKey=String(def.source_key);features[key]=transform(def,raw[sourceKey])}rows.push({features})}
 const scoreDefs=signals.filter((s:any)=>String(s?.role)!=="confidence"&&Number(s?.weight)>0),confidenceDefs=signals.filter((s:any)=>String(s?.role)==="confidence"),totalWeight=scoreDefs.reduce((a:number,s:any)=>a+Number(s.weight),0),minimumCoverage=clamp(Number(model.signal_config?.minimum_evidence_coverage??0));
 const scores:number[]=[],vectors=new Set<string>();let above=0,below=0,insufficient=0;for(const row of rows){let weighted=0,availableWeight=0;for(const s of scoreDefs){const value=numeric(row.features[String(s.id)]);if(value===null)continue;weighted+=value*Number(s.weight);availableWeight+=Number(s.weight)}const coverage=totalWeight?availableWeight/totalWeight*100:0;if(availableWeight<=0||coverage<minimumCoverage){insufficient++;continue}const score=clamp(weighted/availableWeight);scores.push(score);if(score>=threshold)above++;else below++;vectors.add(featureKeys.map(k=>{const v=numeric(row.features[k]);return v===null?"x":round(v,2)}).join("|"))}
 const stats=distribution(scores),features=featureStats(rows,featureKeys),policy=model.signal_config?.holdout_policy||{},minVectors=Number(policy.minimum_unique_feature_vectors||8),minClass=5,variableScoreFeatures=features.filter(f=>scoreDefs.some((s:any)=>String(s.id)===f.feature_key)&&f.distinct_scores>=2&&f.available_rate>=.5).length;
 const blockers:string[]=[];if(rows.length<25)blockers.push("shadow_sample_below_25");if(scores.length<25)blockers.push(`scorable_candidates:${scores.length}<25`);if(stats.distinct_scores<8)blockers.push(`distinct_scores:${stats.distinct_scores}<8`);if(vectors.size<minVectors)blockers.push(`unique_feature_vectors:${vectors.size}<${minVectors}`);if(above<minClass)blockers.push(`threshold_positive_candidates:${above}<${minClass}`);if(below<minClass)blockers.push(`threshold_negative_candidates:${below}<${minClass}`);if(variableScoreFeatures<2)blockers.push(`variable_score_features:${variableScoreFeatures}<2`);
 return out(req,200,{engine:ENGINE,generated_at:new Date().toISOString(),privacy:"aggregate_shadow_evaluation_no_property_identifiers",persistence:"none",model:{model_key:modelKey,model_version:modelVersion,status:model.status,calibration_state:model.calibration_state,current_customer_version:current.version,current_customer_status:current.status},sample:{requested:sampleSize,resolved:rows.length,scorable:scores.length,insufficient_evidence:insufficient},score_distribution:stats,threshold:{value:threshold,at_or_above:above,below},feature_health:features,unique_feature_vectors:vectors.size,variable_score_features:variableScoreFeatures,structurally_ready_for_fresh_holdout:blockers.length===0,blocked_reasons:blockers,promotion_boundary:"Shadow discrimination is not model validation. Do not persist a promotion holdout or move the current model pointer until structural readiness passes; fresh independent labels and calibration quality gates remain mandatory."});
});
