(function(){'use strict';
var URL='https://uvkvaxljhhngydvlrzom.supabase.co',KEY='sb_publishable_MYX59qCbK3d-21zDfJqkNw_fvmfnexa',client,user,entitlement,counts={properties:0,cases:0};
var $=function(id){return document.getElementById(id);};
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function label(v){return v==='pro_plus'?'Pro+':v==='pro'?'Pro':v==='standard'?'Standard':v==='developer'?'Developer':String(v||'Standard').replace(/_/g,' ').replace(/\b\w/g,function(c){return c.toUpperCase();});}
function date(v){if(!v)return'—';return new Date(v).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});}
function sb(){return client||(client=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,flowType:'pkce',storageKey:'sb-uvkvaxljhhngydvlrzom-auth-token'}}));}
function profile(){return(user.user_metadata&&user.user_metadata.watchdog_profile)||{};}
function completion(p){var keys=['preferred_name','phone','home_zip','use_case','priority','timeframe','property_focus','counties'],n=keys.filter(function(k){return p[k]&&String(p[k]).trim();}).length;return Math.round(n/keys.length*100);}
function select(id,title,options,value){return'<label>'+title+'<select id="'+id+'">'+options.map(function(o){return'<option value="'+o[0]+'"'+(o[0]===value?' selected':'')+'>'+o[1]+'</option>';}).join('')+'</select></label>';}
function render(){var p=profile(),developer=entitlement.account_role==='developer',plan=developer?'developer':entitlement.plan_tier,percent=completion(p),provider=(user.app_metadata&&user.app_metadata.provider)||'email';
$('ac-gate').hidden=true;$('ac-app').hidden=false;$('ac-app').innerHTML='<section class="ac-profile-hero"><div class="ac-avatar">'+esc((p.preferred_name||user.email||'W').charAt(0).toUpperCase())+'</div><div><span>PROFILE &amp; SETTINGS</span><h1>'+esc(p.preferred_name||user.user_metadata.full_name||'Your Watchdog profile')+'</h1><p>'+esc(user.email||'')+' · '+label(plan)+' member</p></div><div class="ac-completion"><b>'+percent+'%</b><span>Profile complete</span><i><em style="width:'+percent+'%"></em></i></div></section>'+  
'<section class="ac-section"><header><div><span>YOUR WATCHDOG</span><h2>Activity at a glance</h2></div></header><div class="ac-stats"><article><i class="fas fa-house"></i><b>'+counts.properties+'</b><span>Saved properties</span></article><article><i class="fas fa-folder-tree"></i><b>'+counts.cases+'</b><span>Professional cases</span></article><article><i class="fas fa-calendar"></i><b>'+date(user.created_at)+'</b><span>Member since</span></article></div></section>'+  
'<section class="ac-section"><header><div><span>PERSONALIZATION</span><h2>Tell Watchdog what matters</h2><p>Your answers tune recommendations and defaults. They never change paid access.</p></div></header><details open><summary><i class="fas fa-user"></i><span><b>Profile details</b><small>Name, contact and home area</small></span><i class="fas fa-chevron-down"></i></summary><div class="ac-form-grid"><label>Preferred name<input id="ac-name" value="'+esc(p.preferred_name||'')+'" autocomplete="name"></label><label>Phone<input id="ac-phone" value="'+esc(p.phone||'')+'" autocomplete="tel"></label><label>Home ZIP<input id="ac-zip" value="'+esc(p.home_zip||'')+'" inputmode="numeric" maxlength="10"></label><label>Counties or towns<input id="ac-counties" value="'+esc(p.counties||'')+'" placeholder="Camden, Gloucester…"></label></div></details>'+  
'<details><summary><i class="fas fa-bullseye"></i><span><b>Property goals</b><small>Why you use Watchdog</small></span><i class="fas fa-chevron-down"></i></summary><div class="ac-form-grid">'+select('ac-use','I use Watchdog as',[['homeowner','Homeowner'],['professional','Professional'],['both','Both']],p.use_case||'homeowner')+select('ac-priority','Current priority',[['tax','Understand or lower taxes'],['buy','Buy a property'],['sell','Sell a property'],['invest','Investment research'],['client','Client diligence']],p.priority||'tax')+select('ac-timeframe','Timeframe',[['research','Just researching'],['0_3','Within 3 months'],['3_6','3–6 months'],['6_12','6–12 months'],['later','More than a year']],p.timeframe||'research')+select('ac-focus','Property focus',[['residential','Residential'],['commercial','Commercial'],['mixed','Both']],p.property_focus||'residential')+'</div></details>'+  
'<details><summary><i class="fas fa-briefcase"></i><span><b>Professional workflow</b><small>Role-specific defaults and tools</small></span><i class="fas fa-chevron-down"></i></summary><div class="ac-form-grid">'+select('ac-profession-select','Primary role',[['homeowner','Homeowner'],['real_estate','Real estate professional'],['attorney','Attorney'],['mortgage_lending','Mortgage / lending'],['investor','Investor'],['appraiser','Appraiser'],['contractor','Contractor'],['property_tax_professional','Property tax professional'],['title_closing','Title / closing'],['other','Other professional']],entitlement.profession||'homeowner')+select('ac-notify','Update preference',[['important','Important changes only'],['weekly','Weekly digest'],['all','Every monitored change'],['none','No data alerts']],p.notification_preference||'important')+'</div></details><div class="ac-save-row"><button id="ac-save-profile" type="button">Save profile</button><span id="ac-profile-note" aria-live="polite"></span></div></section>'+  
'<section class="ac-grid"><article class="ac-card ac-plan"><span>CURRENT MEMBERSHIP</span><h2>'+label(plan)+'</h2><p>'+ (developer?'Developer access is billing-independent.':label(entitlement.subscription_status||'none')+' subscription status')+'</p><div class="ac-meta"><div><small>Renewal / period end</small><b>'+date(entitlement.current_period_end)+'</b></div><div><small>Primary role</small><b>'+label(entitlement.profession||'homeowner')+'</b></div></div>'+(!developer&&['active','trialing','past_due'].indexOf(entitlement.subscription_status)>=0?'<a class="ac-primary" href="#" data-billing-portal><i class="fas fa-arrow-up-right-from-square"></i> Manage membership</a>':'')+'</article><article class="ac-card"><span>ACCOUNT &amp; SECURITY</span><h2>Sign-in details</h2><div class="ac-account-rows"><div><i class="fas fa-envelope"></i><span><b>'+esc(user.email||'')+'</b><small>Email</small></span><i class="fas fa-lock"></i></div><div><i class="'+(provider==='google'?'fab fa-google':'fas fa-key')+'"></i><span><b>'+label(provider)+'</b><small>Sign-in provider</small></span><i class="fas fa-circle-check"></i></div><div><i class="fas fa-clock"></i><span><b>'+date(user.last_sign_in_at)+'</b><small>Last sign-in</small></span></div></div></article></section>';
var save=$('ac-save-profile');if(save)save.onclick=saveProfile;if(window.NJPTRBilling&&window.NJPTRBilling.bindPortalLinks)window.NJPTRBilling.bindPortalLinks();}
function saveProfile(){var note=$('ac-profile-note'),role=$('ac-profession-select').value,p={preferred_name:$('ac-name').value.trim(),phone:$('ac-phone').value.trim(),home_zip:$('ac-zip').value.trim(),counties:$('ac-counties').value.trim(),use_case:$('ac-use').value,priority:$('ac-priority').value,timeframe:$('ac-timeframe').value,property_focus:$('ac-focus').value,notification_preference:$('ac-notify').value,updated_at:new Date().toISOString()};note.textContent='Saving…';Promise.all([sb().auth.updateUser({data:Object.assign({},user.user_metadata,{watchdog_profile:p})}),sb().from('professional_preferences').upsert({user_id:user.id,profession:role,onboarding_complete:true,updated_at:new Date().toISOString()},{onConflict:'user_id'})]).then(function(results){if(results[0].error)throw results[0].error;if(results[1].error)throw results[1].error;user=results[0].data.user;entitlement.profession=role;render();$('ac-profile-note').textContent='Saved. Your recommendations will use these preferences.';}).catch(function(e){note.textContent=e.message||'Could not save your profile.';});}
function init(){if(!window.supabase)return;sb().auth.getSession().then(function(r){user=r.data&&r.data.session&&r.data.session.user;if(!user)throw Error('signed out');return Promise.all([sb().rpc('get_my_entitlement'),sb().from('saved_properties').select('id',{count:'exact',head:true}),sb().from('professional_cases').select('id',{count:'exact',head:true})]);}).then(function(v){var rows=v[0].data||[];entitlement=Array.isArray(rows)?rows[0]:rows;if(v[0].error||!entitlement)throw v[0].error||Error('No entitlement');counts.properties=v[1].count||0;counts.cases=v[2].count||0;if(window.NJPTRPlan)window.NJPTRPlan.init(user,entitlement);render();}).catch(function(){});}init();})();
