(function(){'use strict';
var URL='https://uvkvaxljhhngydvlrzom.supabase.co',KEY='sb_publishable_MYX59qCbK3d-21zDfJqkNw_fvmfnexa',client,user,entitlement;
var $=function(id){return document.getElementById(id);};
function label(v){return v==='pro_plus'?'Pro+':v==='pro'?'Pro':v==='standard'?'Standard':v==='developer'?'Developer':String(v||'Standard').replace(/_/g,' ').replace(/\b\w/g,function(c){return c.toUpperCase();});}
function date(v){if(!v)return'—';return new Date(v).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});}
function sb(){return client||(client=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,flowType:'pkce',storageKey:'sb-uvkvaxljhhngydvlrzom-auth-token'}}));}
function paint(){var e=entitlement,q=new URLSearchParams(location.search),notice=$('ac-success');$('ac-gate').hidden=true;$('ac-app').hidden=false;$('ac-plan').textContent=label(e.account_role==='developer'?'developer':e.plan_tier);$('ac-status').textContent=e.account_role==='developer'?'Developer access · billing independent':label(e.subscription_status||'none')+' subscription status';$('ac-renewal').textContent=date(e.current_period_end);$('ac-profession').textContent=label(e.profession||'homeowner');$('ac-profession-select').value=e.profession||'homeowner';if(e.account_role!=='developer'&&['active','trialing','past_due'].indexOf(e.subscription_status)>=0)$('ac-portal').hidden=false;if(window.NJPTRPlan)window.NJPTRPlan.init(user,{account_role:e.account_role,plan_tier:e.plan_tier,subscription_status:e.subscription_status});if(q.get('checkout')==='success')notice.hidden=false;if(q.get('plan_change')==='pending'){notice.querySelector('b').textContent='Plan change requested.';notice.querySelector('span').textContent='Paddle is confirming your '+label(q.get('plan'))+' subscription. Watchdog access changes only after the verified billing event arrives.';notice.hidden=false;}}
function saveProfession(){var role=$('ac-profession-select').value,note=$('ac-profession-note');note.textContent='Saving…';sb().from('professional_preferences').upsert({user_id:user.id,profession:role,onboarding_complete:true,updated_at:new Date().toISOString()},{onConflict:'user_id'}).then(function(r){if(r.error)throw r.error;entitlement.profession=role;paint();note.textContent='Saved. Recommendations can now follow this workflow.';}).catch(function(e){note.textContent=e.message||'Could not save role.';});}
function init(){if(!window.supabase)return;sb().auth.getSession().then(function(r){user=r.data&&r.data.session&&r.data.session.user;if(!user)throw Error('signed out');return sb().rpc('get_my_entitlement');}).then(function(result){var rows=result.data||[];entitlement=Array.isArray(rows)?rows[0]:rows;if(result.error||!entitlement)throw result.error||Error('No entitlement');paint();$('ac-save-profession').onclick=saveProfession;}).catch(function(){});}
init();})();
