(function(){'use strict';
var SB_URL='https://uvkvaxljhhngydvlrzom.supabase.co',KEY='sb_publishable_MYX59qCbK3d-21zDfJqkNw_fvmfnexa';
var client,user,saved=[],farm=[],events=[],actions=[],opps=[],queue='top',sort='score',query='',digest=null,displayLimit=12,rawActionableCount=0;
var $=function(id){return document.getElementById(id);};
function sb(){return client||(client=window.supabase.createClient(SB_URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,flowType:'pkce',storageKey:'sb-uvkvaxljhhngydvlrzom-auth-token'}}));}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function safe(v){try{var u=new URL(v,location.origin);return /^https?:$/.test(u.protocol)?u.href:'';}catch(_){return'';}}
function val(o,names){for(var i=0;i<names.length;i++){var v=o&&o[names[i]];if(v!==undefined&&v!==null&&v!=='')return v;}return null;}
function num(v){var n=Number(String(v==null?'':v).replace(/[$,%\s,]/g,''));return isFinite(n)?n:null;}
function date(v){if(!v)return'Not dated';var d=new Date(v);return isNaN(d)?'Not dated':d.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});}
function daysAgo(v){var n=(Date.now()-new Date(v).getTime())/86400000;return isFinite(n)?Math.max(0,Math.floor(n)):9999;}
function toast(m){var t=$('pl-toast');if(!t)return;t.textContent=m;t.style.display='block';clearTimeout(window._adt);window._adt=setTimeout(function(){t.style.display='none';},2600);}
var TYPES={
 assessment_change:{label:'Assessment changed materially',icon:'fa-building-columns',starter:'I noticed the public assessment record changed. I can walk you through what the town now reports and what it may mean.',source:'NJ Division of Taxation MOD-IV property assessment records',url:'https://www.nj.gov/treasury/taxation/lpt/statdata.shtml',limit:'An assessment change alone does not prove overassessment or establish an appeal case.'},
 tax_change:{label:'Annual property tax changed',icon:'fa-receipt',starter:'Your public tax record changed. Would a plain-English review of the new annual carrying cost be useful?',source:'NJ Division of Taxation and municipal tax records',url:'https://www.nj.gov/treasury/taxation/lpt/statdata.shtml',limit:'Published tax figures may lag a supplemental bill, payment, deduction, or municipal correction.'},
 appeal_deadline:{label:'Assessment-review deadline is approaching',icon:'fa-calendar-day',starter:'The assessment-review window is approaching. I can share the public dates and help you gather the right property records before deciding what to do.',source:'NJ Division of Taxation appeal guidance',url:'https://www.nj.gov/treasury/taxation/pdf/lpt/appeal.pdf',limit:'Deadlines and filing rules vary. This reminder is not legal advice or a recommendation to appeal.'},
 permit_change:{label:'Permit lifecycle changed',icon:'fa-helmet-safety',starter:'A public permit record changed for the property. I can help explain how completed or open work may show up in a future sale or assessment conversation.',source:'NJ Department of Community Affairs construction permit data',url:'https://www.nj.gov/dca/codes/reporter/',limit:'A permit record does not prove construction quality, completion, value, or code compliance.'},
 deed_change:{label:'Recorded transfer activity changed',icon:'fa-file-signature',starter:'The public property record shows recent transfer activity. I can provide a post-closing check of the assessment, taxes, and local market context.',source:'NJ Division of Taxation MOD-IV/SR1A records',url:'https://www.nj.gov/treasury/taxation/lpt/statdata.shtml',limit:'A recorded transfer is not evidence that a person wants to sell or needs real-estate services.'},
 market_change:{label:'Verified nearby sales moved',icon:'fa-house-signal',starter:'New verified sales changed the local market picture. I can share a short, factual update focused on comparable homes—not an automated valuation.',source:'NJ Division of Taxation SR1A verified sales',url:'https://www.nj.gov/treasury/taxation/lpt/statdata.shtml',limit:'Nearby sales are context only. A property-specific valuation requires relevant comparable selection and professional judgment.'},
 municipal_change:{label:'Municipal assessment context changed',icon:'fa-city',starter:'The town updated a public assessment or revaluation signal. I can explain what changed and which property numbers are worth watching.',source:'NJ Division of Taxation and municipal notices',url:'https://www.nj.gov/treasury/taxation/lpt/statdata.shtml',limit:'Municipal signals do not by themselves determine a property value or appeal outcome.'},
 evidence_change:{label:'Chapter 123 evidence changed',icon:'fa-scale-balanced',starter:'There is new independently testable assessment evidence. I can show you the public ratio and comparable facts, with the limitations clearly marked.',source:'NJ Division of Taxation equalization and verified-sale records',url:'https://www.nj.gov/treasury/taxation/lpt/chapter123.shtml',limit:'This is a screening reason, not a win probability, appraisal, legal opinion, or filing recommendation.'},
 record_review:{label:'Current property record is ready for review',icon:'fa-clipboard-check',starter:'I pulled together the current public assessment and tax record for your property. Would a short, plain-English annual review be useful?',source:'NJ Division of Taxation MOD-IV property assessment records',url:'https://www.nj.gov/treasury/taxation/lpt/statdata.shtml',limit:'This is a current-record check-in, not evidence that the property changed, is overassessed, or is likely to sell.'}
};
var ACTIONABLE_TYPES=['assessment_change','tax_change','appeal_deadline','permit_change','deed_change','market_change','municipal_change','evidence_change'];
function propertyKey(p){return String((p&&p.pams_pin)||'').trim()||String((p&&p.address)||'').trim().toLowerCase();}
function sphereProperties(){var seen={};return farm.concat(saved).filter(function(p){var k=propertyKey(p);if(!k||seen[k])return false;seen[k]=1;return true;});}
function propertyForEvent(e){var payload=e.payload||{},pin=String(e.pams_pin||payload.pams_pin||'').trim(),address=String(payload.property_address||payload.address||'').trim().toLowerCase();return sphereProperties().find(function(p){return(pin&&String(p.pams_pin||'').trim()===pin)||(address&&String(p.address||'').trim().toLowerCase()===address);})||null;}
function relationFor(pin,address){var all=farm.concat(saved),r=all.find(function(x){return(pin&&x.pams_pin===pin)||String(x.address||'').toLowerCase()===String(address||'').toLowerCase();});return r&&r.relationship||((r&&r.kind==='home')?'claimed_home':'watchlist');}
function relPoints(r){return{past_client:20,claimed_home:20,sphere:17,watchlist:15,farm:10}[r]||10;}
function evidencePoints(e){var u=safe(e.source_url),trusted=u&&(/\.nj\.gov|nj\.gov|\.gov\//i.test(u));return trusted?25:(u?21:17);}
function magnitudePoints(e){var d=Math.abs(num(e.delta_numeric)||0),old=Math.abs(num(e.old_value)||0);if(d&&old)return Math.min(30,12+Math.round(Math.min(1,d/old)*18));if(d)return Math.min(30,14+Math.round(Math.log10(d+1)*4));return e.severity==='action'?26:e.severity==='important'?21:15;}
function freshnessPoints(e){var d=daysAgo(e.occurred_at);return d<=7?25:d<=30?21:d<=90?16:d<=180?11:6;}
function makeOpp(e){var t=TYPES[e.event_type],property=propertyForEvent(e);if(!t||ACTIONABLE_TYPES.indexOf(e.event_type)<0||!property)return null;var payload=e.payload||{},address=property.address||payload.property_address||payload.address||'Saved property',town=property.town||property.municipality||payload.municipality||'',pin=property.pams_pin||e.pams_pin||payload.pams_pin||'';var rel=relationFor(pin,address),parts={freshness:freshnessPoints(e),magnitude:magnitudePoints(e),evidence:evidencePoints(e),relationship:relPoints(rel)};var score=parts.freshness+parts.magnitude+parts.evidence+parts.relationship;var q=score>=76&&daysAgo(e.occurred_at)<=30?'now':score>=58&&daysAgo(e.occurred_at)<=120?'week':'watch';var key=[propertyKey(property),e.event_type].join(':');return{key:key,pin:pin,address:address,town:town,type:e.event_type,title:e.title||t.label,reason:e.summary||t.label,observed:e.occurred_at,source:e.source_url||t.url,sourceLabel:t.source,starter:t.starter,limit:t.limit,score:score,parts:parts,queue:q,relationship:rel,marker:e.marker_id||'',updateCount:1,raw:e};}
function actionFor(key){return actions.find(function(a){return a.opportunity_key===key;})||{};}
function activeOpps(){return opps.filter(function(o){var a=actionFor(o.key);return a.action_state!=='dismissed'&&!(a.action_state==='snoozed'&&a.snoozed_until&&new Date(a.snoozed_until)>new Date());});}
function money(v){var n=num(v);return n===null?'not available':n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});}
function baselineOpp(p){var pin=p.pams_pin||'',address=p.address||'Saved property',town=p.town||p.municipality||'',rel=relationFor(pin,address),observed=p.updated_at||p.created_at||new Date().toISOString(),facts=[];if(num(p.assessed)!==null)facts.push('assessment '+money(p.assessed));if(num(p.last_year_tax)!==null)facts.push('annual tax '+money(p.last_year_tax));if(num(p.watchdog_value)!==null)facts.push('estimated market context '+money(p.watchdog_value));var parts={freshness:Math.min(18,freshnessPoints({occurred_at:observed})),magnitude:12,evidence:pin?25:17,relationship:relPoints(rel)};return{key:propertyKey(p)+':record_review',pin:pin,address:address,town:town,type:'record_review',title:TYPES.record_review.label,reason:facts.length?'Current public record: '+facts.join(' · ')+'.':'The current parcel record is available for a factual annual check-in.',observed:observed,source:TYPES.record_review.url,sourceLabel:TYPES.record_review.source,starter:TYPES.record_review.starter,limit:TYPES.record_review.limit,score:parts.freshness+parts.magnitude+parts.evidence+parts.relationship,parts:parts,queue:'week',relationship:rel,marker:'',updateCount:1,raw:p};}
function compute(){var grouped={},covered={};rawActionableCount=0;events.forEach(function(e){var o=makeOpp(e);if(!o)return;rawActionableCount++;covered[o.pin||o.address.toLowerCase()]=1;var prior=grouped[o.key];if(!prior){grouped[o.key]=o;return;}prior.updateCount++;if(o.score>prior.score||new Date(o.observed)>new Date(prior.observed)){o.updateCount=prior.updateCount;grouped[o.key]=o;}});sphereProperties().forEach(function(p){var k=p.pams_pin||String(p.address||'').toLowerCase();if(k&&!covered[k]){var o=baselineOpp(p);grouped[o.key]=o;}});opps=Object.keys(grouped).map(function(k){return grouped[k];});draw();}
function stat(icon,label,n,note){return'<article class="ad-stat"><i class="fas '+icon+'"></i><div><b>'+Number(n||0).toLocaleString()+'</b><span>'+label+'</span>'+(note?'<small>'+note+'</small>':'')+'</div></article>';}
function drawStats(){var all=activeOpps(),fresh=all.filter(function(o){return daysAgo(o.observed)<=7;}).length,strong=all.filter(function(o){return o.parts.evidence>=21;}).length,followups=actions.filter(function(a){return['touch','reply','valuation_request','appointment'].indexOf(a.outcome)>=0;}).length;$('ad-stats').innerHTML=stat('fa-bolt','Act now',all.filter(function(o){return o.queue==='now';}).length,'highest-priority signals')+stat('fa-clock-rotate-left','New this week',fresh,'recent evidence')+stat('fa-shield-check','Evidence ready',strong,'linked public sources')+stat('fa-phone-arrow-up-right','Conversations',followups,'touches and replies');}
function list(){var out=activeOpps().filter(function(o){return(queue==='top'||queue==='all'||o.queue===queue)&&(!query||[o.address,o.town,o.title,o.reason].join(' ').toLowerCase().indexOf(query)>=0);});out.sort(function(a,b){if(sort==='fresh')return new Date(b.observed)-new Date(a.observed);if(sort==='address')return a.address.localeCompare(b.address);return b.score-a.score;});if(queue==='top'){var seen={};out=out.filter(function(o){var k=o.pin||o.address.toLowerCase();if(seen[k])return false;seen[k]=1;return true;}).slice(0,10);}return out;}
function propertyUrl(o){return o.pin?'/property/home.html?pin='+encodeURIComponent(o.pin):'/property/?address='+encodeURIComponent([o.address,o.town,'NJ'].filter(Boolean).join(', '));}
function focusCard(){var best=list()[0],el=$('ad-focus');if(!el)return;if(!best){el.innerHTML='<div class="ad-focus-empty"><i class="fas fa-circle-check"></i><div><b>Your priority desk is clear.</b><span>Add properties or return after the next material public-record update.</span></div></div>';return;}el.innerHTML='<div class="ad-focus-label"><span>BEST NEXT CONVERSATION</span><small>Anonymous property signal · match it to your own CRM</small></div><div class="ad-focus-main"><div class="ad-focus-score"><b>'+best.score+'</b><span>/100</span></div><div><a href="'+esc(propertyUrl(best))+'">'+esc(best.address)+(best.town?' · '+esc(best.town):'')+'</a><h3>'+esc(best.title)+'</h3><p>'+esc(best.reason)+'</p></div></div><div class="ad-focus-actions"><button type="button" data-focus="evidence" data-key="'+esc(best.key)+'"><i class="fas fa-magnifying-glass-chart"></i> Review evidence</button><a href="'+esc(propertyUrl(best))+'"><i class="fas fa-house"></i> Open property</a></div>';}
function card(o){var a=actionFor(o.key);return'<article class="ad-card" data-key="'+esc(o.key)+'"><div class="ad-card-top"><div class="ad-score"><div><b>'+o.score+'</b><small> / 100</small></div></div><div><h3><i class="fas '+TYPES[o.type].icon+'"></i> '+esc(o.title)+'</h3><a class="ad-address ad-address-link" href="'+esc(propertyUrl(o))+'">'+esc(o.address)+(o.town?' · '+esc(o.town):'')+' <i class="fas fa-arrow-right"></i></a><p class="ad-reason">'+esc(o.reason)+'</p></div><span class="ad-queue '+o.queue+'">'+(o.queue==='now'?'NOW':o.queue==='week'?'THIS WEEK':'WATCH')+'</span></div><div class="ad-card-meta"><span><i class="fas fa-database"></i>'+esc(o.sourceLabel)+'</span><span><i class="fas fa-clock"></i>'+date(o.observed)+'</span><span><i class="fas fa-user-check"></i>'+esc(o.relationship.replace(/_/g,' '))+'</span>'+(o.updateCount>1?'<span><i class="fas fa-layer-group"></i>'+o.updateCount+' updates combined</span>':'')+'</div><div class="ad-card-actions"><button class="primary" data-action="evidence"><i class="fas fa-magnifying-glass-chart"></i> Why this reason</button><a href="'+esc(propertyUrl(o))+'"><i class="fas fa-house"></i> Open property</a><button data-action="watch"><i class="fas fa-bookmark"></i> '+(a.action_state==='watched'?'Watching':'Quick-watch')+'</button><button data-action="snooze"><i class="fas fa-clock"></i> Snooze</button><select class="ad-outcome" data-action="outcome" aria-label="Record outcome"><option value="">Record outcome</option><option value="touch">Touch recorded</option><option value="reply">Reply</option><option value="valuation_request">Valuation request</option><option value="appointment">Appointment</option><option value="listing">Listing</option><option value="not_relevant">Not relevant</option></select><button class="dismiss" data-action="dismiss" aria-label="Dismiss"><i class="fas fa-xmark"></i></button></div></article>';}
function draw(){var all=activeOpps(),counts={now:0,week:0,watch:0};all.forEach(function(o){counts[o.queue]++;});$('ad-total').textContent=all.length;$('ad-now-count').textContent=counts.now;$('ad-week-count').textContent=counts.week;$('ad-watch-count').textContent=counts.watch;var l=list(),shown=queue==='top'?l:l.slice(0,displayLimit);$('ad-result-count').textContent=queue==='top'?(l.length+' priorit'+(l.length===1?'y':'ies')):(shown.length+' of '+l.length+' reason'+(l.length===1?'':'s'));$('ad-queue-title').textContent={top:'Your priority worklist',now:'Act now',week:'Plan this week',watch:'Keep watching',all:'All active reasons'}[queue];$('ad-list').innerHTML=shown.length?shown.map(card).join(''):'<div class="ad-empty"><i class="fas fa-inbox"></i><b>No property-specific reasons in this view.</b><p>Routine source refreshes are intentionally hidden. Add your sphere or wait for a material assessment, tax, permit, deed, market, municipal, deadline, or evidence change.</p></div>';$('ad-load-more').hidden=queue==='top'||shown.length>=l.length;drawStats();drawCoverage();focusCard();}
function drawCoverage(){var unique={},matched=0;farm.concat(saved).forEach(function(p){var k=p.pams_pin||String(p.address||'').toLowerCase();if(!k||unique[k])return;unique[k]=1;if(p.pams_pin)matched++;});var total=Object.keys(unique).length;$('ad-coverage').innerHTML='<div class="ad-coverage-row"><span>Properties loaded</span><b>'+total+'</b></div><div class="ad-coverage-row"><span>Parcel matched</span><b>'+matched+'</b></div><div class="ad-coverage-row"><span>Actionable reasons</span><b>'+opps.length+'</b></div><div class="ad-coverage-row"><span>Updates combined</span><b>'+Math.max(0,rawActionableCount-opps.length)+'</b></div><div class="ad-coverage-row"><span>Plan capacity</span><b>'+total+' / 1,000</b></div>';}
function saveAction(o,values){var base=Object.assign({user_id:user.id,opportunity_key:o.key,pams_pin:o.pin||null,updated_at:new Date().toISOString()},values);return sb().from('agent_opportunity_actions').upsert(base,{onConflict:'user_id,opportunity_key'}).select().single().then(function(r){if(r.error)throw r.error;var i=actions.findIndex(function(a){return a.opportunity_key===o.key;});if(i<0)actions.push(r.data);else actions[i]=r.data;draw();return r.data;});}
function showEvidence(o){var src=safe(o.source),p=o.parts;$('ad-drawer-content').innerHTML='<span class="top-eyebrow">SOURCED TOUCH REASON</span><h2 id="ad-drawer-title">'+esc(o.title)+'</h2><p>'+esc(o.reason)+'</p><div class="ad-evidence-score"><div><b>'+p.freshness+'</b><span>FRESHNESS / 25</span></div><div><b>'+p.magnitude+'</b><span>MAGNITUDE / 30</span></div><div><b>'+p.evidence+'</b><span>EVIDENCE / 25</span></div><div><b>'+p.relationship+'</b><span>RELEVANCE / 20</span></div></div><section class="ad-evidence-section"><h3>Why it is useful</h3><p>The '+o.score+'/100 score ranks the timeliness and usefulness of this property conversation. It does not predict a move, sale, distress, or listing.</p></section><section class="ad-evidence-section"><h3>Homeowner-safe conversation starter</h3><p>“'+esc(o.starter)+'”</p><button class="ad-import-submit" data-copy="'+esc(o.starter)+'"><i class="fas fa-copy"></i> Copy conversation starter</button></section><section class="ad-evidence-section"><h3>Evidence</h3><p><b>'+esc(o.sourceLabel)+'</b><br>Observed '+date(o.observed)+(o.marker?'<br>Marker: <a href="/property/marker.html?id='+encodeURIComponent(o.marker)+'">'+esc(o.marker)+'</a>':'')+'</p>'+(src?'<a href="'+esc(src)+'" target="_blank" rel="noopener">Open source <i class="fas fa-arrow-up-right-from-square"></i></a>':'')+'</section><section class="ad-evidence-section"><h3>Limitations</h3><p class="ad-limit">'+esc(o.limit)+'</p></section>';$('ad-drawer').hidden=false;document.body.style.overflow='hidden';saveAction(o,{first_opened_at:actionFor(o.key).first_opened_at||new Date().toISOString()}).catch(function(){});}
function closeDrawer(){$('ad-drawer').hidden=true;document.body.style.overflow='';}
function bindList(){$('ad-list').addEventListener('click',function(e){var card=e.target.closest('.ad-card'),b=e.target.closest('[data-action]');if(!card||!b||b.tagName==='SELECT')return;var o=opps.find(function(x){return x.key===card.dataset.key;});if(!o)return;var act=b.dataset.action;if(act==='evidence')showEvidence(o);if(act==='watch')saveAction(o,{action_state:'watched'}).then(function(){toast('Added to your watch queue');});if(act==='snooze'){var d=new Date();d.setDate(d.getDate()+7);saveAction(o,{action_state:'snoozed',snoozed_until:d.toISOString()}).then(function(){toast('Snoozed for one week');});}if(act==='dismiss')saveAction(o,{action_state:'dismissed'}).then(function(){toast('Reason dismissed');});});$('ad-list').addEventListener('change',function(e){if(!e.target.matches('[data-action="outcome"]')||!e.target.value)return;var card=e.target.closest('.ad-card'),o=opps.find(function(x){return x.key===card.dataset.key;}),v=e.target.value;saveAction(o,{action_state:'completed',outcome:v,touched_at:new Date().toISOString()}).then(function(){toast('Outcome recorded');});});}
function csvRows(text){var lines=String(text||'').split(/\r?\n/).filter(function(x){return x.trim();});if(!lines.length)return[];var split=function(line){return line.match(/("(?:[^"]|"")*"|[^,]*)(?:,|$)/g).map(function(x){return x.replace(/,$/,'').replace(/^"|"$/g,'').replace(/""/g,'"').trim();});};var head=split(lines[0]).map(function(x){return x.toLowerCase().replace(/\s+/g,'_');});return lines.slice(1).map(function(line){var a=split(line),o={};head.forEach(function(h,i){o[h]=a[i]||'';});return o;});}
function importPayload(){var csv=!$('ad-import-csv').hidden,allowed=['past_client','sphere','claimed_home','watchlist','farm'];if(csv)return csvRows($('ad-csv').value).slice(0,1000).filter(function(x){return x.address;}).map(function(x){return{user_id:user.id,address:x.address,municipality:x.municipality||null,county:x.county||null,zip:x.zip||x.postal_code||null,pams_pin:x.pams_pin||null,contact_ref:x.contact_ref||null,relationship:allowed.indexOf(x.relationship)>=0?x.relationship:'farm',source:'csv',match_status:x.pams_pin?'matched':'pending',updated_at:new Date().toISOString()};});return Array.from(document.querySelectorAll('.ad-saved-row input:checked')).map(function(x){var p=saved.find(function(s){return String(s.id)===x.value;});return{user_id:user.id,address:p.address,municipality:p.town||p.municipality||null,county:p.county||null,zip:p.zip||p.postal_code||null,pams_pin:p.pams_pin||null,relationship:p.kind==='home'?'claimed_home':'watchlist',source:'saved_property',match_status:p.pams_pin?'matched':'pending',updated_at:new Date().toISOString()};});}
function drawSaved(){$('ad-saved-count').textContent=saved.length+' available';$('ad-saved-list').innerHTML=saved.length?saved.map(function(p){return'<label class="ad-saved-row"><input type="checkbox" value="'+esc(p.id)+'"><span><b>'+esc(p.address)+'</b><small>'+esc([p.town||p.municipality,p.county].filter(Boolean).join(' · '))+'</small></span><em>'+esc(p.kind==='home'?'Your home':'Watchlist')+'</em></label>';}).join(''):'<div class="ad-empty">No saved properties yet.</div>';}
function openImport(){$('ad-import-modal').hidden=false;document.body.style.overflow='hidden';drawSaved();}
function closeImport(){$('ad-import-modal').hidden=true;document.body.style.overflow='';}
function bindImport(){$('ad-import-open').onclick=$('ad-import-side').onclick=openImport;$('ad-import-close').onclick=closeImport;$('ad-import-modal').addEventListener('click',function(e){if(e.target===$('ad-import-modal'))closeImport();});document.querySelectorAll('[data-import-view]').forEach(function(b){b.onclick=function(){document.querySelectorAll('[data-import-view]').forEach(function(x){x.classList.toggle('on',x===b);});$('ad-import-saved').hidden=b.dataset.importView!=='saved';$('ad-import-csv').hidden=b.dataset.importView!=='csv';$('ad-import-submit').textContent=b.dataset.importView==='csv'?'Import CSV':'Add selected properties';};});$('ad-select-all').onchange=function(){document.querySelectorAll('.ad-saved-row input').forEach(function(x){x.checked=$('ad-select-all').checked;});};$('ad-import-submit').onclick=function(){var rows=importPayload(),status=$('ad-import-status');if(!rows.length){status.textContent='Choose at least one property or paste CSV rows.';return;}status.textContent='Adding '+rows.length+' properties…';var chunks=[];for(var i=0;i<rows.length;i+=100)chunks.push(rows.slice(i,i+100));Promise.all(chunks.map(function(c){return sb().from('agent_farm_properties').upsert(c,{onConflict:'user_id,address'});})).then(function(res){var err=res.find(function(x){return x.error;});if(err)throw err.error;status.textContent=rows.length+' properties added.';return load();}).then(function(){setTimeout(closeImport,500);}).catch(function(e){status.textContent=e.message||'Import could not be completed.';});};}
function bind(){$('ad-tabs').onclick=function(e){var b=e.target.closest('[data-queue]');if(!b)return;queue=b.dataset.queue;displayLimit=12;document.querySelectorAll('[data-queue]').forEach(function(x){x.classList.toggle('on',x===b);});draw();};$('ad-focus').onclick=function(e){var b=e.target.closest('[data-focus="evidence"]');if(!b)return;var o=opps.find(function(x){return x.key===b.dataset.key;});if(o)showEvidence(o);};$('ad-search').oninput=function(){query=this.value.trim().toLowerCase();displayLimit=12;draw();};$('ad-sort').onchange=function(){sort=this.value;displayLimit=12;draw();};$('ad-load-more').onclick=function(){displayLimit+=12;draw();};$('ad-drawer-close').onclick=closeDrawer;$('ad-drawer').querySelector('.ad-drawer-backdrop').onclick=closeDrawer;$('ad-drawer-content').onclick=function(e){var b=e.target.closest('[data-copy]');if(!b)return;navigator.clipboard.writeText(b.dataset.copy).then(function(){toast('Conversation starter copied');});};$('ad-digest').onchange=function(){var row={user_id:user.id,enabled:this.checked,updated_at:new Date().toISOString()};sb().from('agent_digest_preferences').upsert(row).select().single().then(function(r){if(r.error)throw r.error;digest=r.data;$('ad-digest-note').textContent=digest.enabled?'Next digest: Monday at 8:00 AM ET':'Weekly digest is off';}).catch(function(){toast('Digest preference could not be saved');});};bindList();bindImport();}
function load(){return Promise.all([sb().from('saved_properties').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).limit(1000),sb().from('agent_farm_properties').select('*').eq('user_id',user.id).order('updated_at',{ascending:false}).limit(1000),sb().from('property_update_events').select('*').eq('user_id',user.id).order('occurred_at',{ascending:false}).limit(2000),sb().from('agent_opportunity_actions').select('*').eq('user_id',user.id).order('updated_at',{ascending:false}).limit(2000),sb().from('agent_digest_preferences').select('*').eq('user_id',user.id).maybeSingle()]).then(function(r){for(var i=0;i<r.length;i++)if(r[i].error&&r[i].error.code!=='PGRST116')throw r[i].error;saved=r[0].data||[];farm=r[1].data||[];events=r[2].data||[];actions=r[3].data||[];digest=r[4].data||null;$('ad-digest').checked=digest?digest.enabled:true;$('ad-digest-note').textContent=$('ad-digest').checked?'Next digest: Monday at 8:00 AM ET':'Weekly digest is off';var newest=events[0]&&events[0].occurred_at;$('ad-refreshed').textContent=newest?'Latest evidence '+date(newest):'No source events yet';drawSaved();compute();});}
function init(){if(!window.supabase||!window.njptrAccessReady)return;window.njptrAccessReady.then(function(ctx){user=ctx.user;return load();}).then(function(){$('ad-gate').hidden=true;$('ad-app').hidden=false;bind();}).catch(function(e){console.error('Agent Desk:',e);$('ad-gate').hidden=false;});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
