(function(){
'use strict';
if(!window.NJPTRSupabaseRuntime)return;
var db;try{db=window.NJPTRSupabaseRuntime.createClient()}catch(_){return}
var user=null,application=null,rating=0,busy=false;
function q(s){return document.querySelector(s)}
function digits(v){return String(v||'').replace(/\D/g,'').slice(0,6)}
function wantedRating(){var n=Number(new URLSearchParams(location.search).get('rating'));return Number.isInteger(n)&&n>=1&&n<=5?n:0}
function status(message,error){var el=q('#review-status');if(!el)return;el.textContent=message||'';el.className='review-status'+(error?' error':'')}
// content-architecture: dynamic — the comment label, required state, and placeholder change from optional to required based on the user's live 1–3 vs 4–5 star selection.
function syncFeedbackPrompt(){var low=rating>=1&&rating<=3,prompt=q('#review-feedback-prompt'),label=q('#review-comment-label'),comment=q('#review-comment');if(prompt)prompt.hidden=!low;if(label)label.innerHTML=low?'What could we have done better? <span>Required</span>':'Anything you\'d like to add? <span>Optional</span>';if(comment){comment.required=low;comment.setAttribute('aria-required',low?'true':'false');comment.placeholder=low?'Please tell us what happened or what we could improve.':'Tell us what worked well or what we could improve.'}}
function paint(value){rating=Number(value)||0;document.querySelectorAll('[data-rating]').forEach(function(button){var n=Number(button.dataset.rating||0);button.classList.toggle('is-selected',n<=rating);button.setAttribute('aria-checked',n===rating?'true':'false')});var copy=q('#review-rating-copy');if(copy)copy.textContent=rating?rating+' star'+(rating===1?'':'s')+' selected':'';syncFeedbackPrompt()}
function showAuth(){q('#review-auth').hidden=false;q('#review-form').hidden=true;q('#review-success').hidden=true}
function showForm(){q('#review-auth').hidden=true;q('#review-form').hidden=false;q('#review-success').hidden=true}
function showSuccess(){q('#review-auth').hidden=true;q('#review-form').hidden=true;q('#review-success').hidden=false}
async function latestCompletedApplication(){var result=await db.from('anchor_applications').select('id,tax_year,status,generated_at').eq('user_id',user.id).eq('status','generated').order('generated_at',{ascending:false}).limit(1).maybeSingle();if(result.error)throw result.error;return result.data||null}
async function existingReview(){if(!application)return null;var result=await db.from('anchor_application_reviews').select('rating,review_comment,submitted_at,updated_at,withdrawn_at').eq('application_id',application.id).maybeSingle();if(result.error)throw result.error;return result.data&&!result.data.withdrawn_at?result.data:null}
// content-architecture: dynamic — this copy depends on authenticated ownership, completed-application state, prior-review state, and the email deep-link rating.
async function loadReview(){status('');application=await latestCompletedApplication();if(!application){showForm();q('#review-submit').disabled=true;paint(0);return status('We could not find a completed application on this account. Sign in with the same email you used when you completed the application.',true)}var saved=await existingReview();if(saved){paint(saved.rating);q('#review-comment').value=saved.review_comment||'';q('#review-submit').textContent='Update review';status('Your previous rating is shown below. You can update it anytime.')}else{paint(wantedRating());q('#review-submit').textContent='Submit review';status('')}showForm()}
async function sendCode(){var email=String(q('#review-email').value||'').trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email))return status('Enter the email address you used for your application.',true);var button=q('#review-send-code');button.disabled=true;status('Sending your secure sign-in code…');try{var result=await db.auth.signInWithOtp({email:email,options:{shouldCreateUser:false}});if(result.error)throw result.error;q('#review-code-wrap').hidden=false;status('Check your email for the 6-digit code.');q('#review-code').focus()}catch(_){status('We could not send a code to that address. Use the same email you used for your completed application.',true)}finally{button.disabled=false}}
async function verifyCode(){var email=String(q('#review-email').value||'').trim().toLowerCase(),token=digits(q('#review-code').value);if(token.length!==6)return status('Enter the 6-digit code from your email.',true);var button=q('#review-verify-code');button.disabled=true;status('Verifying…');try{var result=await db.auth.verifyOtp({email:email,token:token,type:'email'});if(result.error||!result.data||!result.data.user)throw(result.error||new Error('verify_failed'));user=result.data.user;await loadReview()}catch(_){status('That code could not be verified. Check it and try again.',true)}finally{button.disabled=false}}
async function recordReviewEvent(){if(!application)return;try{await db.rpc('record_my_anchor_funnel_event',{p_application_id:application.id,p_event_name:'application_review_saved'})}catch(_){}}
// content-architecture: dynamic — the validation message is shown only when the live rating is 1–3 and the required feedback field is empty, including the equivalent backend-enforced state.
async function submit(){if(busy||!application)return;if(rating<1||rating>5)return status('Choose a rating from 1 to 5 stars.',true);var comment=String(q('#review-comment').value||'').trim();if(rating<=3&&!comment){status('Please tell us what we could have done better before submitting a rating of 3 stars or below.',true);q('#review-comment').focus();return}busy=true;var button=q('#review-submit');button.disabled=true;status('Saving your review…');try{var result=await db.rpc('record_my_anchor_application_review_v1',{p_application_id:application.id,p_rating:rating,p_review_comment:comment||null});if(result.error)throw result.error;await recordReviewEvent();status('');showSuccess()}catch(error){var message=String(error&&error.message||'');if(message.indexOf('feedback_required_for_rating_3_or_below')>=0){status('Please tell us what we could have done better before submitting a rating of 3 stars or below.',true);q('#review-comment').focus()}else status('We could not save your review. Please try again.',true)}finally{busy=false;button.disabled=false}}
function bind(){q('#review-send-code').addEventListener('click',sendCode);q('#review-verify-code').addEventListener('click',verifyCode);q('#review-submit').addEventListener('click',submit);document.querySelectorAll('[data-rating]').forEach(function(button){button.addEventListener('click',function(){paint(button.dataset.rating);status('')})});q('#review-code').addEventListener('keydown',function(event){if(event.key==='Enter')verifyCode()});q('#review-email').addEventListener('keydown',function(event){if(event.key==='Enter')sendCode()})}
async function init(){bind();paint(wantedRating());try{var result=await db.auth.getUser();if(result.error)throw result.error;user=result.data&&result.data.user||null;if(!user)return showAuth();await loadReview()}catch(_){showAuth();status('Sign in to verify the completed application associated with your review.')}}
init();
})();
