(function(){
'use strict';
if(window.__WATCHDOG_BROADCAST_STUDIO_V3__)return;
window.__WATCHDOG_BROADCAST_STUDIO_V3__=true;
var $=function(id){return document.getElementById(id);};
var analyticsBusy=false,listBusy=false,renderTimer=null,lastFrameDoc='';
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function clean(v){return String(v==null?'':v).trim();}
function num(v){var n=Number(v);return Number.isFinite(n)?n:0;}
function pct(v){var n=num(v);if(Math.abs(n)<=1)n*=100;return n.toLocaleString(undefined,{minimumFractionDigits:n&&n<1?2:0,maximumFractionDigits:2})+'%';}
function date(v){if(!v)return'—';var d=new Date(v);return Number.isFinite(d.getTime())?d.toLocaleString():'—';}
function statusLabel(v){var s=clean(v).toLowerCase();return s?s.charAt(0).toUpperCase()+s.slice(1):'Draft';}
function setText(node,value){if(node&&node.textContent!==String(value))node.textContent=String(value);}
function addStyles(){if(document.querySelector('link[data-broadcast-v4]'))return;var l=document.createElement('link');l.rel='stylesheet';l.href='/property/css/broadcast-studio-v4.css';l.dataset.broadcastV4='1';document.head.appendChild(l);}
async function providerCall(action,body){var rt=window.NJPTRSupabaseRuntime;if(!rt||!rt.url||!rt.key||!rt.createClient)throw new Error('Watchdog connection unavailable');var s=await rt.createClient().auth.getSession(),session=s&&s.data&&s.data.session,token=session&&session.access_token;if(!token)throw new Error('Your Watchdog session has expired.');var controller=new AbortController(),timer=setTimeout(function(){controller.abort();},12000);try{var r=await fetch(rt.url+'/functions/v1/tmp-boldtrail-probe',{method:'POST',signal:controller.signal,headers:{apikey:rt.key,authorization:'Bearer '+token,'content-type':'application/json'},body:JSON.stringify(Object.assign({action:action},body||{}))}),d=await r.json().catch(function(){return{};});if(!r.ok)throw new Error(d.error||'Request failed');return d;}catch(err){if(err&&err.name==='AbortError')throw new Error('Kit took too long to respond. Watchdog released the page; try again.');throw err;}finally{clearTimeout(timer);}}
async function analyticsRpc(broadcastId){var rt=window.NJPTRSupabaseRuntime;if(!rt||!rt.createClient)throw new Error('Watchdog connection unavailable');var r=await rt.createClient().rpc('marketing_email_broadcast_analytics',{p_broadcast_id:broadcastId||null});if(r.error)throw new Error(r.error.message||'Analytics request failed');return r.data||{};}

function senderParts(){var raw=clean($('nl-default-sender')&&$('nl-default-sender').textContent);if(!raw||raw==='Set a sender')return{name:'Your sender',email:'sender@example.com'};var email=(raw.match(/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/)||[])[0]||'',name=raw.replace(email,'').replace(/[<>·|]/g,' ').trim();return{name:name||email||'Your sender',email:email||raw};}
function sanitize(html){var t=document.createElement('template');t.innerHTML=String(html||'');t.content.querySelectorAll('script,iframe,object,embed,form').forEach(function(n){n.remove();});t.content.querySelectorAll('*').forEach(function(el){Array.from(el.attributes).forEach(function(a){if(/^on/i.test(a.name)||/javascript\s*:/i.test(a.value))el.removeAttribute(a.name);});});return t.innerHTML;}
function frameDoc(html){var s=sanitize(html);if(!s.trim())return '<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font:16px Arial,sans-serif;color:#52606d;padding:38px;margin:0}div{border:1px dashed #d9e0e5;border-radius:14px;padding:32px;text-align:center}</style></head><body><div>Your broadcast preview will appear here as you type.</div></body></html>';if(/^\s*<!doctype|^\s*<html/i.test(s))return s;return '<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>html,body{margin:0;min-height:100%;background:#fff}img{max-width:100%;height:auto}</style></head><body>'+s+'</body></html>';}
function setPreviewMode(mode){var inbox=$('nl-mail-inbox-view'),open=$('nl-mail-open-view'),ti=$('nl-preview-tab-inbox'),to=$('nl-preview-tab-open');if(!inbox||!open)return;var opened=mode==='open';inbox.hidden=opened;open.hidden=!opened;ti.classList.toggle('active',!opened);to.classList.toggle('active',opened);ti.setAttribute('aria-selected',opened?'false':'true');to.setAttribute('aria-selected',opened?'true':'false');}
function updatePreview(){var subject=clean($('nl-subject')&&$('nl-subject').value)||'Your subject',pre=clean($('nl-preview')&&$('nl-preview').value)||'Preview text will appear here.',html=$('nl-content')&&$('nl-content').value||'',sp=senderParts();setText($('nl-client-inbox-subject'),subject);setText($('nl-client-inbox-preheader'),pre);setText($('nl-client-inbox-sender'),sp.name);setText($('nl-preview-subject'),subject);setText($('nl-preview-preheader'),pre);setText($('nl-client-open-sender'),sp.name);setText($('nl-client-open-email'),sp.email);setText($('nl-client-avatar'),(sp.name||sp.email||'W').trim().charAt(0).toUpperCase());var f=$('nl-email-preview-frame'),doc=frameDoc(html);if(f&&doc!==lastFrameDoc){lastFrameDoc=doc;f.srcdoc=doc;}}
function fullscreen(){var root=document.querySelector('.nl-client-preview-card')||$('nl-mail-client'),btn=$('nl-preview-fullscreen');if(!root)return;if(document.fullscreenElement){document.exitFullscreen&&document.exitFullscreen();return;}if(root.requestFullscreen){root.requestFullscreen().catch(function(){root.classList.toggle('nl-preview-expanded');});}else root.classList.toggle('nl-preview-expanded');if(btn)btn.blur();}

function statOf(r){return r&&r.stats&&typeof r.stats==='object'?r.stats:r&&r.provider_snapshot&&r.provider_snapshot.analytics||{};}
function renderBroadcasts(rows){var body=$('nl-broadcasts'),empty=$('nl-broadcasts-empty');if(!body)return;rows=Array.isArray(rows)?rows:[];body.dataset.v3='1';body.innerHTML=rows.map(function(r){var s=statOf(r),rec=num(s.recipients),opened=num(s.emails_opened),clicks=num(s.total_clicks),unsubs=num(s.unsubscribes),status=s.status||r.status||'draft';return '<tr data-v3-row="1"><td><div class="nl-bcast-subject"><b>'+esc(r.subject||'Untitled broadcast')+'</b><small>Kit #'+esc(r.external_broadcast_id||'—')+'</small></div></td><td><span class="nl-bcast-status '+esc(String(status).toLowerCase())+'">'+esc(statusLabel(status))+'</span></td><td>'+rec.toLocaleString()+'</td><td>'+opened.toLocaleString()+'</td><td>'+pct(s.open_rate)+'</td><td>'+clicks.toLocaleString()+'</td><td>'+pct(s.click_rate)+'</td><td>'+unsubs.toLocaleString()+'</td><td><small>'+esc(date(r.updated_at||r.send_at||r.created_at))+'</small></td><td><button type="button" class="nl-analytics-open" data-local-id="'+esc(r.id||'')+'" aria-label="Open analytics"><i class="fas fa-chart-column"></i><span>Analytics</span></button></td></tr>';}).join('');if(empty)empty.hidden=rows.length>0;}
function setProviderState(node,state,label){if(!node)return;node.dataset.state=state;setText(node,label);}
function updateProviderStrip(d){var crm=d&&d.crm&&d.crm.connection,kit=d&&d.provider;setProviderState($('nl-provider-crm-state'),crm&&crm.status==='active'?'live':'down',crm&&crm.status==='active'?'Live':'Not connected');var ks=kit&&kit.status==='connected'?'live':kit&&kit.status==='degraded'?'warn':'down';setProviderState($('nl-provider-kit-state'),ks,ks==='live'?'Live':ks==='warn'?'Needs attention':'Not connected');}
async function loadList(){if(listBusy)return;listBusy=true;try{var d=await providerCall('email.status');updateProviderStrip(d);try{var a=await analyticsRpc(null);renderBroadcasts(a.recent_broadcasts||d.recent_broadcasts||[]);}catch(_analyticsError){renderBroadcasts(d.recent_broadcasts||[]);}}catch(e){}finally{listBusy=false;}}
function scheduleListEnhance(){clearTimeout(renderTimer);renderTimer=setTimeout(function(){var b=$('nl-broadcasts');if(b&&b.children.length&&!(b.firstElementChild&&b.firstElementChild.hasAttribute('data-v3-row')))loadList();},80);}

function analyticsMeta(d){var s=d.stats||{},details=d.provider_details||{},parts=[];parts.push('<span><i class="fas fa-circle"></i> '+esc(statusLabel(s.status||d.broadcast&&d.broadcast.status))+'</span>');if(details.send_at||d.broadcast&&d.broadcast.send_at)parts.push('<span><i class="far fa-clock"></i> '+esc(date(details.send_at||d.broadcast.send_at))+'</span>');if(s.open_tracking_disabled)parts.push('<span class="warn"><i class="fas fa-eye-slash"></i> Open tracking disabled</span>');if(s.click_tracking_disabled)parts.push('<span class="warn"><i class="fas fa-link-slash"></i> Click tracking disabled</span>');if(s.progress!=null)parts.push('<span><i class="fas fa-bars-progress"></i> '+esc(pct(s.progress))+' delivery progress</span>');return parts.join('');}
function renderAnalytics(d){var s=d.stats||{},clicks=Array.isArray(d.clicks)?d.clicks:[];setText($('nl-stat-recipients'),num(s.recipients).toLocaleString());setText($('nl-stat-opened'),num(s.emails_opened).toLocaleString());setText($('nl-stat-open-rate'),pct(s.open_rate)+' open rate');setText($('nl-stat-clicks'),num(s.total_clicks).toLocaleString());setText($('nl-stat-click-rate'),pct(s.click_rate)+' click rate');setText($('nl-stat-unsubs'),num(s.unsubscribes).toLocaleString());setText($('nl-stat-unsub-rate'),pct(s.unsubscribe_rate)+' unsubscribe rate');$('nl-analytics-meta').innerHTML=analyticsMeta(d);var tb=$('nl-link-clicks'),em=$('nl-link-clicks-empty');tb.innerHTML=clicks.map(function(x){return '<tr><td><a href="'+esc(x.url||'#')+'" target="_blank" rel="noopener">'+esc(x.url||'Unknown link')+'</a></td><td>'+num(x.unique_clicks).toLocaleString()+'</td><td>'+pct(x.click_to_delivery_rate)+'</td><td>'+pct(x.click_to_open_rate)+'</td></tr>';}).join('');em.hidden=clicks.length>0;$('nl-analytics-loading').hidden=true;$('nl-analytics-content').hidden=false;$('nl-analytics-error').hidden=true;}
async function openAnalytics(button){if(analyticsBusy)return;var local=button.getAttribute('data-local-id'),dialog=$('nl-analytics-dialog');if(!local)return;analyticsBusy=true;$('nl-analytics-loading').hidden=false;$('nl-analytics-content').hidden=true;$('nl-analytics-error').hidden=true;setText($('nl-analytics-title'),(button.closest('tr').querySelector('.nl-bcast-subject b')||{}).textContent||'Broadcast analytics');if(dialog&&typeof dialog.showModal==='function')dialog.showModal();else if(dialog)dialog.setAttribute('open','');try{renderAnalytics(await analyticsRpc(local));}catch(e){$('nl-analytics-loading').hidden=true;$('nl-analytics-error').hidden=false;setText($('nl-analytics-error'),e.message||'Analytics could not be loaded.');}finally{analyticsBusy=false;}}
function closeAnalytics(){var d=$('nl-analytics-dialog');if(d&&d.open&&d.close)d.close();else if(d)d.removeAttribute('open');}

var samples={
 basic:{kicker:'A QUICK NOTE',headline:'A quick update from your local real estate resource',intro:'A simple, personal email for announcements, check-ins and short client updates.',story1:'What I am watching this week',summary1:'Keep the message direct, useful and easy to scan. This format works well when the relationship matters more than heavy design.',story2:'One helpful thing to know',summary2:'Add one supporting item, link or reminder without making the email feel busy.',cta:'Have a question?',ctacopy:'Reply anytime or take the next step when you are ready.',footer:'A personal update, delivered simply.'},
 deluxe:{kicker:'SOUTH JERSEY MARKET BRIEF',headline:'What changed in the market this week',intro:'A polished update with one feature story and a few supporting items for clients who want the highlights quickly.',story1:'The number buyers and sellers should watch',summary1:'Lead with the most useful market point, then explain why it matters in plain language.',story2:'Three local signals worth knowing',summary2:'Use supporting sections for inventory, rates, pricing or community news.',cta:'Want a property-specific look?',ctacopy:'Use the call to action for a report, consultation or property search.',footer:'Useful local context without the clutter.'},
 premium:{kicker:'THE PROPERTY BRIEF',headline:'Four things worth knowing right now',intro:'A publication-style briefing built for premium market intelligence, research and editorial content.',story1:'The signal that deserves your attention',summary1:'Open with the strongest insight and give readers enough context to understand why it matters.',story2:'New data changes the picture',summary2:'Follow with a concise second story that supports the broader narrative.',cta:'Turn the data into an advantage',ctacopy:'Finish with one clear next action and a high-confidence reason to take it.',footer:'Property intelligence, presented with purpose.'}
};
function templateTier(card){return (card&&card.dataset&&card.dataset.tier)||'premium';}
function previewMarkup(tier){if(tier==='basic')return '<div class="nl-sample-sheet basic"><div class="s-kicker">PERSONAL UPDATE</div><div class="s-title">A quick note from your local real estate resource</div><div class="s-copy">Hi there,<br><br>Here are two things I thought were worth sharing this week.</div><div class="s-line"></div><div class="s-line"></div><div class="s-line short"></div><span class="s-btn">Read the update</span><div class="s-sign">Talk soon,<br>Your Name</div></div>';if(tier==='deluxe')return '<div class="nl-sample-sheet deluxe"><div class="s-top"><div class="s-brand">MARKET BRIEF</div><div class="s-title">What changed in South Jersey this week</div><div class="s-copy">A clean market update with the most useful numbers first.</div></div><div class="s-hero"></div><div class="s-body"><div class="s-story"><b>Inventory moved again</b><span>What buyers and sellers should know.</span></div><div class="s-story"><b>Rates, pricing and demand</b><span>Three signals in one quick read.</span></div></div></div>';return '<div class="nl-sample-sheet premium"><div class="s-mast"><div class="s-brand">PROPERTY INTELLIGENCE</div><div class="s-title">Four things worth knowing right now.</div><div class="s-copy">Data, context and local insight in one premium brief.</div></div><div class="s-feature"><small>FEATURED SIGNAL</small><b>The number that deserves your attention</b><span>A concise explanation of what changed and why it matters.</span></div><div class="s-briefs"><div class="s-brief"><b>New data</b><span>A supporting intelligence note.</span></div><div class="s-brief"><b>Local context</b><span>Another useful story at a glance.</span></div></div></div>';}
function installTemplatePreviews(){document.querySelectorAll('.nl-template-card').forEach(function(card){var tier=templateTier(card),thumb=card.querySelector('.nl-template-thumb');if(thumb)thumb.innerHTML=previewMarkup(tier);var copy=card.querySelector('.nl-template-copy');if(copy){var title=copy.querySelector('b'),small=copy.querySelector('small');if(title)title.textContent=tier==='basic'?'Simple Update':tier==='deluxe'?'Market Brief':'Editorial Intelligence';if(small)small.textContent=tier==='basic'?'Clean and personal. Best for quick sends.':tier==='deluxe'?'Designed, modern and easy to scan.':'Premium editorial layout for flagship broadcasts.';}});}
function fillSample(tier){var s=samples[tier]||samples.premium,put=function(id,v){var n=$(id);if(n)n.value=v||'';};put('nl-build-kicker',s.kicker);put('nl-build-headline',s.headline);put('nl-build-intro',s.intro);put('nl-story-1-title',s.story1);put('nl-story-1-summary',s.summary1);put('nl-story-1-cta','Read more');put('nl-story-2-title',s.story2);put('nl-story-2-summary',s.summary2);put('nl-story-3-title','');put('nl-story-3-summary','');put('nl-story-4-title','');put('nl-story-4-summary','');put('nl-build-cta-title',s.cta);put('nl-build-cta-copy',s.ctacopy);put('nl-build-cta-button','Learn more');put('nl-build-footer',s.footer);if(!$('nl-subject').value.trim())$('nl-subject').value=s.headline;if(!$('nl-preview').value.trim())$('nl-preview').value=s.intro.slice(0,220);var builder=$('nl-template-builder');if(builder)builder.open=true;var brand=$('nl-brand-panel');if(brand)brand.open=false;setTimeout(function(){var build=$('nl-build-html');if(build)build.click();var target=$('nl-template-builder');if(target)target.scrollIntoView({behavior:'smooth',block:'start'});},60);}
function tuckAdvancedHtml(){var ta=$('nl-content');if(!ta||ta.closest('.nl-advanced-html'))return;var label=ta.closest('label');if(!label||!label.parentNode)return;var d=document.createElement('details');d.className='nl-advanced-html';d.innerHTML='<summary>Advanced HTML</summary><div></div>';label.parentNode.insertBefore(d,label);d.querySelector('div').appendChild(label);}
function setupSimpleUx(){var ws=$('nl-workspace');if(ws)ws.classList.add('nl-newbie-polish');var brand=$('nl-brand-panel'),builder=$('nl-template-builder');if(brand)brand.open=false;if(builder)builder.open=false;var nav=document.querySelector('.nl-jump-nav');if(nav){var links=nav.querySelectorAll('a');if(links[0])setText(links[0].querySelector('span'),'Templates');if(links[1])setText(links[1].querySelector('span'),'Create');if(links[4])setText(links[4].querySelector('span'),'Broadcasts');}var head=document.querySelector('.nl-brand-head h2'),p=document.querySelector('.nl-brand-head p');setText(head,'Choose a starting point');setText(p,'Pick a look first. You can change colors, branding and content after you choose.');installTemplatePreviews();tuckAdvancedHtml();document.querySelectorAll('.nl-provider-brand').forEach(function(n){n.setAttribute('role','button');n.setAttribute('tabindex','0');n.title='Manage connection';});}
function openConnections(){var p=$('nl-connections-panel');if(!p)return;p.open=true;p.scrollIntoView({behavior:'smooth',block:'start'});}
function handleTemplatePick(card){if(!card)return;fillSample(templateTier(card));}

function click(e){var b=e.target.closest('button');if(b){if(b.id==='nl-preview-inbox-row'||b.id==='nl-preview-tab-open'){e.preventDefault();setPreviewMode('open');return;}if(b.id==='nl-preview-back'||b.id==='nl-preview-tab-inbox'){e.preventDefault();setPreviewMode('inbox');return;}if(b.id==='nl-preview-fullscreen'){e.preventDefault();fullscreen();return;}if(b.classList.contains('nl-analytics-open')){e.preventDefault();openAnalytics(b);return;}if(b.id==='nl-analytics-close'){e.preventDefault();closeAnalytics();return;}if(b.id==='nl-analytics-refresh'){e.preventDefault();loadList();return;}if(b.classList.contains('nl-template-card')){setTimeout(function(){handleTemplatePick(b);},0);return;}}var provider=e.target.closest('.nl-provider-brand');if(provider){e.preventDefault();openConnections();}}
function key(e){if((e.key==='Enter'||e.key===' ')&&e.target.classList&&e.target.classList.contains('nl-provider-brand')){e.preventDefault();openConnections();}}
function boot(){addStyles();setupSimpleUx();['nl-subject','nl-preview','nl-content','nl-default-sender'].forEach(function(id){var el=$(id);if(el){el.addEventListener('input',updatePreview);el.addEventListener('change',updatePreview);}});document.addEventListener('click',click);document.addEventListener('keydown',key);var tbody=$('nl-broadcasts');if(tbody)new MutationObserver(scheduleListEnhance).observe(tbody,{childList:true});document.addEventListener('fullscreenchange',function(){var btn=$('nl-preview-fullscreen');if(btn)btn.innerHTML=document.fullscreenElement?'<i class="fas fa-compress"></i> Exit full screen':'<i class="fas fa-expand"></i> Full screen';});updatePreview();setTimeout(loadList,450);setTimeout(loadList,1400);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
