(function () {
  'use strict';
  var catalog = null, selected = [], views = [], activeView = '';
  var $ = function (id) { return document.getElementById(id); };
  var SB_URL = 'https://uvkvaxljhhngydvlrzom.supabase.co', SB_KEY = 'sb_publishable_MYX59qCbK3d-21zDfJqkNw_fvmfnexa', sb = null;
  function esc(v) { return String(v == null ? '' : v).replace(/[&<>\"]/g, function (c) { return { '&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;' }[c]; }); }
  function label(v) { return String(v || '').replace(/_/g, ' ').replace(/\b\w/g, function (c) { return c.toUpperCase(); }); }
  function allowed(m, tier, prof) { if (tier === 'standard') return m.tier === 'standard'; if (tier === 'pro') return m.tier === 'standard' || (m.tier === 'pro' && (!prof || m.professions.indexOf(prof) >= 0)); return true; }
  function client() { if (!sb && window.supabase) sb = window.supabase.createClient(SB_URL, SB_KEY, { auth:{ persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,flowType:'pkce',storageKey:'sb-uvkvaxljhhngydvlrzom-auth-token' } }); return sb; }
  function renderStats() { var s = catalog.summary; $('dc-total').textContent = s.total; $('dc-percent').textContent = s.percent_of_goal + '%'; $('dc-progress-bar').style.width = Math.min(100, s.percent_of_goal) + '%'; $('dc-stats').innerHTML = [['Public source',s.public_source],['Watchdog derived',s.proprietary_derived],['Standard',s.by_tier.standard],['Pro',s.by_tier.pro],['Pro+',s.by_tier.pro_plus]].map(function (x) { return '<div class="dc-stat"><b>'+x[1]+'</b><span>'+x[0]+'</span></div>'; }).join(''); }
  function saveLocal() { localStorage.setItem('watchdog:data-center:fields', JSON.stringify(selected)); }
  function renderSelected() { var map={}; catalog.markers.forEach(function(m){map[m.id]=m;}); selected=selected.filter(function(id){return map[id];}); $('dc-selected-count').textContent=selected.length+' field'+(selected.length===1?'':'s')+' selected'; $('dc-chips').innerHTML='<div class="dc-chips">'+selected.map(function(id){return'<button data-remove="'+esc(id)+'" title="Remove">'+esc(map[id].label)+' ×</button>';}).join('')+'</div>'; }
  function filters() { return { profession:$('dc-prof').value, tier:$('dc-tier').value, category:$('dc-category').value, origin:$('dc-origin').value, query:$('dc-search').value.trim() }; }
  function render() { var f=filters(),q=f.query.toLowerCase(); var rows=catalog.markers.filter(function(m){return allowed(m,f.tier,f.profession)&&(!f.category||m.category===f.category)&&(!f.origin||m.origin===f.origin)&&(!f.profession||m.professions.indexOf(f.profession)>=0)&&(!q||(m.label+' '+m.description+' '+m.id+' '+m.category+' '+m.professions.join(' ')+' '+(m.professional_reason||'')).toLowerCase().indexOf(q)>=0);}); $('dc-rows').innerHTML=rows.length?rows.map(function(m){return'<tr><td class="dc-check"><input type="checkbox" data-marker="'+esc(m.id)+'" '+(selected.indexOf(m.id)>=0?'checked':'')+'></td><td><a class="dm" title="'+esc(m.professional_reason||m.description||'')+'" data-marker-id="'+esc(m.id)+'" href="/property/marker.html?id='+encodeURIComponent(m.id)+'"><strong>'+esc(m.label)+'</strong></a><small>'+esc(m.id)+'</small></td><td>'+esc(label(m.category))+'</td><td>'+esc(label(m.scope))+'</td><td><span class="dc-pill '+esc(m.tier)+'">'+esc(m.tier==='pro_plus'?'PRO+':m.tier.toUpperCase())+'</span></td><td><span class="dc-pill '+esc(m.origin)+'">'+esc(m.origin==='public'?'Public':'Watchdog derived')+'</span></td><td class="dc-prof-tags">'+m.professions.map(function(p){return'<span>'+esc((catalog.professions.find(function(x){return x.id===p;})||{label:p}).label)+'</span>';}).join('')+'</td></tr>';}).join(''):'<tr><td class="dc-empty" colspan="7">No live markers match these filters.</td></tr>'; renderSelected(); }
  function ensureViewControls() { if ($('dc-saved-views')) return; if(!document.getElementById('dc-saas-css')){var css=document.createElement('link');css.id='dc-saas-css';css.rel='stylesheet';css.href='/property/css/data-center-saved.css?v=20260806a';document.head.appendChild(css);} var selectedBox=document.querySelector('.dc-selected'); if(!selectedBox)return; var bar=document.createElement('div');bar.className='dc-view-actions';bar.innerHTML='<select id="dc-saved-views" aria-label="Saved Data Center views"><option value="">Saved views</option></select><button id="dc-save-view" type="button"><i class="fas fa-bookmark"></i> Save view</button><button id="dc-delete-view" type="button" title="Delete selected view" hidden><i class="fas fa-trash"></i></button>';selectedBox.insertBefore(bar,$('dc-chips'));$('dc-save-view').addEventListener('click',saveView);$('dc-saved-views').addEventListener('change',applyView);$('dc-delete-view').addEventListener('click',deleteView); }
  function session() { var c=client(); return c?c.auth.getSession().then(function(r){return r.data&&r.data.session;}):Promise.resolve(null); }
  function loadViews() { ensureViewControls(); return session().then(function(s){if(!s)return[];return client().from('saved_data_center_views').select('id,name,scope,marker_ids,filters,sort_config,updated_at').order('updated_at',{ascending:false}).then(function(r){if(r.error)throw r.error;views=r.data||[];paintViews();return views;});}).catch(function(){return[];}); }
  function paintViews() { var select=$('dc-saved-views'); if(!select)return;select.innerHTML='<option value="">Saved views</option>'+views.map(function(v){return'<option value="'+esc(v.id)+'"'+(v.id===activeView?' selected':'')+'>'+esc(v.name)+'</option>';}).join('');$('dc-delete-view').hidden=!activeView; }
  function saveView() { session().then(function(s){if(!s){alert('Sign in to save Data Center views across devices.');return;}var name=window.prompt('Name this Data Center view:');if(!name||!name.trim())return;return client().from('saved_data_center_views').insert({name:name.trim().slice(0,120),scope:'property',marker_ids:selected,filters:filters()}).select('id,name,scope,marker_ids,filters,sort_config,updated_at').single().then(function(r){if(r.error)throw r.error;views.unshift(r.data);activeView=r.data.id;paintViews();});}).catch(function(e){alert('View could not be saved: '+e.message);}); }
  function applyView(e) { activeView=e.target.value;$('dc-delete-view').hidden=!activeView;if(!activeView)return;var v=views.find(function(x){return x.id===activeView;});if(!v)return;selected=Array.isArray(v.marker_ids)?v.marker_ids:[];var f=v.filters||{};$('dc-prof').value=f.profession||'';$('dc-tier').value=f.tier||'pro_plus';$('dc-category').value=f.category||'';$('dc-origin').value=f.origin||'';$('dc-search').value=f.query||'';saveLocal();render(); }
  function deleteView() { if(!activeView||!window.confirm('Delete this saved Data Center view?'))return;client().from('saved_data_center_views').delete().eq('id',activeView).then(function(r){if(r.error)throw r.error;views=views.filter(function(v){return v.id!==activeView;});activeView='';paintViews();}).catch(function(e){alert('View could not be deleted: '+e.message);}); }
  function init(j) { catalog=j;var vp=document.documentElement.dataset.viewPlan;if(vp)$('dc-tier').value=vp==='developer'?'pro_plus':vp;try{selected=JSON.parse(localStorage.getItem('watchdog:data-center:fields'))||[];}catch(e){selected=[];}j.professions.forEach(function(p){$('dc-prof').insertAdjacentHTML('beforeend','<option value="'+esc(p.id)+'">'+esc(p.label)+'</option>');});Array.from(new Set(j.markers.map(function(m){return m.category;}))).sort().forEach(function(c){$('dc-category').insertAdjacentHTML('beforeend','<option value="'+esc(c)+'">'+esc(label(c))+'</option>');});renderStats();render();loadViews(); }
  ['dc-search','dc-prof','dc-tier','dc-category','dc-origin'].forEach(function(id){$(id).addEventListener(id==='dc-search'?'input':'change',render);});
  $('dc-rows').addEventListener('change',function(e){var id=e.target.dataset.marker;if(!id)return;if(e.target.checked&&selected.indexOf(id)<0)selected.push(id);if(!e.target.checked)selected=selected.filter(function(x){return x!==id;});saveLocal();renderSelected();});
  $('dc-chips').addEventListener('click',function(e){var b=e.target.closest('[data-remove]');if(!b)return;selected=selected.filter(function(x){return x!==b.dataset.remove;});saveLocal();render();});
  $('dc-clear').addEventListener('click',function(){selected=[];saveLocal();render();});
  fetch('/property/data/marker-registry.json?v=20260807c').then(function(r){if(!r.ok)throw Error(r.status);return r.json();}).then(init).catch(function(e){$('dc-rows').innerHTML='<tr><td class="dc-empty" colspan="7">Marker registry could not load.</td></tr>';console.error(e);});
})();
