(function () {
  'use strict';
  var catalog = null, selected = [], views = [], activeView = '', resultRows = [];
  var $ = function (id) { return document.getElementById(id); };
  var SB_URL = 'https://uvkvaxljhhngydvlrzom.supabase.co', SB_KEY = 'sb_publishable_MYX59qCbK3d-21zDfJqkNw_fvmfnexa', sb = null;
  function esc(v) { return String(v == null ? '' : v).replace(/[&<>\"]/g, function (c) { return { '&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;' }[c]; }); }
  function label(v) { return String(v || '').replace(/_/g, ' ').replace(/\b\w/g, function (c) { return c.toUpperCase(); }); }
  function allowed(m, tier, prof) { if (tier === 'standard') return m.tier === 'standard'; if (tier === 'pro') return m.tier === 'standard' || (m.tier === 'pro' && (!prof || m.professions.indexOf(prof) >= 0)); return true; }
  function client() { if (!sb && window.supabase) sb = window.supabase.createClient(SB_URL, SB_KEY, { auth:{ persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,flowType:'pkce',storageKey:'sb-uvkvaxljhhngydvlrzom-auth-token' } }); return sb; }
  window.WatchdogDataCenterClient = client;
  function renderStats() { var s = catalog.summary; $('dc-total').textContent = s.total; $('dc-percent').textContent = s.percent_of_goal + '%'; $('dc-progress-bar').style.width = Math.min(100, s.percent_of_goal) + '%'; $('dc-stats').innerHTML = [['Public source',s.public_source],['Watchdog derived',s.proprietary_derived],['Standard',s.by_tier.standard],['Pro',s.by_tier.pro],['Pro+',s.by_tier.pro_plus]].map(function (x) { return '<div class="dc-stat"><b>'+x[1]+'</b><span>'+x[0]+'</span></div>'; }).join(''); }
  function saveLocal() { localStorage.setItem('watchdog:data-center:fields', JSON.stringify(selected)); }
  function renderSelected() { var map={}; catalog.markers.forEach(function(m){map[m.id]=m;}); selected=selected.filter(function(id){return map[id];}); $('dc-selected-count').textContent=selected.length+' field'+(selected.length===1?'':'s')+' selected'; $('dc-chips').innerHTML='<div class="dc-chips">'+selected.map(function(id){return'<button data-remove="'+esc(id)+'" title="Remove">'+esc(map[id].label)+' ×</button>';}).join('')+'</div>'; }
  function filters() { return { profession:$('dc-prof').value, tier:$('dc-tier').value, category:$('dc-category').value, origin:$('dc-origin').value, query:$('dc-search').value.trim() }; }
  function render() { var f=filters(),q=f.query.toLowerCase(); var rows=catalog.markers.filter(function(m){return allowed(m,f.tier,f.profession)&&(!f.category||m.category===f.category)&&(!f.origin||m.origin===f.origin)&&(!f.profession||m.professions.indexOf(f.profession)>=0)&&(!q||(m.label+' '+m.description+' '+m.id+' '+m.category+' '+m.professions.join(' ')+' '+(m.professional_reason||'')).toLowerCase().indexOf(q)>=0);}); $('dc-rows').innerHTML=rows.length?rows.map(function(m){return'<tr><td class="dc-check"><input type="checkbox" data-marker="'+esc(m.id)+'" '+(selected.indexOf(m.id)>=0?'checked':'')+'></td><td><a class="dm" title="'+esc(m.professional_reason||m.description||'')+'" data-marker-id="'+esc(m.id)+'" href="/property/marker?id='+encodeURIComponent(m.id)+'"><strong>'+esc(m.label)+'</strong></a><small>'+esc(m.id)+'</small></td><td>'+esc(label(m.category))+'</td><td>'+esc(label(m.scope))+'</td><td><span class="dc-pill '+esc(m.tier)+'">'+esc(m.tier==='pro_plus'?'PRO+':m.tier.toUpperCase())+'</span></td><td><span class="dc-pill '+esc(m.origin)+'">'+esc(m.origin==='public'?'Public':'Watchdog derived')+'</span></td><td class="dc-prof-tags">'+m.professions.map(function(p){return'<span>'+esc((catalog.professions.find(function(x){return x.id===p;})||{label:p}).label)+'</span>';}).join('')+'</td></tr>';}).join(''):'<tr><td class="dc-empty" colspan="7">No live markers match these filters.</td></tr>'; renderSelected(); }
  function ensureViewControls() { if ($('dc-saved-views')) return; if(!document.getElementById('dc-saas-css')){var css=document.createElement('link');css.id='dc-saas-css';css.rel='stylesheet';css.href='/property/css/data-center-saved.css';document.head.appendChild(css);} var selectedBox=document.querySelector('.dc-selected'); if(!selectedBox)return; var bar=document.createElement('div');bar.className='dc-view-actions';bar.innerHTML='<select id="dc-saved-views" aria-label="Saved Data Center views"><option value="">Saved views</option></select><button id="dc-save-view" type="button"><i class="fas fa-bookmark"></i> Save view</button><button id="dc-delete-view" type="button" title="Delete selected view" hidden><i class="fas fa-trash"></i></button>';selectedBox.insertBefore(bar,$('dc-chips'));$('dc-save-view').addEventListener('click',saveView);$('dc-saved-views').addEventListener('change',applyView);$('dc-delete-view').addEventListener('click',deleteView); }
  function ensureResultBuilder(){if($('dc-build'))return;var host=document.querySelector('.dc-selected'),box=document.createElement('section');box.className='dc-result-builder';box.innerHTML='<div class="dc-result-controls"><label>Scope<select id="dc-scope"><option value="property">Property rows</option><option value="town">Town summary</option><option value="county">County summary</option></select></label><button id="dc-build" type="button">Build sheet</button><button id="dc-export" type="button" disabled>Export CSV</button><button id="dc-schedule" type="button">Schedule</button></div><p id="dc-result-note">Select fields, then build a governed provider-backed result sheet. Unsupported fields are identified, never invented.</p><div id="dc-results" class="dc-results" hidden></div>';host.insertAdjacentElement('afterend',box);$('dc-build').onclick=buildSheet;$('dc-export').onclick=exportSheet;$('dc-schedule').onclick=scheduleDelivery;}
  var providers={'property.address':'address','property.municipality':'town','property.county':'county','property.block':'block','property.lot':'lot','property.pams_pin':'pams_pin','property.assessed_value':'assessed','property.assessed':'assessed','property.annual_tax':'last_year_tax','property.market_value':'watchdog_value','watchdog.market_value_estimate':'watchdog_value','watchdog.effective_tax_rate':'effective_rate','tax.effective_rate':'effective_rate'};
  function value(row,id){if(row&&row.__markers&&Object.prototype.hasOwnProperty.call(row.__markers,id)){var resolved=row.__markers[id];return resolved==null||resolved===''?'Not available':resolved;}var k=providers[id];if(!k)return 'Not connected';var v=row[k];return v==null||v===''?'Not available':v;}
  function markerById(id){return catalog&&catalog.markers?catalog.markers.find(function(m){return m.id===id;}):null;}
  function aggregate(rows,scope){var grouped={};rows.forEach(function(r){var key=scope==='town'?(r.town||'Unknown town'):(r.county||'Unknown county');(grouped[key]||(grouped[key]=[])).push(r);});return Object.keys(grouped).sort().map(function(k){var rs=grouped[k],out={address:k,town:k,county:k,pams_pin:rs.length+' account properties',__markers:{}};['assessed','last_year_tax','watchdog_value'].forEach(function(f){var nums=rs.map(function(r){return Number(r[f]);}).filter(Number.isFinite);out[f]=nums.length?nums.reduce(function(a,b){return a+b;},0):null;});var rates=rs.map(function(r){return Number(r.effective_rate);}).filter(Number.isFinite);out.effective_rate=rates.length?rates.reduce(function(a,b){return a+b;},0)/rates.length:null;selected.forEach(function(id){var m=markerById(id),compatible=scope==='town'&&m&&(m.scope==='municipality'||m.scope==='town')||scope==='county'&&m&&m.scope==='county';if(!compatible)return;for(var i=0;i<rs.length;i++){if(rs[i].__markers&&Object.prototype.hasOwnProperty.call(rs[i].__markers,id)&&rs[i].__markers[id]!=null){out.__markers[id]=rs[i].__markers[id];break;}}});return out;});}
  function chunksOf(items,size){var out=[];for(var i=0;i<items.length;i+=size)out.push(items.slice(i,i+size));return out;}
  function invokeWorkbench(name,batch,ids){return client().functions.invoke(name,{body:{pams_pins:batch,marker_ids:ids}}).then(function(r){if(r.error)throw r.error;return r.data||{};});}
  function hydrateRows(rows){
    var pins=rows.map(function(r){return r.pams_pin;}).filter(Boolean);if(!pins.length)return Promise.resolve(rows);
    var pinChunks=chunksOf(pins,500),allFieldChunks=chunksOf(selected,500),derivedIds=selected.filter(function(id){var m=markerById(id);return m&&m.origin==='watchdog-derived';}),derivedFieldChunks=chunksOf(derivedIds,250),calls=[];
    pinChunks.forEach(function(batch){
      allFieldChunks.forEach(function(ids){calls.push(invokeWorkbench('workbench-hydrate',batch,ids).then(function(data){return{kind:'base',data:data};}));});
      derivedFieldChunks.forEach(function(ids){calls.push(invokeWorkbench('workbench-derived',batch,ids).then(function(data){return{kind:'derived',data:data};}));});
    });
    return Promise.all(calls).then(function(parts){
      var records={},markers={},meta={};
      parts.sort(function(a,b){return a.kind==='base'&&b.kind==='derived'?-1:a.kind==='derived'&&b.kind==='base'?1:0;});
      parts.forEach(function(part){var data=part.data||{};(data.records||[]).forEach(function(r){records[String(r.pams_pin)]=Object.assign(records[String(r.pams_pin)]||{},r);});Object.keys(data.markers||{}).forEach(function(pin){markers[pin]=Object.assign(markers[pin]||{},data.markers[pin]);});Object.keys(data.meta||{}).forEach(function(pin){meta[pin]=Object.assign(meta[pin]||{},data.meta[pin]);});});
      return rows.map(function(r){var pin=String(r.pams_pin||''),live=records[pin]||{};return Object.assign({},r,live,{__markers:markers[pin]||{},__meta:meta[pin]||{}});});
    });
  }
  function buildSheet(){if(!selected.length){alert('Select at least one field first.');return;}$('dc-result-note').textContent='Resolving selected fields through live governed providers…';session().then(function(s){if(!s)throw Error('Sign in required');return client().from('saved_properties').select('pams_pin,address,town,county,block,lot,assessed,last_year_tax,effective_rate,watchdog_value').order('address');}).then(function(r){if(r.error)throw r.error;return hydrateRows(r.data||[]);}).then(function(rows){var scope=$('dc-scope').value;resultRows=scope==='property'?rows:aggregate(rows,scope);var labels={};catalog.markers.forEach(function(m){labels[m.id]=m.label;});$('dc-results').hidden=false;$('dc-results').innerHTML='<table><thead><tr>'+selected.map(function(id){return'<th>'+esc(labels[id]||id)+'</th>';}).join('')+'</tr></thead><tbody>'+resultRows.map(function(row){return'<tr>'+selected.map(function(id){return'<td>'+esc(value(row,id))+'</td>';}).join('')+'</tr>';}).join('')+'</tbody></table>';$('dc-export').disabled=!resultRows.length;$('dc-result-note').textContent=resultRows.length+' governed '+scope+' row'+(resultRows.length===1?'':'s')+'. Live fields are resolved by the production Workbench provider contract; missing source values remain explicitly blank.';}).catch(function(e){$('dc-result-note').textContent='Sheet could not be built: '+e.message;});}
  function csvCell(v){return '"'+String(v==null?'':v).replace(/"/g,'""')+'"';}function exportSheet(){if(!resultRows.length)return;var labels={};catalog.markers.forEach(function(m){labels[m.id]=m.label;});var csv=[selected.map(function(id){return csvCell(labels[id]||id);}).join(',')].concat(resultRows.map(function(r){return selected.map(function(id){return csvCell(value(r,id));}).join(',');})).join('\r\n');var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='watchdog-data-center-'+new Date().toISOString().slice(0,10)+'.csv';a.click();setTimeout(function(){URL.revokeObjectURL(a.href);},1000);}
  function scheduleDelivery(){if(!activeView){alert('Save this column set before scheduling delivery.');return;}var cadence=window.prompt('Delivery cadence: weekly or monthly','weekly');if(['weekly','monthly'].indexOf(String(cadence).toLowerCase())<0)return;var v=views.find(function(x){return x.id===activeView;});client().from('data_center_delivery_jobs').insert({view_id:activeView,name:(v&&v.name||'Data Center')+' delivery',scope:$('dc-scope').value,format:'csv',cadence:String(cadence).toLowerCase(),status:'scheduled',next_run_at:new Date().toISOString()}).then(function(r){if(r.error)throw r.error;alert('Scheduled. Watchdog will prepare the next delivery automatically.');}).catch(function(e){alert('Delivery could not be scheduled: '+e.message);});}
  function session() { var c=client(); return c?c.auth.getSession().then(function(r){return r.data&&r.data.session;}):Promise.resolve(null); }
  function loadViews() { ensureViewControls(); return session().then(function(s){if(!s)return[];return client().from('saved_data_center_views').select('id,name,scope,marker_ids,filters,sort_config,updated_at').order('updated_at',{ascending:false}).then(function(r){if(r.error)throw r.error;views=r.data||[];paintViews();return views;});}).catch(function(){return[];}); }
  function paintViews() { var select=$('dc-saved-views'); if(!select)return;select.innerHTML='<option value="">Saved views</option>'+views.map(function(v){return'<option value="'+esc(v.id)+'"'+(v.id===activeView?' selected':'')+'>'+esc(v.name)+'</option>';}).join('');$('dc-delete-view').hidden=!activeView; }
  function saveView() { session().then(function(s){if(!s){alert('Sign in to save Data Center views across devices.');return;}var name=window.prompt('Name this Data Center view:');if(!name||!name.trim())return;return client().from('saved_data_center_views').insert({name:name.trim().slice(0,120),scope:'property',marker_ids:selected,filters:filters()}).select('id,name,scope,marker_ids,filters,sort_config,updated_at').single().then(function(r){if(r.error)throw r.error;views.unshift(r.data);activeView=r.data.id;paintViews();});}).catch(function(e){alert('View could not be saved: '+e.message;}); }
  function applyView(e) { activeView=e.target.value;$('dc-delete-view').hidden=!activeView;if(!activeView)return;var v=views.find(function(x){return x.id===activeView;});if(!v)return;selected=Array.isArray(v.marker_ids)?v.marker_ids:[];var f=v.filters||{};$('dc-prof').value=f.profession||'';$('dc-tier').value=f.tier||'pro_plus';$('dc-category').value=f.category||'';$('dc-origin').value=f.origin||'';$('dc-search').value=f.query||'';saveLocal();render(); }
  function deleteView() { if(!activeView||!window.confirm('Delete this saved Data Center view?'))return;client().from('saved_data_center_views').delete().eq('id',activeView).then(function(r){if(r.error)throw r.error;views=views.filter(function(v){return v.id!==activeView;});activeView='';paintViews();}).catch(function(e){alert('View could not be deleted: '+e.message;}); }
  function init(j) { catalog=j;var vp=document.documentElement.dataset.viewPlan;if(vp)$('dc-tier').value=vp==='developer'?'pro_plus':vp;try{selected=JSON.parse(localStorage.getItem('watchdog:data-center:fields'))||[];}catch(e){selected=[];}j.professions.forEach(function(p){$('dc-prof').insertAdjacentHTML('beforeend','<option value="'+esc(p.id)+'">'+esc(p.label)+'</option>');});Array.from(new Set(j.markers.map(function(m){return m.category;}))).sort().forEach(function(c){$('dc-category').insertAdjacentHTML('beforeend','<option value="'+esc(c)+'">'+esc(label(c))+'</option>');});renderStats();render();ensureResultBuilder();loadViews(); }
  ['dc-search','dc-prof','dc-tier','dc-category','dc-origin'].forEach(function(id){$(id).addEventListener(id==='dc-search'?'input':'change',render);});
  $('dc-rows').addEventListener('change',function(e){var id=e.target.dataset.marker;if(!id)return;if(e.target.checked&&selected.indexOf(id)<0)selected.push(id);if(!e.target.checked)selected=selected.filter(function(x){return x!==id;});saveLocal();renderSelected();});
  $('dc-chips').addEventListener('click',function(e){var b=e.target.closest('[data-remove]');if(!b)return;selected=selected.filter(function(x){return x!==b.dataset.remove;});saveLocal();render();});
  $('dc-clear').addEventListener('click',function(){selected=[];saveLocal();render();});
  fetch('/property/data/marker-registry.json?v=20260822b',{cache:'no-store'}).then(function(r){if(!r.ok)throw Error(r.status);return r.json();}).then(init).catch(function(e){$('dc-rows').innerHTML='<tr><td class="dc-empty" colspan="7">Marker registry could not load.</td></tr>';console.error('[Watchdog Data Center] marker registry load failed',e);});
})();