(function(){'use strict';
var URL='https://uvkvaxljhhngydvlrzom.supabase.co',KEY='sb_publishable_MYX59qCbK3d-21zDfJqkNw_fvmfnexa',policy=null;
var $=function(id){return document.getElementById(id);};function esc(v){return String(v==null?'':v).replace(/[&<>\"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c];});}
function when(m){if(m.cadence==='live')return'Live query';if(m.cadence==='dependency')return'Derived cascade';var f=policy._fresh&&policy._fresh[m.dataset_id];if(!f||!f.last_modified)return'Not yet recorded';var d=new Date(f.last_modified);return isNaN(d)?'Not yet recorded':d.toLocaleDateString();}
function render(){var q=$('do-search').value.toLowerCase(),cad=$('do-cadence').value,tier=$('do-tier').value;var rows=policy.markers.filter(function(m){return(!cad||m.cadence===cad)&&(!tier||m.tier===tier)&&(!q||(m.marker_id+' '+m.label+' '+m.source_id+' '+m.dataset_id).toLowerCase().indexOf(q)>=0);});$('do-rows').innerHTML=rows.map(function(m){return'<tr><td><strong>'+esc(m.label)+'</strong><small>'+esc(m.marker_id)+'</small></td><td><span class="do-pill '+esc(m.cadence)+'">'+esc(m.cadence)+'</span></td><td><strong>'+esc(m.source_id)+'</strong><small>'+esc(m.dataset_id)+'</small></td><td>'+esc(when(m))+'</td><td>'+esc(m.trigger.replace(/_/g,' '))+'</td><td>'+esc(m.tier==='pro_plus'?'Pro+':m.tier)+'</td><td>'+esc(m.rule)+'</td></tr>';}).join('');}
function readiness(r){if(!r)return;var host=$('do-readiness'),score=r.readiness_score||{},phases=r.phases||[];host.innerHTML='<div class="do-readiness-head"><div><span>PRODUCTION READINESS</span><h2>'+esc(score.current||42)+'% to launch-grade SaaS</h2><p>'+esc(score.summary||'The next milestones make the platform dependable, billable and supportable.')+'</p></div><a href="/property/updates.html">Open roadmap <i class="fas fa-arrow-right"></i></a></div><div class="do-phase-grid">'+phases.map(function(x){return'<article><b>'+esc(x.target)+'%</b><span>'+esc(x.title)+'</span><p>'+esc(x.focus)+'</p></article>';}).join('')+'</div>';}
function paint(p,monitor,freshness,readinessData){policy=p;policy._fresh={};((freshness&&freshness.datasets)||[]).forEach(function(x){policy._fresh[x.id]=x;});var s=p.summary;$('do-stats').innerHTML=[['All markers',s.total],['Annual',s.annual],['Quarterly',s.quarterly],['Live',s.live],['Historical correction',s.correction],['Derived cascade',s.dependency]].map(function(x){return'<div class="do-stat"><b>'+x[1]+'</b><span>'+x[0]+'</span></div>';}).join('');readiness(readinessData);var a=$('do-source-alert');var changed=monitor&&monitor.changed||[],errors=monitor&&monitor.errors||[];a.className='do-source-alert '+(changed.length||errors.length?'warn':'good');a.innerHTML=changed.length?'<b>'+changed.length+' official source change(s) awaiting review.</b> Run the validated refresh before publishing new data.':errors.length?'<b>'+errors.length+' source endpoint(s) could not be checked.</b> Review monitoring health.':'<b>No unresolved publisher-change alert is recorded in the current report.</b> Six-hour monitoring complements—not replaces—the cadence rules below.';render();}
function init(){if(!window.supabase)return;var sb=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,flowType:'pkce',storageKey:'sb-uvkvaxljhhngydvlrzom-auth-token'}});sb.auth.getSession().then(function(r){var session=r.data&&r.data.session;if(!session)throw Error('denied');return sb.rpc('is_watchdog_developer');}).then(function(r){if(r.error||r.data!==true)throw Error('denied');document.dispatchEvent(new CustomEvent('watchdog:developer-confirmed'));$('do-denied').hidden=true;$('do-app').hidden=false;return Promise.all([fetch('/property/data/marker-refresh-policy.json?v=20260806a').then(function(x){return x.json();}),fetch('/property/data/source-monitor-report.json?v=20260806a').then(function(x){return x.json();}).catch(function(){return{};}),fetch('/property/data/data-freshness.json?v=20260806a').then(function(x){return x.json();}).catch(function(){return{};}),fetch('/property/data/saas-production-readiness.json?v=20260807d').then(function(x){return x.json();}).catch(function(){return{};})]);}).then(function(x){paint(x[0],x[1],x[2],x[3]);}).catch(function(){});}
['do-search','do-cadence','do-tier'].forEach(function(id){$(id).addEventListener(id==='do-search'?'input':'change',function(){if(policy)render();});});init();})();
