(function(){'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const data={
 assessment:{score:87,confidence:91,coverage:89,title:'123 Main Street, Washington Township',summary:'Assessment relationship and tax context differ materially from the current review cohort.',model:'Assessment Anomaly Finder',signals:[['Assessment-to-sale relationship','Structured Watchdog derived signal. Formula/version retained.'],['Tax context','Governed tax and assessment inputs available for review.'],['Recent change','Source-linked change event increases review priority.']],missing:'No customer-facing conclusion should imply facts that were not resolved.',source:'Watchdog governed formula registry · preview model v1'},
 closing:{score:84,confidence:78,coverage:74,title:'55 Oak Avenue, Berlin',summary:'Multiple due-diligence signals deserve review before a professional conclusion is made.',model:'Closing Review Priority',signals:[['Closing exception priority','Governed composite signal indicates multiple public-record exceptions deserve review.'],['Permit closure confidence','Published permit/certificate evidence is incomplete enough to affect confidence.'],['Title constraint stack','Mapped public-record constraints are present and require professional review.']],missing:'One supporting diligence input is unresolved; Watchdog will not infer a legal or title conclusion.',source:'Watchdog governed formula registry · preview model v1'},
 change:{score:81,confidence:86,coverage:92,title:'90 Pine Road, Voorhees',summary:'A material source-linked record change moved this property higher in the current queue.',model:'Property Change Intelligence',signals:[['Materiality','A governed field-level change crossed the current preview materiality threshold.'],['Recency','The change occurred inside the current high-priority review window.'],['Property story confidence','Most supporting source facts remain available after the change.']],missing:'No missing core change evidence for this preview finding.',source:'Watchdog snapshot/change infrastructure · preview model v1'}
};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(msg){const t=$('#wi-toast');if(!t)return;t.textContent=msg;t.classList.add('on');clearTimeout(window.__wiToast);window.__wiToast=setTimeout(()=>t.classList.remove('on'),2600)}
function renderDetail(key){const x=data[key]||data.assessment;$('#wi-detail-title').textContent=x.title;$('#wi-detail-summary').textContent=x.summary;$('#wi-detail-score').textContent=x.score;$('#wi-detail-confidence').textContent=x.confidence+'%';$('#wi-detail-coverage').textContent=x.coverage+'%';$('#wi-detail-model').textContent=x.model+' · preview / uncalibrated';$('#wi-detail-evidence').innerHTML=x.signals.map(s=>`<div class="wi-evidence"><b>${esc(s[0])}</b><span>${esc(s[1])}</span></div>`).join('')+`<div class="wi-evidence missing"><b>Missing evidence / caveat</b><span>${esc(x.missing)}</span></div><div class="wi-evidence"><b>Lineage</b><span class="wi-source">${esc(x.source)}</span></div>`;$$('[data-finding]').forEach(b=>b.classList.toggle('primary',b.dataset.finding===key))}
function setModel(key){$$('[data-model]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.model===key?'true':'false'));const label=$(`[data-model="${key}"] b`)?.textContent||'Intelligence model';toast(label+' selected for preview')}
function boot(){
 $$('[data-chip]').forEach(b=>b.addEventListener('click',()=>{$('#wi-question').value=b.textContent.trim();toast('Question staged. Live Analyst comes in Phase 4.')}));
 $$('[data-model]').forEach(b=>b.addEventListener('click',()=>setModel(b.dataset.model)));
 $$('[data-finding]').forEach(b=>b.addEventListener('click',()=>renderDetail(b.dataset.finding)));
 $$('[data-preview-action]').forEach(b=>b.addEventListener('click',()=>toast('Prototype only. This action will use the existing Watchdog workflow when Phase 3 is wired.')));
 renderDetail('assessment');
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();