(function(){
'use strict';
const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rank=p=>({standard:0,agent:1,pro:2,pro_plus:3,teams:4,developer:5}[p]??0);
const human=v=>String(v||'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
let client=null,user=null,digests=[],intent=null,events=[],host=null,showHandled=false,busy=false;
function count(d,key){return Number(d?.summary?.[key]||0)}
function reason(d){const bits=[];if(count(d,'new_count'))bits.push(`${count(d,'new_count')} new`);if(count(d,'strengthened_count'))bits.push(`${count(d,'strengthened_count')} strengthened`);if(count(d,'weakened_count'))bits.push(`${count(d,'weakened_count')} weakened`);if(count(d,'evidence_change_count'))bits.push(`${count(d,'evidence_change_count')} evidence change${count(d,'evidence_change_count')===1?'':'s'}`);if(count(d,'removed_count'))bits.push(`${count(d,'removed_count')} removed`);return bits.join(' · ')||'Scheduled review completed'}
function itemKey(x){return `${x.digestId||''}|${x.model}|${x.pin}`}
function todayItems(rows){const seen=new Set(),items=[];for(const d of rows){for(const q of (Array.isArray(d.recommended_queue)?d.recommended_queue:[])){const pin=String(q.pams_pin||'').trim(),model=String(d.model_key||'intelligence');const dedupe=`${model}|${pin}`;if(!pin||seen.has(dedupe))continue;seen.add(dedupe);items.push({digestId:d.id||null,pin,score:Number(q.score||0),model,date:d.digest_date,reason:reason(d),address:String(q.property_address||q.address||'').trim()})}}return items.slice(0,20)}
function latestEventMap(rows){const map=new Map();for(const e of rows){const key=`${e.digest_id||''}|${e.model_key}|${e.pams_pin}`;if(!map.has(key))map.set(key,e)}return map}
function itemState(item,map){const e=map.get(itemKey(item));if(!e)return'open';if(e.action==='reopened')return'open';if(e.action==='snoozed'){const until=e.snooze_until?new Date(e.snooze_until).getTime():0;return until>Date.now()?'snoozed':'open'}if(e.action==='reviewed'||e.action==='dismissed')return'handled';return'open'}
function when(v){if(!v)return'';const d=new Date(v);return Number.isFinite(d.getTime())?d.toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):''}
function propertyTitle(item){return item.address||item.pin}
function actionButtons(item,state,event){const attrs=`data-pin="${esc(item.pin)}" data-model="${esc(item.model)}" data-digest="${esc(item.digestId||'')}"`;if(state==='handled')return `<div class="wdi-today-actions"><button type="button" data-today-action="reopened" ${attrs}><i class="fas fa-rotate-left"></i> Reopen</button><a href="/property/home?pin=${encodeURIComponent(item.pin)}"><i class="fas fa-house"></i> Property</a></div>`;if(state==='snoozed')return `<div class="wdi-today-actions"><span class="wdi-snooze-label"><i class="far fa-clock"></i> Until ${esc(when(event?.snooze_until))}</span><button type="button" data-today-action="reopened" ${attrs}>Reopen</button></div>`;return `<div class="wdi-today-actions"><button class="primary" type="button" data-today-action="reviewed" ${attrs}><i class="fas fa-magnifying-glass"></i> Review property</button><button type="button" data-today-action="snoozed" ${attrs}><i class="far fa-clock"></i> Tomorrow</button><button type="button" data-today-action="dismissed" ${attrs}><i class="fas fa-check"></i> Dismiss</button></div>`}
function row(item,index,state,event){return `<article class="wdi-today-item ${state}" data-today-key="${esc(itemKey(item))}"><div class="wdi-today-rank">${index+1}</div><div class="wdi-today-copy"><b>${esc(propertyTitle(item))}</b>${item.address?`<em>${esc(item.pin)}</em>`:''}<small>${esc(human(item.model))} · ${esc(item.reason)} · ${esc(String(item.date||''))}</small></div><div class="wdi-today-score"><span>MODEL SCORE</span><b>${Math.round(item.score)}/100</b></div>${actionButtons(item,state,event)}</article>`}
function render(){if(!host)return;const items=todayItems(digests),eventMap=latestEventMap(events),open=[],snoozed=[],handled=[];for(const item of items){const state=itemState(item,eventMap),pair={item,event:eventMap.get(itemKey(item))||null};if(state==='snoozed')snoozed.push(pair);else if(state==='handled')handled.push(pair);else open.push(pair)}const confidence=Number(intent?.active_job_confidence||0),confirmed=Boolean(intent?.active_job)&&confidence>=1;const context=confirmed?`Watchdog is prioritizing this workspace through your confirmed <b>${esc(human(intent.active_job))}</b> research context.`:'Watchdog has no confirmed research objective for this workspace yet. The queue stays evidence-first and does not guess your purpose.';const cleared=!open.length;host.innerHTML=`<section class="wdi-today"><div class="wdi-today-head"><div><span>TODAY</span><h2>${cleared?'You are caught up':'Your Intelligence inbox'}</h2><p>${context}</p></div><a href="/property/data-workbench">Open Workbench <i class="fas fa-arrow-right"></i></a></div><div class="wdi-today-stats"><span><b>${open.length}</b><small>to review</small></span><span><b>${snoozed.length}</b><small>snoozed</small></span><span><b>${handled.length}</b><small>handled</small></span><span><b>${items.length}</b><small>latest queue</small></span></div>${open.length?`<div class="wdi-today-list">${open.map((x,i)=>row(x.item,i,'open',x.event)).join('')}</div>`:`<div class="wdi-today-empty"><i class="fas fa-check-circle"></i><div><b>No open review item remains from the latest governed queues.</b><span>New or materially changed findings will return here after scheduled runs complete. A new digest creates a new review item even if you handled an older one.</span></div></div>`}${snoozed.length?`<section class="wdi-today-secondary"><header><span>SNOOZED</span><b>Coming back later</b></header>${snoozed.map((x,i)=>row(x.item,i,'snoozed',x.event)).join('')}</section>`:''}${handled.length?`<section class="wdi-today-secondary handled"><header><span>HANDLED</span><b>${handled.length} item${handled.length===1?'':'s'} from the latest queues</b><button type="button" id="wdi-toggle-handled">${showHandled?'Hide':'Show'}</button></header>${showHandled?handled.map((x,i)=>row(x.item,i,'handled',x.event)).join(''):''}</section>`:''}<div class="wdi-today-foot"><i class="fas fa-shield-halved"></i><span>This is a governed review queue, not a prediction of seller intent, value, profit, urgency, or outcome. Model score is not action certainty. Review the underlying property evidence before acting. Review, snooze, dismiss and reopen actions are retained as owner-scoped Intelligence events.</span></div></section>`;wire()}
function findItem(button){const pin=button.dataset.pin,model=button.dataset.model,digest=button.dataset.digest;return todayItems(digests).find(x=>x.pin===pin&&x.model===model&&String(x.digestId||'')===String(digest||''))||null}
async function logContextAction(item,action,snoozeUntil){if(!user)return;const payload={surface:'daily_intelligence_today',action,pams_pin:item.pin,model_key:item.model,digest_id:item.digestId,digest_date:item.date,snooze_until:snoozeUntil};const evidence=item.digestId?[{type:'intelligence_daily_digest',id:item.digestId}]:[];try{await client.from('intelligence_intent_events').insert({user_id:user.id,context_key:'daily-intelligence:today',event_type:'observation',fact_class:'observed',payload,evidence_refs:evidence,confidence:null})}catch(_error){}}
async function record(item,action){if(!item||!user||busy)return false;busy=true;const snoozeUntil=action==='snoozed'?new Date(Date.now()+24*60*60*1000).toISOString():null;try{const result=await client.from('intelligence_today_events').insert({user_id:user.id,digest_id:item.digestId,pams_pin:item.pin,model_key:item.model,action,snooze_until:snoozeUntil,metadata:{surface:'daily_intelligence_today',digest_date:item.date,queue_reason:item.reason,model_score:item.score}});if(result.error)throw result.error;logContextAction(item,action,snoozeUntil);await loadEvents();render();return true}catch(error){console.warn('Watchdog Today action could not be saved.',error);return false}finally{busy=false}}
function wire(){host.querySelectorAll('[data-today-action]').forEach(button=>{button.addEventListener('click',async()=>{const item=findItem(button),action=button.dataset.todayAction;if(!item)return;button.disabled=true;const ok=await record(item,action);if(ok&&action==='reviewed')location.href='/property/home?pin='+encodeURIComponent(item.pin);else if(!ok)button.disabled=false})});const toggle=host.querySelector('#wdi-toggle-handled');if(toggle)toggle.addEventListener('click',()=>{showHandled=!showHandled;render()})}
async function loadEvents(){const r=await client.from('intelligence_today_events').select('digest_id,pams_pin,model_key,action,snooze_until,created_at').order('created_at',{ascending:false}).limit(500);events=r.data||[]}
async function load(){const [digestR,intentR,eventR]=await Promise.all([client.from('intelligence_daily_digests').select('id,model_key,digest_date,recommended_queue,summary,created_at').order('digest_date',{ascending:false}).order('created_at',{ascending:false}).limit(20),client.from('intelligence_intent_states').select('active_job,active_job_confidence,profession,confirmed_fields,updated_at').eq('context_key','dashboard:research-set').maybeSingle(),client.from('intelligence_today_events').select('digest_id,pams_pin,model_key,action,snooze_until,created_at').order('created_at',{ascending:false}).limit(500)]);digests=digestR.data||[];intent=intentR.data||null;events=eventR.data||[];render()}
async function init(){await Promise.resolve(window.njptrAccessReady);client=window.NJPTRAccess?.client?.();if(!client)return;const usage=await client.rpc('get_agent_usage');if(rank(usage.data?.plan||'standard')<3)return;const auth=await client.auth.getUser();user=auth.data?.user||null;if(!user)return;const shell=document.querySelector('#wdi-app');if(!shell)return;host=document.querySelector('#wdi-today');if(!host){host=document.createElement('div');host.id='wdi-today';shell.before(host)}await load()}
function boot(){init().catch(error=>console.warn('Watchdog Today could not load.',error))}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,300),{once:true});else setTimeout(boot,300);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&client)load().catch(()=>{})});
})();
