(function(){
'use strict';
if(window.__WATCHDOG_INTEGRATIONS__)return;window.__WATCHDOG_INTEGRATIONS__=true;
var db=null,connections=[],deliveries=[],busy=false;
var $=function(id){return document.getElementById(id);};
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function fmt(v){if(!v)return'—';var d=new Date(v);return Number.isFinite(d.getTime())?d.toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'—';}
function titleEvent(v){return String(v||'event').replace(/[._-]/g,' ').replace(/\b\w/g,function(x){return x.toUpperCase();});}
function show(id,on){var n=$(id);if(n)n.hidden=!on;}
function note(text,isError){var n=$('ig-create-note');if(!n)return;n.textContent=text||'';n.classList.toggle('error',!!isError);}
function setBusy(on){busy=!!on;var b=$('ig-create');if(b)b.disabled=busy;document.querySelectorAll('[data-ig-action]').forEach(function(x){if(x.dataset.igAction!=='close-credentials')x.disabled=busy;});}
async function parseError(error){try{if(error&&error.context&&typeof error.context.json==='function'){var data=await error.context.json();return data&&data.error||error.message;}}catch(_){}return error&&error.message||'Request failed';}
async function invoke(action,body){if(!db)throw new Error('Watchdog connection unavailable');var r=await db.functions.invoke('integration-gateway',{body:Object.assign({action:action},body||{})});if(r.error)throw new Error(await parseError(r.error));return r.data||{};}
function patchShell(){var pagebar=document.querySelector('.wdx-pagebar');if(pagebar){var k=pagebar.querySelector('.wdx-kicker'),h=pagebar.querySelector('h1'),p=pagebar.querySelector('p');if(k)k.textContent='Connected workflows';if(h)h.textContent='Integrations';if(p)p.textContent='Connect Watchdog to CRM and automation workflows with governed, auditable data exchange.';}var nav=document.querySelector('.wd4-nav-links');if(nav&&!nav.querySelector('a[href="/property/integrations"]')){var a=document.createElement('a');a.href='/property/integrations';a.className='active';a.innerHTML='<i class="fas fa-plug"></i>Integrations';var account=nav.querySelector('a[href="/property/account"]');nav.insertBefore(a,account||null);}document.title='Integrations | Watchdog';}
function directionChanged(){var d=$('ig-direction').value,row=$('ig-outbound-row'),input=$('ig-outbound-url');var needs=d==='outbound'||d==='bidirectional';row.hidden=!needs;input.required=needs;if(!needs)input.value='';}
function credentialsModal(connection,credentials){var wrap=$('ig-credentials-fields'),items=[];if(connection&&connection.inbound_url&&credentials&&credentials.inbound_token){items.push(['Inbound endpoint',connection.inbound_url]);items.push(['Inbound token',credentials.inbound_token]);}if(credentials&&credentials.outbound_signing_secret)items.push(['Outbound HMAC signing secret',credentials.outbound_signing_secret]);wrap.innerHTML=items.map(function(item){return'<div class="ig-secret"><label>'+esc(item[0])+'</label><div class="ig-copyrow"><code>'+esc(item[1])+'</code><button type="button" data-copy="'+esc(item[1])+'" aria-label="Copy"><i class="far fa-copy"></i></button></div></div>';}).join('');show('ig-credentials-modal',true);var first=$('ig-credentials-modal').querySelector('button[data-ig-action="close-credentials"]');if(first)first.focus();}
async function copy(value,button){try{await navigator.clipboard.writeText(value);var old=button.innerHTML;button.innerHTML='<i class="fas fa-check"></i>';setTimeout(function(){button.innerHTML=old;},1000);}catch(_){}}
function connCard(c){var inbound=c.direction==='inbound'||c.direction==='bidirectional',outbound=c.direction==='outbound'||c.direction==='bidirectional',intel=(c.scopes||[]).indexOf('intelligence.context.read')>=0&&c.intelligence_access;return'<article class="ig-conn" data-connection="'+esc(c.id)+'"><div class="ig-conn-top"><div class="ig-conn-title"><i class="fas fa-plug"></i><span><b>'+esc(c.name)+'</b><small>'+esc(c.external_account_label||'Generic webhook')+' · '+esc(c.direction)+'</small></span></div><span class="ig-status '+esc(c.status)+'">'+esc(c.status)+'</span></div><div class="ig-conn-meta"><div><small>Last inbound</small><b>'+esc(fmt(c.last_inbound_at))+'</b></div><div><small>Last outbound</small><b>'+esc(fmt(c.last_outbound_at))+'</b></div><div><small>Events</small><b>'+esc((c.event_types||[]).filter(function(x){return x!=='integration.test';}).length+' subscribed')+'</b></div><div><small>Signing</small><b>'+esc(c.outbound_signing_configured?'HMAC enabled':outbound?'Not configured':'Inbound only')+'</b></div></div>'+(inbound?'<div class="ig-endpoint"><label>Inbound endpoint</label><div class="ig-copyrow"><code>'+esc(c.inbound_url)+'</code><button type="button" data-copy="'+esc(c.inbound_url)+'"><i class="far fa-copy"></i></button></div></div>':'')+(outbound?'<div class="ig-endpoint"><label>Outbound destination</label><div class="ig-copyrow"><code>'+esc(c.outbound_url||'Not configured')+'</code><button type="button" data-copy="'+esc(c.outbound_url||'')+'"><i class="far fa-copy"></i></button></div></div>':'')+(c.last_error?'<div class="ig-conn-error"><i class="fas fa-triangle-exclamation"></i> '+esc(c.last_error)+'</div>':'')+'<div class="ig-conn-controls"><label class="ig-toggle"><input type="checkbox" data-intel="'+esc(c.id)+'" '+(intel?'checked':'')+'><span></span><div><b>CRM context for Intelligence</b><small>'+(intel?'Explicit read scope enabled':'Off for this connection')+'</small></div></label><div class="ig-conn-actions">'+(outbound?'<button type="button" data-ig-action="test" data-id="'+esc(c.id)+'"><i class="fas fa-paper-plane"></i> Test</button>':'')+'<button type="button" data-ig-action="pause" data-id="'+esc(c.id)+'"><i class="fas '+(c.status==='active'?'fa-pause':'fa-play')+'"></i> '+(c.status==='active'?'Pause':'Resume')+'</button><button type="button" data-ig-action="rotate" data-id="'+esc(c.id)+'"><i class="fas fa-key"></i> Rotate</button><button class="danger" type="button" data-ig-action="revoke" data-id="'+esc(c.id)+'"><i class="fas fa-trash"></i> Revoke</button></div></div></article>';}
function renderConnections(){var box=$('ig-connections');box.innerHTML=connections.map(connCard).join('');show('ig-connections-empty',!connections.length);$('ig-stat-connections').textContent=connections.filter(function(c){return c.status==='active';}).length;$('ig-stat-intel').textContent=connections.filter(function(c){return c.intelligence_access&&(c.scopes||[]).indexOf('intelligence.context.read')>=0;}).length;}
function renderHistory(){var body=$('ig-history');var delivered=0,problems=0;body.innerHTML=deliveries.map(function(d){var e=d.event||{},c=d.connection||{},s=d.status||'pending';if(s==='delivered')delivered++;if(s==='failed'||Number(d.attempt_count||0)>1)problems++;return'<tr><td><b>'+esc(titleEvent(e.event_type))+'</b><br><small>'+esc(e.event_key||'')+'</small></td><td>'+esc(c.name||'—')+'</td><td><span class="ig-status '+esc(s)+'">'+esc(s)+'</span></td><td>'+esc(d.attempt_count||0)+' / '+esc(d.max_attempts||5)+'</td><td>'+esc(d.last_http_status||'—')+'</td><td>'+esc(fmt(d.created_at))+(d.last_error?'<br><small title="'+esc(d.last_error)+'">'+esc(String(d.last_error).slice(0,70))+'</small>':'')+'</td></tr>';}).join('');$('ig-stat-delivered').textContent=delivered;$('ig-stat-retries').textContent=problems;show('ig-history-empty',!deliveries.length);var table=document.querySelector('.ig-history-wrap');if(table)table.hidden=!deliveries.length;}
async function loadConnections(){var data=await invoke('connections.list');connections=data.connections||[];renderConnections();}
async function loadHistory(){var data=await invoke('events.list',{limit:40});deliveries=data.deliveries||[];renderHistory();}
async function refresh(){setBusy(true);try{await Promise.all([loadConnections(),loadHistory()]);}finally{setBusy(false);}}
async function createConnection(event){event.preventDefault();if(busy)return;var direction=$('ig-direction').value,intel=$('ig-intelligence').checked,scopes=[];if(direction==='inbound'||direction==='bidirectional')scopes.push('crm.context.ingest');if(intel)scopes.push('intelligence.context.read');var body={name:$('ig-name').value.trim(),direction:direction,outbound_url:$('ig-outbound-url').value.trim(),external_account_label:$('ig-account-label').value.trim(),event_types:$('ig-event-property').checked?['property.signal.changed','integration.test']:['integration.test'],scopes:scopes};note('Creating secure credentials…');setBusy(true);try{var data=await invoke('connection.create',body);if(intel&&data.connection){await invoke('connection.update',{connection_id:data.connection.id,scopes:scopes,intelligence_access:true});data.connection.intelligence_access=true;data.connection.scopes=scopes;}credentialsModal(data.connection,data.credentials||{});$('ig-create-form').reset();$('ig-direction').value='bidirectional';$('ig-event-property').checked=true;directionChanged();note('Connection created. Save the one-time credentials.');await refresh();}catch(err){note(err.message,true);}finally{setBusy(false);}}
function findConnection(id){return connections.find(function(c){return c.id===id;});}
async function action(button){var a=button.dataset.igAction,id=button.dataset.id,c=id&&findConnection(id);if(a==='reload'){location.reload();return;}if(a==='close-credentials'){show('ig-credentials-modal',false);return;}if(a==='refresh'||a==='history'){setBusy(true);try{await refresh();}catch(err){note(err.message,true);}finally{setBusy(false);}return;}if(!c)return;setBusy(true);try{if(a==='test'){await invoke('delivery.test',{connection_id:id});note('Test delivery queued.');setTimeout(function(){loadHistory().catch(function(){});},900);}else if(a==='pause'){await invoke('connection.update',{connection_id:id,status:c.status==='active'?'paused':'active'});await loadConnections();}else if(a==='rotate'){if(!confirm('Rotate this connection’s inbound token and signing secret? Existing credentials will stop working immediately.'))return;var r=await invoke('connection.rotate',{connection_id:id});credentialsModal(r.connection,r.credentials||{});await loadConnections();}else if(a==='revoke'){if(!confirm('Revoke this connection? Pending deliveries will be canceled and its credentials will stop working.'))return;await invoke('connection.revoke',{connection_id:id});await refresh();}}catch(err){alert(err.message);}finally{setBusy(false);}}
async function intelChanged(input){var id=input.dataset.intel,c=findConnection(id);if(!c)return;var scopes=(c.scopes||[]).filter(function(x){return x!=='intelligence.context.read';});if(input.checked)scopes.push('intelligence.context.read');setBusy(true);try{await invoke('connection.update',{connection_id:id,scopes:scopes,intelligence_access:input.checked});await loadConnections();}catch(err){input.checked=!input.checked;alert(err.message);}finally{setBusy(false);}}
async function boot(){patchShell();setTimeout(patchShell,60);try{db=window.NJPTRSupabaseRuntime&&window.NJPTRSupabaseRuntime.createClient?window.NJPTRSupabaseRuntime.createClient():null;if(!db)throw new Error('Watchdog data client unavailable');var session=await db.auth.getSession(),s=session&&session.data&&session.data.session;if(!s){show('ig-signin',true);return;}try{await invoke('status');}catch(err){if(/Pro\+|Teams|requires/i.test(err.message)){show('ig-plan-gate',true);return;}throw err;}show('ig-workspace',true);await refresh();}catch(err){$('ig-error-text').textContent=err.message||'Integration Center could not load.';show('ig-error',true);}}
document.addEventListener('submit',function(e){if(e.target&&e.target.id==='ig-create-form')createConnection(e);});document.addEventListener('change',function(e){if(e.target&&e.target.id==='ig-direction')directionChanged();if(e.target&&e.target.matches('[data-intel]'))intelChanged(e.target);});document.addEventListener('click',function(e){var copyBtn=e.target.closest('[data-copy]');if(copyBtn){copy(copyBtn.dataset.copy||'',copyBtn);return;}var b=e.target.closest('[data-ig-action]');if(b)action(b);});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
