(function(){
'use strict';
if(window.__WATCHDOG_INTEGRATIONS__)return;window.__WATCHDOG_INTEGRATIONS__=true;
var db=null,connections=[],deliveries=[],keys=[],contextSummary={},busy=false,editingKeyId=null;
var $=function(id){return document.getElementById(id);};
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function fmt(v){if(!v)return'—';var d=new Date(v);return Number.isFinite(d.getTime())?d.toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'—';}
function titleEvent(v){return String(v||'event').replace(/[._-]/g,' ').replace(/\b\w/g,function(x){return x.toUpperCase();});}
function show(id,on){var n=$(id);if(n)n.hidden=!on;}
function setText(id,v){var n=$(id);if(n)n.textContent=v;}
function note(id,text,isError){var n=$(id);if(!n)return;n.textContent=text||'';n.classList.toggle('error',!!isError);}
function setBusy(on){busy=!!on;document.querySelectorAll('#ig-app button,#ig-app input,#ig-app select').forEach(function(x){if(!x.matches('[data-ig-action="close-credentials"],[data-ig-action="close-mapping"]'))x.disabled=busy;});}
async function parseError(error){try{if(error&&error.context&&typeof error.context.json==='function'){var data=await error.context.json();return data&&data.error||error.message;}}catch(_){}return error&&error.message||'Request failed';}
async function invokeFunction(name,action,body){if(!db)throw new Error('Watchdog connection unavailable');var r=await db.functions.invoke(name,{body:Object.assign({action:action},body||{})});if(r.error)throw new Error(await parseError(r.error));return r.data||{};}
function invoke(action,body){return invokeFunction('integration-gateway',action,body);}
function invokeKeys(action,body){return invokeFunction('integration-key-manager',action,body);}
function patchShell(){var pagebar=document.querySelector('.wdx-pagebar');if(pagebar){var k=pagebar.querySelector('.wdx-kicker'),h=pagebar.querySelector('h1'),p=pagebar.querySelector('p');if(k)k.textContent='Connected workflows';if(h)h.textContent='Integrations';if(p)p.textContent='Connect Watchdog to CRM and automation workflows with governed, auditable data exchange.';}var nav=document.querySelector('.wd4-nav-links');if(nav&&!nav.querySelector('a[href="/property/integrations"]')){var a=document.createElement('a');a.href='/property/integrations';a.className='active';a.innerHTML='<i class="fas fa-plug"></i>Integrations';var account=nav.querySelector('a[href="/property/account"]');nav.insertBefore(a,account||null);}document.title='Integrations | Watchdog';}
function directionChanged(){var d=$('ig-direction').value,row=$('ig-outbound-row'),input=$('ig-outbound-url');var needs=d==='outbound'||d==='bidirectional';row.hidden=!needs;input.required=needs;if(!needs)input.value='';}
function credentialModal(title,copyText,items){$('ig-credentials-title').textContent=title;$('ig-credentials-copy').textContent=copyText;$('ig-credentials-fields').innerHTML=items.map(function(item){return'<div class="ig-secret"><label>'+esc(item[0])+'</label><div class="ig-copyrow"><code>'+esc(item[1])+'</code><button type="button" data-copy="'+esc(item[1])+'" aria-label="Copy"><i class="far fa-copy"></i></button></div></div>';}).join('');show('ig-credentials-modal',true);}
function webhookCredentialModal(connection,credentials){var items=[];if(connection&&connection.inbound_url&&credentials&&credentials.inbound_token){items.push(['Inbound endpoint',connection.inbound_url]);items.push(['Inbound token',credentials.inbound_token]);}if(credentials&&credentials.outbound_signing_secret)items.push(['Outbound HMAC signing secret',credentials.outbound_signing_secret]);credentialModal('Save your connection credentials','Watchdog will not show these secrets again. Store them in the receiving system’s secure credential fields.',items);}
async function copy(value,button){try{await navigator.clipboard.writeText(value);var old=button.innerHTML;button.innerHTML='<i class="fas fa-check"></i>';setTimeout(function(){button.innerHTML=old;},1000);}catch(_){}}
function providerIcon(c){return c.provider==='zapier'?'fa-bolt':'fa-plug';}
function connectionHealth(c){if(c.last_error)return['error','Needs attention'];if(c.status==='paused')return['paused','Paused'];if(c.last_inbound_at||c.last_outbound_at)return['active','Connected'];return['active','Ready'];}
function scopeChips(scopes){return(scopes||[]).filter(function(x){return x!=='crm.context.ingest';}).map(function(x){return'<span>'+esc(x.replace('intelligence.context.read','Intelligence context').replace('crm.','CRM ').replace(/\./g,' '))+'</span>';}).join('');}
function connCard(c){var inbound=c.direction==='inbound'||c.direction==='bidirectional',outbound=c.direction==='outbound'||c.direction==='bidirectional',intel=(c.scopes||[]).indexOf('intelligence.context.read')>=0&&c.intelligence_access,health=connectionHealth(c);return'<article class="ig-conn" data-connection="'+esc(c.id)+'"><div class="ig-conn-top"><div class="ig-conn-title"><i class="fas '+providerIcon(c)+'"></i><span><b>'+esc(c.name)+'</b><small>'+esc(c.external_account_label||c.provider||'Webhook')+' · '+esc(c.direction)+'</small></span></div><span class="ig-status '+esc(health[0])+'">'+esc(health[1])+'</span></div><div class="ig-conn-meta"><div><small>Last inbound</small><b>'+esc(fmt(c.last_inbound_at))+'</b></div><div><small>Last outbound</small><b>'+esc(fmt(c.last_outbound_at))+'</b></div><div><small>Events</small><b>'+esc((c.event_types||[]).filter(function(x){return x!=='integration.test';}).length+' subscribed')+'</b></div><div><small>Field mapping</small><b>'+esc(c.mapping_configured?'Configured':'Standard paths')+'</b></div></div>'+(scopeChips(c.scopes)?'<div class="ig-scope-chips">'+scopeChips(c.scopes)+'</div>':'')+(inbound?'<div class="ig-endpoint"><label>Inbound endpoint</label><div class="ig-copyrow"><code>'+esc(c.inbound_url)+'</code><button type="button" data-copy="'+esc(c.inbound_url)+'"><i class="far fa-copy"></i></button></div></div>':'')+(outbound?'<div class="ig-endpoint"><label>Outbound destination</label><div class="ig-copyrow"><code>'+esc(c.outbound_url||'Not configured')+'</code><button type="button" data-copy="'+esc(c.outbound_url||'')+'"><i class="far fa-copy"></i></button></div></div>':'')+(c.last_error?'<div class="ig-conn-error"><i class="fas fa-triangle-exclamation"></i> '+esc(c.last_error)+'</div>':'')+'<div class="ig-conn-controls"><label class="ig-toggle"><input type="checkbox" data-intel="'+esc(c.id)+'" '+(intel?'checked':'')+'><span></span><div><b>CRM context for Intelligence</b><small>'+(intel?'Explicit permission enabled'+(c.intelligence_access_updated_at?' · '+esc(fmt(c.intelligence_access_updated_at)):''):'Off for this connection')+'</small></div></label><div class="ig-conn-actions">'+(inbound?'<button type="button" data-ig-action="mapping" data-id="'+esc(c.id)+'"><i class="fas fa-table-columns"></i> Field mapping</button>':'')+(outbound?'<button type="button" data-ig-action="test" data-id="'+esc(c.id)+'"><i class="fas fa-paper-plane"></i> Test</button>':'')+'<button type="button" data-ig-action="pause" data-id="'+esc(c.id)+'"><i class="fas '+(c.status==='active'?'fa-pause':'fa-play')+'"></i> '+(c.status==='active'?'Pause':'Resume')+'</button><button type="button" data-ig-action="rotate" data-id="'+esc(c.id)+'"><i class="fas fa-key"></i> Rotate</button><button class="danger" type="button" data-ig-action="revoke" data-id="'+esc(c.id)+'"><i class="fas fa-trash"></i> Revoke</button></div></div></article>';}
function renderConnections(){var box=$('ig-connections');box.innerHTML=connections.map(connCard).join('');show('ig-connections-empty',!connections.length);setText('ig-stat-connections',connections.filter(function(c){return c.status==='active';}).length);}
function keyScopeLabel(s){return{'zapier.auth':'Authenticate','triggers.manage':'Triggers','property.read':'Property read','watchlist.write':'Watchlist write','crm.context.write':'CRM context'}[s]||s;}
function keyCard(k){var active=k.status==='active';return'<article class="ig-key '+(active?'':'revoked')+'"><div class="ig-key-main"><div><b>'+esc(k.label)+'</b><code>'+esc(k.key_prefix)+'••••••••</code></div><span class="ig-status '+(active?'active':'failed')+'">'+esc(k.status)+'</span></div><div class="ig-scope-chips">'+(k.scopes||[]).map(function(s){return'<span>'+esc(keyScopeLabel(s))+'</span>';}).join('')+'</div><div class="ig-key-meta"><span>Created '+esc(fmt(k.created_at))+'</span><span>Last used '+esc(fmt(k.last_used_at))+'</span></div>'+(active?'<div class="ig-key-actions"><button type="button" data-ig-action="key-edit" data-id="'+esc(k.id)+'"><i class="fas fa-sliders"></i>Scopes</button><button class="danger" type="button" data-ig-action="key-revoke" data-id="'+esc(k.id)+'"><i class="fas fa-ban"></i>Revoke</button></div>':'')+'</article>';}
function renderKeys(){var active=keys.filter(function(k){return k.status==='active';});$('ig-keys').innerHTML=keys.map(keyCard).join('');show('ig-keys-empty',!keys.length);setText('ig-stat-keys',active.length);}
function renderContext(){setText('ig-stat-crm',Number(contextSummary.crm_records||0));setText('ig-context-records',Number(contextSummary.crm_records||0));setText('ig-context-linked',Number(contextSummary.property_linked||0));setText('ig-context-latest',contextSummary.latest?fmt(contextSummary.latest.updated_at):'Not yet');}
function renderHistory(){var body=$('ig-history'),problems=0;body.innerHTML=deliveries.map(function(d){var e=d.event||{},c=d.connection||{},s=d.status||'pending';if(s==='failed'||Number(d.attempt_count||0)>1)problems++;return'<tr><td><b>'+esc(titleEvent(e.event_type))+'</b><br><small>'+esc(e.event_key||'')+'</small></td><td>'+esc(c.name||'—')+'</td><td><span class="ig-status '+esc(s)+'">'+esc(s)+'</span></td><td>'+esc(d.attempt_count||0)+' / '+esc(d.max_attempts||5)+'</td><td>'+esc(d.last_http_status||'—')+'</td><td>'+esc(fmt(d.created_at))+(d.last_error?'<br><small title="'+esc(d.last_error)+'">'+esc(String(d.last_error).slice(0,70))+'</small>':'')+'</td></tr>';}).join('');setText('ig-stat-retries',problems);show('ig-history-empty',!deliveries.length);var table=document.querySelector('.ig-history-wrap');if(table)table.hidden=!deliveries.length;}
async function loadConnections(){var data=await invoke('connections.list');connections=data.connections||[];renderConnections();}
async function loadHistory(){var data=await invoke('events.list',{limit:40});deliveries=data.deliveries||[];renderHistory();}
async function loadKeys(){var data=await invokeKeys('keys.list');keys=data.keys||[];renderKeys();}
async function loadContext(){contextSummary=await invoke('context.summary');renderContext();}
async function refresh(){setBusy(true);try{await Promise.all([loadConnections(),loadHistory(),loadKeys(),loadContext()]);}finally{setBusy(false);}}
function selectedEvents(){var out=[];if($('ig-event-property').checked)out.push('property.signal.changed');if($('ig-event-watchlist').checked)out.push('watchlist.alert');if($('ig-event-report').checked)out.push('report.ready');if($('ig-event-intelligence').checked)out.push('intelligence.finding.created');return out;}
async function createConnection(event){event.preventDefault();if(busy)return;var direction=$('ig-direction').value,intel=$('ig-intelligence').checked,scopes=[];if(direction==='inbound'||direction==='bidirectional')scopes.push('crm.context.ingest');if(intel)scopes.push('intelligence.context.read');var body={name:$('ig-name').value.trim(),direction:direction,outbound_url:$('ig-outbound-url').value.trim(),external_account_label:$('ig-account-label').value.trim(),event_types:selectedEvents(),scopes:scopes};note('ig-create-note','Creating secure connection…');setBusy(true);try{var data=await invoke('connection.create',body);if(intel&&data.connection){await invoke('connection.update',{connection_id:data.connection.id,scopes:scopes,intelligence_access:true});}webhookCredentialModal(data.connection,data.credentials||{});$('ig-create-form').reset();$('ig-direction').value='bidirectional';$('ig-event-property').checked=true;$('ig-event-watchlist').checked=true;directionChanged();note('ig-create-note','Connection created. Save the one-time credentials.');await refresh();}catch(err){note('ig-create-note',err.message,true);}finally{setBusy(false);}}
function selectedKeyScopes(){var s=[];if($('ig-key-triggers').checked)s.push('triggers.manage');if($('ig-key-property').checked)s.push('property.read');if($('ig-key-watchlist').checked)s.push('watchlist.write');if($('ig-key-crm').checked)s.push('crm.context.write');return s;}
function resetKeyEditor(){editingKeyId=null;$('ig-key-form').reset();['ig-key-triggers','ig-key-property','ig-key-watchlist','ig-key-crm'].forEach(function(id){$(id).checked=true;});$('ig-create-key-label').textContent='Create Zapier key';show('ig-key-cancel',false);}
async function createKey(event){event.preventDefault();if(busy)return;var isEdit=!!editingKeyId;note('ig-key-note',isEdit?'Saving key settings…':'Creating revocable Zapier key…');setBusy(true);try{if(isEdit){await invokeKeys('key.update',{key_id:editingKeyId,label:$('ig-key-label').value.trim(),scopes:selectedKeyScopes()});resetKeyEditor();note('ig-key-note','Key settings updated.');await loadKeys();}else{var data=await invokeKeys('key.create',{label:$('ig-key-label').value.trim(),scopes:selectedKeyScopes()});credentialModal('Save your Zapier API key','Paste this key into Watchdog for Zapier when Zapier asks for your Watchdog API key. It will not be shown again.',[['Watchdog API key',data.credential.api_key]]);resetKeyEditor();note('ig-key-note','Key created. Save it before closing the credential window.');await loadKeys();}}catch(err){note('ig-key-note',err.message,true);}finally{setBusy(false);}}
function findConnection(id){return connections.find(function(c){return c.id===id;});}
function findKey(id){return keys.find(function(k){return k.id===id;});}
async function openMapping(id){var c=findConnection(id);if(!c)return;setBusy(true);try{var data=await invoke('mapping.get',{connection_id:id});$('ig-mapping-connection').value=id;document.querySelectorAll('[data-map-key]').forEach(function(input){input.value=data.mapping&&data.mapping[input.dataset.mapKey]||'';});$('ig-mapping-title').textContent='Map fields for '+c.name;note('ig-mapping-note',data.updated_at?'Last saved '+fmt(data.updated_at):'Using standard Watchdog paths until you save a custom mapping.');show('ig-mapping-modal',true);}catch(err){alert(err.message);}finally{setBusy(false);}}
async function saveMapping(event){event.preventDefault();var id=$('ig-mapping-connection').value,mapping={};document.querySelectorAll('[data-map-key]').forEach(function(input){var v=input.value.trim();if(v)mapping[input.dataset.mapKey]=v;});note('ig-mapping-note','Saving mapping…');setBusy(true);try{var data=await invoke('mapping.update',{connection_id:id,mapping:mapping});note('ig-mapping-note','Mapping saved '+fmt(data.updated_at));await loadConnections();}catch(err){note('ig-mapping-note',err.message,true);}finally{setBusy(false);}}
async function action(button){var a=button.dataset.igAction,id=button.dataset.id,c=id&&findConnection(id);if(a==='reload'){location.reload();return;}if(a==='close-credentials'){show('ig-credentials-modal',false);return;}if(a==='close-mapping'){show('ig-mapping-modal',false);return;}if(a==='refresh'||a==='history'){try{await refresh();}catch(err){alert(err.message);}return;}if(a==='refresh-keys'){setBusy(true);try{await loadKeys();}catch(err){alert(err.message);}finally{setBusy(false);}return;}if(a==='mapping'){await openMapping(id);return;}if(a==='key-edit-cancel'){resetKeyEditor();note('ig-key-note','');return;}if(a==='key-revoke'){var key=findKey(id);if(!key||!confirm('Revoke '+key.label+'? Any Zap using this key will stop authenticating immediately.'))return;setBusy(true);try{await invokeKeys('key.revoke',{key_id:id});if(editingKeyId===id)resetKeyEditor();await loadKeys();}catch(err){alert(err.message);}finally{setBusy(false);}return;}if(a==='key-edit'){var k=findKey(id);if(!k)return;editingKeyId=id;$('ig-key-label').value=k.label;$('ig-key-triggers').checked=(k.scopes||[]).indexOf('triggers.manage')>=0;$('ig-key-property').checked=(k.scopes||[]).indexOf('property.read')>=0;$('ig-key-watchlist').checked=(k.scopes||[]).indexOf('watchlist.write')>=0;$('ig-key-crm').checked=(k.scopes||[]).indexOf('crm.context.write')>=0;$('ig-create-key-label').textContent='Save key settings';show('ig-key-cancel',true);note('ig-key-note','Editing '+k.label+'. The API key itself does not change.');$('ig-key-form').scrollIntoView({behavior:'smooth',block:'center'});return;}if(!c)return;setBusy(true);try{if(a==='test'){await invoke('delivery.test',{connection_id:id});note('ig-create-note','Test delivery queued.');setTimeout(function(){loadHistory().catch(function(){});},900);}else if(a==='pause'){await invoke('connection.update',{connection_id:id,status:c.status==='active'?'paused':'active'});await loadConnections();}else if(a==='rotate'){if(!confirm('Rotate this connection’s inbound token and signing secret? Existing credentials will stop working immediately.'))return;var r=await invoke('connection.rotate',{connection_id:id});webhookCredentialModal(r.connection,r.credentials||{});await loadConnections();}else if(a==='revoke'){if(!confirm('Revoke this connection? Pending deliveries will be canceled and its credentials will stop working.'))return;await invoke('connection.revoke',{connection_id:id});await refresh();}}catch(err){alert(err.message);}finally{setBusy(false);}}
async function intelChanged(input){var id=input.dataset.intel,c=findConnection(id);if(!c)return;var scopes=(c.scopes||[]).filter(function(x){return x!=='intelligence.context.read';});if(input.checked)scopes.push('intelligence.context.read');setBusy(true);try{await invoke('connection.update',{connection_id:id,scopes:scopes,intelligence_access:input.checked});await loadConnections();await loadContext();}catch(err){input.checked=!input.checked;alert(err.message);}finally{setBusy(false);}}
async function boot(){patchShell();setTimeout(patchShell,60);try{db=window.NJPTRSupabaseRuntime&&window.NJPTRSupabaseRuntime.createClient?window.NJPTRSupabaseRuntime.createClient():null;if(!db)throw new Error('Watchdog data client unavailable');var session=await db.auth.getSession(),s=session&&session.data&&session.data.session;if(!s){show('ig-signin',true);return;}try{await invoke('status');}catch(err){if(/Pro\+|Teams|requires/i.test(err.message)){show('ig-plan-gate',true);return;}throw err;}show('ig-workspace',true);await refresh();}catch(err){$('ig-error-text').textContent=err.message||'Integration Center could not load.';show('ig-error',true);}}
document.addEventListener('submit',function(e){if(e.target&&e.target.id==='ig-create-form')createConnection(e);if(e.target&&e.target.id==='ig-key-form')createKey(e);if(e.target&&e.target.id==='ig-mapping-form')saveMapping(e);});
document.addEventListener('change',function(e){if(e.target&&e.target.id==='ig-direction')directionChanged();if(e.target&&e.target.matches('[data-intel]'))intelChanged(e.target);});
document.addEventListener('click',function(e){var copyBtn=e.target.closest('[data-copy]');if(copyBtn){copy(copyBtn.dataset.copy||'',copyBtn);return;}var b=e.target.closest('[data-ig-action]');if(b)action(b);});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();