(function(){
'use strict';
if(window.__WATCHDOG_INTEGRATION_RECIPES__)return;window.__WATCHDOG_INTEGRATION_RECIPES__=true;
if(!document.body||document.body.getAttribute('data-sidebar-page')!=='integrations')return;
var root=document.getElementById('ig-workspace');if(!root)return;
var recipes=[
 {key:'opportunity_followup',icon:'fa-crosshairs',kicker:'LEAD FOLLOW-UP',title:'High-priority opportunity → CRM task + team alert',summary:'Turn a governed Watchdog Intelligence finding into a follow-up task, then notify the assigned team in Slack or SMS.',trigger:'Intelligence Finding Created',watchdog:['Require a verified CRM-to-property relationship','Read the proof-backed Intelligence finding','Keep the finding and property IDs in downstream activity'],zapier:['Create a task in the connected CRM','Notify the assigned team in Slack or an approved SMS tool'],scopes:['triggers.manage','intelligence.read'],tier:'Tier 2 proposed workflow',approval:'No customer communication is included. Any client send is a separate Tier 3 human-approved action.'},
 {key:'watchlist_change',icon:'fa-binoculars',kicker:'WATCHLIST',title:'Watched property changed → notify + create follow-up',summary:'React to a material Watchlist alert without making every raw property update an external workflow.',trigger:'Watchlist Alert',watchdog:['Use the governed Watchlist event','Apply the materiality filter before downstream work','Preserve the original event ID for retries'],zapier:['Notify the user or team','Create a reversible CRM/task follow-up'],scopes:['triggers.manage'],tier:'Tier 2 proposed workflow',approval:'Reversible task/notification flow. External writes remain subject to provider and connection kill switches.'},
 {key:'report_ready',icon:'fa-file-circle-check',kicker:'CLIENT HANDOFF',title:'Report ready → client draft + Drive + CRM activity',summary:'When a Watchdog report is ready, prepare the operational handoff while keeping customer communication approval explicit.',trigger:'Report Ready',watchdog:['Verify report access for the requesting user','Pass a governed report reference instead of copying unrestricted evidence'],zapier:['Save the authorized report reference to Drive','Attach/log the report in the verified CRM record','Prepare an email draft'],scopes:['triggers.manage','property.read'],tier:'Tier 2 draft workflow',approval:'The recipe prepares a client email draft. Sending customer communication remains a separate Tier 3 approval.'},
 {key:'investor_threshold',icon:'fa-chart-line',kicker:'INVESTOR',title:'Investor threshold crossed → acquisition sheet + alert',summary:'Route a qualified property opportunity into an acquisition workflow only after Watchdog evidence and thresholds pass.',trigger:'Intelligence Finding Created',watchdog:['Require a governed property identifier','Use the Intelligence score/confidence and evidence coverage supplied by Watchdog','Do not infer owner distress or seller intent'],zapier:['Create or update an acquisition sheet row','Create a CRM research task','Notify the acquisitions channel'],scopes:['triggers.manage','intelligence.read','property.read'],tier:'Tier 2 proposed workflow',approval:'Research/task writes only. No outreach or spend-bearing action is included.'},
 {key:'external_lead_intelligence',icon:'fa-arrows-rotate',kicker:'INBOUND LEAD',title:'External CRM lead → Watchlist + Watchdog Intelligence',summary:'Bring normalized CRM relationship context into Watchdog, save the governed property, and queue an approved Intelligence analysis.',trigger:'External CRM / lead event',watchdog:['Send normalized CRM context as non-authoritative workflow context','Resolve the property through Watchdog','Add the governed property to Watchlist','Run an approved Intelligence model with the source event as idempotency identity'],zapier:['Start from the CRM lead/update trigger','Route the Watchdog result back into the CRM or team workflow'],scopes:['crm.context.write','property.read','watchlist.write','intelligence.run'],tier:'Tier 2 proposed workflow',approval:'CRM context never overwrites governed property truth. Intelligence uses normal plan quotas and supported models.'}
];
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function addCss(){if(document.querySelector('link[data-watchdog-integration-recipes]'))return;var l=document.createElement('link');l.rel='stylesheet';l.href='/property/css/integrations-recipes.css';l.dataset.watchdogIntegrationRecipes='true';document.head.appendChild(l);}
function list(items){return'<ul>'+items.map(function(x){return'<li>'+esc(x)+'</li>';}).join('')+'</ul>';}
function card(r){return'<article class="igr-card" data-recipe="'+esc(r.key)+'"><div class="igr-card-top"><span class="igr-icon"><i class="fas '+esc(r.icon)+'"></i></span><div><small>'+esc(r.kicker)+'</small><h4>'+esc(r.title)+'</h4></div></div><p>'+esc(r.summary)+'</p><div class="igr-trigger"><span>WATCHDOG TRIGGER</span><b>'+esc(r.trigger)+'</b></div><details><summary>See governed build plan <i class="fas fa-chevron-down"></i></summary><div class="igr-plan"><section><span>WATCHDOG</span>'+list(r.watchdog)+'</section><section><span>ZAPIER / DOWNSTREAM</span>'+list(r.zapier)+'</section><section><span>REQUIRED WATCHDOG SCOPES</span><div class="igr-scopes">'+r.scopes.map(function(x){return'<code>'+esc(x)+'</code>';}).join('')+'</div></section><div class="igr-boundary"><b>'+esc(r.tier)+'</b><p>'+esc(r.approval)+'</p></div></div></details><div class="igr-actions"><button type="button" data-igr-copy="'+esc(r.key)+'"><i class="far fa-copy"></i>Copy build plan</button><a href="/property/integrations/zapier/#setup"><i class="fas fa-arrow-up-right-from-square"></i>Zapier setup</a></div></article>';}
function buildText(r){return ['Watchdog Automation Recipe: '+r.title,'','Trigger: '+r.trigger,'','Watchdog steps:'].concat(r.watchdog.map(function(x){return'- '+x;}),['','Zapier / downstream steps:']).concat(r.zapier.map(function(x){return'- '+x;}),['','Required Watchdog scopes: '+r.scopes.join(', '),'Autonomy: '+r.tier,'Boundary: '+r.approval]).join('\n');}
function install(){if(document.getElementById('ig-recipes'))return;var box=document.createElement('section');box.id='ig-recipes';box.className='ig-recipes-section';box.innerHTML='<div class="igr-head"><div><span class="ig-kicker">AUTOMATION RECIPES</span><h3>Start with an outcome, not a raw webhook.</h3><p>These recipes map the governed Watchdog building blocks to common professional workflows. They are build plans, not hidden autonomous permissions.</p></div><a href="/property/integrations/zapier/"><i class="fas fa-bolt"></i>Watchdog for Zapier guide</a></div><div class="igr-grid">'+recipes.map(card).join('')+'</div><div class="igr-foot"><i class="fas fa-shield-halved"></i><span><b>Guardrails stay attached.</b> Recipe selection never grants new scopes, bypasses approval, turns CRM context into property truth, or enables Tier 4 autonomy.</span></div>';root.appendChild(box);}
async function copyRecipe(key,button){var r=recipes.find(function(x){return x.key===key;});if(!r)return;try{await navigator.clipboard.writeText(buildText(r));var old=button.innerHTML;button.innerHTML='<i class="fas fa-check"></i>Copied';setTimeout(function(){button.innerHTML=old;},1400);}catch(_){button.textContent='Copy unavailable';}}
function wire(){document.addEventListener('click',function(e){var b=e.target.closest('[data-igr-copy]');if(!b)return;copyRecipe(b.dataset.igrCopy,b);});}
addCss();install();wire();
window.dispatchEvent(new CustomEvent('watchdog:integration-recipes-ready',{detail:{count:recipes.length}}));
})();
