(function(){
'use strict';
const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rank=p=>({standard:0,agent:1,pro:2,pro_plus:3,teams:4,developer:5}[p]??0);
const human=v=>String(v||'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
function count(d,key){return Number(d?.summary?.[key]||0)}
function reason(d){const bits=[];if(count(d,'new_count'))bits.push(`${count(d,'new_count')} new`);if(count(d,'strengthened_count'))bits.push(`${count(d,'strengthened_count')} strengthened`);if(count(d,'weakened_count'))bits.push(`${count(d,'weakened_count')} weakened`);if(count(d,'evidence_change_count'))bits.push(`${count(d,'evidence_change_count')} evidence change${count(d,'evidence_change_count')===1?'':'s'}`);if(count(d,'removed_count'))bits.push(`${count(d,'removed_count')} removed`);return bits.join(' · ')||'Scheduled review completed'}
function todayItems(digests){const seen=new Set(),items=[];for(const d of digests){for(const q of (Array.isArray(d.recommended_queue)?d.recommended_queue:[])){const pin=String(q.pams_pin||'').trim();if(!pin||seen.has(pin))continue;seen.add(pin);items.push({pin,score:Number(q.score||0),model:d.model_key||'intelligence',date:d.digest_date,reason:reason(d)})}}return items.slice(0,10)}
function render(host,digests,intent){const items=todayItems(digests),confirmed=Boolean(intent?.active_job)&&Number(intent?.confidence||0)>=1;const context=confirmed?`Watchdog is prioritizing this workspace through your confirmed <b>${esc(human(intent.active_job))}</b> research context.`:'Watchdog has no confirmed research objective for this workspace yet. The queue below stays evidence-first and does not guess your purpose.';host.innerHTML=`<section class="wdi-today"><div class="wdi-today-head"><div><span>TODAY</span><h2>What deserves your attention</h2><p>${context}</p></div><a href="/property/data-workbench">Open Workbench <i class="fas fa-arrow-right"></i></a></div>${items.length?`<div class="wdi-today-list">${items.map((x,i)=>`<article><div class="wdi-today-rank">${i+1}</div><div><b>${esc(x.pin)}</b><small>${esc(human(x.model))} · ${esc(x.reason)}</small></div><div class="wdi-today-score"><span>MODEL SCORE</span><b>${Math.round(x.score)}/100</b></div></article>`).join('')}</div><div class="wdi-today-foot"><i class="fas fa-shield-halved"></i><span>This is a governed review queue, not a prediction of seller intent, value, profit, urgency, or outcome. Open the underlying finding before acting.</span></div>`:`<div class="wdi-today-empty"><i class="fas fa-check-circle"></i><div><b>No queued property requires review from the latest digests.</b><span>Watchdog will surface net-new or materially changed governed findings here after scheduled runs complete.</span></div></div>`}</section>`}
async function init(){await Promise.resolve(window.njptrAccessReady);const client=window.NJPTRAccess?.client?.();if(!client)return;const usage=await client.rpc('get_agent_usage');if(rank(usage.data?.plan||'standard')<3)return;const shell=document.querySelector('#wdi-app');if(!shell)return;let host=document.querySelector('#wdi-today');if(!host){host=document.createElement('div');host.id='wdi-today';shell.before(host)}const [digestR,intentR]=await Promise.all([client.from('intelligence_daily_digests').select('model_key,digest_date,recommended_queue,summary,created_at').order('digest_date',{ascending:false}).limit(12),client.from('intelligence_intent_states').select('active_job,confidence,profession,updated_at').eq('context_key','dashboard:research-set').maybeSingle()]);render(host,digestR.data||[],intentR.data||null)}
function boot(){init().catch(()=>{})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,300),{once:true});else setTimeout(boot,300);document.addEventListener('visibilitychange',()=>{if(!document.hidden)boot()});
})();
