(function(){
  'use strict';
  var SB_URL='https://uvkvaxljhhngydvlrzom.supabase.co',KEY='sb_publishable_MYX59qCbK3d-21zDfJqkNw_fvmfnexa',client=null,root=null,summary=null,rows=[];
  function sb(){return client||(client=window.supabase.createClient(SB_URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,flowType:'pkce',storageKey:'sb-uvkvaxljhhngydvlrzom-auth-token'}}));}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function date(v){if(!v)return'Not redeemed';var d=new Date(v);return isNaN(d.getTime())?'Not dated':d.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});}
  function active(row){return row.status==='redeemed'&&row.expires_at&&new Date(row.expires_at)>new Date();}
  function state(row){if(row.status==='issued')return{key:'pending',label:'Pending'};if(active(row))return{key:'active',label:'Active'};return{key:'ended',label:'Ended'};}
  function notice(message,error){var n=document.getElementById('ad-move-note');if(!n)return;n.textContent=message||'';n.classList.toggle('error',!!error);}
  function meter(){var total=Number(summary&&summary.seats_total||0),used=Number(summary&&summary.seats_used||0),remain=Math.max(total-used,0),pct=total?Math.min(100,Math.round(used/total*100)):0;return'<div class="ad-move-meter" style="--move-used:'+pct+'%"><b>'+remain+' / '+total+'</b><span>Move seats remaining this month</span><i></i></div>';}
  function rowHtml(row){var s=state(row),when=row.status==='issued'?'Issued '+date(row.issued_at):(active(row)?'Active until '+date(row.expires_at):'Last term '+date(row.expires_at||row.issued_at));var buttons='';if(active(row))buttons+='<button class="ad-move-action secondary" type="button" data-move-properties="'+esc(row.id)+'">Saved properties</button>';if(row.status!=='issued')buttons+='<button class="ad-move-action" type="button" data-move-renew="'+esc(row.id)+'" data-move-email="'+esc(row.recipient_email)+'">Renew 90 days</button>';return'<div class="ad-move-row" data-move-row="'+esc(row.id)+'"><div class="ad-move-client"><b>'+esc(row.recipient_email)+'</b><small>Client email</small></div><div><span class="ad-move-state '+s.key+'">'+s.label+'</span></div><div class="ad-move-date">'+esc(when)+'</div><div class="ad-move-actions">'+buttons+'</div><div class="ad-move-properties" id="ad-move-properties-'+esc(row.id)+'" hidden></div></div>';}
  function render(){if(!root)return;var total=Number(summary&&summary.seats_total||0);root.innerHTML='<div class="ad-move-head"><div><span>WATCHDOG MOVE · CLIENT BENEFIT</span><h2>Give a client 90 days of Watchdog.</h2><p>Sponsored Move seats are included with eligible professional plans. Seats reset monthly and do not roll over.</p></div>'+meter()+'</div>'+(total?'<form class="ad-move-form" id="ad-move-form"><input id="ad-move-email" type="email" required autocomplete="email" placeholder="client@example.com" aria-label="Client email"><button type="submit">Issue Move seat</button></form>':'<p class="ad-move-note error">Your current plan does not include sponsored Move seats.</p>')+'<p class="ad-move-note" id="ad-move-note"></p><div class="ad-move-rows">'+(rows.length?rows.map(rowHtml).join(''):'<div class="ad-move-row"><div class="ad-move-client"><b>No Move seats issued yet</b><small>Your monthly allotment is ready when a client needs it.</small></div></div>')+'</div><p class="ad-move-privacy"><i class="fas fa-shield-halved"></i><span>Watchdog only exposes saved-property identity and location through an active sponsored relationship. Browsing history, notes and unrelated activity stay private.</span></p>';wire();}
  function load(){var c=sb();return Promise.all([c.rpc('get_my_watchdog_move_seat_summary'),c.from('watchdog_move_sponsorships').select('id,recipient_email,status,issued_at,redeemed_at,expires_at,recipient_user_id,renewal_of').order('issued_at',{ascending:false}).limit(50)]).then(function(results){if(results[0].error)throw results[0].error;if(results[1].error)throw results[1].error;summary=Array.isArray(results[0].data)&&results[0].data.length?results[0].data[0]:{seats_total:0,seats_used:0,seats_remaining:0};rows=results[1].data||[];render();}).catch(function(e){console.error('Move seats failed',e);if(root)root.innerHTML='<p class="ad-control-loading">Move seats are unavailable right now.</p>';});}
  function issue(email,renewal){var c=sb();notice(renewal?'Renewing client Move access…':'Issuing Move seat…');return c.rpc('issue_watchdog_move_seat',{p_recipient_email:email,p_renewal_of:renewal||null}).then(function(r){if(r.error)throw r.error;notice(renewal?'Another 90-day Move seat was issued.':'Move seat issued. Existing Watchdog users activate immediately; new users claim it when they sign in with this email.');return load();}).catch(function(e){console.error('Move seat issue failed',e);notice(e&&e.message?e.message:'Could not issue Move seat.',true);});}
  function properties(id){var c=sb(),box=document.getElementById('ad-move-properties-'+id);if(!box)return;if(!box.hidden){box.hidden=true;return;}box.hidden=false;box.innerHTML='<span>Loading saved properties…</span>';c.rpc('get_watchdog_move_sponsored_client_properties',{p_sponsorship_id:id}).then(function(r){if(r.error)throw r.error;var items=r.data||[];box.innerHTML=items.length?'<ul>'+items.map(function(p){return'<li><b>'+esc(p.address||'Saved property')+'</b>'+esc([p.city||p.town,p.county&&p.county+' County',p.zip].filter(Boolean).join(' · '))+'</li>';}).join('')+'</ul>':'<span>This client has not saved a property yet.</span>';}).catch(function(e){console.error('Move sponsored properties failed',e);box.innerHTML='<span>Saved properties could not be loaded.</span>';});}
  function wire(){var form=document.getElementById('ad-move-form');if(form)form.addEventListener('submit',function(e){e.preventDefault();var input=document.getElementById('ad-move-email'),email=String(input&&input.value||'').trim().toLowerCase();if(!email)return;var btn=form.querySelector('button');if(btn)btn.disabled=true;issue(email,null).finally(function(){if(btn)btn.disabled=false;if(input)input.value='';});});root.querySelectorAll('[data-move-properties]').forEach(function(btn){btn.addEventListener('click',function(){properties(btn.dataset.moveProperties);});});root.querySelectorAll('[data-move-renew]').forEach(function(btn){btn.addEventListener('click',function(){if(!confirm('Use another Move seat to give '+btn.dataset.moveEmail+' another 90 days?'))return;btn.disabled=true;issue(btn.dataset.moveEmail,btn.dataset.moveRenew).finally(function(){btn.disabled=false;});});});}
  function init(){var capacity=document.getElementById('ad-capacity');if(!capacity||!window.supabase)return;root=document.createElement('section');root.className='ad-move-seats';root.id='ad-move-seats';root.setAttribute('aria-label','Watchdog Move client seats');capacity.insertAdjacentElement('afterend',root);root.innerHTML='<p class="ad-control-loading">Loading Watchdog Move seats…</p>';sb().auth.getSession().then(function(r){if(r.data&&r.data.session)return load();root.hidden=true;});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
