(function(){
'use strict';
if(window.__WATCHDOG_NEWSLETTER_STUDIO__)return;window.__WATCHDOG_NEWSLETTER_STUDIO__=true;
var db=null,state={crm:null,email:null,catalog:{tags:[],segments:[]}},busy=false;
var $=function(id){return document.getElementById(id);};
function show(id,on){var n=$(id);if(n)n.hidden=!on;}
function text(id,v){var n=$(id);if(n)n.textContent=v==null?'':String(v);}
function fmt(v){if(!v)return'Not yet';var d=new Date(v);return Number.isFinite(d.getTime())?d.toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'Not yet';}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c];});}
function note(id,msg,error){var n=$(id);if(!n)return;n.textContent=msg||'';n.classList.toggle('error',!!error);}
function setBusy(on){busy=!!on;document.querySelectorAll('#nl-workspace button,#nl-workspace input,#nl-workspace select,#nl-workspace textarea').forEach(function(n){n.disabled=busy;});}
async function call(fn,action,body){
  if(!db)throw new Error('Watchdog connection unavailable');
  var s=await db.auth.getSession(),session=s&&s.data&&s.data.session,token=session&&session.access_token;if(!token)throw new Error('Sign in required');
  var rt=window.NJPTRSupabaseRuntime;if(!rt||!rt.url||!rt.key)throw new Error('Watchdog runtime unavailable');
  var gatewayAction=action;if(action==='status')gatewayAction=fn==='newsletter-beta-crm'?'crm.status':'email.status';
  var r=await fetch(rt.url+'/functions/v1/tmp-boldtrail-probe',{method:'POST',headers:{apikey:rt.key,authorization:'Bearer '+token,'content-type':'application/json'},body:JSON.stringify(Object.assign({action:gatewayAction},body||{}))});
  var d=await r.json().catch(function(){return{};});if(!r.ok)throw Object.assign(new Error(d.error||'Request failed'),{status:r.status,data:d});return d;
}
function status(node,value){if(!node)return;node.className='nl-status';node.textContent=value;if(/connected|ready/i.test(value))node.classList.add('good');else if(/sync|pending/i.test(value))node.classList.add('warn');else if(/error|attention|degraded/i.test(value))node.classList.add('bad');}
function countSuppressed(e){e=e||{};return Number(e.suppressed||0)+Number(e.unsubscribed||0)+Number(e.bounced||0)+Number(e.complained||0)+Number(e.invalid||0);}
function render(){
  var crm=state.crm||{},cp=crm.provider||null,email=state.email||{},ep=email.provider||null;
  status($('nl-crm-status'),cp?(cp.sync_status==='error'?'Needs attention':cp.sync_status==='syncing'?'Syncing':'Connected'):'Not connected');
  show('nl-crm-connect',!cp);show('nl-crm-connected',!!cp);text('nl-crm-total',Number(crm.total_contacts||email.crm&&email.crm.total_contacts||0).toLocaleString());text('nl-crm-email',Number(crm.contacts_with_email||email.crm&&email.crm.contacts_with_email||0).toLocaleString());text('nl-crm-last',cp?fmt(cp.last_success_at):'Not yet');text('nl-pipe-crm',cp?'BoldTrail connected':'Connect BoldTrail');
  status($('nl-kit-status'),ep?(ep.status==='degraded'?'Degraded':'Connected'):'Not connected');show('nl-kit-connect',!ep||ep.status==='revoked');show('nl-kit-connected',!!ep&&ep.status!=='revoked');text('nl-pipe-email',ep&&ep.status!=='revoked'?'Kit connected':'Connect Kit');
  if(ep){text('nl-kit-account',ep.account_name||'Kit');text('nl-kit-plan',ep.plan_type?ep.plan_type+' plan':'');}
  var sender=(email.senders||[]).find(function(s){return s.is_default;})||(email.senders||[])[0];text('nl-default-sender',sender?((sender.display_name?sender.display_name+' · ':'')+sender.email_address):'Set a sender');text('nl-sender-verification',sender?String(sender.verification_status||'declared').replace(/_/g,' '):'');
  var linked=Number(email.linked_contacts||0),elig=email.eligibility||{},eligible=Number(elig.eligible||0),suppressed=countSuppressed(elig);text('nl-aud-crm',Number(email.crm&&email.crm.contacts_with_email||crm.contacts_with_email||0).toLocaleString());text('nl-aud-linked',linked.toLocaleString());text('nl-aud-eligible',eligible.toLocaleString());text('nl-aud-suppressed',suppressed.toLocaleString());text('nl-pipe-audience',linked?linked.toLocaleString()+' linked':'Not reconciled');
  renderBroadcasts(email.recent_broadcasts||[]);$('nl-reconcile').disabled=busy||!cp||!ep;
}
function renderBroadcasts(rows){var body=$('nl-broadcasts');if(!body)return;body.innerHTML=rows.map(function(r){var t=r.target_definition||{},aud=t.all_subscribers?'All Kit subscribers':((t.type||'target')+' '+((t.ids||[]).join(', ')));return'<tr><td><b>'+esc(r.subject)+'</b></td><td><span class="nl-pill '+esc(r.status||'draft')+'">'+esc(r.status||'draft')+'</span></td><td>'+esc(r.from_email||'Kit default')+'</td><td>'+esc(aud)+'</td><td>'+esc(r.send_at?fmt(r.send_at):'Draft only')+'</td><td>'+esc(fmt(r.updated_at))+'</td></tr>';}).join('');show('nl-broadcasts-empty',!rows.length);}
async function loadStatus(){var results=await Promise.allSettled([call('newsletter-beta-crm','status'),call('marketing-email-provider','status')]);var denied=results.some(function(r){return r.status==='rejected'&&r.reason&&r.reason.status===403;});if(denied){show('nl-denied',true);show('nl-workspace',false);return false;}if(results[0].status==='rejected')throw results[0].reason;if(results[1].status==='rejected')throw results[1].reason;state.crm=results[0].value;state.email=results[1].value;show('nl-workspace',true);show('nl-denied',false);render();return true;}
async function loadCatalog(){if(!state.email||!state.email.provider||state.email.provider.status!=='connected')return;try{state.catalog=await call('marketing-email-provider','kit.catalog');renderTargets();}catch(err){note('nl-broadcast-note','Kit tags/segments could not be loaded: '+err.message,true);}}
function renderTargets(){var type=$('nl-target-type').value,row=$('nl-target-row'),select=$('nl-target-id');show('nl-target-row',!!type);if(!type){select.innerHTML='';return;}var list=type==='tag'?(state.catalog.tags||[]):(state.catalog.segments||[]);select.innerHTML='<option value="">Choose '+type+'</option>'+list.map(function(x){return'<option value="'+esc(x.id)+'">'+esc(x.name)+'</option>';}).join('');}
async function refresh(){if(busy)return;setBusy(true);show('nl-error',false);try{var ok=await loadStatus();if(ok)await loadCatalog();}catch(err){show('nl-error',true);text('nl-error-copy',err.message);}finally{setBusy(false);render();}}
async function connectCrm(e){e.preventDefault();if(busy)return;var token=$('nl-crm-token').value.trim();if(token.length<20){note('nl-crm-note','Enter a valid BoldTrail token.',true);return;}setBusy(true);note('nl-crm-note','Validating with BoldTrail…');try{await call('newsletter-beta-crm','boldtrail.connect',{api_token:token,external_account_label:$('nl-crm-label').value.trim()});$('nl-crm-token').value='';note('nl-crm-note','BoldTrail connected. First sync queued.');await loadStatus();setTimeout(function(){refresh();},3000);}catch(err){$('nl-crm-token').value='';note('nl-crm-note',err.message,true);}finally{setBusy(false);render();}}
async function syncCrm(){if(busy)return;setBusy(true);note('nl-crm-status-note','Sync queued…');try{await call('newsletter-beta-crm','boldtrail.sync');note('nl-crm-status-note','BoldTrail sync queued.');setTimeout(function(){refresh();},3000);}catch(err){note('nl-crm-status-note',err.message,true);}finally{setBusy(false);render();}}
async function disconnectCrm(){if(busy||!confirm('Disconnect BoldTrail from this Watchdog login and remove its normalized CRM context?'))return;setBusy(true);try{await call('newsletter-beta-crm','boldtrail.disconnect');state.crm=null;state.email=null;await loadStatus();}catch(err){note('nl-crm-status-note',err.message,true);}finally{setBusy(false);render();}}
async function connectKit(e){e.preventDefault();if(busy)return;var key=$('nl-kit-key').value.trim();if(key.length<16){note('nl-kit-note','Enter a valid Kit V4 API key.',true);return;}setBusy(true);note('nl-kit-note','Validating with Kit…');try{await call('marketing-email-provider','kit.connect',{api_key:key,sender_name:$('nl-sender-name').value.trim(),sender_email:$('nl-sender-email').value.trim()});$('nl-kit-key').value='';note('nl-kit-note','Kit connected.');await loadStatus();await loadCatalog();}catch(err){$('nl-kit-key').value='';note('nl-kit-note',err.message,true);}finally{setBusy(false);render();}}
async function healthKit(){if(busy)return;setBusy(true);note('nl-kit-status-note','Checking Kit…');try{var d=await call('marketing-email-provider','kit.health');note('nl-kit-status-note','Kit connection checked '+fmt(d.checked_at)+'.');await loadStatus();}catch(err){note('nl-kit-status-note',err.message,true);}finally{setBusy(false);render();}}
async function saveSender(e){e.preventDefault();if(busy)return;setBusy(true);try{await call('marketing-email-provider','sender.save',{display_name:$('nl-new-sender-name').value.trim(),email_address:$('nl-new-sender-email').value.trim(),is_default:true});$('nl-new-sender-name').value='';$('nl-new-sender-email').value='';note('nl-kit-status-note','Default sender saved.');await loadStatus();}catch(err){note('nl-kit-status-note',err.message,true);}finally{setBusy(false);render();}}
async function disconnectKit(){if(busy||!confirm('Disconnect Kit from this Watchdog login? Existing drafts in Kit are not deleted.'))return;setBusy(true);try{await call('marketing-email-provider','kit.disconnect');state.email=null;state.catalog={tags:[],segments:[]};await loadStatus();}catch(err){note('nl-kit-status-note',err.message,true);}finally{setBusy(false);render();}}
async function reconcile(){if(busy)return;setBusy(true);$('nl-reconcile-result').hidden=false;text('nl-reconcile-result','Comparing BoldTrail email addresses with subscribers already in Kit…');try{var d=await call('marketing-email-provider','kit.reconcile_existing');text('nl-reconcile-result',d.matched.toLocaleString()+' existing Kit subscribers matched to '+d.unique_crm_emails.toLocaleString()+' unique BoldTrail email addresses. CRM-only addresses were not uploaded.');await loadStatus();}catch(err){text('nl-reconcile-result',err.message);}finally{setBusy(false);render();}}
function safePreview(html){var t=document.createElement('template');t.innerHTML=String(html||'');t.content.querySelectorAll('script,iframe,object,embed').forEach(function(n){n.remove();});t.content.querySelectorAll('*').forEach(function(n){Array.from(n.attributes).forEach(function(a){if(/^on/i.test(a.name)||/^javascript:/i.test(a.value))n.removeAttribute(a.name);});});return t.innerHTML;}
function updatePreview(){text('nl-preview-subject',$('nl-subject').value.trim()||'Your subject');text('nl-preview-preheader',$('nl-preview').value.trim()||'Preview text will appear here.');$('nl-email-preview').innerHTML=safePreview($('nl-content').value)||'<p>Your newsletter preview will appear as you type.</p>';}
async function createBroadcast(e){e.preventDefault();if(busy)return;if(!state.email||!state.email.provider){note('nl-broadcast-note','Connect Kit first.',true);return;}var targetType=$('nl-target-type').value,targetId=Number($('nl-target-id').value||0),sender=(state.email.senders||[]).find(function(s){return s.is_default;})||(state.email.senders||[])[0];setBusy(true);note('nl-broadcast-note','Creating a draft in Kit…');try{var d=await call('marketing-email-provider','broadcast.create',{subject:$('nl-subject').value.trim(),preview_text:$('nl-preview').value.trim(),content:$('nl-content').value,email_address:sender&&sender.email_address||null,target_type:targetType||null,target_mode:'all',target_ids:targetType&&targetId?[targetId]:[]});note('nl-broadcast-note','Kit draft created'+(d.broadcast&&d.broadcast.external_broadcast_id?' · #'+d.broadcast.external_broadcast_id:'')+'. Review it in Kit before sending.');$('nl-broadcast-form').reset();renderTargets();updatePreview();await loadStatus();}catch(err){note('nl-broadcast-note',err.message,true);}finally{setBusy(false);render();}}
async function boot(){try{db=window.NJPTRSupabaseRuntime&&window.NJPTRSupabaseRuntime.createClient?window.NJPTRSupabaseRuntime.createClient():null;if(!db)throw new Error('Watchdog runtime unavailable');var s=await db.auth.getSession(),session=s&&s.data&&s.data.session;if(!session){show('nl-signin',true);return;}show('nl-signin',false);await refresh();}catch(err){show('nl-error',true);text('nl-error-copy',err.message);}}
document.addEventListener('submit',function(e){if(e.target.id==='nl-crm-form')connectCrm(e);else if(e.target.id==='nl-kit-form')connectKit(e);else if(e.target.id==='nl-sender-form')saveSender(e);else if(e.target.id==='nl-broadcast-form')createBroadcast(e);});
document.addEventListener('click',function(e){var id=e.target.closest('button')&&e.target.closest('button').id;if(id==='nl-refresh')refresh();else if(id==='nl-crm-sync')syncCrm();else if(id==='nl-crm-disconnect')disconnectCrm();else if(id==='nl-kit-health')healthKit();else if(id==='nl-kit-disconnect')disconnectKit();else if(id==='nl-reconcile')reconcile();});
document.addEventListener('change',function(e){if(e.target.id==='nl-target-type')renderTargets();});['nl-subject','nl-preview','nl-content'].forEach(function(id){document.addEventListener('input',function(e){if(e.target.id===id)updatePreview();});});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
