(function(){
'use strict';
if(window.__WATCHDOG_OAUTH_CONSENT__)return;window.__WATCHDOG_OAUTH_CONSENT__=true;
var db=null,authorizationId='',details=null,user=null,canAuthorize=false;
var $=function(id){return document.getElementById(id);};
function show(id,on){var n=$(id);if(n)n.hidden=!on;}
function note(id,text,error){var n=$(id);if(!n)return;n.textContent=text||'';n.classList.toggle('error',!!error);}
function normalizePlan(v){return String(v||'standard').toLowerCase().replace('pro+','pro_plus');}
function fail(message){show('oauth-loading',false);show('oauth-signin',false);show('oauth-consent',false);$('oauth-error-text').textContent=message||'The authorization request is invalid or expired.';show('oauth-error',true);}
function returnHere(){return location.origin+location.pathname+'?authorization_id='+encodeURIComponent(authorizationId);}
async function planAllowed(){try{var entitlement=await db.rpc('get_my_entitlement'),row=Array.isArray(entitlement.data)?entitlement.data[0]:entitlement.data,p=normalizePlan(row&&row.plan_tier);if(p==='developer'||p==='pro_plus'||p==='teams')return true;var profile=await db.from('profiles').select('account_role').eq('id',user.id).maybeSingle();return profile.data&&String(profile.data.account_role).toLowerCase()==='developer';}catch(_){return false;}}
function clientName(d){return d&&((d.client&&d.client.name)||d.client_name||d.application_name)||'Connected application';}
function scopeText(d){var s=d&&(d.scope||d.scopes);if(Array.isArray(s))return s.join(' ');return String(s||'email');}
function redirectText(d){return String(d&&((d.client&&d.client.redirect_uri)||d.redirect_uri||d.redirect_url)||'Registered OAuth callback');}
async function renderConsent(){show('oauth-loading',false);show('oauth-signin',false);show('oauth-error',false);show('oauth-consent',true);var name=clientName(details);$('oauth-client-name').textContent=name;$('oauth-client-inline').textContent=name;$('oauth-user-email').textContent=user.email||'Watchdog account';$('oauth-scopes').textContent=scopeText(details);$('oauth-redirect').textContent=redirectText(details);canAuthorize=await planAllowed();show('oauth-plan-warning',!canAuthorize);$('oauth-approve').disabled=!canAuthorize;}
async function loadRequest(){var res=await db.auth.oauth.getAuthorizationDetails(authorizationId);if(res.error)throw res.error;details=res.data||{};var who=await db.auth.getUser();user=who&&who.data&&who.data.user;if(!user){show('oauth-loading',false);show('oauth-signin',true);return;}await renderConsent();}
async function google(){note('oauth-signin-note','Opening Google sign-in…',false);var r=await db.auth.signInWithOAuth({provider:'google',options:{redirectTo:returnHere()}});if(r.error)note('oauth-signin-note',r.error.message,true);}
async function email(e){e.preventDefault();var value=$('oauth-email').value.trim();if(!value)return;note('oauth-signin-note','Sending secure sign-in link…',false);var r=await db.auth.signInWithOtp({email:value,options:{emailRedirectTo:returnHere()}});if(r.error)note('oauth-signin-note',r.error.message,true);else note('oauth-signin-note','Check your email, then return here using the sign-in link.',false);}
async function decide(approve){var approveButton=$('oauth-approve'),denyButton=$('oauth-deny');approveButton.disabled=true;denyButton.disabled=true;note('oauth-consent-note',approve?'Authorizing connection…':'Canceling authorization…',false);try{var r=approve?await db.auth.oauth.approveAuthorization(authorizationId):await db.auth.oauth.denyAuthorization(authorizationId);if(r.error)throw r.error;var redirect=r.data&&(r.data.redirect_url||r.data.url);if(!redirect)throw new Error('Authorization server did not return a redirect URL.');location.assign(redirect);}catch(err){approveButton.disabled=!canAuthorize;denyButton.disabled=false;note('oauth-consent-note',err.message||'Authorization could not be completed.',true);}}
async function boot(){authorizationId=new URL(location.href).searchParams.get('authorization_id')||'';if(!authorizationId){fail('Missing authorization_id. Start the connection from the requesting application.');return;}try{db=window.NJPTRSupabaseRuntime&&window.NJPTRSupabaseRuntime.createClient?window.NJPTRSupabaseRuntime.createClient():null;if(!db||!db.auth||!db.auth.oauth)throw new Error('Watchdog OAuth is not available in this browser session.');await loadRequest();}catch(err){fail(err&&err.message||'The authorization request is invalid, expired, or the OAuth server is not enabled.');}}
document.addEventListener('click',function(e){if(e.target.closest('#oauth-google'))google();if(e.target.closest('#oauth-approve'))decide(true);if(e.target.closest('#oauth-deny'))decide(false);});document.addEventListener('submit',function(e){if(e.target&&e.target.id==='oauth-email-form')email(e);});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
