(function(){
  'use strict';
  var user=null, lastFocus=null;
  function q(id){return document.getElementById(id);}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function recent(){try{return JSON.parse(localStorage.getItem('watchdogRecentProperties')||'[]').slice(0,4);}catch(e){return[];}}
  function setRecent(r){if(!r||!r.address)return;var rows=recent().filter(function(x){return x.pin!==r.pin&&x.address!==r.address;});rows.unshift({address:r.address,town:r.town||'',pin:r.pin||'',at:new Date().toISOString()});try{localStorage.setItem('watchdogRecentProperties',JSON.stringify(rows.slice(0,8)));}catch(e){}renderProfile();}
  function displayName(){var m=user&&user.user_metadata||{};return m.full_name||m.name||(user&&user.email||'').split('@')[0]||'Your account';}
  function avatar(){var m=user&&user.user_metadata||{};return m.avatar_url||m.picture||'';}
  function renderTrigger(){var b=q('wd-profile-trigger');if(!b)return;var a=avatar();b.innerHTML=a?'<img src="'+esc(a)+'" alt="">':'<i class="fas fa-user"></i><span>'+(user?'Account':'Sign in')+'</span>';b.setAttribute('aria-label',user?'Open account menu':'Sign in or open account menu');}
  function renderProfile(){var host=q('wd-profile-content');if(!host)return;var rs=recent();var recentHtml=rs.length?rs.map(function(x){return '<a class="wd-public-link" href="/property/?address='+encodeURIComponent(x.address)+'"><i class="fas fa-clock-rotate-left"></i><span>'+esc(x.address)+'<small>'+esc(x.town||'New Jersey')+'</small></span><i class="fas fa-chevron-right"></i></a>';}).join(''):'<div class="wd-public-recent-empty">Properties you open will appear here on this device.</div>';if(!user){host.innerHTML='<button class="wd-public-signin" type="button" onclick="WatchdogPublicNav.signIn()"><i class="fab fa-google"></i> Sign in to Watchdog</button><div class="wd-public-section"><span class="wd-public-label">Recently viewed</span><div class="wd-public-recent">'+recentHtml+'</div></div><div class="wd-public-section"><a class="wd-public-link" href="/property/account.html"><i class="fas fa-circle-user"></i><span>Account details</span><i class="fas fa-chevron-right"></i></a></div>';return;}var a=avatar();host.innerHTML='<div class="wd-public-account">'+(a?'<img src="'+esc(a)+'" alt="">':'<div class="avatar">'+esc(displayName().charAt(0).toUpperCase())+'</div>')+'<div><b>'+esc(displayName())+'</b><span>'+esc(user.email||'')+'</span></div></div><div class="wd-public-section"><a class="wd-public-link" href="/property/dashboard.html"><i class="fas fa-house"></i><span>Your home &amp; properties</span><i class="fas fa-chevron-right"></i></a><a class="wd-public-link" href="/property/dashboard.html#profile"><i class="fas fa-user-gear"></i><span>Profile &amp; benefits</span><i class="fas fa-chevron-right"></i></a><a class="wd-public-link" href="/property/account.html"><i class="fas fa-credit-card"></i><span>Account &amp; billing</span><i class="fas fa-chevron-right"></i></a></div><div class="wd-public-section"><span class="wd-public-label">Recently viewed</span><div class="wd-public-recent">'+recentHtml+'</div></div><div class="wd-public-section"><button class="wd-public-link" style="border:0;background:transparent;width:100%;cursor:pointer" type="button" onclick="WatchdogPublicNav.signOut()"><i class="fas fa-arrow-right-from-bracket"></i><span>Sign out</span></button></div>';}
  function open(which){close();lastFocus=document.activeElement;var sheet=q(which==='profile'?'wd-profile-sheet':'wd-main-sheet'),back=q('wd-public-backdrop');if(!sheet||!back)return;sheet.classList.add('open');sheet.setAttribute('aria-hidden','false');back.classList.add('open');document.body.classList.add('wd-public-menu-open');var c=sheet.querySelector('.wd-public-close');if(c)c.focus();}
  function close(){['wd-main-sheet','wd-profile-sheet'].forEach(function(id){var e=q(id);if(e){e.classList.remove('open');e.setAttribute('aria-hidden','true');}});var b=q('wd-public-backdrop');if(b)b.classList.remove('open');document.body.classList.remove('wd-public-menu-open');if(lastFocus&&lastFocus.focus)lastFocus.focus();lastFocus=null;}
  function signIn(){close();if(typeof window.plSignInPrompt==='function')window.plSignInPrompt();}
  function signOut(){close();if(typeof window.plSignOut==='function')window.plSignOut();}
  function setUser(u){user=u||null;renderTrigger();renderProfile();}
  (function scopeVerifiedSales(){if(window.__watchdogSalesFetchScoped)return;window.__watchdogSalesFetchScoped=true;var original=window.fetch.bind(window),district='';function rememberFromParcel(response){try{response.clone().json().then(function(data){var f=data&&data.features&&data.features[0],a=f&&f.attributes||{},pin=String(a.PAMS_PIN||'');var d=pin.replace(/\D/g,'').slice(0,4);if(d.length===4){district=d;try{sessionStorage.setItem('watchdogCurrentDistrict',d);}catch(_){}}}).catch(function(){});}catch(_){}}try{district=sessionStorage.getItem('watchdogCurrentDistrict')||'';}catch(_){}window.fetch=function(input,init){var url=typeof input==='string'?input:(input&&input.url)||'';if(/Parcels_Composite_NJ_WM|Framework\/Cadastral/i.test(url)){return original(input,init).then(function(r){rememberFromParcel(r);return r;});}var m=url.match(/\/property\/sales-([a-z-]+)\.json(?:\?|$)/i);if(m&&district&&/^\d{4}$/.test(district)){var scoped='/api/sales-by-district?county='+encodeURIComponent(m[1].toLowerCase())+'&district='+encodeURIComponent(district);return original(scoped,init).then(function(r){if(r.ok)return r;district='';try{sessionStorage.removeItem('watchdogCurrentDistrict');}catch(_){}return original(input,init);}).catch(function(){return original(input,init);});}return original(input,init);};})();
  function runAddressFromQuery(){var params;try{params=new URLSearchParams(window.location.search||'');}catch(e){return;}var address=(params.get('address')||'').trim();if(!address)return;var attempts=0;function handoff(){attempts+=1;var input=q('pl-addr');if(input&&typeof window.plLookup==='function'){input.value=address;window.plLookup();try{var clean=new URL(window.location.href);clean.searchParams.delete('address');window.history.replaceState({},document.title,clean.pathname+clean.search+clean.hash);}catch(e){}return;}if(attempts<80)window.setTimeout(handoff,100);}handoff();}
  function loadFlood(){if(window.WatchdogFlood||document.getElementById('wd-flood-script'))return;var s=document.createElement('script');s.id='wd-flood-script';s.src='/property/js/flood-intelligence.js';s.defer=true;document.head.appendChild(s);}
  function init(){renderTrigger();renderProfile();loadFlood();document.addEventListener('keydown',function(e){if(e.key==='Escape')close();});runAddressFromQuery();}
  window.WatchdogPublicNav={open:open,close:close,setUser:setUser,remember:setRecent,signIn:signIn,signOut:signOut};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
