(function(){'use strict';
var URL='https://uvkvaxljhhngydvlrzom.supabase.co',KEY='sb_publishable_MYX59qCbK3d-21zDfJqkNw_fvmfnexa',client,user,properties=[],prefs=[],events=[],scoreHistory=[],days=183,type='all';
var $=function(id){return document.getElementById(id)};
function sb(){return client||(client=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,flowType:'pkce',storageKey:'sb-uvkvaxljhhngydvlrzom-auth-token'}}));}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function date(v){return new Date(v).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});}
function safeUrl(v){try{var u=new URL(v);return /^https?:$/.test(u.protocol)?u.href:'';}catch(_){return'';}}
function icon(t){return({appeal_deadline:'fa-scale-balanced',score_change:'fa-chart-line',assessment_change:'fa-building-columns',tax_change:'fa-receipt',permit_change:'fa-helmet-safety',deed_change:'fa-file-signature',environment_change:'fa-leaf',evidence_change:'fa-diagram-project',market_change:'fa-house-signal',municipal_change:'fa-city'}[t]||'fa-satellite-dish');}
function setSummary(){var unread=events.filter(function(e){return !e.read_at;}).length,material=events.filter(function(e){return e.severity==='action';}).length;$('pulse-summary').innerHTML='<article><span>UNREAD</span><b>'+unread+'</b><small>New changes</small></article><article><span>FOLLOWED</span><b>'+properties.length+'</b><small>Saved properties</small></article><article><span>ACTION SIGNALS</span><b>'+material+'</b><small>Higher-priority events</small></article>';}
function filteredEvents(){var cutoff=days?Date.now()-days*86400000:0;return events.filter(function(e){return(!cutoff||new Date(e.occurred_at).getTime()>=cutoff)&&(type==='all'||e.event_type===type);});}
function delta(e){if(e.old_value==null&&e.new_value==null)return'';var arrow=e.delta_numeric>0?'↑':e.delta_numeric<0?'↓':'→',cl=e.delta_numeric>0?'up':e.delta_numeric<0?'down':'flat';return'<div class="pulse-delta '+cl+'"><span>'+esc(e.old_value||'—')+'</span><b>'+arrow+'</b><strong>'+esc(e.new_value||'—')+'</strong></div>';}
function drawEvents(){var root=$('pulse-events'),list=filteredEvents(),button=$('pulse-read-all');button.hidden=!events.some(function(e){return !e.read_at;});if(!list.length){root.innerHTML='<div class="pulse-empty"><b>No changes in this view.</b>Try another time range or signal type. New verified events will appear here with their source and timestamp.</div>';return;}root.innerHTML=list.map(function(e){var source=safeUrl(e.source_url);return'<article class="pulse-event" data-severity="'+esc(e.severity)+'"><div class="pulse-event-icon"><i class="fas '+icon(e.event_type)+'"></i></div><div class="pulse-event-body"><div class="pulse-event-title"><h3>'+esc(e.title)+'</h3>'+(e.minimum_plan&&e.minimum_plan!=='standard'?'<em>'+esc(e.minimum_plan==='pro_plus'?'PRO+':'PRO')+'</em>':'')+'</div><p>'+esc(e.summary)+'</p>'+delta(e)+'<div class="pulse-meta"><time>'+date(e.occurred_at)+(e.read_at?' · Read':' · New')+'</time>'+(e.marker_id?'<a href="/property/marker?id='+encodeURIComponent(e.marker_id)+'">'+esc(e.marker_id)+'</a>':'')+(source?'<a href="'+esc(source)+'" target="_blank" rel="noopener noreferrer">Source <i class="fas fa-arrow-up-right-from-square"></i></a>':'')+'</div></div></article>';}).join('');}
function card(p,pref){pref=pref||{alert_score:true,alert_tax:true,alert_assessment:true,alert_deadline:true,paused:false};var opts=[['alert_score','Scores','fa-chart-line'],['alert_tax','Tax','fa-receipt'],['alert_assessment','Assessment','fa-building-columns'],['alert_deadline','Deadlines','fa-calendar-day']];return'<article class="pulse-property" data-pin="'+esc(p.pams_pin)+'"><div class="pulse-property-head"><div><h3>'+esc(p.nickname||p.address)+'</h3><small>'+esc([p.town,p.county].filter(Boolean).join(' · ')||'Saved property')+'</small></div><label class="pulse-pause"><input type="checkbox" data-pref="paused" '+(pref.paused?'checked':'')+'> Pause</label></div><div class="pulse-options">'+opts.map(function(o){return'<label class="pulse-option"><input type="checkbox" data-pref="'+o[0]+'" '+(pref[o[0]]?'checked':'')+'><i class="fas '+o[2]+'"></i>'+o[1]+'</label>';}).join('')+'</div><div class="pulse-saving" aria-live="polite"></div></article>';}
function drawProperties(){var by={};prefs.forEach(function(p){by[p.pams_pin]=p;});$('pulse-properties').innerHTML=properties.length?properties.map(function(p){return card(p,by[p.pams_pin]);}).join(''):'<div class="pulse-empty"><b>No saved properties yet.</b>Add a property to start a history.</div>';var sel=$('pulse-property-select');sel.innerHTML=properties.map(function(p){return'<option value="'+esc(p.pams_pin)+'">'+esc(p.nickname||p.address)+'</option>';}).join('');if(!properties.length){sel.innerHTML='<option>No saved properties</option>';sel.disabled=true;} }
function bindPreferences(){ $('pulse-properties').addEventListener('change',function(ev){var input=ev.target;if(!input.matches('[data-pref]'))return;var c=input.closest('.pulse-property'),pin=c.dataset.pin,data={user_id:user.id,pams_pin:pin,updated_at:new Date().toISOString()};c.querySelectorAll('[data-pref]').forEach(function(f){data[f.dataset.pref]=f.checked;});var note=c.querySelector('.pulse-saving');note.textContent='Saving…';sb().from('property_alert_preferences').upsert(data,{onConflict:'user_id,pams_pin'}).then(function(r){note.textContent=r.error?'Could not save':'Saved';setTimeout(function(){if(note.textContent==='Saved')note.textContent='';},1600);});});}
function trendPath(points){if(!points.length)return'';var vals=points.map(function(p){return+p.score;}),lo=Math.min.apply(null,vals),hi=Math.max.apply(null,vals);return points.map(function(p,i){var x=16+i/Math.max(1,points.length-1)*468,y=112-((+p.score-lo)/((hi-lo)||1))*86;return(i?'L':'M')+x.toFixed(1)+' '+y.toFixed(1);}).join(' ');}
function drawTrend(){var root=$('pulse-trend-chart');if(!scoreHistory.length){root.innerHTML='<div class="pulse-trend-empty"><i class="fas fa-chart-line"></i><span>No trusted Watchdog Score history has been captured for this property yet.</span></div>';return;}var first=+scoreHistory[0].score,last=+scoreHistory[scoreHistory.length-1].score,d=last-first,arr=d>0?'↑':d<0?'↓':'→',cl=d>0?'up':d<0?'down':'flat';root.innerHTML='<div class="pulse-ticker"><strong>'+last+'</strong><span class="'+cl+'">'+arr+' '+Math.abs(d).toFixed(1)+' since '+date(scoreHistory[0].observed_at)+'</span><small>'+scoreHistory.length+' trusted observations</small></div><svg viewBox="0 0 500 130" preserveAspectRatio="none" aria-label="Watchdog Score historical trend"><path d="'+trendPath(scoreHistory)+'"></path></svg>';}
function loadTrend(pin){if(!pin){scoreHistory=[];drawTrend();return;}sb().from('score_observations').select('score,observed_at,observed_on').eq('pams_pin',pin).eq('marker_id','watchdog.score').order('observed_at',{ascending:true}).limit(500).then(function(r){scoreHistory=r.data||[];drawTrend();});}
function bindFilters(){ $('pulse-ranges').addEventListener('click',function(e){var b=e.target.closest('[data-days]');if(!b)return;days=+b.dataset.days;$('pulse-ranges').querySelectorAll('button').forEach(function(x){x.classList.toggle('on',x===b);});drawEvents();});$('pulse-types').addEventListener('click',function(e){var b=e.target.closest('[data-type]');if(!b)return;type=b.dataset.type;$('pulse-types').querySelectorAll('button').forEach(function(x){x.classList.toggle('on',x===b);});drawEvents();});$('pulse-property-select').addEventListener('change',function(){loadTrend(this.value);});}
function init(){if(!window.supabase)return;sb().auth.getUser().then(function(r){user=r.data&&r.data.user;if(!user)throw Error('signed out');return Promise.all([sb().from('saved_properties').select('pams_pin,address,nickname,town,county').order('updated_at',{ascending:false}),sb().from('property_alert_preferences').select('*'),sb().from('property_update_events').select('*').order('occurred_at',{ascending:false}).limit(500)]);}).then(function(v){properties=v[0].data||[];prefs=v[1].data||[];events=v[2].data||[];$('pulse-gate').hidden=true;$('pulse-app').hidden=false;setSummary();drawEvents();drawProperties();bindPreferences();bindFilters();loadTrend(properties[0]&&properties[0].pams_pin);$('pulse-read-all').onclick=function(){var ids=events.filter(function(e){return!e.read_at;}).map(function(e){return e.id;});if(!ids.length)return;sb().from('property_update_events').update({read_at:new Date().toISOString()}).in('id',ids).then(function(){events.forEach(function(e){if(ids.indexOf(e.id)>=0)e.read_at=new Date().toISOString();});setSummary();drawEvents();});};}).catch(function(){$('pulse-gate').hidden=false;});}
init();})();
