(function(){
'use strict';
var deferredPrompt;
function isiOS(){return /iphone|ipad|ipod/i.test(navigator.userAgent);}
function standalone(){return window.matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;}
function note(text){var n=document.createElement('div');n.className='wd-install-note';n.innerHTML='<span><i class="fas fa-mobile-screen-button"></i><b>Add Watchdog to your Home Screen</b><small>'+text+'</small></span><button type="button" aria-label="Close">×</button>';n.querySelector('button').onclick=function(){n.remove();};document.body.appendChild(n);return n;}
function show(){if(standalone()||sessionStorage.getItem('wdInstallDismissed'))return;var n=note(isiOS()?'In Safari, tap Share, then “Add to Home Screen.”':'Install for a focused, app-like workspace.');if(!isiOS()){n.querySelector('span').onclick=function(){if(!deferredPrompt)return;deferredPrompt.prompt();deferredPrompt.userChoice.finally(function(){deferredPrompt=null;n.remove();});};}n.querySelector('button').onclick=function(){sessionStorage.setItem('wdInstallDismissed','1');n.remove();};}
function loadWhyWatchdog(){var page=String(document.body&&document.body.getAttribute('data-sidebar-page')||'');if(page!=='dashboard'&&page!=='agent-desk')return;if(window.WatchdogWhy||document.getElementById('watchdog-why-script'))return;var s=document.createElement('script');s.id='watchdog-why-script';s.src='/property/js/watchdog-why.js';s.defer=true;document.head.appendChild(s);}
function loadScript(src,key){if(document.querySelector('script['+key+']'))return;var s=document.createElement('script');s.src=src;s.defer=true;s.setAttribute(key,'true');document.body.appendChild(s);}
function loadPropertyHomeFirstImpression(){var page=String(document.body&&document.body.getAttribute('data-sidebar-page')||'');if(page!=='home')return;/* Prevent the legacy Google Street View hero before the premium loader can request it. */window.__WATCHDOG_HOME_HERO_INTELLIGENCE__=true;loadScript('/property/js/dashboard/home/home-property-first-impression.js?v=20260827d','data-watchdog-home-first-impression');loadScript('/property/js/dashboard/home/home-property-first-impression-compact.js?v=20260827e','data-watchdog-home-first-impression-compact');}
function loadPageEnhancements(){var page=String(document.body&&document.body.getAttribute('data-sidebar-page')||'');if(page!=='integrations')return;loadScript('/property/js/integrations-command-center.js','data-watchdog-integrations-command-center');loadScript('/property/js/integrations-recipes.js','data-watchdog-integration-recipes');loadScript('/property/js/integrations-policy-feedback.js','data-watchdog-integration-policy-feedback');loadScript('/property/js/integrations-policy-comparison.js','data-watchdog-integration-policy-comparison');}
window.addEventListener('beforeinstallprompt',function(event){event.preventDefault();deferredPrompt=event;show();});
loadPropertyHomeFirstImpression();
loadPageEnhancements();
window.addEventListener('load',function(){if('serviceWorker' in navigator)navigator.serviceWorker.register('/property/sw.js',{scope:'/property/'}).catch(function(){});if(isiOS())window.setTimeout(show,1300);loadPropertyHomeFirstImpression();loadWhyWatchdog();loadPageEnhancements();});
})();
