(function(){
'use strict';
function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(ch){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch];});}
function fmtDate(value){try{return new Intl.DateTimeFormat('en-US',{month:'long',day:'numeric',year:'numeric'}).format(new Date(value+'T12:00:00'));}catch(_){return value;}}
function stateError(message){var state=document.getElementById('recap-state');if(!state)return;state.classList.add('wr-error');state.innerHTML='<i class="fas fa-triangle-exclamation"></i><b>Unable to load recap</b><span>'+esc(message||'The protected recap could not be loaded.')+'</span>';}
async function token(){var client=window.NJPTRAccess&&window.NJPTRAccess.client?window.NJPTRAccess.client():null;if(!client)throw new Error('Authentication client unavailable.');var result=await client.auth.getSession();var session=result&&result.data&&result.data.session;if(!session||!session.access_token)throw new Error('Developer session unavailable.');return session.access_token;}
async function getRows(date){var t=await token();var url='/api/watchdog-recaps'+(date?'?date='+encodeURIComponent(date):'');var response=await fetch(url,{headers:{Authorization:'Bearer '+t},cache:'no-store'});var data=await response.json().catch(function(){return {};});if(!response.ok)throw new Error(data.error||'Recap request failed.');return Array.isArray(data.rows)?data.rows:[];}
function archive(rows){var app=document.getElementById('recap-app'),state=document.getElementById('recap-state'),list=document.getElementById('recap-list'),count=document.getElementById('recap-count');if(!app||!list)return;if(count)count.textContent=rows.length+' daily '+(rows.length===1?'record':'records');list.innerHTML=rows.length?rows.map(function(row){return '<article class="wr-row"><div class="wr-date">'+esc(fmtDate(row.recap_date))+'</div><div><h3>'+esc(row.headline)+'</h3><p>'+esc(row.executive_summary)+'</p></div><a href="/property/logs/recap/'+esc(row.recap_date)+'/">Open recap <i class="fas fa-arrow-right"></i></a></article>';}).join(''):'<div class="wr-empty">No daily recaps have been recorded yet.</div>';if(state)state.hidden=true;app.hidden=false;}
var sectionMeta={completed:['Completed','fa-circle-check'],in_progress:['In progress','fa-spinner'],started:['Started','fa-play'],remaining:['Left to finish','fa-list-check'],todo:['Today\'s ranked TODO','fa-bullseye']};
function renderItems(key,items){if(!Array.isArray(items)||!items.length)return '';var meta=sectionMeta[key]||[key,'fa-circle'];var todo=key==='todo';return '<section class="wr-section '+(todo?'wr-todo':'')+'"><div class="wr-section-head"><span class="wr-section-icon"><i class="fas '+meta[1]+'"></i></span><h2>'+meta[0]+'</h2></div><div class="wr-items">'+items.map(function(item,index){if(todo){return '<article class="wr-item"><span class="wr-rank">'+esc(item.rank||index+1)+'</span><div><b>'+esc(item.item||'')+'</b></div></article>';}var label=item.area||item.priority||'';return '<article class="wr-item"><div class="wr-item-top">'+(label?'<span class="wr-area">'+esc(label)+'</span>':'')+'<b>'+esc(item.title||item.item||'')+'</b></div>'+(item.detail?'<p>'+esc(item.detail)+'</p>':'')+'</article>';}).join('')+'</div></section>';}
function detail(row){var state=document.getElementById('recap-state'),head=document.getElementById('recap-detail-head'),detail=document.getElementById('recap-detail');document.getElementById('recap-headline').textContent=row.headline||'';document.getElementById('recap-summary').textContent=row.executive_summary||'';var chips=document.getElementById('recap-system-chips');if(chips){var systems=row.systems&&typeof row.systems==='object'?row.systems:{};chips.innerHTML=Object.keys(systems).map(function(k){return '<span class="wr-chip">'+esc(k.replace(/_/g,' '))+': '+esc(systems[k])+'</span>';}).join('');}detail.innerHTML=['completed','in_progress','started','remaining','todo'].map(function(key){return renderItems(key,row[key]);}).join('');if(state)state.hidden=true;if(head)head.hidden=false;detail.hidden=false;}
async function run(){try{if(window.njptrAccessReady)await window.njptrAccessReady;var mode=document.body.getAttribute('data-recap-mode')||'archive';var date=document.body.getAttribute('data-recap-date')||'';var rows=await getRows(mode==='detail'?date:'');if(mode==='detail'){if(!rows.length)throw new Error('Recap not found.');detail(rows[0]);}else archive(rows);}catch(error){stateError(error&&error.message?error.message:'Unable to load recap.');}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
})();
