(function(){'use strict';
var SBURL='https://uvkvaxljhhngydvlrzom.supabase.co',KEY='sb_publishable_MYX59qCbK3d-21zDfJqkNw_fvmfnexa',client,user,properties=[],cases=[],activities={},active=null;
var $=function(id){return document.getElementById(id)};
function sb(){return client||(client=window.supabase.createClient(SBURL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,flowType:'pkce',storageKey:'sb-uvkvaxljhhngydvlrzom-auth-token'}}));}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function label(v){return String(v||'general').replace(/_/g,' ').replace(/\b\w/g,function(c){return c.toUpperCase();});}
function money(v){var n=+v;return Number.isFinite(n)&&n?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n):'—';}
function date(v){return v?new Date(v).toLocaleString('en-US',{month:'short',day:'numeric',year:'numeric'}):'—';}
function drawCases(){var q=String($('wb-filter').value||'').toLowerCase(),list=cases.filter(function(c){return !q||[c.title,c.property_address,c.municipality,c.case_type].join(' ').toLowerCase().indexOf(q)>=0;});$('wb-cases').innerHTML=list.length?list.map(function(c){return'<button class="wb-case '+(active&&active.id===c.id?'on':'')+'" data-case="'+esc(c.id)+'" type="button"><b>'+esc(c.title)+'</b><span>'+esc(c.property_address||c.municipality||'Research file')+'</span><em>'+esc(label(c.case_type))+'</em></button>';}).join(''):'<div class="wb-empty"><p>No matching case files.</p></div>';}
function snapshot(c){var s=c.evidence_snapshot||{};return'<div class="wb-snapshot"><article><span>ASSESSED</span><b>'+money(s.assessed)+'</b></article><article><span>ANNUAL TAX</span><b>'+money(s.tax)+'</b></article><article><span>WATCHDOG VALUE</span><b>'+money(s.watchdog_value)+'</b></article><article><span>SNAPSHOT</span><b>'+esc(s.captured_at?date(s.captured_at):'At case creation')+'</b></article></div>';}
function markerLinks(ids){ids=Array.isArray(ids)?ids:[];return ids.length?'<div class="wb-marker-list">'+ids.map(function(id){return'<a href="/property/marker.html?id='+encodeURIComponent(id)+'">'+esc(id)+'</a>';}).join('')+'</div>':'<p class="wb-form-note">No markers pinned yet.</p>';}
function activity(c){var rows=activities[c.id]||[];return rows.length?'<div class="wb-activity">'+rows.slice(0,12).map(function(a){return'<article><b>'+esc(label(a.event_type))+'</b><span>'+date(a.created_at)+'</span></article>';}).join('')+'</div>':'<p class="wb-form-note">Activity starts when the case is created.</p>';}
function render(){if(!active){$('wb-detail').innerHTML='<div class="wb-empty"><i class="fas fa-folder-open"></i><h2>Choose a case to begin</h2><p>Or create one from a saved property. Your notes, markers and evidence snapshot stay private to your account.</p></div>';drawCases();return;}var c=active,markers=Array.isArray(c.pinned_marker_ids)?c.pinned_marker_ids:[];$('wb-detail').innerHTML='<div class="wb-file-head"><div><span class="wb-kicker">'+esc(label(c.case_type))+' · '+esc(label(c.status))+'</span><h2>'+esc(c.title)+'</h2><p>'+esc([c.property_address,c.municipality].filter(Boolean).join(' · '))+'</p></div><div class="wb-file-actions"><button class="wb-secondary" data-wb-action="print" type="button"><i class="fas fa-print"></i> Print / PDF</button><button class="wb-secondary" data-wb-action="export" type="button"><i class="fas fa-file-arrow-down"></i> Export</button></div></div>'+snapshot(c)+'<div class="wb-grid"><article class="wb-card"><h3>Working notes</h3><label>Status<select id="wb-status">'+['research','review','ready','active','closed','archived'].map(function(v){return'<option value="'+v+'" '+(c.status===v?'selected':'')+'>'+label(v)+'</option>';}).join('')+'</select></label><label>Case notes<textarea id="wb-notes" placeholder="Facts, questions, client instructions, follow-up…">'+esc(c.notes||'')+'</textarea></label><label>Pinned marker IDs<input id="wb-markers" value="'+esc(markers.join(', '))+'" placeholder="watchdog.score, property.assessed…"></label>'+markerLinks(markers)+'<div class="wb-save-row"><button class="wb-primary" data-wb-action="save" type="button">Save case</button><span class="wb-save-note" id="wb-save-note"></span></div></article><aside><article class="wb-card"><h3>Evidence path</h3><p>Use the property report to inspect the full Evidence Graph, then pin the marker IDs that support your professional conclusion.</p><div class="wb-links"><a href="/property/home.html?pin='+encodeURIComponent(c.pams_pin||'')+'#sec-diligence"><i class="fas fa-diagram-project"></i> Open Evidence Graph</a><a href="/property/pulse.html"><i class="fas fa-wave-square"></i> Review change history</a><a href="/property/data-center.html"><i class="fas fa-table-cells-large"></i> Open Data Center</a></div></article><article class="wb-card" style="margin-top:18px"><h3>Case activity</h3>'+activity(c)+'</article></aside></div>';drawCases();}
function loadActivity(id){return sb().from('professional_case_activity').select('id,event_type,payload,created_at').eq('case_id',id).order('created_at',{ascending:false}).limit(50).then(function(r){activities[id]=r.data||[];});}
function log(c,type,payload){return sb().from('professional_case_activity').insert({case_id:c.id,user_id:user.id,event_type:type,payload:payload||{}}).then(function(){return loadActivity(c.id);});}
function select(id){active=cases.find(function(c){return c.id===id;})||null;if(!active){render();return;}loadActivity(id).finally(render);}
function modal(open){$('wb-modal').hidden=!open;document.body.style.overflow=open?'hidden':'';if(open){var p=properties[0];$('wb-title').value=p?(p.address+' professional file'):'';$('wb-form-note').textContent='';}}
function snapshotFor(p){return{assessed:p.assessed||null,tax:p.last_year_tax||null,effective_rate:p.effective_rate||null,watchdog_value:p.watchdog_value||null,block:p.block||null,lot:p.lot||null,town:p.town||null,county:p.county||null,captured_at:new Date().toISOString()};}
function createCase(){var pin=$('wb-property').value,p=properties.find(function(x){return x.pams_pin===pin;}),title=$('wb-title').value.trim();if(!p||!title){$('wb-form-note').textContent='Choose a saved property and give the case a name.';return;}$('wb-create').disabled=true;var row={user_id:user.id,pams_pin:p.pams_pin,case_type:$('wb-type').value,status:'research',title:title,property_address:p.address||'',municipality:p.town||'',profession:$('wb-profession').value,notes:'',pinned_marker_ids:[],evidence_snapshot:snapshotFor(p)};sb().from('professional_cases').insert(row).select().single().then(function(r){if(r.error)throw r.error;cases.unshift(r.data);active=r.data;return log(active,'created',{workflow:active.case_type});}).then(function(){modal(false);render();}).catch(function(e){$('wb-form-note').textContent=e.message||'Could not create case.';}).finally(function(){$('wb-create').disabled=false;});}
function save(){if(!active)return;var status=$('wb-status').value,notes=$('wb-notes').value,markers=$('wb-markers').value.split(',').map(function(x){return x.trim();}).filter(Boolean).filter(function(x,i,a){return a.indexOf(x)===i;}).slice(0,80),previousStatus=active.status;var update={status:status,notes:notes,pinned_marker_ids:markers,updated_at:new Date().toISOString()};$('wb-save-note').textContent='Saving…';sb().from('professional_cases').update(update).eq('id',active.id).select().single().then(function(r){if(r.error)throw r.error;Object.assign(active,r.data);var i=cases.findIndex(function(c){return c.id===active.id;});if(i>=0)cases[i]=active;return log(active,previousStatus!==status?'status':'note',{status:status,marker_count:markers.length});}).then(function(){$('wb-save-note').textContent='Saved';render();}).catch(function(e){$('wb-save-note').textContent=e.message||'Could not save';});}
function exportCase(){if(!active)return;var payload={exported_at:new Date().toISOString(),case:active,activity:activities[active.id]||[]};var blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=globalThis.URL.createObjectURL(blob);a.download='watchdog-case-'+active.id+'.json';a.click();setTimeout(function(){globalThis.URL.revokeObjectURL(a.href);},1000);log(active,'export',{format:'json'});}
function bind(){$('wb-new').onclick=function(){modal(true);};$('wb-close').onclick=function(){modal(false);};$('wb-create').onclick=createCase;$('wb-filter').oninput=drawCases;$('wb-cases').onclick=function(e){var b=e.target.closest('[data-case]');if(b)select(b.dataset.case);};$('wb-detail').onclick=function(e){var b=e.target.closest('[data-wb-action]');if(!b)return;if(b.dataset.wbAction==='save')save();if(b.dataset.wbAction==='print'){log(active,'export',{format:'print'});window.print();}if(b.dataset.wbAction==='export')exportCase();};$('wb-modal').addEventListener('click',function(e){if(e.target===$('wb-modal'))modal(false);});document.addEventListener('keydown',function(e){if(e.key==='Escape'&&!$('wb-modal').hidden)modal(false);});}
function init(){if(!window.supabase)return;Promise.resolve(window.njptrAccessReady).then(function(){return sb().auth.getUser();}).then(function(r){user=r.data&&r.data.user;if(!user)throw Error('Sign in required');return Promise.all([sb().from('saved_properties').select('pams_pin,address,nickname,town,county,block,lot,assessed,last_year_tax,effective_rate,watchdog_value').order('updated_at',{ascending:false}),sb().from('professional_cases').select('*').order('updated_at',{ascending:false})]);}).then(function(v){properties=v[0].data||[];cases=v[1].data||[];$('wb-property').innerHTML=properties.length?properties.map(function(p){return'<option value="'+esc(p.pams_pin)+'">'+esc(p.nickname||p.address)+'</option>';}).join(''):'<option value="">No saved properties</option>';$('wb-app').hidden=false;bind();drawCases();var wanted=new URLSearchParams(location.search).get('case');if(wanted)select(wanted);}).catch(function(e){console.warn('Workbench could not initialize',e);});}
init();})();
