import { createClient } from 'npm:@supabase/supabase-js@2.95.0';
const URL=Deno.env.get('SUPABASE_URL')!,ANON=Deno.env.get('SUPABASE_ANON_KEY')!,SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,PCM='https://v3.pcmintegrations.com';
const ORIGINS=new Set(['https://njpropertytaxrelief.com','https://www.njpropertytaxrelief.com']);
function cors(req:Request){const o=req.headers.get('origin')||'';return{'Access-Control-Allow-Origin':ORIGINS.has(o)?o:'https://njpropertytaxrelief.com','Access-Control-Allow-Headers':'authorization, apikey, content-type, x-client-info','Access-Control-Allow-Methods':'POST, OPTIONS','Cache-Control':'private, no-store','Vary':'Origin'}}
function reply(req:Request,status:number,body:unknown){return new Response(JSON.stringify(body),{status,headers:{...cors(req),'Content-Type':'application/json; charset=utf-8'}})}
function clean(v:unknown,n=400){return String(v??'').trim().replace(/[\u0000-\u001f]/g,'').slice(0,n)}
function tokenFrom(d:any){return clean(d?.token??d?.accessToken??d?.access_token??d?.code,4000)}
async function login(){const key=Deno.env.get('PCM_SANDBOX_API_KEY')||'',secret=Deno.env.get('PCM_API_SECRET')||Deno.env.get('PCM_SANDBOX_API_SECRET')||'';if(!key||!secret)throw new Error('PCM sandbox credentials are incomplete');const r=await fetch(PCM+'/auth/login',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify({apiKey:key,apiSecret:secret})});const text=await r.text();let d:any={};try{d=JSON.parse(text)}catch{}const token=tokenFrom(d);if(!r.ok||!token)throw new Error(`PCM sandbox login failed (${r.status})`);return token}
function rows(d:any,keys:string[]){if(Array.isArray(d))return d;for(const k of keys)if(Array.isArray(d?.[k]))return d[k];if(Array.isArray(d?.data))return d.data;return[]}
function pick(o:any,names:string[]){for(const n of names){const v=o?.[n];if(v!==undefined&&v!==null&&String(v)!=='')return v}return null}
function normalize(o:any,type:string){return{type,id:clean(pick(o,['orderID','orderId','order_id','batchID','batchId','batch_id','id']),100)||null,ext_ref:clean(pick(o,['extRefNbr','extRef','externalReference','external_reference','reference']),160)||null,status:clean(pick(o,['status','orderStatus','order_status','batchStatus','batch_status','state']),100)||null,created_at:pick(o,['createdAt','created_at','dateCreated','createdDate'])||null,updated_at:pick(o,['updatedAt','updated_at','dateUpdated','modifiedDate'])||null}}
async function pcmGet(token:string,path:string){const r=await fetch(PCM+path,{headers:{Authorization:`Bearer ${token}`,Accept:'application/json'}});const text=await r.text();let d:any={};try{d=JSON.parse(text)}catch{}return{ok:r.ok,status:r.status,data:d}}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors(req)});if(req.method!=='POST')return reply(req,405,{error:'Method not allowed'});const origin=req.headers.get('origin')||'';if(origin&&!ORIGINS.has(origin))return reply(req,403,{error:'Origin not allowed'});const auth=req.headers.get('Authorization')||'';if(!auth.startsWith('Bearer '))return reply(req,401,{error:'Sign in required'});const uc=createClient(URL,ANON,{global:{headers:{Authorization:auth}},auth:{persistSession:false}}),admin=createClient(URL,SERVICE,{auth:{persistSession:false}});const{data:{user},error:ue}=await uc.auth.getUser();if(ue||!user)return reply(req,401,{error:'Session could not be verified'});const access=await uc.rpc('marketing_studio_bootstrap');if(access.error)return reply(req,403,{error:'Marketing Studio access required'});const body=await req.json().catch(()=>({})),campaignId=clean(body.campaign_id,80);if(!campaignId)return reply(req,400,{error:'campaign_id is required'});const c=await admin.from('marketing_campaigns').select('id,name').eq('id',campaignId).eq('user_id',user.id).maybeSingle();if(c.error||!c.data)return reply(req,404,{error:'Campaign not found'});const jobsQ=await admin.from('marketing_provider_jobs').select('id,status,provider_job_id,provider_status,idempotency_key,created_at,submitted_at').eq('campaign_id',campaignId).eq('user_id',user.id).eq('provider_key','pcm').order('created_at',{ascending:false});const jobs=jobsQ.data||[];let token='';try{token=await login()}catch(e){return reply(req,502,{error:clean(e instanceof Error?e.message:e,300)})}const [ordersR,batchesR]=await Promise.all([pcmGet(token,'/order'),pcmGet(token,'/batch')]);const orders=rows(ordersR.data,['orders','orderList','items']).map((x:any)=>normalize(x,'order')),batches=rows(batchesR.data,['batches','batchList','items']).map((x:any)=>normalize(x,'batch'));const identifiers=new Set<string>();for(const j of jobs){if(j.provider_job_id)identifiers.add(String(j.provider_job_id));if(j.idempotency_key)identifiers.add(String(j.idempotency_key))}const prefix=`WD-${campaignId.slice(0,8)}`;const relevant=(x:any)=>Boolean((x.id&&identifiers.has(String(x.id)))||(x.ext_ref&&(identifiers.has(String(x.ext_ref))||String(x.ext_ref).startsWith(prefix))));const matchedOrders=orders.filter(relevant),matchedBatches=batches.filter(relevant);return reply(req,200,{environment:'sandbox',read_only:true,campaign_id:campaignId,local_jobs:jobs,pcm:{order_http_status:ordersR.status,batch_http_status:batchesR.status,orders_count:orders.length,batches_count:batches.length,matched_orders:matchedOrders,matched_batches:matchedBatches},checked_at:new Date().toISOString()})});