(function(){
'use strict';
var W=window.WatchdogAgentWorkflows;if(!W)return;var db=W.client(),user=null,packs=[],selected=null,picked=null;
var $=function(s){return document.querySelector(s)};
function snapshot(row){return{pams_pin:row.pams_pin||null,address:row.address||'',city:row.city||row.town||'',town:row.town||row.city||'',county:row.county||'',zip:row.zip||'',block:row.block||'',lot:row.lot||'',qualifier:row.qualifier||'',prop_class:row.prop_class||'',year_built:row.year_built||null,acres:row.acres||null,building_desc:row.building_desc||'',land_value:row.land_value||null,improvement_value:row.improvement_value||null,assessed_value:row.assessed_value||null,last_year_tax:row.last_year_tax||null,effective_rate:row.effective_rate||null,last_sale_price:row.last_sale_price||null,last_sale_year:row.last_sale_year||null,permit_review:row.permit_review||null,municipal_requirements:Array.isArray(row.municipal_requirements)?row.municipal_requirements:[]}}
function renderList(){var host=$('#lp-list');if(!packs.length){host.innerHTML='<div class="ag-empty">No listing prep packs yet. Create one from a property address.</div>';return}host.innerHTML=packs.map(function(p){return'<button type="button" data-id="'+W.esc(p.id)+'" class="'+(selected&&selected.id===p.id?'active':'')+'"><strong>'+W.esc(p.address)+'</strong><small>'+W.esc([p.client_label,p.city||p.municipality,p.status].filter(Boolean).join(' · '))+'</small></button>'}).join('')}
function req(s,key){var rows=Array.isArray(s&&s.municipal_requirements)?s.municipal_requirements:[];return rows.find(function(x){return x&&x.requirement_key===key})||null}
function permitCopy(p){if(!p)return{copy:'Not checked for this saved prep pack.',tag:'Review'};if(p.status==='available')return{copy:String(Number(p.verification_candidates)||0)+' permit/certificate verification candidate'+(Number(p.verification_candidates)===1?'':'s')+' observed in the NJ DCA lifecycle source. '+(p.latest_candidate_permit_date?'Latest candidate permit date: '+p.latest_candidate_permit_date+'. ': '')+'This is not a legal determination that a permit is open.',tag:Number(p.verification_candidates)>0?'Verify':'Source checked'};if(p.status==='no_rows')return{copy:'No NJ DCA rows were returned for the exact parcel keys. This is coverage information only, not proof that no permit issue exists.',tag:'Source checked'};if(p.status==='missing_key')return{copy:'Exact municipality/block/lot keys were not available for the NJ DCA permit lookup.',tag:'Verify'};return{copy:'The NJ DCA permit source could not be checked when this prep pack was created.',tag:'Retry'}}
function reqCopy(r){if(!r)return{copy:'No municipality-specific requirement record was attached to this prep pack. Verify directly with the municipality.',tag:'Verify'};var when=r.last_verified_at?(' Last verified '+W.date(r.last_verified_at)+'.'):'';return{copy:(r.title||'Municipal requirement')+' · '+String(r.requirement_state||'verify').replace(/_/g,' ')+'.'+when+(r.source_excerpt?' '+r.source_excerpt:''),tag:String(r.requirement_state||'verify').replace(/_/g,' ')}}
function renderDiligence(s){var panel=$('#lp-diligence');if(!panel)return;panel.hidden=false;var pc=permitCopy(s.permit_review),res=reqCopy(req(s,'resale_cco')),fire=reqCopy(req(s,'smoke_fire_cert'));$('#lp-permit-status').textContent=pc.copy;$('#lp-permit-tag').textContent=pc.tag;$('#lp-resale-status').textContent=res.copy;$('#lp-resale-tag').textContent=res.tag;$('#lp-fire-status').textContent=fire.copy;$('#lp-fire-tag').textContent=fire.tag}
function renderDetail(){var detail=$('#lp-detail'),check=$('#lp-checklist'),diligence=$('#lp-diligence');if(!selected){detail.hidden=true;check.hidden=true;if(diligence)diligence.hidden=true;return}detail.hidden=false;check.hidden=false;var s=selected.property_snapshot||{};$('#lp-title').textContent=selected.address;$('#lp-assessed').textContent=W.money(s.assessed_value);$('#lp-tax').textContent=W.money(s.last_year_tax);$('#lp-sale').textContent=s.last_sale_price?W.money(s.last_sale_price)+(s.last_sale_year?' · '+s.last_sale_year:''):'—';$('#lp-built').textContent=s.year_built||'—';$('#lp-edit-client').value=selected.client_label||'';$('#lp-edit-status').value=selected.status||'draft';$('#lp-edit-notes').value=selected.notes||'';$('#lp-property-link').href=W.propertyUrl(s);renderDiligence(s);renderList()}
async function load(){try{user=await W.auth();var r=await db.from('agent_listing_packs').select('*').eq('user_id',user.id).order('updated_at',{ascending:false});if(r.error)throw r.error;packs=r.data||[];var wanted=new URLSearchParams(location.search).get('id');selected=packs.find(function(p){return p.id===wanted})||packs[0]||null;renderList();renderDetail()}catch(e){W.showNote($('#lp-create-note'),e.message,'error')}}
async function search(){var q=W.clean($('#lp-search').value),host=$('#lp-results');if(q.length<3){host.hidden=true;return}$('#lp-search-btn').disabled=true;try{var rows=await W.propertySearch(q,8);host.hidden=false;host.innerHTML=rows.length?rows.map(function(r,i){return'<button class="ag-result" type="button" data-pick="'+i+'"><span><b>'+W.esc(r.address)+'</b><small>'+W.esc(W.place(r))+'</small></span><span class="ag-pill">Select</span></button>'}).join(''):'<div class="ag-empty">No matching Watchdog property record found. Try a shorter street address.</div>';host._rows=rows}catch(e){host.hidden=false;host.innerHTML='<div class="ag-empty">Property search is unavailable right now.</div>'}finally{$('#lp-search-btn').disabled=false}}
function pick(i){var rows=$('#lp-results')._rows||[];picked=rows[Number(i)]||null;if(!picked)return;$('#lp-create-form').hidden=false;$('#lp-picked-address').textContent=picked.address;$('#lp-picked-place').textContent=W.place(picked);$('#lp-client').focus()}
async function create(e){e.preventDefault();if(!picked||!user)return;var payload={user_id:user.id,address:picked.address,city:picked.city||picked.town||null,municipality:picked.town||picked.city||null,county:picked.county||null,postal_code:picked.zip||null,pams_pin:picked.pams_pin||null,client_label:W.clean($('#lp-client').value)||null,notes:W.clean($('#lp-notes').value)||null,status:$('#lp-status').value,property_snapshot:snapshot(picked),checklist:{tax_assessment:true,permits:true,municipal_resale:true,brokerage_cma:true},last_opened_at:new Date().toISOString()};W.showNote($('#lp-create-note'),'Saving…');var r=await db.from('agent_listing_packs').insert(payload).select('*').single();if(r.error){W.showNote($('#lp-create-note'),r.error.message,'error');return}packs.unshift(r.data);selected=r.data;$('#lp-create-form').hidden=true;$('#lp-results').hidden=true;$('#lp-search').value='';picked=null;renderDetail();W.showNote($('#lp-create-note'),'Prep pack created.','ok')}
async function save(){if(!selected)return;var patch={client_label:W.clean($('#lp-edit-client').value)||null,status:$('#lp-edit-status').value,notes:W.clean($('#lp-edit-notes').value)||null,updated_at:new Date().toISOString(),last_opened_at:new Date().toISOString()};W.showNote($('#lp-save-note'),'Saving…');var r=await db.from('agent_listing_packs').update(patch).eq('id',selected.id).eq('user_id',user.id).select('*').single();if(r.error){W.showNote($('#lp-save-note'),r.error.message,'error');return}selected=r.data;var i=packs.findIndex(function(p){return p.id===selected.id});if(i>=0)packs[i]=selected;renderDetail();W.showNote($('#lp-save-note'),'Saved.','ok')}
async function del(){if(!selected||!confirm('Delete this listing prep pack?'))return;var id=selected.id,r=await db.from('agent_listing_packs').delete().eq('id',id).eq('user_id',user.id);if(r.error){W.showNote($('#lp-save-note'),r.error.message,'error');return}packs=packs.filter(function(p){return p.id!==id});selected=packs[0]||null;renderDetail()}
async function startTx(){if(!selected)return;var s=selected.property_snapshot||{};var row={user_id:user.id,address:selected.address,city:selected.city||s.city||null,state:'NJ',postal_code:selected.postal_code||s.zip||null,municipality:selected.municipality||s.town||null,county:selected.county||s.county||null,block:s.block||null,lot:s.lot||null,qualifier:s.qualifier||null,pams_pin:selected.pams_pin||s.pams_pin||null,side:'seller',status:'under_contract',client_label:selected.client_label||null,notes:'Started from Agent Listing Prep Pack.'};$('#lp-start-tx').disabled=true;try{var r=await db.from('transaction_workspaces').insert(row).select('id').single();if(r.error)throw r.error;location.href='/transaction/?tx='+encodeURIComponent(r.data.id)}catch(e){W.showNote($('#lp-save-note'),e.message,'error');$('#lp-start-tx').disabled=false}}
document.addEventListener('click',function(e){var b=e.target.closest('[data-id]');if(b){selected=packs.find(function(p){return p.id===b.dataset.id})||null;renderDetail()}var p=e.target.closest('[data-pick]');if(p)pick(p.dataset.pick)});
$('#lp-search-btn').addEventListener('click',search);$('#lp-search').addEventListener('keydown',function(e){if(e.key==='Enter'){e.preventDefault();search()}});$('#lp-create-form').addEventListener('submit',create);$('#lp-save').addEventListener('click',save);$('#lp-delete').addEventListener('click',del);$('#lp-start-tx').addEventListener('click',startTx);$('#lp-new').addEventListener('click',function(){$('#lp-search').focus();scrollTo({top:0,behavior:'smooth'})});
load();
})();