import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.95.0";

type Obj=Record<string,any>;
type AddressEvidence={source:string;hint:string;street:string;city:string;region:string;zip:string;full:string;norm:string;enrichment?:Obj|null};
type ParcelMatch={parcel:Obj;address:AddressEvidence;matchPolicy:string;geocodeScore?:number|null};
const BOLDTRAIL_CONTACT=(id:string)=>`https://api.kvcore.com/v2/public/contact/${encodeURIComponent(id)}`;
const NJ="https://services2.arcgis.com/XVOqAjTOJ5P6ngMu/arcgis/rest/services/Parcels_Composite_NJ_WM/FeatureServer/0/query";
const NJ_GEOCODE="https://geo.nj.gov/arcgis/rest/services/Tasks/NJ_Geocode/GeocodeServer/findAddressCandidates";
const BATCH_SIZE=20;
const SUFFIX:Record<string,string>={STREET:"ST",ST:"ST",AVENUE:"AVE",AVE:"AVE",ROAD:"RD",RD:"RD",DRIVE:"DR",DR:"DR",LANE:"LN",LN:"LN",COURT:"CT",CT:"CT",BOULEVARD:"BLVD",BLVD:"BLVD",CIRCLE:"CIR",CIR:"CIR",PARKWAY:"PKWY",PKWY:"PKWY",HIGHWAY:"HWY",HWY:"HWY",TERRACE:"TER",TER:"TER",PLACE:"PL",PL:"PL",TRAIL:"TRL",TRL:"TRL",TURNPIKE:"TPKE",TPKE:"TPKE",WAY:"WAY"};
const DIR:Record<string,string>={NORTH:"N",SOUTH:"S",EAST:"E",WEST:"W",N:"N",S:"S",E:"E",W:"W"};
function namedEnv(jsonName:string,legacyName:string){const raw=Deno.env.get(jsonName)||"";if(raw){try{const x=JSON.parse(raw);if(x?.default)return String(x.default)}catch{}}return Deno.env.get(legacyName)||"";}
function clean(v:unknown,max=300){return String(v??"").replace(/[\u0000-\u001f<>]/g,"").trim().slice(0,max);}
function same(a:string,b:string){if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0;}
function escSql(v:string){return v.replace(/'/g,"''");}
function zip5(v:unknown){const m=clean(v,20).match(/\b(\d{5})\b/);return m?m[1]:"";}
function normalizeStreet(v:unknown){let s=clean(v,240).toUpperCase().replace(/&/g," AND ").replace(/[.,']/g," ").replace(/#/g," UNIT ").replace(/\b(APARTMENT|APT|UNIT|STE|SUITE)\b/g," UNIT ").replace(/[^A-Z0-9-]+/g," ").trim();if(!s)return"";let parts=s.split(/\s+/).filter(Boolean);parts=parts.map(p=>SUFFIX[p]||DIR[p]||p);return parts.join(" ").replace(/\bUNIT\s+UNIT\b/g,"UNIT").trim();}
function numberPrefix(v:string){const m=v.match(/^([0-9]+[A-Z-]?)/);return m?m[1]:"";}
function fullAddress(street:string,city:string,state:string,zip:string){return [street,[city,state].filter(Boolean).join(", "),zip].filter(Boolean).join(" ").replace(/\s+/g," ").trim();}
function makeAddress(detail:Obj,prefix:"primary"|"poi"):AddressEvidence|null{const street=clean(detail?.[`${prefix}_address`],220);if(!street)return null;const city=clean(detail?.[`${prefix}_city`],120),region=clean(detail?.[`${prefix}_state`],20).toUpperCase(),zip=zip5(detail?.[`${prefix}_zip`]);return{source:`boldtrail.${prefix}_address`,hint:prefix==="poi"?"property_interest":"contact_address",street,city,region,zip,full:fullAddress(street,city,region,zip),norm:normalizeStreet(street),enrichment:null};}
async function fetchJson(url:string,headers:HeadersInit,timeout=12000){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),timeout);try{const r=await fetch(url,{headers,signal:ctl.signal});if(!r.ok)throw new Error(`http_${r.status}`);return await r.json();}finally{clearTimeout(timer);}}
async function contactDetail(token:string,id:string){return await fetchJson(BOLDTRAIL_CONTACT(id),{"Authorization":`Bearer ${token}`,"Accept":"application/json","Content-Type":"application/json"});}
async function parcelCandidates(street:string,zip:string){const norm=normalizeStreet(street),prefix=numberPrefix(norm);if(!norm||!prefix||!/^\d{5}$/.test(zip))return[] as Obj[];const p=new URLSearchParams({f:"json",where:`ZIP5='${escSql(zip)}' AND PROP_LOC LIKE '${escSql(prefix)}%'`,outFields:"PAMS_PIN,PROP_LOC,MUN_NAME,COUNTY,ZIP5",returnGeometry:"false",resultRecordCount:"100"});const data=await fetchJson(`${NJ}?${p.toString()}`,{"Accept":"application/json"},12000);const features=Array.isArray(data?.features)?data.features:[];return features.map((f:Obj)=>f?.attributes||{}).filter((a:Obj)=>normalizeStreet(a.PROP_LOC)===norm&&zip5(a.ZIP5)===zip&&clean(a.PAMS_PIN,120));}
async function enrichMissingZip(a:AddressEvidence){if(a.region!=="NJ"||a.zip||!a.norm||!numberPrefix(a.norm))return null;const p=new URLSearchParams({f:"json",SingleLine:a.full,outFields:"Match_addr,StAddr,City,Region,Postal,Addr_type",maxLocations:"3",sourceCountry:"USA"});const data=await fetchJson(`${NJ_GEOCODE}?${p.toString()}`,{"Accept":"application/json"},15000);const candidates=Array.isArray(data?.candidates)?data.candidates:[];const top=candidates.sort((x:Obj,y:Obj)=>Number(y?.score||0)-Number(x?.score||0))[0];if(!top)return null;const score=Number(top?.score||0),attrs=top?.attributes||{},region=clean(attrs.Region,40).toUpperCase(),postal=zip5(attrs.Postal),street=clean(attrs.StAddr,220),norm=normalizeStreet(street),origNumber=numberPrefix(a.norm),candidateNumber=numberPrefix(norm),location=top?.location||{},wkid=Number(data?.spatialReference?.wkid||102711);if(score<95||!(region==="NJ"||region==="NEW JERSEY")||!postal||norm!==a.norm||!origNumber||origNumber!==candidateNumber)return null;const x=Number(location?.x),y=Number(location?.y);if(!Number.isFinite(x)||!Number.isFinite(y))return null;const enriched:AddressEvidence={...a,zip:postal,full:fullAddress(a.street,a.city,a.region,postal),enrichment:{provider:"NJOGIS NJ_Geocode",method:"recover_missing_zip_exact_street",score,recovered_zip:postal,spatial_reference:wkid}};return{address:enriched,score,x,y,wkid};}
async function spatialParcelCandidates(street:string,zip:string,x:number,y:number,wkid:number){const norm=normalizeStreet(street);if(!norm||!/^\d{5}$/.test(zip))return[] as Obj[];const p=new URLSearchParams({f:"json",geometry:`${x},${y}`,geometryType:"esriGeometryPoint",inSR:String(wkid||102711),spatialRel:"esriSpatialRelIntersects",outFields:"PAMS_PIN,PROP_LOC,MUN_NAME,COUNTY,ZIP5",returnGeometry:"false",resultRecordCount:"5"});const data=await fetchJson(`${NJ}?${p.toString()}`,{"Accept":"application/json"},15000);const features=Array.isArray(data?.features)?data.features:[];return features.map((f:Obj)=>f?.attributes||{}).filter((p:Obj)=>normalizeStreet(p.PROP_LOC)===norm&&zip5(p.ZIP5)===zip&&clean(p.PAMS_PIN,120));}
async function getToken(admin:any,state:Obj,cache:Map<string,string>){const cid=String(state.connection_id);if(cache.has(cid))return cache.get(cid)!;const {data:p}=await admin.from("integration_provider_connections").select("credential_secret_id,provider,sync_status").eq("connection_id",cid).eq("user_id",state.user_id).maybeSingle();if(!p||p.provider!=="boldtrail"||p.sync_status==="revoked"||!p.credential_secret_id)throw new Error("provider_credential_unavailable");const {data:token,error}=await admin.rpc("integration_get_secret",{p_secret_id:p.credential_secret_id});if(error||!token)throw new Error("provider_credential_unavailable");cache.set(cid,String(token));return String(token);}
async function setState(admin:any,id:string,patch:Obj){await admin.from("integration_crm_resolution_state").update({...patch,updated_at:new Date().toISOString()}).eq("crm_context_id",id);}
async function clearAddressCandidates(admin:any,state:Obj){await admin.from("integration_crm_property_links").delete().eq("user_id",state.user_id).eq("crm_context_id",state.crm_context_id).eq("status","candidate").in("link_method",["exact_address_candidate","enriched_zip_exact_candidate"]);}
async function storeAddress(admin:any,state:Obj,ctxId:string,a:AddressEvidence){const {error}=await admin.rpc("integration_set_crm_resolution_address",{p_user_id:state.user_id,p_connection_id:state.connection_id,p_crm_context_id:ctxId,p_property_address:a.full,p_address_source:a.source,p_city:a.city||null,p_state:a.region||null,p_zip:a.zip||null});if(error)throw new Error("crm_resolution_address_update_failed");}
async function processOne(admin:any,state:Obj,tokenCache:Map<string,string>){const {data:ctx}=await admin.from("integration_crm_context").select("id,user_id,connection_id,external_contact_id,property_ref,property_address,contact_name,context,source_updated_at").eq("id",state.crm_context_id).eq("user_id",state.user_id).maybeSingle();if(!ctx)throw new Error("crm_context_missing");
  if(ctx.property_ref&&/^\d{4}_.+/.test(String(ctx.property_ref))){await admin.rpc("integration_refresh_explicit_crm_links",{p_user_id:state.user_id,p_connection_id:state.connection_id});await setState(admin,ctx.id,{detail_status:"enriched",detail_checked_at:new Date().toISOString(),candidate_count:1,last_error:null});return{status:"explicit_ref"};}
  const token=await getToken(admin,state,tokenCache),detail=await contactDetail(token,String(ctx.external_contact_id)),now=new Date().toISOString();const sources=[makeAddress(detail,"primary"),makeAddress(detail,"poi")].filter(Boolean) as AddressEvidence[];
  if(!sources.length){await setState(admin,ctx.id,{detail_status:"no_address",provider_address_source:"boldtrail.contact_detail",normalized_address:null,normalized_zip:null,detail_checked_at:now,attempt_count:Number(state.attempt_count||0)+1,candidate_count:0,last_error:null,next_attempt_at:null});return{status:"no_address"};}
  await clearAddressCandidates(admin,state);const candidateMap=new Map<string,ParcelMatch>();let attemptedNj=false,firstNj:AddressEvidence|null=null;
  for(const source of sources){if(source.region!=="NJ")continue;attemptedNj=true;if(!firstNj)firstNj=source;let a=source,matches:Obj[]=[],matchPolicy="exact_normalized_street_and_zip",geocodeScore:number|null=null;if(a.zip){matches=await parcelCandidates(a.street,a.zip);}else{const enriched=await enrichMissingZip(a);if(!enriched)continue;a=enriched.address;geocodeScore=enriched.score;matches=await spatialParcelCandidates(a.street,a.zip,enriched.x,enriched.y,enriched.wkid);matchPolicy="njogis_zip_enriched_exact_street_spatial_parcel";}for(const parcel of matches){const pin=clean(parcel.PAMS_PIN,120);if(pin&&!candidateMap.has(pin))candidateMap.set(pin,{parcel,address:a,matchPolicy,geocodeScore});}}
  const chosen=candidateMap.size?candidateMap.values().next().value.address:(firstNj||sources[0]);await storeAddress(admin,state,ctx.id,chosen);
  if(!attemptedNj){const allKnownNonNj=sources.every(a=>a.region&&a.region!=="NJ");await setState(admin,ctx.id,{detail_status:allKnownNonNj?"non_nj":"no_match",provider_address_source:chosen.source,normalized_address:chosen.norm||null,normalized_zip:chosen.zip||null,detail_checked_at:now,attempt_count:Number(state.attempt_count||0)+1,candidate_count:0,last_error:null,next_attempt_at:null});return{status:allKnownNonNj?"non_nj":"no_match"};}
  if(!candidateMap.size){await setState(admin,ctx.id,{detail_status:"no_match",provider_address_source:chosen.source,normalized_address:chosen.norm,normalized_zip:chosen.zip||null,detail_checked_at:now,attempt_count:Number(state.attempt_count||0)+1,candidate_count:0,last_error:null,next_attempt_at:null});return{status:"no_match"};}
  const candidateCount=candidateMap.size;for(const [pin,item] of candidateMap){const a=item.address,parcel=item.parcel,{data:existing}=await admin.from("integration_crm_property_links").select("id,status,link_method").eq("user_id",state.user_id).eq("crm_context_id",ctx.id).eq("pams_pin",pin).maybeSingle();if(existing&&existing.status!=="candidate")continue;const enriched=item.matchPolicy==="njogis_zip_enriched_exact_street_spatial_parcel";const row={user_id:state.user_id,connection_id:state.connection_id,crm_context_id:ctx.id,pams_pin:pin,crm_property_address:a.full,candidate_property_address:clean(parcel.PROP_LOC,220)||null,candidate_municipality:clean(parcel.MUN_NAME,120)||null,link_method:enriched?"enriched_zip_exact_candidate":"exact_address_candidate",confidence:candidateCount===1?(enriched?0.92:0.95):0.8,status:"candidate",candidate_count:candidateCount,evidence:{source:enriched?`${a.source}_njogis_zip_enriched_exact_normalized_match`:`${a.source}_exact_normalized_match`,address_source:a.source,crm_relationship_hint:a.hint,normalized_address:a.norm,zip:a.zip,zip_source:enriched?"NJOGIS NJ_Geocode":"crm_provider",geocode_score:enriched?item.geocodeScore:null,parcel_source:"NJOGIS Parcels / MOD-IV Composite",match_policy:item.matchPolicy,name_match_used:false,ownership_inferred:false,auto_verified:false},verified_at:null,updated_at:now};if(existing)await admin.from("integration_crm_property_links").update(row).eq("id",existing.id);else await admin.from("integration_crm_property_links").insert(row);}
  await setState(admin,ctx.id,{detail_status:candidateCount===1?"candidate":"ambiguous",provider_address_source:chosen.source,normalized_address:chosen.norm,normalized_zip:chosen.zip||null,detail_checked_at:now,attempt_count:Number(state.attempt_count||0)+1,candidate_count:candidateCount,last_error:null,next_attempt_at:null});return{status:candidateCount===1?"candidate":"ambiguous",candidates:candidateCount};
}
Deno.serve(async(req)=>{if(req.method!=="POST")return new Response(JSON.stringify({error:"Method not allowed"}),{status:405,headers:{"Content-Type":"application/json"}});const url=Deno.env.get("SUPABASE_URL")||"",secret=namedEnv("SUPABASE_SECRET_KEYS","SUPABASE_SERVICE_ROLE_KEY");if(!url||!secret)return new Response(JSON.stringify({error:"Worker unavailable"}),{status:503,headers:{"Content-Type":"application/json"}});const admin=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}}),supplied=clean(req.headers.get("x-watchdog-resolution-worker-token"),500);const {data:expected}=await admin.rpc("integration_get_named_secret",{p_name:"integration_crm_resolution_worker_token"});if(!supplied||!expected||!same(supplied,String(expected)))return new Response(JSON.stringify({error:"Unauthorized"}),{status:401,headers:{"Content-Type":"application/json"}});let body:Obj={};try{body=await req.json()}catch{}const requested=clean(body.connection_id,80),limit=Math.min(Math.max(Number(body.limit||BATCH_SIZE),1),50);
  const active=await admin.from("integration_provider_connections").select("connection_id,user_id,provider,sync_status").eq("provider","boldtrail").neq("sync_status","revoked");for(const p of active.data||[])if(!requested||p.connection_id===requested)await admin.rpc("integration_seed_crm_resolution",{p_user_id:p.user_id,p_connection_id:p.connection_id});
  let q=admin.from("integration_crm_resolution_state").select("*").in("detail_status",["pending","error"]).order("updated_at",{ascending:true}).limit(limit);if(requested)q=q.eq("connection_id",requested);const {data:states,error:qerr}=await q;if(qerr)return new Response(JSON.stringify({error:"resolution_queue_unavailable"}),{status:503,headers:{"Content-Type":"application/json"}});const now=Date.now(),todo=(states||[]).filter((s:Obj)=>!s.next_attempt_at||new Date(s.next_attempt_at).getTime()<=now),tokenCache=new Map<string,string>(),results:Obj[]=[];
  for(const state of todo){try{const r=await processOne(admin,state,tokenCache);results.push({crm_context_id:state.crm_context_id,...r});}catch(err){const message=clean(err instanceof Error?err.message:err,300)||"resolution_failed",attempt=Number(state.attempt_count||0)+1,wait=Math.min(360,15*Math.pow(2,Math.min(attempt,4))),next=new Date(Date.now()+wait*60000).toISOString();await setState(admin,state.crm_context_id,{detail_status:"error",detail_checked_at:new Date().toISOString(),attempt_count:attempt,last_error:message,next_attempt_at:next});results.push({crm_context_id:state.crm_context_id,status:"error",error:message});}}
  const counts:Record<string,number>={};for(const r of results)counts[r.status]=(counts[r.status]||0)+1;return new Response(JSON.stringify({ok:true,processed:results.length,counts}),{status:200,headers:{"Content-Type":"application/json","Cache-Control":"no-store"}});
});
