import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.95.0";

const ORIGINS=new Set(["https://njpropertytaxrelief.com","https://www.njpropertytaxrelief.com","http://localhost:3000","http://127.0.0.1:3000"]);
const cors=(r:Request)=>({"Access-Control-Allow-Origin":ORIGINS.has(r.headers.get("origin")||"")?(r.headers.get("origin")||""):"https://njpropertytaxrelief.com","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"});
const out=(r:Request,s:number,p:unknown)=>new Response(JSON.stringify(p),{status:s,headers:{...cors(r),"Content-Type":"application/json","Cache-Control":"private, no-store"}});
const clean=(v:unknown,n=1000)=>String(v??"").replace(/[<>]/g,"").trim().slice(0,n);
const env=(j:string,l:string)=>{const r=Deno.env.get(j)||"";if(r){try{const x=JSON.parse(r);if(x?.default)return String(x.default)}catch{}}return Deno.env.get(l)||""};
const n=(v:unknown)=>{const x=Number(v);return Number.isFinite(x)?x:null};
const median=(xs:number[])=>{if(!xs.length)return null;const a=xs.slice().sort((x,y)=>x-y),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2};

async function summary(admin:any,setId:string){
  const [{data:set,error:se},{data:cases,error:ce}]=await Promise.all([
    admin.from("intelligence_calibration_sets").select("*").eq("id",setId).single(),
    admin.from("intelligence_calibration_cases").select("id,expected_class").eq("calibration_set_id",setId)
  ]);if(se||!set)throw new Error("Calibration set not found");if(ce)throw ce;
  const ids=(cases||[]).map((x:any)=>x.id);let reviews:any[]=[];if(ids.length){const r=await admin.from("intelligence_calibration_reviews").select("calibration_case_id,predicted_class,evidence_coverage,review_outcome,error_kind").in("calibration_case_id",ids);if(r.error)throw r.error;reviews=r.data||[]}
  const byReview=new Map(reviews.map((x:any)=>[x.calibration_case_id,x]));let tp=0,tn=0,fp=0,fn=0,uncertain=0,insufficient=0,reviewed=0;const coverage:number[]=[];
  for(const c of cases||[]){if(c.expected_class==="unreviewed")continue;reviewed++;const r=byReview.get(c.id);if(c.expected_class==="uncertain"){uncertain++;continue}if(!r||r.predicted_class==="insufficient_evidence"){insufficient++;continue}if(n(r.evidence_coverage)!=null)coverage.push(Number(r.evidence_coverage));if(c.expected_class==="review_priority"&&r.predicted_class==="review_priority")tp++;else if(c.expected_class==="not_priority"&&r.predicted_class==="not_priority")tn++;else if(c.expected_class==="not_priority"&&r.predicted_class==="review_priority")fp++;else if(c.expected_class==="review_priority"&&r.predicted_class==="not_priority")fn++}
  const precision=(tp+fp)?tp/(tp+fp):null,recall=(tp+fn)?tp/(tp+fn):null,fpr=(fp+tn)?fp/(fp+tn):null,reasons:string[]=[];
  if(reviewed<Number(set.minimum_reviewed_cases))reasons.push(`Need ${Number(set.minimum_reviewed_cases)-reviewed} more reviewed cases`);
  if(precision===null||precision<Number(set.minimum_precision))reasons.push("Precision gate not met");
  if(recall===null||recall<Number(set.minimum_recall))reasons.push("Recall gate not met");
  if(fpr===null||fpr>Number(set.maximum_false_positive_rate))reasons.push("False-positive-rate gate not met");
  if(insufficient>0)reasons.push(`${insufficient} reviewed cases have insufficient evidence`);
  const row={calibration_set_id:setId,reviewed_cases:reviewed,true_positives:tp,true_negatives:tn,false_positives:fp,false_negatives:fn,uncertain_cases:uncertain,insufficient_evidence_cases:insufficient,precision,recall,false_positive_rate:fpr,median_evidence_coverage:median(coverage),passes_gate:reasons.length===0,gate_reasons:reasons,computed_at:new Date().toISOString()};
  const u=await admin.from("intelligence_calibration_summaries").upsert(row);if(u.error)throw u.error;return{set,summary:row,total_cases:(cases||[]).length};
}

Deno.serve(async(req:Request)=>{
  if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});if(req.method!=="POST")return out(req,405,{error:"POST required"});
  const auth=req.headers.get("authorization")||"";if(!auth.startsWith("Bearer "))return out(req,401,{error:"Sign in required"});
  const url=Deno.env.get("SUPABASE_URL")||"",publishable=env("SUPABASE_PUBLISHABLE_KEYS","SUPABASE_ANON_KEY"),secret=env("SUPABASE_SECRET_KEYS","SUPABASE_SERVICE_ROLE_KEY");const uc=createClient(url,publishable,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}}),admin=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});
  const {data:au}=await uc.auth.getUser();const user=au?.user;if(!user)return out(req,401,{error:"Session invalid"});const {data:p}=await admin.from("profiles").select("account_role").eq("id",user.id).maybeSingle();if(String(p?.account_role||"")!=="developer")return out(req,403,{error:"Developer access required"});
  let b:any={};try{b=await req.json()}catch{return out(req,400,{error:"Invalid JSON"})}const action=clean(b?.action||"list",60);
  try{
    if(action==="list"){
      const {data:sets,error}=await admin.from("intelligence_calibration_sets").select("*").order("created_at");if(error)throw error;const ids=(sets||[]).map((x:any)=>x.id);let sums:any[]=[],cases:any[]=[];if(ids.length){const [sr,cr]=await Promise.all([admin.from("intelligence_calibration_summaries").select("*").in("calibration_set_id",ids),admin.from("intelligence_calibration_cases").select("calibration_set_id,expected_class").in("calibration_set_id",ids)]);if(sr.error)throw sr.error;if(cr.error)throw cr.error;sums=sr.data||[];cases=cr.data||[]}
      const sm=new Map(sums.map((x:any)=>[x.calibration_set_id,x]));return out(req,200,{sets:(sets||[]).map((s:any)=>({...s,summary:sm.get(s.id)||null,case_count:cases.filter((c:any)=>c.calibration_set_id===s.id).length,unreviewed_count:cases.filter((c:any)=>c.calibration_set_id===s.id&&c.expected_class==="unreviewed").length}))});
    }
    if(action==="get_set"){
      const setId=clean(b?.calibration_set_id,80);const [{data:set,error:se},{data:cases,error:ce}]=await Promise.all([admin.from("intelligence_calibration_sets").select("*").eq("id",setId).single(),admin.from("intelligence_calibration_cases").select("*").eq("calibration_set_id",setId).order("created_at")]);if(se||!set)return out(req,404,{error:"Calibration set not found"});if(ce)throw ce;const ids=(cases||[]).map((x:any)=>x.id);let reviews:any[]=[];if(ids.length){const r=await admin.from("intelligence_calibration_reviews").select("*").in("calibration_case_id",ids);if(r.error)throw r.error;reviews=r.data||[]}const rm=new Map(reviews.map((x:any)=>[x.calibration_case_id,x]));const s=await summary(admin,setId);return out(req,200,{set,cases:(cases||[]).map((c:any)=>({...c,review:rm.get(c.id)||null})),summary:s.summary});
    }
    if(action==="import_run"){
      const setId=clean(b?.calibration_set_id,80),runId=clean(b?.run_id,80);const [{data:set,error:se},{data:run,error:re}]=await Promise.all([admin.from("intelligence_calibration_sets").select("*").eq("id",setId).single(),admin.from("intelligence_runs").select("*").eq("id",runId).single()]);if(se||!set)return out(req,404,{error:"Calibration set not found"});if(re||!run)return out(req,404,{error:"Intelligence run not found"});if(set.model_key!==run.model_key||Number(set.model_version)!==Number(run.model_version))return out(req,409,{error:"Run model/version does not match calibration set"});
      const {data:findings,error:fe}=await admin.from("intelligence_findings").select("*").eq("run_id",runId).order("rank");if(fe)throw fe;const threshold=Number(set.source_manifest?.priority_threshold??60);for(const f of findings||[]){const caseKey=clean(f.pams_pin||f.property_address||f.id,200);const caseRow={calibration_set_id:setId,case_key:caseKey,pams_pin:f.pams_pin,property_address:f.property_address,expected_class:"unreviewed",evidence_snapshot:{run_id:runId,finding_id:f.id,score:f.score,confidence:f.confidence,evidence_coverage:f.evidence_coverage,why_now:f.why_now,evidence:f.evidence,missing_evidence:f.missing_evidence,facts_hash:f.facts_hash},source_notes:"Imported from governed Intelligence run for human calibration review."};const ci=await admin.from("intelligence_calibration_cases").upsert(caseRow,{onConflict:"calibration_set_id,case_key"}).select("id").single();if(ci.error)throw ci.error;const predicted=Number(f.evidence_coverage)<Number(run?.normalization_manifest?.minimum_evidence_coverage??0)?"insufficient_evidence":Number(f.score)>=threshold?"review_priority":"not_priority";const rv=await admin.from("intelligence_calibration_reviews").upsert({calibration_case_id:ci.data.id,model_key:run.model_key,model_version:run.model_version,actual_score:f.score,actual_confidence:f.confidence,evidence_coverage:f.evidence_coverage,predicted_class:predicted,review_outcome:"needs_review",review_notes:null,reviewer_user_id:null,reviewed_at:null},{onConflict:"calibration_case_id,model_key,model_version"});if(rv.error)throw rv.error}
      await admin.from("intelligence_calibration_sets").update({status:"reviewing",source_manifest:{...set.source_manifest,priority_threshold:threshold,last_imported_run_id:runId}}).eq("id",setId);const s=await summary(admin,setId);return out(req,200,{ok:true,imported:(findings||[]).length,summary:s.summary});
    }
    if(action==="review_case"){
      const caseId=clean(b?.calibration_case_id,80),expected=clean(b?.expected_class,40);if(!["review_priority","not_priority","uncertain"].includes(expected))return out(req,400,{error:"Valid expected_class required"});const {data:c,error:ce}=await admin.from("intelligence_calibration_cases").select("*,intelligence_calibration_sets!inner(model_key,model_version)").eq("id",caseId).single();if(ce||!c)return out(req,404,{error:"Calibration case not found"});const {data:r,error:re}=await admin.from("intelligence_calibration_reviews").select("*").eq("calibration_case_id",caseId).eq("model_key",c.intelligence_calibration_sets.model_key).eq("model_version",c.intelligence_calibration_sets.model_version).single();if(re||!r)return out(req,409,{error:"Calibration case has no model result to review"});let outcome="needs_review",errorKind:null;if(expected!=="uncertain"){if(r.predicted_class==="insufficient_evidence"){outcome="fail";errorKind="data_gap"}else if(expected===r.predicted_class)outcome="pass";else{outcome="fail";errorKind=expected==="not_priority"?"false_positive":"false_negative"}}
      const cu=await admin.from("intelligence_calibration_cases").update({expected_class:expected,expected_score_min:n(b?.expected_score_min),expected_score_max:n(b?.expected_score_max),source_notes:clean(b?.source_notes,2000)||c.source_notes}).eq("id",caseId);if(cu.error)throw cu.error;const ru=await admin.from("intelligence_calibration_reviews").update({review_outcome:outcome,error_kind:errorKind,review_notes:clean(b?.review_notes,4000)||null,reviewer_user_id:user.id,reviewed_at:new Date().toISOString()}).eq("id",r.id);if(ru.error)throw ru.error;const s=await summary(admin,c.calibration_set_id);return out(req,200,{ok:true,review_outcome:outcome,error_kind:errorKind,summary:s.summary});
    }
    if(action==="recompute")return out(req,200,await summary(admin,clean(b?.calibration_set_id,80)));
    return out(req,400,{error:"Unsupported calibration action"});
  }catch(e){console.error("intelligence-calibration-admin",e);return out(req,500,{error:"Calibration operation failed",detail:clean((e as any)?.message,500)||null})}
});
