(function(){
'use strict';
var W=window.WatchdogAgentWorkflows;if(!W)return;var db=W.client(),user=null,lists=[],selected=null,properties=[];
var $=function(s){return document.querySelector(s)};
function renderLists(){var host=$('#bs-list');if(!lists.length){host.innerHTML='<div class="ag-empty">No buyer shortlists yet.</div>';return}host.innerHTML=lists.map(function(x){return'<button type="button" data-list="'+W.esc(x.id)+'" class="'+(selected&&selected.id===x.id?'active':'')+'"><strong>'+W.esc(x.name)+'</strong><small>'+W.esc([x.client_label,x.status].filter(Boolean).join(' · '))+'</small></button>'}).join('')}
function renderDetail(){var has=!!selected;$('#bs-detail').hidden=!has;$('#bs-add').hidden=!has;$('#bs-compare-card').hidden=!has;if(!has){renderLists();return}$('#bs-title').textContent=selected.name;$('#bs-edit-name').value=selected.name||'';$('#bs-edit-client').value=selected.client_label||'';$('#bs-edit-notes').value=selected.notes||'';renderLists();renderCompare()}
function reqState(rows,key){var r=(Array.isArray(rows)?rows:[]).find(function(x){return x&&x.requirement_key===key});return r?String(r.requirement_state||'verify').replace(/_/g,' '):'Verify municipality'}
function permitState(p){if(!p)return'Not checked';if(p.status==='available')return String(Number(p.verification_candidates)||0)+' verification candidate'+(Number(p.verification_candidates)===1?'':'s');if(p.status==='no_rows')return'No DCA rows returned';if(p.status==='missing_key')return'Needs exact parcel keys';return'Provider unavailable'}
function renderCompare(){var host=$('#bs-compare');$('#bs-count').textContent=properties.length+' '+(properties.length===1?'home':'homes');if(!properties.length){host.innerHTML='<div class="ag-empty">Add homes to compare taxes, assessment and public property context.</div>';return}host.innerHTML=properties.map(function(p){var sale=p.watchdog_value||null,d=p.diligence_snapshot||{},reqs=d.municipal_requirements||[];return'<article class="ag-property-card"><header><h3>'+W.esc(p.address)+'</h3><p>'+W.esc([p.town,p.county?p.county+' County':''].filter(Boolean).join(' · '))+'</p></header><dl><div><dt>Annual tax</dt><dd>'+W.money(p.last_year_tax)+'</dd></div><div><dt>Tax / month</dt><dd>'+(p.last_year_tax?W.money(Number(p.last_year_tax)/12):'—')+'</dd></div><div><dt>Assessment</dt><dd>'+W.money(p.assessed)+'</dd></div><div><dt>Last recorded sale</dt><dd>'+W.money(sale)+'</dd></div><div><dt>Permit review</dt><dd>'+W.esc(permitState(d.permit_review))+'</dd></div><div><dt>Resale / CCO</dt><dd>'+W.esc(reqState(reqs,'resale_cco'))+'</dd></div><div><dt>Smoke / fire</dt><dd>'+W.esc(reqState(reqs,'smoke_fire_cert'))+'</dd></div></dl><footer><a class="ag-btn" href="'+W.esc(W.propertyUrl(p))+'"><i class="fa-solid fa-up-right-from-square"></i> Property</a><button class="ag-btn primary" type="button" data-start-tx="'+W.esc(p.id)+'"><i class="fa-solid fa-file-signature"></i> Start transaction</button><button class="ag-btn danger" type="button" data-remove="'+W.esc(p.id)+'"><i class="fa-regular fa-trash-can"></i></button></footer></article>'}).join('')}
async function load(){try{user=await W.auth();var r=await db.from('agent_buyer_shortlists').select('*').eq('user_id',user.id).order('updated_at',{ascending:false});if(r.error)throw r.error;lists=r.data||[];var wanted=new URLSearchParams(location.search).get('id');selected=lists.find(function(x){return x.id===wanted})||lists[0]||null;renderLists();if(selected)await loadProps();renderDetail()}catch(e){W.showNote($('#bs-create-note'),e.message,'error')}}
async function loadProps(){if(!selected){properties=[];return}var r=await db.from('agent_buyer_shortlist_properties').select('*').eq('shortlist_id',selected.id).eq('user_id',user.id).order('sort_order').order('created_at');if(r.error)throw r.error;properties=r.data||[]}
async function chooseList(id){selected=lists.find(function(x){return x.id===id})||null;await loadProps();renderDetail()}
async function create(e){e.preventDefault();var row={user_id:user.id,name:W.clean($('#bs-name').value),client_label:W.clean($('#bs-client').value)||null,notes:W.clean($('#bs-notes').value)||null,status:'active'};if(!row.name)return;W.showNote($('#bs-create-note'),'Saving…');var r=await db.from('agent_buyer_shortlists').insert(row).select('*').single();if(r.error){W.showNote($('#bs-create-note'),r.error.message,'error');return}lists.unshift(r.data);selected=r.data;properties=[];e.currentTarget.reset();renderDetail();W.showNote($('#bs-create-note'),'Shortlist created.','ok')}
async function saveMeta(){if(!selected)return;var patch={name:W.clean($('#bs-edit-name').value),client_label:W.clean($('#bs-edit-client').value)||null,notes:W.clean($('#bs-edit-notes').value)||null,updated_at:new Date().toISOString()};var r=await db.from('agent_buyer_shortlists').update(patch).eq('id',selected.id).eq('user_id',user.id).select('*').single();if(r.error){W.showNote($('#bs-save-note'),r.error.message,'error');return}selected=r.data;var i=lists.findIndex(function(x){return x.id===selected.id});if(i>=0)lists[i]=selected;renderDetail();W.showNote($('#bs-save-note'),'Saved.','ok')}
async function search(){var q=W.clean($('#bs-search').value),host=$('#bs-results');if(q.length<3){host.hidden=true;return}$('#bs-search-btn').disabled=true;try{var rows=await W.propertySearch(q,8);host._rows=rows;host.hidden=false;host.innerHTML=rows.length?rows.map(function(p,i){var exists=properties.some(function(x){return x.pams_pin&&x.pams_pin===p.pams_pin});return'<button class="ag-result" type="button" data-add="'+i+'" '+(exists?'disabled':'')+'><span><b>'+W.esc(p.address)+'</b><small>'+W.esc(W.place(p))+'</small></span><span class="ag-pill '+(exists?'green':'')+'">'+(exists?'Added':'Add')+'</span></button>'}).join(''):'<div class="ag-empty">No matching property record found.</div>'}catch(e){host.hidden=false;host.innerHTML='<div class="ag-empty">Property search is unavailable right now.</div>'}finally{$('#bs-search-btn').disabled=false}}
async function add(i){if(!selected)return;var p=($('#bs-results')._rows||[])[Number(i)];if(!p)return;var row={shortlist_id:selected.id,user_id:user.id,pams_pin:p.pams_pin||null,address:p.address,town:p.city||p.town||null,county:p.county||null,assessed:p.assessed_value||null,last_year_tax:p.last_year_tax||null,watchdog_value:p.last_sale_price||null,diligence_snapshot:{permit_review:p.permit_review||null,municipal_requirements:Array.isArray(p.municipal_requirements)?p.municipal_requirements:[]},sort_order:properties.length};var r=await db.from('agent_buyer_shortlist_properties').insert(row).select('*').single();if(r.error){return}properties.push(r.data);renderCompare();search()}
async function remove(id){var r=await db.from('agent_buyer_shortlist_properties').delete().eq('id',id).eq('user_id',user.id);if(r.error)return;properties=properties.filter(function(p){return p.id!==id});renderCompare()}
async function startTx(id){var p=properties.find(function(x){return x.id===id});if(!p)return;var row={user_id:user.id,address:p.address,city:p.town||null,state:'NJ',municipality:p.town||null,county:p.county||null,pams_pin:p.pams_pin||null,side:'buyer',status:'under_contract',client_label:selected.client_label||null,notes:'Started from Buyer Shortlist: '+selected.name};var r=await db.from('transaction_workspaces').insert(row).select('id').single();if(r.error){alert(r.error.message);return}location.href='/transaction/?tx='+encodeURIComponent(r.data.id)}
document.addEventListener('click',function(e){var l=e.target.closest('[data-list]');if(l)chooseList(l.dataset.list);var a=e.target.closest('[data-add]');if(a&&!a.disabled)add(a.dataset.add);var rem=e.target.closest('[data-remove]');if(rem)remove(rem.dataset.remove);var tx=e.target.closest('[data-start-tx]');if(tx)startTx(tx.dataset.startTx)});
$('#bs-create-form').addEventListener('submit',create);$('#bs-save-meta').addEventListener('click',saveMeta);$('#bs-search-btn').addEventListener('click',search);$('#bs-search').addEventListener('keydown',function(e){if(e.key==='Enter'){e.preventDefault();search()}});$('#bs-new').addEventListener('click',function(){$('#bs-name').focus();scrollTo({top:0,behavior:'smooth'})});
load();
})();