import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

type Json = Record<string, unknown>;

const SUPABASE_URL = Deno.env.get("SUPABASE_URL") || "";
const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || "";
const ANON_KEY = Deno.env.get("SUPABASE_ANON_KEY") || "";
const service = SUPABASE_URL && SERVICE_KEY
  ? createClient(SUPABASE_URL, SERVICE_KEY, { auth: { persistSession: false, autoRefreshToken: false } })
  : null;

function allowedOrigin(origin: string) {
  if (!origin) return "https://njpropertytaxrelief.com";
  try {
    const u = new URL(origin);
    if (u.protocol !== "https:") return "https://njpropertytaxrelief.com";
    if (["njpropertytaxrelief.com", "www.njpropertytaxrelief.com", "njtaxrelief.vercel.app"].includes(u.hostname)) return origin;
    if (u.hostname.endsWith(".vercel.app")) return origin;
  } catch { /* no-op */ }
  return "https://njpropertytaxrelief.com";
}
function cors(req: Request) { return { "Access-Control-Allow-Origin": allowedOrigin(req.headers.get("origin") || ""), "Access-Control-Allow-Headers": "authorization, content-type", "Access-Control-Allow-Methods": "POST, OPTIONS", "Access-Control-Max-Age": "86400", "Vary": "Origin" }; }
function json(req: Request, body: unknown, status = 200) { return new Response(JSON.stringify(body), { status, headers: { ...cors(req), "Content-Type": "application/json; charset=utf-8", "Cache-Control": "no-store" } }); }
function str(v: unknown) { return typeof v === "string" ? v.trim() : v == null ? "" : String(v).trim(); }
function normalizedEmail(v: unknown) { return str(v).toLowerCase(); }
function normalizedPhone(v: unknown) { const raw = str(v), digits = raw.replace(/\D/g, ""); if (digits.length === 10) return `+1${digits}`; if (digits.length === 11 && digits.startsWith("1")) return `+${digits}`; return raw; }
function boundedNumber(v: unknown, min = 0, max = 100) { if (v === null || v === undefined || v === "") return null; const n = Number(String(v).replace(/[$,]/g, "")); return Number.isFinite(n) ? Math.max(min, Math.min(max, n)) : null; }
function slug(v: unknown) { return str(v).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }
function deriveTags(lead: Json) { const out = new Set<string>(["watchdog"]), program = str(lead.program), tenure = str(lead.tenure), intent = boundedNumber(lead.intent_score), benefit = boundedNumber(lead.estimated_benefit, 0, 1000000); if (/anchor/i.test(program)) out.add("anchor"); if (tenure) out.add(slug(tenure)); if (intent != null) { out.add(`intent-${Math.round(intent)}`); if (intent >= 40) out.add("intent-engaged"); } if (benefit != null && benefit > 0) out.add(`benefit-${Math.round(benefit)}`); if (Array.isArray(lead.tags)) for (const tag of lead.tags) { const clean = slug(tag); if (clean) out.add(clean); } return Array.from(out); }
function hex(bytes: ArrayBuffer | Uint8Array) { const arr = bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes); return Array.from(arr).map((b) => b.toString(16).padStart(2, "0")).join(""); }
async function sha256(value: string) { return hex(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value))); }
function randomToken() { const bytes = new Uint8Array(32); crypto.getRandomValues(bytes); return hex(bytes); }
async function fingerprint(req: Request) { const ip = (req.headers.get("x-forwarded-for") || req.headers.get("cf-connecting-ip") || "unknown").split(",")[0].trim(), ua = req.headers.get("user-agent") || "unknown"; return sha256(`${ip}|${ua}`); }
async function secretConfigured(name: string) { if (!service) return false; const r = await service.rpc("backoffice_secret_configured", { p_name: name }); return !r.error && r.data === true; }
async function getSecret(name: string) { if (!service) return ""; const r = await service.rpc("backoffice_get_secret", { p_name: name }); return r.error ? "" : str(r.data); }
async function setSecret(name: string, value: string, description: string) { if (!service) throw new Error("Server unavailable"); const r = await service.rpc("backoffice_set_secret", { p_name: name, p_value: value, p_description: description }); if (r.error) throw r.error; }
async function createSession(actor: string, req: Request) { if (!service) throw new Error("Server unavailable"); const token = randomToken(), tokenHash = await sha256(token), expiresAt = new Date(Date.now() + 12 * 60 * 60 * 1000).toISOString(), fp = await fingerprint(req); const inserted = await service.from("backoffice_sessions").insert({ token_hash: tokenHash, actor_label: actor, expires_at: expiresAt, request_fingerprint: fp }).select("id,actor_label,expires_at").single(); if (inserted.error) throw inserted.error; return { token, session: inserted.data }; }
async function sessionFromRequest(req: Request) { if (!service) return null; const auth = req.headers.get("authorization") || "", match = auth.match(/^Bearer\s+(.+)$/i); if (!match) return null; const tokenHash = await sha256(match[1]), now = new Date().toISOString(); const q = await service.from("backoffice_sessions").select("id,actor_label,expires_at,revoked_at").eq("token_hash", tokenHash).is("revoked_at", null).gt("expires_at", now).maybeSingle(); if (q.error || !q.data) return null; await service.from("backoffice_sessions").update({ last_seen_at: now }).eq("id", q.data.id); return q.data; }
async function requireSession(req: Request) { const session = await sessionFromRequest(req); if (!session) throw Object.assign(new Error("Backoffice session expired. Sign in again."), { status: 401 }); return session; }
async function logAuth(req: Request, eventType: string, success: boolean, actor: string | null, metadata: Json = {}) { if (!service) return; await service.from("backoffice_auth_events").insert({ actor_label: actor, event_type: eventType, success, request_fingerprint: await fingerprint(req), metadata }); }
async function tooManyFailures(req: Request) { if (!service) return true; const fp = await fingerprint(req), since = new Date(Date.now() - 15 * 60 * 1000).toISOString(); const q = await service.from("backoffice_auth_events").select("id", { count: "exact", head: true }).eq("request_fingerprint", fp).eq("event_type", "login.failed").gte("created_at", since); return (q.count || 0) >= 8; }
async function verifyDeveloperToken(accessToken: string) { if (!service || !SUPABASE_URL || !ANON_KEY || !accessToken) return false; const user = await service.auth.getUser(accessToken); if (user.error || !user.data.user) return false; const userClient = createClient(SUPABASE_URL, ANON_KEY, { auth: { persistSession: false, autoRefreshToken: false }, global: { headers: { Authorization: `Bearer ${accessToken}` } } }); const dev = await userClient.rpc("is_watchdog_developer"); return !dev.error && dev.data === true; }
async function integrationStatus() { if (!service) return { google_address_validation: false, profiles: [] }; const [google, profiles] = await Promise.all([secretConfigured("google_address_validation_api_key"), service.from("backoffice_export_profiles").select("profile_key,label,enabled,sort_order").eq("enabled", true).order("sort_order")]); return { google_address_validation: google, profiles: profiles.data || [] }; }
function minimizedAddressResult(result: Json) { const address = (result.address && typeof result.address === "object" ? result.address : {}) as Json, verdict = (result.verdict && typeof result.verdict === "object" ? result.verdict : {}) as Json, usps = (result.uspsData && typeof result.uspsData === "object" ? result.uspsData : {}) as Json; return { formatted_address: str(address.formattedAddress), postal_address: address.postalAddress || {}, verdict: { input_granularity: verdict.inputGranularity || null, validation_granularity: verdict.validationGranularity || null, geocode_granularity: verdict.geocodeGranularity || null, address_complete: verdict.addressComplete === true, has_unconfirmed_components: verdict.hasUnconfirmedComponents === true, has_inferred_components: verdict.hasInferredComponents === true, has_replaced_components: verdict.hasReplacedComponents === true }, usps: { dpv_confirmation: usps.dpvConfirmation || null, dpv_footnote: usps.dpvFootnote || null, cass_processed: usps.cassProcessed === true } }; }
async function validateLeadAddress(lead: Json) { if (!service) throw new Error("Server unavailable"); const leadId = str(lead.id), input = str(lead.submitted_address); if (!leadId || !input) throw Object.assign(new Error("This lead does not have a submitted address."), { status: 422 }); const key = await getSecret("google_address_validation_api_key"); if (!key) throw Object.assign(new Error("Google Address Validation is not connected yet."), { status: 409, code: "GOOGLE_NOT_CONFIGURED" }); const validatedAt = new Date().toISOString(); let res: Response; try { res = await fetch(`https://addressvalidation.googleapis.com/v1:validateAddress?key=${encodeURIComponent(key)}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ address: { regionCode: "US", addressLines: [input] }, enableUspsCass: true }) }); } catch { await service.from("backoffice_leads").update({ address_status: "error", address_validation_provider: "google", address_validated_at: validatedAt }).eq("id", leadId); throw Object.assign(new Error("Google Address Validation could not be reached."), { status: 502 }); } const body = await res.json().catch(() => ({})); if (!res.ok || !body?.result) { await service.from("backoffice_leads").update({ address_status: "error", address_validation_provider: "google", address_validated_at: validatedAt }).eq("id", leadId); await service.from("backoffice_lead_events").insert({ lead_id: leadId, event_type: "address.validation_failed", status: "error", provider: "google", details: { http_status: res.status } }); throw Object.assign(new Error("Google could not validate this address."), { status: 422 }); } const minimal = minimizedAddressResult(body.result as Json) as Json, verdict = minimal.verdict as Json, usps = minimal.usps as Json, formatted = str(minimal.formatted_address), dpv = str(usps.dpv_confirmation).toUpperCase(), complete = verdict.address_complete === true, unconfirmed = verdict.has_unconfirmed_components === true, status = formatted && complete && !unconfirmed && dpv === "Y" ? "verified" : formatted ? "review" : "error"; const update = await service.from("backoffice_leads").update({ standardized_address: formatted || null, standardized_address_json: minimal, address_status: status, address_validation_provider: "google", address_validated_at: validatedAt, processing_status: status === "verified" ? "ready" : "review" }).eq("id", leadId).select("*").single(); if (update.error) throw update.error; await service.from("backoffice_lead_events").insert({ lead_id: leadId, event_type: "address.validated", status, provider: "google", details: { dpv_confirmation: dpv || null, address_complete: complete, has_unconfirmed_components: unconfirmed } }); return update.data; }
function firstLast(fullName: string) { const parts = fullName.trim().split(/\s+/).filter(Boolean); if (!parts.length) return { first: "", last: "" }; if (parts.length === 1) return { first: parts[0], last: "" }; return { first: parts.slice(0, -1).join(" "), last: parts[parts.length - 1] }; }
function csvCell(value: unknown) { const s = value == null ? "" : String(value).replace(/\r?\n/g, " "); return `"${s.replace(/"/g, '""')}"`; }
function postalParts(lead: Json) { const data = (lead.standardized_address_json && typeof lead.standardized_address_json === "object" ? lead.standardized_address_json : {}) as Json, postal = (data.postal_address && typeof data.postal_address === "object" ? data.postal_address : {}) as Json, lines = Array.isArray(postal.addressLines) ? postal.addressLines.map(str).filter(Boolean) : []; return { street: lines.join(" ") || str(lead.standardized_address) || str(lead.submitted_address), city: str(postal.locality), state: str(postal.administrativeArea), zip: str(postal.postalCode) }; }
function crmNote(lead: Json) { return [`Watchdog lead ${str(lead.id)}`, str(lead.program) ? `Program: ${str(lead.program)}` : "", lead.intent_score != null ? `Intent: ${lead.intent_score}${str(lead.intent_label) ? ` ${str(lead.intent_label)}` : ""}` : "", lead.estimated_benefit != null ? `Estimated benefit: $${Number(lead.estimated_benefit).toLocaleString("en-US")}` : "", str(lead.tenure) ? `Tenure: ${str(lead.tenure)}` : "", str(lead.household_income) ? `Income: ${str(lead.household_income)}` : "", str(lead.submitted_address) ? `Submitted address: ${str(lead.submitted_address)}` : "", str(lead.standardized_address) ? `Google standardized: ${str(lead.standardized_address)} (${str(lead.address_status) || "review"})` : "", str(lead.notes) ? `Notes: ${str(lead.notes)}` : ""].filter(Boolean).join(" | "); }
function buildCsv(leads: Json[]) { const headers = ["First Name", "Last Name", "Email", "Phone", "Street Address", "City", "State", "Postal Code", "Source", "Status", "Hashtags", "Notes", "Watchdog Lead ID", "Program", "Intent Score", "Estimated Benefit", "Tenure", "Household Income", "Address Validation Status"]; const rows = leads.map((lead) => { const name = firstLast(str(lead.full_name)), address = postalParts(lead), tags = Array.isArray(lead.tags) ? lead.tags.map((t) => str(t).replace(/^#/, "")).filter(Boolean).join(",") : ""; return [name.first, name.last, lead.email, lead.phone, address.street, address.city, address.state, address.zip, lead.source || "Watchdog", lead.lead_status || "new", tags, crmNote(lead), lead.id, lead.program, lead.intent_score, lead.estimated_benefit, lead.tenure, lead.household_income, lead.address_status].map(csvCell).join(","); }); return `\uFEFF${[headers.map(csvCell).join(","), ...rows].join("\r\n")}`; }
function errorStatus(error: unknown) { return Number((error as { status?: number })?.status) || 500; }
function errorMessage(error: unknown) { return error instanceof Error ? error.message : "Request failed"; }

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: cors(req) });
  if (req.method !== "POST") return json(req, { error: "Method not allowed" }, 405);
  if (!service) return json(req, { error: "Backoffice server is unavailable." }, 500);
  let payload: Json; try { payload = await req.json(); } catch { return json(req, { error: "Invalid JSON" }, 400); }
  const action = str(payload.action || "status").toLowerCase();
  try {
    if (action === "status") return json(req, { ok: true, setup_required: !(await secretConfigured("backoffice_shared_access_key")), google_address_validation: await secretConfigured("google_address_validation_api_key") });
    if (action === "setup") { if (await secretConfigured("backoffice_shared_access_key")) return json(req, { error: "Backoffice is already initialized." }, 409); const developerToken = str(payload.watchdog_access_token); if (!(await verifyDeveloperToken(developerToken))) return json(req, { error: "A signed-in Watchdog developer account is required for first-time setup." }, 403); const newKey = str(payload.key); if (newKey.length < 14) return json(req, { error: "Use at least 14 characters for the shared backoffice key." }, 422); const actor = ["john", "wife"].includes(str(payload.actor)) ? str(payload.actor) : "john"; await setSecret("backoffice_shared_access_key", newKey, "Shared password for /property/backoffice/"); const created = await createSession(actor, req); await logAuth(req, "setup.completed", true, actor, {}); return json(req, { ok: true, token: created.token, actor, expires_at: created.session.expires_at, integrations: await integrationStatus() }); }
    if (action === "login") { if (!(await secretConfigured("backoffice_shared_access_key"))) return json(req, { error: "Backoffice setup is required.", setup_required: true }, 409); if (await tooManyFailures(req)) return json(req, { error: "Too many failed attempts. Try again in 15 minutes." }, 429); const actor = ["john", "wife"].includes(str(payload.actor)) ? str(payload.actor) : "john", key = str(payload.key), verify = await service.rpc("backoffice_verify_shared_key", { p_candidate: key }), valid = !verify.error && verify.data === true; if (!valid) { await logAuth(req, "login.failed", false, actor, {}); return json(req, { error: "Incorrect backoffice key." }, 401); } const created = await createSession(actor, req); await logAuth(req, "login.succeeded", true, actor, {}); return json(req, { ok: true, token: created.token, actor, expires_at: created.session.expires_at, integrations: await integrationStatus() }); }
    const session = await requireSession(req);
    if (action === "session") return json(req, { ok: true, actor: session.actor_label, expires_at: session.expires_at, integrations: await integrationStatus() });
    if (action === "logout") { await service.from("backoffice_sessions").update({ revoked_at: new Date().toISOString() }).eq("id", session.id); await logAuth(req, "logout", true, session.actor_label, {}); return json(req, { ok: true }); }
    if (action === "integrations") return json(req, { ok: true, ...(await integrationStatus()) });
    if (action === "set_google_key") { const value = str(payload.key); if (value.length < 20) return json(req, { error: "Enter the Google Address Validation API key." }, 422); await setSecret("google_address_validation_api_key", value, "Google Address Validation API key for Watchdog Backoffice"); await logAuth(req, "integration.google_address_validation.updated", true, session.actor_label, {}); return json(req, { ok: true, google_address_validation: true }); }
    if (action === "rotate_access_key") { const value = str(payload.key); if (value.length < 14) return json(req, { error: "Use at least 14 characters for the new backoffice key." }, 422); await setSecret("backoffice_shared_access_key", value, "Shared password for /property/backoffice/"); await service.from("backoffice_sessions").update({ revoked_at: new Date().toISOString() }).is("revoked_at", null); await logAuth(req, "access_key.rotated", true, session.actor_label, {}); return json(req, { ok: true, signed_out: true }); }
    if (action === "list") { const q = await service.from("backoffice_leads").select("id,source,lead_status,processing_status,full_name,email,phone,submitted_address,standardized_address,address_status,tenure,household_income,program,intent_score,intent_label,estimated_benefit,tags,identity_score,identity_status,enrichment_provider,crm_provider,crm_status,crm_owner,last_exported_at,last_export_profile,address_validation_provider,address_validated_at,notes,created_at,updated_at").order("created_at", { ascending: false }).limit(1000); if (q.error) throw q.error; return json(req, { ok: true, leads: q.data || [], integrations: await integrationStatus() }); }
    if (action === "detail") { const id = str(payload.lead_id); if (!id) return json(req, { error: "lead_id is required" }, 422); const [lead, events] = await Promise.all([service.from("backoffice_leads").select("*").eq("id", id).single(), service.from("backoffice_lead_events").select("id,event_type,status,provider,details,created_at").eq("lead_id", id).order("created_at", { ascending: false }).limit(50)]); if (lead.error) throw lead.error; return json(req, { ok: true, lead: lead.data, events: events.data || [] }); }
    if (action === "add") { const incoming = (payload.lead && typeof payload.lead === "object" ? payload.lead : {}) as Json, fullName = str(incoming.full_name), email = normalizedEmail(incoming.email), phone = normalizedPhone(incoming.phone); if (!fullName && !email && !phone) return json(req, { error: "Add a name, email or phone." }, 422); const intent = boundedNumber(incoming.intent_score), benefit = boundedNumber(incoming.estimated_benefit, 0, 1000000); const row: Json = { source: str(incoming.source) || "manual-backoffice", lead_status: "new", processing_status: "pending", full_name: fullName || null, email: email || null, phone: phone || null, submitted_address: str(incoming.submitted_address) || null, submitted_address_json: {}, address_status: str(incoming.submitted_address) ? "pending" : "skipped", tenure: str(incoming.tenure) || null, household_income: str(incoming.household_income) || null, program: str(incoming.program) || null, intent_score: intent == null ? null : Math.round(intent), intent_label: intent != null && intent >= 40 ? "ENGAGED" : null, estimated_benefit: benefit, tags: deriveTags(incoming), identity_status: "pending", crm_status: "pending", crm_owner: ["john", "wife"].includes(str(incoming.crm_owner)) ? str(incoming.crm_owner) : "unassigned", consent_data: {}, raw_payload: { ingest: "manual-backoffice", submitted_at: new Date().toISOString() }, notes: str(incoming.notes) || null }; const inserted = await service.from("backoffice_leads").insert(row).select("*").single(); if (inserted.error) throw inserted.error; await service.from("backoffice_lead_events").insert({ lead_id: inserted.data.id, event_type: "lead.created", status: "pending", provider: "manual-backoffice", details: { actor: session.actor_label } }); let saved = inserted.data as Json; if (str(saved.submitted_address) && await secretConfigured("google_address_validation_api_key")) { try { saved = await validateLeadAddress(saved); } catch { /* retry available in UI */ } } return json(req, { ok: true, lead: saved }, 201); }
    if (action === "update") { const id = str(payload.lead_id), patchIn = (payload.patch && typeof payload.patch === "object" ? payload.patch : {}) as Json, patch: Json = {}; if (["new", "open", "closed", "archived"].includes(str(patchIn.lead_status))) patch.lead_status = str(patchIn.lead_status); if (["pending", "ready", "review", "error"].includes(str(patchIn.processing_status))) patch.processing_status = str(patchIn.processing_status); if (Object.prototype.hasOwnProperty.call(patchIn, "notes")) patch.notes = str(patchIn.notes) || null; if (!id || !Object.keys(patch).length) return json(req, { error: "No allowed changes were supplied." }, 422); const q = await service.from("backoffice_leads").update(patch).eq("id", id).select("*").single(); if (q.error) throw q.error; await service.from("backoffice_lead_events").insert({ lead_id: id, event_type: "lead.updated", status: str(patch.processing_status || patch.lead_status) || null, provider: "backoffice", details: { actor: session.actor_label, fields: Object.keys(patch) } }); return json(req, { ok: true, lead: q.data }); }
    if (action === "assign") { const ids = Array.isArray(payload.lead_ids) ? payload.lead_ids.map(str).filter(Boolean).slice(0, 500) : [], profile = str(payload.profile_key); if (!ids.length || !["unassigned", "john", "wife"].includes(profile)) return json(req, { error: "Select leads and a valid destination." }, 422); const q = await service.from("backoffice_leads").update({ crm_owner: profile }).in("id", ids).select("id,crm_owner"); if (q.error) throw q.error; await service.from("backoffice_lead_events").insert(ids.map((id) => ({ lead_id: id, event_type: "crm.assignment_changed", status: profile, provider: "boldtrail-export", details: { actor: session.actor_label } }))); return json(req, { ok: true, updated: q.data || [] }); }
    if (action === "validate_address") { const id = str(payload.lead_id); if (!id) return json(req, { error: "lead_id is required" }, 422); const q = await service.from("backoffice_leads").select("*").eq("id", id).single(); if (q.error) throw q.error; return json(req, { ok: true, lead: await validateLeadAddress(q.data as Json) }); }
    if (action === "export_csv") { const profile = str(payload.profile_key); if (!["john", "wife"].includes(profile)) return json(req, { error: "Choose John or Wife for this BoldTrail export." }, 422); const ids = Array.isArray(payload.lead_ids) ? payload.lead_ids.map(str).filter(Boolean).slice(0, 1000) : [], includeExported = payload.include_exported === true; let q = service.from("backoffice_leads").select("*").order("created_at", { ascending: true }).limit(1000); if (ids.length) q = q.in("id", ids); else { q = q.eq("crm_owner", profile); if (!includeExported) q = q.is("last_exported_at", null); } const rows = await q; if (rows.error) throw rows.error; const leads = (rows.data || []) as Json[]; if (!leads.length) return json(req, { error: ids.length ? "No selected leads were available for export." : `No new ${profile === "john" ? "John" : "Wife"} leads are waiting for export.` }, 422); const csv = buildCsv(leads), stamp = new Date().toISOString().replace(/[-:]/g, "").replace("T", "-").slice(0, 13), filename = `boldtrail-${profile}-${stamp}.csv`; const created = await service.from("backoffice_exports").insert({ profile_key: profile, filename, row_count: leads.length, session_id: session.id, metadata: { selected_export: ids.length > 0 } }).select("id").single(); if (created.error) throw created.error; const exportId = created.data.id; const items = await service.from("backoffice_export_items").insert(leads.map((lead) => ({ export_id: exportId, lead_id: lead.id }))); if (items.error) throw items.error; const leadIds = leads.map((lead) => str(lead.id)), exportedAt = new Date().toISOString(), updated = await service.from("backoffice_leads").update({ crm_owner: profile, crm_provider: "boldtrail", crm_status: "exported", last_exported_at: exportedAt, last_export_profile: profile }).in("id", leadIds); if (updated.error) throw updated.error; await service.from("backoffice_lead_events").insert(leadIds.map((id) => ({ lead_id: id, event_type: "crm.csv_exported", status: "exported", provider: `boldtrail:${profile}`, details: { export_id: exportId, filename, actor: session.actor_label } }))); return json(req, { ok: true, filename, csv, count: leads.length, export_id: exportId }); }
    return json(req, { error: "Unknown action" }, 400);
  } catch (error) { console.error("backoffice-api", action, errorMessage(error)); return json(req, { error: errorMessage(error), code: (error as { code?: string })?.code || undefined }, errorStatus(error)); }
});
