import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.95.0";

type Row=Record<string,any>;
const RANK:Record<string,number>={standard:0,agent:1,pro:2,pro_plus:3,teams:4,developer:5};
const clean=(v:unknown,n=1000)=>String(v??"").replace(/[<>]/g,"").trim().slice(0,n);
const safe=(v:unknown)=>(v&&typeof v==="object"&&!Array.isArray(v)?v as Row:{});
const countyKey=(v:unknown)=>clean(v,100).replace(/\s+county$/i,"").trim().toUpperCase();
const cors=(r:Request)=>({"Access-Control-Allow-Origin":"https://www.watchdogindex.com","Access-Control-Allow-Headers":"authorization,apikey,content-type,x-client-info","Access-Control-Allow-Methods":"POST,OPTIONS"});
const out=(r:Request,s:number,b:unknown)=>new Response(JSON.stringify(b),{status:s,headers:{...cors(r),"Content-Type":"application/json","Cache-Control":"private, no-store"}});
async function hash(v:unknown){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(JSON.stringify(v)));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}

Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});if(req.method!=="POST")return out(req,405,{error:"POST required"});
 const auth=req.headers.get("authorization")||"";if(!auth.startsWith("Bearer "))return out(req,401,{error:"Sign in required"});const url=Deno.env.get("SUPABASE_URL")||"",anon=Deno.env.get("SUPABASE_ANON_KEY")||"",service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";if(!url||!anon||!service)return out(req,503,{error:"County routing unavailable"});
 const uc=createClient(url,anon,{global:{headers:{Authorization:auth}},auth:{persistSession:false}}),admin=createClient(url,service,{auth:{persistSession:false}});const {data:who}=await uc.auth.getUser();const user=who?.user;if(!user)return out(req,401,{error:"Session invalid"});const [{data:ent},{data:prof}]=await Promise.all([admin.from("account_entitlements").select("plan_tier").eq("user_id",user.id).maybeSingle(),admin.from("profiles").select("account_role").eq("id",user.id).maybeSingle()]);const plan=prof?.account_role==="developer"?"developer":String(ent?.plan_tier||"standard");if((RANK[plan]??0)<RANK.pro_plus)return out(req,403,{error:"Pro+ required"});
 let body:Row={};try{body=await req.json()}catch{return out(req,400,{error:"Invalid JSON"})}const ids=[...new Set((Array.isArray(body.transaction_ids)?body.transaction_ids:[]).map((x:unknown)=>clean(x,80)).filter(Boolean))].slice(0,50);if(!ids.length)return out(req,400,{error:"transaction_ids required"});
 const {data:txs}=await admin.from("transaction_workspaces").select("id,user_id,address,county,pams_pin").eq("user_id",user.id).in("id",ids);const counties=[...new Set((txs||[]).map((t:Row)=>countyKey(t.county)).filter(Boolean))];const {data:routes}=counties.length?await admin.from("transaction_provider_registry").select("jurisdiction_key,jurisdiction_name,provider_key,provider_label,provider_url,evidence_families,access_mode,adapter_status,source_url,last_verified_at,metadata").eq("jurisdiction_type","county").in("jurisdiction_key",counties):{data:[]};const routeMap=new Map<string,Row[]>();for(const r of routes||[]){const k=countyKey(r.jurisdiction_key);routeMap.set(k,[...(routeMap.get(k)||[]),r])}
 const keys=["judgment_lien_search","lis_pendens_title_exceptions","deed_recording_reference"];const {data:items}=await admin.from("transaction_items").select("id,transaction_id,item_key,payload").eq("user_id",user.id).in("transaction_id",ids).in("item_key",keys);const itemMap=new Map<string,Row>();for(const i of items||[])itemMap.set(`${i.transaction_id}:${i.item_key}`,i);const checkedAt=new Date().toISOString(),results:Row[]=[];
 for(const tx of txs||[]){const ck=countyKey(tx.county),all=(routeMap.get(ck)||[]).sort((a,b)=>String(a.access_mode).localeCompare(String(b.access_mode)));const usable=all.filter(r=>r.provider_url);if(!usable.length){results.push({transaction_id:tx.id,county:ck,status:"no_registry_route"});continue}const best=usable[0];const publicRoutes=usable.map(r=>({provider_key:r.provider_key,label:r.provider_label,url:r.provider_url,access_mode:r.access_mode,adapter_status:r.adapter_status,evidence_families:r.evidence_families,last_verified_at:r.last_verified_at}));const patch=async(key:string,v:Row)=>{const it=itemMap.get(`${tx.id}:${key}`);if(!it)return;await admin.from("transaction_items").update({...v,payload:{...safe(it.payload),...safe(v.payload)},updated_at:checkedAt}).eq("id",it.id).eq("user_id",user.id)};
 const routeText=`${clean(best.provider_label,180)} is the routed ${clean(tx.county,100)||ck} County recording source. Watchdog identified the official/public access path, but this routing result alone is not a completed title, lien, judgment, or Lis Pendens search.`;
 await patch("judgment_lien_search",{evidence_state:"verify",severity:"review",source_type:"county_provider_route",source_label:clean(best.provider_label,180),source_url:best.provider_url,source_checked_at:checkedAt,description:`${routeText} County-recorded liens can be searched here; statewide judgment identity matching remains a separate NJ Judiciary search.`,payload:{county:ck,provider_routes:publicRoutes,search_completed:false,records:[]}});
 await patch("lis_pendens_title_exceptions",{evidence_state:"verify",severity:"review",source_type:"county_provider_route",source_label:clean(best.provider_label,180),source_url:best.provider_url,source_checked_at:checkedAt,description:`${routeText} Watchdog will only report “none found” after the applicable county index search actually completes.`,payload:{county:ck,provider_routes:publicRoutes,search_completed:false,records:[]}});
 await patch("deed_recording_reference",{source_type:"county_provider_route",source_label:clean(best.provider_label,180),source_url:best.provider_url,source_checked_at:checkedAt,payload:{county:ck,county_provider_routes:publicRoutes}});
 const evidence={county:ck,routes:publicRoutes};await admin.from("transaction_evidence_observations").upsert({transaction_id:tx.id,user_id:user.id,pams_pin:tx.pams_pin,evidence_key:"county_provider_route",provider_key:`county-${ck.toLowerCase().replace(/[^a-z0-9]+/g,"-")}`,evidence_status:"verify",value:evidence,source_label:clean(best.provider_label,180),source_url:best.provider_url,source_checked_at:checkedAt,facts_hash:await hash(evidence),metadata:{routing_only:true,search_completed:false,title_clearance:false}},{onConflict:"transaction_id,evidence_key,provider_key,facts_hash",ignoreDuplicates:true});results.push({transaction_id:tx.id,county:ck,status:"routed",route_count:publicRoutes.length,primary:best.provider_key})}
 return out(req,200,{ok:true,checked_at:checkedAt,results});
});
