import { createClient } from 'npm:@supabase/supabase-js@2.95.0';
const URL=Deno.env.get('SUPABASE_URL')!,ANON=Deno.env.get('SUPABASE_ANON_KEY')!,SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const ORIGINS=new Set(['https://njpropertytaxrelief.com','https://www.njpropertytaxrelief.com']);
const CALLBACK=`${URL}/functions/v1/google-ads-oauth-callback`;
function cors(req:Request){const o=req.headers.get('origin')||'';return{'Access-Control-Allow-Origin':ORIGINS.has(o)?o:'https://njpropertytaxrelief.com','Access-Control-Allow-Headers':'authorization, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Cache-Control':'private, no-store','Vary':'Origin'}}
function reply(req:Request,status:number,body:unknown){return new Response(JSON.stringify(body),{status,headers:{...cors(req),'Content-Type':'application/json'}})}
const hex=(b:Uint8Array)=>Array.from(b).map(x=>x.toString(16).padStart(2,'0')).join('');
async function sha(v:string){return hex(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v))))}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors(req)});if(req.method!=='POST')return reply(req,405,{error:'Method not allowed'});const origin=req.headers.get('origin')||'';if(origin&&!ORIGINS.has(origin))return reply(req,403,{error:'Origin not allowed'});const clientId=Deno.env.get('GOOGLE_ADS_CLIENT_ID'),clientSecret=Deno.env.get('GOOGLE_ADS_CLIENT_SECRET'),developerToken=Deno.env.get('GOOGLE_ADS_DEVELOPER_TOKEN');if(!clientId||!clientSecret||!developerToken)return reply(req,409,{error:'Google Ads is not configured yet',code:'provider_not_connected'});const auth=req.headers.get('Authorization')||'';const client=createClient(URL,ANON,{global:{headers:{Authorization:auth}},auth:{persistSession:false}});const{data:{user},error}=await client.auth.getUser();if(error||!user)return reply(req,401,{error:'Sign in required'});const access=await client.rpc('marketing_studio_bootstrap');if(access.error)return reply(req,403,{error:'Marketing Studio access required'});const state=hex(crypto.getRandomValues(new Uint8Array(32)));const stateHash=await sha(state);const service=createClient(URL,SERVICE,{auth:{persistSession:false}});const{error:insertError}=await service.from('marketing_provider_oauth_states').insert({state_hash:stateHash,user_id:user.id,provider_key:'google_ads',redirect_path:'/property/marketing-studio.html',expires_at:new Date(Date.now()+10*60*1000).toISOString()});if(insertError)return reply(req,503,{error:'Could not start provider authorization'});const q=new URLSearchParams({client_id:clientId,redirect_uri:CALLBACK,response_type:'code',scope:'https://www.googleapis.com/auth/adwords',access_type:'offline',prompt:'consent',include_granted_scopes:'true',state});return reply(req,200,{authorization_url:`https://accounts.google.com/o/oauth2/v2/auth?${q.toString()}`,provider:'google_ads'});});
