import { createClient } from 'npm:@supabase/supabase-js@2.95.0';

const URL=Deno.env.get('SUPABASE_URL')!;
const ANON=Deno.env.get('SUPABASE_ANON_KEY')!;
const PCM='https://v3.pcmintegrations.com';
const ORIGINS=new Set(['https://njpropertytaxrelief.com','https://www.njpropertytaxrelief.com']);

function cors(req:Request){const o=req.headers.get('origin')||'';return{'Access-Control-Allow-Origin':ORIGINS.has(o)?o:'https://njpropertytaxrelief.com','Access-Control-Allow-Headers':'authorization, apikey, content-type, x-client-info','Access-Control-Allow-Methods':'POST, OPTIONS','Cache-Control':'private, no-store','Vary':'Origin'}}
function reply(req:Request,status:number,body:unknown){return new Response(JSON.stringify(body),{status,headers:{...cors(req),'Content-Type':'application/json; charset=utf-8'}})}
function clean(v:unknown,max=500){if(v&&typeof v==='object')return'';return String(v??'').trim().replace(/[\u0000-\u001f]/g,'').slice(0,max)}
function tokenFrom(d:any){return clean(d?.token??d?.accessToken??d?.access_token??d?.code,4000)}
async function token(){const apiKey=Deno.env.get('PCM_SANDBOX_API_KEY')||'',apiSecret=Deno.env.get('PCM_API_SECRET')||'';if(!apiKey||!apiSecret)throw new Error('PCM sandbox credentials are incomplete');const r=await fetch(PCM+'/auth/login',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify({apiKey,apiSecret})});const text=await r.text();let d:any={};try{d=JSON.parse(text)}catch{}const t=tokenFrom(d);if(!r.ok||!t)throw new Error(`PCM sandbox login failed (${r.status})`);return t}
function rows(data:any){if(Array.isArray(data))return data;if(!data||typeof data!=='object')return[];for(const k of ['data','items','results','orders','batches','designs','records'])if(Array.isArray(data[k]))return data[k];return[]}
function first(obj:any,keys:string[]){for(const k of keys){const v=obj?.[k];if(v!==undefined&&v!==null){if(typeof v==='object')return v;const s=clean(v);if(s)return v}}return''}
function numberText(v:any){const n=Number(v);return Number.isFinite(n)?String(Number(n.toFixed(3))):clean(v,30)}
function formatSize(v:any){if(v===undefined||v===null)return'';if(typeof v!=='object')return clean(v,100);const w=first(v,['width','w','horizontal','x']);const h=first(v,['height','h','vertical','y']);const unit=clean(first(v,['unit','units','measurementUnit','measurement_unit']),20);if(w!==''&&h!==''){const base=`${numberText(w)} × ${numberText(h)}`;return unit?`${base} ${unit}`:base}const named=clean(first(v,['name','label','displayName','display_name','value']),100);if(named)return named;return''}
function deepUrl(obj:any,keyPattern:RegExp,depth=0):string{if(!obj||typeof obj!=='object'||depth>4)return'';for(const [k,v] of Object.entries(obj)){if(typeof v==='string'&&keyPattern.test(k)&&/^https?:\/\//i.test(v.trim()))return clean(v,1600)}for(const v of Object.values(obj)){if(v&&typeof v==='object'){const found=deepUrl(v,keyPattern,depth+1);if(found)return found}}return''}
function normalizeDesign(row:any){const id=clean(first(row,['designID','designId','design_id','id']),120);const name=clean(first(row,['name','designName','title','description']),180)||'PCM design';const status=clean(first(row,['status','state','active']),80);const type=clean(first(row,['designType','design_type','type','mailPieceType','mail_piece_type','productType','product_type']),80);const rawSize=first(row,['size','mailSize','mail_size','format','dimensions','dimension']);const size=formatSize(rawSize);const orientation=clean(first(row,['orientation','layout']),60);const thumbnail_url=deepUrl(row,/(thumbnail|preview|image).*url|url.*(thumbnail|preview|image)/i);const proof_url=deepUrl(row,/(proof|pdf).*url|url.*(proof|pdf)/i);const front_url=deepUrl(row,/(front).*url|url.*front/i);const back_url=deepUrl(row,/(back).*url|url.*back/i);return{id,name,status,type,size,orientation,thumbnail_url,proof_url,front_url,back_url,has_provider_asset:Boolean(thumbnail_url||proof_url||front_url||back_url)}}
function primitives(obj:any){if(!obj||typeof obj!=='object'||Array.isArray(obj))return{};const out:Record<string,unknown>={};for(const [k,v] of Object.entries(obj)){if(Object.keys(out).length>=18)break;if(['string','number','boolean'].includes(typeof v)||v===null)out[k]=typeof v==='string'?clean(v,240):v}return out}
function summary(data:any,kind='generic'){const list=rows(data);return{count:list.length,sample:kind==='design'?list.slice(0,24).map(normalizeDesign):list.slice(0,12).map(primitives),top_level:Array.isArray(data)?['array']:Object.keys(data||{}).slice(0,20)}}
async function getJson(t:string,path:string){const r=await fetch(PCM+path,{headers:{Authorization:`Bearer ${t}`,Accept:'application/json'}});const text=await r.text();let d:any={};try{d=JSON.parse(text)}catch{}return{response:r,data:d}}
async function getRoute(t:string,path:string,kind='generic'){const {response:r,data:d}=await getJson(t,path);return{path,status:r.status,ok:r.ok,...summary(d,kind)}}
function findRawDesign(data:any,id:string){const target=clean(id,120);if(!target)return null;for(const row of rows(data)){const rid=clean(first(row,['designID','designId','design_id','id']),120);if(rid===target)return row}return null}
async function designDetail(t:string,id:string){const direct=await getJson(t,`/design/${encodeURIComponent(id)}`);if(direct.response.ok&&direct.data&&typeof direct.data==='object'){const candidate=Array.isArray(direct.data)?direct.data[0]:(direct.data?.data&&typeof direct.data.data==='object'&&!Array.isArray(direct.data.data)?direct.data.data:direct.data);const normalized=normalizeDesign(candidate);if(normalized.id||Object.keys(candidate||{}).length)return{design:{...normalized,id:normalized.id||id},source:'design_detail',http_status:direct.response.status}}
const catalog=await getJson(t,'/design');const raw=findRawDesign(catalog.data,id);return{design:raw?normalizeDesign(raw):null,source:'catalog',http_status:catalog.response.status,catalog_count:rows(catalog.data).length}}

Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors(req)});if(req.method!=='POST')return reply(req,405,{error:'Method not allowed'});const origin=req.headers.get('origin')||'';if(origin&&!ORIGINS.has(origin))return reply(req,403,{error:'Origin not allowed'});const auth=req.headers.get('Authorization')||'';if(!auth.startsWith('Bearer '))return reply(req,401,{error:'Sign in required'});const client=createClient(URL,ANON,{global:{headers:{Authorization:auth}},auth:{persistSession:false}});const{data:{user},error:authError}=await client.auth.getUser();if(authError||!user)return reply(req,401,{error:'Session could not be verified'});const access=await client.rpc('marketing_studio_bootstrap');if(access.error)return reply(req,403,{error:'Marketing Studio access required'});let body:any={};try{body=await req.json()}catch{};const action=clean(body.action||'catalog',40);let t='';try{t=await token()}catch(e){return reply(req,502,{error:clean(e instanceof Error?e.message:e,300)})}
if(action==='catalog'){const [designs,orders,batches]=await Promise.all([getRoute(t,'/design','design'),getRoute(t,'/order'),getRoute(t,'/batch')]);return reply(req,200,{environment:'sandbox',read_only:true,checked_at:new Date().toISOString(),designs,orders,batches})}
if(action==='design.validate'||action==='design.detail'){const id=clean(body.design_id,120);if(!id)return reply(req,400,{error:'design_id is required'});const detail=await designDetail(t,id);return reply(req,200,{environment:'sandbox',read_only:true,design_id:id,valid:Boolean(detail.design),detail_source:detail.source,http_status:detail.http_status,catalog_count:(detail as any).catalog_count??null,design:detail.design})}
return reply(req,400,{error:'Unknown action'});
});
