import { createClient } from 'npm:@supabase/supabase-js@2.95.0';
const URL=Deno.env.get('SUPABASE_URL')!,ANON=Deno.env.get('SUPABASE_ANON_KEY')!,SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const PCM='https://v3.pcmintegrations.com';
const ORIGINS=new Set(['https://njpropertytaxrelief.com','https://www.njpropertytaxrelief.com']);
const MAX=5000;
function cors(req:Request){const o=req.headers.get('origin')||'';return{'Access-Control-Allow-Origin':ORIGINS.has(o)?o:'https://njpropertytaxrelief.com','Access-Control-Allow-Headers':'authorization, apikey, content-type, x-client-info','Access-Control-Allow-Methods':'POST, OPTIONS','Cache-Control':'private, no-store','Vary':'Origin'}}
function reply(req:Request,status:number,body:unknown){return new Response(JSON.stringify(body),{status,headers:{...cors(req),'Content-Type':'application/json; charset=utf-8'}})}
function clean(v:unknown,n=500){return String(v??'').trim().replace(/[\u0000-\u001f]/g,'').slice(0,n)}
async function sha(v:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return Array.from(new Uint8Array(d)).map(x=>x.toString(16).padStart(2,'0')).join('')}
function tokenFrom(d:any){return clean(d?.token??d?.accessToken??d?.access_token??d?.code,4000)}
async function pcmToken(){const key=Deno.env.get('PCM_SANDBOX_API_KEY')||'',secret=Deno.env.get('PCM_API_SECRET')||Deno.env.get('PCM_SANDBOX_API_SECRET')||'';if(!key||!secret)throw new Error('PCM sandbox credentials are incomplete');const r=await fetch(PCM+'/auth/login',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify({apiKey:key,apiSecret:secret})});const text=await r.text();let d:any={};try{d=JSON.parse(text)}catch{}const t=tokenFrom(d);if(!r.ok||!t)throw new Error(`PCM sandbox login failed (${r.status})`);return t}
async function designValid(token:string,id:string){if(!id)return{valid:false,http_status:null,source:'missing'};let r=await fetch(PCM+'/design/'+encodeURIComponent(id),{headers:{Authorization:`Bearer ${token}`,Accept:'application/json'}});if(r.ok){await r.body?.cancel();return{valid:true,http_status:r.status,source:'detail'}}await r.body?.cancel();r=await fetch(PCM+'/design',{headers:{Authorization:`Bearer ${token}`,Accept:'application/json'}});const text=await r.text();let d:any={};try{d=JSON.parse(text)}catch{}const rows=Array.isArray(d)?d:Array.isArray(d?.data)?d.data:Array.isArray(d?.designs)?d.designs:[];const found=rows.some((x:any)=>String(x?.designID??x?.designId??x?.design_id??x?.id??'')===id);return{valid:found,http_status:r.status,source:'catalog'}}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors(req)});if(req.method!=='POST')return reply(req,405,{error:'Method not allowed'});const origin=req.headers.get('origin')||'';if(origin&&!ORIGINS.has(origin))return reply(req,403,{error:'Origin not allowed'});const auth=req.headers.get('Authorization')||'';if(!auth.startsWith('Bearer '))return reply(req,401,{error:'Sign in required'});const uc=createClient(URL,ANON,{global:{headers:{Authorization:auth}},auth:{persistSession:false}}),admin=createClient(URL,SERVICE,{auth:{persistSession:false}});const{data:{user},error:ae}=await uc.auth.getUser();if(ae||!user)return reply(req,401,{error:'Session could not be verified'});const access=await uc.rpc('marketing_studio_bootstrap');if(access.error)return reply(req,403,{error:'Marketing Studio access required'});const body=await req.json().catch(()=>({})),campaignId=clean(body.campaign_id,80);if(!campaignId)return reply(req,400,{error:'campaign_id is required'});
const campaignQ=await admin.from('marketing_campaigns').select('id,name,status,goal,profession').eq('id',campaignId).eq('user_id',user.id).maybeSingle();if(campaignQ.error||!campaignQ.data)return reply(req,404,{error:'Campaign not found'});const campaign=campaignQ.data;
const creativeQ=await admin.from('marketing_creatives').select('id,creative_type,provider_design_id,content,status,approved_at').eq('campaign_id',campaignId).eq('user_id',user.id).order('approved_at',{ascending:false,nullsFirst:false}).order('version',{ascending:false}).limit(1).maybeSingle();const creative=creativeQ.data;
const recQ=await admin.from('marketing_direct_mail_recipients').select('property_key,recipient_name,address,city,state,zip,validation_status').eq('campaign_id',campaignId).eq('user_id',user.id).limit(MAX);const all=recQ.data||[],valid=all.filter((r:any)=>r.validation_status==='valid'),invalid=all.filter((r:any)=>r.validation_status!=='valid');
const quoteQ=await admin.from('marketing_price_quotes').select('id,quantity,vendor_cost_cents,retail_cents,margin_cents,expires_at,pricing_detail,provider_key,channel').eq('campaign_id',campaignId).eq('user_id',user.id).eq('provider_key','pcm').order('created_at',{ascending:false}).limit(1).maybeSingle();const quote=quoteQ.data;
const payQ=await admin.from('marketing_payments').select('id,quote_id,status,amount_cents,refunded_cents,paid_at').eq('campaign_id',campaignId).eq('user_id',user.id).order('created_at',{ascending:false}).limit(1).maybeSingle();const payment=payQ.data;
const approvalQ=await admin.from('marketing_launch_approvals').select('id,creative_id,quote_id,payment_id,recipient_count,status,approved_at').eq('campaign_id',campaignId).eq('user_id',user.id).eq('provider_key','pcm').eq('channel','direct_mail').order('approved_at',{ascending:false,nullsFirst:false}).limit(1).maybeSingle();const approval=approvalQ.data;
let token='',providerError='';try{token=await pcmToken()}catch(e){providerError=clean(e instanceof Error?e.message:e,400)}const designId=clean(creative?.provider_design_id,80);const design=token?await designValid(token,designId):{valid:false,http_status:null,source:'provider_unavailable'};
const quoteCurrent=Boolean(quote&&new Date(quote.expires_at||0).getTime()>Date.now()&&Number(quote.quantity||0)===valid.length);const paid=Boolean(payment&&payment.status==='paid'&&Number(payment.refunded_cents||0)===0&&quote&&payment.quote_id===quote.id);const approvalCurrent=Boolean(approval&&approval.status==='approved'&&creative&&approval.creative_id===creative.id&&quote&&approval.quote_id===quote.id&&payment&&approval.payment_id===payment.id&&Number(approval.recipient_count||0)===valid.length);
const mailClass=clean(creative?.content?.mail_class||'Standard',20)==='FirstClass'?'FirstClass':'Standard',designValue=/^\d+$/.test(designId)?Number(designId):designId,extRefNbr=`WD-${campaignId.slice(0,8)}-CERT`;
const providerPayload=creative&&designId&&valid.length?[{extRefNbr,orderConfig:{designID:designValue,mailClass,globalDesignVariables:[]},recipientList:valid.map((r:any)=>({firstName:'Current',lastName:'Resident',address:clean(r.address,140),address2:'',city:clean(r.city,80),state:clean(r.state||'NJ',2),zipCode:clean(r.zip,10).replace(/\D/g,'').slice(0,5),extRefNbr:clean(r.property_key,160),recipientDesignVariables:[]}))}]:null;
const payloadHash=providerPayload?await sha(JSON.stringify(providerPayload)):null;
const gates=[
 {key:'campaign',label:'Campaign exists',ok:true},
 {key:'creative',label:'Creative approved',ok:Boolean(creative&&creative.status==='approved')},
 {key:'design_id',label:'PCM design selected',ok:Boolean(designId)},
 {key:'design_valid',label:'PCM sandbox recognizes design',ok:Boolean(design.valid)},
 {key:'recipients',label:'Mail-ready recipients prepared',ok:valid.length>0,detail:`${valid.length} ready · ${invalid.length} need review`},
 {key:'quote',label:'Current server quote matches recipients',ok:quoteCurrent},
 {key:'payment',label:'Campaign payment captured',ok:paid},
 {key:'approval',label:'Explicit launch approval matches campaign snapshot',ok:approvalCurrent},
 {key:'provider',label:'PCM sandbox authentication',ok:Boolean(token),detail:providerError||'Authenticated'},
 {key:'live_lock',label:'Production remains locked during certification',ok:true,detail:'No provider mutation was called'}
];
const ready=gates.filter(g=>g.key!=='live_lock').every(g=>g.ok);
const summary={campaign_id:campaignId,campaign_name:campaign.name,creative_id:creative?.id||null,design_id:designId||null,mail_class:mailClass,recipient_count:valid.length,invalid_recipient_count:invalid.length,quote_id:quote?.id||null,payment_id:payment?.id||null,approval_id:approval?.id||null,payload_hash:payloadHash,provider_design_check:design,provider_payload_preview:providerPayload?{ext_ref_nbr:extRefNbr,design_id:designValue,mail_class:mailClass,recipient_count:valid.length,first_recipient:providerPayload[0].recipientList[0]?{city:providerPayload[0].recipientList[0].city,state:providerPayload[0].recipientList[0].state,zip_code:providerPayload[0].recipientList[0].zipCode,ext_ref_nbr:providerPayload[0].recipientList[0].extRefNbr}:null}:null};
await admin.from('marketing_events').insert({user_id:user.id,campaign_id:campaignId,event_type:'pcm.sandbox_certified',source:'pcm',payload:{ready,payload_hash:payloadHash,gates:gates.map(g=>({key:g.key,ok:g.ok}))}});
return reply(req,200,{environment:'sandbox',read_only:true,provider_mutation_called:false,ready,gates,summary,checked_at:new Date().toISOString()});});