/* Historical Property Time Machine. Uses the private snapshot ledger attached to each saved property. */
(function () {
  'use strict';
  function snapshotPoints(r) {
    var raw = Array.isArray(r.history) ? r.history : [];
    var points = raw.map(function (h) { return { seen:h.seen||h.created_at||h.captured_at||h.date||'', assessed:+(h.assessed||h.assessed_value||h.av_total||0), tax:+(h.last_year_tax||h.tax||h.tax_bill||0) }; });
    points.push({ seen:r.updated_at||r.last_seen||new Date().toISOString(), assessed:+r.assessed||0, tax:+r.last_year_tax||0 });
    points = points.filter(function (p) { return p.assessed > 0 || p.tax > 0; }).sort(function (a,b) { return new Date(a.seen||0)-new Date(b.seen||0); });
    return points.filter(function (p,i) { if (!i) return true; var q=points[i-1]; return p.assessed!==q.assessed||p.tax!==q.tax||String(p.seen).slice(0,10)!==String(q.seen).slice(0,10); });
  }
  function shortDate(v) { if(!v)return 'Date unavailable';var d=new Date(v);return isNaN(d.getTime())?String(v).slice(0,10):d.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}); }
  function delta(a,b){return(+b||0)-(+a||0);} function pct(a,b){return +a?delta(a,b)/+a*100:0;}
  function signedMoney(v){return(v>0?'+':v<0?'-':'')+money(Math.abs(v));} function signedPct(v){return(v>0?'+':'')+v.toFixed(1)+'%';}
  function linePath(points,key,w,h){var vals=points.map(function(p){return+p[key]||0;}).filter(function(v){return v>0;});if(!vals.length)return'';var lo=Math.min.apply(null,vals),hi=Math.max.apply(null,vals);return points.map(function(p,i){var x=12+(i/Math.max(1,points.length-1))*(w-24),y=h-14-(((+p[key]||lo)-lo)/((hi-lo)||1))*(h-28);return(i?'L':'M')+x.toFixed(1)+' '+y.toFixed(1);}).join(' ');}
  function explanation(a,b){var da=delta(a.assessed,b.assessed),dt=delta(a.tax,b.tax);if(!da&&!dt)return'No recorded assessment or tax change yet. This first observation is your baseline.';if(!da&&dt)return'The recorded assessment stayed level while the tax bill changed. That usually points to a rate or levy change rather than a reassessment.';if(da&&!dt)return'The assessment changed while the recorded tax figure stayed level. Confirm the effective year before relying on the newest bill.';if((da>0)===(dt>0))return'Assessment and tax moved in the same direction. The two percentages show whether the bill moved faster or slower than the assessment.';return'Assessment and tax moved in different directions. A rate change may have offset part of the assessment movement.';}
  function timeMachineMarkup(r,detailed){var pts=snapshotPoints(r),first=pts[0],last=pts[pts.length-1];if(!first)return'<div class="tl-wait"><i class="fas fa-hourglass-half"></i><div><b>Building your baseline.</b> Open this saved property over time and Watchdog will preserve changes to its assessment and tax figures.</div></div>';var da=delta(first.assessed,last.assessed),dt=delta(first.tax,last.tax);var chart='<div class="tm-chart" role="img" aria-label="Assessment and tax history chart"><svg viewBox="0 0 720 190" preserveAspectRatio="none"><g class="tm-grid"><line x1="12" y1="48" x2="708" y2="48"/><line x1="12" y1="96" x2="708" y2="96"/><line x1="12" y1="144" x2="708" y2="144"/></g><path class="tm-assessed" d="'+linePath(pts,'assessed',720,190)+'"/><path class="tm-tax" d="'+linePath(pts,'tax',720,190)+'"/></svg><div class="tm-legend"><span><i class="assessed"></i>Assessment</span><span><i class="tax"></i>Tax bill</span></div></div>';var events=pts.slice().reverse().map(function(p,i,rev){var older=rev[i+1];return'<li><span class="tm-dot"></span><div><b>'+shortDate(p.seen)+'</b><span>Assessment '+money(p.assessed)+' · Tax '+money(p.tax)+'</span>'+(older?'<small>'+signedMoney(delta(older.assessed,p.assessed))+' assessment · '+signedMoney(delta(older.tax,p.tax))+' tax</small>':'<small>First recorded baseline</small>')+'</div></li>';}).join('');return'<div class="tm-head"><div><span>Observed '+pts.length+' time'+(pts.length===1?'':'s')+'</span><h3>'+esc(r.address||'Saved property')+'</h3></div><div class="tm-range"><span>'+shortDate(first.seen)+'</span><i class="fas fa-arrow-right"></i><span>'+shortDate(last.seen)+'</span></div></div><div class="tm-kpis"><div><span>Assessment change</span><b class="'+(da>0?'up':da<0?'down':'')+'">'+signedMoney(da)+'</b><small>'+signedPct(pct(first.assessed,last.assessed))+'</small></div><div><span>Tax-bill change</span><b class="'+(dt>0?'up':dt<0?'down':'')+'">'+signedMoney(dt)+'</b><small>'+signedPct(pct(first.tax,last.tax))+'</small></div><div><span>Snapshots</span><b>'+pts.length+'</b><small>private observations</small></div></div>'+chart+'<div class="tm-reading"><i class="fas fa-lightbulb"></i><p><b>What changed:</b> '+explanation(first,last)+'</p></div>'+(detailed?'<ol class="tm-events">'+events+'</ol>':'<a class="tm-open" href="/property/home.html?pin='+encodeURIComponent(r.pams_pin||'')+'#sec-history">Open the full timeline <i class="fas fa-arrow-right"></i></a>')+'<p class="tl-fine">Built from snapshots saved when this property is opened. It is an observed Watchdog history, not a complete municipal record for years before tracking began.</p>';}
  function toolDrift(){if(!rows.length)return'';return toolCard('Historical Property Time Machine','fa-clock-rotate-left',rows.map(function(r){return'<article class="tm-property">'+timeMachineMarkup(r,false)+'</article>';}).join(''));}
  function toolTimeMachine(r){return'<div class="tm-detail">'+timeMachineMarkup(r,true)+'</div>';}
  Object.assign(window,{toolDrift:toolDrift,toolTimeMachine:toolTimeMachine,propertySnapshotPoints:snapshotPoints});
})();
export {};
