/* Trusted observed-score ticker/chart. History is read-only in customer clients. */
(function(){'use strict';
var CANONICAL_MARKER='watchdog.watchdog_score',CANONICAL_MODEL='ROBUST-v1';
function arrow(d){return d>0?'↑':d<0?'↓':'→';}function cls(d){return d>0?'up':d<0?'down':'flat';}
function path(pts){if(!pts.length)return'';var vals=pts.map(function(p){return+p.score;}),lo=Math.min.apply(null,vals),hi=Math.max.apply(null,vals);return pts.map(function(p,i){var x=8+i/Math.max(1,pts.length-1)*284,y=70-((+p.score-lo)/((hi-lo)||1))*54;return(i?'L':'M')+x.toFixed(1)+' '+y.toFixed(1);}).join(' ');}
function canonical(pts){return(pts||[]).filter(function(p){var marker=p.marker_id||p.markerId||CANONICAL_MARKER,model=p.model_version||p.modelVersion||CANONICAL_MODEL;return marker===CANONICAL_MARKER&&model===CANONICAL_MODEL;});}
function render(host,pts,current){pts=canonical(pts).slice().sort(function(a,b){return new Date(a.observed_at)-new Date(b.observed_at);});var prior=pts.length>1?+pts[pts.length-2].score:null,d=prior==null?0:current-prior;host.innerHTML='<div class="sh-ticker"><b>'+current+'</b><span class="'+cls(d)+'">'+arrow(d)+' '+(prior==null?'awaiting ROBUST history':Math.abs(d).toFixed(1)+' since prior')+'</span></div><svg class="sh-chart" viewBox="0 0 300 82" preserveAspectRatio="none" aria-label="Verified ROBUST-v1 Watchdog Score history"><path d="'+path(pts)+'"></path></svg><small>'+(pts.length>1?pts.length+' trusted ROBUST-v1 observations':pts.length===1?'First ROBUST-v1 observation · trend starts here':'No ROBUST-v1 historical observation yet')+'</small>';}
function card(r){if(typeof watchdogScore!=='function')return'';var w=watchdogScore(r);if(!w||w.modelVersion!==CANONICAL_MODEL)return'';var id='sh-'+String(r.pams_pin||'x').replace(/[^a-z0-9]/gi,'');setTimeout(function(){var h=document.getElementById(id);if(!h)return;if(typeof watchdogScoreHistory==='function'){watchdogScoreHistory(r,CANONICAL_MARKER,CANONICAL_MODEL).then(function(pts){render(h,pts,w.score);}).catch(function(){render(h,[],w.score);});}else render(h,[],w.score);},0);return'<div class="score-history" data-score-model="'+CANONICAL_MODEL+'"><div><span>WATCHDOG SCORE TREND · ROBUST</span><h3>Verified score history</h3></div><div id="'+id+'"><div class="sh-ticker"><b>'+w.score+'</b><span class="flat">→ loading ROBUST history</span></div></div><p class="tl-fine">Historical points are written by trusted Watchdog data jobs, never by the browser. Only the canonical '+CANONICAL_MODEL+' series is eligible for this trend.</p></div>';}
Object.assign(window,{toolScoreHistory:card});})();export {};
