import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.95.0";

type Obj=Record<string,any>;
const BOLDTRAIL_CONTACTS="https://api.kvcore.com/v2/public/contacts";
const MAX_CONNECTIONS_PER_RUN=10,MAX_PAGES_PER_CONNECTION=8,PAGE_SIZE=500;
const STATUS_LABELS:Record<string,string>={"0":"New","1":"Client","2":"Closed","3":"Sphere","4":"Active","5":"Contract","6":"Archived","7":"Prospect"};
function namedEnv(jsonName:string,legacyName:string){const raw=Deno.env.get(jsonName)||"";if(raw){try{const x=JSON.parse(raw);if(x?.default)return String(x.default)}catch{}}return Deno.env.get(legacyName)||"";}
function clean(v:unknown,max=220){return String(v??"").replace(/[\u0000-\u001f<>]/g,"").trim().slice(0,max);}
function same(a:string,b:string){if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0;}
function isoDate(v:unknown){const raw=clean(v,40);if(!raw)return null;const normalized=/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/.test(raw)?raw.replace(" ","T")+"Z":raw;const d=new Date(normalized);return Number.isFinite(d.getTime())?d.toISOString():null;}
function kvFilterDate(iso:string|null){if(!iso)return null;const d=new Date(iso);if(!Number.isFinite(d.getTime()))return null;d.setUTCSeconds(d.getUTCSeconds()-120);return d.toISOString().slice(0,19).replace("T"," ");}
function validEmail(v:unknown){const x=clean(v,254).toLowerCase();return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(x)?x:null;}
function due(p:Obj){if(!p.sync_enabled||p.sync_status==="revoked")return false;if(!p.last_sync_completed_at)return true;const last=new Date(p.last_sync_completed_at).getTime(),interval=Math.max(Number(p.sync_interval_minutes||15),5)*60000;return !Number.isFinite(last)||last<=Date.now()-interval;}
function normalizeContact(c:Obj,intelligence:boolean){const id=clean(c.id,180);if(!id)return null;return{external_contact_id:id,property_ref:null,property_address:null,contact_name:clean(c.name,180)||null,contact_email:validEmail(c.email),contact_phone:null,lead_stage:STATUS_LABELS[String(c.status)]||(c.status==null?null:`Status ${clean(c.status,20)}`),relationship:clean(c.deal_type,100)||null,last_activity_at:null,tags:[],context:{provider:"boldtrail",crm_authoritative:true,intelligence_eligible:intelligence,source:clean(c.source,120)||null,system_source:clean(c.system_source,120)||null,deal_type:clean(c.deal_type,100)||null,provider_status_code:c.status==null?null:Number(c.status),assigned_agent_id:c.assigned_agent_id==null?null:clean(c.assigned_agent_id,80),assigned_agent_external_id:clean(c.assigned_agent_external_id,120)||null,external_vendor_id:clean(c.external_vendor_id,120)||null},source_updated_at:isoDate(c.updated_at)};}
async function fetchBoldTrailPage(token:string,page:number,filterAt:string|null){const u=new URL(BOLDTRAIL_CONTACTS);u.searchParams.set("limit",String(PAGE_SIZE));u.searchParams.set("page",String(page));if(filterAt)u.searchParams.set("filter[updated_at]",filterAt);const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),12000);try{const res=await fetch(u,{headers:{"Authorization":`Bearer ${token}`,"Accept":"application/json","Content-Type":"application/json"},signal:ctrl.signal});if(!res.ok)throw new Error(`boldtrail_http_${res.status}`);const data=await res.json();if(!data||!Array.isArray(data.data))throw new Error("boldtrail_invalid_response");return data as Obj;}finally{clearTimeout(timer);}}

Deno.serve(async(req)=>{
  if(req.method!=="POST")return new Response(JSON.stringify({error:"Method not allowed"}),{status:405,headers:{"Content-Type":"application/json"}});
  const url=Deno.env.get("SUPABASE_URL")||"",secret=namedEnv("SUPABASE_SECRET_KEYS","SUPABASE_SERVICE_ROLE_KEY");if(!url||!secret)return new Response(JSON.stringify({error:"Worker unavailable"}),{status:503,headers:{"Content-Type":"application/json"}});
  const admin=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}}),supplied=clean(req.headers.get("x-watchdog-provider-worker-token"),500);const {data:expected}=await admin.rpc("integration_get_named_secret",{p_name:"integration_provider_worker_token"});if(!supplied||!expected||!same(supplied,String(expected)))return new Response(JSON.stringify({error:"Unauthorized"}),{status:401,headers:{"Content-Type":"application/json"}});
  let body:Obj={};try{body=await req.json()}catch{}const requestedId=clean(body.connection_id,80),trigger=["connect","manual","schedule","retry"].includes(clean(body.trigger,20))?clean(body.trigger,20):"schedule";let states:Obj[]=[];
  if(requestedId){const {data}=await admin.from("integration_provider_connections").select("*").eq("connection_id",requestedId).maybeSingle();if(data)states=[data];}else{const {data}=await admin.from("integration_provider_connections").select("*").eq("sync_enabled",true).neq("sync_status","revoked").order("last_sync_completed_at",{ascending:true,nullsFirst:true}).limit(50);states=(data||[]).filter(due).slice(0,MAX_CONNECTIONS_PER_RUN);}
  const results:Obj[]=[];
  for(const state of states){
    const {data:connection}=await admin.from("integration_connections").select("*").eq("id",state.connection_id).eq("user_id",state.user_id).maybeSingle();if(!connection||connection.status!=="active"||connection.provider!==state.provider){results.push({connection_id:state.connection_id,status:"skipped",reason:"inactive_connection"});continue;}
    if(state.sync_status==="syncing"&&state.last_sync_started_at){const started=new Date(state.last_sync_started_at).getTime();if(Number.isFinite(started)&&started>Date.now()-20*60000){results.push({connection_id:state.connection_id,status:"skipped",reason:"already_syncing"});continue;}}
    const now=new Date().toISOString();await admin.from("integration_provider_connections").update({sync_status:"syncing",last_sync_started_at:now,last_error:null,updated_at:now}).eq("connection_id",state.connection_id);const runInsert=await admin.from("integration_provider_sync_runs").insert({user_id:state.user_id,connection_id:state.connection_id,provider:state.provider,trigger_source:trigger,status:"running",cursor_from:state.cursor_updated_at||null}).select("id").single(),runId=runInsert.data?.id||null;
    try{
      if(state.provider!=="boldtrail")throw new Error("provider_not_implemented");if(!state.credential_secret_id)throw new Error("provider_credential_missing");const {data:token,error:tokenError}=await admin.rpc("integration_get_secret",{p_secret_id:state.credential_secret_id});if(tokenError||!token)throw new Error("provider_credential_unavailable");
      const meta=state.provider_metadata&&typeof state.provider_metadata==="object"?{...state.provider_metadata}:{},resumePage=Math.max(Number(meta.resume_page||1),1),resumeFilter=clean(meta.resume_filter_at,40)||null,filterAt=resumeFilter||kvFilterDate(state.cursor_updated_at||null);let page=resumePage,pagesProcessed=0,recordsSeen=0,recordsUpserted=0,maxUpdatedAt:string|null=null,complete=false;const intelligence=!!connection.intelligence_access&&(connection.scopes||[]).includes("intelligence.context.read");
      while(pagesProcessed<MAX_PAGES_PER_CONNECTION){const data=await fetchBoldTrailPage(String(token),page,filterAt),contacts=data.data as Obj[];recordsSeen+=contacts.length;const normalized=contacts.map(c=>normalizeContact(c,intelligence)).filter(Boolean);for(const row of normalized as Obj[])if(row.source_updated_at&&(!maxUpdatedAt||row.source_updated_at>maxUpdatedAt))maxUpdatedAt=row.source_updated_at;if(normalized.length){const {data:upserted,error:upsertError}=await admin.rpc("integration_upsert_crm_context_batch",{p_user_id:state.user_id,p_connection_id:state.connection_id,p_rows:normalized});if(upsertError)throw new Error("crm_context_batch_upsert_failed");recordsUpserted+=Number(upserted||0);}pagesProcessed++;const current=Number(data.current_page||page),last=Number(data.last_page||current);if(!Number.isFinite(last)||current>=last||contacts.length===0){complete=true;break;}page=current+1;}
      const completedAt=new Date().toISOString(),nextMeta:Obj={...meta,api_base:"https://api.kvcore.com",api_version:"v2",last_pages_processed:pagesProcessed};let cursorTo=state.cursor_updated_at||null;if(complete){delete nextMeta.resume_page;delete nextMeta.resume_filter_at;cursorTo=maxUpdatedAt||new Date(Date.now()-120000).toISOString();}else{nextMeta.resume_page=page;nextMeta.resume_filter_at=filterAt;}
      await admin.from("integration_provider_connections").update({sync_status:"idle",cursor_updated_at:cursorTo,last_sync_completed_at:completedAt,last_success_at:completedAt,last_error:null,consecutive_failures:0,last_records_seen:recordsSeen,last_records_upserted:recordsUpserted,records_synced_total:Number(state.records_synced_total||0)+recordsUpserted,provider_metadata:nextMeta,updated_at:completedAt}).eq("connection_id",state.connection_id);await admin.from("integration_connections").update({last_inbound_at:completedAt,last_error:null,updated_at:completedAt}).eq("id",state.connection_id).eq("user_id",state.user_id);await admin.from("integration_events").insert({user_id:state.user_id,connection_id:state.connection_id,direction:"inbound",event_type:"crm.contact.sync.batch",event_key:`boldtrail-sync:${runId||crypto.randomUUID()}`,source:"boldtrail.direct",status:"accepted",payload:{provider:"boldtrail",records_seen:recordsSeen,records_upserted:recordsUpserted,pages_processed:pagesProcessed,complete,intelligence_eligible:intelligence},occurred_at:completedAt});if(runId)await admin.from("integration_provider_sync_runs").update({status:"succeeded",cursor_to:cursorTo,records_seen:recordsSeen,records_upserted:recordsUpserted,details:{pages_processed:pagesProcessed,complete,resumed_from_page:resumePage},completed_at:completedAt}).eq("id",runId);await admin.from("integration_audit_log").insert({user_id:state.user_id,connection_id:state.connection_id,action:"provider.sync.succeeded",actor:"system",details:{provider:"boldtrail",trigger,records_seen:recordsSeen,records_upserted:recordsUpserted,pages_processed:pagesProcessed,complete}});results.push({connection_id:state.connection_id,status:"succeeded",records_seen:recordsSeen,records_upserted:recordsUpserted,complete});
    }catch(err){const message=clean(err instanceof Error?err.message:err,500)||"provider_sync_failed",completedAt=new Date().toISOString();await admin.from("integration_provider_connections").update({sync_status:"error",last_sync_completed_at:completedAt,last_error:message,consecutive_failures:Number(state.consecutive_failures||0)+1,updated_at:completedAt}).eq("connection_id",state.connection_id);await admin.from("integration_connections").update({last_error:message,updated_at:completedAt}).eq("id",state.connection_id).eq("user_id",state.user_id);if(runId)await admin.from("integration_provider_sync_runs").update({status:"failed",error_code:message.split(":")[0].slice(0,100),error_message:message,completed_at:completedAt}).eq("id",runId);await admin.from("integration_audit_log").insert({user_id:state.user_id,connection_id:state.connection_id,action:"provider.sync.failed",actor:"system",details:{provider:state.provider,trigger,error:message}});results.push({connection_id:state.connection_id,status:"failed",error:message});}
  }
  return new Response(JSON.stringify({ok:true,processed:results.length,results}),{status:200,headers:{"Content-Type":"application/json","Cache-Control":"no-store"}});
});
