import { createClient } from 'npm:@supabase/supabase-js@2.95.0';
const URL=Deno.env.get('SUPABASE_URL')!,ANON=Deno.env.get('SUPABASE_ANON_KEY')!;
const ORIGINS=new Set(['https://njpropertytaxrelief.com','https://www.njpropertytaxrelief.com']);
const PCM_V3='https://v3.pcmintegrations.com';
const defs:Record<string,{required:string[],optional?:string[],perUserOAuth?:boolean,note:string}>={
 pcm:{required:['PCM_ACCESS_TOKEN'],optional:['PCM_SANDBOX_API_KEY','PCM_API_KEY','PCM_API_SECRET','PCM_TOKEN_URL','PCM_CHILD_REF_NBR'],note:'PostcardMania platform connection for direct-mail fulfillment.'},
 callrail:{required:['CALLRAIL_API_KEY','CALLRAIL_ACCOUNT_ID'],optional:['CALLRAIL_COMPANY_ID'],note:'CallRail platform connection for tracking numbers and call attribution.'},
 google_ads:{required:['GOOGLE_ADS_DEVELOPER_TOKEN','GOOGLE_ADS_CLIENT_ID','GOOGLE_ADS_CLIENT_SECRET'],optional:['GOOGLE_ADS_LOGIN_CUSTOMER_ID'],perUserOAuth:true,note:'Google Ads application connection; each professional must separately authorize an eligible Ads account.'},
 lob:{required:['LOB_API_KEY'],note:'Alternate print/mail provider connection.'},
 sendgrid:{required:['SENDGRID_API_KEY','SENDGRID_FROM_EMAIL'],optional:['SENDGRID_FROM_NAME'],note:'Permission-based email; sender/domain authentication remains provider-side.'},
 twilio_sms:{required:['TWILIO_ACCOUNT_SID','TWILIO_API_KEY','TWILIO_API_KEY_SECRET','TWILIO_MESSAGING_SERVICE_SID'],note:'Permission-based SMS; consent, suppression and quiet-hour controls remain mandatory.'}
};
function cors(req:Request){const o=req.headers.get('origin')||'';return{'Access-Control-Allow-Origin':ORIGINS.has(o)?o:'https://njpropertytaxrelief.com','Access-Control-Allow-Headers':'authorization, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Cache-Control':'private, no-store','Vary':'Origin'}}
function reply(req:Request,status:number,body:unknown){return new Response(JSON.stringify(body),{status,headers:{...cors(req),'Content-Type':'application/json; charset=utf-8'}})}
function configured(key:string){const d=defs[key];if(!d)return{credential_ready:false,per_user_oauth:false};if(key==='pcm'){const sandbox=Boolean(Deno.env.get('PCM_SANDBOX_API_KEY'));const access=Boolean(Deno.env.get('PCM_ACCESS_TOKEN'));const flow=Boolean(Deno.env.get('PCM_API_KEY')&&Deno.env.get('PCM_API_SECRET')&&Deno.env.get('PCM_TOKEN_URL'));return{credential_ready:sandbox||access||flow,per_user_oauth:false}}const credentialReady=d.required.map(secretName=>Boolean(Deno.env.get(secretName))).every(Boolean);return{credential_ready:credentialReady,per_user_oauth:Boolean(d.perUserOAuth)}}
async function pcmSandboxHealth(){const key=Deno.env.get('PCM_SANDBOX_API_KEY')||'';if(!key)return{state:'not_connected',connected:false};try{const res=await fetch(PCM_V3+'/order',{method:'GET',headers:{Authorization:`Bearer ${key}`,Accept:'application/json'}});if(res.ok)return{state:'sandbox_connected',connected:true,http_status:res.status};if(res.status===401||res.status===403)return{state:'sandbox_exchange_required',connected:false,http_status:res.status};return{state:'sandbox_reachable',connected:false,http_status:res.status};}catch(_){return{state:'sandbox_unreachable',connected:false};}}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors(req)});if(req.method!=='POST')return reply(req,405,{error:'Method not allowed'});const origin=req.headers.get('origin')||'';if(origin&&!ORIGINS.has(origin))return reply(req,403,{error:'Origin not allowed'});const auth=req.headers.get('Authorization')||'';if(!auth.startsWith('Bearer '))return reply(req,401,{error:'Sign in required'});const client=createClient(URL,ANON,{global:{headers:{Authorization:auth}},auth:{persistSession:false}});const{data:{user},error:authError}=await client.auth.getUser();if(authError||!user)return reply(req,401,{error:'Session could not be verified'});const access=await client.rpc('marketing_studio_bootstrap');if(access.error)return reply(req,403,{error:'Marketing Studio access required'});const{data:providers,error}=await client.from('marketing_providers').select('provider_key,display_name,provider_type,adapter_version,auth_strategy,capabilities,operations,compliance,docs_url,default_mode').eq('active',true).order('display_name');if(error)return reply(req,503,{error:'Provider catalog unavailable'});const pcmHealth=await pcmSandboxHealth();return reply(req,200,{providers:(providers||[]).map((p:any)=>{const c=configured(p.provider_key);const pcm=p.provider_key==='pcm'?pcmHealth:null;let state=c.credential_ready?(c.per_user_oauth?'authorization_required':'configured'):'not_connected';if(pcm)state=pcm.state;return{key:p.provider_key,name:p.display_name,type:p.provider_type,adapter_version:p.adapter_version,auth_strategy:p.auth_strategy,capabilities:p.capabilities,operations:p.operations,compliance:p.compliance,docs_url:p.docs_url,mode:p.default_mode,credential_ready:c.credential_ready,account_authorization_required:c.per_user_oauth,connection_state:state,sandbox:pcm?{connected:pcm.connected,http_status:pcm.http_status??null}:null,note:defs[p.provider_key]?.note||''}})});});
