import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.95.0";

type Obj=Record<string,any>;
const BOLDTRAIL_CONTACTS="https://api.kvcore.com/v2/public/contacts";
const ORIGINS=new Set(["https://njpropertytaxrelief.com","https://www.njpropertytaxrelief.com","http://localhost:3000","http://127.0.0.1:3000"]);
function namedEnv(jsonName:string,legacyName:string){const raw=Deno.env.get(jsonName)||"";if(raw){try{const p=JSON.parse(raw);if(p?.default)return String(p.default);}catch{}}return Deno.env.get(legacyName)||"";}
function clean(v:unknown,max=220){return String(v??"").replace(/[\u0000-\u001f<>]/g,"").trim().slice(0,max);}
function cors(req:Request){const origin=req.headers.get("origin")||"";const allow=ORIGINS.has(origin)||/^https:\/\/[a-z0-9-]+\.vercel\.app$/i.test(origin)?origin:"https://njpropertytaxrelief.com";return{"Access-Control-Allow-Origin":allow,"Access-Control-Allow-Headers":"authorization, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Cache-Control":"private, no-store","Vary":"Origin"};}
function reply(req:Request,status:number,payload:unknown){return new Response(JSON.stringify(payload),{status,headers:{...cors(req),"Content-Type":"application/json; charset=utf-8"}});}
async function validateToken(token:string){const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),10000);try{const u=new URL(BOLDTRAIL_CONTACTS);u.searchParams.set("limit","1");const r=await fetch(u,{headers:{Authorization:`Bearer ${token}`,Accept:"application/json"},signal:ctrl.signal});if(!r.ok)return{ok:false,status:r.status,total:null};const d=await r.json().catch(()=>({}));return{ok:true,status:r.status,total:Number.isFinite(Number(d?.total))?Number(d.total):null};}catch{return{ok:false,status:0,total:null};}finally{clearTimeout(timer);}}
function publicState(p:Obj|null,c:Obj|null){if(!p||!c)return null;return{connection_id:p.connection_id,provider:p.provider,status:c.status,sync_status:p.sync_status,sync_enabled:!!p.sync_enabled,sync_interval_minutes:Number(p.sync_interval_minutes||15),last_success_at:p.last_success_at||null,last_sync_completed_at:p.last_sync_completed_at||null,last_records_seen:Number(p.last_records_seen||0),last_records_upserted:Number(p.last_records_upserted||0),records_synced_total:Number(p.records_synced_total||0),last_error:p.last_error||c.last_error||null,external_account_label:c.external_account_label||"BoldTrail CRM",updated_at:p.updated_at};}
Deno.serve(async(req)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});if(req.method!=="POST")return reply(req,405,{error:"Method not allowed"});
 const origin=req.headers.get("origin")||"";if(origin&&!ORIGINS.has(origin)&&!/^https:\/\/[a-z0-9-]+\.vercel\.app$/i.test(origin))return reply(req,403,{error:"Origin not allowed"});
 const auth=req.headers.get("authorization")||"";if(!auth.startsWith("Bearer "))return reply(req,401,{error:"Sign in required"});
 const url=Deno.env.get("SUPABASE_URL")||"",pub=namedEnv("SUPABASE_PUBLISHABLE_KEYS","SUPABASE_ANON_KEY"),secret=namedEnv("SUPABASE_SECRET_KEYS","SUPABASE_SERVICE_ROLE_KEY");if(!url||!pub||!secret)return reply(req,503,{error:"CRM service unavailable"});
 const userDb=createClient(url,pub,{global:{headers:{Authorization:auth}},auth:{persistSession:false}}),admin=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});const {data:authData,error:authError}=await userDb.auth.getUser();if(authError||!authData.user)return reply(req,401,{error:"Session could not be verified"});const user=authData.user;
 const {data:beta}=await admin.from("marketing_email_beta_access").select("access_level,expires_at").eq("user_id",user.id).maybeSingle();if(!beta||beta.expires_at&&new Date(beta.expires_at).getTime()<=Date.now())return reply(req,403,{error:"Newsletter Studio is currently a private beta",private_beta:true});
 let body:Obj={};try{body=await req.json();}catch{return reply(req,400,{error:"Invalid JSON"});}const action=clean(body.action,60);
 const getProvider=async()=>{const {data}=await admin.from("integration_provider_connections").select("*").eq("user_id",user.id).eq("provider","boldtrail").maybeSingle();return data||null;};
 const getConnection=async(id:string)=>{const {data}=await admin.from("integration_connections").select("*").eq("id",id).eq("user_id",user.id).maybeSingle();return data||null;};
 const audit=async(id:string|null,kind:string,details:Obj={})=>{await admin.from("integration_audit_log").insert({user_id:user.id,connection_id:id,action:kind,actor:"user",details:{...details,newsletter_private_beta:true}});};
 try{
  if(action==="status"){
   const p=await getProvider(),c=p?await getConnection(p.connection_id):null;let total=0,withEmail=0;if(p&&c&&p.sync_status!=="revoked"){const a=await admin.from("integration_crm_context").select("id",{count:"exact",head:true}).eq("user_id",user.id).eq("connection_id",p.connection_id);total=Number(a.count||0);const b=await admin.from("integration_crm_context").select("id",{count:"exact",head:true}).eq("user_id",user.id).eq("connection_id",p.connection_id).not("contact_email","is",null);withEmail=Number(b.count||0);}return reply(req,200,{private_beta:true,provider:p&&p.sync_status!=="revoked"?publicState(p,c):null,total_contacts:total,contacts_with_email:withEmail});
  }
  if(action==="boldtrail.connect"){
   const token=String(body.api_token||"").trim();if(token.length<20||token.length>5000)return reply(req,400,{error:"A valid BoldTrail API token is required"});const validation=await validateToken(token);if(!validation.ok){await audit(null,"newsletter.boldtrail.validation_failed",{http_status:validation.status||null});return reply(req,400,{error:"BoldTrail credentials could not be verified",provider_status:validation.status||null});}
   const existing=await getProvider(),connectionId=existing?.connection_id||crypto.randomUUID(),stored=await admin.rpc("integration_store_secret",{p_secret:token,p_name:`newsletter:boldtrail:${connectionId}:${Date.now()}`,p_description:"Watchdog Newsletter Studio BoldTrail API token"});if(stored.error||!stored.data)return reply(req,503,{error:"BoldTrail credential could not be secured"});const newSecretId=String(stored.data),oldSecretId=existing?.credential_secret_id?String(existing.credential_secret_id):null,now=new Date().toISOString(),label=clean(body.external_account_label||"BoldTrail CRM",120)||"BoldTrail CRM";
   if(existing){const c=await getConnection(connectionId);if(!c){await admin.rpc("integration_delete_secret",{p_secret_id:newSecretId});return reply(req,409,{error:"Existing BoldTrail connection is inconsistent"});}const cu=await admin.from("integration_connections").update({provider:"boldtrail",name:"BoldTrail Direct",status:"active",direction:"bidirectional",scopes:["crm.contacts.read"],intelligence_access:false,external_account_label:label,last_error:null,metadata:{...(c.metadata||{}),direct_crm:true,provider:"boldtrail",newsletter_private_beta:true},updated_at:now}).eq("id",connectionId).eq("user_id",user.id);if(cu.error){await admin.rpc("integration_delete_secret",{p_secret_id:newSecretId});return reply(req,503,{error:"BoldTrail connection could not be updated"});}const pu=await admin.from("integration_provider_connections").update({credential_secret_id:newSecretId,auth_type:"api_token",sync_enabled:true,sync_status:"idle",last_error:null,consecutive_failures:0,provider_metadata:{api_base:"https://api.kvcore.com",api_version:"v2",validated_total_contacts:validation.total,direct_beta:true,newsletter_private_beta:true},updated_at:now}).eq("connection_id",connectionId).eq("user_id",user.id);if(pu.error){await admin.rpc("integration_delete_secret",{p_secret_id:newSecretId});return reply(req,503,{error:"BoldTrail provider state could not be updated"});}}
   else{const ci=await admin.from("integration_connections").insert({id:connectionId,user_id:user.id,provider:"boldtrail",name:"BoldTrail Direct",status:"active",direction:"bidirectional",event_types:[],scopes:["crm.contacts.read"],intelligence_access:false,external_account_label:label,metadata:{direct_crm:true,provider:"boldtrail",newsletter_private_beta:true}});if(ci.error){await admin.rpc("integration_delete_secret",{p_secret_id:newSecretId});return reply(req,503,{error:"BoldTrail connection could not be created"});}const pi=await admin.from("integration_provider_connections").insert({connection_id:connectionId,user_id:user.id,provider:"boldtrail",auth_type:"api_token",credential_secret_id:newSecretId,sync_enabled:true,sync_status:"idle",sync_interval_minutes:15,provider_metadata:{api_base:"https://api.kvcore.com",api_version:"v2",validated_total_contacts:validation.total,direct_beta:true,newsletter_private_beta:true}});if(pi.error){await admin.from("integration_connections").delete().eq("id",connectionId).eq("user_id",user.id);await admin.rpc("integration_delete_secret",{p_secret_id:newSecretId});return reply(req,503,{error:"BoldTrail provider state could not be created"});}}
   if(oldSecretId&&oldSecretId!==newSecretId)await admin.rpc("integration_delete_secret",{p_secret_id:oldSecretId});const kick=await admin.rpc("integration_kick_provider_sync",{p_connection_id:connectionId,p_trigger:"connect"});await audit(connectionId,existing?"newsletter.boldtrail.reconnected":"newsletter.boldtrail.connected",{validated_total_contacts:validation.total,first_sync_queued:!kick.error});const p=await getProvider(),c=await getConnection(connectionId);return reply(req,existing?200:201,{provider:publicState(p,c),first_sync_queued:!kick.error});
  }
  if(action==="boldtrail.sync"){
   const p=await getProvider();if(!p||p.sync_status==="revoked")return reply(req,404,{error:"BoldTrail is not connected"});const c=await getConnection(p.connection_id);if(!c||c.status!=="active")return reply(req,409,{error:"BoldTrail connection is not active"});const kick=await admin.rpc("integration_kick_provider_sync",{p_connection_id:p.connection_id,p_trigger:"manual"});if(kick.error)return reply(req,503,{error:"BoldTrail sync could not be queued"});await audit(p.connection_id,"newsletter.boldtrail.sync_queued",{request_id:kick.data||null});return reply(req,202,{ok:true,request_id:kick.data||null});
  }
  if(action==="boldtrail.disconnect"){
   const p=await getProvider();if(!p)return reply(req,200,{ok:true,already_disconnected:true});const now=new Date().toISOString();const {count}=await admin.from("integration_crm_context").delete({count:"exact"}).eq("user_id",user.id).eq("connection_id",p.connection_id);await admin.from("integration_provider_connections").update({credential_secret_id:null,sync_enabled:false,sync_status:"revoked",last_error:null,updated_at:now}).eq("connection_id",p.connection_id).eq("user_id",user.id);await admin.from("integration_connections").update({status:"revoked",updated_at:now}).eq("id",p.connection_id).eq("user_id",user.id);if(p.credential_secret_id)await admin.rpc("integration_delete_secret",{p_secret_id:p.credential_secret_id});await audit(p.connection_id,"newsletter.boldtrail.disconnected",{crm_context_rows_removed:Number(count||0)});return reply(req,200,{ok:true,crm_context_rows_removed:Number(count||0)});
  }
  return reply(req,400,{error:"Unknown action"});
 }catch(err){return reply(req,502,{error:clean(err instanceof Error?err.message:err,600)||"CRM request failed"});}
});
