(()=>{
  'use strict';
  const $=id=>document.getElementById(id),money=v=>Number.isFinite(Number(v))?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(v)):'—';
  const score=v=>Number.isFinite(Number(v))?`${Math.round(Number(v)<=1?Number(v)*100:Number(v))}/100`:'—';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const compact=v=>String(v??'').replace(/\s+/g,' ').trim();
  const itemLabel=item=>typeof item==='string'?compact(item):item&&typeof item==='object'?compact(item.label||item.text||item.requirement||item.description||item.name||item.title||Object.values(item).find(v=>typeof v==='string')||''):'';
  const feeLabel=item=>{if(typeof item==='string')return compact(item);if(!item||typeof item!=='object')return'';const label=compact(item.label||item.name||item.type||item.description||'Fee'),amount=item.amount??item.fee??item.cost;return amount!==undefined&&amount!==null?`${label}: ${typeof amount==='number'?money(amount):amount}`:label;};
  const stateMeta=v=>v==='explicit_required'?{label:'REQUIRED',cls:'required'}:v==='official_process_found'?{label:'OFFICIAL PROCESS',cls:'process'}:v==='statewide_baseline'?{label:'STATE BASELINE',cls:'process'}:{label:'VERIFY',cls:''};
  function requirement(row){const state=stateMeta(row.requirement_state),reqs=(row.requirements||[]).map(itemLabel).filter(Boolean),fees=(row.fees||[]).map(feeLabel).filter(Boolean),links=row.links||[];return `<article class="req"><div class="req-head"><b>${esc(row.title||row.requirement_key)}</b><span class="badge ${state.cls}">${state.label}</span></div><p>${esc(row.summary||'Verify the current municipal process before closing.')}</p>${reqs.length?`<ul>${reqs.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}${fees.length?`<div class="fees">${fees.map(x=>`<span class="fee">${esc(x)}</span>`).join('')}</div>`:''}${links.length?`<div class="links">${links.map(x=>`<a href="${esc(x.url)}" target="_blank" rel="noreferrer">${esc(x.label||'Official source')}</a>`).join('')}</div>`:''}</article>`;}
  chrome.storage.local.get(['wdc_last_municipal_packet'],saved=>{
    const packet=saved.wdc_last_municipal_packet,host=$('packet');if(!packet){host.innerHTML='<div class="loading">No municipal packet is available yet. Open a BoldTrail contact and choose Municipal Packet from the Watchdog Agent Command Bar.</div>';return;}
    const f=packet.facts||{},m=packet.municipal||{},rows=m.requirements||[],sources=packet.sources||[];
    host.innerHTML=`<section class="sheet"><header class="top"><div class="brand"><div class="mark">W</div><div><b>WATCHDOG</b><span>Municipal Closing Packet</span></div></div><div class="actions"><button id="wd-copy">Copy summary</button><button class="primary" id="wd-print">Print / Save PDF</button></div></header><div class="eyebrow">Property</div><h1 class="property">${esc(f.address||'Property')}</h1><div class="place">${esc([f.municipality,'NJ',f.zip].filter(Boolean).join(', '))}</div><div class="facts"><div class="fact"><small>Watchdog Score</small><b>${esc(score(f.watchdog_score))}</b></div><div class="fact"><small>Assessment</small><b>${esc(money(f.assessed_value))}</b></div><div class="fact"><small>Annual tax</small><b>${esc(money(f.annual_property_tax))}</b></div><div class="fact"><small>Block / Lot</small><b>${esc([f.block,f.lot].filter(Boolean).join(' / ')||'—')}</b></div></div><div class="note">This packet summarizes Watchdog's official-source municipal research for the matched New Jersey property. Missing web coverage is never treated as “not required.” Confirm current applicability, timing, fees and inspection status with the municipality or enforcing agency before closing.</div><section class="section"><h2>${esc(m.municipality_name||f.municipality||'Municipal')} closing requirements</h2>${rows.length?rows.map(requirement).join(''):'<div class="empty">No municipal registry rows are currently available for this property.</div>'}</section>${sources.length?`<section class="section"><h2>Property-record sources</h2><ul class="sources">${sources.map(s=>`<li>${esc(String(s.kind||'Public record source').replace(/_/g,' '))}${s.recorded_at?` · ${esc(new Date(s.recorded_at).toLocaleDateString())}`:''}${s.url?` · <a href="${esc(s.url)}" target="_blank" rel="noreferrer">source</a>`:''}</li>`).join('')}</ul></section>`:''}<footer class="footer">Generated ${esc(new Date(packet.generated_at||Date.now()).toLocaleString())} · Watchdog CRM Companion ${esc(packet.extension_version||'')} · Research context only. Watchdog does not provide title, legal, appraisal or municipal certification.</footer></section>`;
    $('wd-print')?.addEventListener('click',()=>window.print());
    $('wd-copy')?.addEventListener('click',async()=>{const summary=[`${f.address||''}, ${f.municipality||''} NJ ${f.zip||''}`.trim(),...rows.map(r=>`${r.title||r.requirement_key}: ${stateMeta(r.requirement_state).label}`)].join('\n');try{await navigator.clipboard.writeText(summary);$('wd-copy').textContent='Copied';setTimeout(()=>$('wd-copy').textContent='Copy summary',1800);}catch(_){}});
  });
})();
