import { createClient } from 'npm:@supabase/supabase-js@2.95.0';
const URL=Deno.env.get('SUPABASE_URL')!,ANON=Deno.env.get('SUPABASE_ANON_KEY')!,SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const admin=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
const SCENARIO='njw294_deterministic_v1',PARCEL='watchdog.njplus.parcel_record_volatility',HOUSING='watchdog.njplus.housing_program_record_freshness',PILOT='watchdog.njplus.pilot_revenue_concentration';
const CHANGE='njplus.nj-dca-modiv-longitudinal.parcel_record_change_count',CLASS='njplus.nj-dca-modiv-longitudinal.property_class_history',HSTATUS='njplus.nj-dca-affordable-housing.affordable_housing_reporting_status',PASS='njplus.nj-dca-pilot-forecast.pilot_project_assessment',VALUATION='njplus.nj-dca-ufb-2025.net_debt_three_year_avg_property_valuation';
const ABSECON='0101_25.01_10',ATLANTIC_CITY='0102_139_15';
function json(status:number,p:any){return new Response(JSON.stringify(p),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store, private'}})}
async function hash(v:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,'0')).join('')}
async function cleanup(id:string){await admin.from('watchdog_test_accounts').delete().eq('user_id',id);await admin.from('account_entitlements').delete().eq('user_id',id);await admin.from('profiles').delete().eq('id',id);await admin.auth.admin.deleteUser(id)}
function n(v:any){if(v===null||v===undefined||v==='')return null;const x=Number(v);return Number.isFinite(x)?x:null}
function round(v:number,p=1){const f=10**p;return Math.round(v*f)/f}
function consecutive(history:any){if(!history||typeof history!=='object'||Array.isArray(history))return 0;const years=Object.keys(history).filter(y=>/^(19|20)\d{2}$/.test(y)).map(Number).filter(Number.isFinite).sort((a,b)=>a-b);let c=0;for(let i=1;i<years.length;i++)if(years[i]===years[i-1]+1)c++;return c}
function freshness(){const now=new Date(),today=Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()),release=Date.UTC(2026,6,1),age=Math.max(0,Math.floor((today-release)/86400000));return{age,score:round(Math.max(0,Math.min(100,100-age/365*100)),1)}}
async function post(path:string,body:any,access:string){const r=await fetch(URL+'/functions/v1/'+path,{method:'POST',headers:{Authorization:'Bearer '+access,apikey:ANON,'Content-Type':'application/json'},body:JSON.stringify(body)});let p:any={};try{p=await r.json()}catch{}return{ok:r.ok,status:r.status,p}}
export async function handleNjw294DeterministicBatchCanary(req:Request){let body:any={};try{body=await req.json()}catch{return json(400,{error:'Invalid JSON'})}const token=String(body?.token||'').trim();if(String(body?.scenario||'')!==SCENARIO||!/^[A-Za-z0-9_-]{40,160}$/.test(token))return json(401,{error:'Invalid release canary request'});const now=new Date().toISOString();const {data:gate}=await admin.from('watchdog_test_bootstrap_tokens').update({used_at:now}).eq('token_hash',await hash(token)).is('used_at',null).gt('expires_at',now).contains('metadata',{purpose:'provider_release_canary',scenario:SCENARIO}).select('id,desired_email').maybeSingle();if(!gate)return json(401,{error:'Invalid or expired release canary token'});let userId='';try{const {data:link,error:linkError}=await admin.auth.admin.generateLink({type:'magiclink',email:String(gate.desired_email||'')});userId=String(link?.user?.id||'');const hashed=String(link?.properties?.hashed_token||'');if(linkError||!userId||!hashed)throw new Error('sandbox_link_generation_failed');const authClient=createClient(URL,ANON,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});const {data:v,error:ve}=await authClient.auth.verifyOtp({token_hash:hashed,type:'email'});const access=v?.session?.access_token||'';if(ve||!access)throw new Error('sandbox_session_verification_failed');const pr=await admin.from('profiles').upsert({id:userId,email:String(gate.desired_email||''),full_name:'Watchdog NJW-294 Canary',display_name:'Watchdog NJW-294 Canary',account_role:'developer',plan_tier:'standard',plan:'free',profile_complete:true,custom:{watchdog_test_account:true,no_real_spend:true,release_canary:true,scenario:SCENARIO}},{onConflict:'id'});if(pr.error)throw new Error('sandbox_profile_failed');const ta=await admin.from('watchdog_test_accounts').upsert({user_id:userId,label:'NJW-294 Deterministic Canary',last_bootstrap_at:now,metadata:{no_real_spend:true,scenario:SCENARIO}},{onConflict:'user_id'});if(ta.error)throw new Error('sandbox_account_failed');const started=Date.now(),pins=[ABSECON,ATLANTIC_CITY],rawIds=[CHANGE,CLASS,HSTATUS,PASS,VALUATION];const hydrate=await post('workbench-hydrate',{pams_pins:pins,marker_ids:rawIds},access);const derived=await post('workbench-derived',{pams_pins:pins,marker_ids:[PARCEL,HOUSING,PILOT]},access);const mismatches:string[]=[];const observations:any={};
const ch=n(hydrate.p?.markers?.[ABSECON]?.[CHANGE]),hist=hydrate.p?.markers?.[ABSECON]?.[CLASS],pairs=consecutive(hist),parcelExpected=ch!=null&&pairs>0&&ch<=pairs?round(ch/pairs*100,1):null,parcelActual=derived.p?.markers?.[ABSECON]?.[PARCEL],parcelMeta=derived.p?.meta?.[ABSECON]?.[PARCEL]||{};observations.parcel={expected:parcelExpected,actual:parcelActual,changes:ch,compared:pairs,kind:parcelMeta.provider_kind||null};if(parcelExpected==null||Number(parcelActual)!==parcelExpected||parcelMeta.provider_kind!=='derived_governed')mismatches.push('parcel_record_volatility');
const hstat=hydrate.p?.markers?.[ABSECON]?.[HSTATUS],fresh=freshness(),housingActual=derived.p?.markers?.[ABSECON]?.[HOUSING],housingMeta=derived.p?.meta?.[ABSECON]?.[HOUSING]||{};observations.housing={reporting_status:hstat,age_days:fresh.age,expected:fresh.score,actual:housingActual,kind:housingMeta.provider_kind||null};if(hstat===null||hstat===undefined||Number(housingActual)!==fresh.score||housingMeta.provider_kind!=='derived_governed')mismatches.push('housing_program_record_freshness');
const pa=n(hydrate.p?.markers?.[ATLANTIC_CITY]?.[PASS]),val=n(hydrate.p?.markers?.[ATLANTIC_CITY]?.[VALUATION]),pilotExpected=pa!=null&&val!=null&&val>0?round(pa/Math.max(val,1)*100,4):null,pilotActual=derived.p?.markers?.[ATLANTIC_CITY]?.[PILOT],pilotMeta=derived.p?.meta?.[ATLANTIC_CITY]?.[PILOT]||{};observations.pilot={pilot_assessed_value:pa,three_year_avg_property_valuation:val,expected:pilotExpected,actual:pilotActual,kind:pilotMeta.provider_kind||null,semantic_contract:'assessed-value concentration proxy; not revenue'};if(pilotExpected==null||Number(pilotActual)!==pilotExpected||pilotMeta.provider_kind!=='derived_governed')mismatches.push('pilot_revenue_concentration');
const ok=hydrate.ok&&derived.ok&&mismatches.length===0;await admin.from('watchdog_test_auth_events').insert({token_id:gate.id,user_id:userId,event_type:'provider_release_canary',metadata:{scenario:SCENARIO,status_code:ok?200:502,duration_ms:Date.now()-started,assertion_ok:ok,mismatches,observations}});return json(ok?200:502,{ok,scenario:SCENARIO,assertion_ok:ok,mismatches,observations,duration_ms:Date.now()-started,engine_version:derived.p?.engine_version||null});}catch(e){return json(500,{ok:false,scenario:SCENARIO,error:String((e as Error)?.message||e)})}finally{if(userId)await cleanup(userId)}}
