(function(){
'use strict';
if(window.__WATCHDOG_TRANSACTION_DOCUMENTS__)return;window.__WATCHDOG_TRANSACTION_DOCUMENTS__=true;

const BUCKET='transaction-documents';
const MAX_BYTES=25*1024*1024;
const MIME=new Set(['application/pdf','image/jpeg','image/png']);
const ANALYZABLE=new Set(['title_commitment','lender_commitment','inspection_report']);
const TYPES=[
  ['title_commitment','Title commitment'],['lender_commitment','Lender commitment / conditions'],['inspection_report','Inspection report'],
  ['mortgage_payoff','Mortgage / lien payoff'],['appraisal','Appraisal'],['attorney_review','Attorney review / amendment'],
  ['hoa_condo','HOA / condo package'],['solar_agreement','Solar lease / PPA'],['tenancy','Tenancy / lease'],
  ['estate_probate','Estate / probate'],['divorce','Divorce document'],['bankruptcy','Bankruptcy document'],
  ['final_walkthrough','Final walkthrough'],['closing_package','Closing package / settlement'],['other','Other closing document']
];
const TYPE_LABEL=Object.fromEntries(TYPES);
let db=null,user=null,busy=false,timer=null;
const clean=v=>String(v==null?'':v).trim();
const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function client(){if(db)return db;try{db=window.NJPTRSupabaseRuntime&&window.NJPTRSupabaseRuntime.createClient?window.NJPTRSupabaseRuntime.createClient():null}catch(e){console.warn('Transaction documents client unavailable',e)}return db}
function activeId(){return clean(document.querySelector('.tx-list-card.active')?.dataset?.txId)}
function toast(message,type){const n=document.querySelector('#tx-toast');if(!n)return;n.textContent=message;n.className='tx-toast show '+(type||'');setTimeout(()=>{if(n.textContent===message)n.className='tx-toast'},3600)}
function safeName(name){const raw=clean(name).replace(/[^A-Za-z0-9._,'!&$@=;:+?() -]+/g,'_').replace(/\s+/g,' ').slice(0,180);return raw||'document'}
function fmtSize(n){n=Number(n)||0;if(n>=1048576)return (n/1048576).toFixed(n>=10485760?0:1)+' MB';if(n>=1024)return Math.round(n/1024)+' KB';return n+' B'}
function fmtDate(v){if(!v)return'';const d=new Date(v);return Number.isFinite(d.getTime())?d.toLocaleString('en-US',{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}):''}
function icon(type,mime){if(type==='title_commitment')return'fa-file-signature';if(type==='inspection_report')return'fa-house-circle-check';if(type==='lender_commitment'||type==='mortgage_payoff')return'fa-building-columns';if(mime==='application/pdf')return'fa-file-pdf';return'fa-file-image'}
function findingItemKey(id){return'document_finding_'+clean(id).replace(/[^A-Za-z0-9]/g,'').slice(0,48)}
function injectStyle(){if(document.querySelector('#tx-document-style'))return;const s=document.createElement('style');s.id='tx-document-style';s.textContent=`
.tx-doc-vault{display:grid;gap:14px}.tx-doc-intro{display:flex;align-items:flex-start;justify-content:space-between;gap:14px}.tx-doc-intro p{margin:4px 0 0;color:#627684;font-size:.76rem;line-height:1.5}.tx-doc-private{display:inline-flex;align-items:center;gap:6px;white-space:nowrap;border:1px solid rgba(20,91,95,.16);border-radius:999px;padding:6px 9px;background:#eef7f5;color:#1e6c61;font-size:.66rem;font-weight:800}
.tx-doc-upload{display:grid;grid-template-columns:minmax(175px,.65fr) minmax(220px,1fr) auto;gap:8px;align-items:end;padding:12px;border:1px dashed rgba(16,42,67,.2);border-radius:14px;background:#fafcfc}.tx-doc-upload label{display:grid;gap:5px;font-size:.65rem;font-weight:800;letter-spacing:.03em;text-transform:uppercase;color:#607786}.tx-doc-upload select,.tx-doc-upload input[type=file]{min-height:39px;width:100%;border:1px solid #d7e1e5;border-radius:10px;background:#fff;padding:7px 9px;font:600 .75rem/1.2 Inter,sans-serif;color:#203a4b}.tx-doc-upload input[type=file]{padding:8px}.tx-doc-upload button{min-height:39px}
.tx-doc-list{display:grid;gap:9px}.tx-doc-empty{padding:18px;border:1px solid #e3e9eb;border-radius:13px;background:#fbfcfc;text-align:center;color:#71828c;font-size:.75rem}.tx-doc-entry{border:1px solid #e1e8ea;border-radius:13px;background:#fff;overflow:hidden}.tx-doc-row{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:10px;padding:11px}.tx-doc-icon{display:grid;place-items:center;width:37px;height:37px;border-radius:10px;background:#eef4f5;color:#145b5f}.tx-doc-copy{min-width:0}.tx-doc-copy b{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-size:.76rem;color:#17334d}.tx-doc-copy span{display:block;margin-top:3px;color:#7a8a92;font-size:.65rem}.tx-doc-tags{display:flex;flex-wrap:wrap;gap:5px;margin-top:5px}.tx-doc-tag{border-radius:999px;padding:3px 6px;background:#f1f5f6;color:#5f7380;font-size:.58rem;font-weight:800;text-transform:uppercase;letter-spacing:.035em}.tx-doc-tag.private{background:#eef7f5;color:#1d6f63}.tx-doc-tag.attention{background:#fff0e4;color:#99621f}.tx-doc-actions{display:flex;gap:5px}.tx-doc-actions button{border:1px solid #d8e2e5;background:#fff;color:#345267;border-radius:9px;padding:7px 8px;cursor:pointer}.tx-doc-actions button.analysis{color:#145b5f;background:#f4fbfa}.tx-doc-actions button.danger{color:#9d3f3a}.tx-doc-actions button:disabled{opacity:.5;cursor:not-allowed}
.tx-doc-analysis{border-top:1px solid #e7edef;background:#fafcfc;padding:11px 12px}.tx-doc-analysis-head{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.tx-doc-analysis-head b{font-size:.7rem;color:#26455a}.tx-doc-analysis-head span{font-size:.62rem;color:#758893}.tx-doc-summary{margin:6px 0 8px;font-size:.69rem;line-height:1.45;color:#647987}.tx-doc-findings{display:grid;gap:6px}.tx-doc-finding{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:9px;padding:9px;border:1px solid #e1e8ea;border-radius:10px;background:#fff}.tx-doc-finding strong{display:block;font-size:.69rem;color:#1d3c50}.tx-doc-finding p{margin:3px 0 0;font-size:.66rem;line-height:1.42;color:#637681}.tx-doc-finding small{display:block;margin-top:5px;color:#84939a;font-size:.59rem}.tx-doc-review-actions{display:flex;gap:4px;align-items:center}.tx-doc-review-actions button{border:1px solid #d6e0e3;border-radius:8px;background:#fff;padding:6px 7px;font-size:.61rem;font-weight:800;cursor:pointer}.tx-doc-review-actions .accept{color:#196e5d}.tx-doc-review-actions .reject{color:#99514b}.tx-doc-review-state{border-radius:999px;padding:4px 7px;font-size:.58rem;font-weight:850;text-transform:uppercase}.tx-doc-review-state.accepted{background:#eaf5ef;color:#26715c}.tx-doc-review-state.rejected{background:#f3f4f5;color:#78848a}.tx-doc-ai-note{padding:9px 11px;border-radius:11px;background:#f6f8f9;color:#6d7f88;font-size:.63rem;line-height:1.45}.tx-doc-foot{margin:0;color:#7a8a92;font-size:.66rem;line-height:1.45}
@media(max-width:780px){.tx-doc-intro{display:grid}.tx-doc-upload{grid-template-columns:1fr}.tx-doc-row{grid-template-columns:auto minmax(0,1fr)}.tx-doc-actions{grid-column:1/-1;justify-content:flex-end}.tx-doc-actions button{flex:1}.tx-doc-private{justify-self:start}.tx-doc-finding{grid-template-columns:1fr}.tx-doc-review-actions{justify-content:flex-end}}
`;document.head.appendChild(s)}
function ensureCard(){const grid=document.querySelector('[data-tx-panel="overview"] .tx-overview-grid');if(!grid)return null;let card=document.querySelector('#tx-documents-card');if(card)return card;card=document.createElement('article');card.id='tx-documents-card';card.className='tx-card tx-card-wide';card.innerHTML=`<div class="tx-doc-vault"><div class="tx-doc-intro"><div><span class="tx-eyebrow">PRIVATE CLOSING FILE</span><h3>Documents</h3><p>Keep closing-party documents with the transaction. AI findings remain proposed until you accept or reject them.</p></div><span class="tx-doc-private"><i class="fas fa-lock"></i> Private to this account</span></div><div class="tx-doc-upload"><label>Document type<select id="tx-doc-type">${TYPES.map(([v,l])=>`<option value="${esc(v)}">${esc(l)}</option>`).join('')}</select></label><label>PDF or image<input id="tx-doc-file" type="file" accept="application/pdf,image/jpeg,image/png,.pdf,.jpg,.jpeg,.png"></label><button type="button" class="tx-btn tx-btn-primary" id="tx-doc-upload"><i class="fas fa-cloud-arrow-up"></i> Upload</button></div><div class="tx-doc-ai-note"><i class="fas fa-wand-magic-sparkles"></i> Optional AI review is available for title commitments, lender commitments and inspection reports. When you choose Analyze, the private document is sent to OpenAI's API for processing with response storage disabled (<code>store:false</code>). Standard OpenAI API data controls apply. Findings remain private and require your review.</div><div class="tx-doc-list" id="tx-doc-list"><div class="tx-doc-empty"><i class="fas fa-circle-notch fa-spin"></i> Loading documents…</div></div><p class="tx-doc-foot"><i class="fas fa-shield-halved"></i> Private Storage + account/transaction RLS. Uploading or analyzing a document never changes Watchdog public-source evidence.</p></div>`;grid.appendChild(card);return card}
async function authUser(){const c=client();if(!c)return null;if(user)return user;const r=await c.auth.getUser();user=r?.data?.user||null;return user}
function findingHtml(f){const v=f.value&&typeof f.value==='object'?f.value:{},state=clean(f.review_state)||'proposed';return `<div class="tx-doc-finding" data-finding-id="${esc(f.id)}"><div><strong>${esc(f.label)}</strong><p>${esc(v.text||'Review this document-supplied finding.')}${v.date?` · ${esc(v.date)}`:''}${v.amount?` · ${esc(v.amount)}`:''}</p><small>${f.page_reference?`Source: ${esc(f.page_reference)} · `:''}${esc((f.finding_type||'finding').replace(/_/g,' '))} · ${esc(f.severity||'review')} · document-supplied, not independently verified</small></div><div class="tx-doc-review-actions">${state==='proposed'?`<button type="button" class="accept" data-doc-action="accept-finding"><i class="fas fa-check"></i> Accept</button><button type="button" class="reject" data-doc-action="reject-finding"><i class="fas fa-xmark"></i> Reject</button>`:`<span class="tx-doc-review-state ${esc(state)}">${esc(state)}</span>`}</div></div>`}
function documentHtml(d,findings){const analyzing=d.extraction_status==='processing',canAnalyze=ANALYZABLE.has(d.document_type),proposed=findings.filter(f=>f.review_state==='proposed').length,summary=d.extraction&&typeof d.extraction==='object'?clean(d.extraction.summary):'';return `<div class="tx-doc-entry" data-doc-id="${esc(d.id)}" data-doc-path="${esc(d.storage_path)}" data-doc-type="${esc(d.document_type)}" data-doc-name="${esc(d.original_name)}"><div class="tx-doc-row"><span class="tx-doc-icon"><i class="fas ${icon(d.document_type,d.mime_type)}"></i></span><div class="tx-doc-copy"><b title="${esc(d.original_name)}">${esc(d.original_name)}</b><span>${esc(TYPE_LABEL[d.document_type]||d.document_type)} · ${esc(fmtSize(d.file_size))} · ${esc(fmtDate(d.created_at))}</span><div class="tx-doc-tags"><span class="tx-doc-tag private">Private document</span>${d.version>1?`<span class="tx-doc-tag">Version ${esc(d.version)}</span>`:''}${d.extraction_status&&d.extraction_status!=='not_requested'?`<span class="tx-doc-tag ${d.extraction_status==='failed'?'attention':''}">${esc(d.extraction_status.replace(/_/g,' '))}</span>`:''}${proposed?`<span class="tx-doc-tag attention">${proposed} to review</span>`:''}</div></div><div class="tx-doc-actions"><button type="button" data-doc-action="view" title="Open private document"><i class="fas fa-arrow-up-right-from-square"></i></button>${canAnalyze?`<button type="button" class="analysis" data-doc-action="analyze" title="Analyze for proposed closing findings" ${analyzing?'disabled':''}><i class="fas ${analyzing?'fa-circle-notch fa-spin':'fa-wand-magic-sparkles'}"></i></button>`:''}<button type="button" class="danger" data-doc-action="delete" title="Delete document"><i class="fas fa-trash"></i></button></div></div>${(findings.length||summary)?`<div class="tx-doc-analysis"><div class="tx-doc-analysis-head"><b>Review proposed findings</b><span>${findings.length} finding${findings.length===1?'':'s'}</span></div>${summary?`<p class="tx-doc-summary">${esc(summary)}</p>`:''}<div class="tx-doc-findings">${findings.map(findingHtml).join('')||'<div class="tx-doc-empty">No actionable findings were proposed.</div>'}</div></div>`:''}</div>`}
async function load(){const txId=activeId(),card=ensureCard(),c=client();if(!txId||!card||!c)return;const u=await authUser();if(!u)return;const list=card.querySelector('#tx-doc-list');const r=await c.from('transaction_documents').select('id,document_type,document_label,original_name,storage_path,mime_type,file_size,version,status,extraction_status,extraction,created_at').eq('transaction_id',txId).eq('user_id',u.id).order('created_at',{ascending:false});if(r.error){console.warn('Transaction documents could not load',r.error);list.innerHTML='<div class="tx-doc-empty">Document vault is unavailable for this transaction.</div>';return}const rows=r.data||[];if(!rows.length){list.innerHTML='<div class="tx-doc-empty"><i class="fas fa-file-circle-plus"></i><br>No closing documents uploaded yet.</div>';return}let findings=[];const ids=rows.map(x=>x.id);if(ids.length){const f=await c.from('transaction_document_findings').select('id,document_id,finding_type,label,value,target_item_key,page_reference,severity,confidence,review_state,created_at').eq('transaction_id',txId).eq('user_id',u.id).in('document_id',ids).order('created_at',{ascending:true});if(!f.error)findings=f.data||[]}const byDoc=new Map();findings.forEach(f=>{if(!byDoc.has(f.document_id))byDoc.set(f.document_id,[]);byDoc.get(f.document_id).push(f)});list.innerHTML=rows.map(d=>documentHtml(d,byDoc.get(d.id)||[])).join('')}
async function upload(){if(busy)return;const txId=activeId(),c=client(),card=ensureCard();if(!txId||!c||!card)return;const u=await authUser();if(!u)return;const input=card.querySelector('#tx-doc-file'),typeEl=card.querySelector('#tx-doc-type'),file=input?.files?.[0],type=clean(typeEl?.value);if(!file){toast('Choose a PDF or image first.','error');return}if(!MIME.has(file.type)){toast('Use a PDF, JPG or PNG document.','error');return}if(file.size<=0||file.size>MAX_BYTES){toast('Closing documents must be 25 MB or smaller.','error');return}const id=crypto.randomUUID(),name=safeName(file.name),path=`user/${u.id}/${txId}/${id}/${name}`;busy=true;const button=card.querySelector('#tx-doc-upload'),old=button.innerHTML;button.disabled=true;button.innerHTML='<i class="fas fa-circle-notch fa-spin"></i> Uploading';try{const up=await c.storage.from(BUCKET).upload(path,file,{upsert:false,contentType:file.type,cacheControl:'0'});if(up.error)throw up.error;const ins=await c.from('transaction_documents').insert({id,transaction_id:txId,user_id:u.id,document_type:type,original_name:name,storage_bucket:BUCKET,storage_path:path,mime_type:file.type,file_size:file.size,status:'uploaded',extraction_status:'not_requested',metadata:{supplied_by:'user_upload',independent_public_evidence:false}}).select('id').single();if(ins.error){await c.storage.from(BUCKET).remove([path]).catch(()=>{});throw ins.error}await c.from('transaction_activity').insert({transaction_id:txId,user_id:u.id,action:'transaction_document_upload',message:`Uploaded ${TYPE_LABEL[type]||'closing document'}: ${name}`,detail:{document_id:id,document_type:type,file_size:file.size,private_document:true,independent_public_evidence:false}});input.value='';toast('Closing document uploaded.','success');await load()}catch(e){console.error('Transaction document upload failed',e);toast(clean(e?.message)||'Could not upload the document.','error')}finally{busy=false;button.disabled=false;button.innerHTML=old}}
async function view(row){const c=client();if(!c)return;const path=clean(row?.dataset?.docPath);if(!path)return;const r=await c.storage.from(BUCKET).createSignedUrl(path,300);if(r.error||!r.data?.signedUrl){toast('Could not create a private document link.','error');return}const a=document.createElement('a');a.href=r.data.signedUrl;a.target='_blank';a.rel='noopener';document.body.appendChild(a);a.click();a.remove()}
async function analyze(row){if(busy)return;const c=client(),id=clean(row?.dataset?.docId),type=clean(row?.dataset?.docType);if(!c||!id||!ANALYZABLE.has(type))return;if(!window.confirm('Analyze this private document for closing follow-up? Findings will be proposals only and will not change public evidence.'))return;busy=true;const btn=row.querySelector('[data-doc-action="analyze"]'),old=btn?.innerHTML;if(btn){btn.disabled=true;btn.innerHTML='<i class="fas fa-circle-notch fa-spin"></i>'}try{const r=await c.functions.invoke('transaction-document-extract',{body:{document_id:id}});if(r.error)throw r.error;toast(`${Number(r.data?.finding_count||0)} proposed finding${Number(r.data?.finding_count||0)===1?'':'s'} ready for review.`,'success');await load()}catch(e){console.error('Document analysis failed',e);toast(clean(e?.message)||'Document analysis failed.','error')}finally{busy=false;if(btn){btn.disabled=false;btn.innerHTML=old}}}
async function reviewFinding(row,findingEl,decision){if(busy)return;const txId=activeId(),c=client(),u=await authUser(),docId=clean(row?.dataset?.docId),findingId=clean(findingEl?.dataset?.findingId);if(!txId||!c||!u||!docId||!findingId)return;busy=true;try{const q=await c.from('transaction_document_findings').select('id,document_id,transaction_id,finding_type,label,value,target_item_key,page_reference,severity,review_state').eq('id',findingId).eq('document_id',docId).eq('transaction_id',txId).eq('user_id',u.id).maybeSingle();if(q.error||!q.data)throw q.error||new Error('Finding not found');const f=q.data;if(f.review_state!=='proposed'){await load();return}if(decision==='accepted'){
      const v=f.value&&typeof f.value==='object'?f.value:{},description=`Document-supplied finding: ${clean(v.text)}${f.page_reference?` Source: ${clean(f.page_reference)}.`:''} This is private closing-party evidence and is not independently verified public evidence.`;
      const item={transaction_id:txId,user_id:u.id,category:'Documents',item_key:findingItemKey(f.id),title:clean(f.label).slice(0,180),description,severity:['info','review','attention','blocked'].includes(f.severity)?f.severity:'review',state:'open',evidence_state:'verify',source_type:'private_document',source_label:`Uploaded ${TYPE_LABEL[clean(row?.dataset?.docType)]||'closing document'}`,source_checked_at:null,source_url:null,payload:{document_id:docId,document_finding_id:f.id,document_supplied:true,independent_public_evidence:false,page_reference:f.page_reference||null,target_item_key:f.target_item_key||null,value:v,accepted_by_user:true},sort_order:65};
      const ins=await c.from('transaction_items').upsert(item,{onConflict:'transaction_id,item_key'});if(ins.error)throw ins.error;
    }
    const upd=await c.from('transaction_document_findings').update({review_state:decision,reviewed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',findingId).eq('user_id',u.id);if(upd.error)throw upd.error;
    await c.from('transaction_activity').insert({transaction_id:txId,user_id:u.id,action:'transaction_document_finding_review',message:`${decision==='accepted'?'Accepted':'Rejected'} document finding: ${clean(f.label).slice(0,180)}`,detail:{document_id:docId,finding_id:f.id,decision,private_document:true,independent_public_evidence:false}});toast(decision==='accepted'?'Finding added as a private checklist follow-up.':'Finding rejected.','success');await load();document.dispatchEvent(new CustomEvent('watchdog:transaction-preflight-complete',{detail:{document_review:true,transaction_id:txId}}))
  }catch(e){console.error('Document finding review failed',e);toast(clean(e?.message)||'Could not review the finding.','error')}finally{busy=false}}
async function remove(row){if(busy)return;const txId=activeId(),c=client(),u=await authUser(),id=clean(row?.dataset?.docId),path=clean(row?.dataset?.docPath);if(!txId||!c||!u||!id||!path)return;if(!window.confirm('Delete this private closing document? Accepted document-supplied checklist items from it will also be removed.'))return;busy=true;try{const f=await c.from('transaction_document_findings').select('id').eq('document_id',id).eq('transaction_id',txId).eq('user_id',u.id);if(!f.error&&f.data?.length){const keys=f.data.map(x=>findingItemKey(x.id));await c.from('transaction_items').delete().eq('transaction_id',txId).eq('user_id',u.id).in('item_key',keys)}const rem=await c.storage.from(BUCKET).remove([path]);if(rem.error)throw rem.error;const del=await c.from('transaction_documents').delete().eq('id',id).eq('transaction_id',txId).eq('user_id',u.id);if(del.error)throw del.error;await c.from('transaction_activity').insert({transaction_id:txId,user_id:u.id,action:'transaction_document_delete',message:'Deleted a private closing document',detail:{document_id:id,private_document:true}});toast('Document deleted.','success');await load()}catch(e){console.error('Transaction document delete failed',e);toast(clean(e?.message)||'Could not delete the document.','error')}finally{busy=false}}
function schedule(delay){clearTimeout(timer);timer=setTimeout(()=>load(),delay==null?180:delay)}
function handle(e){if(e.target.closest('#tx-doc-upload')){upload();return}const btn=e.target.closest('[data-doc-action]');if(!btn)return;const row=btn.closest('.tx-doc-entry'),finding=btn.closest('.tx-doc-finding'),action=btn.dataset.docAction;if(action==='view')view(row);if(action==='analyze')analyze(row);if(action==='delete')remove(row);if(action==='accept-finding')reviewFinding(row,finding,'accepted');if(action==='reject-finding')reviewFinding(row,finding,'rejected')}
injectStyle();document.addEventListener('click',e=>{handle(e);if(e.target.closest('.tx-list-card'))schedule(650)});document.addEventListener('watchdog:transaction-preflight-complete',e=>{if(!e.detail?.document_review)schedule(500)});const observer=new MutationObserver(muts=>{for(const m of muts){if(Array.from(m.addedNodes).some(n=>n.nodeType===1&&(n.matches?.('[data-tx-panel="overview"],.tx-overview-grid')||n.querySelector?.('[data-tx-panel="overview"],.tx-overview-grid')))){schedule(180);break}}});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{observer.observe(document.body,{childList:true,subtree:true});schedule(1100)},{once:true});else{observer.observe(document.body,{childList:true,subtree:true});schedule(1100)}
})();
