(function(){
'use strict';
if(window.__WATCHDOG_TRANSACTION_EVIDENCE_ADDONS__)return;window.__WATCHDOG_TRANSACTION_EVIDENCE_ADDONS__=true;

let client=null,timer=null,busy=false;
const clean=v=>String(v==null?'':v).trim();
const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function getClient(){if(client)return client;try{client=window.NJPTRSupabaseRuntime&&window.NJPTRSupabaseRuntime.createClient?window.NJPTRSupabaseRuntime.createClient():null}catch(e){console.warn('Transaction evidence add-ons client unavailable',e)}return client}
function fmtDate(v){if(!v)return'';const d=new Date(v);return Number.isFinite(d.getTime())?d.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):String(v).slice(0,10)}
function row(label,value){return value!==undefined&&value!==null&&String(value)!==''?`<div class="tx-evidence-row"><span>${esc(label)}</span><b>${esc(value)}</b></div>`:''}
function link(url,label){return url?`<a class="tx-source-link" href="${esc(url)}" target="_blank" rel="noopener">${esc(label)} <i class="fas fa-arrow-up-right-from-square"></i></a>`:''}
function payload(item){return item&&item.payload&&typeof item.payload==='object'?item.payload:{}}
function activeId(){return clean(document.querySelector('.tx-list-card.active')?.dataset?.txId)}
function status(item){const p=payload(item);if(item.item_key==='solar'&&p.solar_observed)return{label:'PUBLIC EVIDENCE',cls:'attention'};if(item.evidence_state==='issue_observed')return{label:'ATTENTION',cls:'attention'};if(item.evidence_state==='clear_observed')return{label:'CHECKED',cls:'checked'};if(item.source_checked_at)return{label:'REVIEW',cls:'review'};return{label:'NOT CHECKED',cls:'missing'}}
function solarBody(item){const p=payload(item),program=Array.isArray(p.solar_program_records)?p.solar_program_records:[],permits=Array.isArray(p.solar_permit_records)?p.solar_permit_records:[];
  if(p.solar_observed){
    const recs=program.slice(0,4).map(r=>`<div class="tx-record"><b>${esc(r.company_on_program_record||r.project_number||'NJDEP solar record')}</b><span>${esc([r.completion_year,r.system_size_kw!=null?`${r.system_size_kw} kW`:null].filter(Boolean).join(' · ')||'Public solar program evidence')}</span>${r.project_number?`<small>Project ${esc(r.project_number)}</small>`:''}${r.third_party_ownership?`<small>Third-party ownership: ${esc(r.third_party_ownership)}</small>`:''}${r.electric_distribution_company?`<small>EDC: ${esc(r.electric_distribution_company)}</small>`:''}</div>`).join('');
    const permitRows=permits.slice(0,4).map(r=>`<div class="tx-record"><b>${esc(r.permit_number||'Solar permit')}</b><span>${esc(fmtDate(r.permit_date)||r.status||'Permit evidence')}</span>${r.description?`<small>${esc(r.description)}</small>`:''}</div>`).join('');
    return `<div class="tx-evidence-box"><div class="tx-evidence-kicker">Public solar evidence matched</div>${row('Third-party ownership',p.third_party_ownership_observed?'Observed in NJDEP record':'Not affirmatively observed')}${row('Payoff / transfer balance','Provider or customer authorization required')}${recs?`<div class="tx-record-stack">${recs}</div>`:''}${permitRows?`<div class="tx-record-stack">${permitRows}</div>`:''}<p>${esc(p.coverage_note||item.description||'Confirm ownership, financing, lease/PPA and transfer requirements with the seller and provider.')}</p></div>`;
  }
  return `<div class="tx-evidence-empty search"><i class="fas fa-solar-panel"></i><div><b>No property-specific public solar match</b><span>${esc(item.description||'Public solar and permit sources were checked, but they are not complete enough to prove that no solar system exists. Seller/provider verification is still required.')}</span></div></div>`;
}
function electricBody(item){const p=payload(item),provider=clean(p.provider_name);return `<div class="tx-evidence-box"><div class="tx-evidence-kicker">Electric service territory</div>${row('Distribution utility',provider||'Could not resolve one utility')}${row('Current account balance',p.account_balance_state==='customer_authorization_required'?'Customer authorization required':clean(p.account_balance_state).replace(/_/g,' ')||'Verification required')}${row('Final bill / transfer clearance',p.final_bill_clearance===true?'Cleared':p.final_bill_clearance===false?'Not cleared by this public source':'Verification required')}${p.geocode_match?row('Address match',p.geocode_match):''}<p>${esc(item.description||'Service-territory data identifies the electric provider; account balances and final-bill status remain private customer data.')}</p></div>`}
function card(item){const p=payload(item),s=status(item),solar=item.item_key==='solar',checked=item.source_checked_at?fmtDate(item.source_checked_at):'';let links='';if(solar){(Array.isArray(p.public_sources_checked)?p.public_sources_checked:[]).slice(0,2).forEach((u,i)=>{links+=link(u,i===0?'Permit source':'Solar source')})}else if(p.provider_portal){links+=link(p.provider_portal,'Utility portal')}if(item.source_url)links+=link(item.source_url,'Open source');return `<article class="tx-source-card ${s.cls}" data-evidence-addon-key="${esc(item.item_key)}"><div class="tx-source-card-top"><span class="tx-source-card-icon"><i class="fas ${solar?'fa-solar-panel':'fa-bolt'}"></i></span><span class="tx-source-status">${esc(s.label)}</span></div><strong>${esc(item.title||(solar?'Solar ownership / PPA / lease':'Electric utility / account transfer'))}</strong>${solar?solarBody(item):electricBody(item)}<div class="tx-source-provenance"><span>${esc(item.source_label||item.source_type||'Watchdog public evidence')}</span>${checked?`<small>Checked ${esc(checked)}</small>`:''}</div><div class="tx-source-actions">${links}</div></article>`}
async function render(force){const id=activeId(),grid=document.querySelector('#tx-source-sweep .tx-source-grid');if(!id||!grid||busy)return;if(!force&&grid.querySelector('[data-evidence-addon-key]'))return;const c=getClient();if(!c)return;busy=true;try{const r=await c.from('transaction_items').select('item_key,title,evidence_state,severity,source_type,source_label,source_url,source_checked_at,description,payload').eq('transaction_id',id).in('item_key',['solar','electric_utility']);if(r.error)return;grid.querySelectorAll('[data-evidence-addon-key]').forEach(n=>n.remove());const by=Object.fromEntries((r.data||[]).map(x=>[x.item_key,x]));['solar','electric_utility'].forEach(k=>{if(by[k])grid.insertAdjacentHTML('beforeend',card(by[k]))})}catch(e){console.warn('Transaction energy cards could not render',e)}finally{busy=false}}
function schedule(force,delay){clearTimeout(timer);timer=setTimeout(()=>render(Boolean(force)),delay==null?180:delay)}
document.addEventListener('watchdog:transaction-preflight-complete',()=>schedule(true,450));
document.addEventListener('click',e=>{if(e.target.closest('.tx-list-card'))schedule(true,550)});
const observer=new MutationObserver(muts=>{if(busy)return;for(const m of muts){if([...m.addedNodes].some(n=>n.nodeType===1&&(n.matches?.('#tx-source-sweep,.tx-source-grid')||n.querySelector?.('#tx-source-sweep,.tx-source-grid')))){schedule(false,160);break}}});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{observer.observe(document.body,{childList:true,subtree:true});schedule(true,850)},{once:true});else{observer.observe(document.body,{childList:true,subtree:true});schedule(true,850)}
setTimeout(()=>schedule(false,0),2200);
})();
