(function(){
'use strict';
if(window.__WATCHDOG_MUNICIPAL_STATUS_WORKFLOWS__)return;window.__WATCHDOG_MUNICIPAL_STATUS_WORKFLOWS__=true;

const DEFINITIONS={
  permit_certificate_lifecycle:{
    match:/permits?\s*&\s*certificates?/i,
    kicker:'Municipal permit final status',
    states:[['not_checked','Not checked'],['municipality_contacted','Municipality contacted'],['inspection_scheduled','Inspection scheduled'],['corrections_required','Corrections required'],['reinspection_scheduled','Reinspection scheduled'],['final_approved','Final approved / closed']],
    completion:'final_approved'
  },
  resale_cco:{
    match:/certificate of occupancy|\bcco\b/i,
    kicker:'Resale CO / CCO status',
    states:[['not_started','Not started'],['application_submitted','Application submitted'],['inspection_scheduled','Inspection scheduled'],['corrections_required','Corrections required'],['reinspection_scheduled','Reinspection scheduled'],['approved_issued','Approved / issued']],
    completion:'approved_issued'
  },
  smoke_fire_cert:{
    match:/smoke\s*\/\s*co\s*\/\s*fire|smoke.*fire/i,
    kicker:'Smoke / CO / fire status',
    states:[['not_started','Not started'],['application_submitted','Request submitted'],['inspection_scheduled','Inspection scheduled'],['corrections_required','Corrections required'],['reinspection_scheduled','Reinspection scheduled'],['approved_issued','Approved / issued']],
    completion:'approved_issued'
  }
};
const clean=v=>String(v==null?'':v).trim();
const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let db=null,user=null,busy=false,timer=null;
function client(){if(db)return db;try{db=window.NJPTRSupabaseRuntime&&window.NJPTRSupabaseRuntime.createClient?window.NJPTRSupabaseRuntime.createClient():null}catch(e){console.warn('Municipal status client unavailable',e)}return db}
function activeId(){return clean(document.querySelector('.tx-list-card.active')?.dataset?.txId)}
function toast(message,type){const n=document.querySelector('#tx-toast');if(!n)return;n.textContent=message;n.className='tx-toast show '+(type||'');setTimeout(()=>{if(n.textContent===message)n.className='tx-toast'},3200)}
function payload(item){return item&&item.payload&&typeof item.payload==='object'?item.payload:{}}
function statusOf(item,key){const p=payload(item),raw=p.municipal_status_workflow&&typeof p.municipal_status_workflow==='object'?p.municipal_status_workflow:{};const def=DEFINITIONS[key];const state=def.states.some(x=>x[0]===raw.state)?raw.state:def.states[0][0];return {...raw,state}}
function cardFor(key){const def=DEFINITIONS[key];return Array.from(document.querySelectorAll('#tx-source-sweep .tx-source-card')).find(card=>def.match.test(clean(card.querySelector('strong')?.textContent)))}
function indexOf(def,state){const i=def.states.findIndex(x=>x[0]===state);return i<0?0:i}
function nextOf(def,state){const i=indexOf(def,state);return i<def.states.length-1?def.states[i+1][0]:''}
function labelOf(def,state){return (def.states.find(x=>x[0]===state)||def.states[0])[1]}
function injectStyle(){if(document.querySelector('#tx-municipal-status-style'))return;const s=document.createElement('style');s.id='tx-municipal-status-style';s.textContent=`
.tx-muni-status{margin:14px 0 2px;padding:14px;border:1px solid rgba(16,42,67,.12);border-radius:16px;background:rgba(248,250,252,.94)}
.tx-muni-status-kicker{font-size:.7rem;font-weight:800;letter-spacing:.08em;color:#486581;text-transform:uppercase;margin-bottom:8px}.tx-muni-status-copy{font-size:.76rem;line-height:1.45;color:#52606d;margin:8px 0 11px}
.tx-muni-status-steps{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:5px;margin:9px 0 11px}.tx-muni-status-step{font-size:.62rem;font-weight:700;line-height:1.2;text-align:center;padding:7px 4px;border-radius:9px;background:#eef2f6;color:#7b8794}.tx-muni-status-step.done{background:#e8f5ee;color:#147d4f}.tx-muni-status-step.current{background:#eaf2ff;color:#174ea6;box-shadow:inset 0 0 0 1px rgba(23,78,166,.12)}.tx-muni-status-step.problem{background:#fff1e6;color:#9a3412}
.tx-muni-status-actions{display:flex;flex-wrap:wrap;gap:7px}.tx-muni-status-actions button{border:0;border-radius:10px;padding:8px 10px;font:inherit;font-size:.72rem;font-weight:750;cursor:pointer;background:#123b5d;color:#fff}.tx-muni-status-actions button.secondary{background:#fff;color:#334e68;border:1px solid #cbd5e1}.tx-muni-status-actions button.warn{background:#fff6e5;color:#8a4b08;border:1px solid #f1c27d}
.tx-muni-status-note{display:flex;gap:8px;align-items:flex-start;margin-top:10px;font-size:.69rem;line-height:1.35;color:#6b7280}@media(max-width:760px){.tx-muni-status-steps{grid-template-columns:repeat(2,minmax(0,1fr))}.tx-muni-status-actions>*{flex:1 1 auto}}
`;document.head.appendChild(s)}
function markup(item,key,w){const def=DEFINITIONS[key],idx=indexOf(def,w.state),next=nextOf(def,w.state),isProblem=w.state==='corrections_required';const steps=def.states.map(([state,label],i)=>`<span class="tx-muni-status-step ${i<idx?'done':i===idx?(isProblem?'current problem':'current'):''}">${esc(label)}</span>`).join('');const final=w.state===def.completion;return `<div class="tx-muni-status" data-muni-item-id="${esc(item.id)}" data-muni-item-key="${esc(key)}"><div class="tx-muni-status-kicker">${esc(def.kicker)} · ${esc(labelOf(def,w.state))}</div><div class="tx-muni-status-steps">${steps}</div><p class="tx-muni-status-copy">This is transaction workflow status supplied by the user/team. It is intentionally separate from Watchdog's public-source evidence and does not convert an evidence card to “clear.”</p><div class="tx-muni-status-actions">${next&&!final?`<button type="button" data-muni-action="advance" data-muni-next="${esc(next)}">${esc(labelOf(def,next))}</button>`:''}${!isProblem&&!final?`<button type="button" class="warn" data-muni-action="corrections">Corrections required</button>`:''}${w.state!==def.states[0][0]?`<button type="button" class="secondary" data-muni-action="reset">Reset workflow</button>`:''}</div><div class="tx-muni-status-note"><i class="fas fa-circle-info"></i><span>${final?'Workflow is marked complete, but the source evidence above remains authoritative for what Watchdog independently verified.':'Use this to manage appointments and follow-up while the official municipal result is pending.'}</span></div></div>`}
async function loadItems(txId){const c=client();if(!c||!txId)return[];if(!user){const a=await c.auth.getUser();user=a?.data?.user||null}if(!user)return[];const r=await c.from('transaction_items').select('id,transaction_id,user_id,item_key,state,evidence_state,severity,source_type,source_checked_at,payload').eq('transaction_id',txId).eq('user_id',user.id).in('item_key',Object.keys(DEFINITIONS));if(r.error){console.warn('Municipal status items could not load',r.error);return[]}return r.data||[]}
async function render(){if(busy)return;const txId=activeId();if(!txId||!document.querySelector('#tx-source-sweep'))return;busy=true;try{const items=await loadItems(txId);for(const item of items){const key=item.item_key,card=cardFor(key);if(!card)continue;card.querySelector('.tx-muni-status')?.remove();const host=card.querySelector('.tx-source-provenance')||card.querySelector('.tx-source-actions');const wrap=document.createElement('div');wrap.innerHTML=markup(item,key,statusOf(item,key));const node=wrap.firstElementChild;if(host)card.insertBefore(node,host);else card.appendChild(node)}}finally{busy=false}}
async function update(itemId,key,state){const c=client();if(!c||!user||!DEFINITIONS[key])return;const txId=activeId(),items=await loadItems(txId),item=items.find(x=>x.id===itemId&&x.item_key===key);if(!item)return;const def=DEFINITIONS[key],valid=def.states.some(x=>x[0]===state);if(!valid)return;const now=new Date().toISOString(),p=payload(item),workflow={...(p.municipal_status_workflow&&typeof p.municipal_status_workflow==='object'?p.municipal_status_workflow:{}),state,updated_at:now,supplied_by:'user_workflow',independent_public_clearance:false};const patch={payload:{...p,municipal_status_workflow:workflow},updated_at:now};if(state===def.states[0][0])patch.state='open';else if(state===def.completion)patch.state='verified';else if(state==='corrections_required')patch.state='received';else patch.state='requested';if(state==='corrections_required')patch.severity='attention';else if(state===def.completion)patch.severity='info';const r=await c.from('transaction_items').update(patch).eq('id',item.id).eq('user_id',user.id).select('id,state,evidence_state,severity').single();if(r.error){toast('Could not update municipal workflow.','error');return}await c.from('transaction_activity').insert({transaction_id:txId,user_id:user.id,action:'municipal_status_workflow',message:`${def.kicker}: ${labelOf(def,state)}`,detail:{item_id:item.id,item_key:key,workflow_state:state,evidence_state:r.data.evidence_state,independent_public_clearance:false}});toast(`${def.kicker}: ${labelOf(def,state)}.`,'success');setTimeout(()=>render(),180)}
async function handle(e){const btn=e.target.closest('[data-muni-action]');if(!btn)return;const root=btn.closest('.tx-muni-status');if(!root)return;const key=root.dataset.muniItemKey,id=root.dataset.muniItemId,action=btn.dataset.muniAction,def=DEFINITIONS[key];if(!def)return;if(action==='reset'){if(!window.confirm('Reset this workflow status? Public-source evidence will be preserved.'))return;await update(id,key,def.states[0][0]);return}if(action==='corrections'){await update(id,key,'corrections_required');return}if(action==='advance'){const next=clean(btn.dataset.muniNext);if(next===def.completion&&!window.confirm('Mark this transaction workflow approved/closed? This will not mark Watchdog public evidence clear.'))return;await update(id,key,next)}}
function schedule(delay){clearTimeout(timer);timer=setTimeout(render,delay==null?180:delay)}
injectStyle();document.addEventListener('click',e=>{handle(e);if(e.target.closest('.tx-list-card'))schedule(600)});document.addEventListener('watchdog:transaction-preflight-complete',()=>schedule(500));const observer=new MutationObserver(muts=>{if(busy)return;for(const m of muts){if(Array.from(m.addedNodes).some(n=>n.nodeType===1&&(n.matches?.('#tx-source-sweep,.tx-source-card')||n.querySelector?.('#tx-source-sweep,.tx-source-card')))){schedule(180);break}}});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{observer.observe(document.body,{childList:true,subtree:true});schedule(1000)},{once:true});else{observer.observe(document.body,{childList:true,subtree:true});schedule(1000)}
})();
