import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.95.0";

const ENGINE="watchdog-context-intelligence-v2-useful-only",CONTRACT_VERSION="watchdog-context-suggestions-v1";
const RANK:Record<string,number>={standard:0,agent:1,pro:2,pro_plus:3,teams:4,developer:5};
const MODELS=[
 {key:"assessment_anomaly",label:"Assessment Anomaly",minimum_plan:"pro",fn:"intelligence-assessment-run-preview"},
 {key:"closing_review",label:"Closing Review",minimum_plan:"pro_plus",fn:"intelligence-closing-run-preview"},
 {key:"property_change_priority",label:"Change Intelligence",minimum_plan:"pro_plus",fn:"intelligence-change-run-preview"}
] as const;
const clean=(v:unknown,n=400)=>String(v??"").replace(/[<>]/g,"").trim().slice(0,n);
const env=(j:string,l:string)=>{const raw=Deno.env.get(j)||"";if(raw){try{const x=JSON.parse(raw);if(x?.default)return String(x.default)}catch{}}return Deno.env.get(l)||""};
function origin(req:Request){const o=req.headers.get("origin")||"";if(["https://njpropertytaxrelief.com","https://www.njpropertytaxrelief.com","http://localhost:3000","http://127.0.0.1:3000"].includes(o))return o;if(/^https:\/\/njtaxrelief(?:-git)?-[a-z0-9-]+-johnscafides-projects\.vercel\.app$/i.test(o))return o;return"https://njpropertytaxrelief.com"}
const cors=(r:Request)=>({"Access-Control-Allow-Origin":origin(r),"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"});
const out=(r:Request,s:number,p:unknown)=>new Response(JSON.stringify(p),{status:s,headers:{...cors(r),"Content-Type":"application/json","Cache-Control":"private, no-store"}});
function attention(f:any){const s=Number(f?.score||0),c=Number(f?.confidence||0),e=Number(f?.evidence_coverage||0);if(f?.limited_evidence||e<50||c<50)return"watch";if(s>=80&&c>=65)return"act_now";if(s>=65)return"this_week";return"watch"}
function actions(k:string){const b=["open_property","why_watchdog","watch_property"];if(k==="closing_review")return[...b,"create_case","create_report"];if(k==="property_change_priority")return[...b,"create_case"];return[...b,"create_case","create_report"]}
function why(f:any){const w=Array.isArray(f?.why_now)?f.why_now:[],x=w.find((i:any)=>clean(i?.explanation,500));if(x)return clean(x.explanation,500);const e=Array.isArray(f?.evidence)?f.evidence:[],y=e.find((i:any)=>clean(i?.explanation,500));return y?clean(y.explanation,500):"Governed evidence produced a Watchdog review finding for this property."}
function normalize(m:any,f:any,surface:string){return{suggestion_id:`${m.key}:${clean(f?.facts_hash||f?.id||f?.pams_pin||crypto.randomUUID(),180)}`,contract_version:CONTRACT_VERSION,surface,model_key:m.key,model_label:m.label,model_version:f?.model_version||null,pams_pin:clean(f?.pams_pin,120)||null,property_address:clean(f?.property_address||f?.address,300)||null,score:Number(f?.score||0),confidence:Number(f?.confidence||0),evidence_coverage:Number(f?.evidence_coverage||0),limited_evidence:Boolean(f?.limited_evidence),attention_band:attention(f),why_now:why(f),why_now_items:Array.isArray(f?.why_now)?f.why_now:[],evidence:Array.isArray(f?.evidence)?f.evidence:[],missing_evidence:Array.isArray(f?.missing_evidence)?f.missing_evidence:[],property_context:f?.property_context&&typeof f.property_context==="object"?f.property_context:{},facts_hash:f?.facts_hash||null,actions:actions(m.key)}}
function useful(x:any){if(!Number.isFinite(Number(x.score))||Number(x.score)<=0)return false;if(!x.limited_evidence&&Number(x.score)<40)return false;if(x.limited_evidence&&Number(x.score)<40&&!(Array.isArray(x.missing_evidence)&&x.missing_evidence.length))return false;return true}
async function run(args:{url:string;pub:string;auth:string;model:any;scopeType:string;scopeValue:Record<string,unknown>;pins:string[];limit:number}){const body:any={model_key:args.model.key,scope_type:args.scopeType,scope_value:args.scopeValue,limit:args.limit};if(args.scopeType!=="farm")body.pams_pins=args.pins;try{const r=await fetch(`${args.url}/functions/v1/${args.model.fn}`,{method:"POST",headers:{Authorization:args.auth,apikey:args.pub,"Content-Type":"application/json"},body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));if(!r.ok)return{ok:false,model_key:args.model.key,status:r.status,error:clean(d?.error||d?.detail||`Model runner returned ${r.status}`,500)};return{ok:true,model_key:args.model.key,data:d}}catch(e){if(e instanceof Deno.errors.RateLimitError)return{ok:false,model_key:args.model.key,status:429,retry_after_ms:e.retryAfterMs,error:"Context Intelligence is temporarily rate limited. Retry shortly."};return{ok:false,model_key:args.model.key,status:503,error:clean((e as any)?.message||"Model runner unavailable",500)}}}
Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});if(req.method!=="POST")return out(req,405,{error:"POST required"});const auth=req.headers.get("authorization")||"";if(!auth.startsWith("Bearer "))return out(req,401,{error:"Sign in required"});
 const url=Deno.env.get("SUPABASE_URL")||"",pub=env("SUPABASE_PUBLISHABLE_KEYS","SUPABASE_ANON_KEY"),secret=env("SUPABASE_SECRET_KEYS","SUPABASE_SERVICE_ROLE_KEY");if(!url||!pub||!secret)return out(req,503,{error:"Context Intelligence configuration incomplete"});
 const uc=createClient(url,pub,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}}),admin=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}}),{data:au}=await uc.auth.getUser(),user=au?.user;if(!user)return out(req,401,{error:"Session invalid"});let body:any={};try{body=await req.json()}catch{return out(req,400,{error:"Invalid JSON"})}
 const surface=clean(body?.surface||"unknown",80)||"unknown",scopeType=clean(body?.scope_type||"custom",40)||"custom";if(!["property","custom","farm"].includes(scopeType))return out(req,400,{error:"Unsupported context scope"});const pins=[...new Set((Array.isArray(body?.pams_pins)?body.pams_pins:[]).map((v:unknown)=>clean(v,120)).filter(Boolean))].slice(0,100) as string[];if(scopeType!=="farm"&&!pins.length)return out(req,409,{error:"Context resolved to no governed properties"});
 const [{data:ent},{data:profile}]=await Promise.all([admin.from("account_entitlements").select("plan_tier,subscription_status").eq("user_id",user.id).maybeSingle(),admin.from("profiles").select("account_role").eq("id",user.id).maybeSingle()]);const plan=String(profile?.account_role||"")==="developer"?"developer":clean(ent?.plan_tier||"standard",40)||"standard",requested=[...new Set((Array.isArray(body?.models)?body.models:[]).map((v:unknown)=>clean(v,80)).filter(Boolean))] as string[];
 const eligible=MODELS.filter(m=>(!requested.length||requested.includes(m.key))&&((RANK[plan]??0)>=(RANK[m.minimum_plan]??99)));if(!eligible.length)return out(req,200,{engine_version:ENGINE,contract_version:CONTRACT_VERSION,surface,plan,scope:{type:scopeType,property_count:scopeType==="farm"?null:pins.length},suggestions:[],summary:{total:0,act_now:0,this_week:0,watch:0,adequate_evidence:0},upgrade:{minimum_plan:"pro",message:"Pro Intelligence is required for proactive property suggestions."}});
 const scopeValue={source:"context_intelligence",surface,context_key:clean(body?.context_key||"",160)||null},limit=Math.max(1,Math.min(Number(body?.limit||20),50)),results=await Promise.all(eligible.map(model=>run({url,pub,auth,model,scopeType,scopeValue,pins,limit}))),suggestions:any[]=[],modelStatus:any[]=[];
 for(const result of results){const model=MODELS.find(m=>m.key===result.model_key);if(!model)continue;if(!result.ok){modelStatus.push({model_key:model.key,ok:false,status:result.status,error:result.error,retry_after_ms:(result as any).retry_after_ms||null});continue}const findings=Array.isArray((result as any).data?.findings)?(result as any).data.findings:[];let usefulCount=0;for(const f of findings){const x=normalize(model,f,surface);if(useful(x)){suggestions.push(x);usefulCount++}}modelStatus.push({model_key:model.key,ok:true,finding_count:findings.length,useful_suggestion_count:usefulCount,model:(result as any).data?.model||null,pipeline_engine:(result as any).data?.pipeline_engine||(result as any).data?.engine_version||null})}
 suggestions.sort((a,b)=>{const ea=a.limited_evidence?0:1,eb=b.limited_evidence?0:1;if(ea!==eb)return eb-ea;if(a.score!==b.score)return b.score-a.score;if(a.confidence!==b.confidence)return b.confidence-a.confidence;return b.evidence_coverage-a.evidence_coverage});const trimmed=suggestions.slice(0,limit),summary={total:trimmed.length,act_now:trimmed.filter(x=>x.attention_band==="act_now").length,this_week:trimmed.filter(x=>x.attention_band==="this_week").length,watch:trimmed.filter(x=>x.attention_band==="watch").length,adequate_evidence:trimmed.filter(x=>!x.limited_evidence&&Number(x.evidence_coverage||0)>=50).length};
 if(results.length>0&&results.every((x:any)=>!x.ok&&x.status===429)){const retry=Math.max(...results.map((x:any)=>Number(x.retry_after_ms||0)));return out(req,429,{error:"Context Intelligence is temporarily busy",retry_after_ms:retry||null,engine_version:ENGINE})}
 return out(req,200,{engine_version:ENGINE,contract_version:CONTRACT_VERSION,surface,plan,scope:{type:scopeType,property_count:scopeType==="farm"?null:pins.length},eligible_models:eligible.map(m=>({key:m.key,label:m.label,minimum_plan:m.minimum_plan})),model_status:modelStatus,summary,suggestions:trimmed});
});
