import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.95.0";

const VERSION="watchdog-intelligence-job-submit-v1";
const ORIGINS=new Set(["https://njpropertytaxrelief.com","https://www.njpropertytaxrelief.com","http://localhost:3000","http://127.0.0.1:3000"]);
const PLAN_RANK:Record<string,number>={standard:0,agent:1,pro:2,pro_plus:3,teams:4,developer:5};
const SUPPORTED_MODELS=new Set(["assessment_anomaly","property_change_priority"]);
const STABLE_VIEW_FILTERS=new Set(["town","county","assessedMin","assessedMax","taxMin","valueMin"]);
type O=Record<string,any>;
const cors=(r:Request)=>({"Access-Control-Allow-Origin":ORIGINS.has(r.headers.get("origin")||"")?(r.headers.get("origin")||""):"https://njpropertytaxrelief.com","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"});
const out=(r:Request,s:number,p:unknown)=>new Response(JSON.stringify(p),{status:s,headers:{...cors(r),"Content-Type":"application/json","Cache-Control":"private, no-store"}});
const clean=(v:unknown,n=300)=>String(v??"").replace(/[<>]/g,"").trim().slice(0,n);
const env=(j:string,l:string)=>{const raw=Deno.env.get(j)||"";if(raw){try{const x=JSON.parse(raw);if(x?.default)return String(x.default)}catch{}}return Deno.env.get(l)||""};
function canon(v:unknown):unknown{if(Array.isArray(v))return v.map(canon);if(v&&typeof v==="object")return Object.fromEntries(Object.entries(v as O).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>[k,canon(x)]));return v}
async function hash(v:unknown){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(JSON.stringify(canon(v))));return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function active(v:unknown){return v!==null&&v!==undefined&&v!==""&&v!==false&&Number(v)!==0}
function pass(row:O,f:O){if(f.town&&String(row.town||"").toLowerCase().indexOf(String(f.town).toLowerCase())<0)return false;if(f.county&&String(row.county||"").toLowerCase().indexOf(String(f.county).toLowerCase())<0)return false;if(active(f.assessedMin)&&Number(row.assessed||row.assessed_value||0)<Number(f.assessedMin))return false;if(active(f.assessedMax)&&Number(row.assessed||row.assessed_value||0)>Number(f.assessedMax))return false;if(active(f.taxMin)&&Number(row.last_year_tax||0)<Number(f.taxMin))return false;if(active(f.valueMin)&&Number(row.watchdog_value||0)<Number(f.valueMin))return false;return true}
async function rowsPaged(queryFactory:()=>any,max:number){const rows:any[]=[];for(let start=0;start<max;start+=1000){const q=queryFactory().range(start,Math.min(start+999,max-1)),r=await q;if(r.error)throw r.error;rows.push(...(r.data||[]));if((r.data||[]).length<1000)break}return rows}
async function resolve(admin:any,userId:string,scopeType:string,scopeValue:O,limit:number){
  if(scopeType==="custom"){const pins=[...new Set((Array.isArray(scopeValue.pams_pins)?scopeValue.pams_pins:[]).map((x:unknown)=>clean(x,100)).filter(Boolean))];return{pins:pins.slice(0,limit),manifest:{source:"custom",requested_count:pins.length}}}
  if(scopeType==="farm"){const rows=await rowsPaged(()=>admin.from("agent_farm_properties").select("pams_pin").eq("user_id",userId).eq("relationship","farm").not("pams_pin","is",null),limit+1);const pins=[...new Set(rows.map((x:O)=>clean(x.pams_pin,100)).filter(Boolean))];return{pins:pins.slice(0,limit),manifest:{source:"agent_farm_properties",source_count:pins.length}}}
  if(scopeType==="municipality"||scopeType==="county"){const key=scopeType==="municipality"?"town":"county",value=clean(scopeValue.value||scopeValue[key],120);if(!value)throw new Error(`${scopeType} value is required`);const rows=await rowsPaged(()=>admin.from("property_lookups").select("pams_pin").eq(key,value).order("pams_pin"),limit+1);const pins=[...new Set(rows.map((x:O)=>clean(x.pams_pin,100)).filter(Boolean))];return{pins:pins.slice(0,limit),manifest:{source:"property_lookups",field:key,value,source_count:pins.length}}}
  if(scopeType==="workbench_view"){
    const viewId=clean(scopeValue.id||scopeValue.scope_id||scopeValue.workbench_view_id,80);if(!viewId)throw new Error("workbench_view id is required");const vr=await admin.from("data_workbench_views").select("id,name,source_type,source_id,filters").eq("id",viewId).eq("user_id",userId).maybeSingle();if(vr.error||!vr.data)throw new Error("Workbench view not found");const view=vr.data,filters=view.filters&&typeof view.filters==="object"?view.filters:{};const keys=Object.keys(filters).filter(k=>filters[k]!==null&&filters[k]!==undefined&&filters[k]!=="");const unsupported=keys.filter(k=>!STABLE_VIEW_FILTERS.has(k));if(unsupported.length)throw new Error(`Scheduled Workbench view has unsupported session or derived filters: ${unsupported.join(', ')}`);
    let source:any[]=[];if(String(view.source_type)==="saved")source=await rowsPaged(()=>admin.from("saved_properties").select("pams_pin,address,town,county,assessed,last_year_tax,watchdog_value").eq("user_id",userId).not("pams_pin","is",null).order("pams_pin"),limit+1);else if(String(view.source_type)==="farm")source=await rowsPaged(()=>admin.from("agent_farm_properties").select("pams_pin,address,municipality,county").eq("user_id",userId).not("pams_pin","is",null).order("pams_pin"),limit+1);else throw new Error(`Scheduled Workbench source '${clean(view.source_type,60)}' is not yet covered by the deterministic population adapter.`);source=source.map(x=>({...x,town:x.town||x.municipality}));const filtered=source.filter(x=>pass(x,filters)),pins=[...new Set(filtered.map((x:O)=>clean(x.pams_pin,100)).filter(Boolean))];return{pins:pins.slice(0,limit),manifest:{source:"data_workbench_views",view_id:view.id,view_name:view.name,source_type:view.source_type,filters,source_count:source.length,filtered_count:pins.length}}
  }
  throw new Error("Unsupported Intelligence population scope");
}

Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});if(req.method!=="POST")return out(req,405,{error:"POST required"});const auth=req.headers.get("authorization")||"";if(!auth.startsWith("Bearer "))return out(req,401,{error:"Sign in required"});const url=Deno.env.get("SUPABASE_URL")||"",pub=env("SUPABASE_PUBLISHABLE_KEYS","SUPABASE_ANON_KEY"),secret=env("SUPABASE_SECRET_KEYS","SUPABASE_SERVICE_ROLE_KEY");if(!url||!pub||!secret)return out(req,503,{error:"Job service configuration incomplete"});const uc=createClient(url,pub,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}}),admin=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}}),{data:au}=await uc.auth.getUser(),user=au?.user;if(!user)return out(req,401,{error:"Session invalid"});let body:O={};try{body=await req.json()}catch{return out(req,400,{error:"Invalid JSON"})}
const [{data:ent},{data:profile}]=await Promise.all([admin.from("account_entitlements").select("plan_tier").eq("user_id",user.id).maybeSingle(),admin.from("profiles").select("account_role").eq("id",user.id).maybeSingle()]),plan=String(profile?.account_role||"")==="developer"?"developer":String(ent?.plan_tier||"standard");if((PLAN_RANK[plan]??0)<PLAN_RANK.pro_plus)return out(req,403,{error:"Pro+ plan required for population Intelligence jobs",minimum_plan:"pro_plus"});const lr=await admin.from("intelligence_plan_limits").select("*").eq("plan_tier",plan).maybeSingle(),limits=lr.data;if(!limits)return out(req,503,{error:"Intelligence plan limits unavailable"});
const action=clean(body.action||"submit",40),scopeType=clean(body.scope_type||"custom",40),scopeValue=body.scope_value&&typeof body.scope_value==="object"?body.scope_value:{},modelKeys=[...new Set((Array.isArray(body.model_keys)?body.model_keys:[body.model_key||"assessment_anomaly"]).map((x:unknown)=>clean(x,100)).filter(Boolean))];const unsupported=modelKeys.filter(k=>!SUPPORTED_MODELS.has(k));if(unsupported.length)return out(req,409,{error:"Population worker does not yet support these governed models.",unsupported_models:unsupported,supported_models:[...SUPPORTED_MODELS]});
const today=new Date(Date.now()-86400000).toISOString(),[{count:jobsToday},{count:activeJobs},{count:savedScopes},{count:scheduledScopes}]=await Promise.all([admin.from("intelligence_jobs").select("id",{count:"exact",head:true}).eq("user_id",user.id).gte("created_at",today),admin.from("intelligence_jobs").select("id",{count:"exact",head:true}).eq("user_id",user.id).in("status",["queued","running","partial"]),admin.from("intelligence_scopes").select("id",{count:"exact",head:true}).eq("user_id",user.id).eq("is_active",true),admin.from("intelligence_scopes").select("id",{count:"exact",head:true}).eq("user_id",user.id).eq("is_active",true).eq("is_scheduled",true)]);if(Number(jobsToday||0)+modelKeys.length>Number(limits.max_jobs_per_day))return out(req,429,{error:"Daily Intelligence job quota reached for this plan."});if(Number(activeJobs||0)>=Number(limits.max_concurrent_jobs))return out(req,429,{error:"Concurrent Intelligence job quota reached for this plan."});
let resolved;try{resolved=await resolve(admin,user.id,scopeType,scopeValue,Number(limits.max_scope_properties)+1)}catch(e){return out(req,409,{error:clean((e as any)?.message||e,500)})}if(resolved.pins.length>Number(limits.max_scope_properties))return out(req,409,{error:"Resolved scope exceeds the plan property limit.",resolved_count:resolved.pins.length,limit:limits.max_scope_properties});if(!resolved.pins.length)return out(req,409,{error:"The requested scope resolved to no governed properties."});const scopeFingerprint=await hash({scope_type:scopeType,scope_value:scopeValue,pams_pins:resolved.pins.slice().sort()});
let scopeId=clean(body.scope_id,80),scope:any=null;if(action==="save_scope"||action==="schedule"||scopeId){const scheduled=action==="schedule"||!!body.is_scheduled,cadence=scheduled?clean(body.cadence||"daily",20):null;if(scheduled&&!["daily","weekly"].includes(cadence))return out(req,400,{error:"Scheduled scopes support daily or weekly cadence."});if(!scopeId&&Number(savedScopes||0)>=Number(limits.max_saved_scopes))return out(req,429,{error:"Saved Intelligence scope limit reached."});if(scheduled&&!scopeId&&Number(scheduledScopes||0)>=Number(limits.max_scheduled_scopes))return out(req,429,{error:"Scheduled Intelligence scope limit reached."});const next=scheduled?(body.next_run_at?new Date(String(body.next_run_at)).toISOString():new Date(Date.now()+(cadence==="weekly"?7:1)*86400000).toISOString()):null;const payload={user_id:user.id,name:clean(body.name||`${scopeType} Intelligence`,140),scope_type:scopeType,scope_value:{...scopeValue,resolution_manifest:resolved.manifest},model_keys:modelKeys,resolved_pams_pins:resolved.pins,scope_fingerprint:scopeFingerprint,is_scheduled:scheduled,cadence:cadence||null,next_run_at:next,is_active:true,updated_at:new Date().toISOString()};const sr=scopeId?await admin.from("intelligence_scopes").update(payload).eq("id",scopeId).eq("user_id",user.id).select("*").single():await admin.from("intelligence_scopes").insert(payload).select("*").single();if(sr.error)return out(req,503,{error:"Could not save Intelligence scope"});scope=sr.data;scopeId=String(sr.data.id);if(action==="save_scope"&&!body.run_now)return out(req,200,{ok:true,scope,version:VERSION})}
const jobs=[];for(const modelKey of modelKeys){const mr=await admin.from("intelligence_models").select("model_key,version,status,calibration_state").eq("model_key",modelKey).maybeSingle();if(mr.error||!mr.data)continue;const idempotency=clean(body.idempotency_key,180)||await hash({user_id:user.id,scope_id:scopeId||null,scope_fingerprint:scopeFingerprint,model_key:modelKey,model_version:mr.data.version,trigger:action,window:new Date().toISOString().slice(0,13)});const jr=await admin.from("intelligence_jobs").upsert({user_id:user.id,scope_id:scopeId||null,model_key:modelKey,model_version:mr.data.version,scope_type:scopeType,scope_value:{...scopeValue,resolution_manifest:resolved.manifest},scope_fingerprint:scopeFingerprint,pams_pins:resolved.pins,idempotency_key:idempotency,trigger_type:action==="schedule"?"scheduled":"manual",status:"queued",candidate_count:resolved.pins.length,batch_size:Math.min(500,Math.max(100,Number(body.batch_size||250))),updated_at:new Date().toISOString()},{onConflict:"user_id,idempotency_key",ignoreDuplicates:true}).select("id,status,model_key,model_version,candidate_count,created_at").maybeSingle();if(jr.error)return out(req,503,{error:"Could not queue Intelligence job"});if(jr.data){jobs.push(jr.data);await admin.from("intelligence_job_events").insert({job_id:jr.data.id,user_id:user.id,event_type:"queued",message:"Population Intelligence job queued.",payload:{scope_type:scopeType,candidate_count:resolved.pins.length,model_key:modelKey}})}}
return out(req,200,{ok:true,version:VERSION,plan,scope:scope?{id:scope.id,name:scope.name,is_scheduled:scope.is_scheduled,cadence:scope.cadence,next_run_at:scope.next_run_at}:null,resolved_count:resolved.pins.length,scope_fingerprint:scopeFingerprint,jobs,warning:"Queued jobs are deterministic and browser-independent. LLM prose is not part of population scoring."})});
