import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.95.0";

const NJOGIS = "https://maps.nj.gov/arcgis/rest/services/Framework/Cadastral/MapServer/0/query";
const RATIO_URL = "https://njpropertytaxrelief.com/property/sr1a-ratios.json";
const PAGE_SIZE = 500;
const CANONICAL_SCORE = "watchdog.watchdog_score";
const SCORE_MODEL = "ROBUST-v1";
const sourceUrl = "https://njpropertytaxrelief.com/property/data-methodology";
const fields = ["address","town","county","block","lot","assessed","last_year_tax","effective_rate","watchdog_value","verified","verify_level"];

function clean(v: unknown, max = 240) { return String(v ?? "").trim().replace(/[\u0000-\u001f]/g, "").slice(0, max); }
function num(v: unknown) { const n = Number(v); return Number.isFinite(n) ? n : null; }
function sqlText(v: string) { return v.replace(/'/g, "''"); }
function html(v: unknown, max = 240) { return clean(v, max).replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c] || c)); }
function stable(v: unknown) { return JSON.stringify(v, Object.keys((v || {}) as Record<string, unknown>).sort()); }
function canonicalJson(v: unknown): string { if (Array.isArray(v)) return `[${v.map(canonicalJson).join(",")}]`; if (v && typeof v === "object") { const o = v as Record<string,unknown>; return `{${Object.keys(o).sort().map(k => `${JSON.stringify(k)}:${canonicalJson(o[k])}`).join(",")}}`; } return JSON.stringify(v); }
function sameDefinition(a: unknown, b: unknown) { return canonicalJson(a) === canonicalJson(b); }
async function sha(v: string) { const b = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(v)); return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,"0")).join(""); }
function materiality(k:string,a:unknown,b:unknown){if(["assessed","last_year_tax","watchdog_value"].includes(k)){const old=Number(a)||0,next=Number(b)||0,pct=old?Math.abs(next-old)/old:1;return pct>=.05?"action":pct>=.01?"material":"informational";}return ["verified","verify_level"].includes(k)?"material":"informational";}
function saleYear(v: unknown) { const x = String(v ?? "").trim(); if (/^\d{6}$/.test(x)) { const yy = Number(x.slice(0,2)), currentYY = new Date().getFullYear() % 100; return yy <= currentYY ? 2000 + yy : 1900 + yy; } const full = x.match(/(19|20)\d{2}/); return full ? Number(full[0]) : null; }
function normalize(a: Record<string, unknown>) { return { pams_pin: clean(a.PAMS_PIN,80), address: clean(a.PROP_LOC,220), town: clean(a.MUN_NAME,140), county: clean(a.COUNTY,100), zip: clean(a.ZIP5 || a.ZIP_CODE,10), block: clean(a.PCLBLOCK,40), lot: clean(a.PCLLOT,40), qualifier: clean(a.PCLQCODE,40), prop_class: clean(a.PROP_CLASS,12), year_built: num(a.YR_CONSTR), acres: num(a.CALC_ACRE), dwelling_units: num(a.DWELL) ?? num(a.COMM_DWELL), building_desc: clean(a.BLDG_DESC,220), land_value: num(a.LAND_VAL), improvement_value: num(a.IMPRVT_VAL), assessed_value: num(a.NET_VALUE), last_year_tax: num(a.LAST_YR_TX), effective_rate: null, last_sale_price: num(a.SALE_PRICE), last_sale_year: saleYear(a.DEED_DATE), sales_code: clean(a.SALES_CODE,20), last_seen: new Date().toISOString(), history: { source: "NJ Office of GIS statewide Parcels and MOD-IV Composite", purpose: "dynamic_list_materialization", cached_at: new Date().toISOString(), deed_date_format: "YYMMDD", deed_parser_version: 2 } }; }
async function geocode(address: string) { const u = new URL("https://geocoding.geo.census.gov/geocoder/locations/onelineaddress"); u.searchParams.set("address", `${address}, NJ`); u.searchParams.set("benchmark", "Public_AR_Current"); u.searchParams.set("format", "json"); const r = await fetch(u); if (!r.ok) return null; const j = await r.json(); const c = j?.result?.addressMatches?.[0]?.coordinates; return c ? {lat:Number(c.y), lon:Number(c.x)} : null; }
function definition(list: any) { return {scope_type:list.scope_type, scope_value:list.scope_value, criteria:list.criteria || {}}; }
function hasKeys(obj: unknown) { return !!obj && typeof obj === "object" && !Array.isArray(obj) && Object.keys(obj as Record<string,unknown>).length > 0; }
function buildWhere(classes: string[], filters: Record<string, unknown>, scopeType: string, scopeValue: string) { let where = "1=1"; if (scopeType === "municipality") where += ` AND UPPER(MUN_NAME) LIKE '%${sqlText(scopeValue.toUpperCase())}%'`; if (scopeType === "county") where += ` AND UPPER(COUNTY) LIKE '%${sqlText(scopeValue.toUpperCase().replace(/ COUNTY$/, ""))}%'`; if (scopeType === "zip") where += ` AND ZIP5='${sqlText(scopeValue.replace(/\D/g, "").slice(0,5))}'`; const safeClasses = classes.filter(x => /^[0-9A-Z.]{1,4}$/.test(x)); if (safeClasses.length) where += ` AND PROP_CLASS IN (${safeClasses.map(x => `'${sqlText(x)}'`).join(",")})`; const remote: Record<string,[string,string]> = {year_built_min:["YR_CONSTR",">="],year_built_max:["YR_CONSTR","<="],assessment_min:["NET_VALUE",">="],assessment_max:["NET_VALUE","<="],tax_min:["LAST_YR_TX",">="],tax_max:["LAST_YR_TX","<="],sale_price_min:["SALE_PRICE",">="],sale_price_max:["SALE_PRICE","<="],acres_min:["CALC_ACRE",">="],acres_max:["CALC_ACRE","<="],units_min:["DWELL",">="],units_max:["DWELL","<="]}; for (const [key,[field,op]] of Object.entries(remote)) { const value = num(filters[key]); if (value !== null) where += ` AND ${field} ${op} ${value}`; } return where; }
function ratioRow(root: any, code: string, town: string) { const pools = [root?.districts,root?.municipalities,root?.ratios,root?.data,root]; for (const pool of pools) { if (!pool) continue; if (Array.isArray(pool)) { const row = pool.find((x:any) => String(x?.district || x?.code || x?.district_code || "").padStart(4,"0") === code || String(x?.name || x?.municipality || "").toLowerCase() === town.toLowerCase()); if (row) return row; } else if (typeof pool === "object") { if (pool[code]) return pool[code]; const row = Object.values(pool).find((x:any) => String(x?.district || x?.code || x?.district_code || "").padStart(4,"0") === code || String(x?.name || x?.municipality || "").toLowerCase() === town.toLowerCase()); if (row) return row; } } return null; }
function pctRatio(v: any) { let x = num(v); if (x === null) return null; if (x > 2) x /= 100; return x > 0 && x < 2 ? x : null; }
function usableSale(row: any) { const sale = num(row.last_sale_price), ass = num(row.assessed_value); if (sale === null || sale < 1000) return false; if (ass !== null && ass > 0) { const raw = ass / sale; if (raw > 5 || raw < .05) return false; } return true; }
function chapter123(row: any, ratios: any) { const code = String(row.pams_pin || "").replace(/\D/g, "").slice(0,4).padStart(4,"0"), rr = ratioRow(ratios, code, String(row.town || "")); if (!rr) return null; const common = pctRatio(rr.common_level_ratio ?? rr.common_ratio ?? rr.ratio ?? rr.average_ratio ?? rr.avg_ratio), upper = pctRatio(rr.upper_limit ?? rr.upper_ratio ?? rr.upper) ?? (common !== null ? common * 1.15 : null), ass = num(row.assessed_value), sale = num(row.last_sale_price), tax = num(row.last_year_tax); if (common === null || upper === null || !ass || !usableSale(row)) return null; const assessmentRatio = ass / Number(sale); if (assessmentRatio <= upper) return {eligible:false,common,upper,assessment_ratio:assessmentRatio}; const target = Number(sale) * common, reduction = Math.max(0, ass - target), taxRate = tax !== null && ass > 0 ? tax / ass : null, annual = taxRate !== null ? reduction * taxRate : null; return {eligible:true,common,upper,assessment_ratio:assessmentRatio,target_assessment:Math.round(target),assessment_reduction:Math.round(reduction),annual_overpayment:annual !== null ? Math.round(annual) : null,over_upper_pct:Number(((assessmentRatio/upper - 1) * 100).toFixed(1))}; }
function metricMap(row: any, obs: Record<string,number>, ratios: any) { const y = new Date().getFullYear(), m: any = {...obs}; if (num(row.year_built) && Number(row.year_built) > 1600) m["watchdog.building_age_years"] = Math.max(0, y - Number(row.year_built)); if (num(row.last_sale_year) && Number(row.last_sale_year) > 1800) m["watchdog.years_since_last_sale"] = Math.max(0, y - Number(row.last_sale_year)); if (num(row.assessed_value) && Number(row.assessed_value) > 0 && num(row.last_year_tax) !== null) m["watchdog.tax_to_assessment_rate"] = Number((Number(row.last_year_tax) / Number(row.assessed_value) * 100).toFixed(3)); if (num(row.assessed_value) && Number(row.assessed_value) > 0 && num(row.land_value) !== null) m["watchdog.land_share_pct"] = Number((Number(row.land_value) / Number(row.assessed_value) * 100).toFixed(1)); if (num(row.assessed_value) && Number(row.assessed_value) > 0 && num(row.improvement_value) !== null) m["watchdog.improvement_share_pct"] = Number((Number(row.improvement_value) / Number(row.assessed_value) * 100).toFixed(1)); if (num(row.acres) && Number(row.acres) > 0) m["watchdog.assessment_per_acre"] = Math.round(Number(row.assessed_value || 0) / Number(row.acres)); const c = chapter123(row, ratios); if (c) { m["watchdog.chapter123_screen"] = c.eligible ? 1 : 0; m["watchdog.chapter123_assessment_ratio"] = Number(c.assessment_ratio.toFixed(4)); m["watchdog.chapter123_upper_limit"] = Number(c.upper.toFixed(4)); m["watchdog.chapter123_common_ratio"] = Number(c.common.toFixed(4)); if (c.eligible) { m["watchdog.chapter123_target_assessment"] = c.target_assessment; m["watchdog.chapter123_assessment_reduction"] = c.assessment_reduction; m["watchdog.chapter123_over_upper_pct"] = c.over_upper_pct; if (c.annual_overpayment !== null) m["watchdog.chapter123_annual_overpayment"] = c.annual_overpayment; } } return m; }
const RULES: Record<string,[string]> = {watchdog_score:[CANONICAL_SCORE],tax_pressure:["watchdog.tax_pressure"],revaluation_risk:["watchdog.revaluation_risk"],uniformity:["uniformity.score"],building_age:["watchdog.building_age_years"],years_since_sale:["watchdog.years_since_last_sale"],tax_assessment_rate:["watchdog.tax_to_assessment_rate"],assessment_per_acre:["watchdog.assessment_per_acre"],overassessment_annual:["watchdog.chapter123_annual_overpayment"],overassessment_pct:["watchdog.chapter123_over_upper_pct"],assessment_reduction:["watchdog.chapter123_assessment_reduction"]};
function intelPass(metrics: any, f: any) { if (f.overassessment_only === true && num(metrics["watchdog.chapter123_screen"]) !== 1) return false; for (const [key,[id]] of Object.entries(RULES)) { const min = num(f[key + "_min"]), max = num(f[key + "_max"]); if (min === null && max === null) continue; const v = num(metrics[id]); if (v === null) return false; if (min !== null && Number(v) < min) return false; if (max !== null && Number(v) > max) return false; } return true; }
function salePass(row: any, filters: any) { const min = num(filters.sale_year_min), max = num(filters.sale_year_max); if (min === null && max === null) return true; const y = num(row.last_sale_year); if (y === null) return false; if (min !== null && y < min) return false; if (max !== null && y > max) return false; return true; }
async function metricsFor(db: any, rows: any[]) { let ratios: any = {}; try { const rr = await fetch(RATIO_URL, {headers:{accept:"application/json"}}); if (rr.ok) ratios = await rr.json(); } catch {} const pins = rows.map(x => x.pams_pin).filter(Boolean), obs: Record<string,Record<string,number>> = {}; for (let i=0;i<pins.length;i+=500) { const {data} = await db.from("score_observations").select("pams_pin,marker_id,score,observed_at,model_version").in("pams_pin", pins.slice(i,i+500)).order("observed_at",{ascending:false}); for (const x of data || []) { if (x.marker_id === CANONICAL_SCORE && x.model_version !== SCORE_MODEL) continue; obs[x.pams_pin] ??= {}; if (obs[x.pams_pin][x.marker_id] === undefined) obs[x.pams_pin][x.marker_id] = Number(x.score); } } return rows.map(r => ({row:r,metrics:metricMap(r,obs[r.pams_pin] || {},ratios)})); }
async function cacheRows(db: any, rows: any[]) { for (let i=0;i<rows.length;i+=500) { const cleaned = rows.slice(i,i+500).map(({sales_code,...r}:any) => r); const {error} = await db.from("property_lookups").upsert(cleaned,{onConflict:"pams_pin",ignoreDuplicates:false}); if (error) throw new Error("CACHE_WRITE_FAILED"); } }
async function insertMembers(db: any, userId: string, listId: string, generation: string, rows: any[]) { if (!rows.length) return; for (let i=0;i<rows.length;i+=500) { const members = rows.slice(i,i+500).map((row:any) => ({user_id:userId,dynamic_list_id:listId,pams_pin:row.pams_pin,generation,matched_at:new Date().toISOString()})); const {error} = await db.from("agent_dynamic_list_properties").insert(members); if (error) throw new Error("MATERIALIZATION_WRITE_FAILED"); } }
async function failRun(db: any, run: any, detail: string) { await db.from("agent_dynamic_list_properties").delete().eq("dynamic_list_id",run.dynamic_list_id).eq("generation",run.generation); await db.from("agent_dynamic_list_materialization_runs").update({status:"failed",detail:clean(detail,220),updated_at:new Date().toISOString(),completed_at:new Date().toISOString()}).eq("id",run.id); }
function cadenceFor(plan: string) { return plan === "agent" ? "weekly" : ["pro","pro_plus","teams","developer"].includes(plan) ? "daily" : null; }
function nextSchedule(cadence: string, base = Date.now()) { return new Date(base + (cadence === "weekly" ? 7 : 1) * 86400000).toISOString(); }
function retrySchedule(base = Date.now()) { return new Date(base + 6 * 3600000).toISOString(); }
function sourceName() { return "NJ Office of GIS statewide Parcels and MOD-IV Composite via Watchdog"; }

async function buildSpatialCommon(list: any, where: string) { const scopeType = clean(list.scope_type,20).toLowerCase(), scopeValue = clean(list.scope_value), common: Record<string,string> = {f:"json",where}; if (scopeType === "radius") { const center = await geocode(scopeValue); if (!center) throw new Error("LOCATION_NOT_FOUND"); Object.assign(common,{geometry:`${center.lon},${center.lat}`,geometryType:"esriGeometryPoint",inSR:"4326",spatialRel:"esriSpatialRelIntersects",distance:String(Math.max(.1,Math.min(num(list.criteria?.radius_miles) || 2,50))),units:"esriSRUnit_StatuteMile"}); } else if (scopeType === "polygon") { const rings = list.criteria?.polygon?.rings; if (!Array.isArray(rings) || !rings.length || !Array.isArray(rings[0]) || rings[0].length < 4) throw new Error("INVALID_POLYGON"); Object.assign(common,{geometry:JSON.stringify({rings,spatialReference:{wkid:4326}}),geometryType:"esriGeometryPolygon",inSR:"4326",spatialRel:"esriSpatialRelIntersects"}); } return common; }

async function finalizeGeneration(db: any, list: any, generation: string, snapshot: any, tier: string, capacity: number, sourceCount: number, stored: number, candidateCount?: number) { const now = new Date().toISOString(), cap = sourceCount > capacity, status = cap ? "ready_capacity_limited" : "ready", detail = cap ? `${stored} of ${sourceCount} complete source matches are available under the ${tier} plan.` : candidateCount !== undefined ? `${stored} properties prepared after scanning all ${candidateCount} statewide candidates.` : `${stored} properties prepared from the complete live NJ statewide parcel source.`; const {error:me} = await db.from("agent_dynamic_list_materializations").upsert({dynamic_list_id:list.id,user_id:list.user_id,generation,definition_snapshot:snapshot,source_count:sourceCount,materialized_count:stored,source_complete:true,capacity_limited:cap,status,source_name:sourceName(),detail,materialized_at:now,updated_at:now},{onConflict:"dynamic_list_id"}); if (me) throw new Error("MATERIALIZATION_FINALIZE_FAILED"); await db.from("agent_dynamic_list_properties").delete().eq("dynamic_list_id",list.id).neq("generation",generation); await db.from("agent_dynamic_lists").update({last_count:sourceCount,last_checked_at:now,updated_at:now}).eq("id",list.id).eq("user_id",list.user_id); return {generation,source_count:sourceCount,materialized_count:stored,source_complete:true,capacity_limited:cap,status,completed_at:now}; }

async function materializeMonitoredList(db: any, list: any, tier: string, limits: any) {
  const capacity = Math.max(0,Number(limits?.properties || 0)), requestLimit = Math.max(1,Number(limits?.requests_5m || 20));
  if (capacity < 1) throw new Error("PLAN_INELIGIBLE");
  const criteria = list.criteria && typeof list.criteria === "object" ? list.criteria : {}, intel = criteria.intelligence_filters && typeof criteria.intelligence_filters === "object" ? criteria.intelligence_filters : {}, filters = criteria.filters && typeof criteria.filters === "object" ? criteria.filters : {}, scopeType = clean(list.scope_type,20).toLowerCase(), scopeValue = clean(list.scope_value);
  if (!["municipality","county","zip","radius","polygon"].includes(scopeType)) throw new Error("UNSUPPORTED_SCOPE");
  const classes = Array.isArray(criteria.property_classes) ? criteria.property_classes.map((x:unknown) => clean(x,4)) : [], where = buildWhere(classes,filters,scopeType,scopeValue), common = await buildSpatialCommon(list,where), deliveryId = crypto.randomUUID();
  const {data:quota,error:quotaError} = await db.rpc("consume_municipal_quota",{p_user_id:list.user_id,p_endpoint:"dynamic-list-monitor",p_limit:requestLimit,p_rows:0,p_delivery_id:deliveryId});
  if (quotaError) throw new Error("QUOTA_CHECK_FAILED");
  if (!quota?.allowed) throw new Error("MONITOR_QUOTA_REACHED");
  const outFields = "PAMS_PIN,PCLBLOCK,PCLLOT,PCLQCODE,COUNTY,MUN_NAME,PROP_CLASS,PROP_LOC,ZIP_CODE,ZIP5,LAND_VAL,IMPRVT_VAL,NET_VALUE,LAST_YR_TX,BLDG_DESC,CALC_ACRE,YR_CONSTR,SALE_PRICE,DEED_DATE,SALES_CODE,DWELL,COMM_DWELL", snapshot = definition(list);

  // Recurring monitoring always uses the resumable scan path. One source page is
  // processed per claim so even large counties and developer plans stay bounded.
  let run: any = null;
  if (list.monitor_run_id) { const q = await db.from("agent_dynamic_list_materialization_runs").select("*").eq("id",list.monitor_run_id).eq("dynamic_list_id",list.id).eq("user_id",list.user_id).maybeSingle(); if (q.data?.status === "scanning") run = q.data; }
  if (!run) { const q = await db.from("agent_dynamic_list_materialization_runs").select("*").eq("dynamic_list_id",list.id).eq("user_id",list.user_id).eq("status","scanning").order("created_at",{ascending:false}).limit(1).maybeSingle(); if (q.data && sameDefinition(q.data.definition_snapshot,snapshot)) run = q.data; else if (q.data) await failRun(db,q.data,"Saved list definition no longer matches the resumable scan."); }
  if (!run) { const countP = new URLSearchParams({...common,returnCountOnly:"true"}), cr = await fetch(`${NJOGIS}?${countP}`); if (!cr.ok) throw new Error("SOURCE_COUNT_UNAVAILABLE"); const cj = await cr.json(); if (cj.error) throw new Error("SOURCE_COUNT_FAILED"); const ins = await db.from("agent_dynamic_list_materialization_runs").insert({dynamic_list_id:list.id,user_id:list.user_id,generation:crypto.randomUUID(),definition_snapshot:snapshot,candidate_count:Math.max(0,Number(cj.count || 0)),scanned_count:0,matched_count:0,status:"scanning",detail:"Bounded recurring complete scan in progress.",source_name:sourceName()}).select("*").single(); if (ins.error) throw new Error("SCAN_START_FAILED"); run = ins.data; }
  if (!sameDefinition(run.definition_snapshot,snapshot)) { await failRun(db,run,"Saved list definition changed during recurring scan."); throw new Error("SCAN_DEFINITION_CHANGED"); }

  const remaining = Math.max(0,Number(run.candidate_count) - Number(run.scanned_count));
  if (remaining === 0) { const sourceCount = Number(run.matched_count || 0), stored = (await db.from("agent_dynamic_list_properties").select("*",{count:"exact",head:true}).eq("dynamic_list_id",list.id).eq("generation",run.generation)).count || 0, expected = Math.min(sourceCount,capacity); if (stored !== expected) { await failRun(db,run,"Stored membership count did not match the complete recurring scan."); throw new Error("SCAN_MEMBERSHIP_MISMATCH"); } const final = await finalizeGeneration(db,list,run.generation,snapshot,tier,capacity,sourceCount,stored,Number(run.candidate_count)); await db.from("agent_dynamic_list_materialization_runs").update({status:"complete",detail:"Complete recurring scan materialized.",updated_at:final.completed_at,completed_at:final.completed_at}).eq("id",run.id); return final; }

  const pageSize = Math.min(PAGE_SIZE,remaining), p = new URLSearchParams({...common,outFields,returnGeometry:"false",resultOffset:String(run.scanned_count),resultRecordCount:String(pageSize),orderByFields:"MUN_NAME ASC, PROP_LOC ASC, PAMS_PIN ASC"}), rr = await fetch(`${NJOGIS}?${p}`);
  if (!rr.ok) { await failRun(db,run,"NJ parcel page request failed."); throw new Error("SOURCE_PAGE_UNAVAILABLE"); }
  const j = await rr.json(); if (j.error) { await failRun(db,run,"NJ parcel page returned an error."); throw new Error("SOURCE_PAGE_FAILED"); }
  const raw = j.features || []; if (raw.length < pageSize && Number(run.scanned_count) + raw.length < Number(run.candidate_count)) { await failRun(db,run,"Upstream candidate page was incomplete."); throw new Error("INCOMPLETE_UPSTREAM_PAGE"); }
  const rows = raw.map((f:any) => normalize(f.attributes || {})).filter((r:any) => r.pams_pin), saleFiltered = rows.filter((r:any) => salePass(r,filters)); let matched = saleFiltered;
  if (hasKeys(intel)) { const enriched = await metricsFor(db,saleFiltered); matched = enriched.filter((x:any) => intelPass(x.metrics,intel)).map((x:any) => x.row); }
  const oldMatched = Number(run.matched_count || 0), remainingCapacity = Math.max(0,capacity - Math.min(oldMatched,capacity)), keep = matched.slice(0,remainingCapacity);
  try { await cacheRows(db,keep); await insertMembers(db,list.user_id,list.id,run.generation,keep); } catch (e) { await failRun(db,run,e instanceof Error ? e.message : "Materialization write failed"); throw e; }
  const scanned = Number(run.scanned_count) + raw.length, matchedCount = oldMatched + matched.length, now = new Date().toISOString(); await db.from("agent_dynamic_list_materialization_runs").update({scanned_count:scanned,matched_count:matchedCount,updated_at:now,detail:`Scanned ${scanned} of ${run.candidate_count} statewide candidates.`}).eq("id",run.id);
  if (scanned < Number(run.candidate_count)) return {status:"scanning",run_id:run.id,generation:run.generation,candidate_count:Number(run.candidate_count),scanned_count:scanned,matched_count:matchedCount,source_complete:false};
  const sourceCount = matchedCount, stored = (await db.from("agent_dynamic_list_properties").select("*",{count:"exact",head:true}).eq("dynamic_list_id",list.id).eq("generation",run.generation)).count || 0, expected = Math.min(sourceCount,capacity);
  if (stored !== expected) { await failRun(db,{...run,scanned_count:scanned,matched_count:matchedCount},"Stored membership count did not match the complete recurring scan."); throw new Error("SCAN_MEMBERSHIP_MISMATCH"); }
  const final = await finalizeGeneration(db,list,run.generation,snapshot,tier,capacity,sourceCount,stored,Number(run.candidate_count)); await db.from("agent_dynamic_list_materialization_runs").update({status:"complete",detail:"Complete recurring scan materialized.",updated_at:final.completed_at,completed_at:final.completed_at}).eq("id",run.id); return final;
}

function emailConfigured() { return Boolean(Deno.env.get("EMAILJS_PUBLIC_KEY") && Deno.env.get("EMAILJS_PRIVATE_KEY") && Deno.env.get("EMAILJS_SERVICE_ID") && Deno.env.get("EMAILJS_AGENT_DIGEST_TEMPLATE_ID")); }
async function recordDelivery(db: any, list: any, diff: any, status: string, attempts: number, lastError: string | null, deliveredAt: string | null) { const summary = {list_name:clean(list.name,80),scope_type:clean(list.scope_type,20),scope_value:clean(list.scope_value,120),new_match_count:Number(diff.new_match_count || 0),dropped_match_count:Number(diff.dropped_match_count || 0),assessment_change_count:Number(diff.assessment_change_count || 0),source_complete:Boolean(diff.source_complete),capacity_limited:Boolean(diff.capacity_limited)}; const now = new Date().toISOString(); await db.from("agent_dynamic_list_alert_deliveries").upsert({user_id:list.user_id,dynamic_list_id:list.id,diff_id:diff.id,channel:"email",status,attempts,scheduled_at:now,delivered_at:deliveredAt,last_error:lastError,summary,updated_at:now},{onConflict:"diff_id,channel"}); }
async function deliverDiffEmail(db: any, list: any, diff: any, suppress: boolean) {
  const total = Number(diff.new_match_count || 0) + Number(diff.dropped_match_count || 0) + Number(diff.assessment_change_count || 0);
  if (!total) return {status:"no_change"};
  if (!diff.source_complete || diff.capacity_limited) return {status:"suppressed_incomplete"};
  const {data:prior} = await db.from("agent_dynamic_list_alert_deliveries").select("status,attempts").eq("diff_id",diff.id).eq("channel","email").maybeSingle();
  if (prior?.status === "sent") return {status:"deduped"};
  if (suppress) return {status:"suppressed_canary"};
  const attempts = Number(prior?.attempts || 0) + 1;
  if (!emailConfigured()) { await recordDelivery(db,list,diff,"failed",attempts,"email_provider_not_configured",null); return {status:"failed",reason:"email_provider_not_configured"}; }
  const authResult = await db.auth.admin.getUserById(list.user_id), email = authResult.data.user?.email;
  if (!email) { await recordDelivery(db,list,diff,"failed",attempts,"recipient_email_unavailable",null); return {status:"failed",reason:"recipient_email_unavailable"}; }
  const publicKey = Deno.env.get("EMAILJS_PUBLIC_KEY")!, privateKey = Deno.env.get("EMAILJS_PRIVATE_KEY")!, serviceId = Deno.env.get("EMAILJS_SERVICE_ID")!, templateId = Deno.env.get("EMAILJS_AGENT_DIGEST_TEMPLATE_ID")!;
  const counts = `${Number(diff.new_match_count || 0)} new · ${Number(diff.dropped_match_count || 0)} no longer matching · ${Number(diff.assessment_change_count || 0)} assessment changes`, rows = `<tr><td style="padding:14px 10px;border-bottom:1px solid #e4e9ee;color:#0f8b8d;font-weight:800">LIST</td><td style="padding:14px 10px;border-bottom:1px solid #e4e9ee"><b>${html(list.name,80)}</b><br><span style="color:#65758a">${html(counts,220)}</span><br><small>${html(list.scope_value,120)} · Complete, uncapped source generations only.</small></td><td style="padding:14px 10px;border-bottom:1px solid #e4e9ee;font-weight:800">${total}</td></tr>`;
  const response = await fetch("https://api.emailjs.com/api/v1.0/email/send",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({service_id:serviceId,template_id:templateId,user_id:publicKey,accessToken:privateKey,template_params:{to_email:email,subject:`Watchdog: ${total} saved-list change${total === 1 ? "" : "s"} in ${clean(list.scope_value,80)}`,opportunity_count:total,digest_rows:rows,desk_url:`https://njpropertytaxrelief.com/property/market-list?id=${encodeURIComponent(list.id)}`,compliance_note:"This alert reports sourced property-list changes, not owner identity, seller intent, distress, or a prediction. Match changes are alerted only when both source generations are complete and uncapped."}})});
  if (!response.ok) { await recordDelivery(db,list,diff,"failed",attempts,"email_provider_rejected_request",null); return {status:"failed",reason:"email_provider_rejected_request"}; }
  const deliveredAt = new Date().toISOString(); await recordDelivery(db,list,diff,"sent",attempts,null,deliveredAt); await db.from("agent_dynamic_lists").update({last_alert_at:deliveredAt,updated_at:deliveredAt}).eq("id",list.id).eq("user_id",list.user_id); return {status:"sent"};
}

async function runDynamicLists(db: any, body: any) {
  const limit = Math.max(1,Math.min(5,Number(body?.limit || 5))), suppress = body?.suppress_delivery === true, {data:claimed,error:claimError} = await db.rpc("claim_due_agent_dynamic_list_monitors_v1",{p_limit:limit});
  if (claimError) throw claimError;
  const result: any = {claimed:(claimed || []).length,completed:0,scanning:0,failed:0,no_change:0,alerts_sent:0,alerts_suppressed:0,email_configured:emailConfigured(),lists:[]};
  for (const list of claimed || []) {
    try {
      const {data:planData} = await db.rpc("watchdog_effective_plan",{p_user_id:list.user_id}), tier = String(planData || "standard"), cadence = cadenceFor(tier);
      if (!cadence) { await db.from("agent_dynamic_lists").update({monitor_cadence:null,next_check_at:null,monitor_run_id:null,monitor_lease_until:null,last_monitor_status:"plan_ineligible",last_monitor_detail:"Recurring monitoring is unavailable under the current effective plan.",updated_at:new Date().toISOString()}).eq("id",list.id); result.failed++; result.lists.push({id:list.id,status:"plan_ineligible"}); continue; }
      const {data:limits,error:limitsError} = await db.rpc("agent_plan_limits",{p_plan:tier}); if (limitsError) throw new Error("PLAN_LIMITS_UNAVAILABLE");
      const refresh: any = await materializeMonitoredList(db,list,tier,limits);
      if (refresh.status === "scanning") { const next = new Date(Date.now() + 3600000).toISOString(); await db.from("agent_dynamic_lists").update({monitor_cadence:cadence,monitor_run_id:refresh.run_id,monitor_lease_until:null,next_check_at:next,last_monitor_status:"scanning",last_monitor_detail:`Complete scan ${refresh.scanned_count} of ${refresh.candidate_count} candidates.`,updated_at:new Date().toISOString()}).eq("id",list.id); result.scanning++; result.lists.push({id:list.id,status:"scanning",scanned_count:refresh.scanned_count,candidate_count:refresh.candidate_count}); continue; }
      const {data:diff} = await db.from("agent_dynamic_list_diffs").select("id,source_complete,capacity_limited,new_match_count,dropped_match_count,assessment_change_count,created_at").eq("dynamic_list_id",list.id).eq("to_generation",refresh.generation).maybeSingle();
      const delivery = diff ? await deliverDiffEmail(db,list,diff,suppress) : {status:"no_change"}, completedAt = refresh.completed_at || new Date().toISOString(), next = nextSchedule(cadence,new Date(completedAt).getTime());
      let status = "complete_no_change", detail = "Refresh completed with no alertable complete-generation change.";
      if (delivery.status === "sent") { status = "complete_alert_sent"; detail = "Refresh completed and one privacy-minimized diff email was delivered."; result.alerts_sent++; }
      else if (delivery.status === "suppressed_canary" || delivery.status === "suppressed_incomplete") { status = "complete_alert_suppressed"; detail = delivery.status === "suppressed_canary" ? "Refresh completed; delivery was intentionally suppressed for canary verification." : "Refresh completed but alerting was suppressed because a complete uncapped comparison was unavailable."; result.alerts_suppressed++; }
      else if (delivery.status === "failed") { status = "complete_delivery_failed"; detail = `Refresh completed; alert delivery failed safely (${delivery.reason}).`; result.failed++; }
      else result.no_change++;
      await db.from("agent_dynamic_lists").update({monitor_cadence:cadence,monitor_run_id:null,monitor_lease_until:null,next_check_at:next,last_monitor_completed_at:completedAt,last_monitor_status:status,last_monitor_detail:detail,updated_at:new Date().toISOString()}).eq("id",list.id);
      result.completed++; result.lists.push({id:list.id,status,source_complete:refresh.source_complete,capacity_limited:refresh.capacity_limited,diff:diff ? {new:Number(diff.new_match_count || 0),dropped:Number(diff.dropped_match_count || 0),assessment:Number(diff.assessment_change_count || 0)} : null,delivery:delivery.status});
    } catch (e) {
      const code = clean(e instanceof Error ? e.message : "MONITOR_FAILED",120), next = retrySchedule();
      await db.from("agent_dynamic_lists").update({monitor_lease_until:null,next_check_at:next,last_monitor_status:"failed",last_monitor_detail:`Recurring refresh failed safely (${code}). The prior durable generation remains in place.`,updated_at:new Date().toISOString()}).eq("id",list.id);
      result.failed++; result.lists.push({id:list.id,status:"failed",code});
    }
  }
  return result;
}

async function runLegacy(db: any, runAt: string) {
  let snapshots = 0, changes = 0, jobs = 0;
  const {data:rows,error} = await db.from("saved_properties").select("user_id,pams_pin,address,town,county,block,lot,assessed,last_year_tax,effective_rate,watchdog_value,verified,verify_level"); if (error) throw error;
  const byPin=new Map<string,any[]>();for(const row of rows||[]){if(!row.pams_pin)continue;const a=byPin.get(row.pams_pin)||[];a.push(row);byPin.set(row.pams_pin,a);}
  for(const [pin,owners] of byPin){const sample=owners[0],payload=Object.fromEntries(fields.map(k=>[k,sample[k]??null])),payloadHash=await sha(stable(payload));
    const {data:prior}=await db.from("property_record_snapshots").select("id,payload,captured_at").eq("pams_pin",pin).eq("source_kind","manual").eq("job_key","watchdog.saved-property-sync").order("captured_at",{ascending:false}).limit(1).maybeSingle();
    const {data:snap,error:se}=await db.from("property_record_snapshots").upsert({pams_pin:pin,source_kind:"manual",source_url:sourceUrl,source_recorded_at:runAt,captured_at:runAt,payload,payload_hash:payloadHash,job_key:"watchdog.saved-property-sync"},{onConflict:"pams_pin,source_kind,payload_hash",ignoreDuplicates:true}).select("id").maybeSingle();if(se)throw se;if(!snap)continue;snapshots++;
    if(prior){for(const k of fields){const before=prior.payload?.[k]??null,after=payload[k]??null;if(JSON.stringify(before)===JSON.stringify(after))continue;const m=materiality(k,before,after),delta=Number.isFinite(Number(after)-Number(before))?Number(after)-Number(before):null;
      const {data:ch}=await db.from("property_field_changes").insert({snapshot_id:snap.id,pams_pin:pin,field_key:k,old_value:before===null?null:before,new_value:after===null?null:after,change_kind:before===null?"added":after===null?"removed":"changed",materiality:m,delta_numeric:delta,source_key:"watchdog.saved-property-sync",source_url:sourceUrl,observed_at:runAt}).select("id").single();changes++;
      for(const owner of owners){const pref=await db.from("property_alert_preferences").select("paused,alert_score,alert_tax,alert_assessment,alert_deadline").eq("user_id",owner.user_id).eq("pams_pin",pin).maybeSingle();if(pref.data?.paused)continue;const type=k==="assessed"?"assessment_change":k==="last_year_tax"?"tax_change":k==="watchdog_value"?"market_change":"evidence_change";await db.from("property_update_events").upsert({user_id:owner.user_id,pams_pin:pin,event_key:`field:${ch.id}:${owner.user_id}`,event_type:type,severity:m==="action"?"action":m==="material"?"watch":"info",title:`${k.replaceAll("_"," ")} changed`,summary:`Watchdog recorded a sourced before-and-after change for ${owner.address||pin}.`,payload:{change_id:ch.id,source_key:"watchdog.saved-property-sync"},occurred_at:runAt,marker_id:`property.${k}`,old_value:String(before??""),new_value:String(after??""),delta_numeric:delta,source_url:sourceUrl,minimum_plan:"standard"},{onConflict:"user_id,event_key"});}
    }}
  }
  await db.rpc("queue_due_data_center_jobs");
  const {data:due}=await db.from("data_center_delivery_jobs").select("id,user_id,view_id,name,scope,format,cadence").eq("status","queued").limit(25);
  for(const job of due||[]){await db.from("data_center_delivery_jobs").update({status:"running",updated_at:runAt}).eq("id",job.id);const {data:view}=await db.from("saved_data_center_views").select("name,marker_ids,filters").eq("id",job.view_id).eq("user_id",job.user_id).maybeSingle();const next=job.cadence==="weekly"?new Date(Date.now()+7*86400000):job.cadence==="monthly"?new Date(Date.now()+30*86400000):null;await db.from("data_center_delivery_jobs").update({status:"ready",last_run_at:runAt,next_run_at:next?.toISOString()||runAt,result:{generated_at:runAt,view:view||null,format:job.format,delivery:"download-ready"},updated_at:runAt}).eq("id",job.id);jobs++;}
  return {snapshots,changes,data_center_jobs:jobs};
}

Deno.serve(async(req:Request)=>{
  if(req.method!=="POST")return Response.json({error:"POST required"},{status:405});
  let body:any={};try{body=await req.json();}catch{}
  const mode=clean(body?.mode,40)||"legacy",url=Deno.env.get("SUPABASE_URL")||"",key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
  if(!url||!key)return Response.json({error:"Unavailable"},{status:503});
  const db=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}),legacySecret=Deno.env.get("WATCHDOG_AUTOMATION_SECRET")||Deno.env.get("AGENT_DIGEST_CRON_SECRET")||"",legacyAuthorized=Boolean(legacySecret&&req.headers.get("x-watchdog-automation-secret")===legacySecret);
  if(mode==="dynamic_lists"){const token=req.headers.get("x-watchdog-monitor-token")||"";let monitorAuthorized=false;if(token){const check=await db.rpc("verify_agent_list_monitor_token_v1",{p_token:token});monitorAuthorized=!check.error&&check.data===true;}if(!legacyAuthorized&&!monitorAuthorized)return Response.json({error:"Unauthorized"},{status:401});const result=await runDynamicLists(db,body);return Response.json({ok:true,mode,run_at:new Date().toISOString(),...result},{headers:{"cache-control":"no-store"}});}
  if(!legacyAuthorized)return Response.json({error:"Unauthorized"},{status:401});
  const runAt=new Date().toISOString(),result=await runLegacy(db,runAt);return Response.json({ok:true,run_at:runAt,...result},{headers:{"cache-control":"no-store"}});
});
