import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const ORIGINS=new Set(['https://njpropertytaxrelief.com','https://www.njpropertytaxrelief.com']);
const SCORE_MARKERS=new Set(['watchdog.watchdog_score','watchdog.score','watchdog.tax_pressure','watchdog.revaluation_risk','uniformity.score']);
const CLIENT_MARKERS=new Set(['fema.flood_zone','fema.flood_risk']);
function cors(req:Request){const o=req.headers.get('origin')||'';return{'Access-Control-Allow-Origin':ORIGINS.has(o)?o:'https://njpropertytaxrelief.com','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Vary':'Origin'}}
function out(req:Request,s:number,p:any){return new Response(JSON.stringify(p),{status:s,headers:{...cors(req),'Content-Type':'application/json','Cache-Control':'private, no-store'}})}
function clean(v:any,max=100){return String(v||'').trim().slice(0,max)}
async function callFn(base:string,name:string,auth:string,apikey:string,body:any){const r=await fetch(`${base}/functions/v1/${name}`,{method:'POST',headers:{Authorization:auth,apikey,'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(j?.error||`${name} failed`),{code:j?.code||'WORKBENCH_REFRESH_PHASE',phase:name,status:r.status,detail:j});return j}
function mergeNested(a:any,b:any){const out:any={...(a||{})};for(const [pin,vals] of Object.entries(b||{})){out[pin]={...(out[pin]||{}),...(vals as any)}}return out}
Deno.serve(async req=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors(req)});if(req.method!=='POST')return out(req,405,{error:'POST required'});
 const auth=req.headers.get('authorization')||'',base=Deno.env.get('SUPABASE_URL')||'',anon=Deno.env.get('SUPABASE_ANON_KEY')||'',service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
 if(!auth.startsWith('Bearer '))return out(req,401,{error:'Sign in required',code:'AUTH_REQUIRED'});
 const uc=createClient(base,anon,{global:{headers:{Authorization:auth}},auth:{persistSession:false}}),admin=createClient(base,service,{auth:{persistSession:false,autoRefreshToken:false}});const {data:u}=await uc.auth.getUser();if(!u.user)return out(req,401,{error:'Session invalid',code:'AUTH_REQUIRED'});
 let body:any={};try{body=await req.json()}catch{return out(req,400,{error:'Invalid JSON'})}
 const pins=[...new Set((Array.isArray(body.pams_pins)?body.pams_pins:[]).map((x:any)=>clean(x,80)).filter(Boolean))].slice(0,1000),markers=[...new Set((Array.isArray(body.marker_ids)?body.marker_ids:[]).map((x:any)=>clean(x,140)).filter(Boolean))].slice(0,500);
 const providerMarkers=markers.filter(id=>!SCORE_MARKERS.has(id)&&!CLIENT_MARKERS.has(id));
 const routedMarkers={provider:providerMarkers,scores:markers.filter(id=>SCORE_MARKERS.has(id)),client:markers.filter(id=>CLIENT_MARKERS.has(id))};
 if(!pins.length)return out(req,200,{records:[],markers:{},meta:{},phases:[],summary:{requested:0},routed_markers:routedMarkers});
 const phases:any[]=[];let baseline:any=null,hydrate:any=null,scores:any=null;
 try{
  const t0=Date.now();baseline=await callFn(base,'workbench-baseline',auth,anon,{pams_pins:pins,source:clean(body.source||'workbench_refresh',40)});phases.push({name:'baseline',status:'complete',duration_ms:Date.now()-t0,...baseline.summary});
  if(providerMarkers.length){const t1=Date.now();hydrate=await callFn(base,'workbench-hydrate',auth,anon,{pams_pins:pins,marker_ids:providerMarkers});phases.push({name:'providers',status:'complete',duration_ms:Date.now()-t1,requested_markers:providerMarkers.length,provider_summary:hydrate.provider_summary||{}})}else phases.push({name:'providers',status:'skipped',reason:'No server-provider fields selected',requested_markers:0});
  const t2=Date.now();scores=await callFn(base,'workbench-score',auth,anon,{pams_pins:pins});phases.push({name:'scores',status:'complete',duration_ms:Date.now()-t2,model_version:scores.model_version,...(scores.summary||{})});
  if(routedMarkers.client.length)phases.push({name:'client_fields',status:'delegated',markers:routedMarkers.client,reason:'Resolved in browser from parcel coordinates / dedicated client service'});
  const providerSummary=hydrate?.provider_summary||{},scoreSummary=scores?.summary||{},summary={requested:pins.length,resolved:Number(baseline?.summary?.resolved||0),missing:Number(baseline?.summary?.missing||0),canonical_alias_hits:Number(baseline?.summary?.canonical_alias_hits||0),warehouse_hits:Number(baseline?.summary?.warehouse_hits||0),nj_hits:Number(baseline?.summary?.nj_hits||0),available:Number(providerSummary.available||0),source_checked_no_value:Number(providerSummary.source_checked_no_value||0),not_computed:Number(providerSummary.not_computed||0),provider_missing:Number(providerSummary.provider_missing||0),not_entitled:Number(providerSummary.not_entitled||0),score_count:Number(scoreSummary.observations_written||0),scored_properties:Number(scoreSummary.scored||0),score_alias_hits:Number(scoreSummary.canonical_alias_hits||0),score_model:scores?.model_version||null,provider_markers_requested:providerMarkers.length,client_markers_delegated:routedMarkers.client.length};
  const mergedMarkers=mergeNested(hydrate?.markers,scores?.markers),mergedMeta=mergeNested(hydrate?.meta,scores?.meta);
  await admin.from('workbench_refresh_runs').insert({user_id:u.user.id,source:clean(body.source||'workbench_refresh',40),requested_count:summary.requested,resolved_count:summary.resolved,warehouse_hits:summary.warehouse_hits,nj_hits:summary.nj_hits,derived_count:summary.available,score_count:summary.score_count,status:'complete',summary:{...summary,routed_markers:routedMarkers,phases}});
  return out(req,200,{records:baseline?.records||[],markers:mergedMarkers,meta:mergedMeta,provider_summary:providerSummary,score_summary:scoreSummary,score_model:scores?.model_version||null,routed_markers:routedMarkers,phases,summary,checked_at:new Date().toISOString()});
 }catch(e:any){const phase=e?.phase||'unknown';phases.push({name:phase,status:'error',message:String(e?.message||'Refresh failed')});await admin.from('workbench_refresh_runs').insert({user_id:u.user.id,source:clean(body.source||'workbench_refresh',40),requested_count:pins.length,resolved_count:Number(baseline?.summary?.resolved||0),warehouse_hits:Number(baseline?.summary?.warehouse_hits||0),nj_hits:Number(baseline?.summary?.nj_hits||0),score_count:Number(scores?.summary?.observations_written||0),status:'partial_error',summary:{phases,routed_markers:routedMarkers,error_phase:phase}});return out(req,503,{error:'Workbench refresh could not complete every phase.',code:'WORKBENCH_REFRESH_PARTIAL',phase,phases,routed_markers:routedMarkers})}
});