import { createClient } from '@supabase/supabase-js';
const enc=new TextEncoder();
function hex(b:ArrayBuffer){return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,'0')).join('')}
function eq(a:string,b:string){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
async function verify(raw:string,h:string,s:string){const p=h.split(';').map(x=>x.trim().split('=')),ts=p.find(x=>x[0]==='ts')?.[1],sigs=p.filter(x=>x[0]==='h1').map(x=>x[1]);if(!ts||!sigs.length)return false;const n=Number(ts),tol=Number(Deno.env.get('PADDLE_WEBHOOK_TOLERANCE_SECONDS')||'5');if(!Number.isFinite(n)||Math.abs(Math.floor(Date.now()/1000)-n)>tol)return false;const k=await crypto.subtle.importKey('raw',enc.encode(s),{name:'HMAC',hash:'SHA-256'},false,['sign']);const dig=hex(await crypto.subtle.sign('HMAC',k,enc.encode(`${ts}:${raw}`)));return sigs.some(x=>eq(x.toLowerCase(),dig))}
const catalog:Record<string,{tier:string,plan:string,interval:string,capacity:number}>={
'pri_01kzp7mcvs46mmcdwyxd0sjvne':{tier:'agent',plan:'pro',interval:'monthly',capacity:25},'pri_01kzp7kwcfzs9znjwwj24zgdb6':{tier:'agent',plan:'pro',interval:'yearly',capacity:25},
'pri_01kzp7jhcsk07k47dtvrmaxvjh':{tier:'pro',plan:'pro_plus',interval:'monthly',capacity:250},'pri_01kzp7hwtx1qp946ftnmj4xpqc':{tier:'pro',plan:'pro_plus',interval:'yearly',capacity:250},
'pri_01kzp7h2mw9waf3exfsee8jxsb':{tier:'pro_plus',plan:'pro_plus',interval:'monthly',capacity:2500},'pri_01kzp7fmg7ksff6sjg054mqbe4':{tier:'pro_plus',plan:'pro_plus',interval:'yearly',capacity:2500},
'pri_01kzp7e6vsmsbjyw36mxgvww1b':{tier:'teams',plan:'pro_plus',interval:'monthly',capacity:10000}};
Deno.serve(async(req)=>{if(req.method!=='POST')return new Response('Method not allowed',{status:405});const secret=Deno.env.get('PADDLE_WEBHOOK_SECRET'),sig=req.headers.get('Paddle-Signature');if(!secret||!sig)return new Response('Webhook not configured',{status:503});const raw=await req.text();if(!(await verify(raw,sig,secret)))return new Response('Invalid Paddle signature',{status:400});let event:any;try{event=JSON.parse(raw)}catch{return new Response('Invalid JSON',{status:400})}const id=String(event?.event_id||''),type=String(event?.event_type||''),at=event?.occurred_at||null;if(!id||!type)return new Response('Invalid Paddle event',{status:400});const service=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);const {data:prior}=await service.from('billing_provider_events').select('provider_event_id').eq('provider','paddle').eq('provider_event_id',id).maybeSingle();if(prior)return new Response('ok');let result:any={handled:false};
if(type.startsWith('subscription.')){const sub=event.data||{},sid=String(sub.id||''),cid=String(sub.customer_id||''),custom=sub?.custom_data||{},priceId=sub?.items?.[0]?.price?.id?String(sub.items[0].price.id):'',cat=catalog[priceId];let uid=custom.watchdog_user_id?String(custom.watchdog_user_id):custom.supabase_user_id?String(custom.supabase_user_id):null;if(!uid&&sid){const {data:m}=await service.from('account_entitlements').select('user_id').eq('provider','paddle').eq('provider_subscription_id',sid).maybeSingle();uid=m?.user_id||null}if(!uid&&cid){const {data:m}=await service.from('account_entitlements').select('user_id').eq('provider','paddle').eq('provider_customer_id',cid).maybeSingle();uid=m?.user_id||null}if(!uid||!cat){result={handled:false,warning:!uid?'unmapped subscription user':'unrecognized price',subscription_id:sid,price_id:priceId}}else{const {data:cur}=await service.from('account_entitlements').select('provider_event_at').eq('user_id',uid).maybeSingle(),incoming=at?new Date(at).getTime():Date.now(),current=cur?.provider_event_at?new Date(cur.provider_event_at).getTime():0;if(current&&incoming<current){result={handled:false,ignored:'out_of_order',user_id:uid,subscription_id:sid}}else{const status=String(sub.status||'none'),end=sub?.current_billing_period?.ends_at||sub?.next_billed_at||null,cancel=sub?.scheduled_change?.action==='cancel';const {error}=await service.from('account_entitlements').upsert({user_id:uid,plan_tier:cat.plan,billing_tier:cat.tier,billing_interval:cat.interval,property_capacity:cat.capacity,subscription_status:status,provider:'paddle',provider_customer_id:cid||null,provider_subscription_id:sid||null,provider_price_id:priceId||null,current_period_end:end,cancel_at_period_end:cancel,provider_event_at:at||new Date().toISOString(),source:'paddle-webhook',updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error)throw error;result={handled:true,user_id:uid,subscription_id:sid,plan_tier:cat.plan,billing_tier:cat.tier,billing_interval:cat.interval,status}}}}
else if(type==='transaction.completed')result={handled:true,audited_only:true,transaction_id:event?.data?.id||null};const {error:le}=await service.from('billing_provider_events').insert({provider:'paddle',provider_event_id:id,event_type:type,occurred_at:at,result});if(le&&le.code!=='23505')throw le;return new Response('ok')});