const makeRestHook = require('./rest-hook');

module.exports = makeRestHook({
  key: 'watchlist_alert',
  noun: 'Watchlist Alert',
  name: 'Watchlist Alert',
  description: 'Triggers when a watched property receives a new Watchdog change alert.',
  eventType: 'watchlist.alert',
  sample: {
    id: 'sample-watch',
    event_type: 'watchlist.alert',
    event_key: 'watchlist_alert:sample-watch',
    occurred_at: '2026-08-19T15:45:00Z',
    data: {
      property_update_id: '00000000-0000-0000-0000-000000000003',
      pams_pin: 'sample-pin',
      source_event_type: 'property.marker.changed',
      severity: 'medium',
      title: 'Watchlist property changed',
      summary: 'A watched property changed.',
      marker_id: 'property.assessed_value',
      old_value: '300000',
      new_value: '325000',
      delta_numeric: 25000,
      source_url: 'https://example.com/source',
      occurred_at: '2026-08-19T15:45:00Z',
    },
  },
  outputFields: [
    { key: 'data__property_update_id', label: 'Property Update ID' },
    { key: 'data__pams_pin', label: 'PAMS PIN' },
    { key: 'data__source_event_type', label: 'Source Event Type' },
    { key: 'data__severity', label: 'Severity' },
    { key: 'data__title', label: 'Title' },
    { key: 'data__summary', label: 'Summary' },
    { key: 'data__marker_id', label: 'Marker ID' },
    { key: 'data__old_value', label: 'Old Value' },
    { key: 'data__new_value', label: 'New Value' },
    { key: 'data__delta_numeric', label: 'Numeric Delta', type: 'number' },
    { key: 'data__source_url', label: 'Source URL' },
    { key: 'data__occurred_at', label: 'Alert Occurred At', type: 'datetime' },
  ],
});
