create table if not exists public.transaction_municipal_requirements (
  id bigint generated by default as identity primary key,
  municipality_code text not null check (municipality_code ~ '^\d{4}$'),
  municipality_name text not null,
  county text,
  requirement_key text not null check (requirement_key in ('resale_cco','smoke_fire_cert')),
  requirement_state text not null default 'verify' check (requirement_state in ('explicit_required','official_process_found','statewide_baseline','verify')),
  title text not null,
  requirements jsonb not null default '[]'::jsonb,
  fees jsonb not null default '[]'::jsonb,
  application_url text,
  department_url text,
  ordinance_url text,
  source_urls jsonb not null default '[]'::jsonb,
  source_excerpt text,
  source_hash text not null,
  last_verified_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (municipality_code, requirement_key)
);

create index if not exists transaction_municipal_requirements_code_idx
  on public.transaction_municipal_requirements(municipality_code, requirement_key);
create index if not exists transaction_municipal_requirements_state_idx
  on public.transaction_municipal_requirements(requirement_key, requirement_state);

alter table public.transaction_municipal_requirements enable row level security;
revoke all on table public.transaction_municipal_requirements from anon, authenticated;

comment on table public.transaction_municipal_requirements is
  'Service-only registry of official NJ municipal resale/CO and smoke-fire requirement evidence. Missing source coverage never means not required.';
