alter table public.marketing_provider_jobs
  add column if not exists product_type text,
  add column if not exists size_label text,
  add column if not exists mail_class text,
  add column if not exists recipient_count integer,
  add column if not exists retail_cents bigint,
  add column if not exists credit_cents bigint default 0,
  add column if not exists gross_margin_cents bigint;

create index if not exists marketing_provider_jobs_user_submitted_idx on public.marketing_provider_jobs(user_id,submitted_at desc);
create index if not exists marketing_provider_jobs_product_status_idx on public.marketing_provider_jobs(provider_key,product_type,status,created_at desc);
create index if not exists marketing_payments_user_paid_idx on public.marketing_payments(user_id,paid_at desc) where status in ('paid','succeeded','completed');

create or replace function public.marketing_direct_mail_product_quote(p_campaign_id uuid,p_product_type text,p_quantity integer,p_size_label text,p_mail_class text,p_provider_key text default 'pcm') returns jsonb language plpgsql security definer set search_path='public' as $function$
declare uid uuid:=auth.uid();plan text;provider text:=coalesce(nullif(trim(p_provider_key),''),'pcm');product text:=lower(replace(trim(coalesce(p_product_type,'postcard')),' ','_'));cost public.marketing_provider_cost_catalog%rowtype;gross_margin numeric;multiplier numeric;vendor_total_cents bigint;retail_unit_cents bigint;retail_total_cents bigint;margin_cents bigint;quote_id uuid;expires timestamptz:=now()+interval '30 minutes';eligible_count integer;
begin
 if uid is null or not public.can_use_data_workbench(uid) then raise exception 'Marketing Studio requires Agent or higher'; end if;
 if product not in ('postcard','letter','brochure','snap_apart','greeting_card') then raise exception 'Unsupported Direct Mail product type'; end if;
 if not exists(select 1 from public.marketing_campaigns c where c.id=p_campaign_id and c.user_id=uid) then raise exception 'Campaign not found'; end if;
 select count(*) into eligible_count from public.marketing_direct_mail_recipients r left join public.marketing_direct_mail_recipient_exclusions e on e.user_id=r.user_id and e.campaign_id=r.campaign_id and e.property_key=r.property_key where r.campaign_id=p_campaign_id and r.user_id=uid and r.validation_status='valid' and not coalesce(e.excluded,false);
 if eligible_count<25 or eligible_count>100000 then raise exception 'Direct-mail eligible recipient count must be between 25 and 100000'; end if;
 if p_quantity is not null and p_quantity<>eligible_count then raise exception 'Recipient count changed. Current eligible count is %',eligible_count; end if;
 plan:=public.watchdog_effective_plan(uid);
 select * into cost from public.marketing_provider_cost_catalog c where c.provider_key=provider and c.product_type=product and c.size_label=trim(p_size_label) and lower(c.mail_class)=lower(trim(p_mail_class)) and c.active order by c.effective_from desc,c.updated_at desc limit 1;
 if cost.id is null then raise exception 'Verified provider pricing is not configured for % / % / %',product,p_size_label,p_mail_class; end if;
 gross_margin:=case plan when 'agent' then .40 when 'pro' then .35 when 'pro_plus' then .30 when 'teams' then .25 when 'developer' then .25 else .40 end;multiplier:=1/(1-gross_margin);retail_unit_cents:=ceil((cost.base_cost_micros::numeric*multiplier)/10000.0);vendor_total_cents:=round((cost.base_cost_micros::numeric*eligible_count::numeric)/10000.0);retail_total_cents:=retail_unit_cents*eligible_count;margin_cents:=retail_total_cents-vendor_total_cents;
 insert into public.marketing_price_quotes(user_id,campaign_id,provider_key,channel,plan_key,quantity,vendor_cost_cents,retail_cents,margin_cents,pricing_detail,expires_at) values(uid,p_campaign_id,provider,'direct_mail',plan,eligible_count,vendor_total_cents,retail_total_cents,margin_cents,jsonb_build_object('pricing_model','provider_cost_plus_target_gross_margin','product_type',product,'size_label',cost.size_label,'mail_class',cost.mail_class,'provider_unit_cost_micros',cost.base_cost_micros,'retail_unit_cents',retail_unit_cents,'target_gross_margin',gross_margin,'provider_cost_source',cost.source,'provider_cost_effective_from',cost.effective_from,'eligible_recipient_count',eligible_count),expires) returning id into quote_id;
 update public.marketing_campaigns set settings=jsonb_set(jsonb_set(jsonb_set(coalesce(settings,'{}'::jsonb),'{direct_mail,product_type}',to_jsonb(product),true),'{direct_mail,size_label}',to_jsonb(cost.size_label),true),'{direct_mail,mail_class}',to_jsonb(cost.mail_class),true),updated_at=now() where id=p_campaign_id and user_id=uid;
 insert into public.marketing_events(user_id,campaign_id,event_type,source,payload) values(uid,p_campaign_id,'quote.created','watchdog',jsonb_build_object('quote_id',quote_id,'channel','direct_mail','provider_key',provider,'product_type',product,'quantity',eligible_count,'retail_cents',retail_total_cents,'vendor_cost_cents',vendor_total_cents,'margin_cents',margin_cents,'size_label',cost.size_label,'mail_class',cost.mail_class,'plan',plan));
 return jsonb_build_object('quote_id',quote_id,'campaign_id',p_campaign_id,'channel','direct_mail','provider_key',provider,'product_type',product,'plan',plan,'quantity',eligible_count,'size_label',cost.size_label,'mail_class',cost.mail_class,'vendor_cost_cents',vendor_total_cents,'provider_unit_cost_micros',cost.base_cost_micros,'retail_unit_cents',retail_unit_cents,'retail_cents',retail_total_cents,'margin_cents',margin_cents,'target_gross_margin',gross_margin,'expires_at',expires);
end $function$;

create or replace function public.marketing_direct_mail_quote(p_campaign_id uuid,p_quantity integer,p_size_label text,p_mail_class text,p_provider_key text default 'pcm') returns jsonb language sql security definer set search_path='public' as $function$ select public.marketing_direct_mail_product_quote(p_campaign_id,'postcard',p_quantity,p_size_label,p_mail_class,p_provider_key) $function$;

create or replace function public.marketing_direct_mail_product_options(p_provider_key text default 'pcm') returns jsonb language plpgsql security definer set search_path='public' as $function$
declare uid uuid:=auth.uid();provider text:=coalesce(nullif(trim(p_provider_key),''),'pcm');out jsonb;
begin
 if uid is null or not public.can_use_data_workbench(uid) then raise exception 'Marketing Studio requires Agent or higher'; end if;
 select jsonb_build_object('provider_key',provider,'products',jsonb_build_array(
 jsonb_build_object('key','postcard','label','Postcards','orderable',exists(select 1 from public.marketing_provider_cost_catalog where provider_key=provider and product_type='postcard' and active),'pricing',coalesce((select jsonb_agg(jsonb_build_object('size_label',size_label,'mail_class',mail_class,'base_cost_micros',base_cost_micros,'effective_from',effective_from) order by size_label,mail_class) from public.marketing_provider_cost_catalog where provider_key=provider and product_type='postcard' and active),'[]'::jsonb)),
 jsonb_build_object('key','letter','label','Letters','orderable',exists(select 1 from public.marketing_provider_cost_catalog where provider_key=provider and product_type='letter' and active),'pricing',coalesce((select jsonb_agg(jsonb_build_object('size_label',size_label,'mail_class',mail_class,'base_cost_micros',base_cost_micros,'effective_from',effective_from) order by size_label,mail_class) from public.marketing_provider_cost_catalog where provider_key=provider and product_type='letter' and active),'[]'::jsonb)),
 jsonb_build_object('key','brochure','label','Brochures','orderable',exists(select 1 from public.marketing_provider_cost_catalog where provider_key=provider and product_type='brochure' and active),'pricing',coalesce((select jsonb_agg(jsonb_build_object('size_label',size_label,'mail_class',mail_class,'base_cost_micros',base_cost_micros,'effective_from',effective_from) order by size_label,mail_class) from public.marketing_provider_cost_catalog where provider_key=provider and product_type='brochure' and active),'[]'::jsonb)),
 jsonb_build_object('key','snap_apart','label','Snap Aparts','orderable',exists(select 1 from public.marketing_provider_cost_catalog where provider_key=provider and product_type='snap_apart' and active),'pricing',coalesce((select jsonb_agg(jsonb_build_object('size_label',size_label,'mail_class',mail_class,'base_cost_micros',base_cost_micros,'effective_from',effective_from) order by size_label,mail_class) from public.marketing_provider_cost_catalog where provider_key=provider and product_type='snap_apart' and active),'[]'::jsonb)),
 jsonb_build_object('key','greeting_card','label','Greeting Cards','orderable',exists(select 1 from public.marketing_provider_cost_catalog where provider_key=provider and product_type='greeting_card' and active),'pricing',coalesce((select jsonb_agg(jsonb_build_object('size_label',size_label,'mail_class',mail_class,'base_cost_micros',base_cost_micros,'effective_from',effective_from) order by size_label,mail_class) from public.marketing_provider_cost_catalog where provider_key=provider and product_type='greeting_card' and active),'[]'::jsonb)))) into out;return out;
end $function$;

create or replace function public.marketing_direct_mail_admin_summary(p_days integer default 90) returns jsonb language plpgsql security definer set search_path='public' as $function$
declare uid uuid:=auth.uid();cutoff timestamptz:=now()-(greatest(1,least(coalesce(p_days,90),730))||' days')::interval;out jsonb;
begin
 if uid is null or not public.is_watchdog_developer() then raise exception 'Developer access required'; end if;
 with paid as(select p.*,greatest(0,coalesce(p.amount_cents,0)-coalesce(p.refunded_cents,0)) net_cash from public.marketing_payments p where p.status in('paid','succeeded','completed') and coalesce(p.paid_at,p.created_at)>=cutoff),jobs as(select j.*,coalesce(j.recipient_count,nullif(j.request_summary->>'recipient_count','')::int,0) pieces from public.marketing_provider_jobs j where j.provider_key='pcm' and j.created_at>=cutoff and j.status not in('failed','canceled','cancelled')),campaigns as(select c.* from public.marketing_campaigns c where c.created_at>=cutoff),funnel as(select jsonb_build_object('campaigns',count(distinct case when e.event_type='campaign.created' then e.campaign_id end),'audiences',count(distinct case when e.event_type like 'direct_mail.audience%' or e.event_type in('direct_mail.saved_area_created','direct_mail.farm_materialized') then e.campaign_id end),'designs',count(distinct case when e.event_type in('creative.pcm_design_selected','creative.created','creative.pcm_design_bound') then e.campaign_id end),'proofs',count(distinct case when e.event_type in('creative.pcm_proof_reviewed','creative.approved') then e.campaign_id end),'recipients',count(distinct case when e.event_type in('direct_mail.recipients_prepared','direct_mail.addresses_prepared') then e.campaign_id end),'quotes',count(distinct case when e.event_type='quote.created' then e.campaign_id end),'payments',count(distinct case when e.event_type in('campaign.payment_captured','payment.captured') then e.campaign_id end),'submitted',count(distinct case when e.event_type='direct_mail.submitted' then e.campaign_id end)) value from public.marketing_events e where e.occurred_at>=cutoff)
 select jsonb_build_object('days',greatest(1,least(coalesce(p_days,90),730)),'customer_base',(select count(*) from public.account_entitlements a where a.plan_tier in('agent','pro','pro_plus','teams','developer') and coalesce(a.subscription_status,'active') not in('canceled','cancelled','expired')),'direct_mail_users',(select count(distinct c.user_id) from campaigns c),'campaigns',(select count(*) from campaigns),'paid_customers',(select count(distinct user_id) from paid),'cash_collected_cents',coalesce((select sum(net_cash) from paid),0),'refunds_cents',coalesce((select sum(coalesce(refunded_cents,0)) from paid),0),'provider_orders',(select count(*) from jobs),'pieces',coalesce((select sum(pieces) from jobs),0),'vendor_cost_cents',coalesce((select sum(coalesce(vendor_cost_cents,0)) from jobs),0),'booked_retail_cents',coalesce((select sum(coalesce(q.retail_cents,j.retail_cents,0)) from jobs j left join public.marketing_price_quotes q on q.id=j.quote_id),0),'gross_margin_cents',coalesce((select sum(coalesce(q.retail_cents,j.retail_cents,0)-coalesce(j.vendor_cost_cents,0)) from jobs j left join public.marketing_price_quotes q on q.id=j.quote_id),0),'average_order_value_cents',coalesce((select round(avg(coalesce(q.retail_cents,j.retail_cents,0))) from jobs j left join public.marketing_price_quotes q on q.id=j.quote_id),0),'repeat_customers',(select count(*) from(select user_id from jobs group by user_id having count(*)>=2)x),'credits_granted_cents',coalesce((select sum(grant_cents) from public.marketing_credit_accounts),0),'credits_used_cents',coalesce((select sum(used_cents) from public.marketing_credit_accounts),0),'credits_available_cents',coalesce((select sum(greatest(grant_cents-used_cents,0)) from public.marketing_credit_accounts where expires_at>now()),0),'funnel',(select value from funnel),'generated_at',now()) into out;return out;
end $function$;

create or replace function public.marketing_direct_mail_admin_customers(p_limit integer default 100,p_offset integer default 0,p_segment text default 'all') returns jsonb language plpgsql security definer set search_path='public' as $function$
declare uid uuid:=auth.uid();lim int:=greatest(1,least(coalesce(p_limit,100),500));off int:=greatest(0,coalesce(p_offset,0));seg text:=lower(coalesce(nullif(trim(p_segment),''),'all'));out jsonb;
begin
 if uid is null or not public.is_watchdog_developer() then raise exception 'Developer access required'; end if;
 with members as(select a.user_id,a.plan_tier,a.billing_interval,a.subscription_status,p.email,p.full_name,p.display_name,p.created_at account_created from public.account_entitlements a left join public.profiles p on p.id=a.user_id where a.plan_tier in('agent','pro','pro_plus','teams','developer')),campaign_stats as(select user_id,count(*) campaigns,max(created_at) last_campaign_at from public.marketing_campaigns group by user_id),pay_stats as(select user_id,count(*) filter(where status in('paid','succeeded','completed')) paid_payments,coalesce(sum(greatest(0,coalesce(amount_cents,0)-coalesce(refunded_cents,0))) filter(where status in('paid','succeeded','completed')),0) cash_spend_cents,max(coalesce(paid_at,created_at)) filter(where status in('paid','succeeded','completed')) last_paid_at from public.marketing_payments group by user_id),job_stats as(select user_id,count(*) filter(where provider_key='pcm' and status not in('failed','canceled','cancelled')) orders,coalesce(sum(coalesce(recipient_count,nullif(request_summary->>'recipient_count','')::int,0)) filter(where provider_key='pcm' and status not in('failed','canceled','cancelled')),0) pieces,coalesce(sum(coalesce(vendor_cost_cents,0)) filter(where provider_key='pcm' and status not in('failed','canceled','cancelled')),0) vendor_cost_cents,max(submitted_at) filter(where provider_key='pcm' and status not in('failed','canceled','cancelled')) last_order_at,mode() within group(order by product_type) filter(where provider_key='pcm' and product_type is not null) favorite_format from public.marketing_provider_jobs group by user_id),credit as(select user_id,sum(grant_cents) grant_cents,sum(used_cents) used_cents,max(expires_at) expires_at from public.marketing_credit_accounts group by user_id),base as(select m.*,coalesce(c.campaigns,0) campaigns,c.last_campaign_at,coalesce(ps.paid_payments,0) paid_payments,coalesce(ps.cash_spend_cents,0) cash_spend_cents,ps.last_paid_at,coalesce(js.orders,0) orders,coalesce(js.pieces,0) pieces,coalesce(js.vendor_cost_cents,0) vendor_cost_cents,js.last_order_at,js.favorite_format,coalesce(cr.grant_cents,0) credit_granted_cents,coalesce(cr.used_cents,0) credit_used_cents,greatest(coalesce(cr.grant_cents,0)-coalesce(cr.used_cents,0),0) credit_remaining_cents,cr.expires_at,case when greatest(coalesce(cr.grant_cents,0)-coalesce(cr.used_cents,0),0)>0 and cr.expires_at between now() and now()+interval '7 days' then 'credit_expiring' when coalesce(ps.cash_spend_cents,0)>=50000 then 'heavy_user' when coalesce(js.orders,0)>=2 then 'repeat_customer' when coalesce(js.orders,0)=1 then 'first_order' when coalesce(c.campaigns,0)>0 then 'started_not_ordered' else 'not_started' end segment from members m left join campaign_stats c on c.user_id=m.user_id left join pay_stats ps on ps.user_id=m.user_id left join job_stats js on js.user_id=m.user_id left join credit cr on cr.user_id=m.user_id),filtered as(select * from base where seg='all' or segment=seg)
 select jsonb_build_object('total',(select count(*) from filtered),'segment',seg,'customers',coalesce((select jsonb_agg(to_jsonb(x) order by cash_spend_cents desc,campaigns desc,email) from(select * from filtered order by cash_spend_cents desc,campaigns desc,email limit lim offset off)x),'[]'::jsonb)) into out;return out;
end $function$;

create or replace function public.marketing_direct_mail_admin_orders(p_limit integer default 100,p_offset integer default 0) returns jsonb language plpgsql security definer set search_path='public' as $function$
declare uid uuid:=auth.uid();lim int:=greatest(1,least(coalesce(p_limit,100),500));off int:=greatest(0,coalesce(p_offset,0));out jsonb;
begin
 if uid is null or not public.is_watchdog_developer() then raise exception 'Developer access required'; end if;
 select jsonb_build_object('total',(select count(*) from public.marketing_provider_jobs where provider_key='pcm'),'orders',coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc),'[]'::jsonb)) into out from(select j.id,j.user_id,p.email,p.full_name,c.name campaign_name,j.campaign_id,j.status,j.mode,j.provider_job_id,coalesce(j.product_type,q.pricing_detail->>'product_type') product_type,coalesce(j.size_label,q.pricing_detail->>'size_label') size_label,coalesce(j.mail_class,q.pricing_detail->>'mail_class') mail_class,coalesce(j.recipient_count,nullif(j.request_summary->>'recipient_count','')::int,q.quantity,0) recipient_count,coalesce(j.retail_cents,q.retail_cents,0) retail_cents,coalesce(j.credit_cents,0) credit_cents,coalesce(j.vendor_cost_cents,q.vendor_cost_cents,0) vendor_cost_cents,coalesce(j.gross_margin_cents,coalesce(j.retail_cents,q.retail_cents,0)-coalesce(j.vendor_cost_cents,q.vendor_cost_cents,0)) gross_margin_cents,j.submitted_at,j.completed_at,j.created_at,j.response_summary from public.marketing_provider_jobs j left join public.profiles p on p.id=j.user_id left join public.marketing_campaigns c on c.id=j.campaign_id left join public.marketing_price_quotes q on q.id=j.quote_id where j.provider_key='pcm' order by j.created_at desc limit lim offset off)x;return coalesce(out,jsonb_build_object('total',0,'orders','[]'::jsonb));
end $function$;

revoke all on function public.marketing_direct_mail_product_quote(uuid,text,integer,text,text,text) from public,anon;
revoke all on function public.marketing_direct_mail_quote(uuid,integer,text,text,text) from public,anon;
revoke all on function public.marketing_direct_mail_product_options(text) from public,anon;
revoke all on function public.marketing_direct_mail_admin_summary(integer) from public,anon,authenticated;
revoke all on function public.marketing_direct_mail_admin_customers(integer,integer,text) from public,anon,authenticated;
revoke all on function public.marketing_direct_mail_admin_orders(integer,integer) from public,anon,authenticated;
grant execute on function public.marketing_direct_mail_product_quote(uuid,text,integer,text,text,text) to authenticated,service_role;
grant execute on function public.marketing_direct_mail_quote(uuid,integer,text,text,text) to authenticated,service_role;
grant execute on function public.marketing_direct_mail_product_options(text) to authenticated,service_role;
grant execute on function public.marketing_direct_mail_admin_summary(integer) to authenticated,service_role;
grant execute on function public.marketing_direct_mail_admin_customers(integer,integer,text) to authenticated,service_role;
grant execute on function public.marketing_direct_mail_admin_orders(integer,integer) to authenticated,service_role;
