create table if not exists public.transaction_provider_registry (
  id bigint generated by default as identity primary key,
  jurisdiction_type text not null check (jurisdiction_type in ('municipality','county')),
  jurisdiction_key text not null,
  jurisdiction_name text not null,
  county text,
  provider_key text not null,
  provider_label text not null,
  provider_url text,
  evidence_families text[] not null default '{}',
  access_mode text not null default 'discovered',
  adapter_status text not null default 'discovered',
  source_url text,
  metadata jsonb not null default '{}'::jsonb,
  last_verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (jurisdiction_type, jurisdiction_key, provider_key, provider_url)
);
create index if not exists transaction_provider_registry_jurisdiction_idx on public.transaction_provider_registry(jurisdiction_type, jurisdiction_key);
create index if not exists transaction_provider_registry_provider_idx on public.transaction_provider_registry(provider_key, adapter_status);
alter table public.transaction_provider_registry enable row level security;
revoke all on table public.transaction_provider_registry from anon, authenticated;
comment on table public.transaction_provider_registry is 'Service-only routing registry for municipal and county transaction evidence providers. Discovery never implies a completed search or clearance.';
