create table if not exists public.search_console_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  site_url text not null,
  snapshot_date date not null,
  range_start date not null,
  range_end date not null,
  dimension text not null check (dimension in ('summary','query','page')),
  dimension_key text not null,
  clicks double precision not null default 0,
  impressions double precision not null default 0,
  ctr double precision not null default 0,
  position double precision not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, site_url, snapshot_date, dimension, dimension_key)
);

create index if not exists search_console_snapshots_lookup_idx
  on public.search_console_snapshots (user_id, site_url, snapshot_date desc, dimension);

alter table public.search_console_snapshots enable row level security;
revoke all on public.search_console_snapshots from anon, authenticated;
grant all on public.search_console_snapshots to service_role;

create or replace view public.analytics_organic_search_conversion_daily
with (security_invoker = true)
as
with sessions as (
  select
    min(occurred_at)::date as day,
    session_id,
    coalesce(nullif(max(landing_path), ''), '/') as landing_path,
    lower(coalesce(nullif(max(referrer_host), ''), '')) as referrer_host,
    bool_or(event_name = 'page_view' and path in ('/property', '/property/')) as property_lookup_opened,
    bool_or(event_name = 'property_lookup_started') as property_lookup_started,
    bool_or(event_name in ('property_lookup_succeeded','marker_viewed','upgrade_cta_clicked','intelligence_action_started','export_started')) as meaningful_action
  from public.watchdog_product_events
  where audience_class in ('external_visitor','external_account')
  group by session_id
), organic as (
  select
    day,
    case
      when landing_path like '/towns/%' and landing_path ~ '\.html$' then 'town_report'
      when landing_path like '/towns/%' then 'county_or_town_directory'
      when landing_path in ('/property','/property/') then 'property_lookup'
      when landing_path = '/' then 'site_home'
      else 'other_public'
    end as landing_group,
    property_lookup_opened,
    property_lookup_started,
    meaningful_action
  from sessions
  where referrer_host = 'google.com'
     or referrer_host like '%.google.%'
     or referrer_host = 'bing.com'
     or referrer_host like '%.bing.com'
     or referrer_host in ('search.yahoo.com','duckduckgo.com','www.ecosia.org','search.brave.com')
)
select
  day,
  landing_group,
  count(*)::bigint as organic_sessions,
  count(*) filter (where property_lookup_opened)::bigint as property_lookup_opened_sessions,
  count(*) filter (where property_lookup_started)::bigint as property_lookup_started_sessions,
  count(*) filter (where meaningful_action)::bigint as meaningful_action_sessions
from organic
group by day, landing_group;

revoke all on public.analytics_organic_search_conversion_daily from anon, authenticated;
grant select on public.analytics_organic_search_conversion_daily to service_role;

comment on table public.search_console_snapshots is 'Developer-only Search Console aggregate snapshots used to measure SEO cohort movement. Query/page keys are never exposed to normal browser roles.';
comment on view public.analytics_organic_search_conversion_daily is 'Aggregate external organic-search session funnel. No address, PAMS PIN, user identity, or property-search text is retained by this view.';
