-- Apply a Watchdog opportunity segment to the current Marketing Studio campaign rather than creating a second campaign.
create or replace function public.marketing_audience_hub_apply_opportunity(p_campaign_id uuid,p_play_key text,p_town text default null,p_limit integer default 1000) returns jsonb language plpgsql security definer set search_path='public' as $$
declare uid uuid:=auth.uid(); town_filter text:=nullif(trim(coalesce(p_town,'')),''); play text:=lower(trim(coalesce(p_play_key,''))); yr int:=extract(year from current_date)::int; lim int:=least(greatest(coalesce(p_limit,1000),1),10000); threshold numeric; keys jsonb:='[]'::jsonb; cnt int:=0; labelv text; explanation text; result jsonb;
begin
 if uid is null or not public.can_use_data_workbench(uid) then raise exception 'Marketing Studio requires Agent or higher'; end if; if not exists(select 1 from public.marketing_campaigns where id=p_campaign_id and user_id=uid) then raise exception 'Campaign not found'; end if;
 case play when 'long_term_ownership' then labelv:='Long-Term Ownership Farm'; explanation:='Recorded sale 15+ years ago; property-data based and does not assert seller intent.'; when 'recent_purchase' then labelv:='Recent Buyer Welcome'; explanation:='Recorded purchase in the last two calendar years.'; when 'older_housing_stock' then labelv:='Older Housing Stock'; explanation:='Recorded construction year is 40+ years old.'; when 'high_tax_exposure' then labelv:='Upper-Quartile Property Tax'; explanation:='Recorded property tax is in the upper quartile for the selected geography; no savings or appeal result is implied.'; else raise exception 'Unsupported opportunity play'; end case;
 if play='high_tax_exposure' then select percentile_cont(0.75) within group(order by last_year_tax) into threshold from public.property_lookups where last_year_tax is not null and last_year_tax>0 and pams_pin is not null and address is not null and town is not null and zip is not null and (town_filter is null or upper(town)=upper(town_filter)); end if;
 with selected as (select pams_pin from public.property_lookups where pams_pin is not null and address is not null and town is not null and zip is not null and (town_filter is null or upper(town)=upper(town_filter)) and case play when 'long_term_ownership' then last_sale_year is not null and last_sale_year<=yr-15 when 'recent_purchase' then last_sale_year is not null and last_sale_year>=yr-2 when 'older_housing_stock' then year_built is not null and year_built<=yr-40 when 'high_tax_exposure' then last_year_tax is not null and threshold is not null and last_year_tax>=threshold else false end order by pams_pin limit lim) select coalesce(jsonb_agg(pams_pin),'[]'::jsonb),count(*)::int into keys,cnt from selected;
 if cnt<1 then raise exception 'No properties matched this opportunity in the selected geography'; end if;
 result:=public.marketing_audience_hub_apply_keys(p_campaign_id,keys,'watchdog_opportunity',play||coalesce(':'||town_filter,''),labelv||coalesce(' · '||town_filter,''),lim,jsonb_build_object('play_key',play,'town',town_filter,'explanation',explanation,'property_count',cnt,'data_scope','Watchdog cached property intelligence'));
 return result||jsonb_build_object('play_key',play,'town',town_filter,'explanation',explanation);
end $$;
revoke all on function public.marketing_audience_hub_apply_opportunity(uuid,text,text,integer) from public,anon; grant execute on function public.marketing_audience_hub_apply_opportunity(uuid,text,text,integer) to authenticated,service_role;