create table if not exists public.pcm_direct_mail_orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  organization_id uuid null references public.organizations(id) on delete set null,
  campaign_id uuid null references public.data_workbench_campaigns(id) on delete set null,
  provider text not null default 'pcm' check (provider = 'pcm'),
  provider_order_id text null,
  provider_batch_id text null,
  external_reference text not null,
  status text not null default 'draft' check (status in ('draft','ready','submitting','submitted','pending','processing','mailed','completed','failed','canceled')),
  design_id text null,
  mail_class text not null default 'Standard' check (mail_class in ('Standard','FirstClass')),
  mail_size text null,
  recipient_count integer not null default 0 check (recipient_count >= 0),
  validated_recipient_count integer not null default 0 check (validated_recipient_count >= 0),
  failed_recipient_count integer not null default 0 check (failed_recipient_count >= 0),
  recipient_snapshot jsonb not null default '[]'::jsonb,
  request_key text not null,
  request_fingerprint text not null,
  provider_summary jsonb not null default '{}'::jsonb,
  estimated_cost numeric(12,2) null check (estimated_cost is null or estimated_cost >= 0),
  final_cost numeric(12,2) null check (final_cost is null or final_cost >= 0),
  currency text not null default 'USD',
  scheduled_for timestamptz null,
  submitted_at timestamptz null,
  completed_at timestamptz null,
  last_error text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, request_key)
);

create unique index if not exists pcm_direct_mail_orders_provider_order_uidx
  on public.pcm_direct_mail_orders(provider, provider_order_id)
  where provider_order_id is not null;
create index if not exists pcm_direct_mail_orders_user_created_idx
  on public.pcm_direct_mail_orders(user_id, created_at desc);
create index if not exists pcm_direct_mail_orders_campaign_idx
  on public.pcm_direct_mail_orders(campaign_id);

comment on table public.pcm_direct_mail_orders is 'Server-owned PCM DirectMail order ledger. Recipient snapshots contain mailing addresses only; demographic/owner profiling fields are prohibited.';
comment on column public.pcm_direct_mail_orders.recipient_snapshot is 'Private mailing-address snapshot used for provider submission/retry. Do not store owner demographics or sensitive profiling fields.';

create table if not exists public.pcm_direct_mail_events (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.pcm_direct_mail_orders(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  provider_status text null,
  message text null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists pcm_direct_mail_events_order_created_idx
  on public.pcm_direct_mail_events(order_id, created_at desc);
create index if not exists pcm_direct_mail_events_user_created_idx
  on public.pcm_direct_mail_events(user_id, created_at desc);

comment on table public.pcm_direct_mail_events is 'Service-written audit timeline for PCM DirectMail actions and sanitized provider state.';

alter table public.pcm_direct_mail_orders enable row level security;
alter table public.pcm_direct_mail_events enable row level security;

revoke all on public.pcm_direct_mail_orders from anon, authenticated;
revoke all on public.pcm_direct_mail_events from anon, authenticated;
revoke all on sequence public.pcm_direct_mail_events_id_seq from anon, authenticated;

drop policy if exists "pcm orders owner read" on public.pcm_direct_mail_orders;
create policy "pcm orders owner read" on public.pcm_direct_mail_orders
for select to authenticated
using (
  public.can_use_data_workbench(auth.uid())
  and (
    user_id = auth.uid()
    or (
      organization_id is not null
      and exists (
        select 1 from public.organization_members m
        where m.organization_id = pcm_direct_mail_orders.organization_id
          and m.user_id = auth.uid()
          and m.status = 'active'
      )
    )
  )
);

drop policy if exists "pcm events owner read" on public.pcm_direct_mail_events;
create policy "pcm events owner read" on public.pcm_direct_mail_events
for select to authenticated
using (
  exists (
    select 1 from public.pcm_direct_mail_orders o
    where o.id = pcm_direct_mail_events.order_id
      and public.can_use_data_workbench(auth.uid())
      and (
        o.user_id = auth.uid()
        or (
          o.organization_id is not null
          and exists (
            select 1 from public.organization_members m
            where m.organization_id = o.organization_id
              and m.user_id = auth.uid()
              and m.status = 'active'
          )
        )
      )
  )
);
