-- Canonical Direct Mail 3.0 source-sync guard. Previous migrations create the objects; this migration reasserts indexes, RLS and API grants so a fresh environment matches production.
alter table public.marketing_credit_accounts enable row level security;
alter table public.marketing_credit_ledger enable row level security;
alter table public.marketing_credit_reservations enable row level security;
create index if not exists marketing_credit_ledger_user_created_idx on public.marketing_credit_ledger(user_id,created_at desc);
create index if not exists marketing_credit_ledger_campaign_idx on public.marketing_credit_ledger(campaign_id) where campaign_id is not null;
create index if not exists marketing_credit_reservations_active_idx on public.marketing_credit_reservations(user_id,status,expires_at);
revoke all on function public.marketing_credit_reserve(uuid,uuid,uuid,bigint) from public,anon,authenticated;
revoke all on function public.marketing_credit_bind_session(uuid,text) from public,anon,authenticated;
revoke all on function public.marketing_credit_finalize(uuid,text,jsonb) from public,anon,authenticated;
grant execute on function public.marketing_credit_reserve(uuid,uuid,uuid,bigint) to service_role;
grant execute on function public.marketing_credit_bind_session(uuid,text) to service_role;
grant execute on function public.marketing_credit_finalize(uuid,text,jsonb) to service_role;
revoke all on function public.marketing_credit_summary() from public,anon;
revoke all on function public.marketing_credit_quote_adjustment(uuid) from public,anon;
grant execute on function public.marketing_credit_summary() to authenticated,service_role;
grant execute on function public.marketing_credit_quote_adjustment(uuid) to authenticated,service_role;
revoke all on function public.marketing_pcm_design_state(uuid) from public,anon;
revoke all on function public.marketing_save_pcm_design_variables(uuid,text,jsonb) from public,anon;
grant execute on function public.marketing_pcm_design_state(uuid) to authenticated,service_role;
grant execute on function public.marketing_save_pcm_design_variables(uuid,text,jsonb) to authenticated,service_role;
revoke all on function public.marketing_audience_hub_apply_keys(uuid,jsonb,text,text,text,integer,jsonb) from public,anon;
revoke all on function public.marketing_audience_hub_apply_source(uuid,text,text,integer) from public,anon;
revoke all on function public.marketing_audience_hub_create_farm(uuid,text,text,text,jsonb) from public,anon;
revoke all on function public.marketing_audience_hub_apply_opportunity(uuid,text,text,integer) from public,anon;
grant execute on function public.marketing_audience_hub_apply_keys(uuid,jsonb,text,text,text,integer,jsonb) to authenticated,service_role;
grant execute on function public.marketing_audience_hub_apply_source(uuid,text,text,integer) to authenticated,service_role;
grant execute on function public.marketing_audience_hub_create_farm(uuid,text,text,text,jsonb) to authenticated,service_role;
grant execute on function public.marketing_audience_hub_apply_opportunity(uuid,text,text,integer) to authenticated,service_role;