-- Downstream professional markers unlocked by cohort v1 and existing governed evidence.
insert into public.derived_formula_registry(marker_id,engine_version,formula,dependencies,confidence,status,explanation,operation,config,updated_at) values
('watchdog.agent.listing_tax_talking_point','watchdog-cohort-v1','source_alias(watchdog.listing_tax_burden_percentile)',array['watchdog.listing_tax_burden_percentile']::text[],'medium','live','V1 listing talking point is the parcel effective-tax-rate peer percentile. It is relative public-record tax context, not projected savings or tax advice.','source_alias',jsonb_build_object('dep','watchdog.listing_tax_burden_percentile'),now()),
('watchdog.title.map_notice_overlap','watchdog-cohort-v1','source_alias(watchdog.attorney.public_notice_density)',array['watchdog.attorney.public_notice_density']::text[],'medium','live','Title-facing map notice overlap reuses the existing governed count of mapped/public notice types; it is not a title defect or encumbrance determination.','source_alias',jsonb_build_object('dep','watchdog.attorney.public_notice_density'),now()),
('watchdog.lender.tax_shock_explanation_quality','watchdog-cohort-v1','60% transaction tax shock + 40% source authority coverage',array['watchdog.transaction_tax_shock_index','watchdog.source_authority_coverage']::text[],'medium','live','Measures whether a property-side tax-shock discussion has both a governed shock signal and strong public-source support. It is not borrower underwriting.','weighted_scores',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('dep','watchdog.transaction_tax_shock_index','weight',60,'transform','identity'),jsonb_build_object('dep','watchdog.source_authority_coverage','weight',40,'transform','identity')),'require_all',true),now()),
('watchdog.consumer.sale_context_strength','watchdog-cohort-v1','40% peer sale coverage + 30% peer sale recency + 30% inverse peer sale dispersion',array['cohort.sale_sample_coverage_score','cohort.sale_recency_score','cohort.sale_price_dispersion_score']::text[],'medium','live','Cohort-aware public sale context using observed peer record coverage, five-year recency and inverse relative IQR dispersion; not a valuation opinion.','weighted_scores',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('dep','cohort.sale_sample_coverage_score','weight',40,'transform','identity'),jsonb_build_object('dep','cohort.sale_recency_score','weight',30,'transform','identity'),jsonb_build_object('dep','cohort.sale_price_dispersion_score','weight',30,'transform','inverse')),'require_all',true),now()),
('watchdog.comparable_depth_score','watchdog-cohort-v1','45% peer sale coverage + 25% peer sale recency + 30% inverse peer sale dispersion',array['cohort.sale_sample_coverage_score','cohort.sale_recency_score','cohort.sale_price_dispersion_score']::text[],'medium','live','Cohort-aware depth of observed public sale evidence; not comparable selection or appraisal methodology.','weighted_scores',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('dep','cohort.sale_sample_coverage_score','weight',45,'transform','identity'),jsonb_build_object('dep','cohort.sale_recency_score','weight',25,'transform','identity'),jsonb_build_object('dep','cohort.sale_price_dispersion_score','weight',30,'transform','inverse')),'require_all',true),now()),
('watchdog.market_anchor_confidence','watchdog-cohort-v1','50% comparable depth + 30% source authority + 20% inverse peer sale dispersion',array['watchdog.comparable_depth_score','watchdog.source_authority_coverage','cohort.sale_price_dispersion_score']::text[],'medium','live','Confidence that public evidence can support a first-pass market anchor. This is not an appraisal or value opinion.','weighted_scores',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('dep','watchdog.comparable_depth_score','weight',50,'transform','identity'),jsonb_build_object('dep','watchdog.source_authority_coverage','weight',30,'transform','identity'),jsonb_build_object('dep','cohort.sale_price_dispersion_score','weight',20,'transform','inverse')),'require_all',true),now())
on conflict(marker_id) do update set engine_version=excluded.engine_version,formula=excluded.formula,dependencies=excluded.dependencies,confidence=excluded.confidence,status=excluded.status,explanation=excluded.explanation,operation=excluded.operation,config=excluded.config,updated_at=now();

insert into public.data_center_provider_coverage(marker_id,scopes,provider_key,value_status,source_keys,last_verified_at,notes,provider_kind,source_fields,calculation_key,freshness_seconds,cache_policy,bulk_capable) values
('watchdog.agent.listing_tax_talking_point',array['property']::text[],'watchdog-cohort-v1','live',array['watchdog.listing_tax_burden_percentile']::text[],now(),'Peer tax-burden position for sourced listing discussion.','derived_cohort',array['watchdog.listing_tax_burden_percentile']::text[],'watchdog-cohort-v1',86400,'refresh_on_demand',true),
('watchdog.title.map_notice_overlap',array['property']::text[],'watchdog-derived','live',array['watchdog.attorney.public_notice_density']::text[],now(),'Exact title-facing alias of governed public notice density.','derived_governed',array['watchdog.attorney.public_notice_density']::text[],'watchdog-cohort-v1',21600,'refresh_on_demand',true),
('watchdog.lender.tax_shock_explanation_quality',array['property']::text[],'watchdog-derived','live',array['watchdog.transaction_tax_shock_index','watchdog.source_authority_coverage']::text[],now(),'Property-side tax-shock explanation quality; not underwriting.','derived_governed',array['watchdog.transaction_tax_shock_index','watchdog.source_authority_coverage']::text[],'watchdog-cohort-v1',21600,'refresh_on_demand',true),
('watchdog.consumer.sale_context_strength',array['property']::text[],'watchdog-cohort-v1','live',array['property_lookups']::text[],now(),'Cohort-aware sale context from coverage, recency and dispersion.','derived_cohort',array['cohort.sale_sample_coverage_score','cohort.sale_recency_score','cohort.sale_price_dispersion_score']::text[],'watchdog-cohort-v1',86400,'refresh_on_demand',true),
('watchdog.comparable_depth_score',array['property']::text[],'watchdog-cohort-v1','live',array['property_lookups']::text[],now(),'Cohort-aware public sale evidence depth.','derived_cohort',array['cohort.sale_sample_coverage_score','cohort.sale_recency_score','cohort.sale_price_dispersion_score']::text[],'watchdog-cohort-v1',86400,'refresh_on_demand',true),
('watchdog.market_anchor_confidence',array['property']::text[],'watchdog-cohort-v1','live',array['property_lookups','watchdog.source_authority_coverage']::text[],now(),'Cohort-aware first-pass public market-anchor confidence.','derived_cohort',array['watchdog.comparable_depth_score','watchdog.source_authority_coverage','cohort.sale_price_dispersion_score']::text[],'watchdog-cohort-v1',86400,'refresh_on_demand',true)
on conflict(marker_id) do update set scopes=excluded.scopes,provider_key=excluded.provider_key,value_status=excluded.value_status,source_keys=excluded.source_keys,last_verified_at=excluded.last_verified_at,notes=excluded.notes,provider_kind=excluded.provider_kind,source_fields=excluded.source_fields,calculation_key=excluded.calculation_key,freshness_seconds=excluded.freshness_seconds,cache_policy=excluded.cache_policy,bulk_capable=excluded.bulk_capable;
