insert into public.data_center_provider_coverage
(marker_id, scopes, provider_key, value_status, source_keys, last_verified_at, notes, provider_kind, source_fields, calculation_key, freshness_seconds, cache_policy, bulk_capable)
values
('njplus.nj-dca-community-assets.transit_station_access', array['property'], 'dca-community-assets-spatial', 'live', array['nj-dca-community-assets'], now(), '1 statute mile (1609.344 m) straight-line proximity screen from the canonical NJ parcel centroid against the current NJ DCA Community Asset Map 2.0 Passenger Rail Stations layer. Boolean false is a valid source-checked result; missing coordinates/provider failures remain explicit missing/error states. Bulk remains uncertified.', 'authoritative_spatial_reference', array['lat','lon','NJ_Passenger_Rail_Stations/FeatureServer/0'], 'spatial-preflight-v11-dca-community-access', 21600, 'refresh_on_demand', false),
('njplus.nj-dca-community-assets.bus_terminal_access', array['property'], 'dca-community-assets-spatial', 'live', array['nj-dca-community-assets'], now(), '1 statute mile (1609.344 m) straight-line proximity screen from the canonical NJ parcel centroid against the current NJ DCA Community Asset Map 2.0 Bus Terminals layer. Boolean false is a valid source-checked result; missing coordinates/provider failures remain explicit missing/error states. Bulk remains uncertified.', 'authoritative_spatial_reference', array['lat','lon','Bus_Terminals_2021/FeatureServer/9'], 'spatial-preflight-v11-dca-community-access', 21600, 'refresh_on_demand', false),
('njplus.nj-dca-community-assets.hospital_access', array['property'], 'dca-community-assets-spatial', 'live', array['nj-dca-community-assets'], now(), '1 statute mile (1609.344 m) straight-line proximity screen from the canonical NJ parcel centroid against the current NJ DCA Community Asset Map 2.0 Hospitals layer. Boolean false is a valid source-checked result; missing coordinates/provider failures remain explicit missing/error states. Bulk remains uncertified.', 'authoritative_spatial_reference', array['lat','lon','Hospitals/FeatureServer/1'], 'spatial-preflight-v11-dca-community-access', 21600, 'refresh_on_demand', false),
('njplus.nj-dca-community-assets.college_access', array['property'], 'dca-community-assets-spatial', 'live', array['nj-dca-community-assets'], now(), '1 statute mile (1609.344 m) straight-line proximity screen from the canonical NJ parcel centroid against the current NJ DCA Community Asset Map 2.0 Colleges And Universities layer. Boolean false is a valid source-checked result; missing coordinates/provider failures remain explicit missing/error states. Bulk remains uncertified.', 'authoritative_spatial_reference', array['lat','lon','Colleges_And_Universities/FeatureServer/2'], 'spatial-preflight-v11-dca-community-access', 21600, 'refresh_on_demand', false),
('njplus.nj-dca-community-assets.park_access', array['property'], 'dca-community-assets-spatial', 'live', array['nj-dca-community-assets'], now(), '1 statute mile (1609.344 m) straight-line proximity screen from the canonical NJ parcel centroid against NJ DCA Community Asset Map 2.0 Open Space, restricted to PRIMARY_USE=23 (Park) and ACCESS_TYPE=Public Access. Boolean false is a valid source-checked result; missing coordinates/provider failures remain explicit missing/error states. Bulk remains uncertified.', 'authoritative_spatial_reference', array['lat','lon','Open_Space/FeatureServer/66','PRIMARY_USE=23','ACCESS_TYPE=Public Access'], 'spatial-preflight-v11-dca-community-access', 21600, 'refresh_on_demand', false),
('njplus.nj-dca-community-assets.library_access', array['property'], 'dca-community-assets-spatial', 'live', array['nj-dca-community-assets'], now(), '1 statute mile (1609.344 m) straight-line proximity screen from the canonical NJ parcel centroid against the current NJ DCA Community Asset Map 2.0 Libraries layer. Boolean false is a valid source-checked result; missing coordinates/provider failures remain explicit missing/error states. Bulk remains uncertified.', 'authoritative_spatial_reference', array['lat','lon','Libraries_2023/FeatureServer/11'], 'spatial-preflight-v11-dca-community-access', 21600, 'refresh_on_demand', false)
on conflict (marker_id) do update set
  scopes=excluded.scopes,
  provider_key=excluded.provider_key,
  value_status=excluded.value_status,
  source_keys=excluded.source_keys,
  last_verified_at=excluded.last_verified_at,
  notes=excluded.notes,
  provider_kind=excluded.provider_kind,
  source_fields=excluded.source_fields,
  calculation_key=excluded.calculation_key,
  freshness_seconds=excluded.freshness_seconds,
  cache_policy=excluded.cache_policy,
  bulk_capable=excluded.bulk_capable;
