-- Turn on the Oct 7 municipal markers that passed production canary municipal_context_oct7_v1
-- (watchdog_test_auth_events id 78, 2026-10-07 14:27:41Z, 8 pins in 8 counties): every served value
-- matched the published data file, and every derived score matched an independent recomputation.
-- pilot_rolloff_watch is left off: its PILOT term input returned no value on any pin.
insert into public.data_center_provider_coverage
(marker_id, scopes, provider_key, value_status, source_keys, last_verified_at, notes, provider_kind, source_fields, calculation_key, freshness_seconds, cache_policy, bulk_capable)
values
('njplus.nj-dca-pilot-forecast.pilot_payment_schedule', array['municipality'], 'workbench-hydrate', 'live', array['nj-dca-pilot-forecast','NJ DCA PILOT Database and Viewer 2026'], now(), 'Yearly PILOT billing 2026-2035 from reported agreements, each held flat through its reported end date. Built from property/data/pilot-schedule.json. Canary event 78.', 'authoritative_reference', array['Raw Data from UFBs: PILOT Billing','Raw Data from UFBs: Agreement End Date'], 'pilot-schedule-v1', 86400, 'shared_property_cache', false),
('njplus.nj-dca-pilot-forecast.pilot_revenue_projection', array['municipality'], 'workbench-hydrate', 'live', array['nj-dca-pilot-forecast','NJ DCA PILOT Database and Viewer 2026'], now(), 'Sum of the 2026-2030 PILOT payment schedule. Canary event 78.', 'authoritative_reference', array['Raw Data from UFBs: PILOT Billing','Raw Data from UFBs: Agreement End Date'], 'pilot-schedule-v1', 86400, 'shared_property_cache', false),
('njplus.nj-dca-pilot-forecast.pilot_forecast_year', array['municipality'], 'workbench-hydrate', 'live', array['nj-dca-pilot-forecast','NJ DCA PILOT Database and Viewer 2026'], now(), 'Latest reported PILOT end year from 2026 on. Canary event 78.', 'authoritative_reference', array['Raw Data from UFBs: Agreement End Date'], 'pilot-schedule-v1', 86400, 'shared_property_cache', false),
('njplus.nj-dca-pilot-forecast.pilot_municipal_share', array['municipality'], 'workbench-hydrate', 'live', array['nj-dca-pilot-forecast','NJ DCA PILOT Database and Viewer 2026','nj-dca-user-friendly-budget'], now(), 'PILOT billing as a percent of the municipal budget. Canary event 78.', 'authoritative_reference', array['Summary By Town: PILOT Billing','UFB: municipal budget'], 'pilot-schedule-v1', 86400, 'shared_property_cache', false),
('watchdog.njplus.pilot_forecast_confidence', array['municipality'], 'workbench-hydrate', 'live', array['nj-dca-pilot-forecast','NJ DCA PILOT Database and Viewer 2026'], now(), 'Share of the town''s PILOT billing that has a reported end date. Canary event 78.', 'derived_governed', array['Raw Data from UFBs: PILOT Billing','Raw Data from UFBs: Agreement End Date'], 'pilot-schedule-v1', 86400, 'shared_property_cache', false),
('njplus.nj-dca-affordable-housing.hud_subsidized_units', array['municipality'], 'workbench-hydrate', 'live', array['HUD Picture of Subsidized Households'], now(), 'HUD project-based subsidized units by town from property/data/federal-housing-context-v041.json. Canary event 78.', 'authoritative_reference', array['HUD Picture of Subsidized Households: units'], 'federal-housing-context-v041', 86400, 'shared_property_cache', false),
('njplus.nj-dca-affordable-housing.low_income_cost_burden', array['municipality'], 'workbench-hydrate', 'live', array['HUD CHAS'], now(), 'HUD CHAS low-income households paying over 30% of income on housing. Canary event 78.', 'authoritative_reference', array['HUD CHAS: cost burden by income'], 'federal-housing-context-v041', 86400, 'shared_property_cache', false),
('njplus.nj-dca-neighborhood-trends.commute_mode_mix', array['municipality'], 'workbench-hydrate', 'live', array['U.S. Census Bureau ACS 5-year'], now(), 'ACS means of transportation to work by town. Canary event 78.', 'authoritative_reference', array['ACS: means of transportation to work'], 'federal-housing-context-v041', 86400, 'shared_property_cache', false),
('watchdog.njplus.development_incentive_profile', array['municipality'], 'workbench-derived', 'live', array['nj-dca-pilot-forecast','NJ DCA PILOT Database and Viewer 2026'], now(), 'Weighted score of PILOT agreement count, PILOT share of assessed value and PILOT share of the budget. Canary event 78.', 'derived_governed', array[]::text[], 'watchdog-derived-v24-njw294', 21600, 'refresh_on_demand', false),
('watchdog.njplus.rental_market_pressure', array['municipality'], 'workbench-derived', 'live', array['U.S. Census Bureau ACS 5-year','nj-dca-neighborhood-trends'], now(), 'Weighted score of low rental vacancy, renter cost burden and rent growth since 2000. Canary event 78.', 'derived_governed', array[]::text[], 'watchdog-derived-v24-njw294', 21600, 'refresh_on_demand', false),
('watchdog.njplus.housing_affordability_gap', array['municipality'], 'workbench-derived', 'live', array['nj-dca-municipal-housing-profile','nj-dca-neighborhood-trends'], now(), 'Weighted score of cost-burdened households and a year of median rent against median income. Canary event 78.', 'derived_governed', array[]::text[], 'watchdog-derived-v24-njw294', 21600, 'refresh_on_demand', false),
('watchdog.njplus.rent_support_context', array['municipality'], 'workbench-derived', 'live', array['HUD Picture of Subsidized Households','nj-dca-affordable-housing','U.S. Census Bureau ACS 5-year'], now(), 'HUD subsidized and DCA affordable rental units per 100 renter households. Canary event 78.', 'derived_governed', array[]::text[], 'watchdog-derived-v24-njw294', 21600, 'refresh_on_demand', false)
on conflict (marker_id) do update set scopes=excluded.scopes, provider_key=excluded.provider_key, value_status=excluded.value_status, source_keys=excluded.source_keys, last_verified_at=excluded.last_verified_at, notes=excluded.notes, provider_kind=excluded.provider_kind, source_fields=excluded.source_fields, calculation_key=excluded.calculation_key, freshness_seconds=excluded.freshness_seconds, cache_policy=excluded.cache_policy, bulk_capable=excluded.bulk_capable;
