-- Closing Review v7: granular direct transaction exceptions.
-- Built only from v6 structural behavior; no human labels are used here.

update public.intelligence_model_versions
set scoring_notes = coalesce(scoring_notes,'') || ' STRUCTURAL RESULT 2026-08-19: 48/48 fresh scorable across 21 counties, but only 4 distinct scores and 7 unique feature vectors; v6 failed structural diversity and is frozen for audit. No human labels were used.'
where model_key='closing_review' and version=6;

insert into public.derived_formula_registry
(marker_id,engine_version,formula,dependencies,confidence,status,explanation,operation,config,updated_at)
values
('watchdog.closing_permit_closure_gap_v7','closing-actionable-v7','100 - permit_closure_confidence',array['watchdog.permit_closure_confidence'],'high','live','Direct permit/certificate record-gap attention. Not a legal finding that a permit is open.','inverse',jsonb_build_object('dep','watchdog.permit_closure_confidence'),now()),
('watchdog.closing_permit_lifecycle_exception_v7','closing-actionable-v7','permit_closure_gap * permit_activity_score / 100',array['watchdog.closing_permit_closure_gap_v7','watchdog.permit_activity_score'],'high','live','Granular permit/certificate lifecycle exception severity: a closure gap must exist, then published permit activity scales the follow-up priority.','product_scores',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('dep','watchdog.closing_permit_closure_gap_v7'),jsonb_build_object('dep','watchdog.permit_activity_score'))),now()),
('watchdog.closing_recording_reference_gap_v7','closing-actionable-v7','100 - recording_reference_completeness',array['watchdog.title.recording_reference_completeness'],'high','live','Direct deed recording-reference gap in the statewide parcel baseline; requires county-record verification and is not a title opinion.','inverse',jsonb_build_object('dep','watchdog.title.recording_reference_completeness'),now()),
('watchdog.closing_recent_sale_attention_v7','closing-actionable-v7','inverse years_since_last_sale on a 0-100 attention scale',array['watchdog.years_since_last_sale'],'medium','live','Recency context used only to scale an existing recording-reference gap. It cannot independently create a Closing Priority.','weighted_scores',jsonb_build_object('require_all',true,'items',jsonb_build_array(jsonb_build_object('dep','watchdog.years_since_last_sale','weight',1,'transform','inverse_identity'))),now()),
('watchdog.closing_recording_gap_context_v7','closing-actionable-v7','75% recording-reference gap + 25% recent-sale attention',array['watchdog.closing_recording_reference_gap_v7','watchdog.closing_recent_sale_attention_v7'],'high','live','Context score for an already-present recording-reference gap. Recent-sale recency only scales the direct gap.','weighted_scores',jsonb_build_object('require_all',true,'items',jsonb_build_array(jsonb_build_object('dep','watchdog.closing_recording_reference_gap_v7','weight',0.75,'transform','identity'),jsonb_build_object('dep','watchdog.closing_recent_sale_attention_v7','weight',0.25,'transform','identity'))),now()),
('watchdog.closing_recording_exception_v7','closing-actionable-v7','recording_reference_gap * recording_gap_context / 100',array['watchdog.closing_recording_reference_gap_v7','watchdog.closing_recording_gap_context_v7'],'high','live','Granular recording exception. A recording-reference gap is mandatory; sale recency only changes severity.','product_scores',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('dep','watchdog.closing_recording_reference_gap_v7'),jsonb_build_object('dep','watchdog.closing_recording_gap_context_v7'))),now()),
('watchdog.closing_actionable_exception_attention_v7','closing-actionable-v7','max(permit lifecycle exception, recording exception)',array['watchdog.closing_permit_lifecycle_exception_v7','watchdog.closing_recording_exception_v7'],'high','live','Strongest direct actionable Closing Review exception. Environmental, flood, wetlands, tidelands, proximity and municipal trend context cannot independently raise this marker.','max_scores',jsonb_build_object('require_all',true,'items',jsonb_build_array(jsonb_build_object('dep','watchdog.closing_permit_lifecycle_exception_v7','transform','identity'),jsonb_build_object('dep','watchdog.closing_recording_exception_v7','transform','identity'))),now()),
('watchdog.closing_actionable_evidence_coverage_v7','closing-actionable-v7','present(permit lifecycle exception, recording exception) / 2 * 100',array['watchdog.closing_permit_lifecycle_exception_v7','watchdog.closing_recording_exception_v7'],'high','live','Coverage of the two primary v7 direct exception families. Evidence coverage is not prediction confidence.','completeness','{}'::jsonb,now())
on conflict (marker_id) do update set engine_version=excluded.engine_version,formula=excluded.formula,dependencies=excluded.dependencies,confidence=excluded.confidence,status=excluded.status,explanation=excluded.explanation,operation=excluded.operation,config=excluded.config,updated_at=excluded.updated_at;

insert into public.intelligence_feature_versions
(feature_key,version,source_key,label,transform_type,config,direction,status,explanation)
values
('watchdog.closing_actionable_exception_attention_v7',1,'watchdog.closing_actionable_exception_attention_v7','Actionable closing exception','identity_0_100','{}'::jsonb,'higher_attention','draft','Maximum direct exception severity across permit/certificate lifecycle and recording-reference follow-up.'),
('watchdog.closing_permit_lifecycle_exception_v7',1,'watchdog.closing_permit_lifecycle_exception_v7','Permit/certificate lifecycle exception','identity_0_100','{}'::jsonb,'higher_attention','draft','Published DCA permit/certificate record-gap severity scaled by parcel permit activity.'),
('watchdog.closing_recording_exception_v7',1,'watchdog.closing_recording_exception_v7','Recording-reference exception','identity_0_100','{}'::jsonb,'higher_attention','draft','Missing/incomplete recording references, with sale recency used only as a severity modifier after a gap exists.'),
('watchdog.closing_permit_closure_gap_v7',1,'watchdog.closing_permit_closure_gap_v7','Permit closure gap','identity_0_100','{}'::jsonb,'higher_attention','draft','Direct permit/certificate record-gap component.'),
('watchdog.closing_recording_reference_gap_v7',1,'watchdog.closing_recording_reference_gap_v7','Recording reference gap','identity_0_100','{}'::jsonb,'higher_attention','draft','Direct missing-recording-reference component.'),
('watchdog.closing_actionable_evidence_coverage_v7',1,'watchdog.closing_actionable_evidence_coverage_v7','Actionable evidence coverage','identity_0_100','{}'::jsonb,'higher_attention','draft','Coverage of permit lifecycle and recording exception families; not model confidence.')
on conflict (feature_key,version) do update set source_key=excluded.source_key,label=excluded.label,transform_type=excluded.transform_type,config=excluded.config,direction=excluded.direction,status=excluded.status,explanation=excluded.explanation;

insert into public.intelligence_model_versions
(model_key,version,label,description,objective,minimum_plan,status,profession_scope,signal_config,calibration_state,scoring_notes)
values
('closing_review',7,'Closing Review v7 · Granular Actionable Exceptions','Draft exception-trigger redesign with granular permit/certificate and recording-reference severity.','Surface concrete parcel-specific transaction follow-ups while keeping generalized property risk context out of the primary score.','pro_plus','draft',array['attorney','title','agent','lender'],
jsonb_build_object('input_contract','closing_granular_actionable_exception_v7','requires_evidence',true,'minimum_evidence_coverage',100,'aggregation','max_direct_exception','signals',jsonb_build_array(
jsonb_build_object('id','watchdog.closing_actionable_exception_attention_v7','role','score','weight',1.0),
jsonb_build_object('id','watchdog.closing_permit_lifecycle_exception_v7','role','support'),
jsonb_build_object('id','watchdog.closing_recording_exception_v7','role','support'),
jsonb_build_object('id','watchdog.closing_permit_closure_gap_v7','role','support'),
jsonb_build_object('id','watchdog.closing_recording_reference_gap_v7','role','support'),
jsonb_build_object('id','watchdog.closing_actionable_evidence_coverage_v7','role','confidence')),
'supporting_context_policy',jsonb_build_object('environmental_flood_tidelands','context_only','may_independently_create_priority',false),
'holdout_policy',jsonb_build_object('development_sanity_review_first',true,'development_sanity_cases',10,'fresh_independent_labels_required',true,'reuse_v5_labels_as_promotion_proof',false,'reuse_v6_shadow_as_promotion_proof',false,'structural_diversity_gate_required',true,'minimum_positive_cases',5,'minimum_negative_cases',5,'minimum_unique_feature_vectors',8)),
'uncalibrated','DRAFT v7. Created from v6 structural collapse only; no human labels used. Must pass unseen statewide structural diversity before any development sanity queue is created.')
on conflict (model_key,version) do update set label=excluded.label,description=excluded.description,objective=excluded.objective,minimum_plan=excluded.minimum_plan,status=excluded.status,profession_scope=excluded.profession_scope,signal_config=excluded.signal_config,calibration_state=excluded.calibration_state,scoring_notes=excluded.scoring_notes;
