-- Data Center batch, Oct 7 2026: formulas for 27 planned markers that the deployed workbench-derived
-- engine can already compute from live inputs. Rows are staged live in the formula registry so the canary
-- can call them; data_center_provider_coverage stays planned until the canary passes and an activation
-- migration cites it.

insert into public.derived_formula_registry(marker_id,engine_version,formula,dependencies,confidence,status,explanation,operation,config,updated_at) values
('watchdog.environmental_site_proximity','watchdog-derived-dc-batch-2026-10-07','35% known contaminated sites within 500 m (10+ = full) + 25% storage-tank sites within 250 m (10+ = full) + 20% deed notice on the parcel + 20% groundwater CEA on the parcel',array['preflight.contaminated_site_500m','preflight.ust_250m','preflight.deed_notice_hit','preflight.cea_hit']::text[],'high','live','Screening priority for environmental site review from NJDEP public records. Higher means more mapped records near or on the parcel. It is not a finding that the property is contaminated.','weighted_scores','{"items": [{"dep": "preflight.contaminated_site_500m", "weight": 35, "transform": "count10"}, {"dep": "preflight.ust_250m", "weight": 25, "transform": "count10"}, {"dep": "preflight.deed_notice_hit", "weight": 20, "transform": "bool"}, {"dep": "preflight.cea_hit", "weight": 20, "transform": "bool"}], "require_all": true}'::jsonb,now()),
('watchdog.water_protection_overlap','watchdog-derived-dc-batch-2026-10-07','55% inside a community wellhead protection area (any tier) + 45% Category One water within 500 m',array['water.wellhead_community_tier','water.category1_water_within_500m']::text[],'medium','live','Overlap of drinking-water protection mapping at the parcel. Sole-source aquifer and source-water areas are left out because NJDEP returns them as area names, not yes/no flags. Outside a wellhead area counts as no overlap.','weighted_signals','{"signals": [{"dep": "water.wellhead_community_tier", "weight": 55, "transform": "bool"}, {"dep": "water.category1_water_within_500m", "weight": 45, "transform": "count1"}]}'::jsonb,now()),
('watchdog.historic_property_constraint','watchdog-derived-dc-batch-2026-10-07','45% mapped historic property + 35% mapped historic district + 20% archaeological site-grid screen, at the parcel point',array['land.historic_property_hit','land.historic_district_hit','land.archaeological_grid_hit']::text[],'high','live','Flags NJ Historic Preservation Office mapping that may affect diligence. Eligibility letters (LOI) are not in the public layer, so they are not counted. Not a determination of historic status.','weighted_signals','{"signals": [{"dep": "land.historic_property_hit", "weight": 45, "transform": "bool"}, {"dep": "land.historic_district_hit", "weight": 35, "transform": "bool"}, {"dep": "land.archaeological_grid_hit", "weight": 20, "transform": "bool"}]}'::jsonb,now()),
('watchdog.njplus.construction_scope_signal','watchdog-derived-dc-batch-2026-10-07','50% DCA authorized construction cost on the parcel ($500,000+ = full) + 50% authorized square feet (5,000+ = full)',array['njplus.nj-dca-permits-raw.authorized_construction_cost','njplus.nj-dca-permits-raw.authorized_square_feet']::text[],'medium','live','Size of recorded permit scope on the parcel from NJ DCA construction permits. Permit-type mix is shown in its own marker and not scored here.','weighted_scores','{"items": [{"dep": "njplus.nj-dca-permits-raw.authorized_construction_cost", "weight": 50, "transform": "count500000"}, {"dep": "njplus.nj-dca-permits-raw.authorized_square_feet", "weight": 50, "transform": "count5000"}], "require_all": true}'::jsonb,now()),
('watchdog.njplus.certificate_gap_priority','watchdog-derived-dc-batch-2026-10-07','open-permit attention (3+ unmatched permits = 100) x latest permit-record age attention (10+ years = 100) / 100',array['watchdog.closing_open_permit_attention_v5','watchdog.permit_record_age_attention']::text[],'medium','live','Follow-up priority for permits with no matching certificate in the DCA data. Zero when there is no gap. Uses the age of the latest permit record because DCA rows do not give a reliable oldest-open date. A gap is not a violation.','product_scores','{"items": [{"dep": "watchdog.closing_open_permit_attention_v5"}, {"dep": "watchdog.permit_record_age_attention"}]}'::jsonb,now()),
('watchdog.njplus.commercial_buildout_signal','watchdog-derived-dc-batch-2026-10-07','35% new office sq ft (200,000+ = full) + 25% new retail sq ft (100,000+ = full) + 40% total nonresidential sq ft (500,000+ = full), latest DCA year',array['njplus.nj-dca-development-trends.latest_annual_office_new_construction_square_feet','njplus.nj-dca-development-trends.latest_annual_retail_new_construction_square_feet','njplus.nj-dca-development-trends.latest_annual_total_nonresidential_square_feet']::text[],'high','live','Town-level commercial construction screen from the NJ DCA Development Trends Viewer, latest published year (2024).','weighted_scores','{"items": [{"dep": "njplus.nj-dca-development-trends.latest_annual_office_new_construction_square_feet", "weight": 35, "transform": "count200000"}, {"dep": "njplus.nj-dca-development-trends.latest_annual_retail_new_construction_square_feet", "weight": 25, "transform": "count100000"}, {"dep": "njplus.nj-dca-development-trends.latest_annual_total_nonresidential_square_feet", "weight": 40, "transform": "count500000"}], "require_all": true}'::jsonb,now()),
('watchdog.njplus.demolition_redevelopment_watch','watchdog-derived-dc-batch-2026-10-07','40% demolitions (50+ = full) + 30% new housing units authorized (500+ = full) + 30% construction cost authorized ($250M+ = full), latest DCA year',array['njplus.nj-dca-development-trends.latest_annual_demolitions','njplus.nj-dca-development-trends.latest_annual_new_housing_units_authorized','njplus.nj-dca-development-trends.latest_annual_construction_cost_authorized']::text[],'high','live','Town-level sign that demolition and new building are both active, from the NJ DCA Development Trends Viewer (2024). Context for a redevelopment review, not a forecast.','weighted_scores','{"items": [{"dep": "njplus.nj-dca-development-trends.latest_annual_demolitions", "weight": 40, "transform": "count50"}, {"dep": "njplus.nj-dca-development-trends.latest_annual_new_housing_units_authorized", "weight": 30, "transform": "count500"}, {"dep": "njplus.nj-dca-development-trends.latest_annual_construction_cost_authorized", "weight": 30, "transform": "count250000000"}], "require_all": true}'::jsonb,now()),
('watchdog.njplus.amenity_access_profile','watchdog-derived-dc-batch-2026-10-07','share of 6 mapped amenity types within 1 mile of the parcel: train station, bus terminal, hospital, college, public park, library',array['njplus.nj-dca-community-assets.transit_station_access','njplus.nj-dca-community-assets.bus_terminal_access','njplus.nj-dca-community-assets.hospital_access','njplus.nj-dca-community-assets.college_access','njplus.nj-dca-community-assets.park_access','njplus.nj-dca-community-assets.library_access']::text[],'high','live','Share of state-mapped community amenity types within a straight-line mile. Says nothing about neighborhood quality.','signal_density','{"require_all": true}'::jsonb,now()),
('watchdog.njplus.public_facility_proximity_signal','watchdog-derived-dc-batch-2026-10-07','share of 3 public facility types within 1 mile: hospital, library, public park',array['njplus.nj-dca-community-assets.hospital_access','njplus.nj-dca-community-assets.library_access','njplus.nj-dca-community-assets.park_access']::text[],'high','live','Share of hospital, library and public park types mapped within a straight-line mile of the parcel.','signal_density','{"require_all": true}'::jsonb,now()),
('watchdog.njplus.site_marketing_context','watchdog-derived-dc-batch-2026-10-07','60% amenity access profile + 40% development designations (opportunity zone, UEZ, transit village, redevelopment area; 4 = full)',array['watchdog.njplus.amenity_access_profile','watchdog.njplus.development_designation_stack']::text[],'medium','live','Sourced location context for an agent or investor brief. Not a valuation.','weighted_scores','{"items": [{"dep": "watchdog.njplus.amenity_access_profile", "weight": 60, "transform": "identity"}, {"dep": "watchdog.njplus.development_designation_stack", "weight": 40, "transform": "count4"}], "require_all": true}'::jsonb,now()),
('watchdog.njplus.new_build_price_pressure','watchdog-derived-dc-batch-2026-10-07','county new-home average price change, latest quarter (0 when flat or falling, +20% or more = 100)',array['njplus.nj-dca-new-home-warranty.new_home_warranty_price_change']::text[],'medium','live','Upward price movement in NJ DCA new home warranty data for the county. Not a price forecast.','weighted_scores','{"items": [{"dep": "njplus.nj-dca-new-home-warranty.new_home_warranty_price_change", "weight": 100, "transform": "count20"}], "require_all": true}'::jsonb,now()),
('watchdog.njplus.new_build_delivery_momentum','watchdog-derived-dc-batch-2026-10-07','county new-home warranty enrollment change, latest quarter (0 when flat or falling, +50% or more = 100)',array['njplus.nj-dca-new-home-warranty.new_home_warranty_enrollment_change']::text[],'medium','live','Growth in new homes enrolled for warranty in the county. DCA reports enrollments and sales as the same count, so one input is used.','weighted_scores','{"items": [{"dep": "njplus.nj-dca-new-home-warranty.new_home_warranty_enrollment_change", "weight": 100, "transform": "count50"}], "require_all": true}'::jsonb,now()),
('watchdog.njplus.new_build_market_depth','watchdog-derived-dc-batch-2026-10-07','county new homes in the latest quarter (500+ = 100)',array['njplus.nj-dca-new-home-warranty.new_home_warranty_sales_count']::text[],'high','live','How many reported new-home transactions the county had in the latest NJ DCA quarter.','weighted_scores','{"items": [{"dep": "njplus.nj-dca-new-home-warranty.new_home_warranty_sales_count", "weight": 100, "transform": "count500"}], "require_all": true}'::jsonb,now()),
('watchdog.njplus.local_demand_context','watchdog-derived-dc-batch-2026-10-07','35% population change since 2000 (+25% or more = full) + 35% jobs per square mile (5,000+ = full) + 30% median household income ($200,000+ = full)',array['njplus.nj-dca-neighborhood-trends.population_change','njplus.nj-dca-neighborhood-trends.employment_density','njplus.nj-dca-neighborhood-trends.household_income']::text[],'medium','live','Public area trends from NJ DCA Neighborhood Trends. Income is the current median, not a trend. Never profiles individuals or protected classes.','weighted_scores','{"items": [{"dep": "njplus.nj-dca-neighborhood-trends.population_change", "weight": 35, "transform": "count25"}, {"dep": "njplus.nj-dca-neighborhood-trends.employment_density", "weight": 35, "transform": "count5000"}, {"dep": "njplus.nj-dca-neighborhood-trends.household_income", "weight": 30, "transform": "count200000"}], "require_all": true}'::jsonb,now()),
('watchdog.njplus.household_cost_context','watchdog-derived-dc-batch-2026-10-07','40% town median annual property tax ($20,000+ = full) + 30% rent change since 2000 (+100% or more = full) + 30% home value change since 2000 (+150% or more = full)',array['njplus.nj-dca-neighborhood-trends.real_estate_tax_median','njplus.nj-dca-neighborhood-trends.rental_cost_change','njplus.nj-dca-neighborhood-trends.home_value_change']::text[],'medium','live','Broad town cost context. Not affordability advice.','weighted_scores','{"items": [{"dep": "njplus.nj-dca-neighborhood-trends.real_estate_tax_median", "weight": 40, "transform": "count20000"}, {"dep": "njplus.nj-dca-neighborhood-trends.rental_cost_change", "weight": 30, "transform": "count100"}, {"dep": "njplus.nj-dca-neighborhood-trends.home_value_change", "weight": 30, "transform": "count150"}], "require_all": true}'::jsonb,now()),
('watchdog.njplus.housing_supply_balance','watchdog-derived-dc-batch-2026-10-07','40% housing unit growth since 2000 (+50% or more = full) + 30% vacancy rate (15%+ = full) + 30% inverse household growth since 2000',array['njplus.nj-dca-neighborhood-trends.housing_unit_change','njplus.nj-dca-municipal-housing-profile.vacancy_rate','njplus.nj-dca-municipal-housing-profile.household_growth']::text[],'medium','live','Higher means more housing supply relative to household demand. Not a rent or home-value forecast.','weighted_scores','{"items": [{"dep": "njplus.nj-dca-neighborhood-trends.housing_unit_change", "weight": 40, "transform": "count50"}, {"dep": "njplus.nj-dca-municipal-housing-profile.vacancy_rate", "weight": 30, "transform": "count15"}, {"dep": "njplus.nj-dca-municipal-housing-profile.household_growth", "weight": 30, "transform": "inverse_identity"}], "require_all": true}'::jsonb,now()),
('watchdog.njplus.assessment_history_reliability','watchdog-derived-dc-batch-2026-10-07','60% MOD-IV assessment years on file (6 = full) + 40% parcel identity confidence',array['njplus.nj-dca-modiv-longitudinal.assessment_history_depth','watchdog.parcel_identity_confidence']::text[],'high','live','Strength of the public assessment history behind this parcel. Source freshness is already shown in its own marker.','weighted_scores','{"items": [{"dep": "njplus.nj-dca-modiv-longitudinal.assessment_history_depth", "weight": 60, "transform": "count6"}, {"dep": "watchdog.parcel_identity_confidence", "weight": 40, "transform": "identity"}], "require_all": true}'::jsonb,now()),
('watchdog.tax_trajectory','watchdog-derived-dc-batch-2026-10-07','100 - tax trend position',array['watchdog.tax_trend_position']::text[],'high','live','How fast the town general tax rate has been rising. 0 when flat or falling, 100 at 5% a year or more. The mirror of tax trend position.','inverse','{"dep": "watchdog.tax_trend_position"}'::jsonb,now()),
('watchdog.collateral_operating_cost_stress','watchdog-derived-dc-batch-2026-10-07','40% tax as a share of assessment (4%+ = full) + 30% town levy growth (5%+ a year = full) + 30% carry-cost volatility',array['watchdog.effective_tax_rate','budget.total_levy_cagr','watchdog.investor_carry_cost_volatility']::text[],'medium','live','When recurring public charges may change monthly housing cost. Uses carry-cost volatility in place of escrow history.','weighted_scores','{"items": [{"dep": "watchdog.effective_tax_rate", "weight": 40, "transform": "count4"}, {"dep": "budget.total_levy_cagr", "weight": 30, "transform": "positive_pct5"}, {"dep": "watchdog.investor_carry_cost_volatility", "weight": 30, "transform": "identity"}], "require_all": true}'::jsonb,now()),
('watchdog.fiscal_trend_momentum','watchdog-derived-dc-batch-2026-10-07','source_alias(watchdog.municipal_cost_absorption_score)',array['watchdog.municipal_cost_absorption_score']::text[],'high','live','Uses the municipal cost absorption score: 70% whether the ratable base keeps pace with levy growth + 30% collection rate. Higher means healthier direction.','source_alias','{"dep": "watchdog.municipal_cost_absorption_score"}'::jsonb,now())
on conflict(marker_id) do update set engine_version=excluded.engine_version,formula=excluded.formula,dependencies=excluded.dependencies,confidence=excluded.confidence,status=excluded.status,explanation=excluded.explanation,operation=excluded.operation,config=excluded.config,updated_at=now();

-- Seven older score ids that repeat a live score keep their ids and read the live value or the same
-- town inputs. Added/omitted assessment risk waits for the added/omitted history pull.
insert into public.derived_formula_registry(marker_id,engine_version,formula,dependencies,confidence,status,explanation,operation,config,updated_at) values
('watchdog.fairness_score','watchdog-derived-dc-batch-2026-10-07','source_alias(watchdog.assessment_defensibility_score)',array['watchdog.assessment_defensibility_score']::text[],'medium','live','Uses the assessment defensibility score: comparable sale evidence, town assessment uniformity and whether the assessment sits inside the Chapter 123 range. Higher means the assessment looks fairer.','source_alias','{"dep": "watchdog.assessment_defensibility_score"}'::jsonb,now()),
('watchdog.reassessment_risk','watchdog-derived-dc-batch-2026-10-07','source_alias(watchdog.revaluation_risk)',array['watchdog.revaluation_risk']::text[],'high','live','Same value as revaluation risk: published ratio level, verified sales-ratio decay and assessment uniformity for the town.','source_alias','{"dep": "watchdog.revaluation_risk"}'::jsonb,now()),
('watchdog.appeal_odds','watchdog-derived-dc-batch-2026-10-07','source_alias(appeals.latest_win_rate_filed)',array['appeals.latest_win_rate_filed']::text[],'high','live','Share of county tax appeals filed in the latest year that won a reduction, from NJ Tax Court and county board outcomes. A county base rate, not a prediction for this property.','source_alias','{"dep": "appeals.latest_win_rate_filed"}'::jsonb,now()),
('watchdog.tax_carry_advantage','watchdog-derived-dc-batch-2026-10-07','source_alias(watchdog.investor.hold_cost_stability)',array['watchdog.investor.hold_cost_stability']::text[],'medium','live','Uses hold-cost stability: 70% inverse carry-cost volatility + 30% town revenue-base resilience. Higher means steadier tax carry.','source_alias','{"dep": "watchdog.investor.hold_cost_stability"}'::jsonb,now()),
('watchdog.permit_lifecycle_score','watchdog-derived-dc-batch-2026-10-07','source_alias(watchdog.permit_closure_confidence)',array['watchdog.permit_closure_confidence']::text[],'high','live','Uses permit closure confidence: the share of DCA permits on the parcel that have a matching certificate.','source_alias','{"dep": "watchdog.permit_closure_confidence"}'::jsonb,now()),
('watchdog.abatement_exposure','watchdog-derived-dc-batch-2026-10-07','town abated share of value (35% or more = 100)',array['abatement.abated_share']::text[],'high','live','How much of the town tax base is under tax abatement, from NJ Division of Taxation abstract of ratables. Town level.','weighted_scores','{"items": [{"dep": "abatement.abated_share", "weight": 100, "transform": "share35"}], "require_all": true}'::jsonb,now()),
('watchdog.exempt_pilot_exposure','watchdog-derived-dc-batch-2026-10-07','50% town exempt share of value + 50% town PILOT share of value (35% or more = full)',array['exemption.exempt_share','exemption.pilot_value_share']::text[],'high','live','How much of the town tax base is exempt or paying PILOTs instead of taxes. Town level.','weighted_scores','{"items": [{"dep": "exemption.exempt_share", "weight": 50, "transform": "share35"}, {"dep": "exemption.pilot_value_share", "weight": 50, "transform": "share35"}], "require_all": true}'::jsonb,now())
on conflict(marker_id) do update set engine_version=excluded.engine_version,formula=excluded.formula,dependencies=excluded.dependencies,confidence=excluded.confidence,status=excluded.status,explanation=excluded.explanation,operation=excluded.operation,config=excluded.config,updated_at=now();

-- Allow the new batch canary, the municipal context canary (municipal_context_oct7_v1), and catalog_njdep_layers_v2 (written for the 5 NJDEP layer markers that
-- returned no value in v1), to be dispatched once provider-release-canary v046 is deployed.
create or replace function public.dispatch_provider_release_canary(p_scenario text)
returns bigint language plpgsql set search_path to 'public','extensions' as $$
declare v_raw text := encode(gen_random_bytes(48), 'hex'); v_email text := 'watchdog-provider-canary-' || substr(v_raw,1,10) || '@example.com'; v_request_id bigint;
begin
 if p_scenario not in ('zoning_v31','designation_stack_v15','csrr_v1','csrr_controls_v2','csrr_semantics_v3','geology_intersections_v1','model_bounds_v1','uniformity_history_v1','uniformity_history_v2','uniformity_history_v3','modiv_longitudinal_v1','modiv_longitudinal_partial_scan_v1','modiv_longitudinal_missing_year_v1','community_assets_access_v1','zoning_contact_status_v1','pilot_observed_v1','v036_sources_v1','modiv_record_change_v1','affordable_housing_v037','development_trends_v038','ufb_v039','ufb_longitudinal_v040','njw294_deterministic_v1','catalog_njdep_layers_v1','catalog_njdep_layers_v2','data_center_batch_oct7_v1','municipal_context_oct7_v1') then raise exception 'Unsupported release canary scenario'; end if;
 insert into public.watchdog_test_bootstrap_tokens(token_hash,desired_email,redirect_to,expires_at,metadata) values (encode(digest(v_raw,'sha256'),'hex'),v_email,'https://njpropertytaxrelief.com/property/dashboard',now()+interval '10 minutes',jsonb_build_object('purpose','provider_release_canary','scenario',p_scenario,'no_real_spend',true));
 select net.http_post(url := 'https://uvkvaxljhhngydvlrzom.supabase.co/functions/v1/provider-release-canary',headers := jsonb_build_object('Content-Type','application/json'),body := jsonb_build_object('token',v_raw,'scenario',p_scenario),timeout_milliseconds := 30000) into v_request_id; return v_request_id;
end; $$;
revoke all on function public.dispatch_provider_release_canary(text) from public, anon, authenticated;
grant execute on function public.dispatch_provider_release_canary(text) to service_role;
