alter table public.derived_formula_registry drop constraint if exists derived_formula_registry_operation_check;
alter table public.derived_formula_registry add constraint derived_formula_registry_operation_check check (operation is null or operation = any(array['year_delta','ratio','completeness','inverse','permit_closure','permit_activity','weighted_signals','signal_count','signal_density','weighted_scores','max_scores','product_scores','tax_rate_position','municipal_cost_absorption','fiscal_resilience','revaluation_pressure','transaction_tax_shock','investor_carry_volatility','tax_reset_sensitivity','marketability_drag','sr1a_subject_square_feet','comparable_evidence_reliability','assessment_defensibility','appeal_evidence_strength','appeal_opportunity','source_alias','chapter123_field','ordered_history','history_metric']));

insert into public.derived_formula_registry(marker_id,engine_version,formula,dependencies,confidence,status,explanation,operation,config,updated_at) values
('watchdog.history.watchdog_score_delta','watchdog-history-v1','Latest Watchdog score minus earliest Watchdog score in the governed observation window','{}','high','live','Exact observed Watchdog Score change. Requires at least two trusted score observations; no history means dependency_missing.','history_metric','{"source_marker":"watchdog.score","field":"score_delta"}'::jsonb,now()),
('watchdog.history.watchdog_score_volatility','watchdog-history-v1','Population standard deviation of Watchdog Score across the governed observation window','{}','high','live','Observed Watchdog Score variability in score points. Requires at least two trusted observations.','history_metric','{"source_marker":"watchdog.score","field":"score_stddev"}'::jsonb,now()),
('watchdog.history.watchdog_score_trend_30d','watchdog-history-v1','Observed Watchdog Score delta normalized to a 30-day span','{}','medium','live','Direction/rate of observed Watchdog Score movement normalized to 30 days. It is not a forecast.','history_metric','{"source_marker":"watchdog.score","field":"trend_points_per_30d"}'::jsonb,now()),
('watchdog.history.tax_pressure_delta','watchdog-history-v1','Latest tax-pressure score minus earliest tax-pressure score in the governed observation window','{}','high','live','Exact observed change in Watchdog tax-pressure score.','history_metric','{"source_marker":"watchdog.tax_pressure","field":"score_delta"}'::jsonb,now()),
('watchdog.history.tax_pressure_volatility','watchdog-history-v1','Population standard deviation of tax-pressure score across the governed observation window','{}','high','live','Observed variability in the Watchdog tax-pressure score.','history_metric','{"source_marker":"watchdog.tax_pressure","field":"score_stddev"}'::jsonb,now()),
('watchdog.history.tax_pressure_trend_30d','watchdog-history-v1','Observed tax-pressure delta normalized to a 30-day span','{}','medium','live','Direction/rate of observed tax-pressure movement normalized to 30 days. It is not a tax forecast.','history_metric','{"source_marker":"watchdog.tax_pressure","field":"trend_points_per_30d"}'::jsonb,now()),
('watchdog.history.revaluation_risk_delta','watchdog-history-v1','Latest revaluation-risk score minus earliest revaluation-risk score in the governed observation window','{}','high','live','Exact observed change in governed revaluation-risk score.','history_metric','{"source_marker":"watchdog.revaluation_risk","field":"score_delta"}'::jsonb,now()),
('watchdog.history.uniformity_delta','watchdog-history-v1','Latest uniformity score minus earliest uniformity score in the governed observation window','{}','high','live','Exact observed change in governed assessment-uniformity score.','history_metric','{"source_marker":"uniformity.score","field":"score_delta"}'::jsonb,now()),
('watchdog.history.observation_count','watchdog-history-v1','Count of trusted Watchdog Score observations in the governed history window','{}','high','live','Number of trusted Watchdog Score observations supporting the longitudinal metrics. Minimum is two.','history_metric','{"source_marker":"watchdog.score","field":"observation_count"}'::jsonb,now()),
('watchdog.history.observation_span_days','watchdog-history-v1','Elapsed days between earliest and latest trusted Watchdog Score observations','{}','high','live','Observed calendar span supporting Watchdog Score longitudinal metrics.','history_metric','{"source_marker":"watchdog.score","field":"observed_span_days"}'::jsonb,now())
on conflict (marker_id) do update set engine_version=excluded.engine_version,formula=excluded.formula,dependencies=excluded.dependencies,confidence=excluded.confidence,status=excluded.status,explanation=excluded.explanation,operation=excluded.operation,config=excluded.config,updated_at=now();

insert into public.data_center_provider_coverage(marker_id,scopes,provider_key,value_status,source_keys,last_verified_at,notes,provider_kind,source_fields,calculation_key,freshness_seconds,cache_policy,bulk_capable)
select v.marker_id,array['property']::text[],'watchdog-history-v1','live',array['score_observations']::text[],now(),v.notes,'derived_governed',v.fields,'watchdog-history-v1',86400,'refresh_on_demand',true
from (values
('watchdog.history.watchdog_score_delta',array['watchdog.score','score_delta']::text[],'Observed Watchdog Score change; requires >=2 trusted observations.'),
('watchdog.history.watchdog_score_volatility',array['watchdog.score','score_stddev']::text[],'Observed Watchdog Score population standard deviation; requires >=2 trusted observations.'),
('watchdog.history.watchdog_score_trend_30d',array['watchdog.score','trend_points_per_30d']::text[],'Observed Watchdog Score movement normalized to 30 days; not a forecast.'),
('watchdog.history.tax_pressure_delta',array['watchdog.tax_pressure','score_delta']::text[],'Observed tax-pressure change; requires >=2 trusted observations.'),
('watchdog.history.tax_pressure_volatility',array['watchdog.tax_pressure','score_stddev']::text[],'Observed tax-pressure population standard deviation; requires >=2 trusted observations.'),
('watchdog.history.tax_pressure_trend_30d',array['watchdog.tax_pressure','trend_points_per_30d']::text[],'Observed tax-pressure movement normalized to 30 days; not a forecast.'),
('watchdog.history.revaluation_risk_delta',array['watchdog.revaluation_risk','score_delta']::text[],'Observed revaluation-risk score change.'),
('watchdog.history.uniformity_delta',array['uniformity.score','score_delta']::text[],'Observed assessment-uniformity score change.'),
('watchdog.history.observation_count',array['watchdog.score','observation_count']::text[],'Trusted observation count supporting longitudinal Watchdog Score metrics.'),
('watchdog.history.observation_span_days',array['watchdog.score','observed_span_days']::text[],'Elapsed days covered by trusted Watchdog Score observations.')
) as v(marker_id,fields,notes)
on conflict (marker_id) do update set scopes=excluded.scopes,provider_key=excluded.provider_key,value_status='live',source_keys=excluded.source_keys,last_verified_at=excluded.last_verified_at,notes=excluded.notes,provider_kind=excluded.provider_kind,source_fields=excluded.source_fields,calculation_key=excluded.calculation_key,freshness_seconds=excluded.freshness_seconds,cache_policy=excluded.cache_policy,bulk_capable=excluded.bulk_capable;