-- NJW-294: admit two deterministic operations and stage three formulas for production canary.
alter table public.derived_formula_registry drop constraint if exists derived_formula_registry_operation_check;
alter table public.derived_formula_registry add constraint derived_formula_registry_operation_check check (operation is null or operation = any (array['year_delta','ratio','completeness','inverse','permit_closure','permit_activity','weighted_signals','signal_count','signal_density','weighted_scores','max_scores','product_scores','tax_rate_position','municipal_cost_absorption','fiscal_resilience','revaluation_pressure','transaction_tax_shock','investor_carry_volatility','tax_reset_sensitivity','marketability_drag','sr1a_subject_square_feet','comparable_evidence_reliability','assessment_defensibility','appeal_evidence_strength','appeal_opportunity','source_alias','chapter123_field','ordered_history','history_metric','chapter123_position','assessment_component_shift','parcel_record_volatility','source_release_freshness']::text[]));

insert into public.derived_formula_registry(marker_id,engine_version,formula,dependencies,confidence,status,explanation,operation,config,updated_at) values
('watchdog.njplus.parcel_record_volatility','watchdog-derived-v23-njw294','parcel_record_change_count / actual consecutive observed property-class transitions * 100; gaps skipped',array['njplus.nj-dca-modiv-longitudinal.parcel_record_change_count','njplus.nj-dca-modiv-longitudinal.property_class_history']::text[],'high','live','Percent of actual consecutive annual MOD-IV transitions with any retained record-field change. Missing years are skipped; no years are synthesized; not a property-condition finding.','parcel_record_volatility',jsonb_build_object('change_dep','njplus.nj-dca-modiv-longitudinal.parcel_record_change_count','history_dep','njplus.nj-dca-modiv-longitudinal.property_class_history'),now()),
('watchdog.njplus.housing_program_record_freshness','watchdog-derived-v23-njw294','100 - elapsed whole days since governed DCA workbook release / declared annual cadence * 100, clamped 0-100',array['njplus.nj-dca-affordable-housing.affordable_housing_reporting_status']::text[],'high','live','Source-record freshness against the governed NJ DCA Affordable Housing workbook release and declared annual cadence. Reporting-status evidence is required. This is provider/source currency, not a claim that an underlying housing fact has or has not changed.','source_release_freshness',jsonb_build_object('gate_dep','njplus.nj-dca-affordable-housing.affordable_housing_reporting_status','release_date','2026-07-01','cadence_days',365),now()),
('watchdog.njplus.pilot_revenue_concentration','watchdog-derived-v23-njw294','aggregate DCA PILOT assessed value / max(DCA UFB 3-year average property valuation,1) * 100',array['njplus.nj-dca-pilot-forecast.pilot_project_assessment','njplus.nj-dca-ufb-2025.net_debt_three_year_avg_property_valuation']::text[],'high','live','Legacy marker ID retained for compatibility. The calculated value is an assessed-value concentration proxy using two observed DCA facts; it is not PILOT revenue, revenue share, or a forecast.','ratio',jsonb_build_object('num','njplus.nj-dca-pilot-forecast.pilot_project_assessment','den','njplus.nj-dca-ufb-2025.net_debt_three_year_avg_property_valuation','den_min',1,'scale',100,'precision',4),now())
on conflict(marker_id) do update set engine_version=excluded.engine_version,formula=excluded.formula,dependencies=excluded.dependencies,confidence=excluded.confidence,status=excluded.status,explanation=excluded.explanation,operation=excluded.operation,config=excluded.config,updated_at=now();

create or replace function public.dispatch_provider_release_canary(p_scenario text)
returns bigint language plpgsql set search_path to 'public','extensions' as $$
declare v_raw text := encode(gen_random_bytes(48), 'hex'); v_email text := 'watchdog-provider-canary-' || substr(v_raw,1,10) || '@example.com'; v_request_id bigint;
begin
 if p_scenario not in ('zoning_v31','designation_stack_v15','csrr_v1','csrr_controls_v2','csrr_semantics_v3','geology_intersections_v1','model_bounds_v1','uniformity_history_v1','uniformity_history_v2','uniformity_history_v3','modiv_longitudinal_v1','modiv_longitudinal_partial_scan_v1','modiv_longitudinal_missing_year_v1','community_assets_access_v1','zoning_contact_status_v1','pilot_observed_v1','v036_sources_v1','modiv_record_change_v1','affordable_housing_v037','development_trends_v038','ufb_v039','ufb_longitudinal_v040','njw294_deterministic_v1') then raise exception 'Unsupported release canary scenario'; end if;
 insert into public.watchdog_test_bootstrap_tokens(token_hash,desired_email,redirect_to,expires_at,metadata) values (encode(digest(v_raw,'sha256'),'hex'),v_email,'https://njpropertytaxrelief.com/property/dashboard',now()+interval '10 minutes',jsonb_build_object('purpose','provider_release_canary','scenario',p_scenario,'no_real_spend',true));
 select net.http_post(url := 'https://uvkvaxljhhngydvlrzom.supabase.co/functions/v1/provider-release-canary',headers := jsonb_build_object('Content-Type','application/json'),body := jsonb_build_object('token',v_raw,'scenario',p_scenario),timeout_milliseconds := 30000) into v_request_id; return v_request_id;
end; $$;
