-- Promote canonical core submodels now supportable from governed live signals.
-- These reduce downstream legacy placeholders without inventing unsupported data.

insert into public.derived_formula_registry
(marker_id,engine_version,formula,dependencies,confidence,status,explanation,operation,config,updated_at)
values
('watchdog.carry_cost_downside','watchdog-derived-v21-core-submodels','source_alias(watchdog.investor_carry_cost_volatility)',array['watchdog.investor_carry_cost_volatility']::text[],'medium','live','V1 Carry Cost Downside reuses governed Investor Carry-Cost Volatility because both represent adverse recurring public tax/fiscal cost momentum. Private operating costs, insurance and financing remain outside this signal.','source_alias',jsonb_build_object('dep','watchdog.investor_carry_cost_volatility'),now()),
('watchdog.municipal_fiscal_capacity','watchdog-derived-v21-core-submodels','source_alias(watchdog.fiscal_resilience_score)',array['watchdog.fiscal_resilience_score']::text[],'medium','live','V1 Municipal Fiscal Capacity reuses governed Fiscal Resilience, which already combines budget pressure, cost absorption, collection performance and debt-service burden. It is public-finance context, not a credit rating.','source_alias',jsonb_build_object('dep','watchdog.fiscal_resilience_score'),now()),
('watchdog.environmental_collateral_review','watchdog-derived-v21-core-submodels','50% environmental encumbrance severity + 50% water protection context',array['watchdog.environmental_encumbrance_severity','watchdog.insurance.water_protection_context']::text[],'medium','live','Implements the defined environmental-collateral review as an equal-weight combination of governed environmental encumbrance and water-protection mapping context. It is a review-priority screen, not environmental due diligence or lending advice.','weighted_scores',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('dep','watchdog.environmental_encumbrance_severity','weight',50,'transform','identity'),jsonb_build_object('dep','watchdog.insurance.water_protection_context','weight',50,'transform','identity')),'require_all',true),now()),
('watchdog.flood_context_severity','watchdog-derived-v21-core-submodels','source_alias(watchdog.flood_environment_risk_score)',array['watchdog.flood_environment_risk_score']::text[],'high','live','Flood Context Severity reuses the governed flood/environment mapping score as the canonical public flood-context screen. It is not a flood-insurance or engineering determination.','source_alias',jsonb_build_object('dep','watchdog.flood_environment_risk_score'),now()),
('watchdog.regulatory_overlap_score','watchdog-derived-v21-core-submodels','source_alias(watchdog.regulatory_constraint_density)',array['watchdog.regulatory_constraint_density']::text[],'medium','live','V1 Regulatory Overlap Score reuses governed Regulatory Constraint Density until a separately weighted regulatory-program model is approved. It represents density of monitored mapped programs, not legal applicability.','source_alias',jsonb_build_object('dep','watchdog.regulatory_constraint_density'),now()),
('watchdog.site_water_constraint_score','watchdog-derived-v21-core-submodels','source_alias(watchdog.contractor.water_review_priority)',array['watchdog.contractor.water_review_priority']::text[],'medium','live','V1 Site Water Constraint Score reuses the governed public water/flood review-priority signal. It does not determine wetlands jurisdiction, water availability, permitting or buildability.','source_alias',jsonb_build_object('dep','watchdog.contractor.water_review_priority'),now()),
('watchdog.geology_complexity_score','watchdog-derived-v21-core-submodels','source_alias(watchdog.contractor.ground_condition_attention)',array['watchdog.contractor.ground_condition_attention']::text[],'medium','live','V1 Geology Complexity Score reuses the governed public geology/ground-condition mapping context. It is not a geotechnical or engineering conclusion.','source_alias',jsonb_build_object('dep','watchdog.contractor.ground_condition_attention'),now()),
('watchdog.predevelopment_review_priority','watchdog-derived-v21-core-submodels','equal-weight development constraint density + regulatory overlap + water constraint + geology complexity',array['watchdog.development_constraint_density','watchdog.regulatory_overlap_score','watchdog.site_water_constraint_score','watchdog.geology_complexity_score']::text[],'medium','live','Implements the defined predevelopment review priority from four governed public site-screen families. All inputs are required; this ranks diligence only and is not an approval/buildability prediction.','weighted_scores',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('dep','watchdog.development_constraint_density','weight',25,'transform','identity'),jsonb_build_object('dep','watchdog.regulatory_overlap_score','weight',25,'transform','identity'),jsonb_build_object('dep','watchdog.site_water_constraint_score','weight',25,'transform','identity'),jsonb_build_object('dep','watchdog.geology_complexity_score','weight',25,'transform','identity')),'require_all',true),now()),
('watchdog.physical_due_diligence_priority','watchdog-derived-v21-core-submodels','equal-weight flood context + environmental collateral review + water protection + geology complexity',array['watchdog.flood_context_severity','watchdog.environmental_collateral_review','watchdog.insurance.water_protection_context','watchdog.geology_complexity_score']::text[],'medium','live','V1 Physical Due Diligence Priority combines four governed public physical/environmental review families. The legacy environmental-proximity submodel is represented by the governed environmental-collateral review rather than a fabricated distance value.','weighted_scores',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('dep','watchdog.flood_context_severity','weight',25,'transform','identity'),jsonb_build_object('dep','watchdog.environmental_collateral_review','weight',25,'transform','identity'),jsonb_build_object('dep','watchdog.insurance.water_protection_context','weight',25,'transform','identity'),jsonb_build_object('dep','watchdog.geology_complexity_score','weight',25,'transform','identity')),'require_all',true),now()),
('watchdog.market_anchor_confidence','watchdog-derived-v21-core-submodels','65% comparable evidence quality + 35% source authority coverage',array['watchdog.comparable_evidence_quality','watchdog.source_authority_coverage']::text[],'medium','live','V1 Market Anchor Confidence uses governed comparable-evidence quality, which already includes sample depth/dispersion/recency context, plus source-authority coverage. It is not a valuation conclusion.','weighted_scores',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('dep','watchdog.comparable_evidence_quality','weight',65,'transform','identity'),jsonb_build_object('dep','watchdog.source_authority_coverage','weight',35,'transform','identity')),'require_all',true),now()),
('watchdog.capital_improvement_activity','watchdog-derived-v21-core-submodels','source_alias(watchdog.permit_activity_score)',array['watchdog.permit_activity_score']::text[],'medium','live','V1 Capital Improvement Activity uses governed public permit activity as the activity proxy. It does not infer capital dollars, property condition, completion or return on investment.','source_alias',jsonb_build_object('dep','watchdog.permit_activity_score'),now()),
('watchdog.collateral_constraint_burden','watchdog-derived-v21-core-submodels','source_alias(watchdog.contractor.site_approval_complexity)',array['watchdog.contractor.site_approval_complexity']::text[],'medium','live','V1 Collateral Constraint Burden reuses the governed multi-family site approval complexity screen as the lender-facing mapped-constraint burden proxy. It is not underwriting or legal diligence.','source_alias',jsonb_build_object('dep','watchdog.contractor.site_approval_complexity'),now()),
('watchdog.town_fiscal_story_score','watchdog-derived-v21-core-submodels','40% collection resilience + 35% ratable growth quality + 25% levy alignment',array['watchdog.municipal.collection_resilience_context','watchdog.municipal.ratable_growth_quality','watchdog.municipal.levy_alignment_score']::text[],'medium','live','Town Fiscal Story Score condenses three governed municipal public-finance dimensions: collection performance/resilience, ratable-growth quality and levy/base alignment. It is not a forecast or credit opinion.','weighted_scores',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('dep','watchdog.municipal.collection_resilience_context','weight',40,'transform','identity'),jsonb_build_object('dep','watchdog.municipal.ratable_growth_quality','weight',35,'transform','identity'),jsonb_build_object('dep','watchdog.municipal.levy_alignment_score','weight',25,'transform','identity')),'require_all',true),now()),
('watchdog.comparable_depth_score','watchdog-derived-v21-core-submodels','source_alias(watchdog.comparable_evidence_reliability)',array['watchdog.comparable_evidence_reliability']::text[],'medium','live','V1 Comparable Depth Score reuses governed Comparable Evidence Reliability because that model already embeds verified-sale depth, dispersion and recency. Subject square-foot availability remains an additional evidence-quality component.','source_alias',jsonb_build_object('dep','watchdog.comparable_evidence_reliability'),now())
on conflict (marker_id) do update set engine_version=excluded.engine_version,formula=excluded.formula,dependencies=excluded.dependencies,confidence=excluded.confidence,status=excluded.status,explanation=excluded.explanation,operation=excluded.operation,config=excluded.config,updated_at=now();

insert into public.data_center_provider_coverage
(marker_id,scopes,provider_key,value_status,source_keys,last_verified_at,notes,provider_kind,source_fields,calculation_key,freshness_seconds,cache_policy,bulk_capable)
select r.marker_id,array['property']::text[],'watchdog-derived','live',r.dependencies,now(),r.explanation,'derived_governed',r.dependencies,'watchdog-derived-v21-core-submodels',21600,'refresh_on_demand',true
from public.derived_formula_registry r where r.engine_version='watchdog-derived-v21-core-submodels'
on conflict (marker_id) do update set scopes=excluded.scopes,provider_key=excluded.provider_key,value_status=excluded.value_status,source_keys=excluded.source_keys,last_verified_at=excluded.last_verified_at,notes=excluded.notes,provider_kind=excluded.provider_kind,source_fields=excluded.source_fields,calculation_key=excluded.calculation_key,freshness_seconds=excluded.freshness_seconds,cache_policy=excluded.cache_policy,bulk_capable=excluded.bulk_capable;
