-- Large professional-intelligence closure batch.
-- 26 catalog markers across all 10 professional categories.
-- Every formula reuses governed live signals/runtime transforms and fails closed where composite inputs are required.

insert into public.derived_formula_registry
  (marker_id, engine_version, formula, dependencies, confidence, status, explanation, operation, config, updated_at)
values
-- Consumer / homeowner
('watchdog.consumer.appeal_question_readiness','watchdog-derived-v20-big-closure','source_alias(watchdog.consumer.appeal_readiness)',array['watchdog.consumer.appeal_readiness']::text[],'medium','live','V1 public-evidence appeal-question readiness reuses the governed Consumer Appeal Readiness screen. The legacy deadline-readiness component remains excluded until a governed filing-calendar input exists; this is not legal advice or an appeal-success prediction.','source_alias',jsonb_build_object('dep','watchdog.consumer.appeal_readiness'),now()),
('watchdog.consumer.buyer_tax_planning_signal','watchdog-derived-v20-big-closure','50% transaction tax shock + 50% buyer tax-reset exposure',array['watchdog.transaction_tax_shock_index','watchdog.buyer_tax_reset_exposure']::text[],'medium','live','Buyer tax planning signal combines two governed public assessment-reset/tax-shock screens. It is a planning-attention signal, not a payment or future-tax forecast.','weighted_scores',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('dep','watchdog.transaction_tax_shock_index','weight',50,'transform','identity'),jsonb_build_object('dep','watchdog.buyer_tax_reset_exposure','weight',50,'transform','identity')),'require_all',true),now()),
('watchdog.consumer.sale_context_strength','watchdog-derived-v20-big-closure','source_alias(watchdog.comparable_evidence_quality)',array['watchdog.comparable_evidence_quality']::text[],'medium','live','V1 sale-context strength reuses governed Comparable Evidence Quality, which already measures verified public sale evidence and appraisal-record coverage. It is not a valuation opinion.','source_alias',jsonb_build_object('dep','watchdog.comparable_evidence_quality'),now()),
-- Attorney
('watchdog.attorney.record_exception_sequence','watchdog-derived-v20-big-closure','source_alias(watchdog.closing_exception_priority)',array['watchdog.closing_exception_priority']::text[],'medium','live','V1 record-exception sequencing reuses the governed Closing Exception Priority score as the ordering driver for public-record review. It does not state legal priority, title status, or legal sufficiency.','source_alias',jsonb_build_object('dep','watchdog.closing_exception_priority'),now()),
('watchdog.attorney.assessment_argument_specificity','watchdog-derived-v20-big-closure','source_alias(watchdog.tax_appeal_evidence_strength)',array['watchdog.tax_appeal_evidence_strength']::text[],'medium','live','V1 assessment-argument specificity uses the canonical governed tax-appeal evidence-strength signal to distinguish evidence-supported questions from general concern. It is not an argument, legal opinion, or success prediction.','source_alias',jsonb_build_object('dep','watchdog.tax_appeal_evidence_strength'),now()),
-- Title / closing
('watchdog.title.exception_resolution_priority','watchdog-derived-v20-big-closure','40% normalized title constraint stack + 30% permit activity + 30% environmental encumbrance',array['watchdog.title_constraint_stack','watchdog.permit_activity_score','watchdog.environmental_encumbrance_severity']::text[],'medium','live','V1 exception-resolution priority ranks governed public-record exception families for follow-up. Open-permit age remains excluded until governed event dates exist. This is not a title or marketability determination.','weighted_scores',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('dep','watchdog.title_constraint_stack','weight',40,'transform','count6'),jsonb_build_object('dep','watchdog.permit_activity_score','weight',30,'transform','identity'),jsonb_build_object('dep','watchdog.environmental_encumbrance_severity','weight',30,'transform','identity')),'require_all',true),now()),
('watchdog.title.address_alias_risk','watchdog-derived-v20-big-closure','source_alias(watchdog.title.parcel_match_variance)',array['watchdog.title.parcel_match_variance']::text[],'medium','live','V1 address-alias risk is deliberately narrowed to governed parcel-match variance until a statewide address-variant history exists. It flags identity reconciliation risk, not a defect in title.','source_alias',jsonb_build_object('dep','watchdog.title.parcel_match_variance'),now()),
-- Agent / broker
('watchdog.agent.buyer_cost_explanation','watchdog-derived-v20-big-closure','50% transaction tax shock + 50% home-cost clarity',array['watchdog.transaction_tax_shock_index','watchdog.consumer.home_cost_clarity']::text[],'medium','live','V1 buyer-cost explanation combines governed tax-shock context with completeness of core public home-cost facts. It does not estimate mortgage payment, insurance, utilities, or closing costs.','weighted_scores',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('dep','watchdog.transaction_tax_shock_index','weight',50,'transform','identity'),jsonb_build_object('dep','watchdog.consumer.home_cost_clarity','weight',50,'transform','identity')),'require_all',true),now()),
('watchdog.agent.buyer_diligence_sequence','watchdog-derived-v20-big-closure','45% offer diligence priority + 35% buyer objection radar + 20% permit activity',array['watchdog.offer_diligence_priority','watchdog.buyer_objection_radar','watchdog.permit_activity_score']::text[],'medium','live','V1 buyer-diligence sequence publishes the governed priority score that drives the order of public-record questions. It is not a transaction recommendation or defect finding.','weighted_scores',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('dep','watchdog.offer_diligence_priority','weight',45,'transform','identity'),jsonb_build_object('dep','watchdog.buyer_objection_radar','weight',35,'transform','identity'),jsonb_build_object('dep','watchdog.permit_activity_score','weight',20,'transform','identity')),'require_all',true),now()),
('watchdog.agent.market_context_confidence','watchdog-derived-v20-big-closure','60% comparable evidence quality + 40% client brief completeness',array['watchdog.comparable_evidence_quality','watchdog.agent.client_brief_completeness']::text[],'medium','live','V1 market-context confidence combines governed public-sale evidence quality with client-brief completeness. Parcel-specific comparable selection remains outside this score.','weighted_scores',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('dep','watchdog.comparable_evidence_quality','weight',60,'transform','identity'),jsonb_build_object('dep','watchdog.agent.client_brief_completeness','weight',40,'transform','identity')),'require_all',true),now()),
('watchdog.agent.transaction_cost_conversation','watchdog-derived-v20-big-closure','50% buyer tax-reset exposure + 50% home-cost clarity',array['watchdog.buyer_tax_reset_exposure','watchdog.consumer.home_cost_clarity']::text[],'medium','live','V1 transaction-cost conversation is limited to governed public tax/reset and core home-cost evidence. Closing-cost estimates and borrower-specific carrying costs remain excluded until verified scenario inputs exist.','weighted_scores',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('dep','watchdog.buyer_tax_reset_exposure','weight',50,'transform','identity'),jsonb_build_object('dep','watchdog.consumer.home_cost_clarity','weight',50,'transform','identity')),'require_all',true),now()),
-- Lender / mortgage
('watchdog.lender.payment_stability_signal','watchdog-derived-v20-big-closure','100 - investor carry-cost volatility',array['watchdog.investor_carry_cost_volatility']::text[],'medium','live','V1 public recurring-cost stability is the exact inverse of governed Investor Carry-Cost Volatility. Borrower debt, escrow, insurance premiums and loan terms are not included.','inverse',jsonb_build_object('dep','watchdog.investor_carry_cost_volatility'),now()),
('watchdog.lender.municipal_tax_capacity_watch','watchdog-derived-v20-big-closure','50% inverse fiscal resilience + 50% tax-base absorption risk',array['watchdog.fiscal_resilience_score','watchdog.tax_base_absorption_risk']::text[],'medium','live','Municipal Tax Capacity Watch combines low governed fiscal resilience with levy/base absorption pressure. It is municipal public-finance context only, not borrower credit or municipal credit analysis.','weighted_scores',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('dep','watchdog.fiscal_resilience_score','weight',50,'transform','inverse_identity'),jsonb_build_object('dep','watchdog.tax_base_absorption_risk','weight',50,'transform','identity')),'require_all',true),now()),
('watchdog.lender.insurance_cost_attention','watchdog-derived-v20-big-closure','50% flood/environment risk + 50% environmental encumbrance severity',array['watchdog.flood_environment_risk_score','watchdog.environmental_encumbrance_severity']::text[],'medium','live','V1 insurance-cost attention uses only mapped public physical/environmental risk context to flag when verified insurance inputs deserve attention. It does not estimate premium, insurability, or coverage.','weighted_scores',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('dep','watchdog.flood_environment_risk_score','weight',50,'transform','identity'),jsonb_build_object('dep','watchdog.environmental_encumbrance_severity','weight',50,'transform','identity')),'require_all',true),now()),
('watchdog.lender.collateral_completion_watch','watchdog-derived-v20-big-closure','100 - permit collateral completion',array['watchdog.permit_collateral_completion']::text[],'medium','live','V1 collateral completion watch is the exact inverse of governed Permit Collateral Completion. Permit/certificate gap age remains excluded until governed event dates are available.','inverse',jsonb_build_object('dep','watchdog.permit_collateral_completion'),now()),
-- Appraiser
('watchdog.appraiser.parcel_physical_context','watchdog-derived-v20-big-closure','present(lot_area, square_feet, year_built, property_class) / 4 * 100',array['property.lot_area','property.square_feet','property.year_built','property.property_class']::text[],'high','live','Measures availability of four public physical parcel facts. It does not infer condition, quality, utility, effective age, or appraisal adjustments.','completeness','{}'::jsonb,now()),
('watchdog.appraiser.ratio_stability_context','watchdog-derived-v20-big-closure','50% comparable evidence quality + 50% assessment evidence alignment',array['watchdog.comparable_evidence_quality','watchdog.appraiser.assessment_evidence_alignment']::text[],'medium','live','V1 ratio-stability context combines governed public comparable-evidence quality and assessment-evidence alignment. It does not replace a cohort-level ratio study or appraisal analysis.','weighted_scores',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('dep','watchdog.comparable_evidence_quality','weight',50,'transform','identity'),jsonb_build_object('dep','watchdog.appraiser.assessment_evidence_alignment','weight',50,'transform','identity')),'require_all',true),now()),
-- Contractor / development
('watchdog.contractor.ground_condition_attention','watchdog-derived-v20-big-closure','source_alias(watchdog.insurance.geology_hazard_context)',array['watchdog.insurance.geology_hazard_context']::text[],'medium','live','V1 ground-condition attention reuses the governed public geology hazard context. It is a mapping review signal, not a geotechnical, engineering, soil, foundation, or buildability conclusion.','source_alias',jsonb_build_object('dep','watchdog.insurance.geology_hazard_context'),now()),
-- Investor
('watchdog.investor.hold_cost_stability','watchdog-derived-v20-big-closure','70% inverse carry-cost volatility + 30% revenue-base resilience',array['watchdog.investor_carry_cost_volatility','watchdog.revenue_base_resilience']::text[],'medium','live','V1 hold-cost stability combines low governed public carry-cost volatility with municipal revenue-base resilience. It excludes property operating expenses, financing and insurance premiums.','weighted_scores',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('dep','watchdog.investor_carry_cost_volatility','weight',70,'transform','inverse_identity'),jsonb_build_object('dep','watchdog.revenue_base_resilience','weight',30,'transform','identity')),'require_all',true),now()),
('watchdog.investor.capital_reinvestment_signal','watchdog-derived-v20-big-closure','50% permit activity + 50% certificate closure rate',array['watchdog.permit_activity_score','watchdog.certificate_closure_rate']::text[],'medium','live','V1 capital-reinvestment signal uses governed public permit activity and certificate closure context. It does not infer physical condition, dollars invested, return on investment, or quality of work.','weighted_scores',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('dep','watchdog.permit_activity_score','weight',50,'transform','identity'),jsonb_build_object('dep','watchdog.certificate_closure_rate','weight',50,'transform','identity')),'require_all',true),now()),
('watchdog.investor.portfolio_evidence_coverage','watchdog-derived-v20-big-closure','source_alias(watchdog.portfolio_data_confidence)',array['watchdog.portfolio_data_confidence']::text[],'medium','live','V1 portfolio evidence coverage reuses governed Portfolio Data Confidence, which combines property, physical-risk and municipal evidence coverage. It does not measure actual portfolio diversification or completeness of private investment records.','source_alias',jsonb_build_object('dep','watchdog.portfolio_data_confidence'),now()),
('watchdog.investor.municipal_fiscal_direction','watchdog-derived-v20-big-closure','60% revenue-base resilience + 40% inverse municipal fiscal beta',array['watchdog.revenue_base_resilience','watchdog.municipal_fiscal_beta']::text[],'medium','live','V1 municipal fiscal direction summarizes current governed resilience and sensitivity context. It is not a forecast, rating, or investment recommendation.','weighted_scores',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('dep','watchdog.revenue_base_resilience','weight',60,'transform','identity'),jsonb_build_object('dep','watchdog.municipal_fiscal_beta','weight',40,'transform','inverse_identity')),'require_all',true),now()),
('watchdog.investor.exit_tax_story','watchdog-derived-v20-big-closure','60% tax-trend position + 40% seller tax-story stability',array['watchdog.tax_trend_position','watchdog.agent.seller_tax_story_stability']::text[],'medium','live','V1 exit-tax story combines governed historical tax-trend context with seller-facing tax-story stability. Listing tax-burden percentile remains excluded until a governed cohort percentile engine exists.','weighted_scores',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('dep','watchdog.tax_trend_position','weight',60,'transform','identity'),jsonb_build_object('dep','watchdog.agent.seller_tax_story_stability','weight',40,'transform','identity')),'require_all',true),now()),
('watchdog.investor.investment_diligence_priority','watchdog-derived-v20-big-closure','40% carry-cost volatility + 30% asset constraint screen + 30% revaluation hold sensitivity',array['watchdog.investor_carry_cost_volatility','watchdog.investor.asset_constraint_screen','watchdog.investor.revaluation_hold_sensitivity']::text[],'medium','live','Investment Diligence Priority implements the professional-pack intent using the governed carry-cost volatility proxy for the legacy carry-cost-downside concept. It ranks public-record diligence only and is not investment advice.','weighted_scores',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('dep','watchdog.investor_carry_cost_volatility','weight',40,'transform','identity'),jsonb_build_object('dep','watchdog.investor.asset_constraint_screen','weight',30,'transform','identity'),jsonb_build_object('dep','watchdog.investor.revaluation_hold_sensitivity','weight',30,'transform','identity')),'require_all',true),now()),
-- Municipal finance
('watchdog.municipal.tax_base_change_signal','watchdog-derived-v20-big-closure','70% positive ratable growth + 30% inverse tax-base absorption risk',array['budget.ratable_growth','watchdog.tax_base_absorption_risk']::text[],'medium','live','V1 tax-base change signal uses published ratable growth as the direction component and the inverse of governed levy/base absorption risk as quality context. It is not an equalized-value forecast.','weighted_scores',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('dep','budget.ratable_growth','weight',70,'transform','positive_pct5'),jsonb_build_object('dep','watchdog.tax_base_absorption_risk','weight',30,'transform','inverse_identity')),'require_all',true),now()),
-- Insurance / risk
('watchdog.insurance.site_review_escalation','watchdog-derived-v20-big-closure','60% site approval complexity + 40% flood/environment risk',array['watchdog.contractor.site_approval_complexity','watchdog.flood_environment_risk_score']::text[],'medium','live','V1 site-review escalation combines governed public approval-complexity and flood/environment risk screens. It prioritizes verified professional review; it does not determine insurance eligibility, engineering suitability, or buildability.','weighted_scores',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('dep','watchdog.contractor.site_approval_complexity','weight',60,'transform','identity'),jsonb_build_object('dep','watchdog.flood_environment_risk_score','weight',40,'transform','identity')),'require_all',true),now())
on conflict (marker_id) do update set
 engine_version=excluded.engine_version, formula=excluded.formula, dependencies=excluded.dependencies,
 confidence=excluded.confidence, status=excluded.status, explanation=excluded.explanation,
 operation=excluded.operation, config=excluded.config, updated_at=now();

insert into public.data_center_provider_coverage
(marker_id,scopes,provider_key,value_status,source_keys,last_verified_at,notes,provider_kind,source_fields,calculation_key,freshness_seconds,cache_policy,bulk_capable)
select r.marker_id,
 case when r.marker_id like 'watchdog.municipal.%' then array['municipality']::text[] else array['property']::text[] end,
 'watchdog-derived','live',r.dependencies,now(),r.explanation,'derived_governed',r.dependencies,
 'watchdog-derived-v20-big-closure',21600,'refresh_on_demand',true
from public.derived_formula_registry r
where r.engine_version='watchdog-derived-v20-big-closure'
on conflict (marker_id) do update set
 scopes=excluded.scopes,provider_key=excluded.provider_key,value_status=excluded.value_status,
 source_keys=excluded.source_keys,last_verified_at=excluded.last_verified_at,notes=excluded.notes,
 provider_kind=excluded.provider_kind,source_fields=excluded.source_fields,calculation_key=excluded.calculation_key,
 freshness_seconds=excluded.freshness_seconds,cache_policy=excluded.cache_policy,bulk_capable=excluded.bulk_capable;
