create table if not exists public.watchdog_auth_funnel_events (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  visitor_id uuid not null,
  session_id uuid not null,
  event_name text not null,
  signup_context text not null,
  auth_provider text,
  path text,
  referrer_host text,
  landing_path text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  constraint watchdog_auth_funnel_event_name_check check (event_name in ('signup_surface_viewed','auth_provider_clicked','auth_code_requested','auth_success','auth_failure')),
  constraint watchdog_auth_funnel_context_check check (signup_context ~ '^[a-z0-9_.-]{1,64}$'),
  constraint watchdog_auth_funnel_provider_check check (auth_provider is null or auth_provider ~ '^[a-z0-9_.-]{1,64}$')
);

create index if not exists watchdog_auth_funnel_events_session_idx
  on public.watchdog_auth_funnel_events (session_id, occurred_at);
create index if not exists watchdog_auth_funnel_events_visitor_idx
  on public.watchdog_auth_funnel_events (visitor_id, occurred_at);
create index if not exists watchdog_auth_funnel_events_reporting_idx
  on public.watchdog_auth_funnel_events (occurred_at desc, signup_context, event_name, auth_provider);

alter table public.watchdog_auth_funnel_events enable row level security;
revoke all on table public.watchdog_auth_funnel_events from anon, authenticated;

create table if not exists public.watchdog_signup_attribution (
  user_id uuid primary key references auth.users(id) on delete cascade,
  visitor_id uuid not null,
  signup_session_id uuid not null,
  signup_context text not null,
  auth_provider text not null,
  first_touch_referrer_host text,
  first_touch_landing_path text,
  first_touch_utm_source text,
  first_touch_utm_medium text,
  first_touch_utm_campaign text,
  account_created_at timestamptz not null,
  linked_at timestamptz not null default now(),
  constraint watchdog_signup_attribution_context_check check (signup_context ~ '^[a-z0-9_.-]{1,64}$'),
  constraint watchdog_signup_attribution_provider_check check (auth_provider ~ '^[a-z0-9_.-]{1,64}$')
);

create index if not exists watchdog_signup_attribution_reporting_idx
  on public.watchdog_signup_attribution (account_created_at desc, signup_context, auth_provider);
create index if not exists watchdog_signup_attribution_session_idx
  on public.watchdog_signup_attribution (signup_session_id);

alter table public.watchdog_signup_attribution enable row level security;
revoke all on table public.watchdog_signup_attribution from anon, authenticated;

create or replace function public.record_watchdog_auth_funnel_event(
  p_event_name text,
  p_visitor_id uuid,
  p_session_id uuid,
  p_signup_context text,
  p_auth_provider text default null,
  p_path text default null,
  p_referrer_host text default null,
  p_landing_path text default null,
  p_utm_source text default null,
  p_utm_medium text default null,
  p_utm_campaign text default null
) returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_id bigint;
  v_event text := lower(trim(coalesce(p_event_name,'')));
  v_context text := lower(trim(coalesce(p_signup_context,'')));
  v_provider text := nullif(lower(trim(coalesce(p_auth_provider,''))), '');
begin
  if p_visitor_id is null or p_session_id is null then
    raise exception 'analytics_context_required' using errcode = '22023';
  end if;
  if v_event not in ('signup_surface_viewed','auth_provider_clicked','auth_code_requested','auth_success','auth_failure') then
    raise exception 'invalid_auth_event' using errcode = '22023';
  end if;
  if v_context !~ '^[a-z0-9_.-]{1,64}$' then
    raise exception 'invalid_signup_context' using errcode = '22023';
  end if;
  if v_provider is not null and v_provider !~ '^[a-z0-9_.-]{1,64}$' then
    raise exception 'invalid_auth_provider' using errcode = '22023';
  end if;

  insert into public.watchdog_auth_funnel_events (
    visitor_id, session_id, event_name, signup_context, auth_provider,
    path, referrer_host, landing_path, utm_source, utm_medium, utm_campaign
  ) values (
    p_visitor_id, p_session_id, v_event, v_context, v_provider,
    left(nullif(trim(coalesce(p_path,'')),''),240),
    left(nullif(lower(trim(coalesce(p_referrer_host,''))),''),120),
    left(nullif(trim(coalesce(p_landing_path,'')),''),240),
    left(nullif(trim(coalesce(p_utm_source,'')),''),80),
    left(nullif(trim(coalesce(p_utm_medium,'')),''),80),
    left(nullif(trim(coalesce(p_utm_campaign,'')),''),120)
  ) returning id into v_id;
  return v_id;
end;
$$;

revoke all on function public.record_watchdog_auth_funnel_event(text,uuid,uuid,text,text,text,text,text,text,text,text) from public;
grant execute on function public.record_watchdog_auth_funnel_event(text,uuid,uuid,text,text,text,text,text,text,text,text) to anon, authenticated;

create or replace function public.link_my_watchdog_signup_attribution(
  p_visitor_id uuid,
  p_session_id uuid,
  p_signup_context text,
  p_auth_provider text default null
) returns boolean
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
  v_created_at timestamptz;
  v_provider text;
  v_context text := lower(trim(coalesce(p_signup_context,'')));
  v_touch public.watchdog_auth_funnel_events%rowtype;
  v_inserted boolean := false;
begin
  if v_uid is null or p_visitor_id is null or p_session_id is null then
    return false;
  end if;
  if v_context !~ '^[a-z0-9_.-]{1,64}$' then
    return false;
  end if;

  select u.created_at,
         lower(coalesce(nullif(u.raw_app_meta_data->>'provider',''), nullif(trim(coalesce(p_auth_provider,'')),''), 'unknown'))
    into v_created_at, v_provider
  from auth.users u
  where u.id = v_uid;

  if v_created_at is null or v_created_at < now() - interval '2 hours' or v_created_at > now() + interval '5 minutes' then
    return false;
  end if;
  if v_provider !~ '^[a-z0-9_.-]{1,64}$' then
    v_provider := 'unknown';
  end if;

  select * into v_touch
  from public.watchdog_auth_funnel_events e
  where e.visitor_id = p_visitor_id
    and e.session_id = p_session_id
  order by e.occurred_at asc, e.id asc
  limit 1;

  insert into public.watchdog_signup_attribution (
    user_id, visitor_id, signup_session_id, signup_context, auth_provider,
    first_touch_referrer_host, first_touch_landing_path,
    first_touch_utm_source, first_touch_utm_medium, first_touch_utm_campaign,
    account_created_at
  ) values (
    v_uid, p_visitor_id, p_session_id, v_context, v_provider,
    v_touch.referrer_host, v_touch.landing_path,
    v_touch.utm_source, v_touch.utm_medium, v_touch.utm_campaign,
    v_created_at
  ) on conflict (user_id) do nothing;

  get diagnostics v_inserted = row_count;

  if v_inserted then
    insert into public.watchdog_auth_funnel_events (
      visitor_id, session_id, event_name, signup_context, auth_provider,
      path, referrer_host, landing_path, utm_source, utm_medium, utm_campaign
    ) values (
      p_visitor_id, p_session_id, 'auth_success', v_context, v_provider,
      coalesce(v_touch.path, null), v_touch.referrer_host, v_touch.landing_path,
      v_touch.utm_source, v_touch.utm_medium, v_touch.utm_campaign
    );
  end if;

  return v_inserted;
end;
$$;

revoke all on function public.link_my_watchdog_signup_attribution(uuid,uuid,text,text) from public;
grant execute on function public.link_my_watchdog_signup_attribution(uuid,uuid,text,text) to authenticated;

create or replace function public.get_watchdog_acquisition_analytics(p_days integer default 30)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  v_days integer := greatest(1, least(coalesce(p_days,30), 366));
  v_result jsonb;
begin
  if not public.is_watchdog_developer() then
    raise exception 'developer_access_required' using errcode = '42501';
  end if;

  with external_signups as (
    select a.*
    from public.watchdog_signup_attribution a
    where a.account_created_at >= now() - make_interval(days => v_days)
      and not exists (
        select 1 from public.analytics_internal_accounts i where i.user_id = a.user_id
      )
  ), signup_groups as (
    select
      (a.account_created_at at time zone 'America/New_York')::date as day,
      a.signup_context,
      a.auth_provider,
      coalesce(nullif(a.first_touch_utm_source,''), nullif(a.first_touch_referrer_host,''), '(direct/none)') as source,
      coalesce(nullif(a.first_touch_utm_medium,''), '(none)') as medium,
      coalesce(nullif(a.first_touch_utm_campaign,''), '(none)') as campaign,
      coalesce(nullif(a.first_touch_landing_path,''), '(unknown)') as landing_path,
      count(*)::bigint as signups,
      count(*) filter (where exists (select 1 from public.anchor_applications aa where aa.user_id = a.user_id))::bigint as anchor_accounts,
      count(*) filter (where exists (select 1 from public.watchdog_onboarding_profiles op where op.user_id = a.user_id and op.status = 'complete'))::bigint as onboarding_completed
    from external_signups a
    group by 1,2,3,4,5,6,7
    order by 1 desc, signups desc
  ), funnel_groups as (
    select
      (e.occurred_at at time zone 'America/New_York')::date as day,
      e.signup_context,
      e.event_name,
      coalesce(e.auth_provider,'(none)') as auth_provider,
      count(*)::bigint as events,
      count(distinct e.session_id)::bigint as sessions
    from public.watchdog_auth_funnel_events e
    where e.occurred_at >= now() - make_interval(days => v_days)
    group by 1,2,3,4
    order by 1 desc, events desc
  )
  select jsonb_build_object(
    'days', v_days,
    'generated_at', now(),
    'signups', coalesce((select jsonb_agg(to_jsonb(s)) from signup_groups s), '[]'::jsonb),
    'auth_funnel', coalesce((select jsonb_agg(to_jsonb(f)) from funnel_groups f), '[]'::jsonb)
  ) into v_result;

  return v_result;
end;
$$;

revoke all on function public.get_watchdog_acquisition_analytics(integer) from public, anon;
grant execute on function public.get_watchdog_acquisition_analytics(integer) to authenticated;

comment on table public.watchdog_auth_funnel_events is 'Privacy-minimized anonymous auth funnel events. Never stores email addresses, names, IPs, or ANCHOR form answers.';
comment on table public.watchdog_signup_attribution is 'Restricted first-touch bridge from a newly created auth user to the anonymous signup session. Direct client reads are disabled.';
comment on function public.link_my_watchdog_signup_attribution(uuid,uuid,text,text) is 'Links only the current auth.uid and only within two hours of account creation; first successful link is immutable.';
comment on function public.get_watchdog_acquisition_analytics(integer) is 'Developer-only aggregate acquisition report excluding analytics_internal_accounts.';
