-- Register the 12 NJDEP value markers that the environment-provider attribute-map fix
-- (workbench-hydrate v92, njdep-attribute-map-v1) made work in production.
--
-- Evidence: public.watchdog_test_auth_events id 77, 2026-09-29 18:10:51 UTC (event_type provider_release_canary, scenario
-- catalog_njdep_layers_v1, the same reviewed canary as 20260929190000, re-run after v92 was deployed).
-- The canary ran live workbench-hydrate v92 for 6 pins in 6 counties as a short-lived bootstrap developer
-- user (deleted afterwards; 0 test accounts and 0 canary users left). Status 200, assertion_ok true,
-- no hydrate failures, no resolver errors, no missing statuses. md5(metadata::text) of that row is
-- 3c8ba201b215b1236bbe2ac067d214d2.
--
-- Rule: a marker is registered when the resolver returned state available with a non-blank value on at
-- least one pin and every other pin returned source_checked_no_value (the property is outside that
-- layer). Nine markers returned values on all 6 pins. Three are small-zone layers and returned values
-- only for pins inside the zone: water.water_source_area (1 of 6), water.wellhead_community_tier (1 of 6)
-- and land.open_space_encumbrance (2 of 6, the two pins on open space).
--
-- Registered: 12. Still not registered: 5.
--   not registered  geology.surficial_aquifer: layer njdep-geology-live/23 had no features at any of the 6 pins; not mapped, needs a pin inside a surficial aquifer polygon
--   not registered  water.wellhead_community_travel_time: mapped (TRAVELTIME on njdep-hydro-live/25) but returned no value at any pin, including the one inside a community wellhead area; needs its own evidence
--   not registered  water.wellhead_noncommunity_tier: layer njdep-hydro-live/26 had no features at any of the 6 pins; not mapped, needs a pin inside a non-community wellhead area
--   not registered  water.wellhead_noncommunity_travel_time: layer njdep-hydro-live/26 had no features at any of the 6 pins; not mapped, needs a pin inside a non-community wellhead area
--   not registered  water.groundwater_treatment_source_area: layer njdep-hydro-live/27 had no features at any of the 6 pins; not mapped, needs a pin inside a treatment source area

insert into public.data_center_provider_coverage
  (marker_id,scopes,provider_key,value_status,source_keys,last_verified_at,notes,
   provider_kind,source_fields,calculation_key,freshness_seconds,cache_policy,bulk_capable)
values
  ('geology.bedrock_aquifer',array['property']::text[],'njdep_geology_spatial_v1','live',array['njdep-geology-live']::text[],'2026-09-29 18:10:51.555926+00'::timestamptz,
   'Resolver evidence: provider release canary catalog_njdep_layers_v1 (public.watchdog_test_auth_events id 77, 2026-09-29 18:10:51 UTC) ran production workbench-hydrate v92 (Watchdog provider-family resolver v19, njdep-attribute-map-v1, spatial-preflight-v11-dca-community-access) as a short-lived bootstrap developer user; the resolver returned state available with a value on 6 of 6 sampled pins in 6 counties and source_checked_no_value on the rest; observed 0202_1_1 (Bergen) = Diabase; 0336_1.01_1 (Burlington) = Kirkwood-Cohansey aquifer system; 0502_1056_2 (Cape May) = Holly Beach water-bearing zone; 1420_1003_1 (Morris) = Igneous and metamorphic rocks; 0113_2802_10 (Atlantic) = Kirkwood-Cohansey aquifer system; 1906_1301_19 (Sussex) = Igneous and metamorphic rocks. Layer confirmed from the canary''s live layer metadata: NJDEP Geology/MapServer/13 "Bedrock Aquifers" (polygon); value read from GEONAME at the representative parcel point.',
   'authoritative_spatial_reference',array['Geology/MapServer/13','GEONAME','representative_parcel_point_intersects']::text[],'spatial-preflight-v11-dca-community-access',21600,'external_live',false),
  ('geology.bedrock_geology',array['property']::text[],'njdep_geology_spatial_v1','live',array['njdep-geology-live']::text[],'2026-09-29 18:10:51.555926+00'::timestamptz,
   'Resolver evidence: provider release canary catalog_njdep_layers_v1 (public.watchdog_test_auth_events id 77, 2026-09-29 18:10:51 UTC) ran production workbench-hydrate v92 (Watchdog provider-family resolver v19, njdep-attribute-map-v1, spatial-preflight-v11-dca-community-access) as a short-lived bootstrap developer user; the resolver returned state available with a value on 6 of 6 sampled pins in 6 counties and source_checked_no_value on the rest; observed 0202_1_1 (Bergen) = Jurassic Diabase; 0336_1.01_1 (Burlington) = Cohansey Formation; 0502_1056_2 (Cape May) = Unnamed Formation at Cape May; 1420_1003_1 (Morris) = Biotite-Quartz-Oligoclase Gneiss; 0113_2802_10 (Atlantic) = Cohansey Formation; 1906_1301_19 (Sussex) = Franklin Marble. Layer confirmed from the canary''s live layer metadata: NJDEP Geology/MapServer/14 "Bedrock Geology" (polygon); value read from GEONAME at the representative parcel point.',
   'authoritative_spatial_reference',array['Geology/MapServer/14','GEONAME','representative_parcel_point_intersects']::text[],'spatial-preflight-v11-dca-community-access',21600,'external_live',false),
  ('geology.groundwater_recharge_rank',array['property']::text[],'njdep_geology_spatial_v1','live',array['njdep-geology-live']::text[],'2026-09-29 18:10:51.555926+00'::timestamptz,
   'Resolver evidence: provider release canary catalog_njdep_layers_v1 (public.watchdog_test_auth_events id 77, 2026-09-29 18:10:51 UTC) ran production workbench-hydrate v92 (Watchdog provider-family resolver v19, njdep-attribute-map-v1, spatial-preflight-v11-dca-community-access) as a short-lived bootstrap developer user; the resolver returned state available with a value on 6 of 6 sampled pins in 6 counties and source_checked_no_value on the rest; observed 0202_1_1 (Bergen) = B; 0336_1.01_1 (Burlington) = W; 0502_1056_2 (Cape May) = E; 1420_1003_1 (Morris) = A; 0113_2802_10 (Atlantic) = D; 1906_1301_19 (Sussex) = E. Layer confirmed from the canary''s live layer metadata: NJDEP Geology/MapServer/18 "Ground Water Recharge Areas" (polygon); value read from RANK at the representative parcel point.',
   'authoritative_spatial_reference',array['Geology/MapServer/18','RANK','representative_parcel_point_intersects']::text[],'spatial-preflight-v11-dca-community-access',21600,'external_live',false),
  ('geology.sole_source_aquifer',array['property']::text[],'njdep_geology_spatial_v1','live',array['njdep-geology-live']::text[],'2026-09-29 18:10:51.555926+00'::timestamptz,
   'Resolver evidence: provider release canary catalog_njdep_layers_v1 (public.watchdog_test_auth_events id 77, 2026-09-29 18:10:51 UTC) ran production workbench-hydrate v92 (Watchdog provider-family resolver v19, njdep-attribute-map-v1, spatial-preflight-v11-dca-community-access) as a short-lived bootstrap developer user; the resolver returned state available with a value on 6 of 6 sampled pins in 6 counties and source_checked_no_value on the rest; observed 0202_1_1 (Bergen) = Not a SSA; 0336_1.01_1 (Burlington) = Coastal Plain; 0502_1056_2 (Cape May) = Coastal Plain; 1420_1003_1 (Morris) = Northwest New Jersey; 0113_2802_10 (Atlantic) = Coastal Plain; 1906_1301_19 (Sussex) = Northwest New Jersey. Layer confirmed from the canary''s live layer metadata: NJDEP Geology/MapServer/19 "Sole-Source Aquifers" (polygon); value read from SSANAME at the representative parcel point.',
   'authoritative_spatial_reference',array['Geology/MapServer/19','SSANAME','representative_parcel_point_intersects']::text[],'spatial-preflight-v11-dca-community-access',21600,'external_live',false),
  ('geology.physiographic_province',array['property']::text[],'njdep_geology_spatial_v1','live',array['njdep-geology-live']::text[],'2026-09-29 18:10:51.555926+00'::timestamptz,
   'Resolver evidence: provider release canary catalog_njdep_layers_v1 (public.watchdog_test_auth_events id 77, 2026-09-29 18:10:51 UTC) ran production workbench-hydrate v92 (Watchdog provider-family resolver v19, njdep-attribute-map-v1, spatial-preflight-v11-dca-community-access) as a short-lived bootstrap developer user; the resolver returned state available with a value on 6 of 6 sampled pins in 6 counties and source_checked_no_value on the rest; observed 0202_1_1 (Bergen) = Piedmont; 0336_1.01_1 (Burlington) = Coastal Plain; 0502_1056_2 (Cape May) = Coastal Plain; 1420_1003_1 (Morris) = Highlands; 0113_2802_10 (Atlantic) = Coastal Plain; 1906_1301_19 (Sussex) = Highlands. Layer confirmed from the canary''s live layer metadata: NJDEP Geology/MapServer/20 "Physiographic Provinces" (polygon); value read from PROVINCE at the representative parcel point.',
   'authoritative_spatial_reference',array['Geology/MapServer/20','PROVINCE','representative_parcel_point_intersects']::text[],'spatial-preflight-v11-dca-community-access',21600,'external_live',false),
  ('geology.surficial_geology',array['property']::text[],'njdep_geology_spatial_v1','live',array['njdep-geology-live']::text[],'2026-09-29 18:10:51.555926+00'::timestamptz,
   'Resolver evidence: provider release canary catalog_njdep_layers_v1 (public.watchdog_test_auth_events id 77, 2026-09-29 18:10:51 UTC) ran production workbench-hydrate v92 (Watchdog provider-family resolver v19, njdep-attribute-map-v1, spatial-preflight-v11-dca-community-access) as a short-lived bootstrap developer user; the resolver returned state available with a value on 6 of 6 sampled pins in 6 counties and source_checked_no_value on the rest; observed 0202_1_1 (Bergen) = RAHWAY TILL; 0336_1.01_1 (Burlington) = SWAMP AND MARSH DEPOSITS; 0502_1056_2 (Cape May) = CAPE MAY FORMATION, UNIT 3; 1420_1003_1 (Morris) = WEATHERED GNEISS; 0113_2802_10 (Atlantic) = BRIDGETON FORMATION; 1906_1301_19 (Sussex) = NETCONG TILL. Layer confirmed from the canary''s live layer metadata: NJDEP Geology/MapServer/25 "Surficial Geology" (polygon); value read from GEONAME at the representative parcel point.',
   'authoritative_spatial_reference',array['Geology/MapServer/25','GEONAME','representative_parcel_point_intersects']::text[],'spatial-preflight-v11-dca-community-access',21600,'external_live',false),
  ('water.wellhead_community_tier',array['property']::text[],'njdep_hydro_spatial_v1','live',array['njdep-hydro-live']::text[],'2026-09-29 18:10:51.555926+00'::timestamptz,
   'Resolver evidence: provider release canary catalog_njdep_layers_v1 (public.watchdog_test_auth_events id 77, 2026-09-29 18:10:51 UTC) ran production workbench-hydrate v92 (Watchdog provider-family resolver v19, njdep-attribute-map-v1, spatial-preflight-v11-dca-community-access) as a short-lived bootstrap developer user; the resolver returned state available with a value on 1 of 6 sampled pins in 6 counties and source_checked_no_value on the rest; observed 0202_1_1 (Bergen) = no value (outside the layer); 0336_1.01_1 (Burlington) = no value (outside the layer); 0502_1056_2 (Cape May) = no value (outside the layer); 1420_1003_1 (Morris) = no value (outside the layer); 0113_2802_10 (Atlantic) = 2; 1906_1301_19 (Sussex) = no value (outside the layer). Layer confirmed from the canary''s live layer metadata: NJDEP Hydrography/MapServer/25 "Well Head Protection Areas (Community)" (polygon); value read from TIER at the representative parcel point.',
   'authoritative_spatial_reference',array['Hydrography/MapServer/25','TIER','representative_parcel_point_intersects']::text[],'spatial-preflight-v11-dca-community-access',21600,'external_live',false),
  ('water.water_source_area',array['property']::text[],'njdep_hydro_spatial_v1','live',array['njdep-hydro-live']::text[],'2026-09-29 18:10:51.555926+00'::timestamptz,
   'Resolver evidence: provider release canary catalog_njdep_layers_v1 (public.watchdog_test_auth_events id 77, 2026-09-29 18:10:51 UTC) ran production workbench-hydrate v92 (Watchdog provider-family resolver v19, njdep-attribute-map-v1, spatial-preflight-v11-dca-community-access) as a short-lived bootstrap developer user; the resolver returned state available with a value on 1 of 6 sampled pins in 6 counties and source_checked_no_value on the rest; observed 0202_1_1 (Bergen) = no value (outside the layer); 0336_1.01_1 (Burlington) = no value (outside the layer); 0502_1056_2 (Cape May) = no value (outside the layer); 1420_1003_1 (Morris) = Elizabethtown Water Company; 0113_2802_10 (Atlantic) = no value (outside the layer); 1906_1301_19 (Sussex) = no value (outside the layer). Layer confirmed from the canary''s live layer metadata: NJDEP Hydrography/MapServer/16 "Water Source Areas" (polygon); value read from SYS_NAME at the representative parcel point.',
   'authoritative_spatial_reference',array['Hydrography/MapServer/16','SYS_NAME','representative_parcel_point_intersects']::text[],'spatial-preflight-v11-dca-community-access',21600,'external_live',false),
  ('water.watershed_huc11',array['property']::text[],'njdep_hydro_spatial_v1','live',array['njdep-hydro-live']::text[],'2026-09-29 18:10:51.555926+00'::timestamptz,
   'Resolver evidence: provider release canary catalog_njdep_layers_v1 (public.watchdog_test_auth_events id 77, 2026-09-29 18:10:51 UTC) ran production workbench-hydrate v92 (Watchdog provider-family resolver v19, njdep-attribute-map-v1, spatial-preflight-v11-dca-community-access) as a short-lived bootstrap developer user; the resolver returned state available with a value on 6 of 6 sampled pins in 6 counties and source_checked_no_value on the rest; observed 0202_1_1 (Bergen) = Hudson River (HUC11 02030101170); 0336_1.01_1 (Burlington) = Mullica River (above Basto River) (HUC11 02040301160); 0502_1056_2 (Cape May) = Cape May Bays & Tribs East (HUC11 02040302080); 1420_1003_1 (Morris) = Lamington River (HUC11 02030105050); 0113_2802_10 (Atlantic) = Mullica River (above Basto River) (HUC11 02040301160); 1906_1301_19 (Sussex) = Wallkill River (above road to Martins) (HUC11 02020007010). Layer confirmed from the canary''s live layer metadata: NJDEP Hydrography/MapServer/17 "Watersheds (Watersheds by Name)-DEPHUC11" (polygon); value read from W_NAME and HUC11 at the representative parcel point.',
   'authoritative_spatial_reference',array['Hydrography/MapServer/17','W_NAME','HUC11','representative_parcel_point_intersects']::text[],'spatial-preflight-v11-dca-community-access',21600,'external_live',false),
  ('water.subwatershed_huc14',array['property']::text[],'njdep_hydro_spatial_v1','live',array['njdep-hydro-live']::text[],'2026-09-29 18:10:51.555926+00'::timestamptz,
   'Resolver evidence: provider release canary catalog_njdep_layers_v1 (public.watchdog_test_auth_events id 77, 2026-09-29 18:10:51 UTC) ran production workbench-hydrate v92 (Watchdog provider-family resolver v19, njdep-attribute-map-v1, spatial-preflight-v11-dca-community-access) as a short-lived bootstrap developer user; the resolver returned state available with a value on 6 of 6 sampled pins in 6 counties and source_checked_no_value on the rest; observed 0202_1_1 (Bergen) = Hudson River (upper) (HUC14 02030101170010); 0336_1.01_1 (Burlington) = Mullica River (39d40m30s to Rt 206) (HUC14 02040301160140); 0502_1056_2 (Cape May) = Cape May Harbor & Bays (below Rt 47) (HUC14 02040302080090); 1420_1003_1 (Morris) = Lamington R (above Rt 10) (HUC14 02030105050010); 0113_2802_10 (Atlantic) = Great Swamp Branch (below Rt 206) (HUC14 02040301160130); 1906_1301_19 (Sussex) = Wallkill R(Hamburg SW Bdy to Frkln Pnd) (HUC14 02020007010040). Layer confirmed from the canary''s live layer metadata: NJDEP Hydrography/MapServer/22 "Watersheds (Subwatersheds by name) DEPHUC14" (polygon); value read from SW_NAME and HUC14 at the representative parcel point.',
   'authoritative_spatial_reference',array['Hydrography/MapServer/22','SW_NAME','HUC14','representative_parcel_point_intersects']::text[],'spatial-preflight-v11-dca-community-access',21600,'external_live',false),
  ('land.open_space_encumbrance',array['property']::text[],'njdep_land_spatial_v1','live',array['njdep-land-live']::text[],'2026-09-29 18:10:51.555926+00'::timestamptz,
   'Resolver evidence: provider release canary catalog_njdep_layers_v1 (public.watchdog_test_auth_events id 77, 2026-09-29 18:10:51 UTC) ran production workbench-hydrate v92 (Watchdog provider-family resolver v19, njdep-attribute-map-v1, spatial-preflight-v11-dca-community-access) as a short-lived bootstrap developer user; the resolver returned state available with a value on 2 of 6 sampled pins in 6 counties and source_checked_no_value on the rest; observed 0202_1_1 (Bergen) = Not Encumbered; 0336_1.01_1 (Burlington) = Encumbered; 0502_1056_2 (Cape May) = no value (outside the layer); 1420_1003_1 (Morris) = no value (outside the layer); 0113_2802_10 (Atlantic) = no value (outside the layer); 1906_1301_19 (Sussex) = no value (outside the layer). Layer confirmed from the canary''s live layer metadata: NJDEP Land/MapServer/65 "Open Space" (polygon); value read from ENCUMBRANCE_STATUS at the representative parcel point.',
   'authoritative_spatial_reference',array['Land/MapServer/65','ENCUMBRANCE_STATUS','representative_parcel_point_intersects']::text[],'spatial-preflight-v11-dca-community-access',21600,'external_live',false),
  ('land.wetland_mitigation_service_area',array['property']::text[],'njdep_land_spatial_v1','live',array['njdep-land-live']::text[],'2026-09-29 18:10:51.555926+00'::timestamptz,
   'Resolver evidence: provider release canary catalog_njdep_layers_v1 (public.watchdog_test_auth_events id 77, 2026-09-29 18:10:51 UTC) ran production workbench-hydrate v92 (Watchdog provider-family resolver v19, njdep-attribute-map-v1, spatial-preflight-v11-dca-community-access) as a short-lived bootstrap developer user; the resolver returned state available with a value on 6 of 6 sampled pins in 6 counties and source_checked_no_value on the rest; observed 0202_1_1 (Bergen) = MRI-3 + Oradell Reservoir; 0336_1.01_1 (Burlington) = Mullica River; 0502_1056_2 (Cape May) = Stipson''s Island FWW; 1420_1003_1 (Morris) = Cranbury; 0113_2802_10 (Atlantic) = Mullica River + Lakes Creek; 1906_1301_19 (Sussex) = Oxford Western + Pequest River. Layer confirmed from the canary''s live layer metadata: NJDEP Land/MapServer/70 "Wetland Mitigation Bank Service Areas" (polygon); value read from SERVICEAREA at the representative parcel point.',
   'authoritative_spatial_reference',array['Land/MapServer/70','SERVICEAREA','representative_parcel_point_intersects']::text[],'spatial-preflight-v11-dca-community-access',21600,'external_live',false)
on conflict (marker_id) do update set
  scopes=excluded.scopes,provider_key=excluded.provider_key,value_status=excluded.value_status,
  source_keys=excluded.source_keys,last_verified_at=excluded.last_verified_at,notes=excluded.notes,
  provider_kind=excluded.provider_kind,source_fields=excluded.source_fields,
  calculation_key=excluded.calculation_key,freshness_seconds=excluded.freshness_seconds,
  cache_policy=excluded.cache_policy,bulk_capable=excluded.bulk_capable;
