-- NJW-51: preserve each completed dynamic-list generation long enough to compute
-- truthful new/dropped/assessment-change diffs before the materializer removes the
-- previous membership generation. This does not schedule scans or send mail.

create table if not exists public.agent_dynamic_list_generation_snapshots (
  user_id uuid not null references auth.users(id) on delete cascade,
  dynamic_list_id uuid not null references public.agent_dynamic_lists(id) on delete cascade,
  generation uuid not null,
  pams_pin text not null,
  address text,
  municipality text,
  county text,
  assessed_value bigint,
  last_year_tax numeric,
  captured_at timestamptz not null default now(),
  primary key (dynamic_list_id, generation, pams_pin)
);

create index if not exists agent_dynamic_list_generation_snapshots_user_list_idx
  on public.agent_dynamic_list_generation_snapshots(user_id, dynamic_list_id, captured_at desc);

alter table public.agent_dynamic_list_generation_snapshots enable row level security;
drop policy if exists "dynamic list generation snapshots own rows" on public.agent_dynamic_list_generation_snapshots;
create policy "dynamic list generation snapshots own rows"
  on public.agent_dynamic_list_generation_snapshots
  for select to authenticated
  using ((select auth.uid()) = user_id);
revoke all on public.agent_dynamic_list_generation_snapshots from anon, authenticated;
grant select on public.agent_dynamic_list_generation_snapshots to authenticated;

create table if not exists public.agent_dynamic_list_diffs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  dynamic_list_id uuid not null references public.agent_dynamic_lists(id) on delete cascade,
  from_generation uuid not null,
  to_generation uuid not null,
  source_complete boolean not null default true,
  capacity_limited boolean not null default false,
  new_match_count integer not null default 0,
  dropped_match_count integer not null default 0,
  assessment_change_count integer not null default 0,
  created_at timestamptz not null default now(),
  unique (dynamic_list_id, to_generation)
);

create index if not exists agent_dynamic_list_diffs_user_list_idx
  on public.agent_dynamic_list_diffs(user_id, dynamic_list_id, created_at desc);

alter table public.agent_dynamic_list_diffs enable row level security;
drop policy if exists "dynamic list diffs own rows" on public.agent_dynamic_list_diffs;
create policy "dynamic list diffs own rows"
  on public.agent_dynamic_list_diffs
  for select to authenticated
  using ((select auth.uid()) = user_id);
revoke all on public.agent_dynamic_list_diffs from anon, authenticated;
grant select on public.agent_dynamic_list_diffs to authenticated;

create table if not exists public.agent_dynamic_list_diff_items (
  id bigint generated by default as identity primary key,
  diff_id bigint not null references public.agent_dynamic_list_diffs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  dynamic_list_id uuid not null references public.agent_dynamic_lists(id) on delete cascade,
  pams_pin text not null,
  change_type text not null check (change_type in ('new_match','dropped_match','assessment_changed')),
  address text,
  municipality text,
  old_assessed_value bigint,
  new_assessed_value bigint,
  created_at timestamptz not null default now(),
  unique (diff_id, change_type, pams_pin)
);

create index if not exists agent_dynamic_list_diff_items_user_list_idx
  on public.agent_dynamic_list_diff_items(user_id, dynamic_list_id, created_at desc);

alter table public.agent_dynamic_list_diff_items enable row level security;
drop policy if exists "dynamic list diff items own rows" on public.agent_dynamic_list_diff_items;
create policy "dynamic list diff items own rows"
  on public.agent_dynamic_list_diff_items
  for select to authenticated
  using ((select auth.uid()) = user_id);
revoke all on public.agent_dynamic_list_diff_items from anon, authenticated;
grant select on public.agent_dynamic_list_diff_items to authenticated;

create or replace function public.capture_dynamic_list_generation_diff_v1()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_diff_id bigint;
  v_old_snapshot_count integer := 0;
begin
  if tg_op = 'UPDATE' and new.generation is not distinct from old.generation then
    return new;
  end if;

  insert into public.agent_dynamic_list_generation_snapshots (
    user_id, dynamic_list_id, generation, pams_pin, address, municipality,
    county, assessed_value, last_year_tax, captured_at
  )
  select
    new.user_id,
    new.dynamic_list_id,
    new.generation,
    p.pams_pin,
    l.address,
    l.town,
    l.county,
    l.assessed_value,
    l.last_year_tax,
    coalesce(new.materialized_at, now())
  from public.agent_dynamic_list_properties p
  left join public.property_lookups l on l.pams_pin = p.pams_pin
  where p.dynamic_list_id = new.dynamic_list_id
    and p.generation = new.generation
  on conflict (dynamic_list_id, generation, pams_pin) do update
    set address = excluded.address,
        municipality = excluded.municipality,
        county = excluded.county,
        assessed_value = excluded.assessed_value,
        last_year_tax = excluded.last_year_tax,
        captured_at = excluded.captured_at;

  if tg_op <> 'UPDATE' then
    return new;
  end if;

  select count(*) into v_old_snapshot_count
  from public.agent_dynamic_list_generation_snapshots s
  where s.dynamic_list_id = new.dynamic_list_id
    and s.generation = old.generation;

  -- A capacity-limited materialization does not persist the complete source set.
  -- Suppress match churn rather than mislabel plan-capacity rotation as a source change.
  if v_old_snapshot_count = 0
     or not coalesce(old.source_complete, false)
     or not coalesce(new.source_complete, false)
     or coalesce(old.capacity_limited, false)
     or coalesce(new.capacity_limited, false) then
    return new;
  end if;

  insert into public.agent_dynamic_list_diffs (
    user_id, dynamic_list_id, from_generation, to_generation,
    source_complete, capacity_limited
  ) values (
    new.user_id, new.dynamic_list_id, old.generation, new.generation, true, false
  )
  on conflict (dynamic_list_id, to_generation) do update
    set from_generation = excluded.from_generation,
        source_complete = true,
        capacity_limited = false
  returning id into v_diff_id;

  insert into public.agent_dynamic_list_diff_items (
    diff_id, user_id, dynamic_list_id, pams_pin, change_type,
    address, municipality, old_assessed_value, new_assessed_value
  )
  select
    v_diff_id, new.user_id, new.dynamic_list_id, n.pams_pin, 'new_match',
    n.address, n.municipality, null, n.assessed_value
  from public.agent_dynamic_list_generation_snapshots n
  left join public.agent_dynamic_list_generation_snapshots o
    on o.dynamic_list_id = n.dynamic_list_id
   and o.generation = old.generation
   and o.pams_pin = n.pams_pin
  where n.dynamic_list_id = new.dynamic_list_id
    and n.generation = new.generation
    and o.pams_pin is null
  on conflict (diff_id, change_type, pams_pin) do nothing;

  insert into public.agent_dynamic_list_diff_items (
    diff_id, user_id, dynamic_list_id, pams_pin, change_type,
    address, municipality, old_assessed_value, new_assessed_value
  )
  select
    v_diff_id, new.user_id, new.dynamic_list_id, o.pams_pin, 'dropped_match',
    o.address, o.municipality, o.assessed_value, null
  from public.agent_dynamic_list_generation_snapshots o
  left join public.agent_dynamic_list_generation_snapshots n
    on n.dynamic_list_id = o.dynamic_list_id
   and n.generation = new.generation
   and n.pams_pin = o.pams_pin
  where o.dynamic_list_id = new.dynamic_list_id
    and o.generation = old.generation
    and n.pams_pin is null
  on conflict (diff_id, change_type, pams_pin) do nothing;

  insert into public.agent_dynamic_list_diff_items (
    diff_id, user_id, dynamic_list_id, pams_pin, change_type,
    address, municipality, old_assessed_value, new_assessed_value
  )
  select
    v_diff_id, new.user_id, new.dynamic_list_id, n.pams_pin, 'assessment_changed',
    coalesce(n.address, o.address), coalesce(n.municipality, o.municipality),
    o.assessed_value, n.assessed_value
  from public.agent_dynamic_list_generation_snapshots o
  join public.agent_dynamic_list_generation_snapshots n
    on n.dynamic_list_id = o.dynamic_list_id
   and n.generation = new.generation
   and n.pams_pin = o.pams_pin
  where o.dynamic_list_id = new.dynamic_list_id
    and o.generation = old.generation
    and o.assessed_value is distinct from n.assessed_value
  on conflict (diff_id, change_type, pams_pin) do nothing;

  update public.agent_dynamic_list_diffs d
  set new_match_count = x.new_match_count,
      dropped_match_count = x.dropped_match_count,
      assessment_change_count = x.assessment_change_count
  from (
    select
      count(*) filter (where change_type = 'new_match')::integer as new_match_count,
      count(*) filter (where change_type = 'dropped_match')::integer as dropped_match_count,
      count(*) filter (where change_type = 'assessment_changed')::integer as assessment_change_count
    from public.agent_dynamic_list_diff_items
    where diff_id = v_diff_id
  ) x
  where d.id = v_diff_id;

  -- Feed the existing Property Pulse contract. The weekly agent digest can consume
  -- these once monitored-list memberships are included in its own audience query.
  insert into public.property_update_events (
    user_id, pams_pin, event_key, event_type, severity, title, summary,
    payload, occurred_at, marker_id, old_value, new_value, delta_numeric,
    source_url, minimum_plan
  )
  select
    i.user_id,
    i.pams_pin,
    'dynamic-list-diff:' || i.diff_id || ':' || i.change_type || ':' || i.pams_pin,
    case when i.change_type = 'assessment_changed' then 'assessment_change' else 'source_refresh' end,
    case when i.change_type = 'assessment_changed' then 'watch' else 'info' end,
    case i.change_type
      when 'new_match' then 'New saved-list match'
      when 'dropped_match' then 'Property no longer matches saved list'
      else 'Assessment changed in saved list'
    end,
    case i.change_type
      when 'new_match' then 'A property now matches this saved Watchdog list.'
      when 'dropped_match' then 'A property no longer matches this saved Watchdog list.'
      else 'Watchdog recorded a sourced assessment change for a property in this saved list.'
    end,
    jsonb_build_object(
      'dynamic_list_id', i.dynamic_list_id,
      'diff_id', i.diff_id,
      'change_type', i.change_type,
      'property_address', i.address,
      'municipality', i.municipality,
      'source_key', 'watchdog.dynamic-list-generation-diff'
    ),
    now(),
    case when i.change_type = 'assessment_changed' then 'property.assessed_value' else null end,
    case when i.old_assessed_value is null then null else i.old_assessed_value::text end,
    case when i.new_assessed_value is null then null else i.new_assessed_value::text end,
    case
      when i.change_type = 'assessment_changed'
       and i.old_assessed_value is not null
       and i.new_assessed_value is not null
      then (i.new_assessed_value - i.old_assessed_value)::numeric
      else null
    end,
    'https://www.watchdogindex.com/data-methodology',
    'standard'
  from public.agent_dynamic_list_diff_items i
  where i.diff_id = v_diff_id
  on conflict (user_id, event_key) do nothing;

  return new;
end;
$$;

revoke all on function public.capture_dynamic_list_generation_diff_v1() from public, anon, authenticated;

drop trigger if exists capture_dynamic_list_generation_diff_v1 on public.agent_dynamic_list_materializations;
create trigger capture_dynamic_list_generation_diff_v1
after insert or update of generation on public.agent_dynamic_list_materializations
for each row execute function public.capture_dynamic_list_generation_diff_v1();

-- Seed the currently active generation so the next successful refresh has a truthful baseline.
insert into public.agent_dynamic_list_generation_snapshots (
  user_id, dynamic_list_id, generation, pams_pin, address, municipality,
  county, assessed_value, last_year_tax, captured_at
)
select
  m.user_id,
  m.dynamic_list_id,
  m.generation,
  p.pams_pin,
  l.address,
  l.town,
  l.county,
  l.assessed_value,
  l.last_year_tax,
  coalesce(m.materialized_at, m.updated_at, now())
from public.agent_dynamic_list_materializations m
join public.agent_dynamic_list_properties p
  on p.dynamic_list_id = m.dynamic_list_id
 and p.generation = m.generation
left join public.property_lookups l on l.pams_pin = p.pams_pin
on conflict (dynamic_list_id, generation, pams_pin) do nothing;
