-- Watchdog Intelligence Intent Context Graph
-- Applied to production 2026-08-19. Owner-scoped and RLS protected.
create table if not exists public.intelligence_intent_states (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  context_key text not null default 'global',
  profession text,
  active_job text,
  active_job_confidence numeric(5,2) check (active_job_confidence is null or (active_job_confidence between 0 and 100)),
  candidate_intents jsonb not null default '[]'::jsonb,
  evidence_refs jsonb not null default '[]'::jsonb,
  confirmed_fields jsonb not null default '{}'::jsonb,
  assumptions jsonb not null default '[]'::jsonb,
  missing_questions jsonb not null default '[]'::jsonb,
  property_scope jsonb not null default '[]'::jsonb,
  source_freshness jsonb not null default '{}'::jsonb,
  last_meaningful_update timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, context_key)
);
create table if not exists public.intelligence_intent_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  intent_state_id uuid references public.intelligence_intent_states(id) on delete set null,
  context_key text not null default 'global',
  event_type text not null check (event_type in ('observation','hypothesis','question','answer','correction','intent_update','analysis','action','outcome')),
  fact_class text not null check (fact_class in ('observed','derived','hypothesis','user_confirmed','assumption','missing_evidence')),
  payload jsonb not null default '{}'::jsonb,
  evidence_refs jsonb not null default '[]'::jsonb,
  confidence numeric(5,2) check (confidence is null or (confidence between 0 and 100)),
  created_at timestamptz not null default now()
);
create index if not exists intelligence_intent_states_user_updated_idx on public.intelligence_intent_states(user_id, updated_at desc);
create index if not exists intelligence_intent_events_user_context_created_idx on public.intelligence_intent_events(user_id, context_key, created_at desc);
alter table public.intelligence_intent_states enable row level security;
alter table public.intelligence_intent_events enable row level security;
drop policy if exists intent_states_owner_select on public.intelligence_intent_states;
create policy intent_states_owner_select on public.intelligence_intent_states for select to authenticated using (auth.uid() = user_id);
drop policy if exists intent_states_owner_insert on public.intelligence_intent_states;
create policy intent_states_owner_insert on public.intelligence_intent_states for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists intent_states_owner_update on public.intelligence_intent_states;
create policy intent_states_owner_update on public.intelligence_intent_states for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists intent_events_owner_select on public.intelligence_intent_events;
create policy intent_events_owner_select on public.intelligence_intent_events for select to authenticated using (auth.uid() = user_id);
drop policy if exists intent_events_owner_insert on public.intelligence_intent_events;
create policy intent_events_owner_insert on public.intelligence_intent_events for insert to authenticated with check (auth.uid() = user_id);
revoke all on public.intelligence_intent_states from anon;
revoke all on public.intelligence_intent_events from anon;
grant select,insert,update on public.intelligence_intent_states to authenticated;
grant select,insert on public.intelligence_intent_events to authenticated;
