-- Register the 12 NJDEP catalog markers that the provider release canary catalog_njdep_layers_v1
-- observed with positive values in production. Generated 2026-09-29; review before applying.
--
-- Evidence: public.watchdog_test_auth_events id 76 (event_type provider_release_canary, created
-- 2026-09-29 17:37:04.188048+00). The canary ran live workbench-hydrate for 6 pins in 6 counties as a short-lived
-- bootstrap developer user (deleted afterwards). Status 200, no hydrate failures, no resolver errors.
-- Each registered marker returned state available on all 6 pins and a positive value (true or a count
-- above 0) on at least one. Its layer id was confirmed against the live layer name. The observed
-- values below were checked against md5 03c62a782ebae26ba405abf28d5daa50 of the production JSON.
--
-- Registered: 12. Not registered: 17.
--   not registered  geology.bedrock_aquifer: features at 6/6 pins (layer 13, key GEONAME); resolver has no attribute mapping yet, awaits the environment-provider fix and catalog_njdep_layers_v2
--   not registered  geology.bedrock_geology: features at 6/6 pins (layer 14, key geoname); awaits the attribute-map fix and v2 canary
--   not registered  geology.groundwater_recharge_rank: features at 6/6 pins (layer 18, key RANK); awaits the attribute-map fix and v2 canary
--   not registered  geology.sole_source_aquifer: features at 6/6 pins (layer 19, key SSANAME); awaits the attribute-map fix and v2 canary
--   not registered  geology.physiographic_province: features at 6/6 pins (layer 20, key PROVINCE); awaits the attribute-map fix and v2 canary
--   not registered  geology.surficial_geology: features at 6/6 pins (layer 25, key GEONAME); awaits the attribute-map fix and v2 canary
--   not registered  water.wellhead_community_tier: features at 1/6 pins (layer 25, key TIER); awaits the attribute-map fix and v2 canary
--   not registered  water.wellhead_community_travel_time: features at 1/6 pins (layer 25, key TRAVELTIME); awaits the attribute-map fix and v2 canary
--   not registered  water.water_source_area: features at 1/6 pins (layer 16, key SYS_NAME); awaits the attribute-map fix and v2 canary
--   not registered  water.watershed_huc11: features at 6/6 pins (layer 17, keys W_NAME/HUC11); awaits the attribute-map fix and v2 canary
--   not registered  water.subwatershed_huc14: features at 6/6 pins (layer 22, keys SW_NAME/HUC14); awaits the attribute-map fix and v2 canary
--   not registered  land.open_space_encumbrance: features at 2/6 pins (layer 65, key ENCUMBRANCE_STATUS); awaits the attribute-map fix and v2 canary
--   not registered  land.wetland_mitigation_service_area: features at 6/6 pins (layer 70, key SERVICEAREA); awaits the attribute-map fix and v2 canary
--   not registered  geology.surficial_aquifer: no features at any of the 6 sampled pins (layer 23); not mapped, needs pins that intersect the layer
--   not registered  water.wellhead_noncommunity_tier: no features at any of the 6 sampled pins (layer 26); not mapped, needs pins that intersect the layer
--   not registered  water.wellhead_noncommunity_travel_time: no features at any of the 6 sampled pins (layer 26); not mapped, needs pins that intersect the layer
--   not registered  water.groundwater_treatment_source_area: no features at any of the 6 sampled pins (layer 27); not mapped, needs pins that intersect the layer

insert into public.data_center_provider_coverage
  (marker_id,scopes,provider_key,value_status,source_keys,last_verified_at,notes,
   provider_kind,source_fields,calculation_key,freshness_seconds,cache_policy,bulk_capable)
values
  ('geology.abandoned_mine_within_1km',array['property']::text[],'njdep_geology_spatial_v1','live',array['njdep-geology-live']::text[],'2026-09-29 17:37:04.188048+00'::timestamptz,
   'Resolver evidence: provider release canary catalog_njdep_layers_v1 (public.watchdog_test_auth_events id 76, 2026-09-29 17:37:04 UTC) ran production workbench-hydrate v91 (Watchdog provider-family resolver v19, spatial-preflight-v11-dca-community-access) as a short-lived bootstrap developer user; the resolver returned state available on 6 of 6 sampled pins in 6 counties, positive on 2; observed 0502_1056_2 (Cape May) = false; 1420_1003_1 (Morris) = true; 1906_1301_19 (Sussex) = true; 0202_1_1 (Bergen) = false; 0336_1.01_1 (Burlington) = false; 0113_2802_10 (Atlantic) = false. Layer confirmed from the canary''s live layer metadata: NJDEP Geology/MapServer/0 "Abandoned Mines" (point), within 1 km. false is an observed negative, not a missing value.',
   'authoritative_spatial_reference',array['Geology/MapServer/0','within_1km']::text[],'spatial-preflight-v11-dca-community-access',21600,'external_live',false),
  ('geology.landslide_within_1km',array['property']::text[],'njdep_geology_spatial_v1','live',array['njdep-geology-live']::text[],'2026-09-29 17:37:04.188048+00'::timestamptz,
   'Resolver evidence: provider release canary catalog_njdep_layers_v1 (public.watchdog_test_auth_events id 76, 2026-09-29 17:37:04 UTC) ran production workbench-hydrate v91 (Watchdog provider-family resolver v19, spatial-preflight-v11-dca-community-access) as a short-lived bootstrap developer user; the resolver returned state available on 6 of 6 sampled pins in 6 counties, positive on 1; observed 0502_1056_2 (Cape May) = false; 1420_1003_1 (Morris) = false; 1906_1301_19 (Sussex) = false; 0202_1_1 (Bergen) = true; 0336_1.01_1 (Burlington) = false; 0113_2802_10 (Atlantic) = false. Layer confirmed from the canary''s live layer metadata: NJDEP Geology/MapServer/1 "Landslides" (point), within 1 km. false is an observed negative, not a missing value.',
   'authoritative_spatial_reference',array['Geology/MapServer/1','within_1km']::text[],'spatial-preflight-v11-dca-community-access',21600,'external_live',false),
  ('geology.fault_within_500m',array['property']::text[],'njdep_geology_spatial_v1','live',array['njdep-geology-live']::text[],'2026-09-29 17:37:04.188048+00'::timestamptz,
   'Resolver evidence: provider release canary catalog_njdep_layers_v1 (public.watchdog_test_auth_events id 76, 2026-09-29 17:37:04 UTC) ran production workbench-hydrate v91 (Watchdog provider-family resolver v19, spatial-preflight-v11-dca-community-access) as a short-lived bootstrap developer user; the resolver returned state available on 6 of 6 sampled pins in 6 counties, positive on 1; observed 0502_1056_2 (Cape May) = 0; 1420_1003_1 (Morris) = 0; 1906_1301_19 (Sussex) = 1; 0202_1_1 (Bergen) = 0; 0336_1.01_1 (Burlington) = 0; 0113_2802_10 (Atlantic) = 0. Layer confirmed from the canary''s live layer metadata: NJDEP Geology/MapServer/6 "Faults" (polyline), within 500 m. Values are feature counts; the resolver requests at most 10 features, so 10 means 10 or more.',
   'authoritative_spatial_reference',array['Geology/MapServer/6','within_500m']::text[],'spatial-preflight-v11-dca-community-access',21600,'external_live',false),
  ('geology.quarry_within_1500m',array['property']::text[],'njdep_geology_spatial_v1','live',array['njdep-geology-live']::text[],'2026-09-29 17:37:04.188048+00'::timestamptz,
   'Resolver evidence: provider release canary catalog_njdep_layers_v1 (public.watchdog_test_auth_events id 76, 2026-09-29 17:37:04 UTC) ran production workbench-hydrate v91 (Watchdog provider-family resolver v19, spatial-preflight-v11-dca-community-access) as a short-lived bootstrap developer user; the resolver returned state available on 6 of 6 sampled pins in 6 counties, positive on 1; observed 0502_1056_2 (Cape May) = 0; 1420_1003_1 (Morris) = 1; 1906_1301_19 (Sussex) = 0; 0202_1_1 (Bergen) = 0; 0336_1.01_1 (Burlington) = 0; 0113_2802_10 (Atlantic) = 0. Layer confirmed from the canary''s live layer metadata: NJDEP Geology/MapServer/3 "Quarries (Sand and Gravel)" (point), within 1500 m. Values are feature counts; the resolver requests at most 10 features, so 10 means 10 or more.',
   'authoritative_spatial_reference',array['Geology/MapServer/3','within_1500m']::text[],'spatial-preflight-v11-dca-community-access',21600,'external_live',false),
  ('water.category1_water_within_500m',array['property']::text[],'njdep_hydro_spatial_v1','live',array['njdep-hydro-live']::text[],'2026-09-29 17:37:04.188048+00'::timestamptz,
   'Resolver evidence: provider release canary catalog_njdep_layers_v1 (public.watchdog_test_auth_events id 76, 2026-09-29 17:37:04 UTC) ran production workbench-hydrate v91 (Watchdog provider-family resolver v19, spatial-preflight-v11-dca-community-access) as a short-lived bootstrap developer user; the resolver returned state available on 6 of 6 sampled pins in 6 counties, positive on 2; observed 0502_1056_2 (Cape May) = 0; 1420_1003_1 (Morris) = 4; 1906_1301_19 (Sussex) = 10; 0202_1_1 (Bergen) = 0; 0336_1.01_1 (Burlington) = 0; 0113_2802_10 (Atlantic) = 0. Layer confirmed from the canary''s live layer metadata: NJDEP Hydrography/MapServer/6 "Category 1 Waters" (polyline), within 500 m. Values are feature counts; the resolver requests at most 10 features, so 10 means 10 or more.',
   'authoritative_spatial_reference',array['Hydrography/MapServer/6','within_500m']::text[],'spatial-preflight-v11-dca-community-access',21600,'external_live',false),
  ('water.surface_spring_within_1km',array['property']::text[],'njdep_hydro_spatial_v1','live',array['njdep-hydro-live']::text[],'2026-09-29 17:37:04.188048+00'::timestamptz,
   'Resolver evidence: provider release canary catalog_njdep_layers_v1 (public.watchdog_test_auth_events id 76, 2026-09-29 17:37:04 UTC) ran production workbench-hydrate v91 (Watchdog provider-family resolver v19, spatial-preflight-v11-dca-community-access) as a short-lived bootstrap developer user; the resolver returned state available on 6 of 6 sampled pins in 6 counties, positive on 1; observed 0502_1056_2 (Cape May) = false; 1420_1003_1 (Morris) = true; 1906_1301_19 (Sussex) = false; 0202_1_1 (Bergen) = false; 0336_1.01_1 (Burlington) = false; 0113_2802_10 (Atlantic) = false. Layer confirmed from the canary''s live layer metadata: NJDEP Hydrography/MapServer/34 "Surface Water Springs" (point), within 1 km. false is an observed negative, not a missing value.',
   'authoritative_spatial_reference',array['Hydrography/MapServer/34','within_1km']::text[],'spatial-preflight-v11-dca-community-access',21600,'external_live',false),
  ('land.open_space_hit',array['property']::text[],'njdep_land_spatial_v1','live',array['njdep-land-live']::text[],'2026-09-29 17:37:04.188048+00'::timestamptz,
   'Resolver evidence: provider release canary catalog_njdep_layers_v1 (public.watchdog_test_auth_events id 76, 2026-09-29 17:37:04 UTC) ran production workbench-hydrate v91 (Watchdog provider-family resolver v19, spatial-preflight-v11-dca-community-access) as a short-lived bootstrap developer user; the resolver returned state available on 6 of 6 sampled pins in 6 counties, positive on 2; observed 0502_1056_2 (Cape May) = false; 1420_1003_1 (Morris) = false; 1906_1301_19 (Sussex) = false; 0202_1_1 (Bergen) = true; 0336_1.01_1 (Burlington) = true; 0113_2802_10 (Atlantic) = false. Layer confirmed from the canary''s live layer metadata: NJDEP Land/MapServer/65 "Open Space" (polygon), representative parcel point intersects. false is an observed negative, not a missing value.',
   'authoritative_spatial_reference',array['Land/MapServer/65','representative_parcel_point_intersects']::text[],'spatial-preflight-v11-dca-community-access',21600,'external_live',false),
  ('land.open_space_within_500m',array['property']::text[],'njdep_land_spatial_v1','live',array['njdep-land-live']::text[],'2026-09-29 17:37:04.188048+00'::timestamptz,
   'Resolver evidence: provider release canary catalog_njdep_layers_v1 (public.watchdog_test_auth_events id 76, 2026-09-29 17:37:04 UTC) ran production workbench-hydrate v91 (Watchdog provider-family resolver v19, spatial-preflight-v11-dca-community-access) as a short-lived bootstrap developer user; the resolver returned state available on 6 of 6 sampled pins in 6 counties, positive on 6; observed 0502_1056_2 (Cape May) = 10; 1420_1003_1 (Morris) = 6; 1906_1301_19 (Sussex) = 6; 0202_1_1 (Bergen) = 8; 0336_1.01_1 (Burlington) = 9; 0113_2802_10 (Atlantic) = 2. Layer confirmed from the canary''s live layer metadata: NJDEP Land/MapServer/65 "Open Space" (polygon), within 500 m. Values are feature counts; the resolver requests at most 10 features, so 10 means 10 or more.',
   'authoritative_spatial_reference',array['Land/MapServer/65','within_500m']::text[],'spatial-preflight-v11-dca-community-access',21600,'external_live',false),
  ('land.historic_property_hit',array['property']::text[],'njdep_land_spatial_v1','live',array['njdep-land-live']::text[],'2026-09-29 17:37:04.188048+00'::timestamptz,
   'Resolver evidence: provider release canary catalog_njdep_layers_v1 (public.watchdog_test_auth_events id 76, 2026-09-29 17:37:04 UTC) ran production workbench-hydrate v91 (Watchdog provider-family resolver v19, spatial-preflight-v11-dca-community-access) as a short-lived bootstrap developer user; the resolver returned state available on 6 of 6 sampled pins in 6 counties, positive on 3; observed 0502_1056_2 (Cape May) = true; 1420_1003_1 (Morris) = false; 1906_1301_19 (Sussex) = true; 0202_1_1 (Bergen) = false; 0336_1.01_1 (Burlington) = false; 0113_2802_10 (Atlantic) = true. Layer confirmed from the canary''s live layer metadata: NJDEP Land/MapServer/55 "Historic Properties" (polygon), representative parcel point intersects. false is an observed negative, not a missing value.',
   'authoritative_spatial_reference',array['Land/MapServer/55','representative_parcel_point_intersects']::text[],'spatial-preflight-v11-dca-community-access',21600,'external_live',false),
  ('land.historic_district_hit',array['property']::text[],'njdep_land_spatial_v1','live',array['njdep-land-live']::text[],'2026-09-29 17:37:04.188048+00'::timestamptz,
   'Resolver evidence: provider release canary catalog_njdep_layers_v1 (public.watchdog_test_auth_events id 76, 2026-09-29 17:37:04 UTC) ran production workbench-hydrate v91 (Watchdog provider-family resolver v19, spatial-preflight-v11-dca-community-access) as a short-lived bootstrap developer user; the resolver returned state available on 6 of 6 sampled pins in 6 counties, positive on 4; observed 0502_1056_2 (Cape May) = true; 1420_1003_1 (Morris) = false; 1906_1301_19 (Sussex) = true; 0202_1_1 (Bergen) = true; 0336_1.01_1 (Burlington) = false; 0113_2802_10 (Atlantic) = true. Layer confirmed from the canary''s live layer metadata: NJDEP Land/MapServer/57 "Historic Districts" (polygon), representative parcel point intersects. false is an observed negative, not a missing value.',
   'authoritative_spatial_reference',array['Land/MapServer/57','representative_parcel_point_intersects']::text[],'spatial-preflight-v11-dca-community-access',21600,'external_live',false),
  ('land.archaeological_grid_hit',array['property']::text[],'njdep_land_spatial_v1','live',array['njdep-land-live']::text[],'2026-09-29 17:37:04.188048+00'::timestamptz,
   'Resolver evidence: provider release canary catalog_njdep_layers_v1 (public.watchdog_test_auth_events id 76, 2026-09-29 17:37:04 UTC) ran production workbench-hydrate v91 (Watchdog provider-family resolver v19, spatial-preflight-v11-dca-community-access) as a short-lived bootstrap developer user; the resolver returned state available on 6 of 6 sampled pins in 6 counties, positive on 3; observed 0502_1056_2 (Cape May) = true; 1420_1003_1 (Morris) = false; 1906_1301_19 (Sussex) = true; 0202_1_1 (Bergen) = false; 0336_1.01_1 (Burlington) = false; 0113_2802_10 (Atlantic) = true. Layer confirmed from the canary''s live layer metadata: NJDEP Land/MapServer/56 "Archaeological Site Grid" (polygon), representative parcel point intersects. false is an observed negative, not a missing value.',
   'authoritative_spatial_reference',array['Land/MapServer/56','representative_parcel_point_intersects']::text[],'spatial-preflight-v11-dca-community-access',21600,'external_live',false),
  ('land.natural_area_preserve_hit',array['property']::text[],'njdep_land_spatial_v1','live',array['njdep-land-live']::text[],'2026-09-29 17:37:04.188048+00'::timestamptz,
   'Resolver evidence: provider release canary catalog_njdep_layers_v1 (public.watchdog_test_auth_events id 76, 2026-09-29 17:37:04 UTC) ran production workbench-hydrate v91 (Watchdog provider-family resolver v19, spatial-preflight-v11-dca-community-access) as a short-lived bootstrap developer user; the resolver returned state available on 6 of 6 sampled pins in 6 counties, positive on 1; observed 0502_1056_2 (Cape May) = false; 1420_1003_1 (Morris) = false; 1906_1301_19 (Sussex) = false; 0202_1_1 (Bergen) = false; 0336_1.01_1 (Burlington) = true; 0113_2802_10 (Atlantic) = false. Layer confirmed from the canary''s live layer metadata: NJDEP Land/MapServer/80 "State Natural Areas Preserve Boundaries" (polygon), representative parcel point intersects. false is an observed negative, not a missing value.',
   'authoritative_spatial_reference',array['Land/MapServer/80','representative_parcel_point_intersects']::text[],'spatial-preflight-v11-dca-community-access',21600,'external_live',false)
on conflict (marker_id) do update set
  scopes=excluded.scopes,provider_key=excluded.provider_key,value_status=excluded.value_status,
  source_keys=excluded.source_keys,last_verified_at=excluded.last_verified_at,notes=excluded.notes,
  provider_kind=excluded.provider_kind,source_fields=excluded.source_fields,
  calculation_key=excluded.calculation_key,freshness_seconds=excluded.freshness_seconds,
  cache_policy=excluded.cache_policy,bulk_capable=excluded.bulk_capable;
