-- NJW-302: owner-only saved ANCHOR estimates for the Watchdog homeowner funnel.
-- The persisted benefit amount and qualification state are generated by Postgres
-- from bounded 2025 estimator inputs. Sensitive application answers remain in the
-- separate zero-knowledge application vault introduced under NJW-303.

create table if not exists public.anchor_estimates (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  tax_year smallint not null default 2025 check (tax_year = 2025),
  program text not null default 'ANCHOR' check (program = 'ANCHOR'),
  rules_version text not null default '2025.1' check (rules_version = '2025.1'),
  estimate_source text not null check (estimate_source in ('njptr_verified_handoff','watchdog_quick_estimator')),
  tenure text not null check (tenure in ('own','rent')),
  income_band text not null check (income_band in ('low','mid','high')),
  age_65_plus boolean not null,
  primary_residence boolean not null,
  property_taxes_paid boolean,
  qualifies boolean generated always as (
    income_band <> 'high'
    and primary_residence
    and not (tenure = 'rent' and income_band = 'mid')
    and not (tenure = 'own' and coalesce(property_taxes_paid, false) = false)
  ) stored,
  estimated_amount integer generated always as (
    case
      when income_band <> 'high'
       and primary_residence
       and not (tenure = 'rent' and income_band = 'mid')
       and not (tenure = 'own' and coalesce(property_taxes_paid, false) = false)
      then case
        when tenure = 'own' then case when income_band = 'low' then 1500 else 1000 end
        else case when age_65_plus then 700 else 450 end
      end
      else 0
    end
  ) stored,
  property_address text not null check (length(btrim(property_address)) between 3 and 300),
  property_pams_pin text,
  property_town text,
  property_county text,
  property_zip text,
  property_block text,
  property_lot text,
  property_qualifier text,
  assessed_value bigint,
  prior_year_tax numeric,
  application_id uuid,
  estimated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, user_id),
  unique (user_id, tax_year, program, property_address),
  constraint anchor_estimates_application_owner_fk
    foreign key (application_id, user_id)
    references public.anchor_applications(id, user_id)
    on delete set null
);

comment on table public.anchor_estimates is
  'Owner-only saved Watchdog ANCHOR estimates. Benefit amount and qualification are generated from bounded 2025 estimator inputs; sensitive application answers remain in the separate zero-knowledge application vault.';
comment on column public.anchor_estimates.estimated_amount is
  'Database-generated informational 2025 ANCHOR estimate. Not a State of New Jersey determination.';

create index if not exists anchor_estimates_user_updated_idx
  on public.anchor_estimates(user_id, updated_at desc);
create index if not exists anchor_estimates_application_idx
  on public.anchor_estimates(application_id)
  where application_id is not null;

alter table public.anchor_estimates enable row level security;
revoke all on table public.anchor_estimates from anon, authenticated;
grant select, insert, update, delete on table public.anchor_estimates to authenticated;

drop policy if exists "anchor_estimates_owner_select" on public.anchor_estimates;
create policy "anchor_estimates_owner_select"
on public.anchor_estimates for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "anchor_estimates_owner_insert" on public.anchor_estimates;
create policy "anchor_estimates_owner_insert"
on public.anchor_estimates for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "anchor_estimates_owner_update" on public.anchor_estimates;
create policy "anchor_estimates_owner_update"
on public.anchor_estimates for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "anchor_estimates_owner_delete" on public.anchor_estimates;
create policy "anchor_estimates_owner_delete"
on public.anchor_estimates for delete to authenticated
using ((select auth.uid()) = user_id);

drop trigger if exists anchor_estimates_touch_updated_at on public.anchor_estimates;
create trigger anchor_estimates_touch_updated_at
before update on public.anchor_estimates
for each row execute function public.touch_updated_at();
