begin;

insert into public.derived_formula_registry(
  marker_id, engine_version, formula, dependencies, confidence, status, explanation, operation, config
)
values
('watchdog.internal.landuse_wetlands_group_v1','watchdog-derived-v16-chapter123-fields','any(wetlands_2012, priority_wetland, wetlands_loi)',array['preflight.wetlands_2012_hit','preflight.epa_priority_wetland_hit','land.wetlands_loi_hit'],'medium','live','Internal governed family helper: positive only when at least one certified wetlands screen is active; zero only after the full defined family is checked.','signal_density','{"require_all":true}'::jsonb),
('watchdog.internal.landuse_historic_group_v1','watchdog-derived-v16-chapter123-fields','any(historic_property, historic_district, archaeological_grid)',array['land.historic_property_hit','land.historic_district_hit','land.archaeological_grid_hit'],'medium','live','Internal governed family helper for certified historic-resource mapping.','signal_density','{"require_all":true}'::jsonb),
('watchdog.internal.offer_flood_group_v1','watchdog-derived-v16-chapter123-fields','any(FEMA_flood_zone, tidal_CAFE)',array['preflight.fema_flood_zone','preflight.tidal_cafe_hit'],'medium','live','Internal governed offer-review flood family helper.','signal_density','{"require_all":true,"flood_dep":"preflight.fema_flood_zone"}'::jsonb),
('watchdog.internal.offer_environment_group_v1','watchdog-derived-v16-chapter123-fields','any(deed_notice, CEA, contaminated_site_500m, UST_250m)',array['preflight.deed_notice_hit','preflight.cea_hit','preflight.contaminated_site_500m','preflight.ust_250m'],'medium','live','Internal governed offer-review environmental family helper.','signal_density','{"require_all":true}'::jsonb),
('watchdog.internal.offer_title_group_v1','watchdog-derived-v16-chapter123-fields','any(tidelands_reference, open_space_encumbrance, wetlands_LOI)',array['preflight.tidelands_reference_hit','land.open_space_encumbrance','land.wetlands_loi_hit'],'medium','live','Internal governed offer-review title/public-land-reference family helper; not a title opinion.','signal_density','{"require_all":true}'::jsonb),
('watchdog.internal.preconstruction_water_group_v1','watchdog-derived-v16-chapter123-fields','any(category1_water_500m, flood_profile_500m, flood_plan_locator, surface_spring_1km)',array['water.category1_water_within_500m','water.flood_profile_within_500m','water.flood_plan_locator_hit','water.surface_spring_within_1km'],'medium','live','Internal governed water-screen family helper for preconstruction questions.','signal_density','{"require_all":true}'::jsonb),
('watchdog.internal.preconstruction_geology_group_v1','watchdog-derived-v16-chapter123-fields','any(historic_fill, acid_soil, bedrock_outcrop, fault_500m, landslide_1km, abandoned_mine_1km, quarry_1500m)',array['geology.historic_fill_hit','geology.acid_producing_soil_hit','geology.bedrock_outcrop_hit','geology.fault_within_500m','geology.landslide_within_1km','geology.abandoned_mine_within_1km','geology.quarry_within_1500m'],'medium','live','Internal governed geology-screen family helper for preconstruction questions.','signal_density','{"require_all":true}'::jsonb),
('watchdog.internal.insurance_flood_group_v1','watchdog-derived-v16-chapter123-fields','any(FEMA_flood_zone, tidal_CAFE, flood_profile_500m, flood_plan_locator)',array['preflight.fema_flood_zone','preflight.tidal_cafe_hit','water.flood_profile_within_500m','water.flood_plan_locator_hit'],'medium','live','Internal governed mapped flood-context family helper; not an insurance determination.','signal_density','{"require_all":true,"flood_dep":"preflight.fema_flood_zone"}'::jsonb),
('watchdog.internal.insurance_contaminated_group_v1','watchdog-derived-v16-chapter123-fields','any(contaminated_site_500m, UST_250m, deed_notice, CEA)',array['preflight.contaminated_site_500m','preflight.ust_250m','preflight.deed_notice_hit','preflight.cea_hit'],'medium','live','Internal governed environmental-site family helper for physical-risk context.','signal_density','{"require_all":true}'::jsonb),
('watchdog.internal.insurance_water_group_v1','watchdog-derived-v16-chapter123-fields','any(category1_water_500m, flood_profile_500m, flood_plan_locator, surface_spring_1km)',array['water.category1_water_within_500m','water.flood_profile_within_500m','water.flood_plan_locator_hit','water.surface_spring_within_1km'],'medium','live','Internal governed water-context family helper for physical-risk context.','signal_density','{"require_all":true}'::jsonb),
('watchdog.constraint_stack_count','watchdog-derived-v16-chapter123-fields','count(active FEMA flood, tidal CAFE, wetlands 2012, EPA priority wetland, Highlands, Pinelands screens)',array['preflight.fema_flood_zone','preflight.tidal_cafe_hit','preflight.wetlands_2012_hit','preflight.epa_priority_wetland_hit','preflight.highlands_hit','preflight.pinelands_hit'],'medium','live','Counts active members of the same six certified mapped development-screen layers used by Development Constraint Density. It is a screen count, not a feasibility finding.','signal_count','{"require_all":true,"flood_dep":"preflight.fema_flood_zone"}'::jsonb),
('watchdog.attorney.land_use_exception_stack','watchdog-derived-v16-chapter123-fields','count(wetlands family, historic-resource family, open-space intersection, tidelands reference, Highlands, Pinelands)',array['watchdog.internal.landuse_wetlands_group_v1','watchdog.internal.landuse_historic_group_v1','land.open_space_hit','preflight.tidelands_reference_hit','preflight.highlands_hit','preflight.pinelands_hit'],'medium','live','Counts six explicitly defined public mapping contexts for attorney review. A count is not a legal exception or land-use determination.','signal_count','{"require_all":true}'::jsonb),
('watchdog.attorney.public_notice_density','watchdog-derived-v16-chapter123-fields','count(deed notice, CEA, historic-resource family, open-space intersection, tidelands reference)',array['preflight.deed_notice_hit','preflight.cea_hit','watchdog.internal.landuse_historic_group_v1','land.open_space_hit','preflight.tidelands_reference_hit'],'medium','live','Counts five explicitly defined public-record notice/mapping contexts for review; it does not state title or legal effect.','signal_count','{"require_all":true}'::jsonb),
('watchdog.title.title_land_constraint_mix','watchdog-derived-v16-chapter123-fields','count(tidelands reference, open-space intersection, historic-resource family, wetlands LOI)',array['preflight.tidelands_reference_hit','land.open_space_hit','watchdog.internal.landuse_historic_group_v1','land.wetlands_loi_hit'],'medium','live','Counts four explicitly defined mapped land/title-review contexts. It is not a title opinion.','signal_count','{"require_all":true}'::jsonb),
('watchdog.agent.offer_question_density','watchdog-derived-v16-chapter123-fields','count(open-permit question, flood family, environmental family, title/public-land-reference family)',array['preflight.open_permit_count','watchdog.internal.offer_flood_group_v1','watchdog.internal.offer_environment_group_v1','watchdog.internal.offer_title_group_v1'],'medium','live','Counts four explicitly defined pre-offer public-record question families. It does not count defects or predict deal outcomes.','signal_count','{"require_all":true}'::jsonb),
('watchdog.contractor.site_preflight_completeness','watchdog-derived-v16-chapter123-fields','checked(14 defined public site-screen inputs) / 14 * 100',array['preflight.fema_flood_zone','preflight.tidal_cafe_hit','preflight.wetlands_2012_hit','preflight.epa_priority_wetland_hit','preflight.tidelands_reference_hit','preflight.deed_notice_hit','preflight.cea_hit','preflight.highlands_hit','preflight.pinelands_hit','preflight.permit_count','preflight.open_permit_count','water.category1_water_within_500m','geology.soil_mapping_hit','land.open_space_hit'],'medium','live','Completeness of a fixed 14-field governed public site-screen set. No missing source is filled by assumption and no score states buildability.','completeness','{"mode":"checked","requirements":["preflight.fema_flood_zone","preflight.tidal_cafe_hit","preflight.wetlands_2012_hit","preflight.epa_priority_wetland_hit","preflight.tidelands_reference_hit","preflight.deed_notice_hit","preflight.cea_hit","preflight.highlands_hit","preflight.pinelands_hit","preflight.permit_count","preflight.open_permit_count","water.category1_water_within_500m","geology.soil_mapping_hit","land.open_space_hit"]}'::jsonb),
('watchdog.contractor.preconstruction_question_set','watchdog-derived-v16-chapter123-fields','count(water family, geology family, wetlands family, historic-resource family, permit-history question)',array['watchdog.internal.preconstruction_water_group_v1','watchdog.internal.preconstruction_geology_group_v1','watchdog.internal.landuse_wetlands_group_v1','watchdog.internal.landuse_historic_group_v1','preflight.permit_count'],'medium','live','Counts five explicitly defined public-record question families before construction review; it is not a site-condition or permitting conclusion.','signal_count','{"require_all":true}'::jsonb),
('watchdog.insurance.mapped_hazard_overlap','watchdog-derived-v16-chapter123-fields','count(flood family, wetlands family, contaminated/environmental family, geology family, water-context family)',array['watchdog.internal.insurance_flood_group_v1','watchdog.internal.landuse_wetlands_group_v1','watchdog.internal.insurance_contaminated_group_v1','watchdog.internal.preconstruction_geology_group_v1','watchdog.internal.insurance_water_group_v1'],'medium','live','Counts five explicitly defined public mapped-context families. It is not an insurance eligibility, pricing, or hazard determination.','signal_count','{"require_all":true}'::jsonb),
('watchdog.insurance.physical_record_coverage','watchdog-derived-v16-chapter123-fields','checked(16 defined public physical-risk inputs) / 16 * 100',array['preflight.fema_flood_zone','preflight.tidal_cafe_hit','preflight.wetlands_2012_hit','preflight.epa_priority_wetland_hit','preflight.contaminated_site_500m','preflight.ust_250m','preflight.deed_notice_hit','preflight.cea_hit','geology.historic_fill_hit','geology.acid_producing_soil_hit','geology.bedrock_outcrop_hit','geology.fault_within_500m','geology.landslide_within_1km','water.category1_water_within_500m','water.flood_profile_within_500m','land.historic_property_hit'],'medium','live','Completeness of a fixed 16-field governed public physical-risk source set. It measures source coverage only.','completeness','{"mode":"checked","requirements":["preflight.fema_flood_zone","preflight.tidal_cafe_hit","preflight.wetlands_2012_hit","preflight.epa_priority_wetland_hit","preflight.contaminated_site_500m","preflight.ust_250m","preflight.deed_notice_hit","preflight.cea_hit","geology.historic_fill_hit","geology.acid_producing_soil_hit","geology.bedrock_outcrop_hit","geology.fault_within_500m","geology.landslide_within_1km","water.category1_water_within_500m","water.flood_profile_within_500m","land.historic_property_hit"]}'::jsonb),
('watchdog.municipal.municipal_source_coverage','watchdog-derived-v16-chapter123-fields','checked(12 defined municipal source fields) / 12 * 100',array['budget.pressure_score','budget.levy_base_gap','njplus.nj-dca-neighborhood-trends.neighborhood_trend_year','njplus.nj-dca-neighborhood-trends.household_income','njplus.nj-dca-neighborhood-trends.population_change','njplus.nj-dca-neighborhood-trends.home_value_change','njplus.nj-dca-municipal-housing-profile.housing_stock','njplus.nj-dca-municipal-housing-profile.vacancy_rate','njplus.nj-dca-municipal-housing-profile.median_gross_rent','njplus.nj-dca-municipal-housing-profile.median_home_value','njplus.nj-dca-development-trends.housing_units_authorized','njplus.nj-dca-development-trends.construction_cost_authorized'],'medium','live','Completeness of a fixed 12-field governed municipal snapshot spanning fiscal, neighborhood, housing, and development sources.','completeness','{"mode":"checked","requirements":["budget.pressure_score","budget.levy_base_gap","njplus.nj-dca-neighborhood-trends.neighborhood_trend_year","njplus.nj-dca-neighborhood-trends.household_income","njplus.nj-dca-neighborhood-trends.population_change","njplus.nj-dca-neighborhood-trends.home_value_change","njplus.nj-dca-municipal-housing-profile.housing_stock","njplus.nj-dca-municipal-housing-profile.vacancy_rate","njplus.nj-dca-municipal-housing-profile.median_gross_rent","njplus.nj-dca-municipal-housing-profile.median_home_value","njplus.nj-dca-development-trends.housing_units_authorized","njplus.nj-dca-development-trends.construction_cost_authorized"]}'::jsonb),
('watchdog.njplus.municipal_housing_evidence_depth','watchdog-derived-v16-chapter123-fields','checked(8 certified municipal housing profile fields) / 8 * 100',array['njplus.nj-dca-municipal-housing-profile.housing_stock','njplus.nj-dca-municipal-housing-profile.owner_occupied_share','njplus.nj-dca-municipal-housing-profile.renter_occupied_share','njplus.nj-dca-municipal-housing-profile.vacancy_rate','njplus.nj-dca-municipal-housing-profile.median_gross_rent','njplus.nj-dca-municipal-housing-profile.median_home_value','njplus.nj-dca-municipal-housing-profile.housing_cost_burden_share','njplus.nj-dca-municipal-housing-profile.household_growth'],'high','live','Coverage of the eight currently certified municipality-level housing-profile facts/calculations. Blocked eviction and housing-production semantics are intentionally excluded rather than assumed.','completeness','{"mode":"checked","requirements":["njplus.nj-dca-municipal-housing-profile.housing_stock","njplus.nj-dca-municipal-housing-profile.owner_occupied_share","njplus.nj-dca-municipal-housing-profile.renter_occupied_share","njplus.nj-dca-municipal-housing-profile.vacancy_rate","njplus.nj-dca-municipal-housing-profile.median_gross_rent","njplus.nj-dca-municipal-housing-profile.median_home_value","njplus.nj-dca-municipal-housing-profile.housing_cost_burden_share","njplus.nj-dca-municipal-housing-profile.household_growth"]}'::jsonb),
('watchdog.njplus.neighborhood_trend_freshness','watchdog-derived-v16-chapter123-fields','current_year - neighborhood_trend_year',array['njplus.nj-dca-neighborhood-trends.neighborhood_trend_year'],'high','live','Elapsed whole calendar years since the published neighborhood-trend vintage. Lower is fresher; no quality judgment is inferred.','year_delta','{"dep":"njplus.nj-dca-neighborhood-trends.neighborhood_trend_year"}'::jsonb),
('watchdog.title.municipal_search_scope','watchdog-derived-v16-chapter123-fields','checked(10 defined parcel/municipal public-search inputs) / 10 * 100',array['property.municipality','property.block','property.lot','property.assessed_value','property.annual_tax','preflight.permit_count','preflight.open_permit_count','njplus.nj-dca-zoning-directory.zoning_map_url','njplus.nj-dca-zoning-directory.zoning_ordinance_url','njplus.nj-dca-zoning-directory.municipal_zoning_portal'],'medium','live','Completeness of a fixed 10-field public municipal-search starting set. It does not state title quality, municipal clearance, permitted use, or legal sufficiency.','completeness','{"mode":"checked","requirements":["property.municipality","property.block","property.lot","property.assessed_value","property.annual_tax","preflight.permit_count","preflight.open_permit_count","njplus.nj-dca-zoning-directory.zoning_map_url","njplus.nj-dca-zoning-directory.zoning_ordinance_url","njplus.nj-dca-zoning-directory.municipal_zoning_portal"]}'::jsonb)
on conflict (marker_id) do update
set engine_version=excluded.engine_version,
    formula=excluded.formula,
    dependencies=excluded.dependencies,
    confidence=excluded.confidence,
    status=excluded.status,
    explanation=excluded.explanation,
    operation=excluded.operation,
    config=excluded.config,
    updated_at=now();

commit;
