create table if not exists public.watchdog_test_accounts (
  user_id uuid primary key references auth.users(id) on delete cascade,
  label text not null default 'Watchdog E2E Sandbox',
  created_at timestamptz not null default now(),
  last_bootstrap_at timestamptz,
  disabled_at timestamptz,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.watchdog_test_bootstrap_tokens (
  id uuid primary key default gen_random_uuid(),
  token_hash text not null unique,
  desired_email text not null,
  redirect_to text not null default 'https://njpropertytaxrelief.com/property/dashboard.html',
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  used_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  constraint watchdog_test_bootstrap_tokens_expiry_check check (expires_at > created_at),
  constraint watchdog_test_bootstrap_tokens_email_check check (desired_email ~* '^[^@[:space:]]+@[^@[:space:]]+\\.[^@[:space:]]+$')
);

create index if not exists watchdog_test_bootstrap_tokens_live_idx
  on public.watchdog_test_bootstrap_tokens(expires_at)
  where used_at is null;

create table if not exists public.watchdog_test_auth_events (
  id bigint generated by default as identity primary key,
  token_id uuid references public.watchdog_test_bootstrap_tokens(id) on delete set null,
  user_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  created_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

alter table public.watchdog_test_accounts enable row level security;
alter table public.watchdog_test_bootstrap_tokens enable row level security;
alter table public.watchdog_test_auth_events enable row level security;

revoke all on public.watchdog_test_accounts from public, anon, authenticated;
revoke all on public.watchdog_test_bootstrap_tokens from public, anon, authenticated;
revoke all on public.watchdog_test_auth_events from public, anon, authenticated;
revoke all on sequence public.watchdog_test_auth_events_id_seq from public, anon, authenticated;

create or replace function public.is_watchdog_test_account(p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists(
    select 1
    from public.watchdog_test_accounts t
    where t.user_id = p_user_id
      and t.disabled_at is null
  );
$$;

revoke all on function public.is_watchdog_test_account(uuid) from public, anon;
grant execute on function public.is_watchdog_test_account(uuid) to authenticated;
