-- Promote authoritative raw municipal/debt and appeal fields already present in the static marker registry and live source JSON.
insert into public.data_center_provider_coverage(marker_id,scopes,provider_key,value_status,source_keys,last_verified_at,notes,provider_kind,source_fields,calculation_key,freshness_seconds,cache_policy,bulk_capable) values
('budget.debt_service_share',array['municipality'],'workbench-hydrate','live',array['nj-dca-budget'],now(),'NJ DCA User-Friendly Budget debt payment divided by current appropriation.','authoritative_reference',array['budget.debt_service_share'],'nj-dca-budget',86400,'refresh_on_demand',true),
('budget.net_debt_pct',array['municipality'],'workbench-hydrate','live',array['nj-dca-budget'],now(),'NJ DCA User-Friendly Budget net debt percentage.','authoritative_reference',array['budget.net_debt_pct'],'nj-dca-budget',86400,'refresh_on_demand',true),
('appeals.latest_total',array['county'],'workbench-hydrate','live',array['nj-tax-court-appeals'],now(),'Latest published county property-tax appeal filings from NJ Division of Taxation summary.','authoritative_reference',array['latest.total'],'nj-tax-court-appeals',86400,'refresh_on_demand',true),
('appeals.latest_assessed_appealed',array['county'],'workbench-hydrate','live',array['nj-tax-court-appeals'],now(),'Latest published county assessed value under appeal.','authoritative_reference',array['latest.assessed_appealed'],'nj-tax-court-appeals',86400,'refresh_on_demand',true),
('appeals.latest_residential',array['county'],'workbench-hydrate','live',array['nj-tax-court-appeals'],now(),'Latest published county residential appeal count.','authoritative_reference',array['latest.residential'],'nj-tax-court-appeals',86400,'refresh_on_demand',true)
on conflict(marker_id) do update set scopes=excluded.scopes,provider_key=excluded.provider_key,value_status='live',source_keys=excluded.source_keys,last_verified_at=excluded.last_verified_at,notes=excluded.notes,provider_kind=excluded.provider_kind,source_fields=excluded.source_fields,calculation_key=excluded.calculation_key,freshness_seconds=excluded.freshness_seconds,cache_policy=excluded.cache_policy,bulk_capable=excluded.bulk_capable;

insert into public.derived_formula_registry(marker_id,engine_version,formula,dependencies,confidence,status,explanation,operation,config,updated_at) values
('watchdog.permit_latest_record_age_years','watchdog-permit-age-v1','Current year minus year of latest authoritative DCA permit record',array['preflight.latest_permit_date'],'high','live','Elapsed calendar years since the latest DCA permit record. It is not the age of a physical condition or proof that work remains open.','year_delta','{"dep":"preflight.latest_permit_date","date_year":true}'::jsonb,now()),
('watchdog.permit_record_age_attention','watchdog-permit-age-v1','Normalize latest permit-record age to a 0-100 attention scale over 10 years',array['watchdog.permit_latest_record_age_years'],'medium','live','A bounded age-attention transform used only as context for an existing permit/certificate gap.','weighted_signals','{"signals":[{"dep":"watchdog.permit_latest_record_age_years","weight":100,"transform":"count10"}]}'::jsonb,now()),
('watchdog.open_permit_gap_presence','watchdog-permit-age-v1','Normalize open permit/certificate gap count to a binary-like attention scale',array['preflight.open_permit_count'],'high','live','0 when the live DCA permit provider reports no permit-issued/certificate gap; 100 once one or more such gaps are present.','weighted_signals','{"signals":[{"dep":"preflight.open_permit_count","weight":100,"transform":"count1"}]}'::jsonb,now()),
('watchdog.title.permit_certificate_gap_age','watchdog-permit-age-v1','Open-gap presence × latest permit-record age attention',array['watchdog.open_permit_gap_presence','watchdog.permit_record_age_attention'],'medium','live','Narrowed v1: age attention is emitted only when a DCA permit-issued/certificate gap exists. Because the provider exposes latest permit date rather than the oldest unresolved permit event date, this is a conservative review-priority score, not the literal age of an unresolved permit or certificate.','product_scores','{"items":[{"dep":"watchdog.open_permit_gap_presence"},{"dep":"watchdog.permit_record_age_attention"}]}'::jsonb,now()),
('watchdog.contractor.development_timeline_uncertainty','watchdog-permit-age-v1','40% permit/certificate gap-age attention + 35% regulatory constraint density + 25% inverse authoritative-source currency',array['watchdog.title.permit_certificate_gap_age','watchdog.regulatory_constraint_density','watchdog.attorney.case_file_source_freshness'],'medium','live','Narrowed v1 development-timeline screen using actual DCA permit/certificate-gap context, mapped regulatory overlap, and governed source currency. It does not estimate approval duration or construction completion time.','weighted_scores','{"require_all":true,"items":[{"dep":"watchdog.title.permit_certificate_gap_age","weight":40,"transform":"identity"},{"dep":"watchdog.regulatory_constraint_density","weight":35,"transform":"identity"},{"dep":"watchdog.attorney.case_file_source_freshness","weight":25,"transform":"inverse_identity"}]}'::jsonb,now()),
('watchdog.municipal.appeal_activity_context','watchdog-municipal-activity-v1','40% county appeal filing volume + 35% assessed value appealed + 25% residential appeal volume, each on bounded screening scales',array['appeals.latest_total','appeals.latest_assessed_appealed','appeals.latest_residential'],'medium','live','County-level public appeal activity context from the latest NJ Division of Taxation appeal summary. It is not municipal appeal volume, a budget-loss forecast, or a prediction of appeal outcomes.','weighted_signals','{"signals":[{"dep":"appeals.latest_total","weight":40,"transform":"count5000"},{"dep":"appeals.latest_assessed_appealed","weight":35,"transform":"count1000000000"},{"dep":"appeals.latest_residential","weight":25,"transform":"count3000"}]}'::jsonb,now()),
('watchdog.municipal.debt_service_attention','watchdog-municipal-debt-v1','60% debt-service share + 40% net-debt share normalized against a 35% screening ceiling',array['budget.debt_service_share','budget.net_debt_pct'],'medium','live','Municipal debt attention from NJ DCA User-Friendly Budget fields. Both inputs are public fiscal context only; this is not a credit rating, solvency conclusion, or forecast.','weighted_signals','{"signals":[{"dep":"budget.debt_service_share","weight":60,"transform":"share35"},{"dep":"budget.net_debt_pct","weight":40,"transform":"share35"}]}'::jsonb,now())
on conflict(marker_id) do update set engine_version=excluded.engine_version,formula=excluded.formula,dependencies=excluded.dependencies,confidence=excluded.confidence,status=excluded.status,explanation=excluded.explanation,operation=excluded.operation,config=excluded.config,updated_at=now();

insert into public.data_center_provider_coverage(marker_id,scopes,provider_key,value_status,source_keys,last_verified_at,notes,provider_kind,source_fields,calculation_key,freshness_seconds,cache_policy,bulk_capable) values
('watchdog.permit_latest_record_age_years',array['property'],'watchdog-derived','live',array['njdep-dca-live'],now(),'Calendar age of latest authoritative DCA permit record; not unresolved-event age.','derived_governed',array['preflight.latest_permit_date'],'watchdog-permit-age-v1',86400,'refresh_on_demand',true),
('watchdog.permit_record_age_attention',array['property'],'watchdog-derived','live',array['njdep-dca-live'],now(),'Bounded latest-permit-record age attention.','derived_governed',array['watchdog.permit_latest_record_age_years'],'watchdog-permit-age-v1',86400,'refresh_on_demand',true),
('watchdog.open_permit_gap_presence',array['property'],'watchdog-derived','live',array['njdep-dca-live'],now(),'Presence score for DCA permit-issued/certificate gap count.','derived_governed',array['preflight.open_permit_count'],'watchdog-permit-age-v1',86400,'refresh_on_demand',true),
('watchdog.title.permit_certificate_gap_age',array['property'],'watchdog-derived','live',array['njdep-dca-live'],now(),'Conservative permit/certificate gap-age attention using live gap count and latest permit-record date.','derived_governed',array['watchdog.open_permit_gap_presence','watchdog.permit_record_age_attention'],'watchdog-permit-age-v1',86400,'refresh_on_demand',true),
('watchdog.contractor.development_timeline_uncertainty',array['property'],'watchdog-derived','live',array['njdep-dca-live','data_center_provider_coverage'],now(),'Public-record development timeline uncertainty screen; not an approval-duration estimate.','derived_governed',array['watchdog.title.permit_certificate_gap_age','watchdog.regulatory_constraint_density','watchdog.attorney.case_file_source_freshness'],'watchdog-permit-age-v1',86400,'refresh_on_demand',true),
('watchdog.municipal.appeal_activity_context',array['county'],'watchdog-derived','live',array['nj-tax-court-appeals'],now(),'Latest county-level appeal volume/value activity context.','derived_governed',array['appeals.latest_total','appeals.latest_assessed_appealed','appeals.latest_residential'],'watchdog-municipal-activity-v1',86400,'refresh_on_demand',true),
('watchdog.municipal.debt_service_attention',array['municipality'],'watchdog-derived','live',array['nj-dca-budget'],now(),'NJ DCA debt-service and net-debt attention context.','derived_governed',array['budget.debt_service_share','budget.net_debt_pct'],'watchdog-municipal-debt-v1',86400,'refresh_on_demand',true)
on conflict(marker_id) do update set scopes=excluded.scopes,provider_key=excluded.provider_key,value_status='live',source_keys=excluded.source_keys,last_verified_at=excluded.last_verified_at,notes=excluded.notes,provider_kind=excluded.provider_kind,source_fields=excluded.source_fields,calculation_key=excluded.calculation_key,freshness_seconds=excluded.freshness_seconds,cache_policy=excluded.cache_policy,bulk_capable=excluded.bulk_capable;