-- NJW-322: privacy-safe ANCHOR completion growth loop, referrals and Watchdog points.
-- Never store application answers, SSNs, income, disability status, PDF contents, or vault keys here.

create table if not exists public.anchor_completion_feedback (
  id uuid primary key default gen_random_uuid(),
  application_id uuid not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  source_category text not null check (source_category in (
    'google_search','facebook','threads','instagram','tiktok','friend_family',
    'real_estate_professional','njpropertytaxrelief','email_newsletter','other'
  )),
  source_detail text check (source_detail is null or length(source_detail) <= 240),
  marketing_opt_in_requested boolean not null default false,
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (application_id, user_id),
  constraint anchor_completion_feedback_application_owner_fk
    foreign key (application_id, user_id)
    references public.anchor_applications(id, user_id)
    on delete cascade
);

comment on table public.anchor_completion_feedback is
  'Post-completion, non-sensitive ANCHOR acquisition feedback. Kept outside the encrypted application payload.';

create table if not exists public.anchor_funnel_events (
  id bigint generated by default as identity primary key,
  application_id uuid not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_name text not null check (event_name in (
    'application_started','progress_quarter','progress_half','progress_three_quarters',
    'review_reached','pdf_generated','pdf_saved_to_vault','download_clicked','print_clicked',
    'application_reopened','watchdog_cta_clicked','completion_feedback_saved','referral_share_opened'
  )),
  event_key text not null unique check (length(event_key) between 20 and 220),
  occurred_at timestamptz not null default now(),
  constraint anchor_funnel_events_application_owner_fk
    foreign key (application_id, user_id)
    references public.anchor_applications(id, user_id)
    on delete cascade
);

comment on table public.anchor_funnel_events is
  'Coarse, privacy-safe ANCHOR funnel events. Route/form type and answer-derived attributes are intentionally excluded.';

create table if not exists public.watchdog_points_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action_key text not null check (action_key ~ '^[a-z0-9_]{2,64}$'),
  points integer not null check (points between 1 and 1000),
  event_key text not null unique check (length(event_key) between 8 and 220),
  source_type text not null default 'system' check (source_type ~ '^[a-z0-9_]{2,64}$'),
  source_id text check (source_id is null or length(source_id) <= 160),
  occurred_at timestamptz not null default now()
);

comment on table public.watchdog_points_ledger is
  'Server-authoritative, append-only Watchdog engagement points. Clients cannot mint or edit awards.';

create table if not exists public.watchdog_referral_codes (
  user_id uuid primary key references auth.users(id) on delete cascade,
  referral_code text not null unique check (referral_code ~ '^[A-Z0-9]{10,16}$'),
  created_at timestamptz not null default now()
);

create table if not exists public.watchdog_referral_conversions (
  id bigint generated by default as identity primary key,
  inviter_user_id uuid not null references auth.users(id) on delete cascade,
  referred_user_id uuid not null unique references auth.users(id) on delete cascade,
  referral_code text not null references public.watchdog_referral_codes(referral_code) on delete cascade,
  verified_at timestamptz not null default now(),
  check (inviter_user_id <> referred_user_id)
);

create index if not exists anchor_completion_feedback_user_idx on public.anchor_completion_feedback(user_id, submitted_at desc);
create index if not exists anchor_funnel_events_user_idx on public.anchor_funnel_events(user_id, occurred_at desc);
create index if not exists anchor_funnel_events_application_idx on public.anchor_funnel_events(application_id, occurred_at asc);
create index if not exists watchdog_points_ledger_user_idx on public.watchdog_points_ledger(user_id, occurred_at desc);
create index if not exists watchdog_points_ledger_action_idx on public.watchdog_points_ledger(user_id, action_key, occurred_at desc);
create index if not exists watchdog_referral_conversions_inviter_idx on public.watchdog_referral_conversions(inviter_user_id, verified_at desc);

alter table public.anchor_completion_feedback enable row level security;
alter table public.anchor_funnel_events enable row level security;
alter table public.watchdog_points_ledger enable row level security;
alter table public.watchdog_referral_codes enable row level security;
alter table public.watchdog_referral_conversions enable row level security;

revoke all on public.anchor_completion_feedback from anon, authenticated;
revoke all on public.anchor_funnel_events from anon, authenticated;
revoke all on public.watchdog_points_ledger from anon, authenticated;
revoke all on public.watchdog_referral_codes from anon, authenticated;
revoke all on public.watchdog_referral_conversions from anon, authenticated;

grant select on public.anchor_completion_feedback to authenticated;
grant select on public.anchor_funnel_events to authenticated;
grant select on public.watchdog_points_ledger to authenticated;
grant select on public.watchdog_referral_codes to authenticated;
grant select on public.watchdog_referral_conversions to authenticated;

drop policy if exists anchor_completion_feedback_owner_select on public.anchor_completion_feedback;
create policy anchor_completion_feedback_owner_select on public.anchor_completion_feedback
for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists anchor_funnel_events_owner_select on public.anchor_funnel_events;
create policy anchor_funnel_events_owner_select on public.anchor_funnel_events
for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists watchdog_points_ledger_owner_select on public.watchdog_points_ledger;
create policy watchdog_points_ledger_owner_select on public.watchdog_points_ledger
for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists watchdog_referral_codes_owner_select on public.watchdog_referral_codes;
create policy watchdog_referral_codes_owner_select on public.watchdog_referral_codes
for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists watchdog_referral_conversions_inviter_select on public.watchdog_referral_conversions;
create policy watchdog_referral_conversions_inviter_select on public.watchdog_referral_conversions
for select to authenticated using ((select auth.uid()) = inviter_user_id);

drop trigger if exists anchor_completion_feedback_touch_updated_at on public.anchor_completion_feedback;
create trigger anchor_completion_feedback_touch_updated_at
before update on public.anchor_completion_feedback
for each row execute function public.touch_updated_at();

create or replace function public.watchdog_award_points_internal(
  p_user_id uuid,
  p_action_key text,
  p_points integer,
  p_event_key text,
  p_source_type text default 'system',
  p_source_id text default null
) returns boolean
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if p_user_id is null or p_points < 1 or p_points > 1000 then return false; end if;
  insert into public.watchdog_points_ledger(user_id, action_key, points, event_key, source_type, source_id)
  values (p_user_id, p_action_key, p_points, left(p_event_key,220), left(coalesce(nullif(p_source_type,''),'system'),64), left(p_source_id,160))
  on conflict (event_key) do nothing;
  return found;
end;
$$;
revoke all on function public.watchdog_award_points_internal(uuid,text,integer,text,text,text) from public, anon, authenticated;
grant execute on function public.watchdog_award_points_internal(uuid,text,integer,text,text,text) to service_role;

create or replace function public.watchdog_points_anchor_application_trigger() returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if new.status = 'generated' and (tg_op = 'INSERT' or old.status is distinct from 'generated') then
    perform public.watchdog_award_points_internal(new.user_id,'anchor_application',10,'anchor_application:'||new.id::text,'anchor_application',new.id::text);
  end if;
  return new;
end;
$$;

drop trigger if exists watchdog_points_anchor_application on public.anchor_applications;
create trigger watchdog_points_anchor_application
after insert or update of status on public.anchor_applications
for each row execute function public.watchdog_points_anchor_application_trigger();

create or replace function public.watchdog_points_anchor_estimate_trigger() returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
declare v_today integer;
begin
  if new.user_id is null then return new; end if;
  select count(*) into v_today from public.watchdog_points_ledger
   where user_id=new.user_id and action_key='anchor_estimate' and occurred_at >= date_trunc('day',now());
  if v_today < 2 then
    perform public.watchdog_award_points_internal(new.user_id,'anchor_estimate',2,'anchor_estimate:'||new.id::text,'anchor_estimate',new.id::text);
  end if;
  return new;
end;
$$;

drop trigger if exists watchdog_points_anchor_estimate on public.anchor_estimates;
create trigger watchdog_points_anchor_estimate
after insert on public.anchor_estimates
for each row execute function public.watchdog_points_anchor_estimate_trigger();

create or replace function public.watchdog_points_first_saved_property_trigger() returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  perform public.watchdog_award_points_internal(new.user_id,'first_saved_property',5,'first_saved_property:'||new.user_id::text,'saved_property',new.id::text);
  return new;
end;
$$;

drop trigger if exists watchdog_points_first_saved_property on public.saved_properties;
create trigger watchdog_points_first_saved_property
after insert on public.saved_properties
for each row execute function public.watchdog_points_first_saved_property_trigger();

create or replace function public.watchdog_points_onboarding_trigger() returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if new.completed_at is not null and (tg_op='INSERT' or old.completed_at is null) then
    perform public.watchdog_award_points_internal(new.user_id,'onboarding_complete',10,'onboarding_complete:'||new.user_id::text,'onboarding',new.onboarding_version::text);
  end if;
  return new;
end;
$$;

drop trigger if exists watchdog_points_onboarding on public.watchdog_onboarding_profiles;
create trigger watchdog_points_onboarding
after insert or update of completed_at on public.watchdog_onboarding_profiles
for each row execute function public.watchdog_points_onboarding_trigger();

create or replace function public.watchdog_points_first_alert_trigger() returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if coalesce(new.paused,false)=false and (coalesce(new.alert_score,false) or coalesce(new.alert_tax,false) or coalesce(new.alert_assessment,false) or coalesce(new.alert_deadline,false)) then
    perform public.watchdog_award_points_internal(new.user_id,'first_property_alert',10,'first_property_alert:'||new.user_id::text,'property_alert',new.id::text);
  end if;
  return new;
end;
$$;

drop trigger if exists watchdog_points_first_alert on public.property_alert_preferences;
create trigger watchdog_points_first_alert
after insert or update on public.property_alert_preferences
for each row execute function public.watchdog_points_first_alert_trigger();

create or replace function public.award_watchdog_search_point(p_user_id uuid) returns boolean
language plpgsql
security definer
set search_path = public, auth
as $$
declare v_count integer; v_key text;
begin
  if p_user_id is null or not exists(select 1 from auth.users where id=p_user_id) then return false; end if;
  select count(*) into v_count from public.watchdog_points_ledger
   where user_id=p_user_id and action_key='property_search' and occurred_at >= date_trunc('day',now());
  if v_count >= 5 then return false; end if;
  v_key := 'property_search:'||p_user_id::text||':'||to_char(now(),'YYYYMMDD')||':'||replace(gen_random_uuid()::text,'-','');
  return public.watchdog_award_points_internal(p_user_id,'property_search',1,v_key,'product_analytics',null);
end;
$$;
revoke all on function public.award_watchdog_search_point(uuid) from public, anon, authenticated;
grant execute on function public.award_watchdog_search_point(uuid) to service_role;

create or replace function public.get_my_watchdog_points() returns jsonb
language sql
stable
security definer
set search_path = public, auth
as $$
  with p as (
    select coalesce(sum(points),0)::integer as balance, count(*)::integer as awards
    from public.watchdog_points_ledger where user_id=(select auth.uid())
  )
  select jsonb_build_object(
    'balance',balance,
    'awards',awards,
    'level',case when balance >= 150 then 'Guardian' when balance >= 75 then 'Advocate' when balance >= 25 then 'Watcher' else 'Scout' end,
    'next_level_at',case when balance >= 150 then null when balance >= 75 then 150 when balance >= 25 then 75 else 25 end
  ) from p;
$$;
revoke all on function public.get_my_watchdog_points() from public, anon;
grant execute on function public.get_my_watchdog_points() to authenticated;

create or replace function public.get_or_create_my_watchdog_referral_code() returns text
language plpgsql
security definer
set search_path = public, auth
as $$
declare v_uid uuid := auth.uid(); v_code text; v_try integer := 0;
begin
  if v_uid is null then raise exception 'authentication_required'; end if;
  select referral_code into v_code from public.watchdog_referral_codes where user_id=v_uid;
  if v_code is not null then return v_code; end if;
  loop
    v_try := v_try + 1;
    v_code := upper(substr(replace(gen_random_uuid()::text,'-',''),1,12));
    begin
      insert into public.watchdog_referral_codes(user_id,referral_code) values(v_uid,v_code);
      return v_code;
    exception when unique_violation then
      select referral_code into v_code from public.watchdog_referral_codes where user_id=v_uid;
      if v_code is not null then return v_code; end if;
      if v_try >= 5 then raise; end if;
    end;
  end loop;
end;
$$;
revoke all on function public.get_or_create_my_watchdog_referral_code() from public, anon;
grant execute on function public.get_or_create_my_watchdog_referral_code() to authenticated;

create or replace function public.record_my_anchor_funnel_event(
  p_application_id uuid,
  p_event_name text
) returns boolean
language plpgsql
security definer
set search_path = public, auth
as $$
declare v_uid uuid := auth.uid(); v_key text;
begin
  if v_uid is null then return false; end if;
  if p_event_name not in (
    'application_started','progress_quarter','progress_half','progress_three_quarters','review_reached',
    'pdf_generated','pdf_saved_to_vault','download_clicked','print_clicked','application_reopened',
    'watchdog_cta_clicked','completion_feedback_saved','referral_share_opened'
  ) then return false; end if;
  if not exists(select 1 from public.anchor_applications where id=p_application_id and user_id=v_uid) then return false; end if;
  v_key := v_uid::text||':'||p_application_id::text||':'||p_event_name;
  insert into public.anchor_funnel_events(application_id,user_id,event_name,event_key)
  values(p_application_id,v_uid,p_event_name,v_key)
  on conflict(event_key) do nothing;
  return found;
end;
$$;
revoke all on function public.record_my_anchor_funnel_event(uuid,text) from public, anon;
grant execute on function public.record_my_anchor_funnel_event(uuid,text) to authenticated;

create or replace function public.record_my_anchor_completion_feedback(
  p_application_id uuid,
  p_source_category text,
  p_source_detail text default null,
  p_marketing_opt_in boolean default false
) returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare v_uid uuid := auth.uid(); v_permission text; v_points jsonb;
begin
  if v_uid is null then raise exception 'authentication_required'; end if;
  if p_source_category not in ('google_search','facebook','threads','instagram','tiktok','friend_family','real_estate_professional','njpropertytaxrelief','email_newsletter','other') then
    raise exception 'invalid_source_category';
  end if;
  if p_source_category='other' and length(trim(coalesce(p_source_detail,''))) < 2 then
    raise exception 'source_detail_required';
  end if;
  if not exists(select 1 from public.anchor_applications where id=p_application_id and user_id=v_uid and status='generated') then
    raise exception 'generated_application_required';
  end if;

  insert into public.anchor_completion_feedback(application_id,user_id,source_category,source_detail,marketing_opt_in_requested)
  values(p_application_id,v_uid,p_source_category,nullif(trim(left(coalesce(p_source_detail,''),240)),''),coalesce(p_marketing_opt_in,false))
  on conflict(application_id,user_id) do update set
    source_category=excluded.source_category,
    source_detail=excluded.source_detail,
    marketing_opt_in_requested=excluded.marketing_opt_in_requested,
    updated_at=now();

  if coalesce(p_marketing_opt_in,false) then
    update public.watchdog_user_lifecycle
      set contact_permission='marketing_opt_in', updated_at=now()
      where user_id=v_uid
        and contact_permission='transactional_only'
        and unsubscribed_at is null
        and suppressed_at is null;
  end if;

  perform public.record_my_anchor_funnel_event(p_application_id,'completion_feedback_saved');
  select contact_permission into v_permission from public.watchdog_user_lifecycle where user_id=v_uid;
  select public.get_my_watchdog_points() into v_points;
  return jsonb_build_object('ok',true,'contact_permission',coalesce(v_permission,'transactional_only'),'points',v_points);
end;
$$;
revoke all on function public.record_my_anchor_completion_feedback(uuid,text,text,boolean) from public, anon;
grant execute on function public.record_my_anchor_completion_feedback(uuid,text,text,boolean) to authenticated;

create or replace function public.watchdog_referral_attribution_trigger() returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
declare v_inviter uuid; v_inserted integer;
begin
  if lower(coalesce(new.first_touch_utm_source,'')) <> 'watchdog_referral'
     or lower(coalesce(new.first_touch_utm_medium,'')) <> 'member'
     or coalesce(new.first_touch_utm_campaign,'') = '' then
    return new;
  end if;
  select user_id into v_inviter from public.watchdog_referral_codes where referral_code=upper(new.first_touch_utm_campaign) limit 1;
  if v_inviter is null or v_inviter=new.user_id then return new; end if;
  insert into public.watchdog_referral_conversions(inviter_user_id,referred_user_id,referral_code)
  values(v_inviter,new.user_id,upper(new.first_touch_utm_campaign))
  on conflict(referred_user_id) do nothing;
  get diagnostics v_inserted = row_count;
  if v_inserted > 0 then
    perform public.watchdog_award_points_internal(v_inviter,'verified_referral',5,'verified_referral:'||new.user_id::text,'referral',new.user_id::text);
  end if;
  return new;
end;
$$;

drop trigger if exists watchdog_referral_attribution on public.watchdog_signup_attribution;
create trigger watchdog_referral_attribution
after insert or update of first_touch_utm_source, first_touch_utm_medium, first_touch_utm_campaign
on public.watchdog_signup_attribution
for each row execute function public.watchdog_referral_attribution_trigger();

-- Backfill earned points for existing real usage so current users do not start at zero.
insert into public.watchdog_points_ledger(user_id,action_key,points,event_key,source_type,source_id,occurred_at)
select user_id,'anchor_application',10,'anchor_application:'||id::text,'anchor_application',id::text,coalesce(generated_at,updated_at)
from public.anchor_applications where status='generated'
on conflict(event_key) do nothing;

insert into public.watchdog_points_ledger(user_id,action_key,points,event_key,source_type,source_id,occurred_at)
select user_id,'anchor_estimate',2,'anchor_estimate:'||id::text,'anchor_estimate',id::text,coalesce(estimated_at,created_at)
from public.anchor_estimates where user_id is not null
on conflict(event_key) do nothing;

insert into public.watchdog_points_ledger(user_id,action_key,points,event_key,source_type,source_id,occurred_at)
select distinct on (user_id) user_id,'first_saved_property',5,'first_saved_property:'||user_id::text,'saved_property',id::text,created_at
from public.saved_properties order by user_id,created_at asc
on conflict(event_key) do nothing;

insert into public.watchdog_points_ledger(user_id,action_key,points,event_key,source_type,source_id,occurred_at)
select user_id,'onboarding_complete',10,'onboarding_complete:'||user_id::text,'onboarding',onboarding_version::text,completed_at
from public.watchdog_onboarding_profiles where completed_at is not null
on conflict(event_key) do nothing;

insert into public.watchdog_points_ledger(user_id,action_key,points,event_key,source_type,source_id,occurred_at)
select distinct on (user_id) user_id,'first_property_alert',10,'first_property_alert:'||user_id::text,'property_alert',id::text,created_at
from public.property_alert_preferences
where coalesce(paused,false)=false and (coalesce(alert_score,false) or coalesce(alert_tax,false) or coalesce(alert_assessment,false) or coalesce(alert_deadline,false))
order by user_id,created_at asc
on conflict(event_key) do nothing;
