module.exports = {
  "program": "Watchdog Compliance Readiness",
  "version": 5,
  "updated_at": "2026-08-19",
  "status": "readiness-in-progress",
  "certification_claim": "Watchdog is building toward independent assurance. No SOC 2, ISO, PCI, WCAG, or other certification/conformance claim is made unless independently established and current.",
  "entries": [
    {
      "id": "WCR-2026-08-18-001",
      "date": "2026-08-18",
      "title": "Compliance readiness program established",
      "frameworks": ["SOC 2", "NIST CSF 2.0", "OWASP ASVS 5.0", "ISO/IEC 27001"],
      "control_area": "Governance and evidence management",
      "status": "implemented",
      "action": "Established a permanent Watchdog compliance-readiness program with a control register, decision log, website Compliance Center, evidence requirements, and a recurring improvement cadence.",
      "evidence": ["property/docs/compliance/README.md", "property/docs/compliance/CONTROL-REGISTER.md", "property/docs/compliance/DECISION-LOG.md", "property/compliance/index.html", "property/tests/compliance-contracts.mjs"],
      "rationale": "Compliance should be engineered into the product while architecture is still evolving rather than treated as a one-time certification project after launch.",
      "residual_risk": "The program is internally managed and has not yet been independently audited or certified.",
      "next_step": "Continue mapping existing production controls to framework requirements and close high-risk gaps before engaging an external auditor."
    },
    {
      "id": "WCR-2026-08-18-002",
      "date": "2026-08-18",
      "title": "Formal certification deferred until production architecture stabilizes",
      "frameworks": ["SOC 2", "ISO/IEC 27001", "ISO/IEC 27701", "ISO/IEC 42001"],
      "control_area": "Assurance strategy",
      "status": "accepted-plan",
      "action": "Documented the decision to build toward audit readiness now while deferring paid formal audits and certifications until core production workflows, billing, material data connectors, and access architecture are substantially stable.",
      "evidence": ["property/docs/compliance/DECISION-LOG.md"],
      "rationale": "Auditing a rapidly changing architecture creates avoidable rework and can produce evidence that no longer represents the production system.",
      "residual_risk": "Enterprise prospects may request assurance reports before Watchdog has completed an independent examination.",
      "next_step": "Define objective readiness gates for a SOC 2 readiness assessment and later Type I/Type II examination."
    },
    {
      "id": "WCR-2026-08-18-003",
      "date": "2026-08-18",
      "title": "Existing security CI recognized as audit evidence",
      "frameworks": ["SOC 2", "OWASP ASVS 5.0", "NIST CSF 2.0"],
      "control_area": "Secure development and access control",
      "status": "implemented",
      "action": "Mapped the existing access-boundary and security-contract CI suite as evidence for authorization, webhook authentication, pricing authority, CORS restrictions, RLS/entitlement boundaries, security headers, and other application-security controls.",
      "evidence": [".github/workflows/access-boundary-audit.yml", "property/tests/security-contracts.mjs"],
      "rationale": "Automated security assertions executed during code changes provide stronger repeatable evidence than policy statements alone.",
      "residual_risk": "Static contract tests do not replace dynamic vulnerability testing, independent penetration testing, or complete ASVS verification.",
      "next_step": "Expand evidence coverage to dependency, secret, code-scanning, accessibility, and dynamic application-security controls."
    },
    {
      "id": "WCR-2026-08-18-004",
      "date": "2026-08-18",
      "title": "Deployment source-of-truth policy mapped to change management",
      "frameworks": ["SOC 2", "NIST CSF 2.0", "ISO/IEC 27001"],
      "control_area": "Change management",
      "status": "implemented",
      "action": "Recognized the existing Git-as-source-of-truth Edge Function policy, production fingerprint reconciliation, and inventory requirements as formal change-management evidence.",
      "evidence": ["supabase/functions/DEPLOYMENT-POLICY.md"],
      "rationale": "Production changes must be traceable to reviewed source and reversible without relying on undocumented dashboard edits.",
      "residual_risk": "Connector and infrastructure changes outside Edge Functions still need the same evidence discipline.",
      "next_step": "Extend change-control evidence requirements to all material production connectors and infrastructure configuration."
    },
    {
      "id": "WCR-2026-08-18-005",
      "date": "2026-08-18",
      "title": "Incident response and telemetry minimization mapped",
      "frameworks": ["SOC 2", "NIST CSF 2.0", "ISO/IEC 27001", "NJDPA"],
      "control_area": "Incident response and privacy",
      "status": "implemented",
      "action": "Mapped the existing incident response runbook and telemetry sanitization rules into the compliance control inventory.",
      "evidence": ["property/docs/incident-response-runbook.md"],
      "rationale": "Incident handling needs defined severity, ownership, mitigation, verification, communication, and privacy-safe evidence collection before a real incident occurs.",
      "residual_risk": "A documented runbook is not sufficient evidence of operational effectiveness until exercises and real response records are retained.",
      "next_step": "Schedule and document a tabletop incident-response exercise and track remediation items."
    },
    {
      "id": "WCR-2026-08-18-006",
      "date": "2026-08-18",
      "title": "Material connector governance established",
      "frameworks": ["SOC 2", "NIST CSF 2.0", "NJDPA", "ISO/IEC 27001", "ISO/IEC 27701"],
      "control_area": "Vendor and connector risk management",
      "status": "implemented",
      "action": "Created a material connector register with a reusable review record, risk-tier guidance, current inventory seed, and explicit rule that being referenced in the repository does not by itself establish production-live status.",
      "evidence": ["property/docs/compliance/CONNECTOR-REGISTER.md"],
      "rationale": "Watchdog must be able to add, replace, or retire data and service connectors without losing control of data flows, credentials, permissions, retention, privacy scope, or vendor risk.",
      "residual_risk": "The initial inventory is seeded from current repository and policy evidence; each connector still requires explicit live-status verification and completion of its detailed review record.",
      "next_step": "Verify production status and complete risk-review fields for Tier 1 connectors first, beginning with authentication, hosting, payments, and any connector processing non-public customer information."
    },
    {
      "id": "WCR-2026-08-18-007",
      "date": "2026-08-18",
      "title": "Compliance evidence delivery moved behind server-side developer verification",
      "frameworks": ["SOC 2", "NIST CSF 2.0", "OWASP ASVS 5.0", "ISO/IEC 27001"],
      "control_area": "Access control and evidence confidentiality",
      "status": "implemented",
      "action": "Changed the Compliance Center so detailed evidence is requested from a server endpoint that independently validates the signed-in Watchdog session and developer entitlement before returning the evidence feed; unauthorized callers receive a non-descriptive not-found response and responses are non-cacheable.",
      "evidence": ["api/compliance-log.js", "property/js/compliance.js", "property/compliance/index.html", "property/tests/compliance-contracts.mjs"],
      "rationale": "Client-side hiding alone is not a sufficient boundary for an internal governance surface because a guessed resource URL should not return the operational evidence feed to an anonymous or non-developer caller.",
      "residual_risk": "The GitHub repository is currently public, so committed compliance artifacts must remain sanitized and must never contain secrets, customer data or exploit-enabling detail.",
      "next_step": "Review whether the repository itself should eventually become private and continue separating public trust information from internal operational evidence."
    },
    {
      "id": "WCR-2026-08-18-008",
      "date": "2026-08-18",
      "title": "Compliance improvement cadence expanded to twice daily",
      "frameworks": ["SOC 2", "NIST CSF 2.0", "ISO/IEC 27001"],
      "control_area": "Continuous monitoring and governance",
      "status": "implemented",
      "action": "Expanded the recurring compliance-readiness cadence to 1:00 AM and 12:00 PM Eastern Time every day, requiring at least one substantive improvement per session while allowing multiple related improvements whenever useful and safe.",
      "evidence": ["property/docs/compliance/README.md"],
      "rationale": "A minimum-only once-daily cadence could become artificially narrow; two review windows with permission to complete multiple related controls better matches an actively evolving SaaS platform.",
      "residual_risk": "Automation frequency does not by itself prove operating effectiveness; completed work still requires useful evidence and periodic human review.",
      "next_step": "Use the scheduled sessions to prioritize high-risk gaps and accumulate evidence that will later support readiness assessments and independent audits."
    },
    {
      "id": "WCR-2026-08-19-001",
      "date": "2026-08-19",
      "title": "Incident-response tabletop exercise completed",
      "frameworks": ["SOC 2", "NIST CSF 2.0", "ISO/IEC 27001", "OWASP ASVS 5.0"],
      "control_area": "Incident response and recovery",
      "status": "implemented",
      "action": "Completed and retained a sanitized internal tabletop exercise for a plausible multi-user authenticated paid-workflow incident, walking through detection, classification, evidence minimization, ownership, containment, authorization verification, source-of-truth reconciliation, communication and closure criteria.",
      "evidence": ["property/docs/compliance/INCIDENT-TABLETOP-2026-08-19.md", "property/docs/incident-response-runbook.md", "property/docs/compliance/CONTROL-REGISTER.md"],
      "rationale": "A written runbook alone does not demonstrate that the response sequence is coherent when applied to a realistic incident; exercising it produces operating evidence and exposes gaps before a real event.",
      "residual_risk": "The tabletop does not measure real-world response speed, staging recovery performance, provider coordination or independent effectiveness.",
      "next_step": "Add a reusable incident record template, define provisional RTO/RPO targets, and conduct a future connector or credential-revocation exercise."
    },
    {
      "id": "WCR-2026-08-19-002",
      "date": "2026-08-19",
      "title": "Seven no-cost readiness tracks activated",
      "frameworks": ["OWASP ASVS 5.0", "NIST CSF 2.0", "WCAG 2.2 AA", "PCI DSS", "NJDPA", "SOC 2", "ISO/IEC 27001"],
      "control_area": "Security, privacy, accessibility and assurance readiness",
      "status": "implemented",
      "action": "Activated all seven zero-cost readiness tracks: ASVS Level 2 baseline mapping, NIST Current/Target Profile, WCAG 2.2 AA evidence program, TLS/HSTS measurement, PCI scope documentation, NJDPA data-protection assessment discipline, and a factual public Security & Trust Center. Added CI evidence generators and claim-boundary tests, and reconciled the public privacy policy's financial-data classification with the New Jersey statute.",
      "evidence": ["property/docs/compliance/SEVEN-TRACK-SPRINT-2026-08-19.md", "property/docs/compliance/ASVS-5-L2-BASELINE.md", "property/docs/compliance/NIST-CSF-2-PROFILE.md", "property/docs/compliance/WCAG-2.2-AA-BASELINE.md", "property/docs/compliance/TLS-SECURITY-BASELINE.md", "property/docs/compliance/PCI-SCOPE-MEMO.md", "property/docs/compliance/NJDPA-DATA-PROTECTION-ASSESSMENT.md", "property/trust/index.html", ".github/workflows/zero-cost-compliance-readiness.yml"],
      "rationale": "The strongest use of a zero-dollar budget is to build controls, repeatable evidence, accurate public claims and audit-ready documentation now, leaving only genuinely independent validation for a later paid phase.",
      "residual_risk": "Several tracks remain readiness programs rather than completed external assurance: ASVS requirement-level verification, manual/authenticated accessibility testing, final PCI merchant validation and ASV scanning, external TLS grading, and independent SOC/ISO/security testing remain incomplete.",
      "next_step": "Use the twice-daily cadence to review generated accessibility/TLS evidence, begin requirement-level ASVS verification, build the NIST risk register, inventory payment/data fields and expand manual/authenticated WCAG evidence."
    },
    {
      "id": "WCR-2026-08-19-003",
      "date": "2026-08-19",
      "title": "Cybersecurity risk register and ASVS identity verification tranche established",
      "frameworks": ["NIST CSF 2.0", "SOC 2", "OWASP ASVS 5.0.0", "ISO/IEC 27001"],
      "control_area": "Risk management, authentication, sessions, authorization and OAuth/OIDC",
      "status": "implemented-with-open-gaps",
      "action": "Created Watchdog's first formal cybersecurity/compliance risk register and completed the first requirement-level ASVS 5.0.0 identity and authorization tranche. Added automated contracts that preserve the centralized PKCE configuration, same-origin /property/ continuation boundary, session runtime settings, removal of legacy magic-link UI, and default-disabled status of unreviewed authentication providers.",
      "evidence": ["property/docs/compliance/RISK-REGISTER.md", "property/docs/compliance/ASVS-AUTH-SESSION-AUTHZ-TRANCHE-2026-08-19.md", "property/tests/auth-asvs-contract.mjs", ".github/workflows/zero-cost-compliance-readiness.yml", "property/docs/compliance/CONTROL-REGISTER.md"],
      "rationale": "NIST CSF 2.0 is intended to help organizations understand, assess, prioritize and communicate cybersecurity risk, while ASVS is only useful as an assurance target when individual requirements are mapped to real implementation and tests rather than broad alignment language.",
      "residual_risk": "Current evidence does not establish enforced MFA for every Watchdog user even though ASVS v5.0.0-6.3.3 is Level 2. Re-authentication for sensitive account changes, active-session termination, provider-side session settings, recovery/account-linking behavior and the full OAuth/OIDC V10 mapping also remain incomplete.",
      "next_step": "Assess a no-cost MFA enforcement path, complete ASVS V10 mapping, verify production Supabase session/authentication settings, create the role-plan-resource authorization matrix, and add dynamic negative authorization tests."
    }
  ]
};
