import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.95.0";

const ENGINE="watchdog-semantic-context-v1";
const CONTRACT="watchdog-semantic-snapshot-v1";
const REGISTRY_URL="https://njpropertytaxrelief.com/property/data/marker-registry.json";
const PACKS:Record<string,{label:string;match:(m:any)=>boolean;max:number}>={
 identity:{label:"Property identity",max:20,match:(m:any)=>["property.address","property.municipality","property.county","property.block","property.lot","property.qualifier","property.pams_pin","property.property_class"].includes(String(m.id||""))},
 assessment_tax:{label:"Assessment and tax",max:55,match:(m:any)=>/(assessment|annual_tax|property_tax|tax_to_assessment|land_share|improvement_share|assessment_per_acre|effective_tax|equalization)/i.test(`${m.id} ${m.label} ${m.category}`)},
 sale_market:{label:"Sale and market context",max:55,match:(m:any)=>/(sale|market|sr1a|years_since_last_sale|price)/i.test(`${m.id} ${m.label} ${m.category}`)},
 appeal_uniformity:{label:"Appeal and uniformity",max:60,match:(m:any)=>/(appeal|uniformity|chapter.?123|cod_|common level|ratio)/i.test(`${m.id} ${m.label} ${m.category}`)},
 permits_closing:{label:"Permits and closing",max:70,match:(m:any)=>/(permit|closing|title|due.?diligence|certificate|deed_notice|preflight)/i.test(`${m.id} ${m.label} ${m.category}`)},
 environment_risk:{label:"Environmental and location constraints",max:70,match:(m:any)=>/(flood|wetland|tideland|environment|contamin|cea|cafra|highlands|pinelands|ust_|tidal)/i.test(`${m.id} ${m.label} ${m.category}`)},
 municipal_pressure:{label:"Municipal and tax pressure",max:55,match:(m:any)=>/(municipal|budget|tax_pressure|revaluation|levy|tax rate|fiscal)/i.test(`${m.id} ${m.label} ${m.category}`)},
 agent_opportunity:{label:"Agent property review",max:90,match:(m:any)=>/(assessment|sale|market|revaluation|permit|tax_pressure|appeal|uniformity|watchdog\.score|property_change)/i.test(`${m.id} ${m.label} ${m.category}`)}
};
let registryCache:any=null,registryAt=0;
const clean=(v:unknown,n=300)=>String(v??"").replace(/[<>]/g,"").trim().slice(0,n);
const env=(j:string,l:string)=>{const r=Deno.env.get(j)||"";if(r){try{const x=JSON.parse(r);if(x?.default)return String(x.default)}catch{}}return Deno.env.get(l)||""};
function origin(req:Request){const o=req.headers.get("origin")||"";if(["https://njpropertytaxrelief.com","https://www.njpropertytaxrelief.com","http://localhost:3000","http://127.0.0.1:3000"].includes(o))return o;if(/^https:\/\/njtaxrelief(?:-git)?-[a-z0-9-]+-johnscafides-projects\.vercel\.app$/i.test(o))return o;return"https://njpropertytaxrelief.com"}
const cors=(r:Request)=>({"Access-Control-Allow-Origin":origin(r),"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"});
const out=(r:Request,s:number,p:unknown)=>new Response(JSON.stringify(p),{status:s,headers:{...cors(r),"Content-Type":"application/json","Cache-Control":"private, no-store"}});
async function registry(){if(registryCache&&Date.now()-registryAt<3600000)return registryCache;const c=new AbortController(),t=setTimeout(()=>c.abort(),7000);try{const r=await fetch(REGISTRY_URL,{signal:c.signal,headers:{accept:"application/json"}});if(!r.ok)throw new Error(`registry ${r.status}`);const j=await r.json();if(!Array.isArray(j?.markers))throw new Error("registry malformed");registryCache=j;registryAt=Date.now();return j}finally{clearTimeout(t)}}
function markerPack(reg:any,names:string[]){const all=Array.isArray(reg?.markers)?reg.markers:[],selected:any[]=[],seen=new Set<string>(),manifest:any[]=[];for(const name of names){const p=PACKS[name];if(!p)continue;const hits=all.filter((m:any)=>["live","partial"].includes(String(m.provider_status||""))&&p.match(m)).slice(0,p.max);manifest.push({key:name,label:p.label,selected:hits.length});for(const m of hits){const id=String(m.id||"");if(id&&!seen.has(id)){seen.add(id);selected.push(m)}}}return{markers:selected.slice(0,250),manifest}}
function stable(v:any):any{if(Array.isArray(v))return v.map(stable);if(v&&typeof v==="object"){const o:any={};for(const k of Object.keys(v).sort())o[k]=stable(v[k]);return o}return v}
async function sha(value:any){const b=new TextEncoder().encode(JSON.stringify(stable(value))),h=await crypto.subtle.digest("SHA-256",b);return Array.from(new Uint8Array(h)).map(x=>x.toString(16).padStart(2,"0")).join("")}
function semanticMarker(def:any,value:any,meta:any){return{id:clean(def?.id,160),label:clean(def?.label,200),description:clean(def?.description,500),category:clean(def?.category,100),scope:clean(def?.scope,80),tier:clean(def?.tier,40),origin:clean(def?.origin,80),proprietary:Boolean(def?.proprietary),professions:Array.isArray(def?.professions)?def.professions.map((x:any)=>clean(x,60)):[],source_id:clean(def?.source_id,120)||null,field:clean(def?.field,120)||null,provider_status:clean(def?.provider_status,40)||null,provider_note:clean(def?.provider_note,300)||null,provider_contract:clean(def?.provider_contract,120)||null,value:value===undefined?null:value,state:clean(meta?.status||"provider_missing",80),source:clean(meta?.source,260)||null,provider_kind:clean(meta?.provider_kind,100)||null,observed_at:meta?.observed_at||null,checked_at:meta?.checked_at||null,model_version:meta?.model_version||null}}
Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});if(req.method!=="POST")return out(req,405,{error:"POST required"});const auth=req.headers.get("authorization")||"";if(!auth.startsWith("Bearer "))return out(req,401,{error:"Sign in required"});
 const url=Deno.env.get("SUPABASE_URL")||"",pub=env("SUPABASE_PUBLISHABLE_KEYS","SUPABASE_ANON_KEY");if(!url||!pub)return out(req,503,{error:"Semantic context configuration incomplete"});const uc=createClient(url,pub,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}}),{data:who}=await uc.auth.getUser();if(!who?.user)return out(req,401,{error:"Session invalid"});let body:any={};try{body=await req.json()}catch{return out(req,400,{error:"Invalid JSON"})}
 const pins=[...new Set((Array.isArray(body?.pams_pins)?body.pams_pins:[]).map((x:unknown)=>clean(x,120)).filter(Boolean))].slice(0,25) as string[];if(!pins.length)return out(req,400,{error:"pams_pins required"});const requested=[...new Set((Array.isArray(body?.packs)?body.packs:["identity","assessment_tax","sale_market"]).map((x:unknown)=>clean(x,80)).filter((x:string)=>PACKS[x]))] as string[];if(!requested.length)return out(req,400,{error:"No supported semantic packs selected",available_packs:Object.keys(PACKS)});
 let reg:any;try{reg=await registry()}catch(e){return out(req,503,{error:"Marker registry unavailable",detail:clean((e as any)?.message,200)})}const resolved=markerPack(reg,requested),markerIds=resolved.markers.map((m:any)=>m.id);const r=await fetch(`${url}/functions/v1/workbench-hydrate`,{method:"POST",headers:{Authorization:auth,apikey:pub,"Content-Type":"application/json"},body:JSON.stringify({pams_pins:pins,marker_ids:markerIds})}),data=await r.json().catch(()=>({}));if(!r.ok)return out(req,r.status,{error:"Governed hydration failed",detail:clean(data?.error||`HTTP ${r.status}`,300)});
 const defs=new Map(resolved.markers.map((m:any)=>[String(m.id),m])),records=Array.isArray(data?.records)?data.records:[],snapshots:any[]=[];for(const pin of pins){const rec=records.find((x:any)=>String(x.pams_pin)===pin)||{pams_pin:pin},vals=data?.markers?.[pin]||{},metas=data?.meta?.[pin]||{},items=markerIds.map((id:string)=>semanticMarker(defs.get(id),vals[id],metas[id])).filter((x:any)=>x.id),hashInput={pams_pin:pin,record:rec,markers:items.map((x:any)=>({id:x.id,value:x.value,state:x.state,observed_at:x.observed_at,checked_at:x.checked_at,model_version:x.model_version}))};snapshots.push({pams_pin:pin,address:rec.address||null,municipality:rec.town||null,county:rec.county||null,property_class:rec.prop_class||null,snapshot_hash:await sha(hashInput),available_count:items.filter((x:any)=>x.state==="available").length,missing_count:items.filter((x:any)=>x.state!=="available").length,record:rec,markers:items})}
 return out(req,200,{engine_version:ENGINE,contract_version:CONTRACT,registry_schema_version:reg?.schema_version||null,registry_generated_at:reg?.generated_at||null,registry_total_markers:Number(reg?.summary?.total||reg?.markers?.length||0),selected_marker_count:markerIds.length,packs:resolved.manifest,plan:data?.plan||null,provider_summary:data?.provider_summary||{},provider_versions:data?.provider_versions||{},checked_at:data?.checked_at||new Date().toISOString(),snapshots});
});
